/**
 * Lot 04b : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Auteurs : Djaïli Amadou Amal, Patrice Nganang, Hemley Boum, Achille Mbembe, Max Lobe, Werewere Liking, Francis Bebey.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string | null) => ({ role: "auteur" as const, name, authorSlug });

const AMAL = auteur("Djaïli Amadou Amal", "djaili-amadou-amal");
const BOUM = auteur("Hemley Boum", "hemley-boum");
const LOBE = auteur("Max Lobe", "max-lobe");
const MBEMBE = auteur("Achille Mbembe", "achille-mbembe");
const BEBEY = auteur("Francis Bebey", "francis-bebey");
const NGANANG = auteur("Patrice Nganang", "patrice-nganang");
const LIKING = auteur("Werewere Liking", "werewere-liking");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------ Djaïli Amadou Amal
  livre({
    slug: "walaande-l-art-de-partager-un-mari",
    title: "Walaande",
    subtitle: "L'art de partager un mari",
    contributors: [AMAL],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition"],
    summary:
      "À Maroua, dans l'Extrême-Nord du Cameroun, quatre épouses partagent la grande concession d'un riche commerçant peul. Chacune à son tour a ses nuits avec le mari et la charge de la maison : c'est le « walaande ». Aïssatou, mariée encore enfant, et ses coépouses racontent tour à tour leur quotidien fait de rivalités, de petites alliances et de rêves confisqués. Le premier roman de Djaïli Amadou Amal, nourri de sa propre vie, ouvre la porte d'un monde que l'on voit rarement de l'intérieur.",
    whyRead: [
      "Le premier roman de l'autrice des Impatientes, déjà sur la polygamie.",
      "Quatre voix de femmes qui disent ce qu'on tait d'habitude.",
      "Une plongée dans le quotidien d'une concession peule du Sahel.",
    ],
    year: 2010,
    publisher: "Ifrikiya",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "mistiriijo-la-mangeuse-d-ames",
    title: "Mistiriijo",
    subtitle: "La mangeuse d'âmes",
    contributors: [AMAL],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "tradition"],
    summary:
      "Dans un quartier de Maroua, le fils d'un notable tombe gravement malade. Très vite, les regards se tournent vers Goggo Aïssa, une Peule d'une soixantaine d'années : on l'accuse d'être une « mistiriijo », une sorcière qui dévore l'âme des autres. Le voisinage se divise et exige qu'elle se soumette à un rituel pour libérer l'enfant. Seule face à la rumeur, la vieille femme revit sa jeunesse au village, quand elle était la plus courtisée de toutes.",
    whyRead: [
      "Un roman fort sur la peur de la sorcellerie et ses victimes.",
      "Le portrait d'une femme âgée que la rumeur rejette.",
      "Le deuxième roman de Djaïli Amadou Amal, paru au Cameroun.",
    ],
    year: 2013,
    publisher: "Ifrikiya",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "coeur-du-sahel",
    title: "Cœur du Sahel",
    contributors: [AMAL],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "travail", "ville", "guerre"],
    summary:
      "Faydé a quinze ans quand elle quitte son village des monts du Nord-Cameroun, où la menace de Boko Haram pèse sur chaque famille. Pour faire vivre les siens, elle descend à Maroua et devient domestique, comme tant d'autres jeunes filles des campagnes. Dans les maisons des riches, elle découvre le mépris, l'injustice et la violence des hommes. Mais elle y trouve aussi l'amitié des autres servantes et le goût de la lecture, qui l'aident à tenir.",
    whyRead: [
      "Le monde des domestiques, vu enfin de leur côté.",
      "Une héroïne courageuse qu'on n'oublie pas.",
      "Un roman sur la fracture sociale au Sahel, sans misérabilisme.",
    ],
    year: 2022,
    publisher: "J'ai lu",
    pages: 285,
    isbn: "9782290376973",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-harem-du-roi",
    title: "Le Harem du roi",
    contributors: [AMAL],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "politique", "amour"],
    summary:
      "À Yaoundé, Boussoura, professeure de lettres, et Seini, médecin, forment un couple moderne et uni. Mais Seini est fils de roi : à la mort de son père, il est appelé à monter sur le trône d'un lamidat peul du Nord. Malgré les craintes de sa femme, il accepte, et le palais avec ses traditions, ses courtisans et son harem change peu à peu l'homme qu'elle aimait. Les voix du roi, de son épouse et des concubines se répondent pour dire ce que le pouvoir fait aux êtres.",
    whyRead: [
      "Une plongée rare dans la cour d'un lamido d'aujourd'hui.",
      "Un couple moderne mis à l'épreuve par le poids de la tradition.",
      "Plusieurs voix de femmes, enfermées mais jamais muettes.",
    ],
    year: 2024,
    publisher: "J'ai lu",
    pages: 280,
    isbn: "9782290415481",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------ Patrice Nganang
  livre({
    slug: "la-joie-de-vivre",
    title: "La Joie de vivre",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "politique", "ville", "histoire"],
    summary:
      "Mambo et Mboma sont jumeaux, et leur petite sœur Kemi se dit avec eux l'une de « faux triplés ». C'est elle qui raconte, en observatrice un peu à l'écart. Dès la naissance, une rivalité silencieuse et tenace oppose les deux frères. Au fil des années, l'histoire de cette famille se confond avec celle du Cameroun, dont la division semble se rejouer entre les jumeaux. Le tout porté par la langue des quartiers populaires, faite de rumeurs et d'anecdotes.",
    whyRead: [
      "Une saga familiale qui raconte tout un pays.",
      "La voix malicieuse d'une petite sœur narratrice.",
      "La langue vivante des quartiers populaires camerounais.",
    ],
    year: 2003,
    publisher: "Le Serpent à plumes",
    pages: 397,
    isbn: "9782842614393",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "l-invention-du-beau-regard",
    title: "L'Invention du beau regard",
    subtitle: "Contes citadins",
    contributors: [NGANANG],
    genre: "contes",
    audience: "adulte",
    themes: ["ville", "humour", "contes"],
    summary:
      "Dans les bars et les gargotes de Yaoundé, les « ambianceurs » racontent deux histoires. Dans la première, le commissaire Antoine Débonnaire Eloundou fait tout pour échapper à la retraite, jusqu'à ce que les crimes de son passé le rattrapent sous la forme d'une menace de mort. Dans la seconde, un pauvre bougre espère faire fortune grâce à une truie au regard étrange et aux pouvoirs redoutables. Deux contes urbains drôles et cruels, qui expliquent au passage d'où vient le « beau regard », nom donné à la viande grillée des rues.",
    whyRead: [
      "Deux contes urbains, entre humour noir et satire.",
      "Yaoundé racontée par ses bars et ses rues.",
      "Un livre court pour découvrir l'auteur de Temps de chien.",
    ],
    year: 2005,
    publisher: "Gallimard",
    pages: 195,
    isbn: "9782070772711",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "manifeste-d-une-nouvelle-litterature-africaine",
    title: "Manifeste d'une nouvelle littérature africaine",
    subtitle: "Pour une écriture préemptive",
    contributors: [NGANANG],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "genocide"],
    summary:
      "Que doit écrire la génération d'auteurs africains nés après les indépendances, qui a grandi avec les dictatures, l'exil et les massacres ? Pour Patrice Nganang, le génocide des Tutsi au Rwanda en 1994 marque une rupture : il ne suffit plus de raconter la tragédie après coup. Il appelle à une « écriture préemptive », qui la rende impensable avant qu'elle n'arrive. Un manifeste vif et exigeant, réédité avec un texte plus récent.",
    whyRead: [
      "Un manifeste qui interroge le rôle de l'écrivain africain.",
      "Une réflexion née du génocide des Tutsi au Rwanda.",
      "Pour comprendre le projet littéraire de Nganang.",
    ],
    year: 2007,
    publisher: "Presses universitaires de Limoges",
    pages: 225,
    isbn: "9782842877224",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-republique-de-l-imagination",
    title: "La République de l'imagination",
    subtitle: "Lettres au benjamin",
    contributors: [NGANANG],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "exil", "identite"],
    summary:
      "Patrice Nganang écrit cinq lettres à un « benjamin », un jeune Africain qui ne rêve plus que de partir en Occident. Après l'esclavage, la colonisation, les dictatures et la mondialisation sauvage, l'Afrique peut-elle encore imaginer son avenir ? L'auteur refuse le silence face à la tyrannie et invite le jeune homme à reprendre le pouvoir de rêver. Un petit livre de colère et d'espoir.",
    whyRead: [
      "Des lettres directes, adressées à la jeunesse africaine.",
      "Un plaidoyer pour le droit de rêver l'avenir.",
      "Un essai court, à lire d'une traite.",
    ],
    year: 2009,
    publisher: "Vents d'ailleurs",
    pages: 125,
    isbn: "9782911412639",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "mont-plaisant",
    title: "Mont Plaisant",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "colonisation", "femmes", "politique"],
    summary:
      "En 1931, Sara, neuf ans, est arrachée à sa mère et conduite à Mont Plaisant, un quartier de Yaoundé où les Français ont exilé le sultan Njoya, roi des Bamoun. Pour la protéger, la femme chargée de préparer les épouses du sultan la déguise en garçon. Sous ce nouveau nom, Sara observe une cour brillante et finissante, peuplée d'artistes, autour d'un roi inventeur d'un alphabet. Des décennies plus tard, une jeune étudiante revenue des États-Unis la retrouve, muette depuis longtemps, et tente de reconstituer son histoire.",
    whyRead: [
      "Le premier volet d'une grande trilogie sur l'histoire du Cameroun.",
      "La cour du sultan Njoya, roi bamoun et inventeur d'écriture.",
      "Mention spéciale du prix des Cinq continents de la Francophonie.",
    ],
    year: 2011,
    publisher: "Philippe Rey",
    pages: 506,
    isbn: "9782848761770",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-saison-des-prunes",
    title: "La Saison des prunes",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "histoire", "colonisation"],
    summary:
      "En 1940, la France vient d'être battue et le Cameroun se range derrière la France libre. À Edéa, le poète Louis-Marie Pouka fonde un cercle de jeunes poètes dans le bar du village, aux côtés de son ami Ruben Um Nyobè, futur chef indépendantiste. Mais l'arrivée de Leclerc change tout : le cercle devient un vivier de recrues, et les jeunes gens partent, mal équipés, vers le désert et la guerre. Au village, les femmes doivent affronter seules d'autres violences.",
    whyRead: [
      "L'histoire méconnue des tirailleurs camerounais de la France libre.",
      "Le deuxième volet de la trilogie ouverte par Mont Plaisant.",
      "Des figures réelles, comme Ruben Um Nyobè, devenues personnages.",
    ],
    year: 2013,
    publisher: "Philippe Rey",
    pages: 443,
    isbn: "9782848762883",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "empreintes-de-crabe",
    title: "Empreintes de crabe",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "independances", "famille", "exil"],
    summary:
      "Nithap, vieil infirmier de Bangwa, dans l'ouest du Cameroun, quitte son pays pour la première fois afin de rendre visite à son fils installé à New York. Tombé malade, il voit son séjour se prolonger, et son fils en profite pour enfin interroger ce père si secret. Nithap se met à raconter la guerre de l'indépendance en pays bamiléké, une guerre dont personne ne parle. Entre New York et les collines de l'Ouest, les époques se mêlent pour faire revivre une mémoire étouffée.",
    whyRead: [
      "Le dernier volet de la trilogie camerounaise de Nganang.",
      "Une guerre d'indépendance longtemps passée sous silence.",
      "Un père et un fils qui se parlent enfin.",
    ],
    year: 2018,
    publisher: "JC Lattès",
    pages: null,
    isbn: "9782709662499",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-revolte-anglophone",
    title: "La Révolte anglophone",
    subtitle: "Essais de liberté, de prison et d'exil",
    contributors: [NGANANG],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "guerre", "identite"],
    summary:
      "Depuis 2016, les régions anglophones du Cameroun, au nord-ouest et au sud-ouest, sont en guerre contre le pouvoir central. Patrice Nganang, arrêté puis expulsé du pays fin 2017, consacre à cette crise l'un des premiers livres en français. Il en retrace l'histoire, les enjeux de langue et les ressorts politiques. Il y mêle son expérience personnelle de prisonnier et d'exilé.",
    whyRead: [
      "Pour comprendre une guerre peu connue en France.",
      "Le témoignage d'un écrivain emprisonné puis expulsé.",
      "Un essai engagé, histoire et politique à la fois.",
    ],
    year: 2018,
    publisher: "Teham",
    pages: null,
    isbn: "9791090147317",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-recette-du-porc",
    title: "La Recette du porc",
    subtitle: "Essais sur l'amour-haine du Bamiléké",
    contributors: [NGANANG],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite"],
    summary:
      "Au Cameroun, les Bamiléké, peuple de l'Ouest, sont à la fois admirés et rejetés. Patrice Nganang, lui-même bamiléké, rassemble ici des textes écrits entre 2011 et 2019 sur ce tribalisme qui empoisonne la vie du pays. Il en démonte les clichés, les discours et les usages politiques. Un livre de combat contre la haine entre les communautés.",
    whyRead: [
      "Un regard rare sur le tribalisme au Cameroun.",
      "Des textes de combat, écrits sur près de dix ans.",
      "Pour mieux comprendre les tensions du pays aujourd'hui.",
    ],
    year: 2020,
    publisher: "Teham",
    pages: 520,
    isbn: "9791090147447",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "mboudjak",
    title: "Mboudjak",
    subtitle: "Ou les aventures du chien-philosophe",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "humour", "guerre", "enfance"],
    summary:
      "Le chien Mboudjak, héros de Temps de chien, est de retour à Yaoundé avec son maître Massa Yo. Depuis la cour où il vit, il observe les humains, des sous-quartiers aux collines chics, et comprend toutes leurs langues. Il est aussi le seul à saisir celle de Bello, une enfant marquée par la guerre qui ravage les régions anglophones. À travers son regard, c'est tout le Cameroun d'aujourd'hui qui se raconte.",
    whyRead: [
      "Le retour du chien-philosophe de Temps de chien.",
      "Un regard malicieux sur le Cameroun d'aujourd'hui.",
      "Une enfant blessée que seul un chien sait comprendre.",
    ],
    year: 2022,
    publisher: "Teham",
    pages: 380,
    isbn: "9791090147492",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "premier-president-noir-de-france",
    title: "Premier président noir de France",
    contributors: [NGANANG],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "identite", "exil"],
    summary:
      "Dans les années 2040, l'Afrique a changé de place dans le monde. Joe Nya, né au Cameroun et professeur à Berkeley, s'installe avec sa femme et son enfant à Tourtour, un village de Provence. Il espère y interviewer un voisin célèbre : le premier président noir de la République française. Reste à savoir quelles questions lui poser. Un court roman d'anticipation qui retourne les regards entre l'Afrique et la France.",
    whyRead: [
      "Un roman d'anticipation inattendu chez Nganang.",
      "La France vue depuis une Afrique devenue puissante.",
      "Un livre court et plein d'ironie.",
    ],
    year: 2022,
    publisher: "Teham",
    pages: null,
    isbn: "9791090147485",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------ Hemley Boum
  livre({
    slug: "le-clan-des-femmes",
    title: "Le Clan des femmes",
    contributors: [BOUM],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition"],
    summary:
      "Au début du XXe siècle, dans un village de savane encore à l'écart des bouleversements du continent, Sarah est mariée jeune, sans qu'on lui demande son avis. Elle entre dans une concession où vivent plusieurs épouses, avec leurs rivalités, leurs alliances et l'obligation de donner des enfants. Devenue vieille, elle raconte cette vie à sa petite-fille qui la questionne. Le premier roman d'Hemley Boum, inspiré des souvenirs de sa grand-mère, fait entendre la force tranquille des femmes.",
    whyRead: [
      "Le premier roman de l'autrice des Maquisards.",
      "Une grand-mère qui transmet son histoire à sa petite-fille.",
      "Un livre court qui dit la vie des coépouses avec justesse.",
    ],
    year: 2010,
    publisher: "L'Harmattan",
    pages: 137,
    isbn: "9782296128477",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "si-d-aimer",
    title: "Si d'aimer…",
    contributors: [BOUM],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "femmes", "ville"],
    summary:
      "À Douala, Salomé mène une vie de cadre brillante aux côtés de Pacôme, son mari si séduisant. Un examen de routine, au début d'une grossesse, lui apprend qu'elle est séropositive. Refusant d'y croire, elle rejette son mari et décide d'aller trouver Cécile, la femme que Pacôme a passionnément aimée avant elle. Plusieurs voix se relaient pour dire l'amour, la peur et le poids du silence autour du sida.",
    whyRead: [
      "Un roman courageux sur le sida dans la ville d'aujourd'hui.",
      "Des personnages complexes, sans juges ni coupables désignés.",
      "Le deuxième roman d'Hemley Boum, peu connu en France.",
    ],
    year: 2012,
    publisher: "La Cheminante",
    pages: 397,
    isbn: "9782917598696",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "les-jours-viennent-et-passent",
    title: "Les jours viennent et passent",
    contributors: [BOUM],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "histoire", "exil"],
    summary:
      "Anna, malade, est soignée par sa fille Abi, venue de France où elle est journaliste. Ce renversement des rôles rapproche les deux femmes et fait remonter leur passé : la jeunesse d'Anna, attirée par l'école des Blancs à l'époque coloniale, puis la vie d'Abi, entre Paris et le Cameroun. En parallèle, Tina, jeune voisine d'Anna, glisse peu à peu sous l'emprise d'un groupe islamiste. Trois générations de femmes racontent un siècle d'histoire camerounaise, des luttes d'indépendance à Boko Haram.",
    whyRead: [
      "Trois femmes, trois époques, un même pays en quête de lui-même.",
      "Prix Ahmadou-Kourouma 2020.",
      "Une mère et une fille qui se découvrent enfin.",
    ],
    year: 2019,
    publisher: "Folio",
    pages: 416,
    isbn: "9782073049377",
    format: "poche",
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2020 }],
  }),
  livre({
    slug: "le-reve-du-pecheur",
    title: "Le Rêve du pêcheur",
    contributors: [BOUM],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "identite", "travail"],
    summary:
      "Zack a quitté Douala à dix-huit ans, laissant derrière lui sa mère et ses secrets. Devenu psychologue à Paris, marié et père, il voit sa vie se fissurer quand son passé le rattrape. Des décennies plus tôt, son grand-père Zacharias vivait de la pêche à Campo, sur la côte camerounaise, jusqu'à l'arrivée d'une grande compagnie forestière qui bouleverse tout. Les deux récits s'entremêlent pour dire ce qu'une famille se transmet sans le savoir.",
    whyRead: [
      "Un grand roman sur les blessures qui passent d'une génération à l'autre.",
      "Prix des Cinq continents de la Francophonie 2025.",
      "Du village de pêcheurs au cabinet parisien, un récit ample et intime.",
    ],
    year: 2024,
    publisher: "Folio",
    pages: 395,
    isbn: "9782073096104",
    format: "poche",
    awards: [
      { name: "Prix Louis-Guilloux", year: 2024 },
      { name: "Prix des Cinq continents de la Francophonie", year: 2025 },
    ],
  }),

  // ------------------------------------------------------------ Max Lobe
  livre({
    slug: "39-rue-de-berne",
    title: "39, rue de Berne",
    contributors: [LOBE],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "famille", "humour"],
    summary:
      "Dipita grandit à Genève, dans le quartier des Pâquis, au 39 de la rue de Berne. Sa mère, arrivée du Cameroun à seize ans, a été livrée à un réseau de prostitution par des « bienfaiteurs » de la famille. Entouré des collègues de sa mère, qu'il appelle ses « mères », le garçon apprend la vie, découvre son homosexualité et se cherche une place. Max Lobe raconte avec humour et tendresse une enfance hors normes.",
    whyRead: [
      "Un narrateur attachant, drôle et lucide.",
      "Prix du Roman des Romands 2014.",
      "Les coulisses de Genève, loin des cartes postales.",
    ],
    year: 2013,
    publisher: "Zoé",
    pages: 238,
    isbn: "9782889070657",
    format: "poche",
    awards: [{ name: "Prix du Roman des Romands", year: 2014 }],
  }),
  livre({
    slug: "la-trinite-bantoue",
    title: "La Trinité bantoue",
    contributors: [LOBE],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "humour", "famille", "politique"],
    summary:
      "Mwána, jeune diplômé venu du « Bantouland », vit en Helvétie, un pays au cœur de l'Europe où une partie de la population veut chasser les « moutons noirs ». Il cherche du travail sans en trouver et compte chaque centime. Le jour où il dépense ses dernières pièces pour appeler sa mère restée au pays, il apprend qu'elle est gravement malade. Entre son ami Ruedi, l'énergique Madame Bauer et sa sœur très pieuse, il tient bon grâce à sa joie de vivre.",
    whyRead: [
      "Une satire tendre de la Suisse face aux étrangers.",
      "Prix de l'Académie romande 2015.",
      "Un héros qui garde le sourire malgré tout.",
    ],
    year: 2014,
    publisher: "Zoé",
    pages: null,
    isbn: null,
    format: "poche",
    awards: [{ name: "Prix de l'Académie romande", year: 2015 }],
  }),
  livre({
    slug: "loin-de-douala",
    title: "Loin de Douala",
    contributors: [LOBE],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "famille", "identite"],
    summary:
      "À Douala, Roger, le frère aîné, a disparu : pour fuir la colère de leur mère, il est parti tenter sa chance comme footballeur en Europe, en passant par le Nigeria. Jean, le narrateur, se lance à sa recherche avec son ami Simon. Les deux garçons remontent vers le nord du Cameroun, une région marquée par Boko Haram. Le voyage devient une traversée du pays et un apprentissage, entre fêtes, rencontres et premiers émois.",
    whyRead: [
      "Un road-movie à travers tout le Cameroun.",
      "Un roman d'apprentissage drôle et émouvant.",
      "Un regard neuf sur ceux qui rêvent d'Europe.",
    ],
    year: 2018,
    publisher: "Zoé",
    pages: 222,
    isbn: "9782889070640",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-promesse-de-sa-phall-excellence",
    title: "La Promesse de Sa Phall'Excellence",
    contributors: [LOBE],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "contes"],
    summary:
      "À Élobi, en République de Crevetterie, un pays qui ressemble beaucoup au Cameroun, la foule se presse au bar de l'oncle Godblessyou. Le conteur AcaDa-Writa y fait patienter tout le monde avec ses fables. On attend le « Grand Jour » où Sa Phall'Excellence viendra enfin partager les richesses du pays. En attendant, seuls passent ses collecteurs, venus prélever les cheveux des habitants pour la coiffure de Sa Royale Bien-Aimée.",
    whyRead: [
      "Une farce politique féroce et pleine d'invention.",
      "Une langue joyeuse qui mêle conte et satire.",
      "Un roman court, à lire comme une fable sur le pouvoir.",
    ],
    year: 2021,
    publisher: "Zoé",
    pages: 143,
    isbn: "9782889278220",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-danse-des-peres",
    title: "La Danse des pères",
    contributors: [LOBE],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "identite", "histoire", "exil"],
    summary:
      "À sa fenêtre, à Genève, Benjamin repense au salon de son enfance à Douala. Son père y racontait sans fin l'histoire du Cameroun : les dirigeants à la solde de l'étranger, le grand-père résistant, la lutte de l'UPC pour l'indépendance. Ce même père n'a jamais accepté l'homosexualité de son fils, tandis que sa mère lui tenait tête pour le protéger. Max Lobe mêle l'histoire d'un pays et celle d'une famille, dans une langue où se croisent bassa, pidgin et français de Suisse.",
    whyRead: [
      "Un fils face à un père qui raconte tout sauf l'essentiel.",
      "L'histoire du Cameroun vue depuis un salon familial.",
      "Une langue métissée, vive et musicale.",
    ],
    year: 2025,
    publisher: "Zoé",
    pages: 170,
    isbn: "9782889074648",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------ Achille Mbembe
  livre({
    slug: "le-politique-par-le-bas-en-afrique-noire",
    title: "Le Politique par le bas en Afrique noire",
    contributors: [auteur("Jean-François Bayart", null), MBEMBE, auteur("Comi Toulabor", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "histoire", "independances"],
    summary:
      "Qui fait vraiment la politique en Afrique ? Trois chercheurs, dont le jeune Achille Mbembe, répondent que ce ne sont pas seulement les présidents et les partis uniques. Leurs textes, écrits dans les années 1980, s'intéressent aux gens ordinaires : leurs façons de détourner l'autorité, de s'en moquer, de négocier avec elle au quotidien. Ils montrent que, même sous les régimes les plus autoritaires, la société pèse sur la formation de l'État. Un livre de référence, réédité et augmenté en 2008.",
    whyRead: [
      "Un livre fondateur pour comprendre le pouvoir en Afrique.",
      "Le regard porté sur les gens ordinaires plutôt que sur les chefs.",
      "Pour lire les premiers travaux d'Achille Mbembe.",
    ],
    year: 1992,
    publisher: "Karthala",
    pages: null,
    isbn: "9782811100193",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "de-la-postcolonie",
    title: "De la postcolonie",
    subtitle: "Essai sur l'imagination politique dans l'Afrique contemporaine",
    contributors: [MBEMBE],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "colonisation", "independances"],
    summary:
      "Que sont devenus les États africains nés de la colonisation ? Achille Mbembe les appelle « postcolonies » et décrit le style de pouvoir qui s'y est inventé : un commandement à la fois brutal, théâtral et grotesque, où dominants et dominés sont liés par d'étranges complicités. Il s'appuie autant sur l'histoire et la politique que sur les romans et la musique africaine pour saisir cette « esthétique de la vulgarité ». L'essai qui a fait connaître Mbembe dans le monde entier.",
    whyRead: [
      "L'essai qui a imposé Achille Mbembe comme un penseur majeur.",
      "Une lecture neuve du pouvoir africain, nourrie de romans et de musique.",
      "Un classique traduit et discuté dans le monde entier.",
    ],
    year: 2000,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782348057502",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "sortir-de-la-grande-nuit",
    title: "Sortir de la grande nuit",
    subtitle: "Essai sur l'Afrique décolonisée",
    contributors: [MBEMBE],
    genre: "essai",
    audience: "adulte",
    themes: ["independances", "colonisation", "identite", "exil"],
    summary:
      "Cinquante ans après les indépendances, Achille Mbembe se demande ce que la décolonisation a vraiment changé. Partant de son propre parcours, il montre une Afrique qui se réinvente par la circulation des personnes, des langues et des cultures. Il nomme « afropolitanisme » cette manière d'être africain et ouvert au monde. Il interroge aussi la France, qui a décolonisé sans jamais vraiment se défaire de son passé impérial.",
    whyRead: [
      "L'essai le plus accessible de Mbembe, écrit à la première personne.",
      "Pour découvrir l'idée d'« afropolitanisme ».",
      "Un regard sans complaisance sur la relation entre la France et l'Afrique.",
    ],
    year: 2010,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782707176646",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "politiques-de-l-inimitie",
    title: "Politiques de l'inimitié",
    contributors: [MBEMBE],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "guerre", "colonisation"],
    summary:
      "Notre époque a-t-elle besoin d'ennemis pour exister ? Achille Mbembe observe comment les démocraties, au nom de la sécurité, glissent vers l'état d'exception, le contrôle et le rejet de l'autre. Il relie ce mouvement à la longue histoire de la colonisation, de la plantation et des guerres de décolonisation. Frantz Fanon l'accompagne tout au long du livre. En conclusion, il esquisse une éthique du « passant », qui se sait de passage et partage le monde avec les autres.",
    whyRead: [
      "Un essai qui éclaire les peurs et les murs de notre temps.",
      "Une relecture vivante de Frantz Fanon.",
      "Un livre court et percutant, au format poche.",
    ],
    year: 2016,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782348040825",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "brutalisme",
    title: "Brutalisme",
    contributors: [MBEMBE],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite", "colonisation"],
    summary:
      "Achille Mbembe emprunte à l'architecture le mot « brutalisme » pour nommer notre époque : un temps où la force devient la seule vérité et où l'on veut tout transformer, la terre comme les corps, en matière et en énergie. Frontières, extractions, machines et virilisme dessinent un monde qui broie le vivant. Puisant dans les pensées africaines, il plaide pour réparer ce qui a été brisé et refonder une communauté humaine solidaire de toute la planète.",
    whyRead: [
      "Un essai ambitieux sur notre monde en crise.",
      "Des pensées africaines mises au service de l'avenir de la planète.",
      "Pour prolonger la Critique de la raison nègre.",
    ],
    year: 2020,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782348078057",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "pour-un-monde-en-commun",
    title: "Pour un monde en commun",
    subtitle: "Regards croisés entre l'Afrique et l'Europe",
    contributors: [MBEMBE, auteur("Rémy Rioux", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "colonisation", "histoire"],
    summary:
      "Un penseur camerounais et le directeur de l'Agence française de développement dialoguent, sous la conduite de la journaliste Séverine Kodjo-Grandvaux. Achille Mbembe et Rémy Rioux confrontent leurs regards sur le poids de l'histoire coloniale entre l'Afrique et l'Europe. Ils parlent aussi de mondialisation, de crise écologique et de ce que pourrait être une politique soucieuse du vivant. Un échange franc entre deux continents qui doivent apprendre à se parler autrement.",
    whyRead: [
      "Un dialogue vivant entre deux points de vue très différents.",
      "Pour réfléchir à l'avenir des relations entre la France et l'Afrique.",
      "Un livre court, qui rend la pensée de Mbembe accessible.",
    ],
    year: 2022,
    publisher: "Actes Sud",
    pages: null,
    isbn: "9782330162177",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-communaute-terrestre",
    title: "La Communauté terrestre",
    contributors: [MBEMBE],
    genre: "essai",
    audience: "adulte",
    themes: ["spiritualite", "politique", "identite"],
    summary:
      "Et si la Terre était notre dernière utopie ? Achille Mbembe la pense comme une immense chaîne du vivant, où humains, animaux, plantes, minéraux et machines sont liés, et où les pensées animistes africaines ajoutent les esprits et les masques. Face à la prise des terres et à l'épuisement de la planète, il défend un rapport au monde fait de partage plutôt que de propriété. Nous n'en serions que les habitants de passage.",
    whyRead: [
      "Un essai de Mbembe sur l'écologie et l'avenir du vivant.",
      "Les pensées africaines au cœur des grandes questions d'aujourd'hui.",
      "Une réflexion stimulante, désormais en poche.",
    ],
    year: 2023,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782348092756",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------ Werewere Liking
  livre({
    slug: "la-puissance-de-um",
    title: "La Puissance de Um",
    contributors: [LIKING],
    genre: "theatre",
    audience: "adulte",
    themes: ["tradition", "politique", "femmes", "spiritualite"],
    summary:
      "Dans un village bassa, Ntep Iliga vient de mourir et sa veuve, Ngond Libii, prépare le deuil en chantant. Mais la cérémonie prend un tour inattendu : elle déclare avoir tué son mari et interdit qu'on le pleure. Le village exige d'abord qu'on raconte la vie du défunt, et ce procès à moitié comique révèle peu à peu un homme de pouvoir pris entre l'Occident et son peuple. Une pièce en un acte où le rituel funéraire devient satire politique.",
    whyRead: [
      "Le théâtre-rituel de Werewere Liking à ses débuts.",
      "Un deuil qui tourne au procès, entre rire et gravité.",
      "Une satire du néocolonialisme portée par la déesse bassa Um.",
    ],
    year: 1979,
    publisher: "CEDA",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "du-rituel-a-la-scene-chez-les-bassa-du-cameroun",
    title: "Du rituel à la scène chez les Bassa du Cameroun",
    contributors: [auteur("Marie-José Hourantier", null), LIKING, auteur("Jacques Scherer", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["tradition", "spiritualite", "contes"],
    summary:
      "Comment passer d'un rituel de village à une pièce de théâtre ? Werewere Liking, la metteuse en scène Marie-José Hourantier et l'universitaire Jacques Scherer réunissent des textes de rituels bassa du Cameroun, dont un rite de guérison, et les présentent. Le volume contient aussi une pièce de Liking, « La Queue du diable », qui montre ce que la scène moderne peut tirer de ces cérémonies. Un livre-manifeste du théâtre-rituel que Liking développera ensuite à Abidjan.",
    whyRead: [
      "Aux sources du théâtre-rituel de Werewere Liking.",
      "Des rituels bassa présentés et transmis par écrit.",
      "Contient une pièce de Liking, « La Queue du diable ».",
    ],
    year: 1979,
    publisher: "Nizet",
    pages: 135,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "orphee-dafric",
    title: "Orphée-Dafric",
    contributors: [LIKING, auteur("Manuna Ma Njock", null)],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "contes", "spiritualite", "tradition"],
    summary:
      "Orphée et Nyango s'aiment, mais leurs familles s'opposent à leur mariage. Pour être unis, ils doivent passer l'épreuve de la pirogue et traverser la Rivière Blanche. Quand la pirogue chavire et que Nyango disparaît, Orphée refuse de croire à sa mort et part la chercher dans l'autre monde. Werewere Liking mêle le mythe grec d'Orphée à un rite initiatique bassa ; le volume est suivi d'« Orphée d'Afrique », théâtre-rituel de Manuna Ma Njock.",
    whyRead: [
      "Le mythe d'Orphée réinventé au cœur de l'Afrique.",
      "Un premier roman court, poétique et initiatique.",
      "Deux regards, roman et théâtre, sur un même mythe.",
    ],
    year: 1981,
    publisher: "L'Harmattan",
    pages: 122,
    isbn: "9782858022083",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "elle-sera-de-jaspe-et-de-corail",
    title: "Elle sera de jaspe et de corail",
    subtitle: "Journal d'une misovire",
    contributors: [LIKING],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "identite", "spiritualite"],
    summary:
      "À Lunaï, un village africain imaginaire qui s'enfonce dans le désespoir, une femme tient son journal. Elle se dit « misovire » : elle ne trouve aucun homme digne de son estime. Autour d'elle, deux hommes, Grozi et Babou, se disputent sans fin, tandis qu'une voix prophétique, Nuit-Noire, la guide vers l'annonce d'une humanité nouvelle. Mêlant journal, dialogues, chants et prières, ce « chant-roman » invente une forme littéraire à part.",
    whyRead: [
      "Un livre inclassable, entre roman, poème et chant.",
      "Une voix de femme libre, ironique et visionnaire.",
      "Traduit en anglais, souvent étudié dans le monde entier.",
    ],
    year: 1983,
    publisher: "L'Harmattan",
    pages: 156,
    isbn: "9782858023295",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "l-amour-cent-vies",
    title: "L'Amour-cent-vies",
    contributors: [LIKING],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "famille", "spiritualite", "histoire"],
    summary:
      "Lem Liam Mianga est devenu un artiste célèbre, mais il n'a aimé qu'une femme dans sa vie : Madjo, sa grand-mère paternelle. Jeune, lâche et tenté d'en finir, il avait été retenu par elle, qui ne l'a pas sermonné mais lui a raconté la vie des grandes figures africaines. Le roman joue avec l'idée de réincarnation et de vies multiples, et fait de la parole des aînés une force qui sauve. Un « roman-chant » où se mêlent récit, poésie et légende.",
    whyRead: [
      "Un lien unique entre un petit-fils et sa grand-mère.",
      "Les héros africains racontés comme des leçons de vie.",
      "L'écriture-chant si particulière de Werewere Liking.",
    ],
    year: 1988,
    publisher: "Publisud",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "singue-mura",
    title: "Singuè Mura",
    subtitle: "Considérant que la femme…",
    contributors: [LIKING],
    genre: "theatre",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition"],
    summary:
      "Singuè Mura a tout réussi : postes prestigieux, écoles et dispensaires construits, nombreux enfants adoptés. Mais elle n'a pas donné d'enfant à son mari. Sa belle-mère, qui comptait tout sur sa descendance, la soupçonne de sorcellerie et fait entrer une femme plus jeune dans le couple. Cette pièce, créée par la compagnie Ki-Yi M'Bock, oppose la femme qui crée à celle qu'on réduit à donner la vie.",
    whyRead: [
      "Une pièce forte sur la pression faite aux femmes sans enfant.",
      "Un spectacle de la compagnie Ki-Yi M'Bock, fondée par Liking.",
      "La tradition et la modernité face à face dans un couple.",
    ],
    year: 1990,
    publisher: "Eyo Ki-Yi",
    pages: 55,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "un-touareg-s-est-marie-a-une-pygmee",
    title: "Un Touareg s'est marié à une Pygmée",
    subtitle: "Épopée m'vet pour une Afrique présente",
    contributors: [LIKING],
    genre: "theatre",
    audience: "adulte",
    themes: ["identite", "histoire", "contes"],
    summary:
      "Un Touareg part à la recherche de l'eau, source de toute survie, et traverse une grande partie du continent, du désert à la forêt et jusqu'à la mer. En ouverture, la Terre-Mère, dont le corps figure l'Afrique, subit une douloureuse métamorphose. Inspirée du mvet, l'épopée chantée d'Afrique centrale, la pièce fait entendre des chants dans une dizaine de langues africaines. C'est à la fois un spectacle musical et une leçon d'histoire et de géographie du continent.",
    whyRead: [
      "Une épopée chantée qui traverse toute l'Afrique.",
      "Des chants en une dizaine de langues africaines.",
      "Un spectacle créé avec le musicien Ray Lema.",
    ],
    year: 1992,
    publisher: "Lansman",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------ Francis Bebey
  livre({
    slug: "trois-petits-cireurs",
    title: "Trois petits cireurs",
    contributors: [BEBEY],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "travail", "ville"],
    summary:
      "Mamou, Abel et Nyassa sont trois jeunes cireurs de chaussures qui travaillent ensemble devant les grands hôtels de la ville. Chaque soir, malgré leurs disputes, ils partagent leurs gains en parts égales. Mamou, quinze ans, n'est jamais allé à l'école : c'est lui qui fait vivre sa famille, car son père aveugle ne peut que tresser des cordes. Francis Bebey raconte avec tendresse l'amitié et le courage de ces enfants obligés de grandir trop vite.",
    whyRead: [
      "Une belle histoire d'amitié entre trois enfants des rues.",
      "Un court roman pour les jeunes lecteurs, plein de dignité.",
      "Par l'auteur du Fils d'Agatha Moudio.",
    ],
    year: 1972,
    publisher: "CLÉ",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-poupee-ashanti",
    title: "La Poupée ashanti",
    contributors: [BEBEY],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "femmes", "politique", "independances"],
    summary:
      "À Accra, quelques années après l'indépendance du Ghana, Edna a grandi au marché auprès de sa grand-mère Mam, l'une des grandes commerçantes de la ville. Belle et sans instruction, elle tombe amoureuse de Spio, un jeune fonctionnaire qui la surnomme « ma poupée ashanti ». Leur amour doit compter avec les différences sociales, les jalousies et le poids des traditions. Pendant ce temps, les femmes du marché se dressent contre un gouvernement qui distribue ses faveurs à ses proches.",
    whyRead: [
      "Une histoire d'amour pleine de charme dans le Ghana des indépendances.",
      "Les femmes du marché, puissantes et frondeuses.",
      "L'humour tendre de Francis Bebey.",
    ],
    year: 1973,
    publisher: "CLÉ",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-roi-albert-d-effidi",
    title: "Le Roi Albert d'Effidi",
    contributors: [BEBEY],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "tradition", "colonisation", "amour"],
    summary:
      "À Effidi, petite ville du Cameroun colonial au bord d'une route neuve, Albert tient la seule boutique appartenant à un Africain. Veuf, ancien combattant, il se donne des airs de roi et décide d'épouser la jeune Nani. Mais il trouve sur son chemin Bikounou, fonctionnaire deux fois plus jeune que lui, qui parade sur sa Vespa et convoite la même fiancée. Entre rivalité amoureuse, querelles de village et premières élections, Francis Bebey dresse une comédie pleine de malice.",
    whyRead: [
      "Une comédie villageoise savoureuse et pleine de malice.",
      "Le choc des anciens et des jeunes à la fin de l'époque coloniale.",
      "Un héros vaniteux qu'on finit par aimer.",
    ],
    year: 1976,
    publisher: "CLÉ",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-ministre-et-le-griot",
    title: "Le Ministre et le Griot",
    contributors: [BEBEY],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "politique", "tradition"],
    summary:
      "Dans un pays d'Afrique imaginaire, Kéita, ministre des Finances, prépare ses fiançailles. Sa mère, Binta Madiallo, refuse d'y inviter le Premier ministre, pourtant le meilleur ami de son fils : il descend d'une famille de griots, et la tradition interdit de les recevoir à sa table. Elle reproche aussi à Kéita de s'être trop éloigné des usages. L'incident familial devient vite une affaire d'État, que Francis Bebey raconte avec humour.",
    whyRead: [
      "Une satire drôle du pouvoir et des castes.",
      "Une mère de ministre inoubliable.",
      "Un roman court et vif, disponible en poche.",
    ],
    year: 1992,
    publisher: "Sépia",
    pages: 184,
    isbn: "9782842801397",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-enfant-pluie",
    title: "L'Enfant-pluie",
    contributors: [BEBEY],
    genre: "roman",
    audience: "jeunesse",
    themes: ["enfance", "famille", "tradition", "ecole"],
    summary:
      "Mwana est un petit garçon pressé de grandir, qui vit auprès de sa grand-mère Iyo, au Cameroun. Il la harcèle de questions, naïves ou profondes, et elle lui répond par des images : le temps qui passe ressemble à l'eau du fleuve. Au fil des jours, l'enfant tente des expériences interdites, découvre l'école et un monde qui l'attire autant qu'il l'effraie. Un récit plein d'humour et de tendresse sur l'enfance et la transmission.",
    whyRead: [
      "Un duo grand-mère et petit-fils très attachant.",
      "Une sagesse simple, à partager dès 11 ans.",
      "Le dernier roman de Francis Bebey, tendre et drôle.",
    ],
    year: 1994,
    publisher: "Sépia",
    pages: 155,
    isbn: "9782842801380",
    format: "poche",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = ["walaande-l-art-de-partager-un-mari", "mistiriijo-la-mangeuse-d-ames", "coeur-du-sahel", "le-harem-du-roi", "la-joie-de-vivre", "l-invention-du-beau-regard", "manifeste-d-une-nouvelle-litterature-africaine", "la-republique-de-l-imagination", "mont-plaisant", "la-saison-des-prunes", "empreintes-de-crabe", "la-revolte-anglophone", "la-recette-du-porc", "mboudjak", "premier-president-noir-de-france", "le-clan-des-femmes", "si-d-aimer", "les-jours-viennent-et-passent", "le-reve-du-pecheur", "39-rue-de-berne", "la-trinite-bantoue", "loin-de-douala", "la-promesse-de-sa-phall-excellence", "la-danse-des-peres", "le-politique-par-le-bas-en-afrique-noire", "de-la-postcolonie", "sortir-de-la-grande-nuit", "politiques-de-l-inimitie", "brutalisme", "pour-un-monde-en-commun", "la-communaute-terrestre", "la-puissance-de-um", "du-rituel-a-la-scene-chez-les-bassa-du-cameroun", "orphee-dafric", "elle-sera-de-jaspe-et-de-corail", "l-amour-cent-vies", "singue-mura", "un-touareg-s-est-marie-a-une-pygmee", "trois-petits-cireurs", "la-poupee-ashanti", "le-roi-albert-d-effidi", "le-ministre-et-le-griot", "l-enfant-pluie"];
