/**
 * Lot 04 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Cameroun : Mongo Beti, Ferdinand Oyono, Calixthe Beyala, Léonora Miano.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string | null) => ({ role: "auteur" as const, name, authorSlug });
const beti = auteur("Mongo Beti", "mongo-beti");
const oyono = auteur("Ferdinand Oyono", "ferdinand-oyono");
const beyala = auteur("Calixthe Beyala", "calixthe-beyala");
const miano = auteur("Léonora Miano", "leonora-miano");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Mongo Beti
  livre({
    slug: "ville-cruelle",
    title: "Ville cruelle",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "ville", "travail"],
    summary:
      "Banda, jeune paysan du sud du Cameroun, porte sa récolte de cacao à Tanga, la ville coloniale où se font les affaires. Il compte sur cette vente pour payer la dot de sa fiancée et offrir à sa mère malade un peu de repos. Mais à Tanga, les contrôleurs, les commerçants grecs et les policiers font la loi, et le travail de toute une saison peut s'envoler en une matinée. Une rencontre imprévue entraîne Banda dans une course à travers les quartiers indigènes de la ville. Mongo Beti signait ce premier roman sous le nom d'Eza Boto.",
    whyRead: [
      "Le tout premier roman de Mongo Beti, paru sous le pseudonyme d'Eza Boto.",
      "La ville coloniale vue par un jeune paysan, avec ses pièges et ses injustices.",
      "Un récit court et vif, idéal pour découvrir l'auteur.",
    ],
    year: 1954,
    publisher: "Présence africaine",
    pages: 223,
    isbn: "9782708702622",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "mission-terminee",
    title: "Mission terminée",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["tradition", "humour", "colonisation", "ecole"],
    summary:
      "Recalé au baccalauréat, Jean-Marie Medza rentre à contrecœur dans son village du Cameroun des années 1950. On lui confie aussitôt une mission : aller à Kala, un village de brousse, ramener l'épouse de son cousin, partie avec un autre homme. Sur place, le jeune « savant » de la ville est fêté, interrogé, admiré, et découvre un monde de liberté qu'il ignorait. Mongo Beti en tire une comédie pleine de malice sur l'école coloniale et ce qu'elle fait aux jeunes Africains.",
    whyRead: [
      "Un roman drôle et tendre sur un jeune diplômé perdu entre deux mondes.",
      "Prix Sainte-Beuve 1958.",
      "Une satire légère de l'école coloniale et de ses « évolués ».",
    ],
    year: 1957,
    publisher: "Éditions des Peuples noirs",
    pages: 223,
    isbn: "9782864410119",
    format: null,
    awards: [{ name: "Prix Sainte-Beuve", year: 1958 }],
  }),
  livre({
    slug: "le-roi-miracule",
    title: "Le Roi miraculé",
    subtitle: "Chronique des Essazam",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "colonisation", "tradition", "humour"],
    summary:
      "En 1948, Essomba Mendouga, chef des Essazam et polygame aux vingt-trois épouses, semble à l'article de la mort. Contre toute attente, il se rétablit, et le père Le Guen, missionnaire zélé, crie au miracle. Le chef décide alors de se convertir au christianisme, ce qui l'oblige à renvoyer presque toutes ses femmes. Toute la tribu s'agite, les clans s'inquiètent, et l'administration coloniale voit d'un mauvais œil ce désordre. Mongo Beti en fait une farce mordante sur la rencontre entre l'Église, le pouvoir colonial et la tradition.",
    whyRead: [
      "Une comédie de mœurs où un baptême met tout un peuple sens dessus dessous.",
      "Un regard ironique sur les missions catholiques en Afrique.",
      "Le dernier volet des romans coloniaux de Mongo Beti.",
    ],
    year: 1958,
    publisher: "Éditions des Peuples noirs",
    pages: 203,
    isbn: "9782864410126",
    format: null,
    awards: [],
  }),
  livre({
    slug: "main-basse-sur-le-cameroun",
    title: "Main basse sur le Cameroun",
    subtitle: "Autopsie d'une décolonisation",
    contributors: [beti],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "independances", "histoire"],
    summary:
      "Au début des années 1970, le procès de Yaoundé condamne à mort des militants de l'UPC, le parti qui s'était battu pour une vraie indépendance du Cameroun. Mongo Beti, alors professeur en France, prend la plume pour raconter comment ce mouvement a été écarté du pouvoir au profit d'un régime soutenu par Paris. Il s'en prend aussi à la presse française, qui relaie selon lui la version officielle sans recul. Interdit en France dès sa sortie, le livre n'a pu circuler librement qu'après plusieurs années de procédure.",
    whyRead: [
      "Un pamphlet qui fut saisi et interdit en France à sa parution.",
      "Pour comprendre l'histoire cachée de l'indépendance camerounaise.",
      "Une plume de romancier au service du combat politique.",
    ],
    year: 1972,
    publisher: "La Découverte",
    pages: 251,
    isbn: "9782707159366",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "perpetue-et-l-habitude-du-malheur",
    title: "Perpétue et l'habitude du malheur",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "politique", "famille", "independances"],
    summary:
      "À la fin des années 1960, Essola sort de six ans de camp, où l'avait envoyé son opposition à la dictature de Baba Toura. De retour chez lui, il apprend que sa jeune sœur Perpétue est morte pendant son absence. Il décide de refaire le chemin de sa vie : son mariage arrangé, son mari ambitieux, les années difficiles dans une petite ville du pays. Son enquête dessine peu à peu le portrait d'une société où les femmes paient le prix fort d'une indépendance confisquée.",
    whyRead: [
      "Une enquête bouleversante sur le destin d'une jeune femme.",
      "Un roman qui dénonce à la fois la dictature et le sort réservé aux femmes.",
      "Souvent cité parmi les chefs-d'œuvre de Mongo Beti.",
    ],
    year: 1974,
    publisher: "Éditions des Peuples noirs",
    pages: 272,
    isbn: "9782864410133",
    format: null,
    awards: [],
  }),
  livre({
    slug: "remember-ruben",
    title: "Remember Ruben",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "politique", "ville", "histoire"],
    summary:
      "Mor-Zamba arrive enfant à Ekoumdoum, sans famille ni origine connue, et le village a bien du mal à l'accepter. Raflé un jour par l'administration coloniale, il découvre Fort-Nègre, la grande ville des Blancs, et Kola-Kola, l'immense quartier africain où grandit la révolte. Il y croise le chemin d'Abena, ami d'enfance devenu militant, et des partisans de Ruben, le chef du mouvement pour l'indépendance. Une vaste fresque inspirée de la lutte de Ruben Um Nyobè et de l'UPC.",
    whyRead: [
      "Une grande fresque sur les luttes pour l'indépendance du Cameroun.",
      "Un roman d'apprentissage porté par un héros attachant.",
      "Le premier volet d'un cycle que poursuit La Ruine presque cocasse d'un polichinelle.",
    ],
    year: 1974,
    publisher: "Éditions des Peuples noirs",
    pages: 351,
    isbn: "9782864410171",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-ruine-presque-cocasse-d-un-polichinelle",
    title: "La Ruine presque cocasse d'un polichinelle",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "independances"],
    summary:
      "Quelques années après les événements de Remember Ruben, Mor-Zamba et Abena reprennent la route d'Ekoumdoum. Le village est désormais tenu par un chef imposé par l'administration et soutenu par les missionnaires, un véritable pantin qui se croit tout permis. Les deux compagnons, rejoints par un jeune garçon débrouillard, veulent rendre le village à ses habitants. Mongo Beti mêle l'aventure, la comédie et la colère pour raconter le réveil d'une communauté.",
    whyRead: [
      "La suite de Remember Ruben, plus enlevée et souvent très drôle.",
      "Un roman de révolte où les femmes jouent un rôle décisif.",
      "Une satire réjouissante des petits tyrans locaux.",
    ],
    year: 1979,
    publisher: "Le Serpent à plumes",
    pages: 493,
    isbn: "9782842614331",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-deux-meres-de-guillaume-ismael-dzewatama",
    title: "Les Deux Mères de Guillaume Ismaël Dzewatama, futur camionneur",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "politique", "independances", "identite"],
    summary:
      "Dans une république d'Afrique équatoriale récemment indépendante, le père de Guillaume Ismaël, ancien étudiant militant à Lyon, est devenu haut magistrat du régime. Il a répudié la mère du garçon et ramené de France une jeune épouse française. Contre toute attente, l'adolescent et sa belle-mère deviennent complices. En découvrant le pays, la jeune femme mesure l'écart entre la misère du peuple et le luxe de la classe dirigeante, et le malaise grandit dans le couple.",
    whyRead: [
      "Une famille déchirée entre deux mères et deux continents.",
      "Un regard acide sur les anciens opposants ralliés à la dictature.",
      "Un roman à la fois burlesque et grave.",
    ],
    year: 1983,
    publisher: "Éditions des Peuples noirs",
    pages: 193,
    isbn: "9782864410157",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-revanche-de-guillaume-ismael-dzewatama",
    title: "La Revanche de Guillaume Ismaël Dzewatama",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "politique", "exil"],
    summary:
      "Le père de Guillaume Ismaël a été emprisonné après un coup d'État manqué, et la famille se retrouve brusquement dans la gêne. La belle-mère française du garçon fait face avec courage : elle découvre la vie du bidonville, puis celle d'un village bousculé par les changements du pays. Bientôt, elle part en France pour alerter l'opinion sur le sort de son mari, et Guillaume l'accompagne. La suite des Deux Mères de Guillaume Ismaël Dzewatama.",
    whyRead: [
      "La suite et la fin des aventures de Guillaume Ismaël.",
      "Une héroïne française qui ouvre les yeux sur la dictature.",
      "Un récit qui fait voyager du bidonville à Paris.",
    ],
    year: 1984,
    publisher: "Éditions des Peuples noirs",
    pages: 220,
    isbn: "9782864410164",
    format: null,
    awards: [],
  }),
  livre({
    slug: "lettre-ouverte-aux-camerounais",
    title: "Lettre ouverte aux Camerounais",
    subtitle: "ou la deuxième mort de Ruben Um Nyobè",
    contributors: [beti],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "histoire", "independances"],
    summary:
      "Depuis son exil, Mongo Beti s'adresse directement à ses compatriotes, au milieu des années 1980. Il rappelle la figure de Ruben Um Nyobè, le leader indépendantiste tué en 1958, et accuse le pouvoir de vouloir effacer sa mémoire une seconde fois. Le livre est un appel à ne pas se résigner et à reprendre en main l'histoire du pays. Un texte court et direct, publié par les éditions de sa propre revue.",
    whyRead: [
      "Un pamphlet bref et ardent, écrit depuis l'exil.",
      "Pour comprendre la place de Ruben Um Nyobè dans la mémoire camerounaise.",
      "Mongo Beti dans son rôle d'intellectuel engagé.",
    ],
    year: 1986,
    publisher: "Éditions des Peuples noirs",
    pages: 131,
    isbn: "9782864410065",
    format: null,
    awards: [],
  }),
  livre({
    slug: "dictionnaire-de-la-negritude",
    title: "Dictionnaire de la négritude",
    contributors: [beti, auteur("Odile Tobner", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "colonisation", "histoire"],
    summary:
      "Mongo Beti et Odile Tobner, sa compagne, rassemblent dans ce dictionnaire des notices sur des personnes, des idées, des événements et des mots liés à l'histoire des peuples noirs. Ils l'ont conçu en réaction aux images que le discours occidental donne des Africains, de la traite à la décolonisation. Plusieurs collaborateurs de leur revue Peuples noirs, peuples africains y ont participé. Un ouvrage de combat autant que de référence.",
    whyRead: [
      "Un dictionnaire engagé, écrit à quatre mains par un couple d'écrivains.",
      "Une autre manière d'aborder l'histoire des peuples noirs.",
      "Un livre à feuilleter, au fil des curiosités.",
    ],
    year: 1989,
    publisher: "L'Harmattan",
    pages: 245,
    isbn: "9782738404947",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-france-contre-l-afrique",
    title: "La France contre l'Afrique",
    subtitle: "Retour au Cameroun",
    contributors: [beti],
    genre: "essai",
    audience: "adulte",
    themes: ["exil", "politique", "identite"],
    summary:
      "En 1991, après plus de trente ans d'exil, Mongo Beti remet le pied au Cameroun. Il raconte ses retrouvailles avec son pays : les routes, les villes, les villages, les gens qu'il rencontre, mais aussi le délabrement et la peur. Au fil du récit, il analyse le rôle de la France dans le maintien des régimes africains qu'il combat. Un livre à mi-chemin entre carnet de voyage et réquisitoire.",
    whyRead: [
      "Le récit d'un retour au pays après trente ans d'exil.",
      "Un témoignage précieux sur le Cameroun du début des années 1990.",
      "Un essai vif sur les relations entre la France et l'Afrique.",
    ],
    year: 1993,
    publisher: "La Découverte",
    pages: 218,
    isbn: "9782707149787",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-histoire-du-fou",
    title: "L'Histoire du fou",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "famille", "humour"],
    summary:
      "Le vieux chef Zoaételeu a toujours su s'arranger avec les puissants, au point de servir deux régimes dictatoriaux successifs. Ses fils Zoaétoa et Narcisse, ses préférés, l'entraînent malgré lui au cœur des luttes politiques de leur pays africain. Arrestations, trahisons et complots s'enchaînent, et la fortune de la famille vacille. Mongo Beti raconte cette chute comme une fable moderne, à la fois comique et terrible.",
    whyRead: [
      "Une fable politique grinçante sur l'Afrique des dictatures.",
      "Un vieux chef roublard pris à son propre piège.",
      "Le premier roman publié par Mongo Beti après son retour au Cameroun.",
    ],
    year: 1994,
    publisher: "Julliard",
    pages: 212,
    isbn: "9782260010999",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "trop-de-soleil-tue-l-amour",
    title: "Trop de soleil tue l'amour",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "politique", "humour", "amour"],
    summary:
      "Zam, journaliste politique dans une capitale africaine, ne se remet pas d'une chose : on lui a volé sa collection de disques de jazz. Peu après, on vient lui annoncer qu'un cadavre se trouve dans son appartement. Entre son amie Bébète, son patron et un avocat porté sur la bouteille, Eddie, il se retrouve pris dans une affaire qui le dépasse. Mongo Beti s'empare des codes du roman policier pour peindre une société gangrenée par la corruption.",
    whyRead: [
      "Un polar tropical plein d'humour et de jazz.",
      "Une satire féroce d'un pays où tout s'achète.",
      "Un Mongo Beti inattendu, léger en apparence seulement.",
    ],
    year: 1999,
    publisher: "Pocket",
    pages: 250,
    isbn: "9782266101912",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "branle-bas-en-noir-et-blanc",
    title: "Branle-bas en noir et blanc",
    contributors: [beti],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "politique", "humour"],
    summary:
      "On retrouve Eddie, l'avocat déchu et grand amateur d'alcool croisé dans Trop de soleil tue l'amour, reconverti en détective privé. Son enquête le conduit à travers toutes les couches d'une société africaine où chacun improvise pour survivre. Policiers, notables, Européens de passage et petites gens composent une comédie humaine pleine de bruit. Mongo Beti y déploie une langue foisonnante, nourrie du français parlé au Cameroun.",
    whyRead: [
      "La suite de Trop de soleil tue l'amour, dans la même veine policière.",
      "Une langue savoureuse, pleine d'expressions camerounaises.",
      "Le dernier roman publié du vivant de Mongo Beti.",
    ],
    year: 2000,
    publisher: "Pocket",
    pages: 351,
    isbn: "9782266108713",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "mongo-beti-parle",
    title: "Mongo Beti parle",
    subtitle: "Testament d'un esprit rebelle",
    contributors: [beti, auteur("Ambroise Kom", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "exil", "identite"],
    summary:
      "Dans ces entretiens menés par l'universitaire camerounais Ambroise Kom, Mongo Beti revient sur sa vie et son œuvre. Il parle de son enfance au village, de ses années d'études et d'enseignement en France, de son exil et de son retour au Cameroun. Il s'explique sur ses romans, ses combats politiques et sa vision de l'Afrique. Un autoportrait libre, souvent tranchant, d'un écrivain qui n'a jamais transigé.",
    whyRead: [
      "Le meilleur moyen d'entendre Mongo Beti parler de lui-même.",
      "Des entretiens francs sur la littérature et la politique.",
      "Une porte d'entrée vers l'ensemble de son œuvre.",
    ],
    year: 2002,
    publisher: "Éditions des Peuples noirs",
    pages: 282,
    isbn: "9782864410195",
    format: null,
    awards: [],
  }),
  livre({
    slug: "africains-si-vous-parliez",
    title: "Africains si vous parliez",
    contributors: [beti],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite", "colonisation"],
    summary:
      "Ce recueil posthume rassemble des textes que Mongo Beti a écrits pour sa revue Peuples noirs, peuples africains entre la fin des années 1970 et le début des années 1990. Il y dénonce les ingérences étrangères en Afrique, le silence des médias occidentaux et les illusions de la francophonie. Il y parle aussi d'exil et de retour. L'ensemble forme un plaidoyer pour que les Africains prennent enfin la parole sur leur propre sort.",
    whyRead: [
      "Le meilleur de la plume polémiste de Mongo Beti.",
      "Des textes sur l'Afrique et les médias qui n'ont pas vieilli.",
      "Un livre paru après sa mort, comme un dernier appel.",
    ],
    year: 2005,
    publisher: "Homnisphères",
    pages: 318,
    isbn: "9782915129083",
    format: null,
    awards: [],
    outOfPrint: true,
  }),

  // ------------------------------------------------------------------ Ferdinand Oyono
  livre({
    slug: "le-vieux-negre-et-la-medaille",
    title: "Le Vieux Nègre et la médaille",
    contributors: [oyono],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "humour", "tradition"],
    summary:
      "Meka, vieux paysan du Cameroun sous administration française, a tout donné aux Blancs : ses terres à la mission catholique et ses deux fils, morts à la guerre. En récompense, on lui annonce qu'il recevra une médaille lors de la fête du 14 Juillet. Tout le village se prépare à l'honneur, et Meka, sanglé dans une veste trop étroite, attend la cérémonie avec fierté. Mais la journée ne se passe pas comme prévu, et le vieil homme va découvrir ce que vaut vraiment l'amitié qu'on lui promet.",
    whyRead: [
      "Un classique de la littérature anticoloniale, drôle et cruel à la fois.",
      "Un vieil homme touchant, au cœur d'une cérémonie absurde.",
      "Paru la même année qu'Une vie de boy, du même auteur.",
    ],
    year: 1956,
    publisher: "10/18",
    pages: null,
    isbn: "9782264009623",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chemin-d-europe",
    title: "Chemin d'Europe",
    contributors: [oyono],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "colonisation", "ecole"],
    summary:
      "Aki Barnabas, jeune Camerounais brillant, a été renvoyé du séminaire où ses parents s'étaient sacrifiés pour l'envoyer. Désormais, il n'a plus qu'une idée : partir en Europe, en France surtout, pour y étudier et y faire fortune. Pour réunir l'argent du voyage, il enchaîne les petits emplois : commis chez un commerçant grec, précepteur d'une jeune Française, guide pour touristes dans un hôtel. Chaque expérience lui renvoie l'image de ce que la colonie fait de ses enfants.",
    whyRead: [
      "Le dernier roman de Ferdinand Oyono, plus amer que les précédents.",
      "Le portrait d'un jeune homme prêt à tout pour partir.",
      "Une réflexion sur le rêve d'Europe à l'époque coloniale.",
    ],
    year: 1960,
    publisher: "10/18",
    pages: 189,
    isbn: "9782264008817",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),

  // ------------------------------------------------------------------ Calixthe Beyala
  livre({
    slug: "c-est-le-soleil-qui-m-a-brulee",
    title: "C'est le soleil qui m'a brûlée",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "ville", "famille"],
    summary:
      "Ateba a dix-neuf ans et vit chez sa tante Ada, femme autoritaire, dans un quartier pauvre d'une grande ville africaine. Sa mère est partie, les hommes passent, et la jeune fille observe le sort fait aux femmes autour d'elle. Pour tenir, elle écrit des lettres à toutes les femmes, qu'elle n'envoie jamais. Le premier roman de Calixthe Beyala dit avec une rare violence le corps, la révolte et le désir de liberté.",
    whyRead: [
      "Le premier roman de Calixthe Beyala, d'une audace frappante.",
      "Une voix de jeune femme qui refuse la soumission.",
      "Une écriture brûlante, poétique et sans tabou.",
    ],
    year: 1987,
    publisher: "J'ai lu",
    pages: 152,
    isbn: "9782277225126",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "tu-t-appelleras-tanga",
    title: "Tu t'appelleras Tanga",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "enfance", "ville"],
    summary:
      "Dans une cellule de prison, deux femmes se retrouvent côte à côte. Tanga, dix-sept ans, est à bout de forces, et sa codétenue, Anna-Claude, est une Européenne que la police a enfermée là. Avant de mourir, Tanga lui confie son histoire : une enfance volée dans les rues d'une ville africaine, la misère, les violences subies. En recevant ce récit, Anna-Claude en devient la gardienne.",
    whyRead: [
      "Un huis clos poignant entre deux femmes que tout sépare.",
      "La transmission d'une histoire comme acte de résistance.",
      "Un roman dur, porté par une langue très libre.",
    ],
    year: 1988,
    publisher: "J'ai lu",
    pages: 219,
    isbn: "9782277228073",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "seul-le-diable-le-savait",
    title: "Seul le diable le savait",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "tradition"],
    summary:
      "Mégri est née avec des cheveux roux, une particularité qui la distingue de tous dans son village africain. Autour d'elle, le monde visible et le monde des esprits ne cessent de se mêler, et son destin semble lui aussi hors du commun. Calixthe Beyala suit cette jeune femme dans une société où la magie, le désir et les règles des anciens se répondent. Le roman a été réédité sous le titre La Négresse rousse.",
    whyRead: [
      "Un roman où le réel et le surnaturel se confondent.",
      "Une héroïne singulière, marquée par sa différence.",
      "Le troisième roman de l'autrice, réédité sous un autre titre.",
    ],
    year: 1990,
    publisher: "J'ai lu",
    pages: 309,
    isbn: "9782290046012",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "le-petit-prince-de-belleville",
    title: "Le Petit Prince de Belleville",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "exil", "famille", "humour"],
    summary:
      "Loukoum a sept ans et vit à Belleville, à Paris, avec son père Abdou, venu du Mali, et les deux femmes de celui-ci. À l'école, il apprend à lire et à se débrouiller ; à la maison, il observe les adultes et leurs secrets. Entre ses bêtises et ses découvertes, il raconte avec ses mots d'enfant la vie d'une famille africaine en France. En contrepoint, la voix du père dit sa fatigue et sa nostalgie.",
    whyRead: [
      "Un narrateur enfant plein de gouaille et de tendresse.",
      "Le Belleville des familles africaines, vu de l'intérieur.",
      "Un roman drôle qui touche à des sujets graves.",
    ],
    year: 1992,
    publisher: "J'ai lu",
    pages: 251,
    isbn: "9782277235521",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "maman-a-un-amant",
    title: "Maman a un amant",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "famille", "amour"],
    summary:
      "On retrouve Loukoum et sa famille de Belleville, mais cette fois, c'est M'am, sa mère, qui prend la parole. Arrivée du Mali pour épouser Abdou, elle a vécu des années dans l'ombre de son mari. Elle apprend à lire, découvre la ville, et un jour tombe amoureuse d'un autre homme. Calixthe Beyala raconte l'éveil d'une femme qui ose enfin penser à elle.",
    whyRead: [
      "La suite du Petit Prince de Belleville, du côté de la mère.",
      "Le portrait sensible d'une femme qui s'émancipe.",
      "Grand prix littéraire d'Afrique noire.",
    ],
    year: 1993,
    publisher: "J'ai lu",
    pages: 246,
    isbn: "9782277239819",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1993 }],
  }),
  livre({
    slug: "asseze-l-africaine",
    title: "Assèze l'Africaine",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "ville", "identite"],
    summary:
      "Assèze grandit dans un village du Cameroun, entre sa mère et sa grand-mère. Un jour, on l'envoie à Douala chez un homme riche, pour servir de compagne à sa fille Sorraya, belle et capricieuse. Entre les deux jeunes filles naît une relation faite de rivalité et d'attachement. Le chemin d'Assèze la conduira jusqu'à Paris, parmi les sans-papiers et les déracinés.",
    whyRead: [
      "Un parcours de femme du village jusqu'à Paris.",
      "Une amitié-rivalité intense entre deux jeunes filles.",
      "Prix François-Mauriac de l'Académie française 1994.",
    ],
    year: 1994,
    publisher: "J'ai lu",
    pages: 319,
    isbn: "9782290042922",
    format: "poche",
    awards: [
      { name: "Prix François-Mauriac de l'Académie française", year: 1994 },
      { name: "Prix Tropiques", year: 1994 },
    ],
  }),
  livre({
    slug: "lettre-d-une-africaine-a-ses-soeurs-occidentales",
    title: "Lettre d'une Africaine à ses sœurs occidentales",
    contributors: [beyala],
    genre: "essai",
    audience: "adulte",
    themes: ["femmes", "identite"],
    summary:
      "Calixthe Beyala s'adresse aux femmes d'Occident dans un essai polémique et sans détour. Elle y interroge le sexisme, les inégalités entre hommes et femmes et la façon dont le féminisme occidental regarde les Africaines. Elle plaide pour une solidarité entre femmes qui tienne compte de leurs différences. Un texte court, au ton vif, qui prolonge les questions posées par ses romans.",
    whyRead: [
      "Le premier essai de Calixthe Beyala, direct et combatif.",
      "Un regard africain sur le féminisme occidental.",
      "Pour comprendre le fil rouge de ses romans.",
    ],
    year: 1995,
    publisher: "Spengler",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "la-petite-fille-du-reverbere",
    title: "La Petite Fille du réverbère",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "femmes", "famille", "ville"],
    summary:
      "Dans les années 1960, à Kassalafam, quartier pauvre de Douala, une petite fille grandit auprès de sa grand-mère, femme forte et autoritaire. Sa mère l'a laissée, et l'enfant fait ses devoirs à la lumière d'un réverbère, faute d'électricité. Entre l'école, les voisins et les secrets de famille, elle se fraie un chemin. Calixthe Beyala y puise dans ses propres souvenirs d'enfance.",
    whyRead: [
      "Un roman d'enfance très personnel, nourri de la vie de l'autrice.",
      "Une grand-mère inoubliable.",
      "Grand prix de l'Unicef 1998.",
    ],
    year: 1998,
    publisher: "J'ai lu",
    pages: 221,
    isbn: "9782290053294",
    format: "poche",
    awards: [{ name: "Grand prix de l'Unicef", year: 1998 }],
  }),
  livre({
    slug: "amours-sauvages",
    title: "Amours sauvages",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "amour", "ville"],
    summary:
      "Ève-Marie a quitté l'Afrique pour Paris en croyant à la devise de la République. Pour être libre, se dit-elle, il faut un travail et un mari. À Belleville, le travail qu'elle trouve est celui de la rue, sous le nom de Mademoiselle Bonne-Surprise. Elle rêve pourtant d'une autre vie, et l'amour va s'en mêler.",
    whyRead: [
      "Une héroïne qui garde ses rêves malgré tout.",
      "Belleville et ses marges, racontés avec humour et crudité.",
      "Une réflexion sur la liberté des femmes immigrées.",
    ],
    year: 1999,
    publisher: "J'ai lu",
    pages: 158,
    isbn: "9782290309025",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "lettre-d-une-afro-francaise-a-ses-compatriotes",
    title: "Lettre d'une Afro-Française à ses compatriotes",
    contributors: [beyala],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique"],
    summary:
      "À la fin des années 1990, des sondages révèlent qu'une large part des Français se déclarent racistes. Calixthe Beyala, alors très engagée pour que les minorités soient visibles à la télévision et dans la vie publique, répond par cette lettre. Elle y parle de sa place de Française d'origine africaine et des discriminations ordinaires. Un coup de gueule bref et argumenté.",
    whyRead: [
      "Un texte court et percutant sur le racisme en France.",
      "Le témoignage d'une écrivaine engagée dans le débat public.",
      "Un débat qui reste d'actualité.",
    ],
    year: 2000,
    publisher: "Mango",
    pages: 94,
    isbn: "9782842702328",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "comment-cuisiner-son-mari-a-l-africaine",
    title: "Comment cuisiner son mari à l'africaine",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "humour", "exil", "tradition"],
    summary:
      "Aïssatou, Parisienne d'origine africaine, a longtemps voulu ressembler aux femmes des magazines. Elle tombe amoureuse de son voisin, un homme qui ne se laisse pas facilement séduire. Pour le conquérir, elle se souvient des leçons de sa mère et se met aux fourneaux, avec les recettes du pays. Le roman, ponctué de vraies recettes, est une comédie gourmande sur l'amour et les racines.",
    whyRead: [
      "Une comédie pleine d'épices, avec de vraies recettes.",
      "Une héroïne qui renoue avec ses origines par la cuisine.",
      "Un roman léger et malicieux.",
    ],
    year: 2000,
    publisher: "J'ai lu",
    pages: 155,
    isbn: "9782290319635",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-arbres-en-parlent-encore",
    title: "Les arbres en parlent encore…",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "tradition", "humour", "histoire"],
    summary:
      "Au fil de seize veillées, une vieille femme raconte l'histoire de son village du Cameroun au temps de la colonisation. Les Blancs arrivent avec leurs lois, leurs missionnaires et leurs certitudes, et les villageois s'y adaptent à leur manière. Amours, querelles, polygamie et polyandrie : rien n'échappe à la conteuse. Calixthe Beyala fait revivre une mémoire africaine avec humour et poésie.",
    whyRead: [
      "Une grande saga villageoise racontée comme au coin du feu.",
      "La colonisation vue avec malice par ceux qui l'ont vécue.",
      "Un roman foisonnant et plein de vie.",
    ],
    year: 2001,
    publisher: "Le Livre de Poche",
    pages: 474,
    isbn: "9782253067764",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "femme-nue-femme-noire",
    title: "Femme nue, femme noire",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "ville"],
    summary:
      "Irène Fofo, jeune femme d'une ville africaine, affirme n'avoir que deux passions : voler et faire l'amour. Un jour, le sac qu'elle dérobe lui réserve une terrible surprise, et sa rencontre avec un certain Ousmane l'entraîne dans une suite d'expériences extrêmes. Au fil de son errance se dessine une société marquée par la misère et l'hypocrisie. Présenté par son éditeur comme le premier roman érotique africain, ce livre interroge sans détour la liberté du corps féminin.",
    whyRead: [
      "Un roman érotique et provocant, qui bouscule les tabous.",
      "Une héroïne libre, insolente et dérangeante.",
      "Pour lecteurs adultes avertis.",
    ],
    year: 2003,
    publisher: "Le Livre de Poche",
    pages: 188,
    isbn: "9782253112693",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-plantation",
    title: "La Plantation",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "identite", "histoire", "amour"],
    summary:
      "Au Zimbabwe, au début des années 2000, Blues Cooper, dix-huit ans, est l'héritière gâtée d'une grande plantation tenue par sa famille blanche. Quand le pouvoir décide d'exproprier les fermiers blancs, son monde vacille. Elle découvre alors à quel point cette terre africaine est la sienne. Calixthe Beyala choisit un point de vue inattendu pour parler de la terre, de l'héritage colonial et de l'appartenance.",
    whyRead: [
      "Un point de vue rare : celui d'une jeune Blanche d'Afrique.",
      "La réforme agraire du Zimbabwe racontée à hauteur d'héroïne.",
      "Un roman ample, entre saga familiale et roman politique.",
    ],
    year: 2005,
    publisher: "Le Livre de Poche",
    pages: 413,
    isbn: "9782253119968",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-homme-qui-m-offrait-le-ciel",
    title: "L'Homme qui m'offrait le ciel",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "femmes", "identite"],
    summary:
      "La narratrice, écrivaine africaine installée à Paris et mère d'une adolescente, vit seule. Elle rencontre un homme célèbre, blanc et marié, et une passion naît entre eux. Tout les sépare : la notoriété, la couleur de peau, le regard des autres. Le roman pose une question simple : un grand amour peut-il résister aux pressions sociales ?",
    whyRead: [
      "Un roman d'amour intense et sans fard.",
      "Une passion confrontée aux préjugés.",
      "Un livre court, qui se lit d'une traite.",
    ],
    year: 2007,
    publisher: "Le Livre de Poche",
    pages: 150,
    isbn: "9782253127970",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-roman-de-pauline",
    title: "Le Roman de Pauline",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "ville", "ecole", "famille"],
    summary:
      "Pauline a quatorze ans et vit à Pantin, entre une mère qui la néglige, un frère délinquant et un petit ami qui la traite mal. Elle a l'esprit vif, mais elle ne va plus à l'école et passe ses journées dans la rue. Un jour, elle croise Mathilde, une ancienne professeure de français qui décide de s'occuper d'elle. Peu à peu, Pauline découvre qu'une autre vie que la violence est possible.",
    whyRead: [
      "Le portrait vrai d'une adolescente de banlieue.",
      "Une rencontre qui change tout, entre deux générations.",
      "Un roman tendre sur l'éducation et la confiance.",
    ],
    year: 2009,
    publisher: "Le Livre de Poche",
    pages: 185,
    isbn: "9782253160236",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-lions-indomptables",
    title: "Les Lions indomptables",
    subtitle: "Cinquante ans de bonheur",
    contributors: [beyala],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "identite"],
    summary:
      "Calixthe Beyala célèbre les cinquante ans de l'équipe nationale de football du Cameroun, les célèbres Lions indomptables. Le livre retrace les grandes heures de la sélection, ses victoires en Coupe d'Afrique des nations et ses joueurs légendaires. Abondamment illustré, il raconte aussi ce que le football représente pour tout un peuple. Un beau livre d'amoureuse du ballon rond.",
    whyRead: [
      "Un hommage passionné à une équipe mythique.",
      "Un beau livre illustré, à offrir aux fans de football.",
      "Une autre facette de Calixthe Beyala.",
    ],
    year: 2010,
    publisher: "Albin Michel",
    pages: 131,
    isbn: "9782226181909",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "le-christ-selon-l-afrique",
    title: "Le Christ selon l'Afrique",
    contributors: [beyala],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "femmes", "ville", "humour"],
    summary:
      "Boréale, vingt ans, revient à Kassalafam, son quartier de Douala, enceinte et trompée par son compagnon. Autour d'elle, sa famille, ses voisines et une foule de prophètes de rue ont chacun leur avis sur la manière de sauver son âme et son couple. Elle ne croit en rien, mais il lui faut bien naviguer dans ce tourbillon de croyances. Calixthe Beyala signe une comédie grinçante sur la religion et la débrouille.",
    whyRead: [
      "Une satire savoureuse des Églises de réveil.",
      "Le retour de l'autrice dans le Douala de son enfance.",
      "Une héroïne sceptique dans un monde de croyants.",
    ],
    year: 2014,
    publisher: "Albin Michel",
    pages: 264,
    isbn: "9782226256010",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Léonora Miano
  livre({
    slug: "l-interieur-de-la-nuit",
    title: "L'Intérieur de la nuit",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "tradition", "femmes", "identite"],
    summary:
      "Ayané a grandi à Eku, petit village d'un pays imaginaire d'Afrique centrale, avant de partir étudier en France. Revenue au village, elle se sent étrangère parmi les siens, qui la tiennent à distance. Une nuit, des combattants venus d'ailleurs envahissent le village et contraignent les habitants à commettre l'impensable, au nom d'un retour aux traditions. Le premier roman de Léonora Miano, d'une grande force.",
    whyRead: [
      "Un premier roman saisissant, couronné de nombreux prix.",
      "Une réflexion sur la violence et la responsabilité collective.",
      "Le premier volet de la « Suite africaine ».",
    ],
    year: 2005,
    publisher: "Pocket",
    pages: 213,
    isbn: "9782266162685",
    format: "poche",
    awards: [
      { name: "Prix Louis-Guilloux", year: 2006 },
      { name: "Prix du premier roman de femme", year: 2006 },
      { name: "Prix René-Fallet", year: 2006 },
    ],
  }),
  livre({
    slug: "contours-du-jour-qui-vient",
    title: "Contours du jour qui vient",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "spiritualite", "guerre"],
    summary:
      "Dans le Mboasu, pays imaginaire meurtri par la guerre, la petite Musango a été rejetée par sa mère, qui l'accuse d'avoir causé ses malheurs. Livrée à elle-même, l'enfant erre dans une ville où les faux prophètes et les profiteurs règnent. Tout au long du livre, elle s'adresse à cette mère qu'elle cherche à comprendre. Sur sa route, quelques femmes généreuses vont l'aider à se tenir debout.",
    whyRead: [
      "Prix Goncourt des lycéens 2006.",
      "Une petite héroïne d'un courage bouleversant.",
      "Une langue poétique au service d'une histoire très dure.",
    ],
    year: 2006,
    publisher: "Pocket",
    pages: 247,
    isbn: "9782266169080",
    format: "poche",
    awards: [{ name: "Prix Goncourt des lycéens", year: 2006 }],
  }),
  livre({
    slug: "afropean-soul",
    title: "Afropean Soul et autres nouvelles",
    contributors: [miano],
    genre: "nouvelles",
    audience: "ado",
    themes: ["exil", "identite", "ville"],
    summary:
      "Ces nouvelles suivent des personnes qu'on voit peu dans la littérature française : un jeune footballeur camerounais isolé à son arrivée en France, un garçon de neuf ans qui perçoit la solitude de sa mère, des jeunes filles pleines de rêves. Tous vivent entre deux cultures, en marge d'une société qui les regarde mal. Léonora Miano leur donne une voix avec justesse. Le recueil, publié dans une collection scolaire, est accompagné d'un dossier de lecture.",
    whyRead: [
      "Une porte d'entrée idéale vers l'œuvre de Léonora Miano.",
      "Des nouvelles courtes, parfaites pour les lycéens.",
      "La France afropéenne racontée de l'intérieur.",
    ],
    year: 2008,
    publisher: "Flammarion",
    pages: 121,
    isbn: "9782080425904",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "tels-des-astres-eteints",
    title: "Tels des astres éteints",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "exil", "ville"],
    summary:
      "Dans une grande ville d'Europe, trois jeunes gens partagent le sentiment de ne pas avoir la couleur de ceux qui les entourent. Amok, venu d'Afrique, refuse que sa peau dise qui il est. Shrapnel, lui aussi africain, se rêve en héritier d'un monde noir qui va de l'Afrique aux Amériques, tandis qu'Amandla, venue des Caraïbes, cherche des réponses dans une mythologie ancienne. Chacun risque de s'enfermer dans sa propre réponse.",
    whyRead: [
      "Trois façons de vivre son identité, sans réponse toute faite.",
      "Un grand roman sur la diaspora noire en Europe.",
      "Le passage de Léonora Miano vers l'univers afropéen.",
    ],
    year: 2008,
    publisher: "Pocket",
    pages: 376,
    isbn: "9782266193757",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "soulfood-equatoriale",
    title: "Soulfood équatoriale",
    contributors: [miano],
    genre: "recit",
    audience: "adulte",
    themes: ["tradition", "identite", "enfance"],
    summary:
      "Léonora Miano raconte le Cameroun par la cuisine : la pierre à écraser où l'on broie gingembre et crevettes séchées, les beignets haricots, la sauce tomate, et même les sauterelles grillées. Chaque plat fait surgir un souvenir, une légende ou une petite scène prise sur le vif. Le jazz, qu'elle aime tant, s'invite aussi à table. Un court texte gourmand, loin des clichés sur l'Afrique.",
    whyRead: [
      "Un petit livre savoureux, à lire en une soirée.",
      "Le Cameroun par ses saveurs et ses souvenirs.",
      "Une Léonora Miano intime et pleine d'humour.",
    ],
    year: 2009,
    publisher: "NiL",
    pages: 100,
    isbn: "9782841113804",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-aubes-ecarlates",
    title: "Les Aubes écarlates",
    subtitle: "Sankofa cry",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "esclavage", "enfance", "histoire"],
    summary:
      "Dans le Mboasu, Epa, garçon du village d'Eku, a été enlevé par des miliciens et enrôlé dans les troupes d'un chef rebelle ambitieux. Au cœur de la guerre, il est assailli de visions : des ombres enchaînées, les âmes de victimes de la traite négrière qui n'ont jamais reçu de sépulture. Lorsqu'il parvient à s'échapper, il croise la route d'Ayané. Le roman relie les violences d'aujourd'hui aux blessures anciennes de l'esclavage.",
    whyRead: [
      "Le dernier volet de la « Suite africaine ».",
      "Un roman qui fait dialoguer les vivants et les morts.",
      "Une réflexion puissante sur la mémoire de la traite.",
    ],
    year: 2009,
    publisher: "Pocket",
    pages: 259,
    isbn: "9782266200585",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "blues-pour-elise",
    title: "Blues pour Élise",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "femmes", "ville", "identite"],
    summary:
      "Akasha, Amahoro, Shale et Malaïka sont quatre jeunes femmes noires qui vivent à Paris. L'une soigne un chagrin d'amour, une autre souffre de la distance de son compagnon, la troisième s'éprend d'un homme qui ne lui plaît pas, et la dernière panique à l'approche de son mariage. Entre speed dating, vélos en libre-service et dîners entre amies, elles cherchent l'amour, celui des autres et le leur. Une France noire urbaine et bohème, loin des clichés.",
    whyRead: [
      "Une comédie sentimentale pétillante.",
      "Des héroïnes afropéennes modernes, loin des stéréotypes.",
      "Un roman court et rythmé comme un morceau de blues.",
    ],
    year: 2010,
    publisher: "Pocket",
    pages: 157,
    isbn: "9782266193306",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ces-ames-chagrines",
    title: "Ces âmes chagrines",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "identite"],
    summary:
      "Antoine est un dandy parisien, élégant et méprisant, qui court les soirées mondaines pour oublier une vieille blessure : sa mère, Thamar, l'a laissé derrière elle quand il était enfant. Son frère Maxime, qu'il jalouse depuis toujours, entretient au contraire avec elle un lien fort. Lorsque Maxime décide de ramener Thamar au pays, au Mboasu, Antoine se retrouve seul face à lui-même. Un roman sur l'amour maternel et la difficulté de s'aimer.",
    whyRead: [
      "Le portrait d'un homme blessé derrière son arrogance.",
      "Une histoire de famille entre Paris et l'Afrique.",
      "Une plongée dans la communauté afropéenne.",
    ],
    year: 2011,
    publisher: "Pocket",
    pages: 274,
    isbn: "9782266223799",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ecrits-pour-la-parole",
    title: "Écrits pour la parole",
    contributors: [miano],
    genre: "theatre",
    audience: "adulte",
    themes: ["identite", "femmes", "exil"],
    summary:
      "Ces textes sont faits pour être dits à voix haute : des monologues et des récits où parlent des Afrodescendants de France. On y entend surtout des femmes, en quête de justice, d'égalité et d'amour, confrontées au racisme ordinaire, au travail, dans la rue ou dans l'intimité. Léonora Miano y donne forme à des vies souvent absentes des récits nationaux. La nouvelle édition s'ouvre sur une préface inédite de l'autrice.",
    whyRead: [
      "Des textes forts, à lire ou à entendre sur scène.",
      "Prix Seligmann contre le racisme 2012.",
      "Des voix de femmes afrodescendantes rarement entendues.",
    ],
    year: 2012,
    publisher: "L'Arche",
    pages: 92,
    isbn: "9782381980577",
    format: null,
    awards: [{ name: "Prix Seligmann contre le racisme", year: 2012 }],
  }),
  livre({
    slug: "habiter-la-frontiere",
    title: "Habiter la frontière",
    contributors: [miano],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "exil", "histoire"],
    summary:
      "Ce volume réunit des conférences données par Léonora Miano entre 2009 et 2011. Elle y explique son lien à une génération de Subsahariens prêts à regarder en face les zones sombres de leur histoire. Elle invite aussi l'Europe à sortir de la culpabilité pour examiner son passé avec lucidité. Au centre de sa réflexion : la frontière, lieu de rencontres parfois violentes mais aussi de création.",
    whyRead: [
      "Pour comprendre la pensée qui nourrit ses romans.",
      "Une réflexion sur les identités métisses et frontalières.",
      "Des conférences claires et accessibles.",
    ],
    year: 2012,
    publisher: "L'Arche",
    pages: 141,
    isbn: "9782851817860",
    format: null,
    awards: [],
  }),
  livre({
    slug: "red-in-blue-trilogie",
    title: "Red in Blue trilogie",
    contributors: [miano],
    genre: "theatre",
    audience: "adulte",
    themes: ["esclavage", "histoire", "identite"],
    summary:
      "Ces trois pièces traversent la mémoire de la traite transatlantique, vue du côté des Subsahariens et des Afrodescendants. La première puise dans les mythologies et l'histoire, et la dernière met en scène le combat d'une Antigone afrodescendante d'aujourd'hui. La langue de Léonora Miano y est ample, musicale et épique. Le premier volet, Révélation, a été mis en scène par le Japonais Satoshi Miyagi en 2018.",
    whyRead: [
      "Une trilogie théâtrale sur la mémoire de l'esclavage.",
      "Une langue puissante, faite pour la scène.",
      "Une Antigone moderne, venue des Amériques noires.",
    ],
    year: 2015,
    publisher: "L'Arche",
    pages: 173,
    isbn: "9782851818652",
    format: null,
    awards: [],
    adaptations: [{ kind: "théâtre", title: "Révélation", year: 2018, by: "Satoshi Miyagi" }],
  }),
  livre({
    slug: "crepuscule-du-tourment",
    title: "Crépuscule du tourment",
    subtitle: "Melancholy",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "amour"],
    summary:
      "Quelque part en Afrique subsaharienne, quatre femmes s'adressent tour à tour au même homme, Dio : sa mère, la femme qu'il a trop aimée, celle qui partage sa vie et sa sœur. Lui ne les entend pas, mais chacune parle pour comprendre. Elles racontent leurs blessures, leurs désirs, une lignée compliquée et ses silences. Peu à peu se dessine le portrait d'une famille et d'une société.",
    whyRead: [
      "Quatre voix de femmes d'une grande intensité.",
      "Une construction originale, en monologues adressés.",
      "Le premier volet d'un diptyque, suivi de Héritage.",
    ],
    year: 2016,
    publisher: "Pocket",
    pages: 293,
    isbn: "9782266273107",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-imperatif-transgressif",
    title: "L'Impératif transgressif",
    contributors: [miano],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "colonisation", "histoire"],
    summary:
      "Dans ces conférences et réflexions, Léonora Miano interroge l'écriture, la langue et la mémoire. Elle montre comment la pensée coloniale persiste dans la littérature et dans la langue françaises. Elle appelle les auteurs et les historiens subsahariens à raconter leur histoire depuis l'Afrique, et propose une « afrophonie » libérée de cet héritage. Un manifeste politique autant qu'artistique.",
    whyRead: [
      "Un essai stimulant sur la langue et le pouvoir.",
      "Une réflexion sur la place des écrivains africains.",
      "Pour prolonger Habiter la frontière.",
    ],
    year: 2016,
    publisher: "L'Arche",
    pages: 183,
    isbn: "9782851818935",
    format: null,
    awards: [],
  }),
  livre({
    slug: "crepuscule-du-tourment-2-heritage",
    title: "Héritage",
    subtitle: "Crépuscule du tourment 2",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "identite"],
    summary:
      "Après des années à l'étranger, Amok rentre au pays pour élever son fils loin du racisme. Ce retour réveille de vieux conflits familiaux et un malaise face à son milieu social. Un soir, il lève la main sur sa compagne et s'enfuit, horrifié, persuadé d'avoir hérité de la violence des hommes de sa lignée. Un accident de voiture le plonge dans un demi-sommeil où il revisite toute son histoire.",
    whyRead: [
      "La suite de Crépuscule du tourment, cette fois du côté d'un homme.",
      "Une réflexion profonde sur ce qu'on hérite de sa famille.",
      "Un roman introspectif et poétique.",
    ],
    year: 2017,
    publisher: "Pocket",
    pages: 316,
    isbn: "9782266280501",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "rouge-imperatrice",
    title: "Rouge impératrice",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "politique", "identite"],
    summary:
      "Dans un peu plus d'un siècle, l'Afrique presque entièrement unifiée s'appelle Katiopa et elle est devenue prospère. Des descendants d'Européens, venus s'y réfugier après le déclin de leur continent, y vivent repliés sur leur identité. Le chef de l'État, Ilunga, veut expulser ces populations, mais il tombe amoureux de Boya, une femme qui plaide pour leur tendre la main. Une grande histoire d'amour et de pouvoir, qui renverse les regards.",
    whyRead: [
      "Un roman d'anticipation qui inverse les rôles entre l'Afrique et l'Europe.",
      "Une histoire d'amour flamboyante au sommet de l'État.",
      "Une langue riche de mots africains.",
    ],
    year: 2019,
    publisher: "Pocket",
    pages: 641,
    isbn: "9782266308106",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ce-qu-il-faut-dire",
    title: "Ce qu'il faut dire",
    contributors: [miano],
    genre: "theatre",
    audience: "adulte",
    themes: ["identite", "exil", "politique"],
    summary:
      "Ce livre réunit trois textes, La question blanche, Le fond des choses et La fin des fins, composés pour être lus comme des partitions musicales. Léonora Miano y parle de l'assignation raciale et de la façon dont la couleur de peau devient un problème dans le regard des autres. Elle y aborde aussi l'immigration, devenue dans le discours public une menace. Une parole rythmée, qui appelle malgré tout à la paix.",
    whyRead: [
      "Des textes à dire, construits comme de la musique.",
      "Une réflexion directe sur le racisme et l'immigration.",
      "Un livre bref et percutant.",
    ],
    year: 2019,
    publisher: "L'Arche",
    pages: 50,
    isbn: "9782851819703",
    format: null,
    awards: [],
  }),
  livre({
    slug: "afropea",
    title: "Afropea",
    subtitle: "Utopie post-occidentale et post-raciste",
    contributors: [miano],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "exil", "politique"],
    summary:
      "Léonora Miano refuse les notions d'identité « noire » ou de négritude et leur préfère des mots comme Subsahariens, Afrodescendants ou Afropéens. Elle voit dans l'Afropéen, à la fois africain et européen, la chance d'une société plus fraternelle et plus juste. Il ne s'agit pas pour elle de rêver d'un retour en Afrique, mais d'agir là où l'on vit. Un essai dense et personnel, écrit aussi pour sa fille.",
    whyRead: [
      "Un essai clé pour comprendre la notion d'« afropéen ».",
      "Une utopie positive plutôt qu'un réquisitoire.",
      "Une pensée exigeante, exposée avec clarté.",
    ],
    year: 2020,
    publisher: "Pluriel",
    pages: 223,
    isbn: "9782818506554",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-autre-langue-des-femmes",
    title: "L'Autre Langue des femmes",
    contributors: [miano],
    genre: "essai",
    audience: "adulte",
    themes: ["femmes", "histoire", "identite"],
    summary:
      "Reines, guerrières, prêtresses, résistantes : l'Afrique subsaharienne a connu de nombreuses femmes puissantes, souvent méconnues hors du continent. Léonora Miano raconte leurs histoires, de Njinga à Yennenga en passant par Sarraounia ou Abla Pokou. Elle s'appuie sur ces figures pour montrer que les Africaines n'ont pas attendu qu'on leur dicte leur émancipation. Elle interroge aussi l'idée d'une « sororité » universelle entre femmes.",
    whyRead: [
      "Un formidable panthéon de femmes africaines.",
      "Un regard neuf sur le féminisme, depuis l'Afrique.",
      "Des histoires vraies et légendaires, racontées avec passion.",
    ],
    year: 2021,
    publisher: "Points",
    pages: 216,
    isbn: "9791041413423",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "stardust",
    title: "Stardust",
    contributors: [miano],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "femmes", "ville"],
    summary:
      "Louise, jeune mère de vingt-trois ans, a quitté le père de sa fille Bliss. Sans logement ni titre de séjour, elle trouve refuge avec son enfant dans un centre d'hébergement d'urgence du 19e arrondissement de Paris. Elle y partage le quotidien d'autres femmes cabossées par la vie. Écrit plus de vingt ans avant sa parution, ce roman s'inspire directement de ce que Léonora Miano a vécu à son arrivée en France.",
    whyRead: [
      "Le livre le plus intime de Léonora Miano.",
      "Un regard sans apitoiement sur la précarité et l'exil.",
      "Un roman court et lumineux malgré tout.",
    ],
    year: 2022,
    publisher: "Pocket",
    pages: 151,
    isbn: "9782266335294",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "fille-d-amanitore-et-que-mon-regne-arrive",
    title: "Fille d'Amanitore",
    subtitle: "suivi de Et que mon règne arrive",
    contributors: [miano],
    genre: "theatre",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "identite"],
    summary:
      "Dans Fille d'Amanitore, des déesses et des esprits de reines guerrières se penchent sur des femmes d'aujourd'hui, filles et mères, pour les révéler à leur propre puissance. La pièce explore l'influence des histoires familiales sur les destins individuels. Et que mon règne arrive invite les femmes subsahariennes à reprendre en main leur mémoire et leur destin. Deux textes pleins d'humour, qui refusent toutes les dominations.",
    whyRead: [
      "Deux pièces où se croisent déesses et femmes d'aujourd'hui.",
      "Un théâtre féministe, joyeux et sans complaisance.",
      "Le prolongement théâtral de L'Autre Langue des femmes.",
    ],
    year: 2023,
    publisher: "L'Arche",
    pages: 92,
    isbn: "9782381980508",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-oppose-de-la-blancheur",
    title: "L'Opposé de la blancheur",
    subtitle: "Réflexions sur le problème blanc",
    contributors: [miano],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "esclavage", "colonisation", "histoire"],
    summary:
      "Léonora Miano examine ce qu'est la « blanchité » : non pas une couleur de peau, mais une catégorie née dans les plantations esclavagistes et diffusée par la colonisation. Elle retrace cette histoire de la traite à nos jours, et montre comment elle se transmet de génération en génération, comme un héritage et un secret de famille. Selon elle, comprendre ce mécanisme est la condition pour le transformer. Un essai bref et argumenté.",
    whyRead: [
      "Un essai court pour comprendre un débat brûlant.",
      "Une analyse historique, de la plantation à aujourd'hui.",
      "Une pensée qui cherche à transformer plutôt qu'à accuser.",
    ],
    year: 2023,
    publisher: "Points",
    pages: 122,
    isbn: "9791041416103",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-aventures-de-la-foufoune",
    title: "Les Aventures de la foufoune",
    contributors: [miano],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "humour", "contes"],
    summary:
      "En dix monologues, Léonora Miano donne la parole au sexe féminin et à celles qui le portent. Mythes de création, rites d'initiation, expériences de vie : chaque texte explore une facette de la sexualité des femmes. L'autrice y parle franchement, avec humour et irrévérence. Un livre sensuel et subversif sur la liberté du corps.",
    whyRead: [
      "Un texte audacieux et drôle sur la sexualité féminine.",
      "Des monologues entre mythe et vie quotidienne.",
      "Une Léonora Miano libre et jubilatoire.",
    ],
    year: 2024,
    publisher: "Seuil",
    pages: null,
    isbn: "9782021569049",
    format: "grand-format",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "ville-cruelle",
  "mission-terminee",
  "le-roi-miracule",
  "main-basse-sur-le-cameroun",
  "perpetue-et-l-habitude-du-malheur",
  "remember-ruben",
  "la-ruine-presque-cocasse-d-un-polichinelle",
  "les-deux-meres-de-guillaume-ismael-dzewatama",
  "la-revanche-de-guillaume-ismael-dzewatama",
  "lettre-ouverte-aux-camerounais",
  "dictionnaire-de-la-negritude",
  "la-france-contre-l-afrique",
  "l-histoire-du-fou",
  "trop-de-soleil-tue-l-amour",
  "branle-bas-en-noir-et-blanc",
  "mongo-beti-parle",
  "africains-si-vous-parliez",
  "le-vieux-negre-et-la-medaille",
  "chemin-d-europe",
  "c-est-le-soleil-qui-m-a-brulee",
  "tu-t-appelleras-tanga",
  "seul-le-diable-le-savait",
  "le-petit-prince-de-belleville",
  "maman-a-un-amant",
  "asseze-l-africaine",
  "lettre-d-une-africaine-a-ses-soeurs-occidentales",
  "la-petite-fille-du-reverbere",
  "amours-sauvages",
  "lettre-d-une-afro-francaise-a-ses-compatriotes",
  "comment-cuisiner-son-mari-a-l-africaine",
  "les-arbres-en-parlent-encore",
  "femme-nue-femme-noire",
  "la-plantation",
  "l-homme-qui-m-offrait-le-ciel",
  "le-roman-de-pauline",
  "les-lions-indomptables",
  "le-christ-selon-l-afrique",
  "l-interieur-de-la-nuit",
  "contours-du-jour-qui-vient",
  "afropean-soul",
  "tels-des-astres-eteints",
  "soulfood-equatoriale",
  "les-aubes-ecarlates",
  "blues-pour-elise",
  "ces-ames-chagrines",
  "ecrits-pour-la-parole",
  "habiter-la-frontiere",
  "red-in-blue-trilogie",
  "crepuscule-du-tourment",
  "l-imperatif-transgressif",
  "crepuscule-du-tourment-2-heritage",
  "rouge-imperatrice",
  "ce-qu-il-faut-dire",
  "afropea",
  "l-autre-langue-des-femmes",
  "stardust",
  "fille-d-amanitore-et-que-mon-regne-arrive",
  "l-oppose-de-la-blancheur",
  "les-aventures-de-la-foufoune",
];
