/**
 * Lot 02 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Auteurs : Aminata Sow Fall, David Diop, Birago Diop, Ken Bugul, Felwine Sarr.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });

const sowFall = auteur("Aminata Sow Fall", "aminata-sow-fall");
const davidDiop = auteur("David Diop", "david-diop");
const biragoDiop = auteur("Birago Diop", "birago-diop");
const kenBugul = auteur("Ken Bugul", "ken-bugul");
const felwineSarr = auteur("Felwine Sarr", "felwine-sarr");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ---------------------------------------------------------------- Aminata Sow Fall
  livre({
    slug: "le-revenant",
    title: "Le Revenant",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "ville", "humour", "tradition"],
    summary:
      "Bakar, modeste employé des postes à Dakar, est un homme honnête. Mais pour tenir son rang et combler les exigences de sa famille et de ses amis, il dépense bien plus qu'il ne gagne. Pris à la gorge, il puise dans la caisse et finit en prison. À sa sortie, tous ceux qui ont profité de ses largesses lui tournent le dos, et Bakar décide de prendre sa revanche.",
    whyRead: [
      "Le premier roman d'Aminata Sow Fall, parmi les premiers publiés par une Sénégalaise.",
      "Une satire mordante de l'argent-roi et des apparences à Dakar.",
      "Une intrigue de vengeance menée avec humour et ironie.",
    ],
    year: 1976,
    publisher: "Nouvelles Éditions africaines",
    pages: 125,
    isbn: "9782723601092",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "l-appel-des-arenes",
    title: "L'Appel des arènes",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "tradition", "identite"],
    summary:
      "Nalla est le fils unique de Diattou et Ndiogou, un couple revenu d'Europe qui a coupé les ponts avec sa famille et ses traditions. Ses parents veulent pour lui les meilleures études et le tiennent à l'écart du quartier. Mais l'adolescent dépérit, jusqu'au jour où il découvre les arènes de lutte, leurs tambours, leurs chants et leurs champions. Peu à peu, il s'attache à ce monde dont on a voulu le priver.",
    whyRead: [
      "Une plongée vivante dans l'univers de la lutte sénégalaise.",
      "Un conflit entre générations que tout lecteur reconnaîtra.",
      "Adapté au cinéma par Cheikh Ndiaye en 2005.",
    ],
    year: 1982,
    publisher: "Edicef",
    pages: null,
    isbn: "9782753107861",
    format: null,
    awards: [{ name: "Prix international pour les lettres africaines", year: 1982 }],
    adaptations: [{ kind: "film", title: "L'Appel des arènes", year: 2005, by: "Cheikh Ndiaye" }],
  }),
  livre({
    slug: "l-ex-pere-de-la-nation",
    title: "L'Ex-Père de la nation",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "histoire"],
    summary:
      "Emprisonné depuis la chute de son régime, l'ancien président d'un pays africain revient sur son parcours. Élu triomphalement, cet homme sincère croyait pouvoir mener son peuple vers la prospérité. Il raconte comment, de compromis en trahisons, son pouvoir a glissé vers la répression et la misère. Le roman explore les mécanismes qui transforment un homme de bonne volonté en tyran.",
    whyRead: [
      "Le récit d'un dictateur déchu, raconté de l'intérieur.",
      "Une réflexion lucide sur le pouvoir après les indépendances.",
      "Un roman politique court et percutant.",
    ],
    year: 1987,
    publisher: "L'Harmattan",
    pages: 189,
    isbn: "9782858028757",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-jujubier-du-patriarche",
    title: "Le Jujubier du patriarche",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "tradition", "histoire", "contes"],
    summary:
      "Yelli et sa femme Tacko descendent d'une lignée glorieuse, mais leur fierté aristocratique ne les protège plus de la gêne. Dans le cimetière du village des ancêtres, le jujubier qui pousse sur la tombe du patriarche refleurit après des années. Yelli organise un pèlerinage pour honorer les aïeux et espère ainsi réconcilier les siens. Les griots y chantent l'épopée qui mêle l'histoire de toutes les familles.",
    whyRead: [
      "Un roman où l'épopée chantée par les griots se mêle au récit.",
      "Une réflexion fine sur les castes, l'orgueil et la mémoire.",
      "Aminata Sow Fall au sommet de son art de conteuse.",
    ],
    year: 1993,
    publisher: "Le Serpent à plumes",
    pages: 188,
    isbn: "9782842610449",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "douceurs-du-bercail",
    title: "Douceurs du bercail",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "femmes", "travail", "identite"],
    summary:
      "Asta, Sénégalaise venue en France avec tous ses papiers en règle, est pourtant refoulée à l'aéroport. Elle se retrouve enfermée au « dépôt », une salle éclairée jour et nuit où s'entassent hommes, femmes et enfants en attente d'expulsion. Cette humiliation devient pour elle un tournant. De retour au pays, elle décide de bâtir autre chose sur sa propre terre, avec ceux qui ont partagé son épreuve.",
    whyRead: [
      "Un roman fort sur le rêve d'Europe et l'humiliation aux frontières.",
      "Une héroïne qui choisit de reconstruire chez elle.",
      "Un regard toujours actuel sur les migrations.",
    ],
    year: 1998,
    publisher: "NEI",
    pages: 224,
    isbn: "9782911725463",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "un-grain-de-vie-et-d-esperance",
    title: "Un grain de vie et d'espérance",
    contributors: [sowFall],
    genre: "essai",
    audience: "adulte",
    themes: ["tradition", "famille", "identite"],
    summary:
      "Dans ce petit livre, Aminata Sow Fall s'interroge sur ce que la nourriture signifie au Sénégal. Partager un repas, accueillir l'hôte, préparer un plat pour une fête : autant de gestes qui disent les liens entre les gens. Sa réflexion est suivie d'une vingtaine de recettes sénégalaises. Un livre à lire autant qu'à cuisiner.",
    whyRead: [
      "Une romancière qui parle de cuisine, de partage et d'hospitalité.",
      "Une vingtaine de recettes sénégalaises à essayer.",
      "Un livre rare et chaleureux dans l'œuvre de l'autrice.",
    ],
    year: 2002,
    publisher: "Françoise Truffaut éditions",
    pages: 141,
    isbn: "9782951661455",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "festins-de-la-detresse",
    title: "Festins de la détresse",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "travail", "politique", "tradition"],
    summary:
      "Maar, fonctionnaire à la retraite, vit dans une grande cour animée avec sa famille. Ses deux fils, pourtant diplômés, ne trouvent pas de travail, et le vieil homme en souffre. Il observe avec colère un État qui se défait et ceux qui s'enrichissent sur le dos des jeunes. Autour de lui, la famille et les voisins cherchent ensemble comment tenir debout.",
    whyRead: [
      "Le chômage des jeunes diplômés vu par les yeux d'un père.",
      "Un éloge de l'honnêteté et de la solidarité face à la corruption.",
      "Un roman plein de vie, porté par une cour dakaroise.",
    ],
    year: 2005,
    publisher: "Éditions d'en bas",
    pages: 158,
    isbn: "9782829003189",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "l-empire-du-mensonge",
    title: "L'Empire du mensonge",
    contributors: [sowFall],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "politique", "tradition", "travail"],
    summary:
      "Tout commence sur une décharge, quelque part en Afrique, où Mapaté trouve de quoi bâtir une maison et lancer un petit commerce. Avec sa femme Sabou, il construit au fil des années une famille solide et respectée. Autour d'eux, trois familles liées par le destin traversent une société où l'on finit par applaudir les menteurs et les malhonnêtes. Le roman oppose à cet empire du mensonge la droiture héritée des aînés.",
    whyRead: [
      "Le grand retour d'Aminata Sow Fall au roman, après douze ans de silence.",
      "Une saga familiale chaleureuse, de la misère à la réussite.",
      "Une critique franche de l'hypocrisie sociale.",
    ],
    year: 2017,
    publisher: "Le Serpent à plumes",
    pages: 120,
    isbn: "9791035600068",
    format: null,
    awards: [],
    outOfPrint: true,
  }),

  // ---------------------------------------------------------------- David Diop
  livre({
    slug: "1889-l-attraction-universelle",
    title: "1889, l'Attraction universelle",
    contributors: [davidDiop],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "exil"],
    summary:
      "En 1889, onze Sénégalais quittent leur pays pour participer à l'Exposition universelle de Paris. Le voyage tourne court : la délégation échoue à Bordeaux, dans un petit cirque. Son directeur veut les exhiber aux côtés de ses animaux exotiques dans ce qu'il appelle un « spectacle de nègres ». Quelques Bordelais, dont une jeune femme et un jeune médecin, s'opposent à cette mise en scène.",
    whyRead: [
      "Le premier roman de l'auteur de Frère d'âme.",
      "Un épisode méconnu des « zoos humains » de la fin du XIXe siècle.",
      "Une galerie de personnages qui rêvent tous de s'élever.",
    ],
    year: 2012,
    publisher: "L'Harmattan",
    pages: 221,
    isbn: "9782296962101",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-porte-du-voyage-sans-retour",
    title: "La Porte du voyage sans retour",
    subtitle: "ou les cahiers secrets de Michel Adanson",
    contributors: [davidDiop],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "colonisation", "amour", "histoire"],
    summary:
      "Après la mort du botaniste Michel Adanson, sa fille découvre des cahiers qu'il avait tenus en secret. Jeune homme, vers 1750, il avait passé plusieurs années au Sénégal pour en étudier les plantes. Il y avait entendu parler d'une jeune femme, Maram, qui aurait échappé à l'esclavage, et s'était lancé à sa recherche. Ce voyage l'avait transformé et lui avait ouvert les yeux sur la traite.",
    whyRead: [
      "Un roman d'aventure et d'amour au temps de la traite négrière.",
      "Le Sénégal du XVIIIe siècle, vu par un savant européen ébranlé.",
      "Le troisième roman de David Diop, après Frère d'âme.",
    ],
    year: 2021,
    publisher: "Points",
    pages: 252,
    isbn: "9782757896495",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-pays-de-reve",
    title: "Le Pays de Rêve",
    contributors: [davidDiop],
    genre: "jeunesse",
    audience: "ado",
    themes: ["contes", "enfance", "famille"],
    summary:
      "Rêve est une orpheline dont les parents ont été tués par des soldats. Sa grand-mère l'élève dans un bidonville et la cache sous des haillons, pour que sa beauté n'attire pas les convoitises. Elle lui promet qu'à sa mort, elle lui donnera les alliances en or de ses parents pour partir à la découverte du monde. Mais Rêve n'a pas envie d'attendre.",
    whyRead: [
      "David Diop écrit pour les jeunes un conte poétique et grave.",
      "Un récit court sur l'injustice du monde et le désir d'en sortir.",
      "Une héroïne déterminée qui refuse d'attendre son destin.",
    ],
    year: 2024,
    publisher: "Rageot",
    pages: null,
    isbn: "9782700281347",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ou-s-adosse-le-ciel",
    title: "Où s'adosse le ciel",
    contributors: [davidDiop],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "spiritualite", "tradition", "exil"],
    summary:
      "À la fin du XIXe siècle, Bilal Seck revient de La Mecque quand une épidémie de choléra le retarde, et son maître, craignant la contagion, l'abandonne en chemin. Bilal est le soixante-treizième griot de sa lignée et doit transmettre la mémoire de sa famille avant qu'elle ne se perde. Il se souvient d'un très ancien voyage : celui d'un groupe d'Égyptiens qui, guidés par un grand prêtre d'Osiris, partirent vers l'ouest, jusqu'au Sénégal. Deux récits séparés par des siècles se répondent.",
    whyRead: [
      "Une fresque qui relie l'Égypte ancienne et le Sénégal.",
      "Le rôle du griot, gardien de la mémoire, au cœur du roman.",
      "Un grand roman d'aventure sur la migration des peuples et le sacré.",
    ],
    year: 2025,
    publisher: "Julliard",
    pages: null,
    isbn: "9782260057307",
    format: "grand-format",
    awards: [],
  }),

  // ---------------------------------------------------------------- Birago Diop
  livre({
    slug: "les-nouveaux-contes-d-amadou-koumba",
    title: "Les Nouveaux Contes d'Amadou Koumba",
    contributors: [biragoDiop],
    genre: "contes",
    audience: "adulte",
    themes: ["contes", "tradition", "humour"],
    summary:
      "Onze ans après son premier recueil, Birago Diop retrouve le griot Amadou Koumba et transcrit treize nouveaux contes. On y croise Mor Lam, l'homme trop avare pour partager un os avec son ami, Bouki l'hyène toujours dupée, des filles mal élevées et des orphelines courageuses. Chaque conte, drôle ou cruel, porte une leçon de sagesse. La langue garde la saveur de la parole dite à la veillée.",
    whyRead: [
      "La suite des célèbres Contes d'Amadou Koumba.",
      "Contient « L'Os », adapté au théâtre par Peter Brook.",
      "Des contes à lire seul ou à voix haute, en famille.",
    ],
    year: 1958,
    publisher: "Présence Africaine",
    pages: 188,
    isbn: "9782708700536",
    format: null,
    awards: [],
  }),
  livre({
    slug: "leurres-et-lueurs",
    title: "Leurres et lueurs",
    contributors: [biragoDiop],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "tradition", "identite"],
    summary:
      "Seul recueil de poèmes de Birago Diop, Leurres et lueurs rassemble des textes écrits sur plus de trente ans. Le poète y fait dialoguer la culture française de sa formation et l'inspiration africaine. On y trouve « Souffles », où les morts ne sont jamais partis : ils vivent dans l'arbre, l'eau et le vent. Un recueil bref, musical, qui se lit et se dit.",
    whyRead: [
      "Le recueil qui contient « Souffles », poème parmi les plus connus d'Afrique.",
      "Une poésie musicale, entre tradition orale et vers français.",
      "Un livre court, idéal pour découvrir Birago Diop poète.",
    ],
    year: 1960,
    publisher: "Présence Africaine",
    pages: 83,
    isbn: "9782708706194",
    format: null,
    awards: [],
  }),
  livre({
    slug: "contes-et-lavanes",
    title: "Contes et lavanes",
    contributors: [biragoDiop],
    genre: "contes",
    audience: "adulte",
    themes: ["contes", "tradition", "humour"],
    summary:
      "Troisième recueil de Birago Diop, Contes et lavanes puise à nouveau dans la tradition orale wolof, recueillie auprès des griots et des bergers. On y retrouve Leuk le lièvre, malin et farceur, et Bouki l'hyène, vorace et sotte, dans un bestiaire qui rappelle le Roman de Renart. Les animaux s'y affrontent à coups de ruses. Derrière le rire, chaque histoire transmet une sagesse de la brousse.",
    whyRead: [
      "Leuk le lièvre et Bouki l'hyène dans leurs meilleures ruses.",
      "Grand prix littéraire d'Afrique noire 1964.",
      "La sagesse de la brousse sénégalaise, servie par une langue savoureuse.",
    ],
    year: 1963,
    publisher: "Présence Africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1964 }],
    outOfPrint: true,
  }),
  livre({
    slug: "l-os-de-mor-lam",
    title: "L'Os de Mor Lam",
    contributors: [biragoDiop],
    genre: "theatre",
    audience: "adulte",
    themes: ["contes", "humour", "tradition"],
    summary:
      "Dans un village frappé par la disette, chacun partage le peu qu'il a. Seul Mor Lam refuse : il garde jalousement pour lui un os à moelle. Quand son ami Moussa arrive pour passer quelques jours chez lui, Mor Lam imagine une ruse énorme pour ne pas avoir à partager. Birago Diop tire de l'un de ses contes une farce à la fois drôle et cruelle sur l'avarice.",
    whyRead: [
      "Une farce irrésistible sur l'avarice, tirée d'un conte de Birago Diop.",
      "Mise en scène par Peter Brook au Festival d'Avignon en 1979.",
      "Une pièce courte, facile à lire et à jouer.",
    ],
    year: 1977,
    publisher: "Nouvelles Éditions africaines",
    pages: 72,
    isbn: "9782723601245",
    format: null,
    awards: [],
    outOfPrint: true,
    adaptations: [{ kind: "théâtre", title: "L'Os", year: 1979, by: "Peter Brook" }],
  }),
  livre({
    slug: "la-plume-raboutee",
    title: "La Plume raboutée",
    contributors: [biragoDiop],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "colonisation", "ecole", "histoire"],
    summary:
      "Premier tome des mémoires de Birago Diop, La Plume raboutée raconte son enfance à Dakar et ses années au lycée Faidherbe de Saint-Louis. En 1928, il part étudier la médecine vétérinaire à Toulouse, où il se marie. Revenu en Afrique, il sillonne le Soudan français comme vétérinaire de l'administration coloniale. Le livre s'achève au sortir de la Seconde Guerre mondiale, après des années parisiennes où il côtoie Senghor et Damas.",
    whyRead: [
      "L'enfance dakaroise d'un grand conteur, racontée avec humour.",
      "Un témoignage précieux sur l'Afrique coloniale des années 1930.",
      "La rencontre avec les poètes de la négritude.",
    ],
    year: 1978,
    publisher: "Présence Africaine",
    pages: 253,
    isbn: "9782708703537",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "a-rebrousse-temps",
    title: "À rebrousse-temps",
    contributors: [biragoDiop],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "histoire", "travail"],
    summary:
      "Deuxième tome des mémoires de Birago Diop, ce livre couvre les années 1945 à 1950. Vétérinaire de l'administration coloniale, il est affecté en Côte d'Ivoire puis en Haute-Volta, où il dirige le service de l'élevage. Il raconte ses tournées, ses collègues et les nombreuses personnes croisées en chemin. On y retrouve l'œil malicieux et le goût de l'anecdote du conteur.",
    whyRead: [
      "La suite des mémoires d'un témoin attentif de l'Afrique coloniale.",
      "Des portraits pleins d'humour, croqués sur le vif.",
      "Une Afrique de l'Ouest d'après-guerre vue de l'intérieur.",
    ],
    year: 1982,
    publisher: "Présence Africaine",
    pages: 205,
    isbn: "9782708703995",
    format: null,
    awards: [],
  }),
  livre({
    slug: "a-rebrousse-gens",
    title: "À rebrousse-gens",
    subtitle: "Épissures, entrelacs et reliefs",
    contributors: [biragoDiop],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "histoire", "travail"],
    summary:
      "Troisième tome des mémoires de Birago Diop, À rebrousse-gens revient surtout sur les années 1950 à 1956. Toujours vétérinaire au service de l'élevage de l'Afrique-Occidentale française, il travaille notamment en Mauritanie. L'auteur y fait défiler les gens qu'il a connus et cherche à les montrer sous un jour plus juste. Un livre de souvenirs et de rencontres, plein de verve.",
    whyRead: [
      "Les années mauritaniennes d'un écrivain vétérinaire.",
      "Une galerie de portraits de la fin de l'époque coloniale.",
      "Le style vif et malicieux de l'auteur des Contes d'Amadou Koumba.",
    ],
    year: 1985,
    publisher: "Présence Africaine",
    pages: 235,
    isbn: "9782708704442",
    format: null,
    awards: [],
  }),

  // ---------------------------------------------------------------- Ken Bugul
  livre({
    slug: "cendres-et-braises",
    title: "Cendres et braises",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "exil", "identite"],
    summary:
      "Marie, jeune Sénégalaise installée en France, vit une passion amoureuse. Peu à peu, l'amour se change en emprise, et les coups remplacent les promesses. Elle s'isole, refuse l'aide qu'on lui tend et reste prisonnière de cette relation. Deuxième volet de la trilogie autobiographique ouverte par Le Baobab fou, le roman raconte aussi la longue route pour se réconcilier avec soi-même.",
    whyRead: [
      "La suite du Baobab fou, entre Paris et le Sénégal.",
      "Un récit sans fard sur la violence conjugale et l'emprise.",
      "Une quête de soi grave et lumineuse à la fois.",
    ],
    year: 1994,
    publisher: "L'Harmattan",
    pages: 190,
    isbn: "9782738421371",
    format: null,
    awards: [],
  }),
  livre({
    slug: "riwan-ou-le-chemin-de-sable",
    title: "Riwan ou le chemin de sable",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "tradition", "identite"],
    summary:
      "Revenue au Sénégal après de longues années en Europe, la narratrice, une intellectuelle, cherche sa place dans son village. Elle se rapproche d'un Serigne, guide religieux respecté, et devient l'une de ses nombreuses épouses. Dans la concession, elle découvre la vie des autres femmes, dont la toute jeune Rama, et de Riwan, un fou que le Serigne a recueilli. Le roman interroge sans détour la polygamie, la foi et la liberté des femmes.",
    whyRead: [
      "Grand prix littéraire d'Afrique noire 1999.",
      "La vie d'une concession polygame racontée de l'intérieur.",
      "Le troisième volet de la trilogie autobiographique de Ken Bugul.",
    ],
    year: 1999,
    publisher: "Présence Africaine",
    pages: 223,
    isbn: "9782708707306",
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1999 }],
  }),
  livre({
    slug: "la-folie-et-la-mort",
    title: "La Folie et la Mort",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "femmes", "ville"],
    summary:
      "Dans un pays imaginaire, le chef suprême a décidé d'éliminer ceux qui pensent comme ceux qui ne pensent pas. Mom Dioum, une jeune femme, et Fatou, son amie d'enfance, tentent de survivre dans ce chaos. Autour d'elles se croisent d'autres destins, pris dans la violence, la misère et la folie. Le roman est une allégorie féroce d'un continent malade de ses dirigeants.",
    whyRead: [
      "Une allégorie politique violente et visionnaire.",
      "Ken Bugul quitte l'autobiographie pour une fable sur l'Afrique.",
      "Un roman coup de poing, qui ne laisse pas indemne.",
    ],
    year: 2000,
    publisher: "Présence Africaine",
    pages: 235,
    isbn: "9782708707177",
    format: null,
    awards: [],
  }),
  livre({
    slug: "de-l-autre-cote-du-regard",
    title: "De l'autre côté du regard",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "femmes", "enfance", "independances"],
    summary:
      "Marie a toujours souffert de n'avoir pas été aimée par sa mère, partie quand elle était enfant. Après la mort de celle-ci, elle tente enfin de comprendre cette blessure. Elle remonte l'histoire de sa famille, des dernières années de la colonisation aux débuts de l'indépendance. Ken Bugul livre un dialogue bouleversant entre une fille et une mère disparue.",
    whyRead: [
      "Un livre unique sur la douleur de ne pas avoir été aimée.",
      "Une histoire familiale sénégalaise, de la colonie à l'indépendance.",
      "Peut-être le livre le plus intime de Ken Bugul.",
    ],
    year: 2003,
    publisher: "Le Serpent à plumes",
    pages: null,
    isbn: "9782842614805",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "rue-felix-faure",
    title: "Rue Félix-Faure",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "femmes", "spiritualite"],
    summary:
      "Un matin, dans la rue Félix-Faure à Dakar, on découvre un corps mutilé sur le trottoir. Deux policiers peu doués mènent l'enquête, tandis que la vie de la rue continue son vacarme habituel. Les habitants s'en mêlent, guidés par quatre mystérieuses silhouettes voilées. Peu à peu se dessine la vérité sur la victime et sur ceux qu'elle a exploités.",
    whyRead: [
      "Une enquête policière écrite comme un poème.",
      "Une rue de Dakar vivante, bruyante, inoubliable.",
      "Une charge contre les faux guides qui exploitent les femmes.",
    ],
    year: 2005,
    publisher: "Amalion",
    pages: 259,
    isbn: "9782359260960",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "la-piece-d-or",
    title: "La Pièce d'or",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "politique", "tradition"],
    summary:
      "À Yakar, ville africaine en plein bouleversement, tout le monde court après la pièce d'or, objet mythique censé apporter richesse, bonheur et peut-être l'immortalité. Moïse quitte sa terre dans l'espoir d'une vie meilleure, comme tant d'autres qui désertent les villages. Mais la ville ne tient pas ses promesses et révèle sa violence et sa solitude. Ken Bugul mêle tradition, fable et touches de science-fiction pour dire les illusions d'un continent.",
    whyRead: [
      "Une fable sociale où surgit le fantastique.",
      "Un regard critique sur l'exode rural et les faux espoirs.",
      "Un roman singulier dans l'œuvre de Ken Bugul.",
    ],
    year: 2006,
    publisher: "Ubu",
    pages: 315,
    isbn: "9782351970003",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "mes-hommes-a-moi",
    title: "Mes hommes à moi",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "femmes", "identite"],
    summary:
      "La narratrice fait le compte de tous les hommes qui ont traversé sa vie. Elle se demande pourquoi ses amours se sont toujours soldées par une insatisfaction douloureuse. Avec une franchise désarmante, elle parle de désir, de sexualité et de solitude. Et elle remonte, encore une fois, à la blessure de l'abandon maternel.",
    whyRead: [
      "Une parole de femme libre sur le désir et l'amour.",
      "Une introspection sincère, souvent bouleversante.",
      "La voix sans tabou qui a fait la réputation de Ken Bugul.",
    ],
    year: 2008,
    publisher: "Présence Africaine",
    pages: 252,
    isbn: "9782708709928",
    format: null,
    awards: [],
  }),
  livre({
    slug: "cacophonie",
    title: "Cacophonie",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "ville"],
    summary:
      "Sali, veuve, vit depuis sept ans dans une grande maison jaune d'une ville au bord de l'océan. Elle y espérait un refuge après la mort de son mari, mais sa belle-famille la juge trop âgée et indésirable. Isolée, elle se perd dans le flot de ses pensées et le vacarme de la ville. Quelques voisins, un gardien et un chauffeur de taxi deviennent ses seuls liens avec le monde.",
    whyRead: [
      "Un long monologue intérieur, intense et poétique.",
      "Le portrait d'une femme âgée que la société met de côté.",
      "Ken Bugul au plus près de la solitude.",
    ],
    year: 2014,
    publisher: "Présence Africaine",
    pages: 200,
    isbn: "9782708708631",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "le-trio-bleu",
    title: "Le Trio bleu",
    contributors: [kenBugul],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "humour"],
    summary:
      "Góora vit seul et dans la précarité en Occident, mais il n'a qu'une idée : retrouver son Jolof natal et Jóojo, l'amour de sa jeunesse. Il se fait construire une villa au pays et prépare son retour. Avec ses amis François et Suleiman, il forme un trio d'hommes cabossés, partis pour fuir la pauvreté, les guerres ou l'injustice. Mais rien ne se passe comme prévu.",
    whyRead: [
      "Un roman sur l'exil et le rêve du retour au pays.",
      "Trois amis attachants, unis par des destins brisés.",
      "Un texte mordant, où l'humour et la poésie sauvent de tout.",
    ],
    year: 2022,
    publisher: "Présence Africaine",
    pages: 251,
    isbn: "9782708709775",
    format: null,
    awards: [],
  }),

  // ---------------------------------------------------------------- Felwine Sarr
  livre({
    slug: "dahij",
    title: "Dahij",
    contributors: [felwineSarr],
    genre: "recit",
    audience: "adulte",
    themes: ["spiritualite", "identite"],
    summary:
      "Dahij, c'est « djihad » lu à l'envers : le titre annonce un combat intérieur. Dans ce premier livre, Felwine Sarr raconte sa lutte pour se libérer des rôles et des identités qu'on lui a assignés. Ce n'est pas une confession mais un corps-à-corps avec soi-même, pour gagner sa liberté de penser et de vivre. Une écriture vive, entre récit, méditation et poésie.",
    whyRead: [
      "Le premier livre de l'auteur d'Afrotopia.",
      "Un « djihad » intérieur pour la liberté, à rebours de tous les clichés.",
      "Une prose ardente, entre récit et méditation.",
    ],
    year: 2009,
    publisher: "Gallimard",
    pages: null,
    isbn: "9782070122677",
    format: null,
    awards: [],
  }),
  livre({
    slug: "105-rue-carnot",
    title: "105, rue Carnot",
    contributors: [felwineSarr],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "ville", "famille"],
    summary:
      "Felwine Sarr revient sur son enfance sénégalaise à travers de courts récits. Des quartiers, des villes, des visages défilent : voisins, camarades, figures du quotidien. Chaque scène, sobre et tendre, tire une leçon de vie d'un fait ordinaire. L'enfance y apparaît comme un royaume.",
    whyRead: [
      "Une enfance au Sénégal racontée avec tendresse et humour.",
      "Des récits courts, simples et lumineux.",
      "Une porte d'entrée intime dans l'œuvre de Felwine Sarr.",
    ],
    year: 2011,
    publisher: "Mémoire d'encrier",
    pages: 75,
    isbn: "9782897129873",
    format: null,
    awards: [],
  }),
  livre({
    slug: "meditations-africaines",
    title: "Méditations africaines",
    contributors: [felwineSarr],
    genre: "essai",
    audience: "adulte",
    themes: ["spiritualite", "identite"],
    summary:
      "Au bord du fleuve, à Saint-Louis du Sénégal, un homme pense lentement au rythme de l'eau. Ce livre rassemble des aphorismes et de courtes réflexions sur l'existence et le monde. Felwine Sarr invite à penser le monde à partir de l'Afrique, sans hâte. Un livre à ouvrir au hasard et à relire.",
    whyRead: [
      "Des pensées brèves à savourer une à une.",
      "La sagesse d'un penseur qui prend le temps.",
      "Un prélude poétique à Afrotopia.",
    ],
    year: 2012,
    publisher: "Mémoire d'encrier",
    pages: 108,
    isbn: "9782897127039",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ishindenshin",
    title: "Ishindenshin",
    subtitle: "De mon âme à ton âme",
    contributors: [felwineSarr],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "identite"],
    summary:
      "Le titre est une expression japonaise qui désigne la transmission directe, d'âme à âme, sans passer par les mots. Ce recueil hybride rassemble une pièce de théâtre, « Sur la barrière », des poèmes, des textes de chansons et un essai, « Pourquoi je suis poète ! ». On y découvre les multiples visages de Felwine Sarr : poète, musicien, penseur. Un livre au carrefour des genres.",
    whyRead: [
      "Théâtre, poèmes et chansons réunis en un seul livre.",
      "Le Felwine Sarr poète et musicien, moins connu que l'essayiste.",
      "Un recueil bref et libre, à lire par fragments.",
    ],
    year: 2017,
    publisher: "Mémoire d'encrier",
    pages: 66,
    isbn: "9782897125165",
    format: null,
    awards: [],
  }),
  livre({
    slug: "habiter-le-monde",
    title: "Habiter le monde",
    subtitle: "Essai de politique relationnelle",
    contributors: [felwineSarr],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite"],
    summary:
      "Comment vivre ensemble dans un monde gagné par la méfiance et l'hostilité ? Dans ce court essai, Felwine Sarr propose de mesurer le progrès à la qualité des relations que nous tissons avec les autres et avec le vivant. Il appelle à réinventer la politique, la démocratie et même le langage. Une utopie active, qui fait de l'ouverture à l'autre le cœur du projet commun.",
    whyRead: [
      "Un plaidoyer bref et clair pour une politique de la relation.",
      "Une pensée africaine qui s'adresse au monde entier.",
      "Le prolongement naturel d'Afrotopia.",
    ],
    year: 2017,
    publisher: "Mémoire d'encrier",
    pages: 59,
    isbn: "9782897125196",
    format: null,
    awards: [],
  }),
  livre({
    slug: "restituer-le-patrimoine-africain",
    title: "Restituer le patrimoine africain",
    contributors: [felwineSarr, { role: "auteur", name: "Bénédicte Savoy", authorSlug: null }],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "histoire", "politique"],
    summary:
      "En 2017, à Ouagadougou, le président Emmanuel Macron annonce vouloir rendre à l'Afrique des œuvres de son patrimoine. Il confie à Felwine Sarr et à l'historienne de l'art Bénédicte Savoy une mission de réflexion. Ce livre en est le fruit : il retrace les pillages de l'époque coloniale, évalue les collections françaises et raconte les demandes africaines restées sans réponse. Il propose enfin des mesures concrètes pour organiser les restitutions.",
    whyRead: [
      "Le rapport qui a relancé le débat mondial sur les restitutions.",
      "Une histoire claire des objets africains emportés en Europe.",
      "Un texte qui a ouvert la voie aux restitutions au Bénin et au Sénégal.",
    ],
    year: 2018,
    publisher: "Philippe Rey",
    pages: null,
    isbn: "9782848767253",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-saveur-des-derniers-metres",
    title: "La Saveur des derniers mètres",
    contributors: [felwineSarr],
    genre: "recit",
    audience: "adulte",
    themes: ["exil", "identite", "spiritualite"],
    summary:
      "Felwine Sarr raconte ses voyages, de Kampala à Mexico, du Caire à Port-au-Prince, de Lisbonne à Istanbul. Il note ce qu'il voit, entend et goûte : un fado dans une rue, des femmes qui marchent sur l'eau vers une île, la fin d'une course à pied. L'île de Niodior, où il est né, reste le point de départ et de retour. Car voyager, pour lui, c'est surtout revenir à soi.",
    whyRead: [
      "Un carnet de voyage poétique et attentif.",
      "Un éloge de la rencontre et de l'inattendu.",
      "Des textes courts, à emporter partout.",
    ],
    year: 2021,
    publisher: "Philippe Rey",
    pages: null,
    isbn: "9782848768540",
    format: null,
    awards: [],
  }),
  livre({
    slug: "traces",
    title: "Traces",
    subtitle: "Discours aux Nations africaines",
    contributors: [felwineSarr],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "identite", "independances"],
    summary:
      "Un homme revient sur son continent après un long voyage. Face à un public, il prend la parole et raconte le monde tel qu'il l'a vu et tel qu'il l'imagine. Son discours, porté par une seule voix, s'adresse aux nations africaines sans complaisance mais avec espoir. Un texte écrit pour la scène, qui prolonge la pensée d'Afrotopia.",
    whyRead: [
      "La pensée de Felwine Sarr portée par une voix de théâtre.",
      "Un monologue d'espoir adressé à tout un continent.",
      "Un texte bref, à lire d'une traite ou à dire à voix haute.",
    ],
    year: 2021,
    publisher: "Actes Sud-Papiers",
    pages: null,
    isbn: "9782330147938",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-lieux-qu-habitent-mes-reves",
    title: "Les Lieux qu'habitent mes rêves",
    contributors: [felwineSarr],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "spiritualite", "tradition", "famille"],
    summary:
      "Bouhel et Fodé sont jumeaux, comme une même âme dans deux corps. Curieux du monde et passionné de livres, Bouhel quitte le Sénégal pour Orléans, où il rencontre Ulga, une jeune Polonaise. Au village, le vieux Ngof choisit Fodé pour lui succéder comme maître des initiations. Les deux frères suivent des chemins opposés, mais une même quête semble les guider.",
    whyRead: [
      "Un roman entre le Sénégal et la France, entre deux mondes.",
      "Deux jumeaux, deux destins, une même recherche de sens.",
      "Une écriture onirique sur l'amour, la mort et la transmission.",
    ],
    year: 2022,
    publisher: "Zulma",
    pages: 181,
    isbn: "9791038702516",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-bouddhisme-est-ne-a-colobane",
    title: "Le bouddhisme est né à Colobane",
    contributors: [felwineSarr],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["amour", "ville", "spiritualite"],
    summary:
      "Un homme s'inquiète de voir son couple s'essouffler, une femme hésite entre son cœur et la raison familiale, des amis pleurent un musicien disparu. Dans ces nouvelles, les personnages cherchent un amour absolu qui toujours se dérobe. De Dakar à Abidjan, de Nantes à Ndangane, la musique de Toumani Diabaté, Wasis Diop ou Cheikh Lô les accompagne. Un recueil qui invite à se laisser traverser par la vie.",
    whyRead: [
      "Des nouvelles sur l'amour, le manque et la passion.",
      "Une bande-son de grands musiciens d'Afrique de l'Ouest.",
      "Une langue limpide, entre sagesse et sensualité.",
    ],
    year: 2024,
    publisher: "Philippe Rey",
    pages: null,
    isbn: "9782384820818",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-fabrique-du-present",
    title: "La Fabrique du présent",
    subtitle: "Pour des utopies en actes",
    contributors: [felwineSarr],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "independances", "identite"],
    summary:
      "Dans Afrotopia, Felwine Sarr invitait l'Afrique à élargir l'horizon de ses possibles. Ce nouvel essai pose la question suivante : comment faire entrer ces utopies dans le présent ? Six décennies après les indépendances, il esquisse une « économie politique de la dignité » fondée sur les savoirs, la politique, l'économie et les imaginaires. Face à un monde de plus en plus brutal, il plaide pour une hospitalité à l'échelle de la planète.",
    whyRead: [
      "La suite attendue d'Afrotopia.",
      "Des pistes concrètes pour une vie digne en Afrique.",
      "Une pensée de l'hospitalité face à un monde brutal.",
    ],
    year: 2026,
    publisher: "Philippe Rey",
    pages: null,
    isbn: "9782384823000",
    format: null,
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "le-revenant",
  "l-appel-des-arenes",
  "l-ex-pere-de-la-nation",
  "le-jujubier-du-patriarche",
  "douceurs-du-bercail",
  "un-grain-de-vie-et-d-esperance",
  "festins-de-la-detresse",
  "l-empire-du-mensonge",
  "1889-l-attraction-universelle",
  "la-porte-du-voyage-sans-retour",
  "le-pays-de-reve",
  "ou-s-adosse-le-ciel",
  "les-nouveaux-contes-d-amadou-koumba",
  "leurres-et-lueurs",
  "contes-et-lavanes",
  "l-os-de-mor-lam",
  "la-plume-raboutee",
  "a-rebrousse-temps",
  "a-rebrousse-gens",
  "cendres-et-braises",
  "riwan-ou-le-chemin-de-sable",
  "la-folie-et-la-mort",
  "de-l-autre-cote-du-regard",
  "rue-felix-faure",
  "la-piece-d-or",
  "mes-hommes-a-moi",
  "cacophonie",
  "le-trio-bleu",
  "dahij",
  "105-rue-carnot",
  "meditations-africaines",
  "ishindenshin",
  "habiter-le-monde",
  "restituer-le-patrimoine-africain",
  "la-saveur-des-derniers-metres",
  "traces",
  "les-lieux-qu-habitent-mes-reves",
  "le-bouddhisme-est-ne-a-colobane",
  "la-fabrique-du-present",
];
