/**
 * Lot 02b : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Auteurs : Marie NDiaye, Cheikh Anta Diop, Amadou Hampâté Bâ, Yambo Ouologuem (liste : docs/listes/lot-02.md).
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string | null) => ({ role: "auteur" as const, name, authorSlug });
const ndiaye = auteur("Marie NDiaye", "marie-ndiaye");
const diop = auteur("Cheikh Anta Diop", "cheikh-anta-diop");
const ba = auteur("Amadou Hampâté Bâ", "amadou-hampate-ba");
const ouologuem = auteur("Yambo Ouologuem", "yambo-ouologuem");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Marie NDiaye
  livre({
    slug: "quant-au-riche-avenir",
    title: "Quant au riche avenir",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "amour", "famille"],
    summary:
      "Le jeune Z, orphelin, vit auprès d'une tante sérieuse et distante qu'il appelle simplement Tante. Il tient une sorte de journal où il s'efforce de ne rien inventer, tout en sachant qu'il romance malgré lui. Il y analyse sans fin l'amour qu'il porte à une amie restée en province, qui répond trop rarement à ses lettres. Entre orgueil, exigence et peur de la médiocrité, il se demande ce que sera sa vie d'adulte. Le premier roman de Marie NDiaye, écrit à dix-sept ans, suit les méandres d'une conscience adolescente.",
    whyRead: [
      "Le premier roman de Marie NDiaye, écrit quand elle était lycéenne.",
      "Une plongée minutieuse dans les pensées d'un adolescent exigeant.",
      "Déjà une phrase longue, souple et ironique, reconnaissable entre toutes.",
    ],
    year: 1985,
    publisher: "Éditions de Minuit",
    pages: 120,
    isbn: "9782707310187",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "comedie-classique",
    title: "Comédie classique",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "amour", "humour"],
    summary:
      "Un vendredi matin d'automne, un jeune homme qui se rêve écrivain se réveille pour une journée qui va tourner à l'épreuve. Son cousin Georges débarque de province, sa fiancée se laisse séduire par un piètre séducteur, et sa famille ne cesse de se rappeler à lui. Entre deux contrariétés reviennent les souvenirs d'un oncle et d'une grand-mère. Tout le roman tient en une seule phrase, qui court du matin jusqu'à minuit en respectant, pour s'en amuser, les règles du théâtre classique.",
    whyRead: [
      "Un roman entier écrit en une seule phrase : une prouesse qui reste légère.",
      "Une journée de malheurs racontée avec un humour pince-sans-rire.",
      "Le deuxième livre de Marie NDiaye, paru quand elle avait vingt ans.",
    ],
    year: 1987,
    publisher: "Folio",
    pages: 128,
    isbn: "9782070451685",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-femme-changee-en-buche",
    title: "La Femme changée en bûche",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "contes", "femmes"],
    summary:
      "Trompée et quittée par son mari, une jeune femme se venge de la manière la plus terrible, grâce à un talisman que lui a autrefois procuré le Diable. Perdue pour le monde des hommes, elle décide de retourner vivre dans la demeure du Diable, dont elle garde le souvenir d'un palais somptueux. Mais l'endroit a bien changé : tout y est délabré, négligé, les vieux rites sont oubliés. Ce conte noir et ironique revisite le mythe de la métamorphose et la descente aux enfers.",
    whyRead: [
      "Un conte fantastique où le Diable lui-même semble fatigué.",
      "Une variation audacieuse sur les mythes de métamorphose.",
      "Un court roman qui mêle effroi, ironie et merveilleux.",
    ],
    year: 1989,
    publisher: "Éditions de Minuit",
    pages: 160,
    isbn: "9782707312853",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "en-famille",
    title: "En famille",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "identite", "femmes"],
    summary:
      "Fanny arrive dans la maison familiale le jour où l'on fête sa grand-mère, mais personne ne veut la reconnaître, et les chiens eux-mêmes se jettent sur elle. Pour gagner enfin sa place, elle décide de retrouver tante Léda, partie depuis des années et dont on parle avec regret. Accompagnée de son cousin Eugène, elle traverse des villages hostiles, va de son père à sa mère, de petit travail en humiliation. Le roman ne dit jamais ce qui rend Fanny si étrangère aux siens : c'est tout le trouble de ce récit d'exclusion.",
    whyRead: [
      "Un conte cruel sur le désir d'être accepté par les siens.",
      "Le roman où s'affirme l'étrangeté si particulière de Marie NDiaye.",
      "Une question jamais résolue, qui hante longtemps après la lecture.",
    ],
    year: 1991,
    publisher: "Éditions de Minuit (Double)",
    pages: 320,
    isbn: "9782707320025",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "un-temps-de-saison",
    title: "Un temps de saison",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "identite"],
    summary:
      "Herman, professeur de mathématiques parisien, a prolongé d'une journée ses vacances d'été dans un village de campagne. Ce jour-là, sa femme Rose et leur petit garçon partent chercher du lait à la ferme et ne reviennent pas. Avec la fin de la saison, l'automne s'abat sur la région : une pluie glaciale, un froid qui ne cessera plus. Herman cherche sa famille auprès de villageois indifférents ou hostiles, et comprend peu à peu qu'il devra se fondre parmi eux pour avoir une chance de la retrouver.",
    whyRead: [
      "Un roman court et inquiétant, entre fable et cauchemar.",
      "Une satire glaçante des Parisiens en vacances et des gens du pays.",
      "Une porte d'entrée idéale dans l'univers de Marie NDiaye.",
    ],
    year: 1994,
    publisher: "Folio",
    pages: 144,
    isbn: "9782073116956",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-sorciere",
    title: "La Sorcière",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "contes"],
    summary:
      "Lucie est une sorcière, mais une sorcière sans grand talent, qui vit dans un lotissement de province avec son mari Pierrot et leurs jumelles de douze ans, Maud et Lise. Malgré l'interdiction de son mari, elle décide de transmettre son don à ses filles, qui se révèlent bien plus douées qu'elle. Quand Pierrot s'en va, Lucie s'épuise à tenir ensemble une famille qui lui échappe, entre une mère au génie inquiétant et des filles prêtes à prendre leur envol. Un roman drôle et triste sur ce que les mères transmettent.",
    whyRead: [
      "La magie vue comme un héritage familial encombrant, avec humour.",
      "Un portrait touchant d'une mère dépassée par ses filles.",
      "Adapté en bande dessinée par Benoît Guillaume en 2018.",
    ],
    year: 1996,
    publisher: "Folio",
    pages: 176,
    isbn: "9782073045188",
    format: "poche",
    awards: [],
    adaptations: [{ kind: "BD", title: "La Sorcière", year: 2018, by: "Benoît Guillaume" }],
  }),
  livre({
    slug: "la-naufragee",
    title: "La Naufragée",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["exil", "identite", "contes"],
    summary:
      "À l'aube, une créature mi-femme mi-poisson se réveille échouée sur un quai de la Seine, au cœur d'une grande ville qu'elle ne connaît pas. Elle souffre sur le pavé, regrette la mer et ne sait comment retourner vers elle. Ni tout à fait humaine ni tout à fait animale, elle n'est reconnue par personne. Marie NDiaye renverse le mythe des sirènes dans ce récit écrit en dialogue avec les toiles du peintre anglais Turner, reproduites au fil du livre.",
    whyRead: [
      "Le mythe de la sirène, retourné et vu de l'intérieur.",
      "Un beau livre où le texte dialogue avec les tableaux de Turner.",
      "Une variation poétique sur le fait d'être étranger partout.",
    ],
    year: 1999,
    publisher: "Flohic",
    pages: 89,
    isbn: "9782842340629",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "hilda",
    title: "Hilda",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["travail", "femmes", "politique"],
    summary:
      "Mme Lemarchand, bourgeoise qui se dit de gauche et mère de trois enfants, cherche une femme pour tenir sa maison et lui tenir compagnie. Elle choisit Hilda, dont on lui a vanté la beauté et le sérieux, et convoque son mari Franck pour négocier. Elle prétend vouloir éduquer Hilda, en faire son amie, mais son désir de la posséder ne cesse de grandir. Hilda ne paraît jamais : toute la pièce est l'affrontement entre la patronne et le mari, autour d'une femme absente.",
    whyRead: [
      "La première pièce de Marie NDiaye, sur la domination déguisée en bienveillance.",
      "Un personnage-titre qu'on ne voit jamais, et qui pourtant résiste.",
      "Un texte souvent mis en scène, tendu comme un thriller.",
    ],
    year: 1999,
    publisher: "Éditions de Minuit",
    pages: 96,
    isbn: "9782707316615",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-diablesse-et-son-enfant",
    title: "La Diablesse et son enfant",
    contributors: [ndiaye],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "famille", "identite"],
    summary:
      "La nuit, on entend un petit bruit de sabots dans les rues du village : c'est la diablesse, qui va de maison en maison à la recherche de son enfant perdu. Dès qu'ils aperçoivent ses pieds de chèvre, les habitants lui claquent la porte au nez et éteignent les lumières. Elle, pourtant, ne veut de mal à personne : elle se souvient qu'autrefois elle avait un enfant, une maison, et de vrais pieds. Un conte doux et grave sur la peur de l'autre, pour les lecteurs à partir de 6 ans.",
    whyRead: [
      "Un premier roman à lire seul ou à deux, dès 6 ans.",
      "Un conte qui fait réfléchir à la rumeur et au rejet de la différence.",
      "La plume de Marie NDiaye, simple et envoûtante, pour les enfants.",
    ],
    year: 2000,
    publisher: "L'École des loisirs (Mouche)",
    pages: null,
    isbn: "9782211208208",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "rosie-carpe",
    title: "Rosie Carpe",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "femmes", "identite"],
    summary:
      "Rose-Marie, dite Rosie, a grandi à Brive-la-Gaillarde entre son frère Lazare et des parents sans chaleur. Devenue adulte, elle travaille dans un hôtel sinistre près de Paris et met au monde Titi, un petit garçon qu'elle peine à aimer. Lorsqu'elle débarque en Guadeloupe avec son fils pour rejoindre Lazare, celui-ci n'est pas venu la chercher à l'aéroport. Commence alors une dérive où Rosie, qui semble ne plus maîtriser sa vie, retrouve des parents méconnaissables.",
    whyRead: [
      "Le roman qui a valu à Marie NDiaye le prix Femina en 2001.",
      "Un portrait bouleversant d'une femme à la dérive.",
      "La Guadeloupe vue loin des cartes postales.",
    ],
    year: 2001,
    publisher: "Éditions de Minuit (Double)",
    pages: 400,
    isbn: "9782707320971",
    format: "poche",
    awards: [{ name: "Prix Femina", year: 2001 }],
  }),
  livre({
    slug: "papa-doit-manger",
    title: "Papa doit manger",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["famille", "identite", "exil"],
    summary:
      "Papa est parti depuis dix ans, et plus personne n'attendait son retour. Le voilà pourtant de nouveau à Courbevoie, l'air riche et étrangement jeune, bien décidé à reprendre sa place auprès de Maman et de leurs deux filles. Il est sûr de son bon droit, sûr qu'on l'aime encore et qu'on lui doit tout. Mais la famille qu'il a abandonnée n'a aucune envie de le nourrir. Une pièce âpre sur le couple, l'abandon et le regard porté sur un homme noir dans une famille blanche.",
    whyRead: [
      "Entrée au répertoire de la Comédie-Française dès sa création en 2003.",
      "Un retour du père qui tourne au règlement de comptes familial.",
      "Des dialogues tranchants, aussi forts à lire qu'à voir.",
    ],
    year: 2003,
    publisher: "Éditions de Minuit",
    pages: 96,
    isbn: "9782707317988",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-paradis-de-prunelle",
    title: "Les Paradis de Prunelle",
    contributors: [ndiaye],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["famille", "enfance", "spiritualite"],
    summary:
      "Cet été-là, Odilon se retrouve seul : sa sœur Prunelle a été emmenée à l'hôpital, et les jours passent sans nouvelles. Un matin, une petite fille qui ressemble à Prunelle vient s'asseoir sur le banc où il l'attend chaque jour. Pâle, les mains froides, elle lui raconte un étrange voyage à travers des paradis où il manque toujours quelque chose. Tandis que ses parents se perdent dans le chagrin, Odilon cherche à comprendre, avec l'aide de sa tante Peggy. Un album grave et délicat sur l'absence, illustré par Pierre Mornet.",
    whyRead: [
      "Un récit sensible pour parler aux enfants de la maladie et de l'absence.",
      "Les illustrations de Pierre Mornet, douces et mystérieuses.",
      "Un livre à partager avec un adulte, plutôt pour les plus grands.",
    ],
    year: 2003,
    publisher: "Albin Michel Jeunesse",
    pages: 42,
    isbn: "9782226140685",
    format: "album",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "tous-mes-amis",
    title: "Tous mes amis",
    contributors: [ndiaye],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["famille", "travail", "identite"],
    summary:
      "Cinq nouvelles composent ce recueil. Un professeur abandonné par les siens emploie comme bonne son ancienne élève, Séverine, et cherche à comprendre pourquoi elle s'acharne à oublier tout ce qu'il lui a appris. Deux amies d'enfance se retrouvent autour du souvenir de Claude François ; un jeune homme sans qualités cherche une femme de la ville qui voudra bien de lui ; une femme abandonnée au bord d'un lac revit sa jeunesse ; une mère veut se séparer de son fils. Partout, des êtres fascinés par ceux qui les dominent.",
    whyRead: [
      "Cinq histoires courtes pour découvrir l'univers de Marie NDiaye.",
      "Des personnages mal aimés, saisis avec une précision cruelle.",
      "Une écriture où le quotidien bascule sans prévenir dans l'étrange.",
    ],
    year: 2004,
    publisher: "Éditions de Minuit",
    pages: 176,
    isbn: "9782707318596",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "les-serpents",
    title: "Les Serpents",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["famille", "femmes"],
    summary:
      "Un 14 Juillet, Mme Diss fait la route jusqu'à la maison de son fils, perdue au milieu des champs de maïs. Elle ne vient pas pour le feu d'artifice : elle veut lui emprunter de l'argent. Mais le fils, enfermé dans la cuisine où il surveille férocement les enfants, refuse de sortir comme de la laisser entrer. Seules ses deux femmes, l'actuelle, France, et l'ancienne, Nancy, ont le droit de franchir la porte. Dans la chaleur de l'été, trois femmes parlent d'un homme qu'on ne voit jamais.",
    whyRead: [
      "Un huis clos à ciel ouvert, étouffant comme une journée de canicule.",
      "Trois femmes face à un homme invisible et tout-puissant.",
      "Une pièce courte, d'une tension saisissante.",
    ],
    year: 2004,
    publisher: "Éditions de Minuit",
    pages: 80,
    isbn: "9782707318565",
    format: null,
    awards: [],
  }),
  livre({
    slug: "rien-d-humain",
    title: "Rien d'humain",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["identite", "ville"],
    summary:
      "Bella revient chez elle après des années d'absence. Avant de partir, elle avait laissé son appartement à Djamila, sa plus vieille amie. Mais Djamila refuse désormais de le lui rendre, soutenue par Ignace, le voisin, qui est amoureux d'elle. Bella ne reconnaît plus son amie et cherche à comprendre qui elle est devenue. Cette courte pièce, écrite sur le thème des fantômes, tient à la fois de l'enquête et de l'histoire de revenants.",
    whyRead: [
      "Une pièce brève, parfaite pour découvrir le théâtre de Marie NDiaye.",
      "Une amitié qui tourne à la lutte pour un appartement.",
      "Une atmosphère d'enquête où les vivants ressemblent à des fantômes.",
    ],
    year: 2004,
    publisher: "Les Solitaires intempestifs",
    pages: 48,
    isbn: "9782846810951",
    format: null,
    awards: [],
  }),
  livre({
    slug: "autoportrait-en-vert",
    title: "Autoportrait en vert",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "famille", "identite"],
    summary:
      "Dans le Sud-Ouest, la narratrice, qui ressemble beaucoup à l'autrice, guette la crue de la Garonne qui menace sa maison. Autour d'elle apparaissent des « femmes en vert » : une voisine, une amie, la nouvelle épouse de son père, sa propre mère. Elles sont à la fois familières et insaisissables, capables de changer d'aspect ou de disparaître. Ponctué de photographies, ce récit ne ressemble à aucun autre : un autoportrait indirect, à travers les femmes qui l'entourent et l'inquiètent.",
    whyRead: [
      "Un livre inclassable, entre récit, journal et rêve éveillé.",
      "Les femmes de l'entourage de l'autrice, vues comme des apparitions.",
      "Un texte court, accompagné de photographies.",
    ],
    year: 2005,
    publisher: "Folio",
    pages: 107,
    isbn: "9782070337545",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-souhait",
    title: "Le Souhait",
    contributors: [ndiaye],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["famille", "enfance", "identite"],
    summary:
      "Dans un pays où il neige toujours à Noël, un homme et une femme rêvent d'avoir un enfant, n'importe lequel, même un peu raté. Ils ont rempli de jouets une chambre qui reste désespérément vide. Une nuit de Noël, ils formulent encore leur souhait, et Camélia, une petite fille au visage noir, apparaît. Mais le bonheur d'être enfin trois ne va pas sans questions. Un petit roman tendre et étrange, illustré par Alice Charbin, pour les lecteurs de 6 à 8 ans.",
    whyRead: [
      "Un conte de Noël pas comme les autres, dès 6 ans.",
      "Une belle histoire sur l'adoption et le désir d'enfant.",
      "Une écriture simple qui ouvre sur de vraies questions.",
    ],
    year: 2005,
    publisher: "L'École des loisirs (Mouche)",
    pages: 55,
    isbn: "9782211079624",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "mon-coeur-a-l-etroit",
    title: "Mon cœur à l'étroit",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "identite", "famille"],
    summary:
      "Nadia et son mari Ange sont instituteurs à Bordeaux, appréciés, installés dans une vie tranquille. Du jour au lendemain, tout le monde semble les haïr : élèves, collègues, voisins, inconnus dans la rue. Personne ne leur dit pourquoi. Quand Ange est blessé, un voisin envahissant, Noget, s'installe chez eux pour les soigner. Nadia, qui ne comprend pas ce qu'on lui reproche, doit regarder en face ce qu'elle a fui de son passé.",
    whyRead: [
      "Un roman-cauchemar dans un Bordeaux poisseux et menaçant.",
      "Une héroïne qui refuse de voir ce qu'elle a renié.",
      "Un suspense psychologique qui ne lâche pas son lecteur.",
    ],
    year: 2007,
    publisher: "Folio",
    pages: 377,
    isbn: "9782070357451",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-grandes-personnes",
    title: "Les Grandes Personnes",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["famille", "ecole"],
    summary:
      "Éva et Rudi pleurent leur fille, disparue depuis des années, et attendent le retour de leur fils adoptif parti depuis longtemps. Leurs amis d'enfance, eux, ne parlent que de leur propre fils, l'instituteur du village, fierté de leurs vieux jours. Mais une femme vient troubler ces conversations paisibles : elle accuse le maître d'école d'avoir abusé de son enfant. Face au mur de solidarité des parents, elle s'obstine à se faire entendre. Une pièce dérangeante sur ce que les adultes refusent de voir.",
    whyRead: [
      "Une pièce courageuse sur le silence des familles.",
      "Une galerie de parents aveuglés par l'amour de leurs enfants.",
      "Créée en 2011 au Théâtre national de la Colline.",
    ],
    year: 2011,
    publisher: "Gallimard",
    pages: 88,
    isbn: "9782070131938",
    format: null,
    awards: [],
  }),
  livre({
    slug: "y-penser-sans-cesse",
    title: "Y penser sans cesse",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "histoire", "ville"],
    summary:
      "Dans les rues de Berlin, une femme marche avec son jeune fils, qui lui demande qui elle est. Sa voix lui répond, et avec elle surgissent des fantômes, des traces d'un passé douloureux que la ville porte encore. Marie NDiaye a écrit ce texte pour être lu à voix haute, en écho aux photographies de Denis Cointe qui l'accompagnent. Le livre propose aussi une traduction allemande, en regard du texte français.",
    whyRead: [
      "Berlin, ville où vit l'autrice, pour la première fois au cœur d'un de ses livres.",
      "Un texte bref, écrit pour la voix, entre poème et récit.",
      "Les photographies de Denis Cointe en contrepoint des mots.",
    ],
    year: 2011,
    publisher: "L'Arbre vengeur",
    pages: 112,
    isbn: "9782916141718",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ladivine",
    title: "Ladivine",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "identite", "femmes"],
    summary:
      "Clarisse Rivière, née Malinka, a construit sa vie sur un secret : sa mère, Ladivine Sylla, femme de ménage noire, qu'elle visite en cachette une fois par mois. Ni son mari Richard ni leur fille, prénommée Ladivine comme la grand-mère qu'elle ne connaît pas, n'en savent rien. Des années plus tard, la jeune Ladivine part en vacances à l'étranger avec son mari et leurs enfants, et d'étranges signes semblent la relier à cette lignée de femmes. Une saga familiale sur trois générations, la honte des origines et ce qu'on transmet sans le dire.",
    whyRead: [
      "Trois générations de femmes liées par un secret.",
      "Un grand roman sur la honte des origines et la transmission.",
      "Le réalisme le plus précis qui glisse vers le fantastique.",
    ],
    year: 2013,
    publisher: "Folio",
    pages: 454,
    isbn: "9782070459384",
    format: "poche",
    awards: [{ name: "Grand prix de l'héroïne Madame Figaro", year: 2013 }],
  }),
  livre({
    slug: "la-cheffe-roman-d-une-cuisiniere",
    title: "La Cheffe, roman d'une cuisinière",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["travail", "femmes", "famille"],
    summary:
      "Un ancien commis raconte la vie de celle qu'il a aimée en silence : la Cheffe, grande cuisinière dont le restaurant de Bordeaux a connu la gloire. Née dans une famille pauvre de la campagne du Sud-Ouest, elle entre très jeune au service d'un couple aisé et découvre la cuisine comme on découvre une vocation. Le narrateur reconstitue son parcours, son exigence, son rapport difficile avec sa fille, tout en avouant ce qu'il ne comprend pas d'elle. Le portrait d'une femme qui a tout donné à son art.",
    whyRead: [
      "Un beau portrait de femme, entièrement tournée vers son art.",
      "La cuisine racontée comme une ascèse et une passion.",
      "Un narrateur amoureux, dont on devine les failles.",
    ],
    year: 2016,
    publisher: "Folio",
    pages: 305,
    isbn: "9782072763632",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "trois-pieces",
    title: "Trois pièces",
    subtitle: "Délivrance, Berlin mon garçon, Honneur à notre élue",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["famille", "politique", "exil"],
    summary:
      "Ce volume réunit trois pièces. Dans Délivrance, un homme exilé écrit à sa femme pour qu'elle rende visite à ses vieux parents et lui donne des nouvelles de leur enfant. Dans Berlin mon garçon, Marina part à Berlin chercher son fils qui s'est éloigné d'elle et doit cohabiter avec un inconnu, Rüdiger. Dans Honneur à notre élue, les habitants d'une ville portuaire vénèrent une élue exemplaire dont ils ne savent presque rien, tandis qu'un opposant cherche des arguments pour la faire tomber.",
    whyRead: [
      "Trois facettes du théâtre de Marie NDiaye en un seul livre.",
      "Une fable politique sur l'idolâtrie des élus.",
      "Un exil, une mère à Berlin, une ville sous le charme : trois mondes.",
    ],
    year: 2019,
    publisher: "Gallimard",
    pages: 151,
    isbn: "9782072841897",
    format: null,
    awards: [],
  }),
  livre({
    slug: "un-pas-de-chat-sauvage",
    title: "Un pas de chat sauvage",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["histoire", "femmes", "identite"],
    summary:
      "Une universitaire parisienne veut écrire sur María Martínez, chanteuse cubaine surnommée la « Malibran noire », qui connut au XIXe siècle une brève gloire à Paris avant de disparaître. Au cours de ses recherches, elle rencontre une mystérieuse artiste noire qui se croit la réincarnation de la chanteuse. Entre les deux femmes naît un lien fait de fascination et de rejet. Ce court texte a été écrit pour l'exposition « Le Modèle noir » du musée d'Orsay, en 2019.",
    whyRead: [
      "La redécouverte d'une chanteuse oubliée, photographiée par Nadar.",
      "Une réflexion sur le regard porté sur les femmes noires.",
      "Un texte bref, écrit pour le musée d'Orsay.",
    ],
    year: 2019,
    publisher: "Flammarion / Musée d'Orsay",
    pages: 42,
    isbn: "9782081485129",
    format: null,
    awards: [],
  }),
  livre({
    slug: "royan-la-professeure-de-francais",
    title: "Royan. La professeure de français",
    contributors: [ndiaye],
    genre: "theatre",
    audience: "adulte",
    themes: ["ecole", "femmes"],
    summary:
      "À Royan, Gabrielle, professeure de français, monte l'escalier de son immeuble en sachant que des parents l'attendent devant sa porte. Ce sont ceux de Daniella, une de ses élèves, morte dans des circonstances dont on comprend peu à peu la gravité. Elle s'adresse à eux dans un long monologue, partagée entre les reproches, le sentiment d'une faute impardonnable et la certitude d'être innocente. Ce monologue sans concession explore la cruauté adolescente et la responsabilité des adultes.",
    whyRead: [
      "Un monologue saisissant, porté à la scène par Nicole Garcia.",
      "Une enseignante face à ce qu'elle n'a pas voulu voir.",
      "Un texte bref qui pose des questions qui dérangent.",
    ],
    year: 2020,
    publisher: "Gallimard",
    pages: 68,
    isbn: "9782072926952",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-vengeance-m-appartient",
    title: "La vengeance m'appartient",
    contributors: [ndiaye],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "exil"],
    summary:
      "Maître Susane, avocate à Bordeaux, reçoit la visite de Gilles Principaux, qui lui demande de défendre sa femme Marlyne, accusée d'avoir tué leurs trois enfants. Susane est troublée : elle croit avoir connu cet homme lorsqu'elle avait dix ans, chez ses parents, où sa propre mère faisait le ménage. Tout en préparant la défense de Marlyne, elle s'efforce de régulariser la situation de Sharon, sa femme de ménage mauricienne. Un roman trouble sur la mémoire, la culpabilité et les rapports de classe.",
    whyRead: [
      "Un roman judiciaire qui devient une enquête sur la mémoire.",
      "Une héroïne fragile et obstinée, que l'on suit pas à pas.",
      "Bordeaux et ses quartiers bourgeois, vus à travers des souvenirs incertains.",
    ],
    year: 2021,
    publisher: "Folio",
    pages: 263,
    isbn: "9782072977220",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-bon-denis",
    title: "Le Bon Denis",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "identite", "exil"],
    summary:
      "Peu après la naissance de Marie NDiaye, son père, venu du Sénégal, a quitté la France et sa famille. Autour de ce départ, l'autrice imagine quatre récits qui se répondent. Une femme interroge sa mère, dont la mémoire se défait, sur un certain « bon Denis » qui l'aurait aidée à l'époque. Ailleurs, on suit deux jeunes gens, elle née en Beauce, lui à Dakar, puis un homme africain qui se sent rejeté par la famille de sa femme, et enfin une jeune fille de dix-huit ans qui croise un père inconnu dans un grand hôtel américain.",
    whyRead: [
      "Le livre le plus personnel de Marie NDiaye, autour de son père.",
      "Quatre récits courts où l'imagination comble les silences.",
      "Un texte illustré, publié dans une collection mêlant images et mots.",
    ],
    year: 2025,
    publisher: "Mercure de France",
    pages: 126,
    isbn: "9782715266223",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "ma-cherie",
    title: "Ma chérie",
    contributors: [ndiaye],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "amour", "famille"],
    summary:
      "Un homme parle, sans s'arrêter. Sa femme l'a quitté après des décennies de vie commune qu'il croyait réussies, exemplaires même, et il réclame qu'on lui rende justice. Dans ce flot de colère et d'incompréhension, les rares mots de la femme qui s'est enfuie peinent à se faire entendre. Marie NDiaye fait entendre, en creux, tout ce que ce silence a porté pendant des années. Un texte bref et intense sur l'emprise conjugale et la liberté retrouvée.",
    whyRead: [
      "Un texte très court, d'une intensité rare.",
      "L'emprise dans le couple, racontée par la voix de celui qui l'exerce.",
      "Accompagné de photographies de Denis Cointe.",
    ],
    year: 2026,
    publisher: "L'Arbre vengeur",
    pages: 64,
    isbn: "9782379414480",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Cheikh Anta Diop
  livre({
    slug: "les-fondements-economiques-et-culturels-d-un-etat-federal-d-afrique-noire",
    title: "Les Fondements économiques et culturels d'un État fédéral d'Afrique noire",
    contributors: [diop],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "independances", "histoire"],
    summary:
      "Au moment où les pays africains accèdent à l'indépendance, Cheikh Anta Diop plaide pour un grand État fédéral réunissant l'Afrique noire. Il s'appuie sur l'unité culturelle du continent et propose de faire d'une langue africaine une langue de gouvernement et d'enseignement. Il passe en revue les ressources énergétiques et naturelles, des barrages à l'énergie solaire, sur lesquelles bâtir une industrie. Un programme politique ambitieux, qui reste une référence du panafricanisme.",
    whyRead: [
      "Le grand projet panafricain de Cheikh Anta Diop, en un livre court.",
      "Une réflexion toujours actuelle sur les langues et l'industrie africaines.",
      "Un texte écrit à l'heure des indépendances, pour penser l'avenir.",
    ],
    year: 1960,
    publisher: "Présence africaine",
    pages: 124,
    isbn: "9782708705357",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "anteriorite-des-civilisations-negres",
    title: "Antériorité des civilisations nègres",
    subtitle: "Mythe ou vérité historique ?",
    contributors: [diop],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "identite", "colonisation"],
    summary:
      "Treize ans après Nations nègres et culture, Cheikh Anta Diop reprend et approfondit sa thèse : l'Égypte ancienne fait partie de l'histoire de l'Afrique noire. Il réunit des arguments tirés de l'archéologie, de l'anthropologie, des langues et des témoignages des auteurs grecs anciens. Il discute pied à pied les positions des égyptologues de son temps, qu'il accuse d'avoir effacé l'Afrique de sa propre histoire. Traduit en anglais, ce livre a fait connaître ses idées dans le monde entier.",
    whyRead: [
      "L'exposé le plus complet de la thèse de Cheikh Anta Diop sur l'Égypte.",
      "Un livre qui a profondément marqué la pensée panafricaine.",
      "Un ouvrage illustré, riche en documents.",
    ],
    year: 1967,
    publisher: "Présence africaine",
    pages: null,
    isbn: "9782708705623",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "civilisation-ou-barbarie",
    title: "Civilisation ou barbarie",
    subtitle: "Anthropologie sans complaisance",
    contributors: [diop],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "identite", "spiritualite"],
    summary:
      "Dans ce dernier grand livre, Cheikh Anta Diop rassemble trente ans de recherches. Il défend l'origine africaine de l'humanité, revient sur la place de l'Égypte ancienne dans l'histoire du continent et retrace les apports de l'Afrique aux mathématiques, à la philosophie et aux sciences. Il critique la manière dont l'histoire a longtemps été écrite pour justifier la domination. Il appelle enfin les Africains à renouer avec leur passé pour bâtir leur avenir culturel.",
    whyRead: [
      "La somme de toute une vie de recherche, en un seul volume.",
      "Un livre de combat contre les préjugés sur l'histoire africaine.",
      "L'ouvrage de référence pour comprendre la pensée de Cheikh Anta Diop.",
    ],
    year: 1981,
    publisher: "Présence africaine",
    pages: 526,
    isbn: "9782708703940",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "alerte-sous-les-tropiques",
    title: "Alerte sous les tropiques",
    subtitle: "Articles 1946-1960. Culture et développement en Afrique noire",
    contributors: [diop],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "colonisation", "independances"],
    summary:
      "Ce recueil, paru après la mort de Cheikh Anta Diop, rassemble les articles qu'il a publiés de 1946 à 1960. On y suit le jeune étudiant de Paris, puis le militant, qui réfléchit à la culture africaine, aux langues nationales, à l'éducation et au développement. Il y dénonce la domination coloniale et réclame dès l'après-guerre l'indépendance des pays africains. Ces textes éclairent la naissance d'une pensée qui a nourri des générations.",
    whyRead: [
      "Les premiers combats de Cheikh Anta Diop, avant les indépendances.",
      "Des textes courts, pour entrer dans sa pensée pas à pas.",
      "Un témoignage sur les luttes des étudiants africains à Paris.",
    ],
    year: 1990,
    publisher: "Présence africaine",
    pages: 148,
    isbn: "9782708705487",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Amadou Hampâté Bâ
  livre({
    slug: "l-empire-peul-du-macina",
    title: "L'Empire peul du Macina",
    subtitle: "1818-1853",
    contributors: [ba, auteur("Jacques Daget", null)],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "spiritualite", "politique"],
    summary:
      "Au début du XIXe siècle, dans le delta intérieur du Niger, le marabout peul Sékou Amadou fonde un État musulman, la Dina, avec pour capitale Hamdallaye. Amadou Hampâté Bâ et Jacques Daget en retracent l'histoire, de sa fondation en 1818 à 1853. Ils s'appuient surtout sur les traditions orales recueillies auprès des descendants et des griots. Le livre décrit l'organisation de l'empire, son armée, sa justice et la vie de ses habitants.",
    whyRead: [
      "L'histoire d'un empire africain racontée à partir de la tradition orale.",
      "Un travail pionnier, salué dès sa parution par Théodore Monod.",
      "Pour comprendre l'histoire du Mali avant la colonisation.",
    ],
    year: 1955,
    publisher: "Nouvelles Éditions africaines",
    pages: 306,
    isbn: "9782723606264",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "vie-et-enseignement-de-tierno-bokar",
    title: "Vie et enseignement de Tierno Bokar",
    subtitle: "Le sage de Bandiagara",
    contributors: [ba],
    genre: "recit",
    audience: "adulte",
    themes: ["spiritualite", "histoire", "ecole"],
    summary:
      "Tierno Bokar, maître soufi de Bandiagara, au Mali, a été le guide spirituel d'Amadou Hampâté Bâ dans sa jeunesse. Celui-ci raconte sa vie, de sa naissance à la fin du XIXe siècle à ses dernières années, assombries par des querelles religieuses et la méfiance de l'administration coloniale. Il rapporte surtout son enseignement : la bonté, la tolérance envers les autres croyances, la recherche de Dieu dans la vie de tous les jours. Un portrait plein de ferveur et de reconnaissance.",
    whyRead: [
      "Le portrait d'un sage africain, apôtre de la tolérance.",
      "Un islam spirituel et ouvert, raconté par son disciple.",
      "Un livre de sagesse, disponible en poche.",
    ],
    year: 1980,
    publisher: "Points",
    pages: 254,
    isbn: "9782757841952",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "koumen",
    title: "Koumen",
    subtitle: "Texte initiatique des pasteurs peuls",
    contributors: [ba, auteur("Germaine Dieterlen", null)],
    genre: "recit",
    audience: "adulte",
    themes: ["contes", "spiritualite", "tradition"],
    summary:
      "Silé Sadio, jeune berger peul, est appelé à devenir le premier initié de son peuple. Guidé par Koumen, petit génie à barbe d'ancêtre, gardien des secrets du bétail, il traverse douze clairières où il doit comprendre des signes et des symboles. Chaque étape lui révèle une part du savoir des pasteurs : les couleurs des bêtes, les plantes, les règles de la vie en brousse. Amadou Hampâté Bâ et l'ethnologue Germaine Dieterlen ont recueilli et commenté ce texte transmis par un maître du Ferlo, au Sénégal.",
    whyRead: [
      "Un grand texte d'initiation de la tradition peule.",
      "Le savoir des bergers, transmis sous forme de voyage symbolique.",
      "Une collaboration rare entre un sage africain et une ethnologue.",
    ],
    year: 1961,
    publisher: "Mouton",
    pages: 95,
    isbn: null,
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "kaidara",
    title: "Kaïdara",
    subtitle: "Récit initiatique peul",
    contributors: [
      ba,
      auteur("Lilyan Kesteloot", null),
      { role: "traducteur", name: "Amadou Hampâté Bâ et Lilyan Kesteloot", authorSlug: null },
    ],
    genre: "poesie",
    audience: "adulte",
    themes: ["contes", "spiritualite", "tradition"],
    summary:
      "Trois compagnons, Hammadi, Hamtoudo et Dembourou, guidés par une voix mystérieuse, descendent au pays souterrain des génies nains. Ils y rencontrent Kaïdara, dieu de l'or et de la connaissance, et croisent en chemin une série de symboles étranges qu'il leur faut comprendre. Chacun réagit selon son caractère : l'un cherche la richesse, l'autre le pouvoir, le troisième le sens des choses. Ce grand poème initiatique de la tradition peule a été recueilli, traduit et enrichi par Amadou Hampâté Bâ.",
    whyRead: [
      "Un chef-d'œuvre de la tradition orale peule, lu comme une épopée.",
      "Une réflexion sur le savoir, le pouvoir et la richesse.",
      "Réédité en 2024 dans une édition illustrée par le peintre Omar Ba.",
    ],
    year: 1969,
    originalLanguage: "peul",
    publisher: "Diane de Selliers",
    pages: 281,
    isbn: "9782364371415",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "aspects-de-la-civilisation-africaine",
    title: "Aspects de la civilisation africaine",
    subtitle: "Personne, culture, religion",
    contributors: [ba],
    genre: "essai",
    audience: "adulte",
    themes: ["tradition", "spiritualite", "identite"],
    summary:
      "Dans ce petit livre, Amadou Hampâté Bâ expose ce qu'il a appris des traditions d'Afrique de l'Ouest. Il explique d'abord comment ces cultures conçoivent la personne humaine, faite de plusieurs dimensions, et la place qu'y tient la parole. Il présente ensuite la culture africaine comme une manière de vivre, avant d'aborder la religion, de l'animisme à l'islam. Partout, il plaide pour le respect des traditions et pour la tolérance entre les croyances.",
    whyRead: [
      "Une introduction claire à la pensée traditionnelle africaine.",
      "Un plaidoyer pour la tolérance religieuse, toujours actuel.",
      "Un livre court, pour découvrir Hampâté Bâ penseur.",
    ],
    year: 1972,
    publisher: "Présence africaine",
    pages: null,
    isbn: "9782708706019",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-eclat-de-la-grande-etoile",
    title: "L'Éclat de la grande étoile",
    subtitle: "Suivi du Bain rituel",
    contributors: [
      ba,
      { role: "traducteur", name: "Amadou Hampâté Bâ, Lilyan Kesteloot, Christiane Seydou et Alfâ Ibrâhîm Sow", authorSlug: null },
    ],
    genre: "poesie",
    audience: "adulte",
    themes: ["contes", "spiritualite", "politique"],
    summary:
      "Ce récit initiatique peul prolonge Kaïdara. Diom-Djéri, descendant de Hammadi, est roi par héritage, mais il doit encore apprendre à gouverner avec sagesse. Il est guidé par Bâgoumâwel, un maître initié qui lui enseigne, au fil d'une longue épreuve, ce que le pouvoir exige de patience et de connaissance de soi. Le volume, publié avec le texte peul et sa traduction, est suivi d'un second récit, Le Bain rituel.",
    whyRead: [
      "La suite de Kaïdara : une initiation au pouvoir.",
      "Une réflexion ancienne sur ce que doit être un bon roi.",
      "Le texte peul et sa traduction réunis.",
    ],
    year: 1974,
    originalLanguage: "peul",
    publisher: "Armand Colin",
    pages: 149,
    isbn: null,
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "jesus-vu-par-un-musulman",
    title: "Jésus vu par un musulman",
    contributors: [ba],
    genre: "essai",
    audience: "adulte",
    themes: ["spiritualite", "tradition"],
    summary:
      "Musulman fervent, disciple du sage Tierno Bokar, Amadou Hampâté Bâ présente la figure de Jésus telle qu'elle apparaît dans le Coran et dans la tradition mystique de l'islam. Il montre la place d'honneur que les musulmans accordent à Jésus et à sa mère Marie. Il y ajoute des réflexions sur le sens caché des nombres et des symboles. Ce petit livre est d'abord un geste de dialogue entre chrétiens et musulmans.",
    whyRead: [
      "Un texte de paix entre les religions, écrit par un sage.",
      "Pour découvrir comment l'islam voit Jésus.",
      "Un livre court, porté par la tolérance de Tierno Bokar.",
    ],
    year: 1976,
    publisher: "Stock",
    pages: 125,
    isbn: "9782234044036",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "petit-bodiel-et-autres-contes-de-la-savane",
    title: "Petit Bodiel et autres contes de la savane",
    contributors: [ba],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "humour", "tradition"],
    summary:
      "Petit Bodiel est un lièvre paresseux et gourmand qui rêve d'être reconnu comme fort et courageux, et même de régner sur la savane. Il demande à Dieu de l'aider, et reçoit la ruse dont il se sert pour tromper des animaux bien plus grands que lui. Mais Bodiel n'est jamais rassasié et finit par se croire capable de tout. Ce long conte peul ouvre un recueil d'histoires de la savane qui se moquent des travers humains : vanité, avidité, sottise.",
    whyRead: [
      "Le lièvre rusé de la savane, cousin africain de nos fables.",
      "Des contes drôles et pleins de sagesse, à lire en famille.",
      "Disponible en poche, idéal à partir de 10 ans.",
    ],
    year: 1994,
    publisher: "Pocket",
    pages: 217,
    isbn: "9782266157889",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "njeddo-dewal-mere-de-la-calamite",
    title: "Njeddo Dewal, mère de la calamité",
    subtitle: "Conte initiatique peul",
    contributors: [ba],
    genre: "contes",
    audience: "adulte",
    themes: ["contes", "spiritualite", "tradition"],
    summary:
      "Autrefois, les Peuls vivaient à Héli et Yoyo, un pays d'abondance. Parce qu'ils se sont mal conduits, Dieu leur envoie Njeddo Dewal, sorcière terrible, mère de toutes les calamités, dont les maléfices les dispersent. Contre elle se dresse un enfant aux dons extraordinaires, Bâgoumâwel, seul capable de lui tenir tête. Entre prodiges, épreuves et combats magiques, ce grand conte initiatique met en scène la lutte du bien et du mal.",
    whyRead: [
      "Un grand conte fantastique de la tradition peule.",
      "Un héros enfant face à une sorcière redoutable.",
      "Une aventure riche en prodiges, qui se lit comme une épopée.",
    ],
    year: 1985,
    publisher: "Nouvelles Éditions ivoiriennes",
    pages: 221,
    isbn: "9782723607322",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "oui-mon-commandant",
    title: "Oui mon commandant !",
    contributors: [ba],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "travail", "spiritualite"],
    summary:
      "Ce deuxième volume des mémoires d'Amadou Hampâté Bâ reprend là où s'arrêtait Amkoullel, l'enfant peul. Au début des années 1920, le jeune homme est nommé commis de l'administration coloniale en Haute-Volta, l'actuel Burkina Faso. Il raconte sa vie de fonctionnaire africain, les commandants, les interprètes, les tournées en brousse, mais aussi sa quête spirituelle auprès de Tierno Bokar. Un témoignage vivant et souvent drôle sur la colonisation vue de l'intérieur.",
    whyRead: [
      "La suite d'Amkoullel, l'enfant peul, aussi vivante que le premier tome.",
      "L'administration coloniale racontée par un de ses commis africains.",
      "Un conteur hors pair, plein d'humour et de sagesse.",
    ],
    year: 1994,
    publisher: "Actes Sud (Babel)",
    pages: 519,
    isbn: "9782742708635",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "sur-les-traces-d-amkoullel-l-enfant-peul",
    title: "Sur les traces d'Amkoullel, l'enfant peul",
    contributors: [ba, { role: "auteur", name: "Philippe Dupuich", authorSlug: null }],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "tradition", "histoire"],
    summary:
      "Ce beau livre part sur les pas d'Amadou Hampâté Bâ enfant, dans le Mali du début du XXe siècle. Le photographe Philippe Dupuich a parcouru les lieux où il a grandi, de Bandiagara aux bords du Niger, et en rapporte des images de paysages, de villages et de visages. Elles accompagnent des textes d'Amadou Hampâté Bâ, adages, fables et souvenirs, choisis par Bernard Magnier. Un voyage illustré pour mettre des images sur le récit d'enfance du grand conteur.",
    whyRead: [
      "Les lieux d'enfance du grand conteur, en photographies.",
      "Un beau livre pour prolonger la lecture des mémoires.",
      "Le Mali d'hier et d'aujourd'hui, réunis.",
    ],
    year: 1998,
    publisher: "Actes Sud",
    pages: 188,
    isbn: "9782742718795",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "il-n-y-a-pas-de-petite-querelle",
    title: "Il n'y a pas de petite querelle",
    subtitle: "Nouveaux contes de la savane",
    contributors: [ba],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "humour", "tradition"],
    summary:
      "Une querelle entre deux lézards peut-elle mettre tout un village à feu et à sang ? C'est ce que raconte le premier conte de ce recueil, qui donne son titre au livre. Suivent un roi qui veut faire tuer tous les vieillards, un marabout trop gourmand, une fille au masque de bois ou un berger bossu. Ces contes de la savane, choisis après la mort de l'auteur parmi ceux qu'il avait recueillis, épinglent avec humour les défauts des hommes et rappellent quelques vérités simples.",
    whyRead: [
      "Des contes courts, drôles et pleins de leçons de vie.",
      "Une porte d'entrée idéale dans la sagesse de la savane.",
      "Un poche à lire à voix haute, dès 10 ans.",
    ],
    year: 1999,
    publisher: "Pocket",
    pages: 160,
    isbn: "9782266230735",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Yambo Ouologuem
  livre({
    slug: "lettre-a-la-france-negre",
    title: "Lettre à la France nègre",
    contributors: [ouologuem],
    genre: "essai",
    audience: "adulte",
    themes: ["humour", "colonisation", "identite"],
    summary:
      "Un an après le prix Renaudot du Devoir de violence, Yambo Ouologuem publie ce pamphlet fait d'une série de lettres ouvertes. Il s'adresse tour à tour au président de la République, aux couples mixtes, aux racistes, aux bonnes âmes et à bien d'autres. Avec une ironie féroce, il démonte les préjugés sur les Noirs, mais aussi l'hypocrisie d'un certain antiracisme et la complaisance des élites africaines. Un livre provocateur, qui n'épargne personne.",
    whyRead: [
      "Un pamphlet drôle et cinglant contre tous les racismes.",
      "La plume insolente de l'auteur du Devoir de violence.",
      "Des lettres courtes, qui se lisent dans le désordre.",
    ],
    year: 1969,
    publisher: "Le Serpent à plumes",
    pages: 217,
    isbn: "9782842613952",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-mille-et-une-bibles-du-sexe",
    title: "Les Mille et Une Bibles du sexe",
    contributors: [ouologuem],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "humour"],
    summary:
      "Paru en 1969 sous le pseudonyme d'Utto Rodolph, ce roman érotique se présente comme un manuscrit confié à Yambo Ouologuem, qui se dit simple éditeur. Il réunit les confessions de nombreux couples, organisées en chapitres qui racontent chacun une expérience amoureuse hors du commun. Ouologuem s'y amuse avec les modèles du Décaméron et de Sade, en jouant avec les noms et les emprunts. Réédité sous son vrai nom en 2015, c'est l'une de ses œuvres les plus surprenantes.",
    whyRead: [
      "Le livre le plus inattendu de l'auteur du Devoir de violence.",
      "Un jeu littéraire sur l'érotisme, le pastiche et les masques.",
      "Réédité en 2015, avec une préface de Sami Tchak et Jean-Pierre Orban.",
    ],
    year: 1969,
    publisher: "Vents d'ailleurs",
    pages: 213,
    isbn: "9782364130630",
    format: "grand-format",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "quant-au-riche-avenir",
  "comedie-classique",
  "la-femme-changee-en-buche",
  "en-famille",
  "un-temps-de-saison",
  "la-sorciere",
  "la-naufragee",
  "hilda",
  "la-diablesse-et-son-enfant",
  "rosie-carpe",
  "papa-doit-manger",
  "les-paradis-de-prunelle",
  "tous-mes-amis",
  "les-serpents",
  "rien-d-humain",
  "autoportrait-en-vert",
  "le-souhait",
  "mon-coeur-a-l-etroit",
  "les-grandes-personnes",
  "y-penser-sans-cesse",
  "ladivine",
  "la-cheffe-roman-d-une-cuisiniere",
  "trois-pieces",
  "un-pas-de-chat-sauvage",
  "royan-la-professeure-de-francais",
  "la-vengeance-m-appartient",
  "le-bon-denis",
  "ma-cherie",
  "les-fondements-economiques-et-culturels-d-un-etat-federal-d-afrique-noire",
  "anteriorite-des-civilisations-negres",
  "civilisation-ou-barbarie",
  "alerte-sous-les-tropiques",
  "l-empire-peul-du-macina",
  "vie-et-enseignement-de-tierno-bokar",
  "koumen",
  "kaidara",
  "aspects-de-la-civilisation-africaine",
  "l-eclat-de-la-grande-etoile",
  "jesus-vu-par-un-musulman",
  "petit-bodiel-et-autres-contes-de-la-savane",
  "njeddo-dewal-mere-de-la-calamite",
  "oui-mon-commandant",
  "sur-les-traces-d-amkoullel-l-enfant-peul",
  "il-n-y-a-pas-de-petite-querelle",
  "lettre-a-la-france-negre",
  "les-mille-et-une-bibles-du-sexe",
];
