/**
 * Lot 01 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Les six premières fiches servent d'essai aux couvertures tirées de planches (2 et 4 illustrations par image).
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  livre({
    slug: "un-chant-ecarlate",
    title: "Un chant écarlate",
    contributors: [auteur("Mariama Bâ", "mariama-ba")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "famille", "tradition", "identite"],
    summary:
      "Mireille, fille d'un diplomate français, et Ousmane, brillant étudiant sénégalais issu d'un quartier populaire de Dakar, s'aiment contre l'avis de leurs familles. Elle quitte tout pour l'épouser et s'installer au Sénégal. Mais le couple doit vivre entre deux mondes : la mère d'Ousmane, les amis, les traditions et le regard des autres pèsent chaque jour un peu plus. Mariama Bâ interroge ce que l'amour peut contre les attentes d'une famille et d'une société.",
    whyRead: [
      "Le second et dernier roman de Mariama Bâ, publié après sa mort.",
      "Un couple mixte au cœur de Dakar, raconté sans fard.",
      "Une réflexion toujours actuelle sur l'amour face aux traditions.",
    ],
    year: 1981,
    publisher: "Le Serpent à plumes",
    pages: null,
    isbn: null,
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "xala",
    title: "Xala",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "tradition", "independances"],
    summary:
      "À Dakar, au lendemain des indépendances, El Hadji Abdou Kader Bèye est un homme d'affaires prospère, membre de la nouvelle élite du pays. Pour affirmer sa réussite, il épouse une troisième femme, bien plus jeune que lui. Mais le soir des noces, il est frappé du « xala », une impuissance qu'il croit due à un mauvais sort. Sa quête d'un remède devient une satire mordante de la bourgeoisie africaine qui a pris la place des colons.",
    whyRead: [
      "Une satire féroce et drôle des nouvelles élites africaines.",
      "Adapté au cinéma par Sembène lui-même en 1975.",
      "Un roman court, vif, qui se lit d'une traite.",
    ],
    year: 1973,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
    adaptations: [{ kind: "film", title: "Xala", year: 1975, by: "Ousmane Sembène" }],
  }),
  livre({
    slug: "le-docker-noir",
    title: "Le Docker noir",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "travail", "identite"],
    summary:
      "Diaw Falla, docker sénégalais sur le port de Marseille, consacre ses nuits à écrire un roman. Une romancière française s'approprie son manuscrit et le publie sous son nom, avec succès. Quand Diaw est jugé pour la mort de cette femme, le procès devient celui d'un travailleur noir face à la justice et à la presse. Ce premier roman, nourri de la vie de Sembène lui-même, dit la condition des ouvriers africains en France.",
    whyRead: [
      "Le premier roman de Sembène, inspiré de ses années de docker à Marseille.",
      "Un regard rare sur les travailleurs africains en France dans les années 1950.",
      "Une réflexion sur qui a le droit d'écrire et d'être lu.",
    ],
    year: 1956,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "o-pays-mon-beau-peuple",
    title: "Ô pays, mon beau peuple !",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "tradition", "amour", "famille"],
    summary:
      "Après la guerre, Oumar Faye revient dans son village de Casamance avec Isabelle, sa jeune épouse européenne. Il rêve de moderniser l'agriculture et de libérer les paysans de la mainmise des commerçants coloniaux. Mais il se heurte à la fois aux intérêts des Blancs installés et aux résistances de sa propre famille, qui accepte mal son mariage. Un roman sur l'espoir d'une Afrique qui veut décider de son avenir.",
    whyRead: [
      "Un portrait vivant de la Casamance à la fin de l'époque coloniale.",
      "Un héros qui veut changer les choses, entre deux mondes.",
      "Le deuxième roman de Sembène, déjà engagé et généreux.",
    ],
    year: 1957,
    publisher: "Pocket",
    pages: null,
    isbn: null,
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chants-d-ombre",
    title: "Chants d'ombre",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "exil", "enfance", "tradition"],
    summary:
      "Premier recueil de Senghor, Chants d'ombre rassemble des poèmes écrits pendant ses années d'études et d'enseignement en France. Le poète, loin du Sénégal, se souvient du royaume d'enfance de Joal, des nuits sereres, des voix des griots et des femmes de son village. On y trouve notamment le célèbre poème « Femme noire ». C'est l'acte de naissance poétique de la négritude chez Senghor.",
    whyRead: [
      "Le premier recueil de Senghor, avec le poème « Femme noire ».",
      "La nostalgie de l'enfance sénégalaise, vue depuis l'exil.",
      "Une porte d'entrée idéale dans la poésie de la négritude.",
    ],
    year: 1945,
    publisher: "Seuil",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "terre-ceinte",
    title: "Terre ceinte",
    contributors: [auteur("Mohamed Mbougar Sarr", "mohamed-mbougar-sarr")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "guerre", "spiritualite", "famille"],
    summary:
      "Kalep, petite ville du Sahel, vit sous le joug d'un groupe djihadiste qui impose sa loi par la terreur. Un jeune couple y est exécuté pour s'être aimé. Dans l'ombre, un petit groupe d'habitants décide de résister en diffusant un journal clandestin, tandis que les mères des victimes s'écrivent des lettres. Le premier roman de Mohamed Mbougar Sarr montre comment des gens ordinaires tiennent face à l'oppression.",
    whyRead: [
      "Le premier roman du futur prix Goncourt 2021.",
      "Un récit fort sur la résistance face au fanatisme.",
      "Prix Ahmadou-Kourouma et Grand prix du roman métis 2015.",
    ],
    year: 2014,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [
      { name: "Prix Ahmadou-Kourouma", year: 2015 },
      { name: "Grand prix du roman métis", year: 2015 },
    ],
  }),
  // ------------------------------------------------------------------ Cheikh Hamidou Kane
  livre({
    slug: "les-gardiens-du-temple",
    title: "Les Gardiens du temple",
    contributors: [auteur("Cheikh Hamidou Kane", "cheikh-hamidou-kane")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "tradition", "independances", "identite"],
    summary:
      "Quelques années après l'indépendance, un jeune pays d'Afrique de l'Ouest traverse une grave crise politique. Salif Bâ, fils du chef des Diallobé, formé à l'école occidentale, cherche comment servir son peuple sans renier ce qu'il est. Autour de lui, Daba Mbaye et Farba Mâri, le chroniqueur de la mémoire des Diallobé, cherchent eux aussi ce que la tradition peut encore apporter au pays. Trente-quatre ans après « L'Aventure ambiguë », Cheikh Hamidou Kane reprend le fil de son premier livre pour imaginer une Afrique réconciliée avec elle-même.",
    whyRead: [
      "La suite attendue de « L'Aventure ambiguë », trente-quatre ans plus tard.",
      "Un roman inspiré des crises politiques du Sénégal après l'indépendance.",
      "Une réflexion apaisée sur la tradition et la modernité.",
    ],
    year: 1995,
    publisher: "Stock",
    pages: 337,
    isbn: "9782234045637",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Ousmane Sembène
  livre({
    slug: "voltaique",
    title: "Voltaïque",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["femmes", "colonisation", "exil", "tradition"],
    summary:
      "Ce recueil réunit des nouvelles, des contes et de courts récits écrits par Sembène au début des années 1960. On y croise des femmes qui tiennent tête aux hommes et aux coutumes, des villageois, des travailleurs, des exilés. La plus connue, « La Noire de… », suit Diouana, une jeune Dakaroise emmenée sur la Côte d'Azur par ses employeurs français, qui découvre qu'on ne voit en elle qu'une domestique. Des textes courts et directs, qui disent le racisme colonial et la place faite aux femmes.",
    whyRead: [
      "Contient « La Noire de… », que Sembène a porté à l'écran en 1966.",
      "Des récits courts, parfaits pour découvrir l'auteur.",
      "Des héroïnes fortes, en Afrique comme en France.",
    ],
    year: 1962,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: "poche",
    awards: [],
    adaptations: [{ kind: "film", title: "La Noire de…", year: 1966, by: "Ousmane Sembène" }],
  }),
  livre({
    slug: "l-harmattan",
    title: "L'Harmattan",
    subtitle: "Référendum",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["independances", "politique", "colonisation", "travail"],
    summary:
      "En 1958, la France demande à ses colonies d'Afrique de voter au référendum sur la Communauté : dire oui, c'est rester liés à la métropole, dire non, c'est choisir l'indépendance tout de suite. Dans une capitale d'Afrique de l'Ouest, des militants, des ouvriers, des enseignants et des femmes font campagne pour le non, face aux partisans du oui et à l'administration coloniale. Sembène suit une foule de personnages dans ces semaines où tout semble possible. Un grand roman collectif sur un moment décisif de l'histoire africaine.",
    whyRead: [
      "Le référendum de 1958 raconté de l'intérieur, comme une fresque.",
      "Une galerie de militants, d'ouvriers et de femmes engagées.",
      "Pour comprendre comment l'Afrique francophone a choisi son destin.",
    ],
    year: 1964,
    publisher: "Présence africaine",
    pages: 311,
    isbn: "9782708703797",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "vehi-ciosane-suivi-du-mandat",
    title: "Véhi-Ciosane ou Blanche-Genèse, suivi du Mandat",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["famille", "tradition", "humour", "ville"],
    summary:
      "Deux longues nouvelles, deux tons très différents. Dans « Véhi-Ciosane », un village de la région des Niayes découvre qu'une jeune fille est enceinte, et le scandale qui éclate met à nu l'autorité d'un chef et le silence d'une communauté. Dans « Le Mandat », Ibrahima Dieng, chômeur de Dakar, reçoit un mandat envoyé de Paris par son neveu ; mais pour toucher cet argent, il lui faut des papiers qu'il n'a pas, et tout le quartier veut déjà sa part. Sembène y passe de la tragédie à la comédie sociale avec la même lucidité.",
    whyRead: [
      "« Le Mandat », satire drôle et cruelle de la bureaucratie, est un classique.",
      "Adapté par Sembène au cinéma : « Niaye » (1964) et « Mandabi » (1968).",
      "Deux récits courts qui montrent toute la palette de l'auteur.",
    ],
    year: 1966,
    publisher: "Présence africaine",
    pages: 190,
    isbn: "9782708701700",
    format: "poche",
    awards: [],
    adaptations: [
      { kind: "film", title: "Niaye", year: 1964, by: "Ousmane Sembène" },
      { kind: "film", title: "Mandabi", year: 1968, by: "Ousmane Sembène" },
    ],
  }),
  livre({
    slug: "le-dernier-de-l-empire",
    title: "Le Dernier de l'Empire",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "humour"],
    summary:
      "Un matin, Léon Mignane, le vieux président qui dirige le pays depuis l'indépendance, a disparu. Personne ne sait s'il a fui, s'il a été enlevé ou s'il prépare un coup. Au gouvernement, les ministres se déchirent pour la succession, tandis que le vieux ministre de la Justice voit s'effondrer l'édifice qu'il a servi toute sa vie. Dans ce gros roman politique, Sembène dresse un portrait sans complaisance du pouvoir sénégalais des années 1970 et de ses arrangements avec l'ancienne puissance coloniale.",
    whyRead: [
      "Un roman politique à suspense, au cœur d'un palais présidentiel.",
      "Un président de fiction qui rappelle beaucoup Senghor.",
      "La critique du pouvoir postcolonial par un écrivain sans concession.",
    ],
    year: 1981,
    publisher: "L'Harmattan",
    pages: null,
    isbn: "9782858021697",
    format: null,
    awards: [],
  }),
  livre({
    slug: "niiwam-suivi-de-taaw",
    title: "Niiwam, suivi de Taaw",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["ville", "famille", "travail"],
    summary:
      "Deux nouvelles sur la pauvreté dans le Dakar des années 1980. Dans « Niiwam », un père pauvre doit traverser la capitale en autobus avec le corps de son fils, enveloppé dans un linge, pour lui trouver une tombe, sans que personne autour de lui ne devine ce qu'il porte. Dans « Taaw », un jeune homme sans travail se heurte à l'autorité d'un père qui règne durement sur sa famille. Sembène y montre une ville qui grandit trop vite et laisse les plus pauvres sur le bord du chemin.",
    whyRead: [
      "Un trajet en bus à travers Dakar, d'une tension extraordinaire.",
      "Deux portraits forts de la pauvreté urbaine.",
      "« Niiwam » a été adapté au cinéma par Clarence Delgado.",
    ],
    year: 1987,
    publisher: "Présence africaine",
    pages: 189,
    isbn: "9782708704862",
    format: "poche",
    awards: [],
    adaptations: [{ kind: "film", title: "Niiwam", year: 1991, by: "Clarence Delgado" }],
  }),
  livre({
    slug: "guelwaar",
    title: "Guelwaar",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "politique", "humour", "tradition"],
    summary:
      "Pierre Henri Thioune, surnommé Guelwaar, « le noble », était un notable catholique au franc-parler redouté, qui dénonçait volontiers l'aide alimentaire venue de l'étranger. À sa mort, sa famille se prépare aux funérailles, mais le corps a disparu de la morgue. On découvre bientôt qu'il a été enterré par erreur dans un cimetière musulman. Entre catholiques et musulmans du village, l'affaire tourne à la querelle, et Sembène en tire une fable pleine d'humour sur la dignité et la tolérance.",
    whyRead: [
      "Un point de départ cocasse pour une fable sérieuse sur la tolérance.",
      "Le roman que Sembène a tiré de son propre film de 1992.",
      "Un appel vibrant à la dignité de l'Afrique.",
    ],
    year: 1996,
    publisher: "Présence africaine",
    pages: 169,
    isbn: "9782708706057",
    format: null,
    awards: [],
    adaptations: [{ kind: "film", title: "Guelwaar", year: 1992, by: "Ousmane Sembène" }],
  }),

  // ------------------------------------------------------------------ Léopold Sédar Senghor
  livre({
    slug: "hosties-noires",
    title: "Hosties noires",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["guerre", "colonisation", "identite"],
    summary:
      "Le deuxième recueil de Senghor est né de la Seconde Guerre mondiale. Mobilisé, fait prisonnier, le poète a passé de longs mois dans des camps allemands réservés aux soldats coloniaux, et plusieurs poèmes ont été écrits là. Il y rend hommage aux tirailleurs sénégalais, « hosties noires » sacrifiées pour la France, et dit sa colère face à l'ingratitude de la métropole, jusqu'au massacre de Thiaroye. Le recueil se termine pourtant sur une prière de paix et de pardon.",
    whyRead: [
      "Le grand livre de poésie sur les tirailleurs sénégalais.",
      "Des poèmes écrits en partie dans un camp de prisonniers.",
      "Repris dans « Œuvre poétique », en poche.",
    ],
    year: 1948,
    publisher: "Seuil",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "anthologie-de-la-nouvelle-poesie-negre-et-malgache",
    title: "Anthologie de la nouvelle poésie nègre et malgache de langue française",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "colonisation", "esclavage"],
    summary:
      "En 1948, pour le centenaire de l'abolition de l'esclavage, Senghor réunit les poètes noirs et malgaches qui écrivent en français : Aimé Césaire, Léon-Gontran Damas, Birago Diop, Jacques Rabemananjara, Jean-Joseph Rabearivelo et bien d'autres. Chaque poète est présenté par une courte notice. Le livre s'ouvre sur « Orphée noir », la longue préface de Jean-Paul Sartre, qui fit connaître la négritude au grand public. C'est l'acte fondateur d'une poésie qui affirme sa voix face à l'Europe.",
    whyRead: [
      "Le livre qui a fait connaître la négritude, avec la préface de Sartre.",
      "Césaire, Damas, Birago Diop, Rabemananjara… réunis en un seul volume.",
      "Une porte d'entrée idéale dans la poésie francophone d'Afrique et des Antilles.",
    ],
    year: 1948,
    publisher: "PUF",
    pages: null,
    isbn: "9782130653059",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chants-pour-naett",
    title: "Chants pour Naëtt",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["amour", "identite"],
    summary:
      "Ce petit recueil réunit des poèmes d'amour écrits par Senghor pour sa première épouse. Le poète y célèbre la femme aimée à travers les paysages, les nuits et les chants de son pays natal. La femme et l'Afrique s'y confondent souvent, dans une langue musicale qui se veut accompagnée d'instruments. Plus tard, Senghor reprendra ces poèmes, retravaillés, sous le titre « Chants pour Signare » dans le recueil « Nocturnes ».",
    whyRead: [
      "Le Senghor poète de l'amour, dans un recueil intime.",
      "Une rareté : l'édition originale de poèmes retravaillés ensuite.",
      "Des poèmes courts, à lire à voix haute.",
    ],
    year: 1949,
    publisher: "Seghers",
    pages: 49,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-belle-histoire-de-leuk-le-lievre",
    title: "La Belle Histoire de Leuk-le-Lièvre",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor"), { role: "auteur", name: "Abdoulaye Sadji", authorSlug: null }],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "enfance", "ecole"],
    summary:
      "Leuk, le petit lièvre de la savane, n'est ni grand ni fort, mais il est malin. De conte en conte, il apprend à connaître la brousse et ses habitants, déjoue les ruses de Bouki l'hyène et se mesure aux plus grands animaux de la brousse. Écrit par Senghor et Abdoulaye Sadji à partir des contes traditionnels du Sénégal, ce livre de lecture a appris à lire à des générations d'écoliers africains. Ses courts chapitres, illustrés, se lisent toujours avec plaisir, à l'école comme en famille.",
    whyRead: [
      "Le livre de lecture qui a bercé des générations d'écoliers africains.",
      "Des contes courts et drôles, avec un héros attachant.",
      "Une belle façon de transmettre les contes du Sénégal aux enfants.",
    ],
    year: 1953,
    publisher: "EDICEF",
    pages: 191,
    isbn: "9782841298327",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "nocturnes",
    title: "Nocturnes",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["amour", "identite", "tradition"],
    summary:
      "Paru l'année qui suit l'indépendance, « Nocturnes » rassemble des poèmes d'amour et de méditation. On y trouve les « Chants pour Signare », version retravaillée des poèmes écrits pour Naëtt, puis une suite d'élégies où le poète s'interroge, la nuit, sur sa vie, sur le pouvoir et sur sa vocation. La femme aimée, le pays sérère et la nuit africaine y dialoguent avec la solitude de l'homme d'État. Un recueil plus intime et plus grave que les précédents.",
    whyRead: [
      "Les « Chants pour Signare », parmi les plus beaux poèmes d'amour de Senghor.",
      "Le poète devenu président médite sur sa vie, la nuit.",
      "Repris dans « Œuvre poétique », en poche.",
    ],
    year: 1961,
    publisher: "Seuil",
    pages: 94,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "nation-et-voie-africaine-du-socialisme",
    title: "Nation et voie africaine du socialisme",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "independances", "identite"],
    summary:
      "Au moment des indépendances, Senghor expose dans ce court livre les idées qui doivent guider le nouvel État. Il y explique ce qu'est pour lui une nation, construite par une volonté commune au-delà des appartenances ethniques. Il y défend surtout un socialisme africain, qui emprunte au marxisme une méthode d'analyse mais s'appuie sur les valeurs communautaires et spirituelles de l'Afrique. Un texte clé pour comprendre la politique du premier président du Sénégal.",
    whyRead: [
      "La doctrine politique de Senghor au moment de l'indépendance.",
      "Pour comprendre ce que fut le « socialisme africain ».",
      "Un texte court, plus accessible que les gros volumes de « Liberté ».",
    ],
    year: 1961,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "liberte-1-negritude-et-humanisme",
    title: "Liberté 1",
    subtitle: "Négritude et humanisme",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "colonisation", "tradition"],
    summary:
      "Premier volume d'une série de cinq, ce gros livre rassemble des articles, des conférences et des discours écrits par Senghor depuis la fin des années 1930 jusqu'au début des années 1960. On y suit la naissance et l'approfondissement de l'idée de négritude : la valeur des civilisations africaines, leur art, leur rapport au rythme et à l'image. Senghor y dialogue avec les penseurs européens et défend un humanisme ouvert, où chaque culture apporte sa part. C'est la base de toute sa pensée.",
    whyRead: [
      "La négritude expliquée par l'un de ses fondateurs.",
      "Vingt-cinq ans de réflexion sur les cultures africaines.",
      "Le point de départ de la série « Liberté ».",
    ],
    year: 1964,
    publisher: "Seuil",
    pages: 438,
    isbn: "9782020022422",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-fondements-de-l-africanite",
    title: "Les Fondements de l'africanité ou Négritude et arabité",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "histoire", "spiritualite"],
    summary:
      "En février 1967, Senghor prononce à l'université du Caire une conférence sur ce qui unit les peuples d'Afrique. Il y soutient que l'Afrique noire et l'Afrique arabo-berbère ne s'opposent pas : leurs histoires, leurs échanges et leurs cultures se sont nourris les uns les autres depuis des siècles. Négritude et arabité sont, pour lui, les deux faces d'une même africanité. Ce texte court, publié la même année, éclaire son idée d'une Afrique unie au-delà du Sahara.",
    whyRead: [
      "Une conférence historique, prononcée au Caire en 1967.",
      "Senghor pense l'unité de l'Afrique, au nord comme au sud du Sahara.",
      "Un texte bref pour aborder sa pensée.",
    ],
    year: 1967,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "liberte-2-nation-et-voie-africaine-du-socialisme",
    title: "Liberté 2",
    subtitle: "Nation et voie africaine du socialisme",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "independances", "travail"],
    summary:
      "Le deuxième volume de « Liberté » réunit les discours et les textes politiques de Senghor des années de la décolonisation et des débuts de l'indépendance. Il y est question de la construction de la nation sénégalaise, du rêve fédéral africain, de l'organisation du parti et du socialisme africain qu'il veut mettre en œuvre. On y voit le poète devenu homme d'État chercher une voie entre le capitalisme et le communisme. Un document précieux sur les premières années du Sénégal indépendant.",
    whyRead: [
      "La pensée politique de Senghor au temps de l'indépendance.",
      "Un témoignage de première main sur la naissance du Sénégal moderne.",
      "Pour qui s'intéresse à l'histoire politique de l'Afrique.",
    ],
    year: 1971,
    publisher: "Seuil",
    pages: 314,
    isbn: "9782020023047",
    format: null,
    awards: [],
  }),
  livre({
    slug: "lettres-d-hivernage",
    title: "Lettres d'hivernage",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["amour", "exil"],
    summary:
      "Pendant l'hivernage, la saison des pluies au Sénégal, le poète est séparé de sa femme, Colette, restée loin de lui. Il lui écrit des poèmes comme on écrit des lettres : il y décrit la pluie, la chaleur, la lumière du pays, et lui dit son manque et son désir. Ces poèmes d'amour, simples et sensuels, montrent un Senghor intime, loin des discours. L'édition originale était illustrée de lithographies de Marc Chagall.",
    whyRead: [
      "Des poèmes d'amour écrits comme des lettres à l'absente.",
      "La saison des pluies au Sénégal, vue par un poète.",
      "Repris dans « Œuvre poétique », en poche.",
    ],
    year: 1973,
    publisher: "Seuil",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "liberte-3-negritude-et-civilisation-de-l-universel",
    title: "Liberté 3",
    subtitle: "Négritude et civilisation de l'universel",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "tradition"],
    summary:
      "Ce troisième volume rassemble les discours et conférences de Senghor des années 1960 et 1970. Il y développe son idée d'une « civilisation de l'universel », à laquelle chaque peuple doit apporter ce qu'il a de meilleur, plutôt que de se fondre dans un modèle unique. La négritude n'y est plus une révolte mais une contribution. On y trouve aussi ses réflexions sur la francophonie, la langue française et le métissage des cultures.",
    whyRead: [
      "La grande idée de Senghor : une civilisation où chaque culture compte.",
      "Ses réflexions sur la francophonie et le métissage.",
      "Une pensée qui garde toute son actualité.",
    ],
    year: 1977,
    publisher: "Seuil",
    pages: 573,
    isbn: "9782020046602",
    format: null,
    awards: [],
  }),
  livre({
    slug: "elegies-majeures",
    title: "Élégies majeures",
    subtitle: "Suivi de Dialogue sur la poésie francophone",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "identite", "histoire"],
    summary:
      "Dans ces longs poèmes graves et amples, Senghor célèbre les êtres et les forces qui ont compté pour lui. Parmi ces élégies figurent un hommage à Martin Luther King et un autre à Georges Pompidou, son ami de jeunesse. Le poète y médite sur la mort, l'amitié, l'histoire et l'espérance, sur un ton proche du chant. Le volume se termine par un dialogue sur la poésie francophone avec les poètes Alain Bosquet, Jean-Claude Renard et Pierre Emmanuel.",
    whyRead: [
      "Le dernier grand recueil de Senghor, au sommet de son art.",
      "Des hommages à Martin Luther King et à Georges Pompidou.",
      "Repris dans « Œuvre poétique », en poche.",
    ],
    year: 1979,
    publisher: "Seuil",
    pages: 123,
    isbn: "9782020052313",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-poesie-de-l-action",
    title: "La Poésie de l'action",
    subtitle: "Conversations avec Mohamed Aziza",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite", "enfance"],
    summary:
      "En 1980, l'année où il quitte le pouvoir, Senghor répond longuement aux questions de l'écrivain tunisien Mohamed Aziza. Il revient sur son enfance à Joal, ses études à Paris, la guerre, la négritude, puis ses vingt années à la tête du Sénégal. Il explique comment il a voulu concilier la poésie et l'action politique. Ces entretiens forment une sorte d'autobiographie parlée, vivante et accessible.",
    whyRead: [
      "Senghor raconte sa vie, de Joal à la présidence.",
      "Des entretiens vivants, plus faciles d'accès que ses essais.",
      "Comment un poète a gouverné un pays pendant vingt ans.",
    ],
    year: 1980,
    publisher: "Stock",
    pages: 359,
    isbn: "9782234006201",
    format: null,
    awards: [],
  }),
  livre({
    slug: "liberte-4-socialisme-et-planification",
    title: "Liberté 4",
    subtitle: "Socialisme et planification",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "travail", "independances"],
    summary:
      "Le quatrième volume de « Liberté » est consacré à l'action économique de Senghor à la tête du Sénégal. Il réunit des discours et des textes sur les plans de développement du pays et sur la façon d'organiser son économie. Le président y explique comment il a voulu planifier le développement sans renoncer à la démocratie. Un livre exigeant, surtout utile à ceux qui s'intéressent à l'histoire du Sénégal.",
    whyRead: [
      "Le bilan économique de vingt ans de présidence, par Senghor lui-même.",
      "Une source pour l'histoire du Sénégal indépendant.",
      "Pour voir le poète aux prises avec les chiffres et les plans.",
    ],
    year: 1983,
    publisher: "Seuil",
    pages: 668,
    isbn: "9782020065542",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ce-que-je-crois",
    title: "Ce que je crois",
    subtitle: "Négritude, francité et civilisation de l'universel",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "spiritualite", "enfance"],
    summary:
      "À plus de quatre-vingts ans, Senghor fait le point sur ce qui a guidé sa vie et sa pensée. Il revient sur son enfance sérère, sur la découverte des civilisations du monde et sur la négritude, qu'il relie à la francité, son amour de la langue française. Il y explique sa foi en un métissage des cultures et en une civilisation de l'universel. Un livre bref, sorte de testament intellectuel, réédité en 2024.",
    whyRead: [
      "Le testament intellectuel de Senghor, en un livre court.",
      "La négritude et la francophonie expliquées simplement.",
      "Réédité récemment, facile à trouver.",
    ],
    year: 1988,
    publisher: "Grasset",
    pages: 180,
    isbn: "9782246840299",
    format: null,
    awards: [],
  }),
  livre({
    slug: "oeuvre-poetique",
    title: "Œuvre poétique",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "amour", "colonisation", "tradition"],
    summary:
      "Ce volume rassemble toute la poésie publiée par Senghor, de « Chants d'ombre » en 1945 aux « Élégies majeures », avec des poèmes divers et des textes sur son art. On y suit un parcours de près d'un demi-siècle : la nostalgie du royaume d'enfance, l'hommage aux tirailleurs, l'amour, les élégies de la maturité. Les recueils devenus introuvables séparément sont tous réunis ici. C'est l'édition de référence pour lire le poète.",
    whyRead: [
      "Toute la poésie de Senghor en un seul volume de poche.",
      "Le meilleur moyen de lire les recueils devenus introuvables.",
      "Un demi-siècle de poésie, de « Femme noire » aux « Élégies ».",
    ],
    year: 1990,
    publisher: "Points",
    pages: 437,
    isbn: "9782757884072",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "liberte-5-le-dialogue-des-cultures",
    title: "Liberté 5",
    subtitle: "Le Dialogue des cultures",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "tradition", "politique"],
    summary:
      "Dernier volume de la série « Liberté », ce livre réunit des discours et des conférences de Senghor consacrés au dialogue des cultures. Il y reprend les thèmes de toute une vie : la rencontre entre les civilisations, le métissage, la francophonie, l'apport de l'Afrique à la civilisation de l'universel. Paru alors qu'il approche de ses quatre-vingt-dix ans, il clôt une entreprise commencée trente ans plus tôt. Une conclusion apaisée à l'œuvre d'essayiste de Senghor.",
    whyRead: [
      "Les derniers textes de Senghor sur le dialogue des cultures.",
      "Une pensée de l'ouverture, plus actuelle que jamais.",
      "La conclusion de la grande série « Liberté ».",
    ],
    year: 1993,
    publisher: "Seuil",
    pages: 295,
    isbn: "9782020191005",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Mohamed Mbougar Sarr
  livre({
    slug: "silence-du-choeur",
    title: "Silence du chœur",
    contributors: [auteur("Mohamed Mbougar Sarr", "mohamed-mbougar-sarr")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "politique"],
    summary:
      "Soixante-douze jeunes migrants africains arrivent à Altino, un village de Sicile, où ils attendent qu'on statue sur leur demande d'asile. Les habitants se divisent : certains les aident, d'autres les rejettent, et la tension monte au fil des mois. Le roman donne la parole à une foule de voix, Italiens et Africains, bénévoles, poètes, prêtres et militants. Mohamed Mbougar Sarr fait de ce petit village le miroir de toute l'Europe face aux migrations.",
    whyRead: [
      "Un grand roman choral sur l'accueil des migrants en Europe.",
      "Prix Littérature-Monde et prix de la Porte Dorée 2018.",
      "Le deuxième roman du futur prix Goncourt 2021.",
    ],
    year: 2017,
    publisher: "Présence africaine",
    pages: 569,
    isbn: "9782708709829",
    format: "poche",
    awards: [
      { name: "Prix Littérature-Monde", year: 2018 },
      { name: "Prix de la Porte Dorée", year: 2018 },
      { name: "Prix du roman métis des lecteurs", year: 2018 },
    ],
  }),
  livre({
    slug: "de-purs-hommes",
    title: "De purs hommes",
    contributors: [auteur("Mohamed Mbougar Sarr", "mohamed-mbougar-sarr")],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "spiritualite", "politique"],
    summary:
      "À Dakar, Ndéné Gueye, jeune professeur de lettres désabusé, découvre une vidéo qui circule sur les téléphones : la dépouille d'un homme est déterrée d'un cimetière par une foule, parce qu'on le disait homosexuel. Cette image l'obsède. Il cherche à savoir qui était cet homme, au risque d'être lui-même soupçonné par ses collègues, sa famille et son quartier. Un roman court et courageux sur l'homophobie au Sénégal et sur la peur du regard des autres.",
    whyRead: [
      "Un roman court et fort sur un sujet tabou.",
      "Une enquête intime qui oblige chacun à se regarder.",
      "La voix de Mbougar Sarr, trois ans avant le Goncourt.",
    ],
    year: 2018,
    publisher: "Le Livre de Poche",
    pages: 188,
    isbn: "9782253240914",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Fatou Diome
  livre({
    slug: "la-preference-nationale",
    title: "La Préférence nationale",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["exil", "femmes", "travail", "identite"],
    summary:
      "Le premier livre de Fatou Diome réunit des nouvelles qui suivent une jeune Sénégalaise, du Sénégal à Strasbourg. Arrivée en France, elle enchaîne les petits boulots, garde des enfants, fait des ménages, tout en poursuivant ses études. Elle se heurte aux préjugés de ses employeurs et aux portes qui se ferment. Avec beaucoup d'ironie, l'autrice met le doigt sur le racisme ordinaire et sur la dignité de ceux qui le subissent.",
    whyRead: [
      "Le premier livre de Fatou Diome, déjà mordant.",
      "Des nouvelles courtes, drôles et révoltées.",
      "Le racisme ordinaire vu par une étudiante immigrée.",
    ],
    year: 2001,
    publisher: "Présence africaine",
    pages: null,
    isbn: "9782708707221",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ketala",
    title: "Kétala",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "famille", "tradition", "femmes"],
    summary:
      "Mémoria vient de mourir. Selon la coutume, sa famille va bientôt se partager ses biens lors du kétala. Pendant les jours qui précèdent la cérémonie, ses meubles et ses objets familiers décident de lui rendre hommage en racontant sa vie. On découvre peu à peu l'histoire de cette jeune femme partie en Europe avec un mari qui lui cachait un secret. Un roman original, tendre et douloureux, sur l'exil et la solitude.",
    whyRead: [
      "Une idée géniale : ce sont les objets qui racontent.",
      "Une héroïne inoubliable, entre Dakar et Strasbourg.",
      "Un roman qui aborde l'exil, le mariage et les secrets de famille.",
    ],
    year: 2006,
    publisher: "J'ai lu",
    pages: 286,
    isbn: "9782290001547",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "inassouvies-nos-vies",
    title: "Inassouvies, nos vies",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "famille", "femmes"],
    summary:
      "Dans une grande ville d'Europe, Betty, une trentenaire solitaire, observe chaque soir les fenêtres de l'immeuble d'en face et imagine la vie de ses voisins. Elle s'attache à une vieille dame souriante, qu'elle surnomme Félicité. Quand celle-ci est placée en maison de retraite, Betty part à sa recherche et une amitié naît entre elles. Fatou Diome y parle de solitude, de vieillesse et de ce qui nous relie aux autres.",
    whyRead: [
      "Une amitié touchante entre une jeune femme et une vieille dame.",
      "Un regard aigu sur la façon dont on traite nos aînés.",
      "Un roman sur la solitude dans les grandes villes.",
    ],
    year: 2008,
    publisher: "J'ai lu",
    pages: 252,
    isbn: "9782290017722",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "celles-qui-attendent",
    title: "Celles qui attendent",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "femmes", "famille"],
    summary:
      "Sur l'île de Niodior, Arame et Bougna voient partir leurs fils, Lamine et Issa, en pirogue vers l'Europe. Ils laissent derrière eux leurs mères, mais aussi Coumba et Daba, leurs jeunes épouses. Commence alors la longue attente : les nouvelles qui ne viennent pas, l'argent espéré, les rumeurs, le regard du village. Fatou Diome raconte l'émigration du côté de celles qui restent, avec force et tendresse.",
    whyRead: [
      "L'émigration racontée du point de vue des femmes qui restent.",
      "Quatre portraits de femmes, deux mères et deux épouses.",
      "L'île natale de l'autrice, décrite avec amour et lucidité.",
    ],
    year: 2010,
    publisher: "J'ai lu",
    pages: 286,
    isbn: "9782290031988",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "impossible-de-grandir",
    title: "Impossible de grandir",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "identite", "exil"],
    summary:
      "Salie vit à Strasbourg. Une simple invitation à dîner chez des amis réveille en elle toute son enfance au Sénégal : une enfant née hors mariage, élevée par ses grands-parents, souvent rejetée par les autres. Pendant deux jours, la femme adulte dialogue avec la petite fille qu'elle a été et qui ne la quitte pas. Un roman très personnel sur les blessures d'enfance et le chemin pour devenir adulte.",
    whyRead: [
      "Un roman intime, en partie inspiré de la vie de l'autrice.",
      "Un dialogue bouleversant entre l'adulte et l'enfant qu'elle était.",
      "La place des enfants nés hors mariage, sujet rarement abordé.",
    ],
    year: 2013,
    publisher: "J'ai lu",
    pages: 506,
    isbn: "9782290093528",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "marianne-porte-plainte",
    title: "Marianne porte plainte !",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "exil"],
    summary:
      "En pleine campagne présidentielle française de 2017, Fatou Diome prend la plume pour répondre aux discours sur l'identité nationale. Franco-Sénégalaise, elle refuse qu'on oppose les Français « de souche » aux autres et plaide pour une France ouverte et multiple. Elle s'en prend à l'idée d'assimilation et défend la République et ses principes. Un essai court, vif et souvent drôle.",
    whyRead: [
      "Un pamphlet vif sur l'identité nationale et l'immigration.",
      "La voix d'une Franco-Sénégalaise qui aime la République.",
      "Un texte court, qui se lit d'une traite.",
    ],
    year: 2017,
    publisher: "Flammarion",
    pages: 139,
    isbn: "9782081408463",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-veilleurs-de-sangomar",
    title: "Les Veilleurs de Sangomar",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "spiritualite", "tradition", "femmes"],
    summary:
      "Coumba a perdu son mari, Bouba, dans le naufrage du Joola, le ferry qui a sombré au large de la Gambie en 2002. Pendant son veuvage, elle doit rester recluse dans sa belle-famille, sur une île du delta du Saloum, avec sa petite fille. Le jour, elle se plie aux rites ; la nuit, elle écrit dans un carnet et convoque les esprits de Sangomar, gardiens des morts selon les croyances sérères. Un roman sur le deuil, l'amour et la mémoire des disparus.",
    whyRead: [
      "Un hommage aux victimes du Joola, l'une des pires catastrophes maritimes.",
      "Une héroïne qui affronte le deuil avec l'écriture.",
      "Les croyances sérères du Saloum, racontées de l'intérieur.",
    ],
    year: 2019,
    publisher: "Le Livre de Poche",
    pages: 351,
    isbn: "9782253242178",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "de-quoi-aimer-vivre",
    title: "De quoi aimer vivre",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["amour", "famille", "exil"],
    summary:
      "Vingt ans après « La Préférence nationale », Fatou Diome revient à la nouvelle. Ses personnages, croisés ou rêvés, sont souvent seuls ou blessés : un boxeur, un pêcheur, un vieil homme sur sa barque. Chacun cherche, à sa manière, une raison de continuer. À travers ces histoires, l'autrice rappelle que l'amour et les liens humains sont ce qui nous fait tenir.",
    whyRead: [
      "Des nouvelles lumineuses sur ce qui donne envie de vivre.",
      "Une galerie de personnages attachants, en Afrique et en Europe.",
      "Le retour de Fatou Diome à la forme courte.",
    ],
    year: 2021,
    publisher: "Le Livre de Poche",
    pages: 184,
    isbn: "9782253106722",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "marianne-face-aux-faussaires",
    title: "Marianne face aux faussaires",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "spiritualite"],
    summary:
      "Cinq ans après « Marianne porte plainte ! », Fatou Diome reprend la parole au moment d'une nouvelle élection présidentielle. Elle s'attaque à ceux qu'elle appelle les faussaires : ceux qui se disent républicains mais désignent les immigrés comme boucs émissaires. Elle défend une laïcité sans adjectif, refuse aussi bien la xénophobie que les replis communautaires, et revendique sa double appartenance. Un essai combatif sur l'identité et la citoyenneté.",
    whyRead: [
      "Un plaidoyer pour une République fidèle à ses principes.",
      "Une défense claire de la laïcité et de l'universalisme.",
      "La suite de « Marianne porte plainte ! ».",
    ],
    year: 2022,
    publisher: "Albin Michel",
    pages: 184,
    isbn: "9782226472489",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "le-verbe-libre-ou-le-silence",
    title: "Le Verbe libre ou le silence",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "ecole"],
    summary:
      "Dans cet essai, Fatou Diome parle de ce qui la fait vivre : l'écriture. Elle dit le bonheur d'écrire la nuit, la liberté que lui donnent les mots depuis l'enfance. Elle s'en prend aussi à ceux qui voudraient dicter aux écrivains, en particulier africains, ce qu'ils doivent écrire et comment. Pour elle, l'écrivain n'a qu'un choix : le verbe libre, ou le silence.",
    whyRead: [
      "Une déclaration d'amour à l'écriture et à la liberté.",
      "Un regard sans détour sur le monde de l'édition.",
      "Pour mieux comprendre l'œuvre et le parcours de Fatou Diome.",
    ],
    year: 2023,
    publisher: "Albin Michel",
    pages: 184,
    isbn: "9782226483874",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "aucune-nuit-ne-sera-noire",
    title: "Aucune nuit ne sera noire",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "tradition"],
    summary:
      "Fatou Diome rend hommage à son grand-père maternel, le pêcheur du Saloum qui l'a élevée avec sa grand-mère dès ses premiers mois. Il était son capitaine, elle était son petit matelot. Chapitre après chapitre, chacun guidé par un mot, elle se souvient de ses leçons, de la mer, des nuits sur l'île et de la tendresse de ce vieil homme. Un livre de mémoire et de gratitude, lumineux et pudique.",
    whyRead: [
      "Un portrait tendre du grand-père qui a élevé l'autrice.",
      "L'enfance sur l'île de Niodior, entre mer et sagesse.",
      "Un livre de gratitude, à offrir.",
    ],
    year: 2025,
    publisher: "Albin Michel",
    pages: 328,
    isbn: "9782226504388",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Boubacar Boris Diop
  livre({
    slug: "le-temps-de-tamango",
    title: "Le Temps de Tamango",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "histoire"],
    summary:
      "En 2063, des historiens africains cherchent à reconstituer des événements survenus au Sénégal dans les années 1970 : une grève, une répression sanglante, un mouvement d'opposition. Au centre de l'histoire, N'Dongo, surnommé Tamango comme le héros révolté d'une nouvelle de Mérimée, est chargé d'éliminer un homme politique détesté. Le récit se construit et se défait sous nos yeux, entre notes, versions et narrateurs. L'édition originale est suivie d'une pièce, « Thiaroye terre rouge ».",
    whyRead: [
      "Le premier roman de Boubacar Boris Diop, audacieux et inventif.",
      "Un récit en morceaux qui joue avec l'histoire et la fiction.",
      "Suivi de « Thiaroye terre rouge », sa pièce sur le massacre de 1944.",
    ],
    year: 1981,
    publisher: "L'Harmattan",
    pages: 203,
    isbn: "9782858021857",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-tambours-de-la-memoire",
    title: "Les Tambours de la mémoire",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "colonisation", "identite", "contes"],
    summary:
      "Fadel, fils d'une famille aisée de Dakar, est obsédé par une figure légendaire : la reine Johanna Simentho, qui aurait mené la résistance contre les colons dans le royaume de Wissombo. Il part sur ses traces, au risque de tout perdre. Après sa mort, son amie reconstitue son histoire à partir de ses notes, de lettres et de récits. Inspiré d'Aline Sitoé Diatta, héroïne de Casamance, le roman interroge le pouvoir des mythes et de la mémoire.",
    whyRead: [
      "Une quête fascinante sur les traces d'une reine résistante.",
      "Une héroïne inspirée d'Aline Sitoé Diatta, figure de la Casamance.",
      "Un roman sur ce que les peuples font de leurs légendes.",
    ],
    year: 1987,
    publisher: "L'Harmattan",
    pages: 237,
    isbn: "9782738409126",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-traces-de-la-meute",
    title: "Les Traces de la meute",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "contes", "histoire"],
    summary:
      "À Dunya, un pays d'Afrique imaginaire, un homme a été témoin d'un crime atroce et ne sait plus très bien s'il l'a seulement vu ou s'il y a pris part. Rongé par la honte et le doute, il frôle la folie. En toile de fond, un dictateur se réclame d'un ancêtre légendaire, vainqueur d'un monstre qui terrorisait autrefois le pays. Boubacar Boris Diop mêle récit politique et légende pour montrer comment le pouvoir se fabrique des mythes.",
    whyRead: [
      "Un roman politique qui puise dans les contes et les légendes.",
      "Une réflexion sur la violence et la responsabilité de chacun.",
      "L'univers inventif de Boubacar Boris Diop, avant « Murambi ».",
    ],
    year: 1993,
    publisher: "L'Harmattan",
    pages: 269,
    isbn: "9782738422781",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-cavalier-et-son-ombre",
    title: "Le Cavalier et son ombre",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "contes", "identite"],
    summary:
      "Dans une petite ville au bord d'un fleuve, un voyageur solitaire attend le bateau qui doit lui permettre de traverser. De l'autre côté, une jeune femme lutte contre la mort : c'est Khadidja, qu'il a aimée autrefois. Pendant l'attente, les souvenirs et les histoires qu'elle racontait remontent et se mêlent au présent. Un roman envoûtant, entre réalité et imaginaire, sur l'amour, la folie et le pouvoir des récits.",
    whyRead: [
      "Un roman envoûtant, où les histoires s'emboîtent comme dans un conte.",
      "Une histoire d'amour et d'attente au bord d'un fleuve.",
      "Réédité en 2024 par Philippe Rey.",
    ],
    year: 1997,
    publisher: "Philippe Rey",
    pages: 237,
    isbn: "9782384820726",
    format: null,
    awards: [],
  }),
  livre({
    slug: "negrophobie",
    title: "Négrophobie",
    contributors: [
      auteur("Boubacar Boris Diop", "boubacar-boris-diop"),
      { role: "auteur", name: "Odile Tobner", authorSlug: null },
      { role: "auteur", name: "François-Xavier Verschave", authorSlug: null },
    ],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "colonisation", "identite"],
    summary:
      "En 2003, un livre à succès d'un journaliste français décrivait une Afrique condamnée par ses propres maux. Dans ce livre à trois voix, Boubacar Boris Diop, Odile Tobner et François-Xavier Verschave lui répondent point par point. Ils y voient le retour de vieux clichés coloniaux et dénoncent la façon dont une partie des médias parle de l'Afrique. Un essai de combat sur les préjugés et sur les relations entre la France et le continent.",
    whyRead: [
      "Une réponse argumentée aux clichés sur l'Afrique.",
      "Trois auteurs engagés contre le racisme ordinaire.",
      "Pour réfléchir à la façon dont on parle de l'Afrique.",
    ],
    year: 2005,
    publisher: "Les Arènes",
    pages: 201,
    isbn: "9782912485816",
    format: null,
    awards: [],
  }),
  livre({
    slug: "kaveena",
    title: "Kaveena",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "guerre", "famille"],
    summary:
      "Dans un pays d'Afrique ravagé par la guerre civile, le colonel Asante Kroma, chef de la police politique, découvre le corps de l'ancien président N'Zo Nikiema dans la maison de sa maîtresse, Mumbi Awele. Quelques années plus tôt, la petite fille de celle-ci, Kaveena, a été assassinée. Kroma remonte le fil de l'histoire : l'ascension de Nikiema, ses alliances troubles avec la France, l'avidité et la violence du pouvoir. Un roman noir et puissant sur la Françafrique.",
    whyRead: [
      "Un roman noir haletant, au cœur d'une dictature.",
      "Une dénonciation féroce de la Françafrique.",
      "Réédité en 2024 par Philippe Rey.",
    ],
    year: 2006,
    publisher: "Philippe Rey",
    pages: 299,
    isbn: "9782384820719",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-afrique-au-dela-du-miroir",
    title: "L'Afrique au-delà du miroir",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "genocide", "identite", "exil"],
    summary:
      "Dans ces textes, Boubacar Boris Diop s'attaque aux images déformées que l'on donne de l'Afrique, et que les Africains finissent parfois par croire. Il y rend hommage à Cheikh Anta Diop et à Mongo Beti, revient sur le génocide des Tutsi au Rwanda, sur le naufrage du Joola, sur les migrations vers l'Europe. Il y parle aussi de la situation de l'écrivain africain, tiraillé entre deux langues. Un essai engagé pour regarder l'Afrique en face.",
    whyRead: [
      "Un regard africain sur les grands drames du continent.",
      "Des hommages à Cheikh Anta Diop et Mongo Beti.",
      "La pensée de l'auteur de « Murambi », en prise avec l'actualité.",
    ],
    year: 2007,
    publisher: "Philippe Rey",
    pages: 215,
    isbn: "9782848760681",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-petits-de-la-guenon",
    title: "Les Petits de la guenon",
    contributors: [
      auteur("Boubacar Boris Diop", "boubacar-boris-diop"),
      { role: "traducteur", name: "Boubacar Boris Diop", authorSlug: null },
    ],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "contes", "politique"],
    summary:
      "Nguirane Faye, un vieil homme, écrit des carnets pour son petit-fils Badou, parti à l'étranger, sans savoir s'il le reverra. Il y raconte sa vie, son quartier, les histoires des siens, et y glisse des contes, dont celui d'une mère qui transforme ses enfants en petits singes pour les protéger. Peu à peu se dessine aussi la chronique d'un pays et de ses dirigeants. Écrit d'abord en wolof sous le titre « Doomi Golo », le roman a été réécrit en français par l'auteur.",
    whyRead: [
      "Un grand roman écrit d'abord en wolof, puis réécrit en français.",
      "Les carnets émouvants d'un grand-père pour son petit-fils exilé.",
      "Un mélange réussi de contes, de chronique et de satire politique.",
    ],
    year: 2003,
    originalLanguage: "wolof",
    publisher: "Philippe Rey",
    pages: 438,
    isbn: "9782384820733",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-gloire-des-imposteurs",
    title: "La Gloire des imposteurs",
    subtitle: "Lettres sur le Mali et l'Afrique",
    contributors: [
      auteur("Boubacar Boris Diop", "boubacar-boris-diop"),
      { role: "auteur", name: "Aminata Dramane Traoré", authorSlug: null },
    ],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "guerre", "colonisation"],
    summary:
      "En 2012 et 2013, alors que le nord du Mali tombe aux mains de groupes armés et que la France intervient militairement, deux intellectuels s'écrivent. L'écrivain sénégalais Boubacar Boris Diop et l'essayiste malienne Aminata Dramane Traoré, ancienne ministre de la Culture, échangent des lettres sur la crise. Ils y interrogent l'intervention française, la souveraineté des États africains et les idées reçues sur le continent. Un dialogue franc entre deux voix engagées.",
    whyRead: [
      "Un échange de lettres au cœur de la crise malienne.",
      "Deux grandes voix africaines, un Sénégalais et une Malienne.",
      "Pour comprendre les débats sur l'intervention française au Mali.",
    ],
    year: 2013,
    publisher: "Philippe Rey",
    pages: 233,
    isbn: "9782848762326",
    format: null,
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = ["un-chant-ecarlate", "xala", "le-docker-noir", "o-pays-mon-beau-peuple", "chants-d-ombre", "terre-ceinte",
  "les-gardiens-du-temple", "voltaique", "l-harmattan", "vehi-ciosane-suivi-du-mandat", "le-dernier-de-l-empire", "niiwam-suivi-de-taaw", "guelwaar", "hosties-noires", "anthologie-de-la-nouvelle-poesie-negre-et-malgache", "chants-pour-naett", "la-belle-histoire-de-leuk-le-lievre", "nocturnes", "nation-et-voie-africaine-du-socialisme", "liberte-1-negritude-et-humanisme", "les-fondements-de-l-africanite", "liberte-2-nation-et-voie-africaine-du-socialisme", "lettres-d-hivernage", "liberte-3-negritude-et-civilisation-de-l-universel", "elegies-majeures", "la-poesie-de-l-action", "liberte-4-socialisme-et-planification", "ce-que-je-crois", "oeuvre-poetique", "liberte-5-le-dialogue-des-cultures", "silence-du-choeur", "de-purs-hommes", "la-preference-nationale", "ketala", "inassouvies-nos-vies", "celles-qui-attendent", "impossible-de-grandir", "marianne-porte-plainte", "les-veilleurs-de-sangomar", "de-quoi-aimer-vivre", "marianne-face-aux-faussaires", "le-verbe-libre-ou-le-silence", "aucune-nuit-ne-sera-noire", "le-temps-de-tamango", "les-tambours-de-la-memoire", "les-traces-de-la-meute", "le-cavalier-et-son-ombre", "negrophobie", "kaveena", "l-afrique-au-dela-du-miroir", "les-petits-de-la-guenon", "la-gloire-des-imposteurs",
];
