/**
 * Lot 08 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * BD des auteurs déjà présents sur le site (les tomes d'une série ont chacun leur fiche).
 */
import type { Author, Book, Contributor } from "../../types";

type Saisie = Omit<
  Book,
  "kind" | "genre" | "format" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"
> &
  Partial<Pick<Book, "subtitle" | "originalLanguage" | "genre" | "format">>;

const commun = {
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
};

/** Bande dessinée (rubrique /bd). */
const bd = (b: Saisie): Book => ({ kind: "bd", genre: "bd", format: "album", ...commun, ...b });

/** Livre (rubrique /livres). */
const livre = (b: Saisie & Pick<Book, "genre">): Book => ({ kind: "livre", format: null, ...commun, ...b });

const sc = (name: string, authorSlug: string | null = null): Contributor => ({ role: "scenariste", name, authorSlug });
const de = (name: string, authorSlug: string | null = null): Contributor => ({ role: "dessinateur", name, authorSlug });
const au = (name: string, authorSlug: string | null = null): Contributor => ({ role: "auteur", name, authorSlug });

const ABOUET = sc("Marguerite Abouet", "marguerite-abouet");
const OUBRERIE = de("Clément Oubrerie");
const SAPIN = de("Mathieu Sapin");
const PAHE = de("Pahé", "pahe");
const ESSO = "joelle-esso";
const KASSAI = "didier-kassai";
const BARUTI = de("Barly Baruti", "barly-baruti");
const GIROUD = sc("Frank Giroud");
const EDIMO = sc("Christophe Ngalle Edimo", "christophe-ngalle-edimo");
const MBUMBO = "simon-pierre-mbumbo";
const MASIONI = de("Pat Masioni", "pat-masioni");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------ Marguerite Abouet : Aya de Yopougon
  bd({
    slug: "aya-de-yopougon-tome-2",
    title: "Aya de Yopougon",
    subtitle: "Tome 2",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["ville", "femmes", "famille", "amour"],
    summary:
      "À Yopougon, le bébé d'Adjoua bouleverse les familles : chez les Sissoko, personne ne veut croire que Moussa en est le père. Adjoua se débrouille seule et compte beaucoup sur Aya pour garder l'enfant, tandis que Bintou n'a d'yeux que pour un beau parleur fraîchement rentré de Paris. Pendant ce temps, Ignace accumule les ennuis au travail et tout le quartier se prépare pour l'élection de Miss Yopougon. La chronique d'Abidjan à la fin des années 1970 prend de l'ampleur, avec ses secrets de famille et ses rires.",
    whyRead: [
      "La suite directe du premier tome, encore plus riche en personnages.",
      "Un regard drôle et tendre sur les familles d'Abidjan.",
      "Les dialogues savoureux du parler ivoirien, expliqués en fin d'album.",
    ],
    year: 2006,
    publisher: "Gallimard BD",
    pages: 106,
    isbn: "9782075171212",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-3",
    title: "Aya de Yopougon",
    subtitle: "Tome 3",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["ville", "femmes", "famille", "identite"],
    summary:
      "La maîtresse d'Ignace a débarqué chez lui avec deux enfants, et la famille d'Aya vacille. Pendant que sa mère prend ses distances, Aya doit encore aider tout le monde : Adjoua qui tente de vendre des beignets pour nourrir son fils, Bintou qui se croit enfin aimée, et Albert, qui cache à ses proches une vie amoureuse impossible à avouer. Le concours de Miss Yopougon approche et chacun y joue un peu plus que sa fierté. Un tome où la comédie de quartier laisse affleurer des questions plus graves.",
    whyRead: [
      "Le tome où la série aborde l'homosexualité, sujet encore tabou à Abidjan.",
      "Des héroïnes qui grandissent et prennent leur vie en main.",
      "L'humour reste là, même quand les familles se déchirent.",
    ],
    year: 2007,
    publisher: "Gallimard BD",
    pages: 126,
    isbn: "9782075171229",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-4",
    title: "Aya de Yopougon",
    subtitle: "Tome 4",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["femmes", "exil", "ville", "ecole"],
    summary:
      "Innocent, le coiffeur de Yopougon, a tenté sa chance à Paris : il découvre un foyer d'immigrés, le travail sans papiers et une ville bien moins accueillante que prévu. À Abidjan, Aya entre à l'université et se retrouve la cible d'un professeur qui abuse de son pouvoir. Le père de Félicité réapparaît pour réclamer sa fille devenue célèbre grâce à une publicité, et Mamadou trouve une drôle de façon de faire vivre sa petite famille. La série élargit son horizon, entre Côte d'Ivoire et France.",
    whyRead: [
      "Le harcèlement à l'université, raconté sans détour et sans lourdeur.",
      "Un premier regard sur l'exil en France, vu depuis Yopougon.",
      "Une galerie de personnages qui prend de l'épaisseur à chaque tome.",
    ],
    year: 2008,
    publisher: "Gallimard BD",
    pages: 106,
    isbn: "9782075171236",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-5",
    title: "Aya de Yopougon",
    subtitle: "Tome 5",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["femmes", "famille", "spiritualite", "exil"],
    summary:
      "Aya n'a pas renoncé à faire tomber le professeur qui l'a agressée, et elle découvre qu'elle n'est pas sa seule victime. Félicité, que l'on croit riche, est retenue au village par son père, et ses amis s'organisent pour aller la chercher. Grégoire s'est improvisé pasteur pour vider la poche des fidèles, tandis que les Sissoko cherchent toujours Moussa, parti avec l'argent de la famille. À Paris, Innocent apprend que vivre son homosexualité au grand jour n'y est pas si simple.",
    whyRead: [
      "Une héroïne qui refuse de se taire face à un homme puissant.",
      "La satire des faux prophètes, aussi drôle que juste.",
      "Abidjan et Paris se répondent, chacune avec ses illusions.",
    ],
    year: 2009,
    publisher: "Gallimard BD",
    pages: 106,
    isbn: "9782075171243",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-6",
    title: "Aya de Yopougon",
    subtitle: "Tome 6",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["femmes", "famille", "amour", "ville"],
    summary:
      "À Yopougon comme à Paris, les fils des intrigues se resserrent. Aya, qui se rapproche enfin d'un garçon qui lui plaît, n'en a pas fini avec le professeur qui la harcèle, et ses amies sont prêtes à tout pour l'aider. Grégoire et Moussa doivent répondre de leurs frasques, les secrets de famille remontent à la surface et Innocent se heurte à son tour aux préjugés en France. Ce sixième tome referme le premier grand cycle de la série.",
    whyRead: [
      "Le tome qui dénoue les intrigues du premier cycle.",
      "Une belle histoire d'amitié entre femmes, solidaires face à l'injustice.",
      "Des secrets de famille révélés avec beaucoup d'humour.",
    ],
    year: 2010,
    publisher: "Gallimard BD",
    pages: 104,
    isbn: "9782075171250",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-7",
    title: "Aya de Yopougon",
    subtitle: "Tome 7",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["politique", "femmes", "ecole", "exil"],
    summary:
      "Douze ans après le sixième tome, la série reprend : Aya fait un stage à la Solibra, l'entreprise de son père, tout en s'engageant aux côtés des étudiants de l'université de Cocody. Albert, rejeté par les siens, cherche un toit dans des résidences saturées, et Bintou, devenue vedette d'un feuilleton télévisé, découvre que le public la confond avec son rôle. À Paris, Innocent vit sans papiers. Chacun tente à sa manière de prendre son destin en main.",
    whyRead: [
      "Le grand retour de la série après une longue pause.",
      "Des combats d'aujourd'hui : droits des étudiants, sans-papiers, homosexualité.",
      "Bintou en star de télévision, un rôle taillé pour elle.",
    ],
    year: 2022,
    publisher: "Gallimard BD",
    pages: 118,
    isbn: "9782075163989",
    awards: [],
  }),
  bd({
    slug: "aya-de-yopougon-tome-8",
    title: "Aya de Yopougon",
    subtitle: "Tome 8",
    contributors: [ABOUET, OUBRERIE],
    audience: "ado",
    themes: ["ville", "famille", "spiritualite", "femmes"],
    summary:
      "Rien ne va plus à Yopougon : Albert se retrouve enfermé dans un village reculé, aux mains d'un charlatan qui prétend le « guérir » de son homosexualité. Moussa a disparu, un autre proche est à l'hôpital, et Bintou n'a plus de maison après l'incendie de sa villa. Tous auraient besoin d'Aya, mais celle-ci reste introuvable depuis sa sortie de prison. Un tome mouvementé, où le quartier part à la recherche des siens.",
    whyRead: [
      "Un tome au rythme haletant, où chacun cherche quelqu'un.",
      "Une dénonciation claire des charlatans et des « thérapies » de conversion.",
      "Toujours le même plaisir de retrouver la bande de Yop City.",
    ],
    year: 2023,
    publisher: "Gallimard BD",
    pages: 96,
    isbn: "9782075193108",
    awards: [],
  }),

  // ------------------------------------------------------------ Marguerite Abouet : Akissi
  bd({
    slug: "akissi-super-heros-en-platre",
    title: "Akissi",
    subtitle: "Super-héros en plâtre",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "humour", "ecole"],
    summary:
      "Akissi, la petite terreur de Yopougon, revient pour sept nouvelles histoires. Avec son copain Edmond, elle rêve de jeter un sort au maître d'école qui les a punis, puis imagine attraper des poux pour échapper à la séance de coiffure. Edmond, lui, se prend pour Spectreman, un super-héros de la télévision, et Akissi doit le ramener sur terre. Des aventures courtes et pleines d'énergie, idéales pour les jeunes lecteurs.",
    whyRead: [
      "Des histoires courtes, faciles à lire seul dès 6 ans.",
      "Une héroïne espiègle qui ne recule devant aucune bêtise.",
      "Des pages bonus en fin d'album : recettes et coiffures africaines.",
    ],
    year: 2011,
    publisher: "Gallimard Jeunesse",
    pages: 44,
    isbn: "9782070639564",
    awards: [],
  }),
  bd({
    slug: "akissi-vacances-dangereuses",
    title: "Akissi",
    subtitle: "Vacances dangereuses",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "humour", "famille", "tradition"],
    summary:
      "Pour les vacances, Akissi quitte Abidjan pour le village. Le voyage en taxi-brousse commence mal : le chauffeur provoque un accident et un mouton s'échappe parmi les bagages. Akissi se lance aussitôt à la poursuite de l'animal, bien décidée à le retrouver. Au village, entre cousins, grands-parents et coutumes nouvelles pour elle, chaque journée réserve son lot de surprises.",
    whyRead: [
      "La découverte de la vie au village, vue par une enfant de la ville.",
      "Des gags qui s'enchaînent sans temps mort.",
      "Une série jeunesse qui fait voyager en Côte d'Ivoire.",
    ],
    year: 2012,
    publisher: "Gallimard Jeunesse",
    pages: 44,
    isbn: "9782070646449",
    awards: [],
  }),
  bd({
    slug: "akissi-rentree-musclee",
    title: "Akissi",
    subtitle: "Rentrée musclée",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "ecole", "humour"],
    summary:
      "Akissi redoute la rentrée des classes. Pour ne plus y penser, elle se lance dans une course-poursuite effrénée avec Edmond, alias Spectreman, qui se termine par un clou planté dans la tête. Un petit accident qui pourrait bien lui éviter l'école quelque temps... Comme toujours, les histoires s'enchaînent dans le quartier de Yopougon, entre voisins, marchandes et copains de jeu.",
    whyRead: [
      "Toutes les angoisses de la rentrée, transformées en comédie.",
      "Le duo Akissi et Edmond, toujours aussi inventif.",
      "Un dessin vif et coloré qui plaît aux plus jeunes.",
    ],
    year: 2013,
    publisher: "Gallimard Jeunesse",
    pages: 44,
    isbn: "9782070649822",
    awards: [],
  }),
  bd({
    slug: "akissi-mixture-magique",
    title: "Akissi",
    subtitle: "Mixture magique",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "spiritualite", "humour", "famille"],
    summary:
      "La maman d'Akissi n'arrive pas à avoir un autre enfant et fait appel au marabout du village. Mais celui-ci procède d'une bien étrange façon : il accuse Akissi d'être possédée et l'oblige à avaler une affreuse potion. La fillette bascule alors dans un monde imaginaire peuplé d'animaux qui parlent et de forêts enchantées. Un album plus onirique que les précédents, qui se moque des charlatans sans perdre sa fantaisie.",
    whyRead: [
      "Un voyage imaginaire au cœur de la série.",
      "Une façon drôle de parler des croyances et des charlatans.",
      "Akissi, toujours aussi effrontée face aux adultes.",
    ],
    year: 2014,
    publisher: "Gallimard",
    pages: 44,
    isbn: "9782070658886",
    awards: [],
  }),
  bd({
    slug: "akissi-sans-amis",
    title: "Akissi",
    subtitle: "Sans amis",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "ecole", "humour"],
    summary:
      "Une nouvelle élève arrive à l'école : Sido, jolie, gentille, pleine de jouets venus de France, et qui a perdu une jambe, croquée par un lion selon la rumeur. Toutes les filles veulent devenir son amie, sauf Akissi, qui se sent soudain éclipsée. Jalouse, elle multiplie les coups bas et se retrouve vite isolée. Six histoires qui parlent avec humour de l'envie, de la différence et de l'amitié.",
    whyRead: [
      "Une histoire sur la jalousie que tous les enfants comprendront.",
      "Un regard simple et juste sur le handicap.",
      "Des pages bonus pour apprendre à dessiner Akissi.",
    ],
    year: 2015,
    publisher: "Gallimard",
    pages: 44,
    isbn: "9782070665495",
    awards: [],
  }),
  bd({
    slug: "akissi-faux-depart",
    title: "Akissi",
    subtitle: "Faux départ",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "famille", "exil", "humour"],
    summary:
      "Drame à Yopougon : les parents de Pélagie se séparent et la fillette risque de déménager. Akissi et ses amis sont prêts à tout pour empêcher ce divorce. Mais Akissi a aussi ses propres soucis : un oncle venu de France veut l'emmener avec lui dans ce pays lointain, qu'elle imagine peuplé d'ours polaires. Il va falloir redoubler de malice pour que personne ne quitte ce petit coin de Côte d'Ivoire.",
    whyRead: [
      "La France vue d'Abidjan, avec beaucoup d'humour.",
      "Des enfants qui tentent de déjouer les décisions des adultes.",
      "Le début d'un grand tournant dans la vie d'Akissi.",
    ],
    year: 2016,
    publisher: "Gallimard BD",
    pages: 44,
    isbn: "9782070604166",
    awards: [],
  }),
  bd({
    slug: "akissi-mission-pas-possible",
    title: "Akissi",
    subtitle: "Mission pas possible",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "famille", "exil", "humour"],
    summary:
      "Le départ d'Akissi pour la France se précise, et tout le quartier en profite pour lui confier des missions. Son grand-père lui demande même de retrouver là-bas une infirmière qu'il a connue pendant la guerre, en 1944. À l'école, les élèves préparent des exposés sur la France qui en donnent une image peu flatteuse, et les voisines voudraient lui confier leurs bébés. Akissi, elle, est bien la seule à ne pas se réjouir du voyage.",
    whyRead: [
      "Les clichés sur la France, retournés avec malice.",
      "Un grand-père et un souvenir de guerre au cœur de l'histoire.",
      "Des cartes de la Côte d'Ivoire et de la France en fin d'album.",
    ],
    year: 2018,
    publisher: "Gallimard BD",
    pages: 44,
    isbn: "9782075084697",
    awards: [],
  }),
  bd({
    slug: "akissi-aller-retour",
    title: "Akissi",
    subtitle: "Aller-retour",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "famille", "humour"],
    summary:
      "À force de bêtises, Akissi a réussi l'impossible : faire revenir l'avion qui l'emmenait en France. De retour à la maison, elle se souvient des moments qui la lient à son pays : sa première rencontre avec Edmond, le sauvetage de Boubou, son singe adoré, un déguisement de Mardi gras ou une promenade avec son grand-père. Six histoires drôles et un brin nostalgiques, suivies de pages de jeux et de bricolage.",
    whyRead: [
      "Des souvenirs d'enfance pleins de tendresse.",
      "La rencontre d'Akissi et d'Edmond enfin racontée.",
      "Un album drôle qui touche aussi par sa nostalgie.",
    ],
    year: 2019,
    publisher: "Gallimard BD",
    pages: 44,
    isbn: "9782075129534",
    awards: [],
  }),
  bd({
    slug: "akissi-enfermes-dedans",
    title: "Akissi",
    subtitle: "Enfermés dedans",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "famille", "humour"],
    summary:
      "Pour Noël, Akissi a reçu une poupée toute neuve, mais elle préfère s'occuper des vrais bébés du quartier, surtout quand leurs parents ne lui ont rien demandé. Avec ses fidèles copains, elle multiplie les expériences. Puis un confinement soudain l'oblige à rester enfermée chez elle, et la fillette qui ne tient pas en place se retrouve bien embarrassée. L'album qui fête les dix ans de la série.",
    whyRead: [
      "Le confinement raconté à hauteur d'enfant, avec humour.",
      "Akissi en nounou improvisée : effet garanti.",
      "L'album anniversaire des dix ans de la série.",
    ],
    year: 2020,
    publisher: "Gallimard BD",
    pages: 44,
    isbn: "9782075150095",
    awards: [],
  }),
  bd({
    slug: "akissi-paix-temporaire",
    title: "Akissi",
    subtitle: "Paix temporaire",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["enfance", "ecole", "humour"],
    summary:
      "C'est Mardi gras à Yopougon. Comme chaque année, les élèves de monsieur Adama présentent leurs costumes, et le plus original remporte une médaille et des crêpes. Akissi, elle, refuse catégoriquement de se déguiser : pas question de finir en princesse. Elle préfère encore se faire gronder... à moins que les choses ne tournent autrement que prévu.",
    whyRead: [
      "Une héroïne qui n'en fait qu'à sa tête, pour le plus grand plaisir des lecteurs.",
      "La fête de Mardi gras à l'école, pleine de rebondissements.",
      "Le onzième tome d'une série jeunesse incontournable.",
    ],
    year: 2024,
    publisher: "Gallimard BD",
    pages: 44,
    isbn: "9782075205351",
    awards: [],
  }),
  bd({
    slug: "akissi-de-paris",
    title: "Akissi de Paris",
    subtitle: "Tome 1",
    contributors: [ABOUET, SAPIN],
    audience: "jeunesse",
    themes: ["exil", "ecole", "identite", "humour"],
    summary:
      "Akissi a maintenant douze ans et vient de quitter la Côte d'Ivoire. Avec son frère Fofana, elle s'installe chez leur grand-oncle à Paris et fait sa rentrée dans un collège parisien. Nouveau pays, nouveaux codes, nouveaux camarades : l'intégration est rude, et les deux adolescents n'ont qu'une envie, rentrer à Abidjan. Marguerite Abouet puise dans sa propre arrivée en France pour ouvrir ce nouveau chapitre de la vie de son héroïne.",
    whyRead: [
      "Akissi grandit : une nouvelle série pour les préadolescents.",
      "L'arrivée en France racontée avec humour et justesse.",
      "Inspiré des souvenirs de l'autrice, arrivée à Paris à douze ans.",
    ],
    year: 2024,
    publisher: "Gallimard BD",
    pages: 71,
    isbn: "9782075196291",
    awards: [],
  }),

  // ------------------------------------------------------------ Marguerite Abouet : Bienvenue, Commissaire Kouamé, Terre gâtée
  bd({
    slug: "bienvenue-tome-1",
    title: "Bienvenue",
    subtitle: "Tome 1",
    contributors: [ABOUET, de("Singeon")],
    audience: "adulte",
    themes: ["ville", "femmes", "amour"],
    summary:
      "Bienvenue est étudiante aux Beaux-Arts de Paris. Sans le sou, elle enchaîne les petits boulots et partage un appartement avec Lola, sa cousine délurée. Entre les enfants qu'elle garde, le nouvel amoureux de sa mère, les chagrins de Lola et une jeune fille fragile qui s'accroche à elle, elle passe son temps à s'occuper des autres. Et sa propre vie, dans tout ça ? Marguerite Abouet transpose à Paris l'art de la chronique qu'elle a déployé dans Aya de Yopougon.",
    whyRead: [
      "Une comédie parisienne par la scénariste d'Aya de Yopougon.",
      "Une héroïne généreuse jusqu'à l'oubli de soi.",
      "Le Paris des étudiants fauchés, croqué avec tendresse.",
    ],
    year: 2010,
    publisher: "Gallimard",
    pages: 106,
    isbn: "9782070626410",
    awards: [],
  }),
  bd({
    slug: "bienvenue-tome-2",
    title: "Bienvenue",
    subtitle: "Tome 2",
    contributors: [ABOUET, de("Singeon")],
    audience: "adulte",
    themes: ["ville", "femmes", "famille"],
    summary:
      "Les galères continuent pour Bienvenue : plus d'argent, une garde d'enfants qui tourne court, un professeur qui réclame son travail et un père qui refait surface dans sa vie. Mais ce sont surtout les soucis de ses voisins qui l'occupent, car l'étudiante ne sait pas dire non et se retrouve au cœur de toutes leurs histoires. Quand trouvera-t-elle le temps de penser à son cœur ?",
    whyRead: [
      "Une galerie de voisins hauts en couleur.",
      "Le portrait drôle d'une jeune femme incapable de dire non.",
      "Une chronique de la vie d'immeuble à Paris.",
    ],
    year: 2012,
    publisher: "Gallimard",
    pages: 104,
    isbn: "9782070645978",
    awards: [],
  }),
  bd({
    slug: "bienvenue-tome-3",
    title: "Bienvenue",
    subtitle: "Tome 3",
    contributors: [ABOUET, de("Singeon")],
    audience: "adulte",
    themes: ["amour", "femmes", "famille"],
    summary:
      "Un baiser inattendu vient compliquer encore la vie déjà bien emmêlée de Bienvenue. Épuisée de devoir régler les problèmes de ses voisins, elle accepte de partir quelques jours en Normandie avec le père de deux enfants qu'elle garde. Loin de l'agitation parisienne, elle espère enfin respirer et y voir plus clair. Le dernier tome de la série.",
    whyRead: [
      "Le dernier tome, qui emmène Bienvenue loin de Paris.",
      "Une héroïne qui apprend enfin à penser à elle.",
      "Une comédie sentimentale fine et lumineuse.",
    ],
    year: 2014,
    publisher: "Gallimard",
    pages: 105,
    isbn: "9782070653348",
    awards: [],
  }),
  bd({
    slug: "commissaire-kouame-un-si-joli-jardin",
    title: "Commissaire Kouamé",
    subtitle: "Un si joli jardin",
    contributors: [ABOUET, de("Donatien Mary")],
    audience: "adulte",
    themes: ["ville", "humour", "politique"],
    summary:
      "À Abidjan, un célèbre magistrat est retrouvé assassiné dans un hôtel de passe minable. Personne n'a rien vu et l'affaire doit rester discrète pour éviter le scandale. Le commissaire Marius Kouamé, surnommé le « scorpion urbain », prend l'enquête en main avec son fidèle adjoint Arsène. Leurs méthodes sont aussi étonnantes qu'efficaces : Marguerite Abouet se lance dans le polar, avec sa verve et son humour habituels.",
    whyRead: [
      "Un polar ivoirien loufoque et plein de rythme.",
      "Un duo d'enquêteurs aux méthodes très particulières.",
      "Prix BD du polar SNCF 2019.",
    ],
    year: 2017,
    publisher: "Gallimard BD",
    pages: 98,
    isbn: "9782075076920",
    awards: [{ name: "Prix BD du polar SNCF", year: 2019 }],
  }),
  bd({
    slug: "commissaire-kouame-un-homme-tombe-avec-son-ombre",
    title: "Commissaire Kouamé",
    subtitle: "Un homme tombe avec son ombre",
    contributors: [ABOUET, de("Donatien Mary")],
    audience: "adulte",
    themes: ["ville", "spiritualite", "politique"],
    summary:
      "La fille d'un grand patron français disparaît en plein jour dans les rues d'Abidjan. Le commissaire Kouamé est chargé de l'affaire, avec un ultimatum : s'il ne la retrouve pas très vite, la police française prendra le relais. L'adolescente est albinos, et l'enquête mène sur la piste de sordides affaires de sorcellerie. Une deuxième enquête qui mêle humour et sujets graves.",
    whyRead: [
      "Un polar qui dénonce les violences faites aux personnes albinos.",
      "Le retour d'un commissaire aussi drôle qu'obstiné.",
      "Abidjan, ses quartiers et ses contrastes en toile de fond.",
    ],
    year: 2021,
    publisher: "Gallimard BD",
    pages: 113,
    isbn: "9782075150194",
    awards: [],
  }),
  bd({
    slug: "commissaire-kouame-on-ne-fait-pas-de-feu-sous-un-arbre-en-fleur",
    title: "Commissaire Kouamé",
    subtitle: "On ne fait pas de feu sous un arbre en fleur",
    contributors: [ABOUET, de("Donatien Mary")],
    audience: "adulte",
    themes: ["ville", "exil", "femmes"],
    summary:
      "À Abidjan, un caïd de la drogue s'évade de prison en laissant derrière lui deux policiers corrompus. À Angoulême, une jeune Ivoirienne disparaît, enlevée par un réseau de traite des êtres humains. Le commissaire Kouamé et son adjoint Arsène mènent les deux enquêtes de front, quitte à bousculer les procédures des deux pays. Une enquête entre Côte d'Ivoire et France.",
    whyRead: [
      "Une enquête à cheval entre Abidjan et Angoulême.",
      "La traite des êtres humains au cœur d'un polar populaire.",
      "Le duo Kouamé et Arsène, plus déterminé que jamais.",
    ],
    year: 2025,
    publisher: "Gallimard BD",
    pages: 94,
    isbn: "9782075211512",
    awards: [],
  }),
  bd({
    slug: "terre-gatee-ange-le-migrant",
    title: "Terre gâtée",
    subtitle: "Ange, le migrant",
    contributors: [ABOUET, sc("Charli Beléteau"), de("Christian De Metter")],
    audience: "adulte",
    themes: ["exil", "travail", "spiritualite"],
    summary:
      "Un homme défiguré, rescapé du désert, arrive dans un village d'Afrique. Les habitants le prennent pour un migrant qui a échoué à traverser la mer, mais le pasteur, lui, y voit un ange et le baptise ainsi. Muet sur son passé, Ange est bientôt embauché sur le chantier d'une route, dirigé par une femme d'affaires influente qui exploite les candidats au départ. Une fable sous forme de western africain, autour de l'émigration et de ceux qui en profitent.",
    whyRead: [
      "Un western africain inattendu, au trait réaliste.",
      "Une fable sur ceux qui exploitent le rêve de partir.",
      "Une autre facette de Marguerite Abouet, plus sombre.",
    ],
    year: 2018,
    publisher: "Rue de Sèvres",
    pages: 84,
    isbn: "9782369815020",
    awards: [],
  }),

  // ------------------------------------------------------------ Pahé
  bd({
    slug: "la-vie-de-pahe-paname",
    title: "La Vie de Pahé",
    subtitle: "Paname",
    contributors: [sc("Pahé", "pahe"), PAHE],
    audience: "ado",
    themes: ["exil", "enfance", "humour", "ecole"],
    summary:
      "Dans ce deuxième tome de son autobiographie dessinée, Pahé raconte ses allers et retours entre le Gabon et la France. Le petit garçon de Bitam découvre Paris, le collège français, les codes d'un pays qui n'est pas le sien et le regard des autres. Chaque retour au pays le confronte aussi à ce qui a changé, chez lui comme autour de lui. Une chronique pleine d'autodérision sur le fait de grandir entre deux cultures.",
    whyRead: [
      "La suite de Bitam, avec le même humour décapant.",
      "Grandir entre le Gabon et la France, raconté de l'intérieur.",
      "Un regard malicieux sur les différences entre les deux pays.",
    ],
    year: 2008,
    publisher: "Paquet",
    pages: 64,
    isbn: "9782888902423",
    awards: [],
  }),
  bd({
    slug: "dipoula-l-albinos-contre-le-petit-pahe",
    title: "Dipoula",
    subtitle: "Dipoula l'Albinos contre le petit Pahé",
    contributors: [sc("Louis-Bertrand Devaud"), PAHE],
    audience: "jeunesse",
    themes: ["enfance", "humour", "identite"],
    summary:
      "Dipoula, petit Gabonais albinos élevé à l'orphelinat des sœurs, voit arriver dans sa classe le petit Pahé, un garçon gabonais installé en France et revenu au pays pour un temps. L'un est « un Noir blanc », l'autre « un Français noir » : entre eux, la rivalité s'installe avant que l'amitié ne s'en mêle. En gags d'une ou deux pages, l'album parle de richesse et de pauvreté, d'identité et surtout de différence.",
    whyRead: [
      "La rencontre de deux personnages fétiches de Pahé.",
      "Des gags courts qui parlent de différence avec légèreté.",
      "Pas besoin d'avoir lu le premier tome pour en profiter.",
    ],
    year: 2010,
    publisher: "Paquet",
    pages: 48,
    isbn: "9782888903833",
    awards: [],
  }),
  bd({
    slug: "dipoula-la-vie-gabonaise",
    title: "Dipoula",
    subtitle: "La Vie gabonaise",
    contributors: [sc("Louis-Bertrand Devaud"), sc("Sti"), PAHE],
    audience: "jeunesse",
    themes: ["enfance", "humour", "identite"],
    summary:
      "Troisième album des aventures de Dipoula, le petit orphelin albinos de huit ans. Toujours entouré de sa bande de copains, il fait les quatre cents coups dans un quartier populaire du Gabon, en courtes scènes d'une page. Au fil des gags, il continue de se poser de grandes questions sur sa place dans un monde où il n'est accepté ni par les Blancs ni par les Noirs. L'humour de Pahé croque la vie gabonaise au quotidien.",
    whyRead: [
      "Un personnage attachant, porte-parole de tous les enfants « différents ».",
      "Une série de gags qui montre la vie de quartier au Gabon.",
      "Un humour accessible aux enfants comme aux adultes.",
    ],
    year: 2012,
    publisher: "Paquet",
    pages: 48,
    isbn: "9782888904427",
    awards: [],
  }),

  // ------------------------------------------------------------ Joëlle Esso
  livre({
    slug: "hanibal-pushkin",
    title: "Hanibal@Pushkin",
    subtitle: "Mémoire en musique, cycle 1",
    contributors: [au("Joëlle Esso", ESSO)],
    genre: "jeunesse",
    audience: "ado",
    themes: ["histoire", "esclavage", "identite", "exil"],
    summary:
      "Enfant, Abraham Hanibal a été enlevé près du fleuve Logone, dans l'actuel Cameroun, puis adopté par le tsar Pierre le Grand ; son arrière-petit-fils, Alexandre Pouchkine, deviendra le père de la littérature russe moderne. Joëlle Esso, chanteuse et dessinatrice, leur rend hommage dans ce livre-disque illustré. On y trouve les paroles de ses chansons, chantées en lagwané, en russe, en français et en anglais, des photographies prises au sultanat de Logone-Birni et le récit de la naissance du projet.",
    whyRead: [
      "Une histoire vraie méconnue, du Cameroun jusqu'à la cour de Russie.",
      "Un livre accompagné d'un CD et d'un DVD.",
      "Pour découvrir l'ancêtre africain de Pouchkine.",
    ],
    year: 2011,
    publisher: "Dagan",
    pages: null,
    isbn: "9782919612024",
    awards: [],
  }),
  bd({
    slug: "eto-o-fils-naissance-d-un-champion",
    title: "Eto'o Fils",
    subtitle: "Naissance d'un champion",
    contributors: [au("Samuel Eto'o"), sc("Joëlle Esso", ESSO), de("Joëlle Esso", ESSO)],
    audience: "jeunesse",
    themes: ["enfance", "exil", "famille"],
    summary:
      "Dans le quartier de New Bell, à Douala, un petit garçon passe ses journées à jouer au football. Son talent attire l'attention d'un entraîneur, et à douze ans, Samuel Eto'o part en France pour tenter sa chance. Hébergé par un oncle et une tante, il découvre ce que signifie vivre sans papiers en règle, quand chaque projet devient impossible. Joëlle Esso met en images, à partir de son propre récit, l'enfance de l'un des plus grands footballeurs africains.",
    whyRead: [
      "L'enfance de Samuel Eto'o, racontée sans enjoliver.",
      "Un premier voyage en France qui tourne à l'épreuve.",
      "Le dessin chaleureux de l'autrice de Petit Joss.",
    ],
    year: 2013,
    publisher: "Dagan",
    pages: 49,
    isbn: "9782919612192",
    awards: [],
  }),
  bd({
    slug: "eto-o-fils-l-envol",
    title: "Eto'o Fils",
    subtitle: "L'Envol",
    contributors: [au("Samuel Eto'o"), sc("Joëlle Esso", ESSO), de("Joëlle Esso", ESSO)],
    audience: "jeunesse",
    themes: ["enfance", "famille", "travail"],
    summary:
      "De retour à Douala après trois mois passés clandestinement en France, Samuel reprend le chemin des terrains. Lors d'un match à Bépanda, un entraîneur le repère et lui propose de rencontrer le directeur d'un prestigieux centre de formation. Le garçon accepte d'entrer à la Kadji Sports Academy, à condition que son père, au chômage, obtienne un emploi. C'est le début d'une carrière prometteuse.",
    whyRead: [
      "La suite du parcours du jeune Samuel Eto'o.",
      "Une histoire de persévérance et de famille.",
      "Pour les jeunes fans de football comme pour leurs parents.",
    ],
    year: 2013,
    publisher: "Dagan",
    pages: 47,
    isbn: "9782919612239",
    awards: [],
  }),

  // ------------------------------------------------------------ Didier Kassaï
  bd({
    slug: "l-odyssee-de-mongou",
    title: "L'Odyssée de Mongou",
    contributors: [sc("Didier Kassaï", KASSAI), de("Didier Kassaï", KASSAI)],
    audience: "ado",
    themes: ["colonisation", "histoire", "tradition"],
    summary:
      "Au début du XXe siècle, Mongou est le chef d'un petit village de brousse au centre de l'Afrique. Il assiste aux premières loges à l'arrivée des Bawés, les Européens, dans son pays, sans savoir encore que son destin va devenir extraordinaire. Témoin puis acteur malgré lui du choc entre deux mondes, il voit la colonisation transformer la vie des siens. Didier Kassaï adapte en bande dessinée le roman du Centrafricain Pierre Sammy-Mackfoy.",
    whyRead: [
      "L'arrivée des colons racontée du point de vue d'un chef africain.",
      "L'adaptation d'un roman classique de Centrafrique.",
      "Les aquarelles de l'auteur de Tempête sur Bangui.",
    ],
    year: 2008,
    publisher: "L'Harmattan",
    pages: 59,
    isbn: "9782343219172",
    awards: [],
  }),
  bd({
    slug: "tempete-sur-bangui-tome-2",
    title: "Tempête sur Bangui",
    subtitle: "Tome 2",
    contributors: [sc("Didier Kassaï", KASSAI), de("Didier Kassaï", KASSAI)],
    audience: "adulte",
    themes: ["guerre", "politique", "ville"],
    summary:
      "Didier Kassaï poursuit le récit de la guerre civile qui a ravagé Bangui à partir de 2013. Dessinateur pris au cœur de la crise, il raconte au jour le jour les tueries, la violence arbitraire et la peur, mais aussi la débrouille et la solidarité de ses voisins. Il continue à dessiner ce qu'il voit, comme un acte de résistance. Un témoignage direct sur un conflit que le monde a vite oublié.",
    whyRead: [
      "La suite d'un témoignage rare, vécu de l'intérieur.",
      "La guerre en Centrafrique vue par un artiste qui l'a subie.",
      "Des aquarelles fines qui disent la violence sans complaisance.",
    ],
    year: 2018,
    publisher: "La Boîte à bulles",
    pages: 166,
    isbn: "9782849533185",
    awards: [],
  }),
  bd({
    slug: "maison-sans-fenetres",
    title: "Maison sans fenêtres",
    subtitle: "Enfances meurtries en Centrafrique",
    contributors: [sc("Marc Ellison"), de("Didier Kassaï", KASSAI)],
    audience: "adulte",
    themes: ["enfance", "guerre", "travail"],
    summary:
      "Le photojournaliste britannique Marc Ellison et Didier Kassaï sont allés à la rencontre des enfants de Centrafrique, premières victimes de guerres à répétition. Enfants des rues de Bangui, enfants des mines de diamants, jeunes filles livrées à la prostitution, déplacés des camps : ils recueillent leurs témoignages. Le reportage mêle dessins, photographies et vidéos accessibles par QR code. Le titre dit le silence des médias sur ce pays devenu une « maison sans fenêtres ».",
    whyRead: [
      "Un reportage dessiné qui donne la parole aux enfants.",
      "Dessins, photos et vidéos réunis dans un même livre.",
      "Une crise oubliée, racontée avec pudeur.",
    ],
    year: 2017,
    publisher: "La Boîte à bulles",
    pages: null,
    isbn: "9782849532973",
    awards: [],
  }),
  bd({
    slug: "rene-maran-un-homme-presque-pareil-aux-autres",
    title: "René Maran",
    subtitle: "Un homme, presque, pareil aux autres",
    contributors: [sc("Jean-Paul Delfino"), sc("Alain Zenou"), de("Didier Kassaï", KASSAI)],
    audience: "ado",
    themes: ["colonisation", "histoire", "identite"],
    summary:
      "Fils d'un administrateur colonial, René Maran se passionne très tôt pour l'écriture. Romancier, poète, conteur et grand voyageur, il devient en 1921 le premier écrivain noir à recevoir le prix Goncourt, pour Batouala, un roman qui dénonce les abus de la colonisation en Oubangui-Chari, l'actuelle Centrafrique. Le livre fait scandale en France. Cette biographie dessinée retrace son parcours et ses amitiés, de Félix Éboué à Aimé Césaire.",
    whyRead: [
      "Le portrait du premier lauréat noir du prix Goncourt.",
      "Une page méconnue de l'histoire coloniale en Centrafrique.",
      "Dessinée par un Centrafricain, sur le pays qui a inspiré Batouala.",
    ],
    year: 2023,
    publisher: "Orphie",
    pages: 49,
    isbn: "9791029805790",
    awards: [],
  }),

  // ------------------------------------------------------------ Barly Baruti
  bd({
    slug: "eva-k-les-hommes-du-train",
    title: "Eva K.",
    subtitle: "Les Hommes du train",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["politique", "ville"],
    summary:
      "Dans un pays africain soumis à une dictature brutale, une émeute gronde dans les rues de la capitale. Au même moment, un train blindé transporte la plus fabuleuse collection d'art sacré jamais réunie sur le continent. Des malfaiteurs préparent le casse du siècle, mais il leur faut l'aide d'un opposant enfermé pour trente ans dans un pénitencier redouté. Le premier tome d'une trilogie policière, qui marque les débuts de Barly Baruti dans la BD franco-belge.",
    whyRead: [
      "Un polar haletant sur fond de dictature africaine.",
      "Le début de la collaboration entre Barly Baruti et Frank Giroud.",
      "Un dessin réaliste qui rompt avec la ligne claire de ses débuts.",
    ],
    year: 1995,
    publisher: "Soleil",
    pages: 48,
    isbn: "9782877643719",
    awards: [],
  }),
  bd({
    slug: "mandrill-la-mome-flamberge",
    title: "Mandrill",
    subtitle: "La Môme Flamberge",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "ville", "guerre"],
    summary:
      "Paris, 1950. Dans les ruelles erre une jeune femme muette, agrippée à une longue épée allemande du XVIe siècle, dont la lame porte des traces de sang bien plus récentes. Elle n'a sur elle que la carte d'un jeune avocat, Adrien Mandrill, ancien résistant. En prenant l'affaire, celui-ci se retrouve face à d'anciens camarades et aux haines qui opposent encore collaborateurs et résistants, sur fond de trafic d'objets pillés pendant la guerre.",
    whyRead: [
      "Un polar à l'ancienne dans le Paris de l'après-guerre.",
      "Un héros avocat, ancien résistant, au fort caractère.",
      "Des décors d'époque reconstitués avec soin par Barly Baruti.",
    ],
    year: 1998,
    publisher: "Glénat",
    pages: 47,
    isbn: "9782723424905",
    awards: [],
  }),
  bd({
    slug: "mandrill-les-mariees-de-saint-lo",
    title: "Mandrill",
    subtitle: "Les Mariées de Saint-Lô",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "guerre", "femmes"],
    summary:
      "1951 : des enfants découvrent en Normandie le corps d'une jeune femme vêtue de sa robe de mariée. En lisant le journal, l'avocat Adrien Mandrill reconnaît la victime : Marielle, une amie qui lui a sauvé la vie au temps du maquis. Ému par ce fait divers, il ne peut plus s'en détacher quand un second corps est retrouvé dans les mêmes circonstances. L'enquête le ramène vers les souvenirs de la Résistance.",
    whyRead: [
      "Une enquête criminelle dans la Normandie de l'après-guerre.",
      "Un polar dans la lignée de Léo Malet et de Boileau-Narcejac.",
      "Mandrill confronté à son propre passé de résistant.",
    ],
    year: 1999,
    publisher: "Glénat",
    pages: 47,
    isbn: "9782723427173",
    awards: [],
  }),
  bd({
    slug: "mandrill-l-engrenage",
    title: "Mandrill",
    subtitle: "L'Engrenage",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "guerre", "politique"],
    summary:
      "Robert Fauque, dit Judex, ancien typographe, syndicaliste et résistant de la première heure, est accusé du meurtre d'un procureur. Son obsession de régler leur compte aux notables compromis dans la collaboration ne plaide pas en sa faveur. Défendu par Mandrill, qu'il a connu au maquis de Normandie, il est lourdement condamné. Pour sauver son ancien compagnon, l'avocat se met à fouiller le passé trouble de la victime.",
    whyRead: [
      "Les comptes non réglés de l'Occupation, au cœur d'un procès.",
      "Un avocat prêt à tout pour un ancien frère d'armes.",
      "Une intrigue serrée, servie par un dessin réaliste.",
    ],
    year: 2000,
    publisher: "Glénat",
    pages: 48,
    isbn: "9782723430692",
    awards: [],
  }),
  bd({
    slug: "mandrill-chute-libre",
    title: "Mandrill",
    subtitle: "Chute libre",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "ville"],
    summary:
      "Cette fois, c'est l'avocat Adrien Mandrill qui se retrouve en garde à vue au Quai des Orfèvres, soupçonné d'avoir tué sa maîtresse. Le commissaire chargé de l'enquête a assez d'éléments pour demander son inculpation. Sa secrétaire Angèle refuse de croire à sa culpabilité, mais les ennuis s'accumulent : un corbeau lui envoie des lettres anonymes, et l'homme qui pouvait l'innocenter est assassiné.",
    whyRead: [
      "Le héros passe du côté des accusés : un vrai tournant de la série.",
      "Un suspense bien construit autour d'un corbeau.",
      "Le Paris des années 1950 en toile de fond.",
    ],
    year: 2001,
    publisher: "Glénat",
    pages: 48,
    isbn: "9782723433044",
    awards: [],
  }),
  bd({
    slug: "mandrill-les-orchidees-de-volnaiev",
    title: "Mandrill",
    subtitle: "Les Orchidées de Volnaïev",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "politique"],
    summary:
      "Paris, juin 1952. Condamné à tort pour le meurtre de sa maîtresse, Mandrill croupit à la prison de la Santé. Au cours d'un transfert vers le Palais de justice, il parvient à s'évader. Au même moment, loin de là, dans le Caucase, des espions américains déguisés en soldats russes tentent d'enlever des savants travaillant sur le nucléaire. Deux affaires que tout semble séparer, et qui pourraient pourtant se rejoindre.",
    whyRead: [
      "Le polar bascule dans le roman d'espionnage de la guerre froide.",
      "Une évasion spectaculaire et une intrigue à double fond.",
      "Le premier tome d'un nouveau cycle de la série.",
    ],
    year: 2002,
    publisher: "Glénat",
    pages: 47,
    isbn: "9782723436052",
    awards: [],
  }),
  bd({
    slug: "mandrill-le-cheval-de-troie",
    title: "Mandrill",
    subtitle: "Le Cheval de Troie",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "politique"],
    summary:
      "Enrôlé par les services secrets français, Mandrill a pris la place de son frère dans un laboratoire nucléaire en Union soviétique. Sa mission : récupérer les résultats des recherches russes sur la bombe H. Il lui faut aussi trouver le moyen de rentrer en France sans que personne ne découvre la supercherie. Un épisode d'espionnage en pleine guerre froide.",
    whyRead: [
      "Un avocat parisien plongé au cœur de l'URSS.",
      "La course à la bombe H en arrière-plan.",
      "Un suspense d'espionnage à l'ancienne.",
    ],
    year: 2004,
    publisher: "Glénat",
    pages: 47,
    isbn: "9782723439961",
    awards: [],
  }),
  bd({
    slug: "mandrill-la-nasse",
    title: "Mandrill",
    subtitle: "La Nasse",
    contributors: [GIROUD, BARUTI],
    audience: "adulte",
    themes: ["histoire", "politique"],
    summary:
      "Février 1953. Passé pour mort aux yeux de tous, Adrien Mandrill a rejoint le centre de recherches nucléaires de Volnaïev, où il remplace son frère, ingénieur au service des Soviétiques. Il doit y récupérer un microfilm destiné à l'OTAN. Mais son informateur reste introuvable, et l'étau se resserre autour de lui jusqu'à Leningrad. Le septième et dernier tome de la série.",
    whyRead: [
      "Le dernier tome de la série, dans l'hiver soviétique.",
      "Un héros pris au piège, loin de son Paris natal.",
      "Le dessin de Baruti, à l'aise de Paris à Leningrad.",
    ],
    year: 2007,
    publisher: "Glénat",
    pages: 48,
    isbn: "9782723448208",
    awards: [],
  }),
  bd({
    slug: "chaos-debout-a-kinshasa",
    title: "Chaos debout à Kinshasa",
    contributors: [sc("Thierry Bellefroid"), BARUTI],
    audience: "adulte",
    themes: ["politique", "histoire", "ville"],
    summary:
      "1974. Ernest, petit voyou de Harlem, enchaîne les combines pour rembourser une dette à de dangereux truands. Il gagne à un concours radio un voyage pour assister au « combat du siècle » entre Mohamed Ali et George Foreman, à Kinshasa. L'occasion de se mettre au vert et de renouer avec ses racines africaines. Mais le Zaïre de Mobutu, en pleine guerre froide, est un nid d'espions et de politiciens véreux qui n'ont rien à envier aux gangsters de Harlem.",
    whyRead: [
      "Les coulisses du célèbre combat Ali-Foreman de 1974.",
      "Le Zaïre de Mobutu, entre propagande et guerre froide.",
      "Un roman graphique rythmé, dessiné par un Kinois.",
    ],
    year: 2016,
    publisher: "Glénat",
    pages: 105,
    isbn: "9782344010297",
    awards: [],
  }),
  bd({
    slug: "le-singe-jaune",
    title: "Le Singe jaune",
    contributors: [sc("Barly Baruti", "barly-baruti"), sc("Christophe Cassiau-Haurie"), BARUTI],
    audience: "adulte",
    themes: ["colonisation", "histoire", "identite"],
    summary:
      "Bruxelles, fin des années 1990 : on aurait découvert en Afrique centrale une nouvelle espèce de primate, le « singe jaune à gorge rouge ». Paulette Blackman, célèbre journaliste d'investigation belge, part tirer l'affaire au clair dans une région encore tenue par des milices rebelles. Elle découvre que cette trouvaille improbable cache un trésor lié à l'histoire douloureuse de la colonisation du Congo. Une aventure par les auteurs de Madame Livingstone, qui aborde le sort des enfants métis.",
    whyRead: [
      "Une aventure enlevée au cœur de la forêt congolaise.",
      "Le passé colonial belge et le tabou des enfants métis.",
      "Par le duo de Madame Livingstone, déjà sur le site.",
    ],
    year: 2018,
    publisher: "Glénat",
    pages: 101,
    isbn: "9782344024508",
    awards: [],
  }),

  // ------------------------------------------------------------ Christophe Ngalle Edimo et Simon-Pierre Mbumbo
  bd({
    slug: "thembi-et-jetje-tisseuses-de-l-arc-en-ciel",
    title: "Thembi et Jetje, tisseuses de l'arc-en-ciel",
    contributors: [
      EDIMO,
      de("Simon-Pierre Mbumbo", MBUMBO),
      de("Batoule Alimam"),
      de("Bozena Augustyn"),
      de("Samuel Daina"),
      de("Adjim Danngar"),
      de("Armella Leung"),
      de("Brahim Rais"),
      de("Brice Reignier"),
      de("Didier Viodé"),
    ],
    audience: "ado",
    themes: ["histoire", "politique", "famille"],
    summary:
      "Afrique du Sud, 1990 : Nelson Mandela sort de prison et l'apartheid vit ses derniers jours. Dans la province du Gauteng, deux familles voisines, l'une ndébélé autour de la grand-mère Thembi, l'autre afrikaner autour de la petite Jetje, doivent apprendre à vivre ensemble après des décennies de séparation. En dix chapitres confiés à neuf dessinateurs, l'album suit vingt ans de cette « nation arc-en-ciel » voulue par Mandela et Desmond Tutu, avec ses peurs, ses rancœurs et ses espoirs.",
    whyRead: [
      "Vingt ans d'histoire sud-africaine à hauteur de voisins.",
      "Neuf dessinateurs, surtout africains, pour une même histoire.",
      "Une belle porte d'entrée sur l'après-apartheid.",
    ],
    year: 2011,
    publisher: "L'Harmattan",
    pages: 128,
    isbn: "9782296546905",
    awards: [],
  }),
  bd({
    slug: "la-chiva-colombiana",
    title: "La Chiva colombiana",
    contributors: [EDIMO, de("Fati Kabuika")],
    audience: "adulte",
    themes: ["politique", "esclavage", "ville"],
    summary:
      "Colombie, 2010. Près de Buenaventura, port de la côte Pacifique peuplé en majorité de descendants d'esclaves, Ortiz et sa bande vivent de rapines et de petits trafics, pris entre l'armée, les paramilitaires et les cartels de la drogue. Quand les narcotrafiquants enrôlent Lucia, la fille de la bande, les autres la suivent, et Ortiz se retrouve rejeté. Réfugié chez d'autres, il rencontre de nouveaux alliés et tombe amoureux. Un récit plein d'humour et de violence, par un scénariste camerounais et un dessinateur congolais.",
    whyRead: [
      "Une BD africaine qui part en Colombie : un vrai ovni.",
      "Les Afro-Colombiens du Pacifique, rarement racontés.",
      "Le dessin déjanté et coloré de Fati Kabuika.",
    ],
    year: 2012,
    publisher: "Les Enfants Rouges",
    pages: 108,
    isbn: "9782354190507",
    awards: [],
  }),
  bd({
    slug: "survy-banlieue-blues",
    title: "Survy",
    subtitle: "Banlieue blues",
    contributors: [EDIMO, de("Nadège Guilloud-Bazin")],
    audience: "ado",
    themes: ["ville", "identite", "travail"],
    summary:
      "Survy est une cité de banlieue comme il y en a trop. Des familles s'y croisent sans se connaître, chacune avec ses difficultés, et toutes subissent l'emprise d'Omar, le caïd du quartier. Marianne, Leïla ou Boubacar se demandent s'il faut laisser faire, partir ou résister. Abdelaziz, travailleur social respecté, mise sur l'entraide et le dialogue, ce qui ne plaît pas du tout à Omar.",
    whyRead: [
      "Une chronique de banlieue loin des clichés.",
      "La solidarité comme réponse à la loi du plus fort.",
      "Des personnages de toutes origines, tous attachants.",
    ],
    year: 2015,
    publisher: "Les Enfants Rouges",
    pages: 112,
    isbn: "9782354190798",
    awards: [],
  }),
  bd({
    slug: "la-vie-d-andolo-le-messager",
    title: "La Vie d'Andolo",
    subtitle: "Le Messager",
    contributors: [EDIMO, de("Fati Kabuika")],
    audience: "ado",
    themes: ["ville", "amour", "famille"],
    summary:
      "Andolo vient de réussir son baccalauréat et tout le quartier l'apprécie, comme sa petite amie Ioanna, Congolaise d'origine roumaine. Mais les parents de la jeune fille veulent l'envoyer étudier en Roumanie et la marier au fils d'un ministre. Ajoutez un trafiquant de chiens et un commandant de police persuadé qu'Andolo est mêlé à tous les trafics : le couple est séparé. Heureusement, Kili Kili, le petit chien d'Andolo, sait faire passer les messages.",
    whyRead: [
      "Une histoire d'amour contrarié dans un quartier africain plein de vie.",
      "Un petit chien messager irrésistible.",
      "Beaucoup d'humour et des personnages très expressifs.",
    ],
    year: 2017,
    publisher: "Toom éditions",
    pages: 53,
    isbn: "9791095035022",
    awards: [],
  }),
  bd({
    slug: "djo-o-bar-tome-1",
    title: "Djo'o bar",
    subtitle: "Tome 1",
    contributors: [EDIMO, de("Hugues Bertrand Biboum")],
    audience: "adulte",
    themes: ["ville", "humour"],
    summary:
      "Le Djo'o bar est un bar bruyant d'un quartier mal famé de Yaoundé. Autour de Djo'o, le patron, défilent des clients à problèmes : Hilary, propriétaire flegmatique d'un singe qui parle, sa compagne Fifi, tombée malade, un médecin qui cherche en vain la cause de son mal, une spécialiste venue du Muséum d'histoire naturelle de Paris ou encore un prophète de catastrophes. Maman Nicole et son solide balai ont bien du mérite à y remettre de l'ordre chaque jour.",
    whyRead: [
      "Une comédie de comptoir au cœur de Yaoundé.",
      "Des personnages loufoques et un singe qui parle.",
      "Un humour camerounais savoureux.",
    ],
    year: 2019,
    publisher: "Toom éditions",
    pages: 55,
    isbn: "9791095035039",
    awards: [],
  }),
  bd({
    slug: "pour-une-couleur-de-peau",
    title: "Pour une couleur de peau",
    contributors: [EDIMO, de("Martini Ngola"), de("Joseph Danny Nyembi"), de("Nathanael Ejob")],
    audience: "ado",
    themes: ["femmes", "famille", "identite", "tradition"],
    summary:
      "Au Cameroun, Agnès est née albinos. Sa mère, Chantal, est bien décidée à la protéger des superstitions et des menaces qui pèsent sur les personnes comme elle. L'album suit les moments décisifs de la vie de ces deux femmes, entre rejet et désir d'une vie normale. Ses trois parties sont dessinées par trois dessinateurs aux styles très différents.",
    whyRead: [
      "Un sujet grave, l'albinisme en Afrique, traité avec humanité.",
      "Le combat d'une mère pour sa fille.",
      "Trois dessinateurs camerounais, trois regards.",
    ],
    year: 2019,
    publisher: "L'Harmattan",
    pages: 70,
    isbn: "9782343168760",
    awards: [],
  }),
  bd({
    slug: "colonel-toutou-a-l-ombre-de-paris",
    title: "Colonel Toutou",
    subtitle: "À l'ombre de Paris",
    contributors: [EDIMO, de("Simon-Pierre Mbumbo", MBUMBO)],
    audience: "adulte",
    themes: ["politique", "humour", "colonisation"],
    summary:
      "Le colonel Papa Toutou est un « dictateur éclairé » qui règne sur un pays africain imaginaire, toujours attentif à ce que l'on pense de lui à Paris. Ce premier tome enchaîne des chapitres de quelques pages qui racontent sur le mode comique une réalité qui ne l'est pas : celle de la Françafrique. Les deux auteurs de Malamine se retrouvent pour cette satire politique.",
    whyRead: [
      "Une satire mordante des liens entre la France et ses anciennes colonies.",
      "Le retour du duo de Malamine, un Africain à Paris.",
      "Des chapitres courts, faciles à picorer.",
    ],
    year: 2020,
    publisher: "Toom éditions",
    pages: 80,
    isbn: "9791095035053",
    awards: [],
  }),
  bd({
    slug: "l-escale-des-mille-pintades",
    title: "L'Escale des mille pintades",
    contributors: [EDIMO, de("Fati Kabuika"), de("Martini Ngola"), de("Lisa Haberer")],
    audience: "adulte",
    themes: ["tradition", "travail", "identite"],
    summary:
      "Depuis une trentaine d'années, une bande d'amis français et la famille de Bomavé Konaté, artisan de Boromo au Burkina Faso, ont noué une amitié profonde. Le fil rouge de l'album : de petites pintades sculptées dans le bois de fromager par Bomavé, que ses amis diffusent en France. À travers cet oiseau chargé de symboles, de l'Antiquité à l'esclavage et à la colonisation, la bande dessinée raconte une rencontre entre deux mondes et leurs projets communs.",
    whyRead: [
      "L'histoire vraie d'une amitié franco-burkinabè.",
      "La pintade, un oiseau chargé d'histoire et de symboles.",
      "Plusieurs dessinateurs pour un album plein de chaleur.",
    ],
    year: 2021,
    publisher: "Toom éditions",
    pages: 116,
    isbn: "9791095035060",
    awards: [],
  }),
  bd({
    slug: "vaudou-soccer-temps-additionnel",
    title: "Vaudou soccer",
    subtitle: "Temps additionnel",
    contributors: [sc("Simon-Pierre Mbumbo", MBUMBO), de("Simon-Pierre Mbumbo", MBUMBO)],
    audience: "ado",
    themes: ["spiritualite", "tradition", "politique"],
    summary:
      "En fin de carrière dans les championnats européens, le footballeur Ndamba rentre au pays, le Bantou, un État imaginaire d'Afrique centrale. Homme d'affaires rigoureux, il investit dans le Grimba FC, club mythique et champion depuis dix ans. Mais avant chaque match décisif, le club organise des cérémonies vaudou sous l'impulsion de Tobassi, un grand sorcier influent chez les supporters. Ndamba veut en finir avec ces pratiques, et Tobassi n'a aucune intention de se laisser faire.",
    whyRead: [
      "Le football africain entre business et croyances.",
      "Un affrontement savoureux entre un manager et un sorcier.",
      "Une série écrite et dessinée par Simon-Pierre Mbumbo.",
    ],
    year: 2017,
    publisher: "Toom éditions",
    pages: 71,
    isbn: "9791095035015",
    awards: [],
  }),
  bd({
    slug: "akkey-le-jugement-des-animaux",
    title: "Akkey",
    subtitle: "Le Jugement des animaux",
    contributors: [sc("Mend Bizmar"), de("Simon-Pierre Mbumbo", MBUMBO)],
    audience: "ado",
    themes: ["tradition", "contes", "travail"],
    summary:
      "Kriss dirige un cabinet de conseil en Bourse à Londres. En vacances en famille dans la réserve du Kalahari, il projette d'y investir pour transformer des espaces sauvages en zone touristique. Le patriarche d'une communauté autochtone, qui voit dans ce projet une menace pour son peuple et pour la faune, l'invite à discuter. Mais une boisson plonge Kriss dans un sommeil cauchemardesque, où il se retrouve accusé devant un tribunal d'animaux.",
    whyRead: [
      "Une fable écologique où les animaux jugent les hommes.",
      "Le Kalahari et ses peuples face aux promoteurs.",
      "Un récit entre conte et satire du monde de la finance.",
    ],
    year: 2019,
    publisher: "Toom éditions",
    pages: 58,
    isbn: "9791095035046",
    awards: [],
  }),

  // ------------------------------------------------------------ Pat Masioni
  bd({
    slug: "rwanda-1994-le-camp-de-la-vie",
    title: "Rwanda 1994",
    subtitle: "Le Camp de la vie",
    contributors: [sc("Cécile Grenier"), sc("Alain Austini"), MASIONI],
    audience: "adulte",
    themes: ["genocide", "guerre", "histoire"],
    summary:
      "D'avril à juillet 1994, le génocide des Tutsi fait des centaines de milliers de morts au Rwanda, sous les yeux du monde entier. Ce second tome couvre les mois de juin et de juillet, alors que les survivants tentent de rester en vie. Les auteurs ont passé sept mois au Rwanda à recueillir des témoignages pour bâtir cette fiction fondée sur des faits réels. Un récit éprouvant et nécessaire.",
    whyRead: [
      "La suite de Descente en enfer, déjà présenté sur le site.",
      "Une fiction nourrie de nombreux témoignages de rescapés.",
      "Le dessin puissant de Pat Masioni au service de la mémoire.",
    ],
    year: 2008,
    publisher: "Vent des savanes",
    pages: null,
    isbn: "9782226177230",
    awards: [],
  }),
  bd({
    slug: "bakanja-une-vie-sans-compromis",
    title: "Bakanja",
    subtitle: "Une vie sans compromis",
    contributors: [sc("Aldo Falconi"), MASIONI],
    audience: "ado",
    themes: ["spiritualite", "colonisation", "histoire"],
    summary:
      "Isidore Bakanja naît vers 1885 dans la région de l'Équateur, au Congo. Baptisé par des missionnaires, il devient catéchiste tout en travaillant comme domestique pour une société belge qui exploite le caoutchouc. Dans cette entreprise coloniale, certains responsables voient d'un très mauvais œil sa foi et son influence sur les ouvriers. Cette bande dessinée retrace la vie de ce jeune Congolais, reconnu comme martyr par l'Église catholique.",
    whyRead: [
      "La vie d'un jeune Congolais devenu figure de l'Église.",
      "Un regard sur la brutalité de l'économie du caoutchouc.",
      "Dessinée par Pat Masioni, éditée à Kinshasa.",
    ],
    year: 2008,
    publisher: "Médiaspaul",
    pages: 48,
    isbn: "9782741400288",
    awards: [],
  }),
  bd({
    slug: "agathe-agent-si-a-la-decouverte-de-la-solidarite-internationale",
    title: "Agathe, agent S.I.",
    subtitle: "À la découverte de la solidarité internationale",
    contributors: [sc("Christophe Vadon"), MASIONI],
    audience: "ado",
    themes: ["travail", "politique"],
    summary:
      "Agathe veut comprendre ce qu'est vraiment la solidarité internationale. Cet album réunit cinq histoires sur le don, la coopération et l'entraide : les suites d'un tsunami, des projets menés par des jeunes et des volontaires en Afrique, l'accompagnement d'une initiative locale au Brésil, un partenariat entre pêcheurs du Sud et du Nord. Une bande dessinée pédagogique conçue avec une association spécialisée.",
    whyRead: [
      "Pour comprendre ce que recouvre la solidarité internationale.",
      "Cinq histoires courtes, sur plusieurs continents.",
      "Le dessin clair et vivant de Pat Masioni.",
    ],
    year: 2009,
    publisher: "GRAD",
    pages: 34,
    isbn: "9782910222321",
    awards: [],
  }),
  bd({
    slug: "njinga-mbandi-reine-du-ndongo-et-du-matamba",
    title: "Njinga Mbandi, reine du Ndongo et du Matamba",
    contributors: [sc("Sylvia Serbin"), sc("Édouard Joubeaud"), MASIONI],
    audience: "ado",
    themes: ["histoire", "femmes", "colonisation", "esclavage"],
    summary:
      "Au XVIIe siècle, sur les terres de l'actuel Angola, Njinga Mbandi devient reine du Ndongo puis du Matamba. Diplomate habile et cheffe de guerre redoutée, elle tient tête pendant des décennies aux Portugais, qui cherchent à étendre leur colonie et la traite des esclaves. Cette bande dessinée fait partie d'une série de l'Unesco consacrée aux grandes figures féminines de l'histoire africaine.",
    whyRead: [
      "Le portrait d'une reine africaine qui a défié le Portugal.",
      "Une série de l'Unesco sur les femmes dans l'histoire de l'Afrique.",
      "Une porte d'entrée claire sur l'histoire de l'Angola.",
    ],
    year: 2014,
    publisher: "Unesco",
    pages: null,
    isbn: null,
    awards: [],
  }),
  bd({
    slug: "thomas-sankara-rebelle-visionnaire",
    title: "Thomas Sankara, rebelle visionnaire",
    contributors: [sc("Pierre Lepidi"), sc("Françoise-Marie Santucci"), MASIONI],
    audience: "ado",
    themes: ["politique", "histoire", "independances"],
    summary:
      "À Paris, Léa, une fillette de neuf ans née d'un couple mixte, demande à sa mère pourquoi on l'a prénommée Léa-Thomas, avec un prénom de garçon. La réponse la mène au Burkina Faso, sur les traces de Thomas Sankara, jeune capitaine devenu président en 1983, surnommé le « Che africain ». Cette biographie dessinée raconte le parcours de cette icône panafricaine de la lutte contre l'impérialisme, à travers les yeux d'une enfant d'aujourd'hui.",
    whyRead: [
      "La vie de Thomas Sankara, racontée simplement.",
      "Une enquête familiale qui relie Paris et Ouagadougou.",
      "Coécrite par un journaliste du Monde spécialiste de l'Afrique.",
    ],
    year: 2023,
    publisher: "Marabout",
    pages: 141,
    isbn: "9782501146593",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = livres.map((b) => b.slug);
