/**
 * Lot 03 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Afrique de l'Ouest : Camara Laye, Monénembo, Niane, Kourouma, Tadjo, Dadié, Gauz, Beyrouk, Nazi Boni,
 * Bhêly-Quenum, Sami Tchak, Kossi Efoui. ISBN et pages relevés au catalogue de la BnF (édition indiquée).
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });

const laye = auteur("Camara Laye", "camara-laye");
const monenembo = auteur("Tierno Monénembo", "tierno-monenembo");
const niane = auteur("Djibril Tamsir Niane", "djibril-tamsir-niane");
const kourouma = auteur("Ahmadou Kourouma", "ahmadou-kourouma");
const tadjo = auteur("Véronique Tadjo", "veronique-tadjo");
const dadie = auteur("Bernard Dadié", "bernard-dadie");
const gauz = auteur("Gauz", "gauz");
const beyrouk = auteur("Mbarek Ould Beyrouk", "mbarek-ould-beyrouk");
const boni = auteur("Nazi Boni", "nazi-boni");
const quenum = auteur("Olympe Bhêly-Quenum", "olympe-bhely-quenum");
const tchak = auteur("Sami Tchak", "sami-tchak");
const efoui = auteur("Kossi Efoui", "kossi-efoui");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Camara Laye
  livre({
    slug: "le-regard-du-roi",
    title: "Le Regard du roi",
    contributors: [laye],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "identite", "colonisation"],
    summary:
      "Clarence, un Blanc ruiné par le jeu et chassé de son hôtel, n'a plus qu'une idée en tête : être reçu par le roi d'un pays africain que l'on ne nomme jamais, pour lui demander un emploi. Guidé par un mendiant rusé et deux garçons espiègles, il s'enfonce vers le sud, dans une forêt où il perd peu à peu ses repères et ses certitudes d'Européen. Ce voyage déroutant, à la fois drôle et mystique, renverse les rôles habituels du roman colonial : c'est ici le Blanc qui doit tout apprendre.",
    whyRead: [
      "Un roman étrange et envoûtant, souvent comparé à Kafka.",
      "Le récit colonial inversé : c'est l'Européen qui est perdu et qui apprend.",
      "Le chef-d'œuvre méconnu de l'auteur de L'Enfant noir.",
    ],
    year: 1954,
    publisher: "Pocket",
    pages: 252,
    isbn: "2266046705",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "dramouss",
    title: "Dramouss",
    contributors: [laye],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "exil", "identite"],
    summary:
      "Après six années passées à Paris, Fatoman revient en Guinée. Il retrouve sa famille, sa ville, les souvenirs de l'enfance, mais aussi un pays devenu indépendant où la peur, les mots d'ordre et la violence politique ont pris le dessus. Une vision onirique, celle de Dramouss, lui révèle le visage inquiétant du régime. Suite de L'Enfant noir, ce roman courageux paraît alors que Camara Laye vient de s'exiler au Sénégal.",
    whyRead: [
      "La suite de L'Enfant noir, à l'âge adulte.",
      "L'une des premières critiques littéraires d'un régime africain indépendant.",
      "Écrit par un auteur contraint à l'exil.",
    ],
    year: 1966,
    publisher: "Pocket",
    pages: 245,
    isbn: "2266040243",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-maitre-de-la-parole",
    title: "Le Maître de la parole",
    subtitle: "Kouma Lafôlô Kouma",
    contributors: [laye],
    genre: "recit",
    audience: "adulte",
    themes: ["histoire", "contes", "tradition"],
    summary:
      "Camara Laye a recueilli auprès du griot Babou Condé, à Fadama en Haute-Guinée, le long récit de la vie de Soundjata Keïta, fondateur de l'empire du Mali au XIIIe siècle. On suit l'enfant infirme et moqué, l'exil de la famille, puis le retour du héros face au roi sorcier Soumaoro. L'écrivain a traduit et mis en forme cette parole en gardant le souffle de la récitation, ses généalogies et ses chants. Une autre version, plus ample, de l'épopée mandingue.",
    whyRead: [
      "L'épopée de Soundjata telle qu'un grand griot la racontait.",
      "Le dernier livre de Camara Laye, fidèle à la tradition orale.",
      "À lire en regard de la version de Djibril Tamsir Niane.",
    ],
    year: 1978,
    publisher: "Pocket",
    pages: 285,
    isbn: "2266008986",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Tierno Monénembo
  livre({
    slug: "les-crapauds-brousse",
    title: "Les Crapauds-brousse",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "ville"],
    summary:
      "Diouldé, jeune fonctionnaire revenu d'études à l'étranger, mène une vie tranquille dans la capitale d'un pays africain qui ressemble beaucoup à la Guinée de Sékou Touré. Il préfère ne pas voir la peur qui gagne autour de lui. Mais la machine du régime, faite de délations, d'arrestations et de complots inventés, finit par l'attraper à son tour. Le premier roman de Monénembo décrit de l'intérieur l'engrenage d'une dictature.",
    whyRead: [
      "Le premier roman de Tierno Monénembo, écrit en exil.",
      "Une plongée glaçante dans la Guinée de la terreur.",
      "Un héros ordinaire, ni bourreau ni résistant, comme beaucoup.",
    ],
    year: 1979,
    publisher: "Points",
    pages: 185,
    isbn: "9782757816691",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-ecailles-du-ciel",
    title: "Les Écailles du ciel",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "colonisation", "politique"],
    summary:
      "Autour de Kolisoko, ville imaginaire d'Afrique de l'Ouest, Monénembo raconte un siècle d'histoire : le temps d'avant les Blancs, la conquête coloniale, puis l'indépendance et la dictature. On suit un personnage pris dans les remous de cette histoire, ballotté d'un régime à l'autre. Le roman mêle le ton du conte, le mythe et la satire. Derrière la ville inventée, on reconnaît sans peine la Guinée.",
    whyRead: [
      "Un siècle d'histoire africaine raconté comme une fable.",
      "Grand prix littéraire d'Afrique noire 1986.",
      "Une langue foisonnante, entre mythe et satire.",
    ],
    year: 1986,
    publisher: "Points",
    pages: 192,
    isbn: "2020314487",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1986 }],
  }),
  livre({
    slug: "un-reve-utile",
    title: "Un rêve utile",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "travail"],
    summary:
      "À Lyon, sur les pentes de la Croix-Rousse, un jeune exilé africain raconte sa vie et celle des autres habitants d'un foyer délabré. Petits boulots mal payés, débrouille, nostalgie du pays et souvenirs du voyage difficile jusqu'en France : chaque voix apporte son histoire. Monénembo mélange l'argot lyonnais et les mots d'Afrique dans une langue vive et drôle. Un roman choral sur la condition des immigrés.",
    whyRead: [
      "La vie des immigrés africains à Lyon, racontée de l'intérieur.",
      "Une langue inventive qui mêle argot lyonnais et parlers africains.",
      "Un récit à plusieurs voix, plein d'humour et de mélancolie.",
    ],
    year: 1991,
    publisher: "Seuil",
    pages: 251,
    isbn: "202012307X",
    format: null,
    awards: [],
  }),
  livre({
    slug: "un-attieke-pour-elgass",
    title: "Un attiéké pour Elgass",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "politique", "ville"],
    summary:
      "À Abidjan, une bande d'étudiants guinéens a fui la terreur du régime de Sékou Touré. Ils partagent un quotidien difficile, entre espoirs politiques, débrouille et souvenirs du pays. Une jeune fille arrive parmi eux, à la recherche de la vérité sur la mort d'Elgass, leur ami et compagnon d'exil. Le narrateur mène l'enquête à sa façon, dans un roman qui emprunte au polar pour parler des désillusions des indépendances.",
    whyRead: [
      "Un roman d'exil construit comme une enquête.",
      "La vie des étudiants guinéens réfugiés à Abidjan.",
      "Un clin d'œil malicieux aux romans policiers d'Agatha Christie.",
    ],
    year: 1993,
    publisher: "Seuil",
    pages: 170,
    isbn: "2020196042",
    format: null,
    awards: [],
  }),
  livre({
    slug: "pelourinho",
    title: "Pelourinho",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "identite", "exil"],
    summary:
      "Un écrivain africain arrive à Salvador de Bahia, au Brésil, sur la piste de lointains parents, descendants d'esclaves venus d'Afrique. Dans le vieux quartier du Pelourinho, deux habitants racontent tour à tour sa présence : un petit débrouillard bavard et une femme du quartier. Entre candomblé, capoeira et misère des rues, le roman explore ce qui relie encore l'Afrique et le Brésil noir. Une quête des origines, vue par ceux qui sont restés de l'autre côté de l'océan.",
    whyRead: [
      "Un voyage à Bahia, sur les traces de la traite atlantique.",
      "Deux narrateurs inoubliables, gouailleurs et touchants.",
      "Monénembo, grand écrivain des liens entre Afrique et Amériques.",
    ],
    year: 1995,
    publisher: "Seuil",
    pages: 221,
    isbn: "2020233495",
    format: null,
    awards: [],
  }),
  livre({
    slug: "cinema",
    title: "Cinéma",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "independances", "famille"],
    summary:
      "Dans une petite ville de Guinée, à la fin des années 1950, le jeune Binguel ne vit que pour les westerns projetés au cinéma du quartier. Avec son ami Benté, plus âgé et un peu voyou, il rêve de colts, de shérifs et d'aventures. Entre l'autorité d'un père sévère, l'école et la rue, l'adolescent cherche sa place pendant que le pays s'approche de l'indépendance. Un roman d'apprentissage vif et drôle.",
    whyRead: [
      "L'enfance guinéenne au temps des westerns et de l'indépendance.",
      "Un ton plus léger et joyeux que les autres romans de l'auteur.",
      "Un bel hommage au pouvoir du cinéma sur l'imaginaire.",
    ],
    year: 1997,
    publisher: "Seuil",
    pages: 216,
    isbn: "2020301989",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-aine-des-orphelins",
    title: "L'Aîné des orphelins",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["genocide", "enfance", "guerre"],
    summary:
      "Faustin a quinze ans. Il raconte depuis une prison de Kigali comment il en est arrivé là. Après le génocide des Tutsi de 1994, il a perdu sa famille et survécu comme il pouvait, en veillant sur d'autres enfants livrés à eux-mêmes. Sa voix d'adolescent, gouailleuse et pudique à la fois, dit l'horreur sans jamais s'y arrêter. Monénembo a écrit ce roman après un séjour au Rwanda, dans le cadre de l'opération « Écrire par devoir de mémoire ».",
    whyRead: [
      "Le génocide des Tutsi vu à hauteur d'adolescent.",
      "Né du projet « Rwanda : écrire par devoir de mémoire ».",
      "Prix Tropiques 2000.",
    ],
    year: 2000,
    publisher: "Points",
    pages: 156,
    isbn: "2020798344",
    format: "poche",
    awards: [{ name: "Prix Tropiques", year: 2000 }],
  }),
  livre({
    slug: "peuls",
    title: "Peuls",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "tradition", "identite"],
    summary:
      "Monénembo raconte l'histoire de son peuple, les Peuls, sur près de mille ans : des bergers nomades venus de l'est jusqu'aux royaumes du Fouta-Djalon, puis l'arrivée des colonisateurs français à la fin du XIXe siècle. Des générations de pasteurs, de guerriers, de lettrés et de rois se succèdent. Le roman suit les transhumances, les guerres et les alliances, avec le souffle d'une épopée. Une grande fresque historique, mêlant chronique et légende.",
    whyRead: [
      "Une fresque de dix siècles d'histoire peule.",
      "Un roman-épopée, riche en batailles et en figures légendaires.",
      "Pour découvrir le Fouta-Djalon, berceau de l'auteur.",
    ],
    year: 2004,
    publisher: "Points",
    pages: 489,
    isbn: "9782757814642",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-terroriste-noir",
    title: "Le Terroriste noir",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "histoire", "colonisation"],
    summary:
      "En 1940, Addi Bâ, tirailleur guinéen, échappe aux Allemands après la débâcle et trouve refuge dans un village des Vosges. Adopté par les habitants, il devient l'un des premiers organisateurs de la Résistance dans la région, au point que l'occupant le surnomme « le terroriste noir ». Des années plus tard, une vieille villageoise raconte son histoire. Monénembo fait revivre ce héros oublié, réel, de la Résistance française.",
    whyRead: [
      "L'histoire vraie d'un résistant guinéen dans les Vosges.",
      "Grand prix du roman métis 2012 et prix Ahmadou-Kourouma 2013.",
      "Adapté au cinéma sous le titre Nos patriotes (2017).",
    ],
    year: 2012,
    publisher: "Points",
    pages: 214,
    isbn: "9782757836002",
    format: "poche",
    awards: [
      { name: "Grand prix du roman métis", year: 2012 },
      { name: "Prix Erckmann-Chatrian", year: 2012 },
      { name: "Prix Ahmadou-Kourouma", year: 2013 },
    ],
    adaptations: [{ kind: "film", title: "Nos patriotes", year: 2017, by: "Gabriel Le Bomin" }],
  }),
  livre({
    slug: "les-coqs-cubains-chantent-a-minuit",
    title: "Les coqs cubains chantent à minuit",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "exil", "histoire"],
    summary:
      "À La Havane, le vieil Ignacio gagne sa vie en accueillant les touristes à l'aéroport pour leur faire découvrir la ville. Un jour, il prend sous son aile El Palenque, un jeune Guinéen venu à Cuba chercher la trace de sa propre histoire. En le guidant, Ignacio lui raconte des souvenirs remontant aux années de la révolution castriste. Un roman sur les liens secrets entre l'Afrique et Cuba, et sur la recherche des origines.",
    whyRead: [
      "Cuba et l'Afrique, reliées par une histoire de famille.",
      "Un narrateur cubain truculent, guide de La Havane.",
      "Monénembo poursuit son exploration de la diaspora noire.",
    ],
    year: 2015,
    publisher: "Points",
    pages: 183,
    isbn: "9782757857281",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "bled",
    title: "Bled",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "exil"],
    summary:
      "En Algérie, Zoubida, jeune femme rejetée par sa famille et par sa communauté, doit fuir. Sur sa route, elle rencontre des marginaux et des amis inattendus qui la protègent et lui ouvrent les portes de la littérature. Face à l'intégrisme religieux, les livres deviennent pour elle un refuge et une arme. Monénembo signe un roman de fuite et de liberté, porté par une héroïne attachante.",
    whyRead: [
      "Une héroïne en fuite qui trouve la liberté dans les livres.",
      "Un regard d'écrivain guinéen sur l'Algérie et l'intégrisme.",
      "Un éloge de la tolérance et de la lecture.",
    ],
    year: 2016,
    publisher: "Seuil",
    pages: 198,
    isbn: "9782021088960",
    format: null,
    awards: [],
  }),
  livre({
    slug: "saharienne-indigo",
    title: "Saharienne Indigo",
    contributors: [monenembo],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "histoire", "femmes"],
    summary:
      "À Conakry, Véronique Bangoura, quinze ans, prend la fuite après un geste terrible. Elle se cache dans une carrière abandonnée, puis erre de bar en boîte de nuit, suivie par un inconnu vêtu d'une saharienne indigo. Peu à peu, son histoire en croise une autre, plus ancienne, liée aux prisons du régime de Sékou Touré et au sinistre camp Boiro. Monénembo revient sur les blessures de la Guinée indépendante à travers une héroïne en cavale.",
    whyRead: [
      "Un roman haletant qui ressemble à un polar.",
      "La mémoire du camp Boiro, prison politique de la Guinée de Sékou Touré.",
      "Une héroïne en cavale, inoubliable.",
    ],
    year: 2022,
    publisher: "Seuil",
    pages: 330,
    isbn: "9782021088977",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-tribu-des-gonzesses",
    title: "La Tribu des gonzesses",
    contributors: [monenembo],
    genre: "theatre",
    audience: "adulte",
    themes: ["femmes", "exil", "identite", "humour"],
    summary:
      "Une petite communauté de femmes africaines vivant en exil se réunit et affiche fièrement son identité : refus de l'assimilation, solidarité, fidélité aux valeurs du pays. Mais au fil des échanges, les belles déclarations se heurtent aux mesquineries, aux jalousies et à tout ce que la vie loin de chez soi a changé. Seule pièce de théâtre de Tierno Monénembo, cette comédie grinçante interroge l'authenticité revendiquée par la diaspora.",
    whyRead: [
      "L'unique pièce de théâtre de Tierno Monénembo.",
      "Une comédie mordante sur la diaspora africaine.",
      "Des personnages féminins hauts en couleur.",
    ],
    year: 2006,
    publisher: "Cauris",
    pages: 118,
    isbn: "2914605242",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Djibril Tamsir Niane
  livre({
    slug: "sikasso-ou-la-derniere-citadelle-suivi-de-chaka",
    title: "Sikasso ou la Dernière Citadelle",
    subtitle: "suivi de Chaka",
    contributors: [niane],
    genre: "theatre",
    audience: "adulte",
    themes: ["histoire", "colonisation", "politique"],
    summary:
      "La première pièce met en scène le siège de Sikasso, capitale du royaume du Kénédougou, par les troupes coloniales françaises en 1898. Autour du roi Babemba, les guerriers et les conseillers se préparent à défendre la dernière citadelle libre de la région. La seconde pièce revient sur Chaka, le célèbre roi zoulou, bâtisseur d'empire et chef de guerre. L'historien du Soundjata fait revivre sur scène deux grandes figures de la résistance africaine.",
    whyRead: [
      "Le théâtre historique de l'auteur de Soundjata.",
      "Babemba et Chaka, deux héros de l'histoire africaine.",
      "Pour faire découvrir la résistance à la conquête coloniale.",
    ],
    year: 1971,
    publisher: "P.-J. Oswald",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Ahmadou Kourouma
  livre({
    slug: "monne-outrages-et-defis",
    title: "Monnè, outrages et défis",
    contributors: [kourouma],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "politique", "humour"],
    summary:
      "Djigui Keita, roi de Soba, en pays malinké, règne depuis si longtemps qu'on le croit éternel. À la fin du XIXe siècle, les Français arrivent et il choisit de composer avec eux pour garder son trône. Commence alors un siècle de « monnè », d'outrages et d'humiliations : travaux forcés, impôts, guerres des Blancs. Avec une ironie mordante, Kourouma raconte toute la colonisation à travers ce vieux roi et sa cour de griots.",
    whyRead: [
      "Un siècle de colonisation raconté avec une ironie féroce.",
      "Un vieux roi inoubliable, entre grandeur et compromissions.",
      "Le grand roman historique de Kourouma.",
    ],
    year: 1990,
    publisher: "Points",
    pages: 277,
    isbn: "2020349647",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "en-attendant-le-vote-des-betes-sauvages",
    title: "En attendant le vote des bêtes sauvages",
    contributors: [kourouma],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "humour", "tradition"],
    summary:
      "Pendant six veillées, un griot et son répondeur chantent la geste de Koyaga, chasseur devenu président-dictateur de la République du Golfe. Comme dans les récits de chasseurs, on raconte ses exploits, ses ruses, ses complots et ses alliances pendant la guerre froide. Derrière ce personnage, on reconnaît plusieurs dictateurs africains bien réels. Kourouma signe une satire puissante et drôle des pouvoirs absolus.",
    whyRead: [
      "Une satire géniale des dictatures africaines.",
      "Construit comme une veillée de chasseurs, avec griot et répondeur.",
      "Prix du Livre Inter 1999.",
    ],
    year: 1998,
    publisher: "Points",
    pages: 381,
    isbn: "9782757877104",
    format: "poche",
    awards: [{ name: "Prix du Livre Inter", year: 1999 }],
  }),
  livre({
    slug: "quand-on-refuse-on-dit-non",
    title: "Quand on refuse on dit non",
    contributors: [kourouma],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "histoire", "politique"],
    summary:
      "On retrouve Birahima, l'ancien enfant-soldat d'Allah n'est pas obligé. Il vit désormais à Daloa, en Côte d'Ivoire, et rêve d'école et de la belle Fanta. Quand la guerre civile éclate en 2002, la ville devient dangereuse et les deux jeunes gens partent vers le nord. En chemin, Fanta raconte à Birahima l'histoire de son pays, pour qu'il comprenne ce conflit. Ce dernier roman, resté inachevé, a été publié après la mort de Kourouma.",
    whyRead: [
      "La suite d'Allah n'est pas obligé, avec la même gouaille.",
      "Une leçon d'histoire ivoirienne racontée à un gamin des rues.",
      "Le dernier texte de Kourouma, publié après sa mort.",
    ],
    year: 2004,
    publisher: "Seuil",
    pages: 159,
    isbn: "202068022X",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-diseur-de-verite",
    title: "Le Diseur de vérité",
    contributors: [kourouma],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "tradition", "humour"],
    summary:
      "Dans un royaume malinké, le tyran Diarra règne par la peur, entouré de courtisans qui ne lui disent que ce qu'il veut entendre. Face à lui, une princesse, un griot et un fou font entendre d'autres voix. La pièce, inspirée des contes et des traditions du Manding, fait le procès du mensonge, d'où qu'il vienne. Jouée à Abidjan en 1972, elle fut vite interdite par le pouvoir et n'a été publiée qu'en 1998.",
    whyRead: [
      "L'unique pièce de théâtre de Kourouma.",
      "Une œuvre censurée en Côte d'Ivoire dès sa création.",
      "Le conte africain mis au service de la satire politique.",
    ],
    year: 1998,
    publisher: "Acoria",
    pages: 87,
    isbn: "2912525144",
    format: null,
    awards: [],
  }),
  livre({
    slug: "yacouba-chasseur-africain",
    title: "Yacouba, chasseur africain",
    contributors: [kourouma],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["tradition", "enfance", "famille"],
    summary:
      "Mathieu, jeune Franco-Ivoirien, passe ses vacances chez ses cousins à Abidjan. Il découvre une famille divisée : faut-il envoyer les garçons se faire initier dans le village d'origine, au nord du pays, par Yacouba, chasseur et prêtre traditionnel ? Les rites ont la réputation d'être dangereux. Le seul roman pour la jeunesse de Kourouma fait découvrir l'initiation et la Côte d'Ivoire d'aujourd'hui.",
    whyRead: [
      "Le seul roman pour la jeunesse d'Ahmadou Kourouma.",
      "Une découverte de l'initiation et des chasseurs malinké.",
      "À partir de 10 ans, en collection Folio cadet.",
    ],
    year: 1998,
    publisher: "Gallimard Jeunesse",
    pages: 108,
    isbn: "9782070630158",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Véronique Tadjo
  livre({
    slug: "laterite",
    title: "Latérite",
    contributors: [tadjo],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "amour", "tradition"],
    summary:
      "Premier livre de Véronique Tadjo, Latérite rassemble des poèmes courts et lumineux, nés de la terre rouge d'Afrique de l'Ouest qui lui donne son titre. La poète y parle d'amour, de paysages, de villages et de villes, mais aussi des injustices et des espoirs de son continent. La réédition en poche l'accompagne d'un autre recueil, Déclinaison du temps premier. Une voix simple et musicale, qui a marqué la poésie ivoirienne.",
    whyRead: [
      "Le premier livre de Véronique Tadjo.",
      "Des poèmes courts, faciles à lire à voix haute.",
      "Réédité en poche, avec un second recueil.",
    ],
    year: 1984,
    publisher: "Points",
    pages: 172,
    isbn: "9791041413652",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "a-vol-d-oiseau",
    title: "À vol d'oiseau",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "ville", "identite"],
    summary:
      "Plutôt qu'une histoire suivie, Véronique Tadjo propose une suite de courts tableaux, comme vus d'en haut, à vol d'oiseau. On y croise des amoureux, des passants, des enfants, des destins qui se nouent et se perdent dans une ville africaine. La narratrice dit elle-même qu'elle aurait aimé écrire une histoire avec un début et une fin, mais que la vie ne se raconte pas ainsi. Un premier roman fragmenté et poétique.",
    whyRead: [
      "Le premier roman de Véronique Tadjo, écrit par fragments.",
      "Une prose poétique, entre roman et recueil de nouvelles.",
      "Pour lire par petites touches, page après page.",
    ],
    year: 1986,
    publisher: "L'Harmattan",
    pages: 95,
    isbn: "2738416993",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-royaume-aveugle",
    title: "Le Royaume aveugle",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "femmes", "amour"],
    summary:
      "Dans un royaume imaginaire, un roi s'enferme dans sa forteresse et ne veut plus voir la misère de son peuple, livré aux abus de ses serviteurs. Sa fille unique, la princesse Akissi, refuse cet aveuglement. Elle ouvre les yeux sur le monde qui l'entoure et se laisse séduire par un homme qui veut libérer le pays de la tyrannie. Une fable politique sur le pouvoir et sur le courage de regarder la vérité en face.",
    whyRead: [
      "Une fable politique en forme de conte.",
      "Une princesse qui choisit de voir ce que son père refuse de voir.",
      "Une critique transparente des régimes autoritaires.",
    ],
    year: 1990,
    publisher: "L'Harmattan",
    pages: 143,
    isbn: "2738408893",
    format: null,
    awards: [],
  }),
  livre({
    slug: "champs-de-bataille-et-d-amour",
    title: "Champs de bataille et d'amour",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "ville", "identite"],
    summary:
      "Aimée, une Européenne, et Eloka, un Africain, vivent ensemble depuis longtemps dans une grande ville d'Afrique. Le temps a usé leur amour, et chacun se sent seul dans le couple. Autour d'eux, la ville bruyante et les crises du continent pèsent sur leur quotidien. Par petites scènes, Véronique Tadjo raconte l'érosion d'une histoire d'amour mixte et la difficulté de vivre ensemble.",
    whyRead: [
      "Le portrait sensible d'un couple mixte qui s'abîme.",
      "La grande ville africaine comme personnage à part entière.",
      "Une écriture par tableaux, sobre et intime.",
    ],
    year: 1999,
    publisher: "Présence africaine",
    pages: 175,
    isbn: "2911725751",
    format: null,
    awards: [],
  }),
  livre({
    slug: "a-mi-chemin",
    title: "À mi-chemin",
    contributors: [tadjo],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "identite", "amour"],
    summary:
      "Dans ce recueil de poèmes, Véronique Tadjo parle des départs et des retours, des chemins entre ici et là-bas, entre l'Afrique et le reste du monde. La poète se tient à mi-chemin, entre deux pays, deux langues, deux moments de la vie. Ses vers courts disent l'amour, la mémoire et l'attente. Le recueil est préfacé par l'écrivain Hamidou Dia.",
    whyRead: [
      "Des poèmes sur le voyage et l'entre-deux.",
      "Une écriture simple, accessible aux lecteurs de poésie débutants.",
      "Une étape dans l'œuvre poétique de Véronique Tadjo.",
    ],
    year: 2000,
    publisher: "L'Harmattan",
    pages: 99,
    isbn: "2738491545",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-ombre-d-imana",
    title: "L'Ombre d'Imana",
    subtitle: "Voyages jusqu'au bout du Rwanda",
    contributors: [tadjo],
    genre: "recit",
    audience: "adulte",
    themes: ["genocide", "histoire", "guerre"],
    summary:
      "En 1998, quatre ans après le génocide des Tutsi, Véronique Tadjo se rend au Rwanda avec d'autres écrivains africains. Elle visite les lieux des massacres, rencontre des rescapés, des orphelins, des prisonniers, des femmes qui tentent de reconstruire leur vie. Son récit mêle témoignages, impressions de voyage et courtes fictions. Un livre bref et bouleversant, qui interroge la mémoire et le pardon.",
    whyRead: [
      "Un des grands livres du projet « Écrire par devoir de mémoire ».",
      "Un récit court, entre reportage, témoignages et fiction.",
      "Pour comprendre le Rwanda d'après le génocide.",
    ],
    year: 2000,
    publisher: "Actes Sud (Babel)",
    pages: 130,
    isbn: "2742754776",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "loin-de-mon-pere",
    title: "Loin de mon père",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "identite", "tradition"],
    summary:
      "Après des années d'absence, Nina, fille d'une Française et d'un Ivoirien, revient à Abidjan pour enterrer son père, le docteur Kouadio Yao. La famille organise des funérailles selon la tradition, tandis que Nina range les affaires du défunt. Elle découvre alors des pans entiers de sa vie qu'elle ignorait. Un roman en partie autobiographique sur le deuil, le métissage et une Côte d'Ivoire marquée par la crise.",
    whyRead: [
      "Un roman intime sur le deuil d'un père.",
      "Les funérailles ivoiriennes, entre tradition et modernité.",
      "La quête d'identité d'une héroïne métisse.",
    ],
    year: 2010,
    publisher: "Actes Sud",
    pages: 188,
    isbn: "9782742791279",
    format: null,
    awards: [],
  }),
  livre({
    slug: "en-compagnie-des-hommes",
    title: "En compagnie des hommes",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "tradition", "famille"],
    summary:
      "En 2014, l'épidémie d'Ebola frappe la Guinée, le Liberia et la Sierra Leone. Véronique Tadjo donne la parole à ceux qui l'ont vécue : soignants, malades, survivants, fossoyeurs, familles. Mais elle fait aussi parler un vieux baobab, témoin de l'histoire des hommes, et la chauve-souris soupçonnée d'avoir transmis le virus. Un roman choral et poétique sur la fragilité humaine et notre lien avec la nature.",
    whyRead: [
      "L'épidémie d'Ebola racontée à plusieurs voix.",
      "Un baobab et une chauve-souris parmi les narrateurs.",
      "Un livre devenu encore plus fort après la pandémie de Covid.",
    ],
    year: 2017,
    publisher: "Don Quichotte",
    pages: 166,
    isbn: "9782359496390",
    format: null,
    awards: [],
  }),
  livre({
    slug: "je-remercie-la-nuit",
    title: "Je remercie la nuit",
    contributors: [tadjo],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "femmes", "exil"],
    summary:
      "Flora et Yasmina sont étudiantes à Abidjan quand éclate la crise électorale de 2010-2011, qui plonge la Côte d'Ivoire dans la violence. Prises dans la tourmente, les deux amies voient leurs chemins se séparer : l'une doit rentrer dans sa famille, l'autre s'installe à Johannesburg pour recommencer sa vie. À travers les carnets de Flora, Véronique Tadjo raconte une génération qui cherche sa voie entre engagement, art et désir de réconciliation.",
    whyRead: [
      "La crise ivoirienne de 2010-2011 vue par deux jeunes femmes.",
      "Prix Ivoire 2025.",
      "Un roman sur l'amitié, l'exil et l'espoir d'une génération.",
    ],
    year: 2024,
    publisher: "Mémoire d'encrier",
    pages: 302,
    isbn: "9782897129842",
    format: null,
    awards: [{ name: "Prix Ivoire", year: 2025 }],
  }),
  livre({
    slug: "la-chanson-de-la-vie",
    title: "La Chanson de la vie",
    subtitle: "et autres histoires",
    contributors: [tadjo],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "tradition", "enfance"],
    summary:
      "Ce recueil réunit une vingtaine de textes courts, contes, nouvelles et poèmes, écrits par Véronique Tadjo et illustrés de ses propres dessins en noir et blanc. Plusieurs histoires s'inspirent des traditions orales du Nigeria, où l'autrice vivait alors. On y rencontre des animaux, des esprits et des humains face à leurs choix. Les messages, discrets, parlent de la folie des hommes et de la fragilité de la terre.",
    whyRead: [
      "Un classique de la littérature jeunesse africaine.",
      "Des contes, des nouvelles et des poèmes à lire dès 10 ans.",
      "Illustré par l'autrice elle-même.",
    ],
    year: 1990,
    publisher: "NEI-CEDA",
    pages: 120,
    isbn: "9782863945650",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "mamy-wata-et-le-monstre",
    title: "Mamy Wata et le Monstre",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "tradition"],
    summary:
      "Mamy Wata, la reine de toutes les eaux, nage tranquillement dans un grand fleuve quand elle apprend qu'un horrible monstre terrorise les villages voisins. Elle décide d'aller à sa rencontre. Mais derrière l'apparence effrayante du monstre se cache une histoire plus triste qu'on ne le croit. Un album illustré par Véronique Tadjo, qui fait découvrir aux enfants une grande figure des croyances d'Afrique de l'Ouest.",
    whyRead: [
      "Mamy Wata, la déesse des eaux, racontée aux petits.",
      "Un album aux couleurs vives, illustré par l'autrice.",
      "Une histoire de bonté face à la peur.",
    ],
    year: 1993,
    publisher: "NEI / EDICEF",
    pages: 25,
    isbn: "2910190196",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "le-seigneur-de-la-danse",
    title: "Le Seigneur de la danse",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["tradition", "spiritualite", "contes"],
    summary:
      "Dans les villages sénoufo du nord de la Côte d'Ivoire, le masque est le seigneur de la danse. Il sort pour les fêtes et les deuils, accompagné de chants et de tambours, et partage les joies et les peines des hommes. Véronique Tadjo a écrit ce texte poétique en s'inspirant d'un vieux chant anglais et l'a illustré dans le style de l'art sénoufo, en couleurs éclatantes. Une page finale présente le peuple sénoufo et ses masques.",
    whyRead: [
      "Un album poétique sur les masques sénoufo.",
      "Des illustrations inspirées de l'art traditionnel.",
      "Une belle introduction à la culture ivoirienne pour les enfants.",
    ],
    year: 1993,
    publisher: "NEI / EDICEF",
    pages: 24,
    isbn: "2850699101",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "le-grain-de-mais-magique",
    title: "Le Grain de maïs magique",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "enfance"],
    summary:
      "Le petit Soro a reçu de ses parents un grain de maïs magique. Mais une pintade sauvage le lui vole et s'enfuit. Bien décidé à retrouver son trésor, Soro se lance à sa poursuite et ne se laisse détourner par rien, même pas par trois rencontres pleines de promesses. Un conte rythmé, avec ses refrains et ses dialogues, qui apprend aux enfants que la magie n'est pas toujours là où on la croit.",
    whyRead: [
      "Un conte à lire à voix haute, avec refrains et répétitions.",
      "Un petit héros obstiné auquel les enfants s'identifient.",
      "Des images aux couleurs franches, signées par l'autrice.",
    ],
    year: 1995,
    publisher: "NEI",
    pages: 23,
    isbn: "2910190633",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "grand-mere-nanan",
    title: "Grand-mère Nanan",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["famille", "tradition", "enfance"],
    summary:
      "Grand-mère Nanan adore les enfants. Sa porte leur est toujours ouverte : elle joue avec eux, leur raconte des histoires, leur donne des conseils et soigne les petits bobos avec des plantes. Elle a aussi une poupée qui ne la quitte jamais. Véronique Tadjo a écrit cet album à la mort de sa propre grand-mère, et l'a illustré avec des dessins et des photos de son village. Un hommage tendre à toutes les grands-mères.",
    whyRead: [
      "Un hommage tendre aux grands-mères africaines.",
      "Des illustrations qui mêlent dessins et photographies.",
      "Une histoire douce sur la transmission entre générations.",
    ],
    year: 1996,
    publisher: "NEI / EDICEF",
    pages: 23,
    isbn: null,
    format: "album",
    awards: [],
  }),
  livre({
    slug: "le-bel-oiseau-et-la-pluie",
    title: "Le Bel Oiseau et la pluie",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "tradition"],
    summary:
      "La pluie se fait attendre et la terre se dessèche. Les hommes partent à sa recherche, sans succès. C'est finalement un bel oiseau qui s'élance vers le ciel et perce un énorme nuage, pour ramener la joie sur la terre. Un conte illustré de la collection « Le bois sacré », qui parle aux enfants de la nature, de la sécheresse et de la solidarité.",
    whyRead: [
      "Un conte simple sur la pluie et la sécheresse.",
      "Un oiseau courageux, héros de l'histoire.",
      "Un album illustré par Véronique Tadjo.",
    ],
    year: 1998,
    publisher: "NEI",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
  }),
  livre({
    slug: "masque-raconte-moi",
    title: "Masque, raconte-moi",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["tradition", "contes"],
    summary:
      "Un masque sort de la forêt et se met à danser. Il devient tour à tour l'antilope, le crocodile, l'oiseau, le caméléon, et raconte leur histoire. Chaque animal lui prête une qualité : l'élégance, la force, la capacité de s'adapter. Avec cet album illustré sur papier kraft, Véronique Tadjo invite les enfants à regarder un masque africain de près et à comprendre ce qu'il représente.",
    whyRead: [
      "Apprendre à regarder un masque africain, détail par détail.",
      "Des animaux symboliques et leurs qualités.",
      "Des illustrations originales sur papier kraft.",
    ],
    year: 2002,
    publisher: "EDICEF",
    pages: 23,
    isbn: "2841298337",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "ayanda-la-petite-fille-qui-ne-voulait-pas-grandir",
    title: "Ayanda, la petite fille qui ne voulait pas grandir",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "guerre", "famille"],
    summary:
      "Ayanda est une petite fille heureuse, jusqu'au jour où son père, enrôlé comme soldat, ne revient pas de la guerre. Révoltée contre le monde cruel des adultes, elle décide de ne plus grandir. Mais quand sa famille et son village ont besoin d'elle, Ayanda va devoir changer de taille. Un album qui aborde avec délicatesse la guerre, le deuil et la force des enfants.",
    whyRead: [
      "Un album qui parle de la guerre et du deuil aux enfants.",
      "Une héroïne au pouvoir merveilleux, entre conte et réalité.",
      "Une histoire de courage et d'amour.",
    ],
    year: 2007,
    publisher: "Actes Sud Junior",
    pages: null,
    isbn: "9782742769995",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "nelson-mandela-non-a-l-apartheid",
    title: "Nelson Mandela",
    subtitle: "Non à l'apartheid !",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "ado",
    themes: ["politique", "histoire", "identite"],
    summary:
      "Véronique Tadjo raconte aux jeunes lecteurs la vie de Nelson Mandela, de son enfance dans un village du Transkei à son combat contre l'apartheid en Afrique du Sud. Elle évoque ses années d'avocat, l'engagement dans l'ANC, le procès et les vingt-sept années de prison. Le livre explique ce qu'était le régime de ségrégation raciale et pourquoi Mandela est devenu un symbole mondial. Une biographie claire, dans la collection « Ceux qui ont dit non ».",
    whyRead: [
      "Une biographie de Mandela écrite pour les adolescents.",
      "Pour comprendre l'apartheid simplement.",
      "Dans la collection « Ceux qui ont dit non » d'Actes Sud Junior.",
    ],
    year: 2010,
    publisher: "Actes Sud Junior",
    pages: 95,
    isbn: "9782330032418",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "leopold-sedar-senghor-le-poete-des-paroles-qui-durent",
    title: "Léopold Sédar Senghor",
    subtitle: "Le poète des paroles qui durent",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["identite", "politique", "histoire"],
    summary:
      "Ce petit livre raconte aux enfants la vie de Léopold Sédar Senghor : l'enfance à Joal, au bord de l'océan, les études à Paris, la poésie de la négritude, puis la présidence du Sénégal indépendant. Véronique Tadjo explique simplement ce que veut dire être poète et homme politique à la fois. Le texte est accompagné d'illustrations et paraît dans une collection de biographies pour les jeunes lecteurs.",
    whyRead: [
      "Une première biographie de Senghor pour les enfants.",
      "La négritude expliquée simplement.",
      "Un petit format illustré, facile à lire.",
    ],
    year: 2014,
    publisher: "À dos d'âne",
    pages: 45,
    isbn: "9782919372348",
    format: null,
    awards: [],
  }),
  livre({
    slug: "graca-machel-championne-des-enfants",
    title: "Graça Machel",
    subtitle: "Championne des enfants",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["femmes", "politique", "enfance"],
    summary:
      "Véronique Tadjo raconte aux jeunes lecteurs le parcours de Graça Machel, née au Mozambique sous la colonisation portugaise. Militante de l'indépendance, puis ministre de l'Éducation, elle a consacré sa vie à l'école et à la défense des droits des enfants, notamment des enfants pris dans les guerres. Une petite biographie illustrée, qui présente une grande figure féminine de l'Afrique australe.",
    whyRead: [
      "Le portrait d'une grande militante africaine des droits des enfants.",
      "Une figure féminine encore trop peu connue en France.",
      "Une biographie courte et illustrée pour les enfants.",
    ],
    year: 2017,
    publisher: "À dos d'âne",
    pages: 45,
    isbn: "9782376060000",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-voyage-de-yao",
    title: "Le Voyage de Yao",
    contributors: [tadjo],
    genre: "jeunesse",
    audience: "ado",
    themes: ["enfance", "identite", "exil"],
    summary:
      "Yao vit dans un village du nord du Sénégal et rêve de voyages grâce à ses lectures. Quand il apprend que son écrivain préféré, Seydou Tall, vient présenter son livre à Dakar, il part seul pour le rencontrer. Touché, l'auteur décide de raccompagner l'enfant chez lui. Commence un long trajet à travers le pays, où l'adulte et l'enfant apprennent à se connaître. Véronique Tadjo a tiré ce roman du film Yao de Philippe Godeau.",
    whyRead: [
      "Un road-movie tendre à travers le Sénégal.",
      "Adapté du film Yao, avec Omar Sy.",
      "Une belle histoire sur le pouvoir des livres.",
    ],
    year: 2019,
    publisher: "Seuil Jeunesse",
    pages: 189,
    isbn: "9791023512052",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Bernard Dadié
  livre({
    slug: "afrique-debout",
    title: "Afrique debout !",
    contributors: [dadie],
    genre: "poesie",
    audience: "adulte",
    themes: ["colonisation", "identite", "politique"],
    summary:
      "Premier recueil de Bernard Dadié, Afrique debout ! paraît en 1950, alors que le poète milite contre le système colonial en Côte d'Ivoire. Ses poèmes appellent l'Afrique à se relever, à retrouver sa dignité et à refuser la domination. On y entend la colère, mais aussi l'espoir et la fraternité. Le recueil est aujourd'hui repris avec d'autres textes de Dadié dans le volume Légendes et poèmes.",
    whyRead: [
      "Le premier recueil d'un pionnier de la littérature ivoirienne.",
      "Une poésie de combat, écrite au temps de la colonisation.",
      "Des vers simples et puissants, faits pour être dits.",
    ],
    year: 1950,
    publisher: "Seghers",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "legendes-africaines",
    title: "Légendes africaines",
    contributors: [dadie],
    genre: "contes",
    audience: "adulte",
    themes: ["contes", "tradition", "histoire"],
    summary:
      "Bernard Dadié réunit des légendes de Côte d'Ivoire et d'Afrique de l'Ouest, transmises oralement de génération en génération. On y trouve notamment la légende baoulé de la reine Pokou, qui dut faire un terrible sacrifice pour sauver son peuple au moment de traverser un fleuve. D'autres récits expliquent l'origine des choses, des peuples ou des coutumes. Un recueil qui fixe par écrit une mémoire collective.",
    whyRead: [
      "La légende de la reine Pokou, aux origines du peuple baoulé.",
      "Des récits de la tradition orale ivoirienne.",
      "Un classique de Dadié, toujours réédité à Abidjan.",
    ],
    year: 1954,
    publisher: "NEI-CEDA",
    pages: 111,
    isbn: "9782844876942",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-ronde-des-jours",
    title: "La Ronde des jours",
    contributors: [dadie],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "tradition", "colonisation"],
    summary:
      "Dans ce deuxième recueil, Bernard Dadié chante la vie de tous les jours, le travail, l'amour, la fraternité et l'attachement à la terre africaine. On y trouve le poème « Je vous remercie mon Dieu », où le poète revendique avec fierté et ironie sa couleur de peau. Les poèmes, à la fois simples et engagés, accompagnent la marche vers la liberté. Une œuvre essentielle de la poésie ivoirienne.",
    whyRead: [
      "Le recueil du célèbre poème « Je vous remercie mon Dieu ».",
      "Une poésie lumineuse, engagée sans être austère.",
      "Un incontournable de la poésie africaine francophone.",
    ],
    year: 1956,
    publisher: "NEI",
    pages: 55,
    isbn: "2844872077",
    format: null,
    awards: [],
  }),
  livre({
    slug: "un-negre-a-paris",
    title: "Un nègre à Paris",
    contributors: [dadie],
    genre: "recit",
    audience: "adulte",
    themes: ["humour", "identite", "ville"],
    summary:
      "Tanhoé Bertin, un Ivoirien, obtient un billet pour Paris et découvre la capitale française en 1956. Dans une longue lettre à un ami resté au pays, il décrit avec étonnement les Parisiens, leurs coutumes, leurs monuments, leur politique et leur rapport à l'argent. Comme les voyageurs des Lettres persanes, il retourne le regard : c'est l'Africain qui observe et juge les Européens. Une chronique pleine d'humour et de malice.",
    whyRead: [
      "Paris vu par un Africain, avec une ironie réjouissante.",
      "Un renversement du regard colonial, à la manière de Montesquieu.",
      "Un classique toujours drôle et très actuel.",
    ],
    year: 1959,
    publisher: "Présence africaine",
    pages: 217,
    isbn: "2708706187",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "patron-de-new-york",
    title: "Patron de New York",
    contributors: [dadie],
    genre: "recit",
    audience: "adulte",
    themes: ["humour", "ville", "identite"],
    summary:
      "Après Paris, Bernard Dadié pose son regard malicieux sur New York, qu'il découvre au début des années 1960. Il décrit la ville des gratte-ciel, la place de l'argent, la vitesse, la religion, mais aussi la situation des Noirs américains en pleine lutte pour les droits civiques. Avec humour et curiosité, il compare sans cesse ce qu'il voit à l'Afrique. Une chronique de voyage savoureuse.",
    whyRead: [
      "L'Amérique des années 1960 vue par un écrivain ivoirien.",
      "Grand prix littéraire d'Afrique noire 1965.",
      "Un regard drôle et lucide sur la société américaine.",
    ],
    year: 1964,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1965 }],
  }),
  livre({
    slug: "hommes-de-tous-les-continents",
    title: "Hommes de tous les continents",
    contributors: [dadie],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "politique"],
    summary:
      "Dans ce recueil, Bernard Dadié élargit son regard au-delà de l'Afrique. Ses poèmes s'adressent aux hommes et aux femmes de tous les pays, de toutes les couleurs, unis par les mêmes peines et les mêmes espoirs. Le poète dénonce le racisme, la guerre et l'injustice, et rêve d'une humanité fraternelle. Une poésie généreuse, tournée vers les autres.",
    whyRead: [
      "Une poésie de la fraternité universelle.",
      "Dadié, poète engagé contre le racisme et l'injustice.",
      "Des vers simples, faciles à partager.",
    ],
    year: 1967,
    publisher: "Présence africaine",
    pages: 86,
    isbn: "2708704656",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-ville-ou-nul-ne-meurt",
    title: "La Ville où nul ne meurt",
    subtitle: "Rome",
    contributors: [dadie],
    genre: "recit",
    audience: "adulte",
    themes: ["ville", "spiritualite", "humour"],
    summary:
      "Après Paris et New York, Bernard Dadié visite Rome, la ville éternelle. Il se promène parmi les ruines antiques, les églises et les places, observe le Vatican, les touristes et les Romains d'aujourd'hui. Avec son humour habituel, il s'interroge sur ce qui fait durer une ville et une civilisation. Le troisième volet de ses chroniques de voyage, récemment réédité.",
    whyRead: [
      "Rome vue par un voyageur africain des années 1960.",
      "Le troisième volet des chroniques après Paris et New York.",
      "Réédité en 2023 chez Présence africaine.",
    ],
    year: 1969,
    publisher: "Présence africaine",
    pages: 256,
    isbn: "9782708710221",
    format: null,
    awards: [],
  }),
  livre({
    slug: "monsieur-thogo-gnini",
    title: "Monsieur Thôgô-gnini",
    contributors: [dadie],
    genre: "theatre",
    audience: "adulte",
    themes: ["humour", "colonisation", "politique"],
    summary:
      "Au XIXe siècle, sur la côte d'Afrique de l'Ouest, Thôgô-gnini, porte-canne du roi, devient l'intermédiaire indispensable entre son peuple et les commerçants européens. Il s'enrichit, prend des airs de grand bourgeois et n'hésite pas à écraser les siens pour garder sa fortune. Bernard Dadié signe une comédie satirique sur l'avidité et sur ces élites africaines qui profitent de la domination étrangère.",
    whyRead: [
      "Une comédie satirique encore très jouée en Afrique.",
      "Un personnage d'arriviste inoubliable.",
      "Une critique des élites qui profitent du système.",
    ],
    year: 1970,
    publisher: "Présence africaine",
    pages: 115,
    isbn: "2708702394",
    format: null,
    awards: [],
  }),
  livre({
    slug: "beatrice-du-congo",
    title: "Béatrice du Congo",
    contributors: [dadie],
    genre: "theatre",
    audience: "adulte",
    themes: ["colonisation", "spiritualite", "femmes", "histoire"],
    summary:
      "Au début du XVIIIe siècle, le royaume du Kongo est affaibli par les guerres et l'influence des Portugais, que Dadié appelle les « Bitandais ». Une jeune femme, Béatrice, se dit inspirée par Dieu et appelle son peuple à se libérer de la domination étrangère. Elle rassemble les foules et inquiète le pouvoir. Inspirée de l'histoire réelle de Kimpa Vita, cette tragédie parle aussi des indépendances africaines.",
    whyRead: [
      "L'histoire de Kimpa Vita, prophétesse et résistante du Kongo.",
      "Une grande tragédie politique du théâtre africain.",
      "Une héroïne féminine face aux colonisateurs.",
    ],
    year: 1970,
    publisher: "Présence africaine",
    pages: 147,
    isbn: "2708705989",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-voix-dans-le-vent",
    title: "Les Voix dans le vent",
    contributors: [dadie],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "spiritualite"],
    summary:
      "Nahoubou, homme du peuple, rêve de devenir roi pour rétablir la justice. Mais pour obtenir le pouvoir absolu, il accepte les conseils d'un sorcier et sacrifie ceux qui lui sont chers. Une fois sur le trône, il installe la terreur, hanté par des voix qui l'accusent sans relâche. Cette tragédie est une parabole sur les dirigeants qui trahissent les promesses faites à leur peuple.",
    whyRead: [
      "Une tragédie du pouvoir, à la manière de Macbeth.",
      "Une parabole sur les dictatures africaines.",
      "Un texte fort, souvent étudié et joué.",
    ],
    year: 1970,
    publisher: "NEI",
    pages: 144,
    isbn: "2844871321",
    format: null,
    awards: [],
  }),
  livre({
    slug: "iles-de-tempete",
    title: "Îles de tempête",
    contributors: [dadie],
    genre: "theatre",
    audience: "adulte",
    themes: ["esclavage", "colonisation", "histoire"],
    summary:
      "Dans cette pièce en sept tableaux, Bernard Dadié raconte la révolte de Saint-Domingue, la colonie française qui deviendra Haïti. Au centre, Toussaint Louverture, ancien esclave devenu général, qui mène la lutte contre l'esclavage et tient tête à Bonaparte. La pièce montre son génie politique, mais aussi ses doutes et ses contradictions. Une réflexion sur la liberté et sur le prix des indépendances.",
    whyRead: [
      "Toussaint Louverture et la révolution haïtienne sur scène.",
      "Un pont entre l'Afrique et les Caraïbes.",
      "Une pièce sur la liberté et ses contradictions.",
    ],
    year: 1973,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "opinions-d-un-negre",
    title: "Opinions d'un nègre",
    contributors: [dadie],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "identite", "humour"],
    summary:
      "Ce petit livre rassemble des aphorismes écrits par Bernard Dadié entre 1934 et 1946, en pleine époque coloniale. En quelques mots, souvent avec ironie, le jeune écrivain dit ce qu'il pense du racisme, du pouvoir colonial, de la religion, de l'amitié ou de la condition humaine. Ces pensées brèves éclairent la formation d'un esprit libre, bien avant les indépendances.",
    whyRead: [
      "Les pensées de jeunesse de Dadié, en formules courtes.",
      "Un regard lucide sur l'époque coloniale.",
      "À picorer, une phrase à la fois.",
    ],
    year: 1979,
    publisher: "Nouvelles Éditions africaines",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "carnet-de-prison",
    title: "Carnet de prison",
    contributors: [dadie],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "politique", "independances"],
    summary:
      "En février 1949, Bernard Dadié, militant du Rassemblement démocratique africain, est arrêté avec d'autres responsables du parti et emprisonné à Grand-Bassam. Pendant seize mois, il tient un journal. Il y note la vie quotidienne en prison, les nouvelles du dehors, ses réflexions sur la lutte anticoloniale et sur la liberté. Publié plus de trente ans plus tard, ce carnet est un document précieux sur le chemin vers l'indépendance ivoirienne.",
    whyRead: [
      "Le journal de prison d'un militant anticolonial.",
      "Un témoignage rare sur la Côte d'Ivoire de 1949.",
      "Pour comprendre l'engagement politique de Dadié.",
    ],
    year: 1981,
    publisher: "CEDA",
    pages: 335,
    isbn: "2863940244",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-belles-histoires-de-kacou-ananze",
    title: "Les Belles Histoires de Kacou Ananzè, l'araignée",
    contributors: [dadie, { role: "auteur", name: "André Terrisse", authorSlug: null }],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "ecole", "humour"],
    summary:
      "Kacou Ananzè, l'araignée, est le grand rusé des contes akan de Côte d'Ivoire et du Ghana. Gourmand, menteur, toujours prêt à tromper les autres animaux, il se fait parfois prendre à son propre piège. Bernard Dadié et André Terrisse ont réuni ses aventures dans un livre de lecture destiné aux écoles africaines. Des fables malicieuses où la ruse et l'intelligence l'emportent souvent sur la force.",
    whyRead: [
      "Les aventures de l'araignée Ananzè, héros des contes akan.",
      "Un livre de lecture qui a accompagné des générations d'écoliers.",
      "Des fables drôles, à lire avec les enfants.",
    ],
    year: 1962,
    publisher: "Nathan",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Gauz
  livre({
    slug: "camarade-papa",
    title: "Camarade papa",
    contributors: [gauz],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "identite", "humour"],
    summary:
      "À la fin du XIXe siècle, Dabilly, jeune Français en quête d'aventure, débarque sur la côte de l'actuelle Côte d'Ivoire, au moment où la France y installe sa colonie. Un siècle plus tard, à Amsterdam, un petit garçon noir élevé par des parents communistes est envoyé chez sa grand-mère en Côte d'Ivoire. Leurs deux récits, l'un en vieux français colonial, l'autre en langage d'enfant militant, se répondent. Gauz revisite la colonisation avec beaucoup d'humour et d'invention.",
    whyRead: [
      "La colonisation racontée par deux voix étonnantes.",
      "Grand prix littéraire d'Afrique noire et prix Ivoire 2018.",
      "Un roman drôle, inventif et très documenté.",
    ],
    year: 2018,
    publisher: "Le Livre de poche",
    pages: 264,
    isbn: "9782253259589",
    format: "poche",
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2018 },
      { name: "Prix Ivoire", year: 2018 },
    ],
  }),
  livre({
    slug: "black-manoo",
    title: "Black Manoo",
    contributors: [gauz],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "humour"],
    summary:
      "Black Manoo débarque à Paris dans les années 1990 avec un faux passeport. Sans papiers, il apprend à survivre à Belleville et croise une galerie de personnages hauts en couleur. Chaque chapitre est une histoire, drôle ou poignante. Gauz dresse un portrait vivant du Paris des immigrés africains.",
    whyRead: [
      "Le Paris des sans-papiers raconté avec tendresse et humour.",
      "Des chapitres courts, comme autant d'histoires.",
      "Par l'auteur de Debout-payé.",
    ],
    year: 2020,
    publisher: "Points",
    pages: 154,
    isbn: "9782757889350",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "cocoaians-naissance-d-une-nation-chocolat",
    title: "Cocoaïans",
    subtitle: "Naissance d'une nation chocolat",
    contributors: [gauz],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "travail", "politique", "independances"],
    summary:
      "La Côte d'Ivoire est le premier producteur mondial de cacao, mais le chocolat se fabrique et se vend surtout ailleurs. Dans ce texte écrit pour être dit à voix haute, Gauz raconte l'histoire politique du cacao au XXe siècle, de la plantation au produit fini. Il imagine le projet des « Cocoaïans », habitants du pays du cacao, décidés à fabriquer et vendre eux-mêmes leur chocolat. Un cri de révolte plein de rythme et d'humour.",
    whyRead: [
      "L'histoire du cacao ivoirien racontée comme une épopée.",
      "Un texte court, écrit pour la scène et la voix.",
      "Une réflexion vive sur l'économie postcoloniale.",
    ],
    year: 2022,
    publisher: "L'Arche",
    pages: 105,
    isbn: "9782381980423",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-portes",
    title: "Les Portes",
    contributors: [gauz],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "politique", "travail"],
    summary:
      "Paris, 1996. Menés par leur porte-parole Madjiguène Cissé, des Africains sans papiers occupent l'église Saint-Bernard, dans le quartier de la Goutte-d'Or, pour réclamer leur régularisation. Gauz raconte, jour après jour, le combat de ces hommes et de ces femmes, leurs espoirs, leurs peurs et la solidarité qui les entoure. Un roman librement inspiré d'un épisode marquant de l'histoire de l'immigration en France.",
    whyRead: [
      "L'occupation de l'église Saint-Bernard, en 1996, racontée de l'intérieur.",
      "Un hommage à Madjiguène Cissé et aux sans-papiers.",
      "Un roman engagé et humain.",
    ],
    year: 2024,
    publisher: "Le Nouvel Attila",
    pages: 188,
    isbn: "9782493213754",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Mbarek Ould Beyrouk
  livre({
    slug: "et-le-ciel-a-oublie-de-pleuvoir",
    title: "Et le ciel a oublié de pleuvoir",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "ville"],
    summary:
      "Aux confins du désert mauritanien, dans les campements de la tribu des Oulad Ayatt, la belle Lolla dérange par sa fierté. Le chef Béchir, hostile à tout changement, veut l'épouser contre son gré. Lolla refuse de se soumettre et choisit la ville. Son destin croise celui de Mahmoud, ancien esclave en fuite devenu haut placé dans l'État. Le premier roman de Beyrouk raconte une société nomade bousculée par la modernité.",
    whyRead: [
      "Le premier roman de Beyrouk, entre désert et ville.",
      "Une héroïne libre face aux traditions tribales.",
      "La Mauritanie, rarement présente en littérature.",
    ],
    year: 2006,
    publisher: "Dapper",
    pages: 124,
    isbn: "2915258139",
    format: null,
    awards: [],
  }),
  livre({
    slug: "nouvelles-du-desert",
    title: "Nouvelles du désert",
    contributors: [beyrouk],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["tradition", "ville", "identite"],
    summary:
      "Ce recueil réunit une vingtaine de textes courts sur la Mauritanie d'aujourd'hui. Beyrouk y raconte une société en plein bouleversement, partagée entre les traditions du désert et l'attrait de la ville. Nomades sédentarisés, jeunes tentés par la capitale, anciens attachés aux coutumes : chaque nouvelle saisit un moment de ce passage. Des histoires brèves, ironiques ou mélancoliques.",
    whyRead: [
      "Des nouvelles courtes sur la Mauritanie contemporaine.",
      "Le choc entre la vie nomade et la ville.",
      "Une bonne porte d'entrée dans l'œuvre de Beyrouk.",
    ],
    year: 2009,
    publisher: "Présence africaine",
    pages: 138,
    isbn: "9782708707993",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-griot-de-l-emir",
    title: "Le Griot de l'émir",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["tradition", "politique", "histoire"],
    summary:
      "Dans le Sahara d'autrefois, parmi les tribus maures, un griot, héritier d'une lignée de poètes-musiciens aujourd'hui dispersée, va de campement en campement. L'émir Ahmed, homme brutal et sans scrupules, voudrait qu'il chante sa gloire, mais le griot refuse de le servir. Un drame lié à l'émir va le pousser vers l'exil, jusqu'à Tombouctou, la ville du savoir. Un récit à la première personne, à la fois poème et musique.",
    whyRead: [
      "Le Sahara des émirs et des griots, raconté de l'intérieur.",
      "Un artiste qui refuse de flatter le pouvoir.",
      "Une langue poétique et musicale.",
    ],
    year: 2013,
    publisher: "Elyzad",
    pages: 166,
    isbn: "9789973580528",
    format: null,
    awards: [],
  }),
  livre({
    slug: "je-suis-seul",
    title: "Je suis seul",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "spiritualite", "guerre"],
    summary:
      "Dans une ville aux portes du Sahara, un groupe djihadiste vient de prendre le pouvoir. Le narrateur, menacé, se cache dans la maison d'une femme qu'il a aimée. Enfermé, il ressasse ses peurs, ses doutes et ses regrets, et ne trouve de réconfort que dans un dialogue imaginaire avec un ancêtre. Un long monologue sur la peur, la lâcheté et la violence qui menace le Sahel.",
    whyRead: [
      "Un huis clos tendu, face à la menace djihadiste.",
      "Un monologue intérieur saisissant.",
      "Un roman court sur le Sahel d'aujourd'hui.",
    ],
    year: 2018,
    publisher: "Elyzad",
    pages: 107,
    isbn: "9789973581136",
    format: null,
    awards: [],
  }),
  livre({
    slug: "parias",
    title: "Parias",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "ville", "tradition"],
    summary:
      "En Mauritanie, un père enfermé dans une cellule écrit à la femme qu'il aime toujours. Issu d'une tribu de nomades, il a tout quitté par amour. Pendant ce temps, leur fils survit dans les quartiers pauvres de la ville, entre petits larcins et bandes rivales. Leurs deux voix alternent sans jamais se parler. Beyrouk reconstitue une tragédie familiale, entre désert perdu et misère urbaine.",
    whyRead: [
      "Deux monologues croisés, un père et un fils.",
      "Le déracinement des nomades dans la ville mauritanienne.",
      "Une écriture élégante et intense.",
    ],
    year: 2021,
    publisher: "Sabine Wespieser",
    pages: 183,
    isbn: "9782848053868",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-silence-des-horizons",
    title: "Le Silence des horizons",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "famille", "tradition"],
    summary:
      "Nadir, jeune homme rongé par un acte violent qu'il vient de commettre, fuit et rejoint un ami guide pour touristes dans le désert. Il est engagé comme conteur, chargé de raconter aux enfants des voyageurs des histoires de djinns et de mondes lointains. Mais sa conscience le tourmente : doit-il se livrer ? Il repense aussi à son père, guide et conteur aimé, autrefois condamné à tort. Un roman sur la faute et la vérité.",
    whyRead: [
      "Un dilemme moral au cœur du désert.",
      "Des contes de djinns enchâssés dans le récit.",
      "Une écriture qui rappelle L'Étranger de Camus.",
    ],
    year: 2021,
    publisher: "Elyzad",
    pages: 183,
    isbn: "9782492270017",
    format: null,
    awards: [],
  }),
  livre({
    slug: "saara",
    title: "Saara",
    contributors: [beyrouk],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "politique"],
    summary:
      "Dans une oasis paisible au pied d'une montagne mystérieuse, Saara, jeune femme libre, détonne au milieu de la pudeur générale. Autour d'elle gravitent un mendiant sourd-muet qui entend tout, un cheikh sage troublé par une passion interdite, et une administration corrompue qui veut construire un barrage. Beyrouk dénonce les injustices tout en célébrant la nature et la spiritualité du désert.",
    whyRead: [
      "Une héroïne libre dans une oasis traditionnelle.",
      "Un conte moderne, sensuel et engagé.",
      "La poésie du désert mauritanien.",
    ],
    year: 2022,
    publisher: "Elyzad",
    pages: 201,
    isbn: "9782492270840",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Nazi Boni
  livre({
    slug: "histoire-synthetique-de-l-afrique-resistante",
    title: "Histoire synthétique de l'Afrique résistante",
    subtitle: "Les réactions des peuples africains face aux influences extérieures",
    contributors: [boni],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "colonisation", "politique"],
    summary:
      "Homme politique voltaïque et auteur de Crépuscule des temps anciens, Nazi Boni a aussi voulu raconter l'histoire de l'Afrique du point de vue de ceux qui ont résisté. Cet essai passe en revue les réactions des peuples africains face aux influences venues de l'extérieur : invasions, traite, conquête coloniale. Rois, chefs de guerre et peuples entiers y apparaissent comme des acteurs de leur histoire. Le livre, préfacé par l'historien Jean Suret-Canale, est paru après la mort de l'auteur.",
    whyRead: [
      "L'histoire africaine racontée du côté des résistants.",
      "Le testament intellectuel de Nazi Boni, paru après sa mort.",
      "Préfacé par l'historien Jean Suret-Canale.",
    ],
    year: 1971,
    publisher: "Présence africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Olympe Bhêly-Quenum
  livre({
    slug: "le-chant-du-lac",
    title: "Le Chant du lac",
    contributors: [quenum],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "tradition", "independances"],
    summary:
      "Au bord d'un lac du Dahomey, les villageois vénèrent et redoutent les divinités des eaux : leur chant, dit-on, annonce la mort. Le roman met en scène l'affrontement entre croyances traditionnelles et esprit moderne, dans une atmosphère où le fantastique n'est jamais loin. Il a reçu le Grand prix littéraire d'Afrique noire.",
    whyRead: [
      "Grand prix littéraire d'Afrique noire 1966.",
      "Une atmosphère fantastique, entre croyances et modernité.",
      "Le Dahomey (actuel Bénin) et ses croyances du lac.",
    ],
    year: 1965,
    publisher: "Présence africaine",
    pages: 159,
    isbn: "2708705733",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1966 }],
  }),
  livre({
    slug: "liaison-d-un-ete",
    title: "Liaison d'un été",
    contributors: [quenum],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["spiritualite", "amour", "tradition"],
    summary:
      "Ce recueil réunit des récits et nouvelles d'Olympe Bhêly-Quenum, dont plusieurs ont été écrits avant ses romans. On y trouve déjà le grand thème de son œuvre : la présence du surnaturel dans la vie quotidienne, entre amours, croyances et destins. Une bonne entrée dans l'univers d'un écrivain béninois majeur.",
    whyRead: [
      "Les premiers récits d'un grand écrivain béninois.",
      "Le surnaturel au cœur de la vie quotidienne.",
      "Des textes courts, à découvrir un par un.",
    ],
    year: 1968,
    publisher: "SAGEREP",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "un-enfant-d-afrique",
    title: "Un enfant d'Afrique",
    contributors: [quenum],
    genre: "jeunesse",
    audience: "ado",
    themes: ["enfance", "famille", "tradition"],
    summary:
      "Ayao grandit au Dahomey dans une famille de cultivateurs propriétaires de leurs terres, entourée d'affection. Le roman suit son enfance, ses jeux, l'école, les travaux des champs et l'éducation qu'il reçoit des siens. Inspiré des souvenirs de l'auteur, ce livre écrit à l'origine pour les jeunes lecteurs veut montrer une Afrique loin des clichés de misère. Un récit sincère et lumineux sur l'enfance.",
    whyRead: [
      "Une enfance heureuse au Dahomey, loin des clichés.",
      "Écrit d'abord pour les lecteurs de 10 à 14 ans.",
      "Inspiré des souvenirs de l'auteur.",
    ],
    year: 1970,
    publisher: "Présence africaine",
    pages: 328,
    isbn: "2708706454",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-initie",
    title: "L'Initié",
    contributors: [quenum],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "tradition", "identite"],
    summary:
      "Le héros est un médecin formé en France. Mais il est aussi initié à une société de guérisseurs traditionnels. Le roman le place entre la science qu'il a apprise et les savoirs secrets qu'on lui a transmis, deux mondes qui ne parlent pas la même langue. Olympe Bhêly-Quenum explore les pouvoirs du vodou et la question de la magie, thème central de son œuvre.",
    whyRead: [
      "Un médecin entre science moderne et savoirs initiatiques.",
      "Le vodou et ses mystères au cœur du roman.",
      "Une œuvre importante de la littérature béninoise.",
    ],
    year: 1979,
    publisher: "Présence africaine",
    pages: 345,
    isbn: "2708707477",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-appels-du-vodou",
    title: "Les Appels du vodou",
    contributors: [quenum],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "tradition", "famille"],
    summary:
      "Une grande prêtresse du vodou vient de mourir à Cotonou. Pourtant, on la voit dans une rue de Gléxwé, sa ville natale, en conversation avec des parents morts depuis longtemps qui l'accueillent. Le roman s'ouvre sur ce dialogue des morts et plonge dans l'univers du vodou béninois, ses rites et ses mystères. Spécialiste de ces croyances, Olympe Bhêly-Quenum en fait la matière d'un roman ample.",
    whyRead: [
      "Une plongée dans le vodou du Bénin.",
      "Un roman qui fait dialoguer les vivants et les morts.",
      "Par un spécialiste de la culture vodou.",
    ],
    year: 1994,
    publisher: "L'Harmattan",
    pages: 335,
    isbn: "2738428754",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-naissance-d-abikou",
    title: "La Naissance d'Abikou",
    contributors: [quenum],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["spiritualite", "exil", "amour", "humour"],
    summary:
      "Ce recueil rassemble des textes écrits entre 1953 et 1984. Le récit qui donne son titre au livre est un dialogue plein d'humour entre une femme enceinte et l'enfant qu'elle porte. D'autres nouvelles évoquent le pouvoir des fétiches ou la chute d'un dictateur. Une série de cinq récits suit aussi un jeune Africain perdu dans la province française des années 1950, entre amitiés, amours et engagement politique.",
    whyRead: [
      "Trente ans d'écriture réunis en un volume.",
      "Un dialogue savoureux entre une mère et son enfant à naître.",
      "Un jeune Africain dans la France provinciale des années 1950.",
    ],
    year: 1998,
    publisher: "Phoenix Afrique",
    pages: 340,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "c-etait-a-tigony",
    title: "C'était à Tigony",
    contributors: [quenum],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "identite", "politique"],
    summary:
      "L'héroïne est une géophysicienne, brillante et indépendante. À Tigony, elle commence à remettre en question sa vie, ses choix et ses convictions, en particulier sur le capitalisme mondialisé. Ce que le lieu lui fait découvrir la conduit à revoir sa place dans le monde. Un roman tardif d'Olympe Bhêly-Quenum, traduit ensuite en anglais.",
    whyRead: [
      "Une héroïne scientifique, rare dans le roman africain.",
      "Une réflexion sur la mondialisation et ses dégâts.",
      "Un roman de la maturité d'Olympe Bhêly-Quenum.",
    ],
    year: 2000,
    publisher: "Présence africaine",
    pages: 385,
    isbn: "2708707051",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Sami Tchak
  livre({
    slug: "femme-infidele",
    title: "Femme infidèle",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "famille"],
    summary:
      "Entre Lomé et le nord du Togo, Talahatou est mariée de force à un homme polygame qu'elle n'aime pas. Refusant de se résigner, elle cherche à vivre selon ses propres désirs, au risque d'être jugée par tous. Ce premier roman de Sami Tchak, paru sous son vrai nom, Sadamba Tcha-Koura, est un plaidoyer pour la liberté des femmes africaines. On y trouve déjà l'audace qui marquera toute son œuvre.",
    whyRead: [
      "Le premier roman de Sami Tchak, encore signé de son vrai nom.",
      "Un plaidoyer pour la liberté des femmes au Togo.",
      "Les débuts d'une œuvre audacieuse.",
    ],
    year: 1988,
    publisher: "Nouvelles Éditions africaines",
    pages: 144,
    isbn: "2723609618",
    format: null,
    awards: [],
  }),
  livre({
    slug: "hermina",
    title: "Hermina",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "amour"],
    summary:
      "Hermina, lycéenne de seize ans à l'allure impérieuse, n'est qu'une des figures de ce roman. Autour d'elle et d'Heberto gravitent de nombreux personnages, exilés, artistes ratés, amants déçus, entre le Mexique, Cuba, Haïti, Paris et Miami. Sami Tchak compose une mosaïque de vies marquées par le désir, l'ambition et l'imposture. Ce roman foisonnant ouvre son grand cycle latino-américain.",
    whyRead: [
      "Le premier des romans latino-américains de Sami Tchak.",
      "Une mosaïque de personnages entre Caraïbes, Amériques et Paris.",
      "Un roman foisonnant sur le désir et l'exil.",
    ],
    year: 2003,
    publisher: "Gallimard",
    pages: 339,
    isbn: "2070768473",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-fete-des-masques",
    title: "La Fête des masques",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "amour", "humour"],
    summary:
      "Dans une ville d'Amérique latine que l'on ne nomme pas, Carlos, jeune homme hanté depuis l'enfance par un sentiment d'infériorité, raconte sa vie. Sa sœur Clara l'a déguisé en jeune fille, ce qui a changé son destin. Le roman s'ouvre sur un drame survenu chez Alberta, une femme dont le fils veut se venger. Entre désir et mort, Sami Tchak signe un court roman troublant, grinçant et tendre.",
    whyRead: [
      "Grand prix littéraire d'Afrique noire 2004.",
      "Un roman court, troublant et provocant.",
      "Le désir et l'identité au cœur du récit.",
    ],
    year: 2004,
    publisher: "Gallimard",
    pages: 104,
    isbn: "2070770389",
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 2004 }],
  }),
  livre({
    slug: "le-paradis-des-chiots",
    title: "Le Paradis des chiots",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "ville", "travail"],
    summary:
      "El Paraíso est un bidonville d'Amérique latine où une bande d'enfants abandonnés lutte pour survivre. Ernesto, quatorze ans, se prostitue pour quelques dollars afin de faire vivre sa mère. Autour de lui, Laura, Riki son pire ennemi et Juanito, le chef de bande qui terrorise tout le monde. Sami Tchak fait entendre leurs voix dans un roman dur et cru, sur la violence et l'humiliation.",
    whyRead: [
      "Prix Ahmadou-Kourouma 2007.",
      "Une plongée sans fard dans un bidonville latino-américain.",
      "Un roman polyphonique, porté par des voix d'enfants.",
    ],
    year: 2006,
    publisher: "Mercure de France",
    pages: 222,
    isbn: "2715226268",
    format: null,
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2007 }],
  }),
  livre({
    slug: "filles-de-mexico",
    title: "Filles de Mexico",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "identite"],
    summary:
      "À Mexico, Djibril Nawo, écrivain français d'origine togolaise, intrigue : certains le méprisent, d'autres sont fascinés par lui. Il arpente la ville, des bas-fonds aux beaux quartiers, et croise une foule de personnages étranges ou attachants. Sa rencontre avec une poétesse colombienne va compter. Entre réalisme et fantasmagorie, Sami Tchak parle d'inégalités sociales et raciales, de violence et de sexualité.",
    whyRead: [
      "Mexico vue par un écrivain africain en errance.",
      "Une tragi-comédie sur les inégalités et le racisme.",
      "Le troisième volet du cycle latino-américain de Tchak.",
    ],
    year: 2008,
    publisher: "Mercure de France",
    pages: 179,
    isbn: "9782715227842",
    format: null,
    awards: [],
  }),
  livre({
    slug: "al-capone-le-malien",
    title: "Al Capone le Malien",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "tradition"],
    summary:
      "René, journaliste français, est venu faire un reportage sur un balafon légendaire, à la frontière de la Guinée et du Mali. Il se retrouve coincé dans un hôtel de luxe à Bamako, où tout tourne autour d'un homme flamboyant surnommé Al Capone, le prince Edmond VII. Derrière lui se profile un célèbre escroc international. Sami Tchak signe une satire où l'argent, le sexe et le pouvoir mènent la danse.",
    whyRead: [
      "Le retour de Sami Tchak en Afrique après le cycle latino-américain.",
      "Une satire de l'argent roi et des escrocs de haut vol.",
      "Le choc entre tradition mandingue et bling-bling.",
    ],
    year: 2011,
    publisher: "Mercure de France",
    pages: 297,
    isbn: "9782715231788",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-ethnologue-et-le-sage",
    title: "L'Ethnologue et le Sage",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["tradition", "spiritualite", "identite"],
    summary:
      "Dans le petit village togolais de Tèdi, un imam enseigne l'islam aux paysans tout en respectant leurs croyances anciennes. Un ethnologue français, Maurice Boyer, vient étudier le village. Quand des ignames sont volées, l'imam organise une épreuve : chacun doit jurer sur le Coran qu'il n'est pas le voleur. Sami Tchak observe avec malice les rapports entre le savant venu d'ailleurs et ceux qu'il étudie.",
    whyRead: [
      "Un roman court sur le regard de l'ethnologue.",
      "Un village togolais entre islam et croyances anciennes.",
    ],
    year: 2013,
    publisher: "Odem",
    pages: 127,
    isbn: "9782919487677",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-couleur-de-l-ecrivain",
    title: "La Couleur de l'écrivain",
    contributors: [tchak],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "humour", "ecole"],
    summary:
      "Sami Tchak présente ce livre comme une « comédie littéraire ». À travers dialogues, souvenirs et réflexions, il s'interroge sur la position inconfortable d'un écrivain noir dans le monde des lettres. Il parle des auteurs qui l'ont formé, de ses contemporains, de l'Afrique d'aujourd'hui et de ce qu'on attend d'un écrivain africain. Un livre entre fiction et confession, plein d'humour et de liberté.",
    whyRead: [
      "Un écrivain africain parle librement de son métier.",
      "Entre essai, autobiographie et comédie.",
      "Pour mieux comprendre l'œuvre de Sami Tchak.",
    ],
    year: 2014,
    publisher: "La Cheminante",
    pages: 221,
    isbn: "9782917598863",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ainsi-parlait-mon-pere",
    title: "Ainsi parlait mon père",
    contributors: [tchak],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "tradition", "ecole"],
    summary:
      "Le père de Sami Tchak était forgeron dans un village du Togo. Avant les livres et les stylos, il y eut pour l'enfant la forge, le charbon, le soufflet, l'enclume et surtout les paroles de ce père. Pendant plus de quarante ans, jusqu'à sa mort en 2003, le fils l'a écouté. Ce livre rassemble ces « leçons de la forge », pleines de sagesse, d'humilité et d'amour.",
    whyRead: [
      "Un bel hommage d'un fils à son père forgeron.",
      "Des leçons de vie simples et profondes.",
      "Un livre intime, loin des romans provocants de l'auteur.",
    ],
    year: 2018,
    publisher: "JC Lattès",
    pages: 267,
    isbn: "9782709661829",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-fables-du-moineau",
    title: "Les Fables du moineau",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["contes", "spiritualite", "identite"],
    summary:
      "Un volcan se réveille, des œufs éclosent et libèrent moineaux, poules, vipères, tortues, chauves-souris et agoutis. Dans ce livre singulier, Sami Tchak se fait fabuliste sans être moraliste. Les animaux et les hommes y dialoguent, les récits courts s'enchaînent comme des rêves. Le texte est suivi d'une postface de la romancière mauricienne Ananda Devi.",
    whyRead: [
      "Un livre de fables étrange et poétique.",
      "Prix La Renaissance française 2020.",
      "Postface d'Ananda Devi.",
    ],
    year: 2020,
    publisher: "Gallimard",
    pages: 139,
    isbn: "9782072857454",
    format: null,
    awards: [{ name: "Prix La Renaissance française", year: 2020 }],
  }),
  livre({
    slug: "le-continent-du-tout-et-du-presque-rien",
    title: "Le Continent du Tout et du presque Rien",
    contributors: [tchak],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "colonisation", "ecole"],
    summary:
      "Maurice Boyer, fils de paysans français, devient étudiant en ethnologie à la Sorbonne. Il part au Togo pour ses recherches de doctorat, sur les traces de son maître Georges Balandier, et y passe deux ans dans un village. Cette rencontre devient le grand bouleversement de sa vie. À travers lui, Sami Tchak interroge la façon dont l'Occident a regardé, inventé et raconté l'Afrique.",
    whyRead: [
      "Prix Ivoire 2022.",
      "Une réflexion romanesque sur le regard occidental posé sur l'Afrique.",
      "Un ethnologue français transformé par un village togolais.",
    ],
    year: 2021,
    publisher: "JC Lattès",
    pages: 314,
    isbn: "9782709662635",
    format: null,
    awards: [{ name: "Prix Ivoire", year: 2022 }],
  }),
  livre({
    slug: "profaner-ananda",
    title: "Profaner Ananda",
    contributors: [tchak, { role: "auteur", name: "Annie Ferret", authorSlug: null }],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "spiritualite"],
    summary:
      "Sami Tchak et Annie Ferret, tous deux grands lecteurs d'Ananda Devi, écrivent ensemble un livre sur la romancière mauricienne, autrice du Sari vert. Entre roman et essai, ils croisent leurs regards sur son œuvre et sur la figure qu'elle est devenue pour eux. Leur texte, présenté comme un voyage initiatique, célèbre l'écriture, la vie et la mort qui l'accompagne. Ananda Devi elle-même y voit l'enfant de leurs trois écritures.",
    whyRead: [
      "Un hommage original à la romancière Ananda Devi.",
      "Écrit à quatre mains, entre essai et récit.",
      "Pour les lecteurs curieux des coulisses de l'écriture.",
    ],
    year: 2025,
    publisher: "Gallimard",
    pages: 121,
    isbn: "9782073104502",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Kossi Efoui
  livre({
    slug: "la-polka",
    title: "La Polka",
    contributors: [efoui],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "guerre", "politique"],
    summary:
      "Dans une ville africaine sans nom, des « événements » terribles ont tout changé. Avant, on dansait la rumba au Bar M, où l'arrivée de Nahéma do Nacimento avait fait sensation. Aujourd'hui, la ville a perdu son rythme et sa musique. À partir d'une vieille carte postale, le narrateur remonte le fil des souvenirs. Le premier roman de Kossi Efoui, énigmatique et poétique, parle des lendemains de violence.",
    whyRead: [
      "Le premier roman de Kossi Efoui.",
      "Une ville fantôme après la violence, entre rêve et mémoire.",
      "Une écriture poétique et déroutante.",
    ],
    year: 1998,
    publisher: "Seuil",
    pages: 156,
    isbn: "2020327953",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-fabrique-de-ceremonies",
    title: "La Fabrique de cérémonies",
    contributors: [efoui],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "exil", "humour", "ville"],
    summary:
      "Edgar Fall, ancien étudiant en Union soviétique devenu traducteur à Paris, accepte une mission douteuse : partir en repérage en Afrique de l'Ouest pour un magazine de voyages à sensations. Il se retrouve à Lomé, en partie inondée et tenue par des milices. Son voyage mêle son histoire personnelle aux drames du continent. Avec humour noir et inventivité, Kossi Efoui raconte les absurdités de la mondialisation.",
    whyRead: [
      "Grand prix littéraire d'Afrique noire 2002.",
      "Un humour noir et une langue très inventive.",
      "Lomé et l'Afrique de l'Ouest vues par un revenant.",
    ],
    year: 2001,
    publisher: "Seuil",
    pages: 251,
    isbn: "2020472996",
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 2002 }],
  }),
  livre({
    slug: "l-ombre-des-choses-a-venir",
    title: "L'Ombre des choses à venir",
    contributors: [efoui],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "famille", "politique"],
    summary:
      "Le temps d'une nuit, un jeune homme raconte son enfance, dans un monde réduit aux dimensions d'une cellule. Il évoque une guerre sans fin, où les fausses paroles s'allient à la violence des armes. Son père, sorti de prison et devenu malgré lui une sorte de héros, a préféré fuir. Kossi Efoui poursuit l'exploration commencée dans Solo d'un revenant, dans un récit sombre et visionnaire.",
    whyRead: [
      "Un roman bref et intense sur la guerre et la mémoire.",
      "Une relation père-fils au cœur de l'histoire.",
      "Dans la lignée de Solo d'un revenant.",
    ],
    year: 2011,
    publisher: "Seuil",
    pages: 157,
    isbn: "9782020990974",
    format: null,
    awards: [],
  }),
  livre({
    slug: "cantique-de-l-acacia",
    title: "Cantique de l'acacia",
    contributors: [efoui],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "spiritualite"],
    summary:
      "Trois générations de femmes en Afrique d'aujourd'hui. Io-Anna a fui l'oppression des hommes à bicyclette, avec Sunday, un colporteur. Leur fille, Joyce, est arrivée mystérieusement sur un radeau. Sous l'acacia, arbre de l'innocence, Kossi Efoui compose une fable réaliste et politique, animiste et poétique, sur le courage de vivre. Ici, dit-on, il faut trois pour faire un enfant : l'homme, la femme et l'Invisible.",
    whyRead: [
      "Une saga de femmes, entre réalisme et merveilleux.",
      "Un hymne au courage de vivre.",
      "L'écriture poétique de Kossi Efoui à son meilleur.",
    ],
    year: 2017,
    publisher: "Seuil",
    pages: 284,
    isbn: "9782021377132",
    format: null,
    awards: [],
  }),
  livre({
    slug: "une-magie-ordinaire",
    title: "Une magie ordinaire",
    contributors: [efoui],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "femmes", "identite"],
    summary:
      "Un appel téléphonique apprend au narrateur que sa mère est hospitalisée à Lomé, dans un état grave. Il se souvient d'elle : une femme joyeuse et courageuse, qui chantait pour conjurer le malheur, aimait les beaux habits et les bijoux, et lui avait dit un jour : « Va vivre ailleurs et ne reviens pas. » De ce portrait d'une mère dans la pauvreté naît aussi le récit de la vocation d'un écrivain.",
    whyRead: [
      "Un portrait de mère bouleversant et lumineux.",
      "Le livre le plus personnel de Kossi Efoui.",
      "Sur ce qui fait naître un écrivain.",
    ],
    year: 2023,
    publisher: "Seuil",
    pages: 156,
    isbn: "9782021524109",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-carrefour",
    title: "Le Carrefour",
    contributors: [efoui],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "guerre"],
    summary:
      "À un carrefour, quatre personnages très différents par leurs attitudes, leurs visions et leurs expériences se rencontrent et s'affrontent. Kossi Efoui a écrit cette pièce à la fin des années 1980 pour dénoncer les mécanismes de répression des régimes totalitaires, alors que le Togo vivait sous la dictature. C'est sa première pièce, celle qui a lancé sa carrière.",
    whyRead: [
      "La première pièce de Kossi Efoui, celle qui l'a fait connaître.",
      "Un théâtre politique né sous la dictature togolaise.",
      "Une œuvre clé du renouveau du théâtre africain.",
    ],
    year: 1990,
    publisher: "L'Harmattan",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "recuperations",
    title: "Récupérations",
    contributors: [efoui],
    genre: "theatre",
    audience: "adulte",
    themes: ["ville", "humour", "travail"],
    summary:
      "Un journaliste de télévision prépare une émission choc sur les exclus : sans-abri, petits débrouillards, habitants menacés d'expulsion. Pour l'occasion, il reconstitue un quartier pauvre sur un plateau et y invite ceux qui vont être chassés. Leur précarité devient un spectacle. Dans cette pièce satirique, Kossi Efoui dénonce le sensationnalisme des médias et la façon dont on exploite la misère des autres.",
    whyRead: [
      "Une satire féroce des médias et de la télé-réalité.",
      "Une pièce courte, facile à monter.",
      "Le théâtre engagé de Kossi Efoui.",
    ],
    year: 1992,
    publisher: "Lansman",
    pages: 37,
    isbn: "9782872827411",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-malaventure",
    title: "La Malaventure",
    contributors: [efoui],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "guerre"],
    summary:
      "Un montreur de marionnettes, une femme qui attend, un certain Edgar Fall et une mystérieuse Darling V. se croisent dans un monde étouffé par la peur. Chacun cache quelque chose, et leurs échanges forment un ballet de non-dits. La pièce plonge dans l'univers de l'oppression et de la résistance, avec une écriture poétique où la mémoire se dérobe.",
    whyRead: [
      "Une pièce énigmatique sur la peur et l'oppression.",
      "On y croise Edgar Fall, futur héros de La Fabrique de cérémonies.",
      "Une langue poétique, entre rêve et cauchemar.",
    ],
    year: 1993,
    publisher: "Lansman",
    pages: 33,
    isbn: "9782872827428",
    format: null,
    awards: [],
  }),
  livre({
    slug: "oublie-suivi-de-voisins-anonymes",
    title: "Oublie !",
    subtitle: "suivi de Voisins anonymes",
    contributors: [efoui],
    genre: "theatre",
    audience: "jeunesse",
    themes: ["enfance", "contes", "identite"],
    summary:
      "Dans Oublie !, Enfant porte en lui l'image d'un homme avec des cornes de zébu sur la tête, que personne ne veut accepter. Avec La Sauvage, il entreprend un voyage initiatique à travers ses émotions et ses peurs, vers une case vide. Cette fable philosophique s'adresse aux enfants comme aux adultes. Voisins anonymes, courte ballade de cage d'escalier, met en scène un drôle d'oiseau qui résiste aux règlements et aux contraintes.",
    whyRead: [
      "Un conte philosophique pour la scène, dès l'enfance.",
      "Deux pièces courtes, poétiques et drôles.",
      "Une porte d'entrée dans le théâtre de Kossi Efoui.",
    ],
    year: 2011,
    publisher: "Lansman",
    pages: 33,
    isbn: "9782872828463",
    format: null,
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "le-regard-du-roi", "dramouss", "le-maitre-de-la-parole", "les-crapauds-brousse", "les-ecailles-du-ciel", "un-reve-utile",
  "un-attieke-pour-elgass", "pelourinho", "cinema", "l-aine-des-orphelins", "peuls", "le-terroriste-noir", "les-coqs-cubains-chantent-a-minuit",
  "bled", "saharienne-indigo", "la-tribu-des-gonzesses", "sikasso-ou-la-derniere-citadelle-suivi-de-chaka", "monne-outrages-et-defis",
  "en-attendant-le-vote-des-betes-sauvages", "quand-on-refuse-on-dit-non", "le-diseur-de-verite", "yacouba-chasseur-africain", "laterite",
  "a-vol-d-oiseau", "le-royaume-aveugle", "champs-de-bataille-et-d-amour", "a-mi-chemin", "l-ombre-d-imana", "loin-de-mon-pere",
  "en-compagnie-des-hommes", "je-remercie-la-nuit", "la-chanson-de-la-vie", "mamy-wata-et-le-monstre", "le-seigneur-de-la-danse",
  "le-grain-de-mais-magique", "grand-mere-nanan", "le-bel-oiseau-et-la-pluie", "masque-raconte-moi",
  "ayanda-la-petite-fille-qui-ne-voulait-pas-grandir", "nelson-mandela-non-a-l-apartheid", "leopold-sedar-senghor-le-poete-des-paroles-qui-durent",
  "graca-machel-championne-des-enfants", "le-voyage-de-yao", "afrique-debout", "legendes-africaines", "la-ronde-des-jours", "un-negre-a-paris",
  "patron-de-new-york", "hommes-de-tous-les-continents", "la-ville-ou-nul-ne-meurt", "monsieur-thogo-gnini", "beatrice-du-congo",
  "les-voix-dans-le-vent", "iles-de-tempete", "opinions-d-un-negre", "carnet-de-prison", "les-belles-histoires-de-kacou-ananze", "camarade-papa",
  "black-manoo", "cocoaians-naissance-d-une-nation-chocolat", "les-portes", "et-le-ciel-a-oublie-de-pleuvoir", "nouvelles-du-desert",
  "le-griot-de-l-emir", "je-suis-seul", "parias", "le-silence-des-horizons", "saara", "histoire-synthetique-de-l-afrique-resistante",
  "le-chant-du-lac", "liaison-d-un-ete", "un-enfant-d-afrique", "l-initie", "les-appels-du-vodou", "la-naissance-d-abikou", "c-etait-a-tigony",
  "femme-infidele", "hermina", "la-fete-des-masques", "le-paradis-des-chiots", "filles-de-mexico", "al-capone-le-malien", "l-ethnologue-et-le-sage",
  "la-couleur-de-l-ecrivain", "ainsi-parlait-mon-pere", "les-fables-du-moineau", "le-continent-du-tout-et-du-presque-rien", "profaner-ananda",
  "la-polka", "la-fabrique-de-ceremonies", "l-ombre-des-choses-a-venir", "cantique-de-l-acacia", "une-magie-ordinaire", "le-carrefour",
  "recuperations", "la-malaventure", "oublie-suivi-de-voisins-anonymes",
];
