/**
 * Lot 09 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * BD : nouveaux auteurs (Diantantu, Danngar, Viodé, Paluku, Njock, Kamgang, Tounkara, Mongo Sisé, Al'Mata,
 * Kingue Epanya, Thembo Kash, Kojélé, KHP, N'Guessan, Sonon, Dwa, Groud). ISBN et pages relevés dans le catalogue
 * de la BnF ; résumés appuyés sur les notices de la BnF, de Takam Tikou (BnF-CNLJ) et des éditeurs.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage" | "kind">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

/** BD : genre « bd », format album. */
const bd = (b: Omit<Saisie, "genre" | "format" | "kind">): Book => livre({ kind: "bd", genre: "bd", format: "album", ...b });

const auteur = (name: string, authorSlug: string | null) => ({ role: "auteur" as const, name, authorSlug });
const scenario = (name: string, authorSlug: string | null) => ({ role: "scenariste" as const, name, authorSlug });
const dessin = (name: string, authorSlug: string | null) => ({ role: "dessinateur" as const, name, authorSlug });
/** Auteur complet d'une BD : scénario et dessin. */
const complet = (name: string, authorSlug: string) => [scenario(name, authorSlug), dessin(name, authorSlug)];

const EDIMO = scenario("Christophe Ngalle Edimo", "christophe-ngalle-edimo");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Serge Diantantu
  bd({
    slug: "simon-kimbangu-la-voix-du-peuple-opprime",
    title: "Simon Kimbangu, t. 1",
    subtitle: "La Voix du peuple opprimé",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["colonisation", "spiritualite", "histoire"],
    summary:
      "Premier volet de la grande biographie dessinée que Serge Diantantu consacre à Simon Kimbangu, né en 1887 à Nkamba, dans le Bas-Congo. L'album replace le futur prophète dans le Congo belge de son enfance, entre villages, missions et administration coloniale, et suit la naissance de sa prédication, qui attire très vite des foules. Inquiet de ce mouvement, le pouvoir colonial voit en lui une menace. L'auteur, qui a grandi dans cette région, s'appuie sur des archives et sur la mémoire des anciens pour raconter une histoire vraie mais mal connue.",
    whyRead: [
      "Le début d'une fresque historique sur une grande figure de résistance congolaise.",
      "Un regard sur le Congo belge raconté par un auteur né dans la région.",
      "Une BD d'histoire plus qu'une BD religieuse, comme l'auteur le revendique.",
    ],
    year: 2002,
    publisher: "Mandala",
    pages: 48,
    isbn: "9782951901704",
    outOfPrint: true,
    awards: [],
  }),
  bd({
    slug: "simon-kimbangu-lipanda-dia-zole",
    title: "Simon Kimbangu, t. 3",
    subtitle: "Lipanda dia Zole, la liberté à jamais",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["colonisation", "spiritualite", "histoire", "independances"],
    summary:
      "En 1921, Simon Kimbangu, arrêté par l'administration belge, est envoyé en relégation : un long voyage le mène du Bas-Congo jusqu'à une prison du Katanga, à l'autre bout du pays. Pendant ce temps, des milliers de ses fidèles sont déportés à leur tour dans des camps. Autour de ce destin, l'album déroule trente ans d'histoire du Congo : écoles coloniales, visite royale, Seconde Guerre mondiale, puis la marche vers l'indépendance. Ce dernier tome peut se lire seul.",
    whyRead: [
      "Une fresque dense qui couvre l'histoire du Congo jusqu'à l'indépendance.",
      "Le portrait d'un défenseur de la non-violence, emprisonné pendant trente ans.",
      "Un album richement documenté, avec sa bibliographie.",
    ],
    year: 2010,
    publisher: "Mandala",
    pages: 50,
    isbn: "9782952664776",
    awards: [],
  }),
  bd({
    slug: "la-petite-djily-et-mere-mamou",
    title: "La Petite Djily et Mère Mamou",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["enfance", "famille", "ville"],
    summary:
      "À Kinshasa, la petite Djily traîne en rentrant de l'école et redoute les vacances. Chez elle l'attend Mère Mamou, la nouvelle épouse de son père, qui la maltraite pendant que le père est absent. Serge Diantantu aborde sans détour un sujet tabou, la violence faite aux enfants dans les familles recomposées. Il le fait par une vraie histoire, vivante et bien ancrée dans le quotidien kinois, qui parle aux enfants comme aux adultes.",
    whyRead: [
      "Un sujet rarement abordé, traité avec justesse et sans lourdeur.",
      "Kinshasa dessinée au plus près de la vie des familles.",
      "Une BD remarquée bien au-delà du Congo.",
    ],
    year: 2008,
    publisher: "Diantantu éditions",
    pages: 48,
    isbn: "9782953132014",
    awards: [],
  }),
  livre({
    slug: "femme-noire-d-afrique-d-amerique-et-des-antilles",
    title: "Femme noire d'Afrique, d'Amérique et des Antilles",
    contributors: [auteur("Serge Diantantu", "serge-diantantu")],
    genre: "essai",
    audience: "ado",
    themes: ["femmes", "histoire", "identite"],
    summary:
      "Un grand album illustré qui rend hommage aux femmes noires qui ont marqué l'histoire, d'Afrique, des Amériques et des Antilles. De la reine Nzinga à Rosa Parks, en passant par Kimpa Vita, Maryse Condé ou Christiane Taubira, chacune a droit à une courte biographie et à un ou deux portraits peints en couleurs vives. Serge Diantantu reprend ici, en la retravaillant, une première galerie publiée en 2008. Un livre à feuilleter pour découvrir des parcours souvent oubliés.",
    whyRead: [
      "Une galerie de destins de femmes, des reines d'Afrique aux militantes d'aujourd'hui.",
      "Des portraits lumineux, faciles à feuilleter en famille.",
      "Un bon point de départ pour des recherches plus poussées.",
    ],
    year: 2011,
    publisher: "Caraïbéditions",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
  }),
  bd({
    slug: "bulambemba",
    title: "Mémoire de l'esclavage, t. 1",
    subtitle: "Bulambemba",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["esclavage", "histoire", "colonisation"],
    summary:
      "On pense souvent à Gorée quand on évoque la traite des Africains. Ce premier tome nous emmène sur une autre île, Bulambemba, à l'embouchure du fleuve Congo, où tout a commencé quatre siècles durant. Après avoir présenté les différentes traites, l'album suit l'arrivée des navigateurs portugais de Diogo Cão au XVe siècle et la mise en place pas à pas d'un système effroyable. Grandes cases, cartes et explications sur les mots de l'époque accompagnent le récit.",
    whyRead: [
      "Un épisode méconnu des débuts de la traite, en Afrique centrale.",
      "Une BD documentaire claire, idéale pour aborder l'histoire en classe.",
      "Un album qui s'est vendu à dix mille exemplaires.",
    ],
    year: 2010,
    publisher: "Caraïbéditions",
    pages: 44,
    isbn: "9782917623152",
    awards: [],
  }),
  bd({
    slug: "en-naviguant-vers-les-indes",
    title: "Mémoire de l'esclavage, t. 2",
    subtitle: "En naviguant vers les Indes",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["esclavage", "histoire", "colonisation"],
    summary:
      "À la fin du XVe siècle, les navigateurs portugais cherchent la route des Indes. Bartolomeu Dias franchit le cap de Bonne-Espérance, Diogo Cão revient vers le royaume Kongo, et Christophe Colomb aborde les îles d'un Nouveau Monde. Entre récit et pages documentaires, l'album montre les premiers échanges avec le roi du Kongo, les pactes d'amitié, puis les manipulations qui permettent à la déportation de s'installer presque sans bruit.",
    whyRead: [
      "Les premiers contacts entre l'Europe et le royaume Kongo, racontés en détail.",
      "Une alternance réussie entre bande dessinée et pages documentaires.",
      "La suite directe de Bulambemba.",
    ],
    year: 2011,
    publisher: "Caraïbéditions",
    pages: 46,
    isbn: "9782917623343",
    awards: [],
  }),
  bd({
    slug: "l-embarquement-de-bois-d-ebene",
    title: "Mémoire de l'esclavage, t. 3",
    subtitle: "L'Embarquement de bois d'ébène",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["esclavage", "histoire", "colonisation"],
    summary:
      "Après les premières découvertes, le commerce des captifs s'organise. Ce troisième tome montre comment les puissances européennes, Portugais et Espagnols d'abord, puis d'autres nations, mettent sur pied le commerce triangulaire. Serge Diantantu décrit les rois africains face aux marchands, tantôt dupés, tantôt associés malgré eux, tantôt révoltés, et la mécanique de la capture et de l'embarquement vers les Amériques.",
    whyRead: [
      "Le commerce triangulaire expliqué avec précision.",
      "Un regard nuancé sur le rôle des souverains africains.",
      "Une série documentaire saluée par la Bibliothèque nationale de France.",
    ],
    year: 2012,
    publisher: "Caraïbéditions",
    pages: 45,
    isbn: "9782917623435",
    awards: [],
  }),
  bd({
    slug: "ile-de-goree",
    title: "Mémoire de l'esclavage, t. 4",
    subtitle: "Île de Gorée",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["esclavage", "histoire", "colonisation"],
    summary:
      "Le quatrième tome de la série s'arrête sur l'île de Gorée, au large de Dakar, devenue le symbole de la traite atlantique. Serge Diantantu y poursuit son travail de mémoire, entre récit et documentation, pour montrer ce que fut ce lieu de passage et comment s'y organisait le départ des captifs. Comme les autres volumes, l'album se veut un support pour enseigner l'esclavage, sans fiction romancée, et rappelle que d'autres formes d'esclavage existent encore aujourd'hui.",
    whyRead: [
      "Gorée racontée par un auteur qui a fait de la mémoire de la traite son combat.",
      "Un album très documenté, pensé pour les élèves comme pour leurs parents.",
      "Un dessin soigné et des couleurs vives.",
    ],
    year: 2014,
    publisher: "Caraïbéditions",
    pages: 46,
    isbn: "9782917623701",
    awards: [],
  }),
  bd({
    slug: "colonies-des-antilles-et-de-l-ocean-indien",
    title: "Mémoire de l'esclavage, t. 5",
    subtitle: "Colonies des Antilles et de l'océan Indien",
    contributors: complet("Serge Diantantu", "serge-diantantu"),
    audience: "ado",
    themes: ["esclavage", "histoire", "colonisation"],
    summary:
      "Dernier tome de la série, cet album suit les captifs de l'autre côté de l'océan, dans les colonies des Antilles et de l'océan Indien. Le travail dans les plantations, l'exploitation et les résistances sont au cœur du récit, qui mène jusqu'à l'abolition de l'esclavage en France en 1848. Serge Diantantu n'oublie pas les traites orientales et garde le même souci du détail historique, avec un trait proche de la ligne claire.",
    whyRead: [
      "La conclusion d'une série documentaire unique en bande dessinée.",
      "Le lien entre l'Afrique, les Antilles et l'océan Indien.",
      "Un outil précieux pour transmettre cette histoire aux plus jeunes.",
    ],
    year: 2015,
    publisher: "Caraïbéditions",
    pages: 48,
    isbn: "9782917623916",
    awards: [],
  }),
  bd({
    slug: "felix-eboue-heros-de-la-france-libre",
    title: "Félix Éboué, héros de la France libre",
    contributors: [scenario("Serge Diantantu", "serge-diantantu"), dessin("Jean-Claude Degras", null)],
    audience: "ado",
    themes: ["colonisation", "histoire", "guerre"],
    summary:
      "Né à Cayenne en 1884, Félix Éboué part étudier à Bordeaux puis à Paris avant d'entamer une longue carrière d'administrateur colonial en Afrique, à commencer par le Congo. Devenu gouverneur, il est en 1940 l'un des premiers à rallier la France libre du général de Gaulle. À travers sa vie, cette BD retrace l'histoire des colonies françaises de l'aube du XXe siècle jusqu'aux années 1950, avec des planches claires et précises.",
    whyRead: [
      "Le portrait d'un homme dont on connaît le nom sans toujours savoir pourquoi.",
      "Une page d'histoire de la Seconde Guerre mondiale vue d'Afrique.",
      "Une lecture fluide, accessible dès 10 ans.",
    ],
    year: 2016,
    publisher: "Caraïbéditions",
    pages: 63,
    isbn: "9782373110098",
    awards: [],
  }),

  // ------------------------------------------------------------------ Adjim Danngar
  bd({
    slug: "mamie-denis-evadee-de-la-maison-de-retraite",
    title: "Mamie Denis",
    subtitle: "Évadée de la maison de retraite",
    contributors: [EDIMO, dessin("Adjim Danngar", "adjim-danngar")],
    audience: "adulte",
    themes: ["humour", "exil", "identite"],
    summary:
      "Mamie Denis, vieille Parisienne du 9e arrondissement, a mauvais caractère, adore les procès et ne cache pas ses préjugés racistes. Placée en maison de retraite sous la pression des services sociaux et d'un neveu qui lorgne l'héritage, elle décide de reprendre sa vie en main. Son plan : s'enfuir et finir ses jours en Afrique, avec l'aide de ses anciens voisins africains, qui ont gardé pour elle le respect dû aux aînés malgré les débuts difficiles. Une comédie qui retourne les clichés sur l'immigration.",
    whyRead: [
      "Une héroïne âgée, insupportable et pourtant attachante.",
      "Une satire tendre du racisme ordinaire et de la solitude des anciens.",
      "Le premier album du dessinateur tchadien Adjim Danngar.",
    ],
    year: 2017,
    publisher: "L'Harmattan",
    pages: 116,
    isbn: "9782343101309",
    awards: [],
  }),
  bd({
    slug: "djarabane-au-petit-marche-des-amours-perdues",
    title: "Djarabane, t. 1",
    subtitle: "Au petit marché des amours perdues",
    contributors: complet("Adjim Danngar", "adjim-danngar"),
    audience: "adulte",
    themes: ["enfance", "guerre", "politique", "exil"],
    summary:
      "Sarh, dans le sud du Tchad, en 1984. Kandji a sept ans quand il découvre, accrochée au mur du salon, une peinture dont les couleurs l'éblouissent : il sera peintre. Mais le pays traverse alors l'une des périodes les plus violentes de son histoire, et les rêves d'un enfant pèsent peu face à la guerre et à la peur. Djarabane, qui signifie « que faire ? » en langue sara, est un long récit sur l'exil et sur la place des rêves d'enfant dans un pays en crise.",
    whyRead: [
      "Un grand roman graphique sur le Tchad des années 1980, rarement raconté.",
      "Une histoire d'enfance et de vocation, portée par un héros de sept ans.",
      "Près de deux cents pages en couleurs, chez Delcourt.",
    ],
    year: 2023,
    publisher: "Delcourt",
    pages: 197,
    isbn: "9782413044017",
    awards: [],
  }),

  // ------------------------------------------------------------------ Didier Viodé
  bd({
    slug: "etranger-sans-rendez-vous",
    title: "Étranger sans rendez-vous, t. 1",
    contributors: complet("Didier Viodé", "didier-viode"),
    audience: "adulte",
    themes: ["exil", "identite"],
    summary:
      "Un jeune Ivoirien a quitté son pays, qui va mal, et se retrouve en France, perdu dans les rues de Besançon. Un jour, sa route croise celle d'un inconnu. De cette rencontre naît une longue conversation, où les deux hommes confrontent leur manière de voir le monde, au-delà du noir et du blanc. Didier Viodé, lui-même installé en France après ses études d'art, signe un premier album à l'encre de Chine, tout en retenue.",
    whyRead: [
      "Une rencontre entre deux inconnus, qui interroge le regard porté sur l'étranger.",
      "Un dessin à l'encre délicat, par un plasticien reconnu.",
      "Le premier album de Didier Viodé.",
    ],
    year: 2011,
    publisher: "Bidon rouillé",
    pages: 45,
    isbn: "9782954075808",
    awards: [],
  }),
  bd({
    slug: "vive-la-corruption",
    title: "Vive la corruption",
    contributors: complet("Didier Viodé", "didier-viode"),
    audience: "adulte",
    themes: ["humour", "politique", "ville"],
    summary:
      "Yao est un jeune peintre autodidacte qui vit dans un paisible pays d'Afrique et ne vend presque rien. Sincère et un peu naïf, il se heurte à chaque pas à la corruption, à l'indifférence et parfois à la cruauté de ses concitoyens. Dans une société où l'argent décide de tout, chacun veut sa part du gâteau, du policier au fonctionnaire. Une suite d'histoires courtes et drôles dont le malheureux Yao est toujours la victime.",
    whyRead: [
      "Une satire mordante d'un mal qui touche tout le continent.",
      "Des gags courts et efficaces, faciles à lire.",
      "La première apparition de Yao, héros de Didier Viodé.",
    ],
    year: 2011,
    publisher: "L'Harmattan",
    pages: 53,
    isbn: "9782296136939",
    awards: [],
  }),
  bd({
    slug: "yao-visa-refuse",
    title: "Yao : visa refusé",
    contributors: complet("Didier Viodé", "didier-viode"),
    audience: "adulte",
    themes: ["humour", "exil", "travail"],
    summary:
      "Yao est revenu, toujours peintre engagé, toujours sans le sou, dans une ville où le marché de l'art n'existe pas. Son rêve : partir exposer ses toiles en Occident. Encore faut-il obtenir un visa. Au fil d'histoires courtes, l'album aligne les obstacles, les files d'attente et les absurdités administratives qu'il rencontre. Didier Viodé s'est inspiré des débats sur l'« immigration choisie » pour dénoncer, avec humour, l'inégalité devant les visas et la précarité des artistes africains.",
    whyRead: [
      "L'envers des visas « compétences et talents », raconté avec un humour grinçant.",
      "Un regard d'artiste sur la vie des artistes en Afrique.",
      "Se lit seul, même sans connaître Vive la corruption.",
    ],
    year: 2019,
    publisher: "L'Harmattan",
    pages: 77,
    isbn: "9782343173399",
    awards: [],
  }),

  // ------------------------------------------------------------------ Hallain Paluku
  bd({
    slug: "missy",
    title: "Missy",
    contributors: [scenario("Benoît Rivière", null), dessin("Hallain Paluku", "hallain-paluku")],
    audience: "adulte",
    themes: ["femmes", "identite", "amour"],
    summary:
      "La nuit, Missy est l'étoile d'un cabaret : ses formes généreuses font sa gloire sur scène. Le jour, elle redevient une grosse femme que personne ne regarde. Lassée de n'être qu'un objet de fantasme pour les hommes, elle décide de maigrir, au risque de perdre ce qui fait d'elle une vedette. Hallain Paluku a inventé ce personnage de femme ronde, dessinée sans visage, dès 1999 à Kinshasa, avant que l'album ne paraisse en France.",
    whyRead: [
      "Une héroïne originale qui interroge le regard porté sur le corps des femmes.",
      "Un dessin rond et expressif, sans visage, très reconnaissable.",
      "Le premier album d'un dessinateur congolais devenu pionnier de l'animation en lingala.",
    ],
    year: 2006,
    publisher: "La Boîte à bulles",
    pages: 78,
    isbn: "9782849530467",
    awards: [],
  }),
  bd({
    slug: "rugbill",
    title: "Rugbill, t. 1",
    subtitle: "Les Dessous de la mêlée",
    contributors: [scenario("Faro", null), dessin("Hallain Paluku", "hallain-paluku")],
    audience: "ado",
    themes: ["humour"],
    summary:
      "À Quinté, petit village du Sud-Ouest, le sport roi, c'est le rugby. Rugbill est le capitaine de l'équipe locale, entouré de coéquipiers hauts en couleur comme Bourrepif, le plus costaud de la bande. Autour du terrain s'agitent l'entraîneur, sa femme, le kiné, le curé et les supporters. Un album de gags sur la vie d'un club de village, où la troisième mi-temps compte presque autant que le match.",
    whyRead: [
      "Des gags courts sur le rugby de village, pour les amateurs du ballon ovale.",
      "Un dessinateur congolais dans un registre humoristique bien français.",
      "Une lecture légère, à partager en famille.",
    ],
    year: 2007,
    publisher: "Carabas",
    pages: 40,
    isbn: "9782351002841",
    awards: [],
  }),

  // ------------------------------------------------------------------ Gaspard Njock
  bd({
    slug: "un-voyage-sans-retour",
    title: "Un voyage sans retour",
    contributors: complet("Gaspard Njock", "gaspard-njock"),
    audience: "ado",
    themes: ["exil", "enfance", "famille"],
    summary:
      "Malik a dix-sept ans et vit à Douala. Sur un coup de tête, poussé par ses amis, il quitte sa famille pour tenter sa chance en Europe. Commence alors un long périple : la traversée du désert et du Maghreb, puis la Méditerranée à bord d'une embarcation de fortune. Arrivé en Italie, Malik n'a pas le cœur à rêver d'avenir : il se raccroche aux souvenirs de son quartier, de ses copains et de ses grands-parents. Une fiction nourrie de réalité sur l'exil des jeunes Africains.",
    whyRead: [
      "L'exil raconté à hauteur d'adolescent, sans misérabilisme.",
      "Un bel hommage à Douala et à ceux qu'on laisse derrière soi.",
      "Le premier album français d'un auteur camerounais formé en Italie.",
    ],
    year: 2018,
    publisher: "Nouveau Monde éditions",
    pages: 95,
    isbn: "9782369425014",
    awards: [],
  }),
  bd({
    slug: "la-callas-l-enfance-d-une-diva",
    title: "La Callas",
    subtitle: "L'Enfance d'une diva",
    contributors: complet("Gaspard Njock", "gaspard-njock"),
    audience: "ado",
    themes: ["enfance", "famille", "femmes"],
    summary:
      "Avant de devenir la Callas, la plus célèbre cantatrice du XXe siècle, Maria Kalogeropoulos est une petite fille née à New York dans une famille d'immigrés grecs. Sa mère repère très tôt sa voix exceptionnelle et la pousse sans relâche vers le chant. Gaspard Njock raconte ces années de formation, entre l'Amérique et la Grèce, où se forge une vocation mais aussi une blessure intime. Un album en couleurs sur l'enfance d'une légende de l'opéra.",
    whyRead: [
      "Les jeunes années, peu connues, d'une immense chanteuse.",
      "Un auteur camerounais qui s'empare d'une figure européenne.",
      "Un récit sur le prix d'un talent hors du commun.",
    ],
    year: 2020,
    publisher: "Nouveau Monde éditions",
    pages: 112,
    isbn: "9782369428459",
    awards: [],
  }),

  // ------------------------------------------------------------------ Annick Kamgang
  bd({
    slug: "lucha-chronique-d-une-revolution-sans-armes-au-congo",
    title: "Lucha",
    subtitle: "Chronique d'une révolution sans armes au Congo",
    contributors: [scenario("Justine Brabant", null), dessin("Annick Kamgang", "annick-kamgang")],
    audience: "ado",
    themes: ["politique", "histoire", "travail"],
    summary:
      "En 2012, à Goma, dans l'est de la République démocratique du Congo, de jeunes Congolais de tous milieux fondent la Lucha, un mouvement citoyen qui refuse la violence. Dans une région ravagée par les groupes armés, ils militent pour l'accès à l'eau et à l'éducation, contre l'impunité et pour des élections libres. Cette BD-reportage retrace les origines du mouvement, ses actions, ses débats internes et la répression qu'il subit. Un documentaire engagé, publié avec Amnesty International.",
    whyRead: [
      "L'histoire d'une jeunesse congolaise qui choisit la non-violence.",
      "Une BD-reportage sérieuse, qui ne cache pas les difficultés du mouvement.",
      "Un noir et blanc élégant pour un sujet rarement traité.",
    ],
    year: 2018,
    publisher: "La Boîte à bulles",
    pages: 95,
    isbn: "9782849533031",
    awards: [],
  }),
  bd({
    slug: "les-enfants-du-pays",
    title: "Les Enfants du pays",
    contributors: complet("Annick Kamgang", "annick-kamgang"),
    audience: "adulte",
    themes: ["famille", "independances", "colonisation", "identite"],
    summary:
      "Miriam apprend que son père, Hubert, qui l'a abandonnée il y a vingt-cinq ans, est gravement malade au Cameroun. Elle part le rejoindre pour obtenir enfin des réponses, mais le vieil homme n'a plus la force de raconter sa vie. Miriam mène alors l'enquête auprès de ceux qui l'ont connu et découvre, pièce après pièce, l'histoire tourmentée de la lutte pour l'indépendance du pays. Un thriller familial qui éclaire une guerre longtemps passée sous silence.",
    whyRead: [
      "Une enquête familiale au cœur de la guerre d'indépendance du Cameroun.",
      "Un premier album en solo, entre autofiction, drame et histoire.",
      "Près de 170 pages qui se lisent comme un polar.",
    ],
    year: 2025,
    publisher: "La Boîte à bulles",
    pages: 167,
    isbn: "9782849535523",
    awards: [],
  }),

  // ------------------------------------------------------------------ Massiré Tounkara
  bd({
    slug: "issa-et-wassa-woroni-du-bafing",
    title: "Issa et Wassa, t. 1",
    subtitle: "Woroni du Bafing",
    contributors: [scenario("Mahamadou Traoré de Seydou", null), dessin("Massiré Tounkara", "massire-tounkara")],
    audience: "jeunesse",
    themes: ["enfance", "tradition"],
    summary:
      "Wassa, une jeune citadine de Bamako, part avec ses parents dans le Bafing, une réserve naturelle de l'ouest du Mali. Elle y retrouve son cousin Issa et Woroni, le singe qui ne le quitte jamais. Grâce à eux, elle découvre la vie des chimpanzés, les menaces que font peser les braconniers, la déforestation et les feux de brousse. Une BD malienne pour sensibiliser les jeunes lecteurs à la protection de la nature.",
    whyRead: [
      "Une aventure qui fait découvrir les chimpanzés du Mali.",
      "Un message écologique clair, pour les plus jeunes.",
      "Une BD éditée à Bamako.",
    ],
    year: 2008,
    publisher: "Balani's",
    pages: null,
    isbn: "9789995280239",
    awards: [],
  }),
  bd({
    slug: "issa-et-wassa-le-forestier-du-baoule",
    title: "Issa et Wassa, t. 2",
    subtitle: "Le Forestier du Baoulé",
    contributors: [scenario("Mahamadou Traoré de Seydou", null), dessin("Massiré Tounkara", "massire-tounkara")],
    audience: "jeunesse",
    themes: ["enfance", "tradition", "contes"],
    summary:
      "Wassa, Issa et le singe Woroni se retrouvent cette fois dans la réserve de biosphère de la boucle du Baoulé, au nord-ouest de Bamako. Un vieux griot leur raconte comment un pacte rompu par un chasseur a détourné les hommes du respect de la nature. Les enfants aident ensuite un garde forestier, bien mal équipé, à traquer des braconniers. Un album qui montre que la défense de l'environnement concerne tout le monde, éleveurs, cultivateurs et chasseurs.",
    whyRead: [
      "Un conte traditionnel au service d'un message écologique.",
      "La découverte d'un site naturel classé par l'Unesco.",
      "La suite des aventures d'Issa, Wassa et Woroni.",
    ],
    year: 2008,
    publisher: "Balani's",
    pages: null,
    isbn: "9789995280246",
    awards: [],
  }),
  bd({
    slug: "le-mali-de-madi",
    title: "Le Mali de Madi",
    subtitle: "50 ans d'histoire, 50 ans d'indépendance",
    contributors: [scenario("Sébastien Lalande", null), dessin("Massiré Tounkara", "massire-tounkara")],
    audience: "ado",
    themes: ["histoire", "independances", "politique"],
    summary:
      "Le 22 septembre 2010, Bamako fête le cinquantenaire de l'indépendance du Mali. Invité aux festivités, Madi, un journaliste célèbre, se souvient. À travers sa mémoire défilent cinquante ans d'histoire du pays : la politique surtout, mais aussi l'économie, les arts, les sciences et le sport. En parallèle se dessine la vie personnelle de Madi, marquée par un conflit avec son frère. Une BD conçue comme un support de mémoire collective pour tous les Maliens.",
    whyRead: [
      "Cinquante ans d'histoire malienne, de 1960 à 2010, en une seule BD.",
      "Une fiction familiale qui donne chair au récit historique.",
      "Un album réalisé avec l'appui d'un historien.",
    ],
    year: 2010,
    publisher: "Princes du Sahel",
    pages: 54,
    isbn: null,
    awards: [],
  }),
  bd({
    slug: "les-dogues-noirs-de-l-empire-la-force-noire",
    title: "Les Dogues noirs de l'Empire, t. 1",
    subtitle: "La Force noire",
    contributors: [scenario("Christophe Cassiau-Haurie", null), dessin("Massiré Tounkara", "massire-tounkara")],
    audience: "ado",
    themes: ["guerre", "colonisation", "histoire"],
    summary:
      "Dahomey, août 1914. Pour éviter que son village ne soit rasé par l'administration coloniale, Bakary, jeune guerrier kabyé, s'engage chez les tirailleurs sénégalais. Son régiment reçoit l'ordre d'envahir le Togo voisin, colonie allemande dont un simple ruisseau marque la frontière. Car la Première Guerre mondiale se joue aussi en Afrique, et les frontières tracées par les colons séparent les peuples : Bakary va devoir affronter les siens. Une page méconnue de l'histoire, dessinée en ligne claire.",
    whyRead: [
      "La Grande Guerre vue d'Afrique, un sujet rarement traité en BD.",
      "Un héros pris entre deux camps qui ne sont pas les siens.",
      "Une ligne claire en couleurs, accessible aux adolescents.",
    ],
    year: 2019,
    publisher: "L'Harmattan",
    pages: 61,
    isbn: "9782343133256",
    awards: [],
  }),

  // ------------------------------------------------------------------ Mongo Sisé
  bd({
    slug: "mokanda-illusion",
    title: "Mata Mata et Pili Pili",
    subtitle: "Mokanda illusion",
    contributors: complet("Mongo Sisé", "mongo-sise"),
    audience: "ado",
    themes: ["humour", "ville", "exil"],
    summary:
      "Une lettre, un « mokanda », arrive d'Europe, et voilà tout Kinshasa en ébullition. Mata Mata et Pili Pili, le célèbre duo créé par Mongo Sisé, se retrouvent au cœur d'une comédie truculente sur les rêves que fait naître l'Occident, avec leur lot de fantasmes, d'espoirs et de désillusions. Cet album inédit, retrouvé dans les archives de l'auteur après sa mort, est publié dans ses deux versions successives, avec un documentaire sur le pionnier de la BD congolaise.",
    whyRead: [
      "Un inédit du précurseur de la bande dessinée africaine.",
      "Une satire toujours actuelle du mirage de l'Europe.",
      "Deux versions du même récit, pour voir l'auteur au travail.",
    ],
    year: 2012,
    publisher: "L'Harmattan",
    pages: 78,
    isbn: "9782296993976",
    awards: [],
  }),
  bd({
    slug: "trois-aventures-de-mata-mata-et-pili-pili",
    title: "Trois aventures de Mata Mata et Pili Pili",
    subtitle: "La Médaille d'or, Le Portefeuille et Le Boy",
    contributors: complet("Mongo Sisé", "mongo-sise"),
    audience: "ado",
    themes: ["humour", "ville", "colonisation"],
    summary:
      "Mata Mata et Pili Pili, l'un grand et l'autre petit, sont les héros fétiches de Mongo Sisé, disciple d'Hergé et premier auteur africain de BD publié en Europe. Ce premier volume de son anthologie réunit trois de leurs aventures, dont Le Boy, l'album paru au tout début des années 1980 qui avait fait date. Un dossier de présentation replace l'œuvre dans l'histoire de la BD congolaise. L'occasion de redécouvrir un classique longtemps introuvable.",
    whyRead: [
      "Les débuts historiques de la BD africaine publiée en Europe.",
      "Un duo comique à la manière de la BD franco-belge des années 1970-1980.",
      "Un dossier qui éclaire l'œuvre d'un pionnier.",
    ],
    year: 2024,
    publisher: "L'Harmattan",
    pages: 169,
    isbn: "9782336418858",
    awards: [],
  }),

  // ------------------------------------------------------------------ Al'Mata
  bd({
    slug: "le-retour-au-pays-d-alphonse-madiba-dit-daudet",
    title: "Le Retour au pays d'Alphonse Madiba dit Daudet",
    contributors: [EDIMO, dessin("Al'Mata", "al-mata")],
    audience: "adulte",
    themes: ["humour", "exil", "famille"],
    summary:
      "Alphonse Madiba, dit Daudet, a vécu en France et revient au pays, où toute sa famille attend de voir le fruit de sa réussite. Seulement voilà, Daudet est un rêveur impénitent qui préfère vivre sa vie plutôt que de la regarder en face, et il n'a pas grand-chose à montrer. Comment avouer son échec quand tout un clan a misé sur vous ? Un roman graphique plein d'humour sur la pression qui pèse sur ceux qui sont partis.",
    whyRead: [
      "Un regard drôle et lucide sur le retour au pays des émigrés.",
      "Le premier album de la collection L'Harmattan BD, devenu un petit succès.",
      "Le début des aventures d'un antihéros inoubliable.",
    ],
    year: 2010,
    publisher: "L'Harmattan",
    pages: 54,
    isbn: "9782296121966",
    awards: [],
  }),
  bd({
    slug: "le-retour-en-france-d-alphonse-madiba-dit-daudet",
    title: "Le Retour en France d'Alphonse Madiba dit Daudet",
    contributors: [EDIMO, dessin("Al'Mata", "al-mata")],
    audience: "adulte",
    themes: ["humour", "exil", "politique"],
    summary:
      "Expulsé de France, Alphonse Madiba dit Daudet est coincé en Balaphonie, un pays imaginaire qui ressemble beaucoup à l'Afrique d'aujourd'hui. Devenu professeur, il n'a qu'une idée en tête : repartir au pays de ses rêves, coûte que coûte. Combines, rencontres et déconvenues s'enchaînent dans cette comédie grinçante, qui se moque autant des travers de la Balaphonie que des illusions de son héros.",
    whyRead: [
      "Une comédie grinçante sur l'obsession du départ.",
      "La Balaphonie, pays imaginaire et miroir du continent.",
      "La suite du Retour au pays, du même duo Edimo et Al'Mata.",
    ],
    year: 2016,
    publisher: "L'Harmattan",
    pages: 56,
    isbn: "9782343090726",
    awards: [],
  }),
  bd({
    slug: "revoir-paris",
    title: "Revoir Paris ?",
    subtitle: "Une nouvelle aventure d'Alphonse Madiba dit Daudet",
    contributors: [EDIMO, dessin("Al'Mata", "al-mata")],
    audience: "adulte",
    themes: ["humour", "exil", "ville"],
    summary:
      "Alphonse Madiba dit Daudet n'a pas renoncé : il aime la France et il est prêt à tout pour y retourner. Dans ce troisième album, il enchaîne les magouilles les plus rocambolesques, croise des policiers corrompus et des sorciers de pacotille. Sous l'humour, Edimo et Al'Mata dressent un portrait juste et réaliste d'une Afrique contemporaine où la migration reste au cœur de toutes les conversations.",
    whyRead: [
      "Le retour d'un antihéros qu'on adore suivre dans ses combines.",
      "Un dessin soigné, plus riche que jamais.",
      "Une satire sociale où l'on rit beaucoup.",
    ],
    year: 2024,
    publisher: "L'Harmattan",
    pages: 71,
    isbn: "9782343178479",
    awards: [],
  }),

  // ------------------------------------------------------------------ Christian Kingue Epanya
  livre({
    slug: "le-taxi-brousse-de-papa-diop",
    title: "Le Taxi-brousse de Papa Diop",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "famille", "ville"],
    summary:
      "Quand il n'a pas école, Sène accompagne son oncle Papa Diop au volant de son taxi-brousse, un minibus rouge qui relie Dakar à Saint-Louis du Sénégal. Le trajet est toujours le même, et pourtant chaque voyage est une aventure : passagers bavards, marchandises sur le toit, arrêts imprévus et paysages qui défilent. Un album aux images éclatantes, qui fait découvrir aux enfants le quotidien de la société sénégalaise.",
    whyRead: [
      "Un voyage coloré sur les routes du Sénégal.",
      "Des illustrations lumineuses, pleines de détails à observer.",
      "Un classique de l'album jeunesse africain, réédité avec un CD.",
    ],
    year: 2005,
    publisher: "Syros",
    pages: null,
    isbn: "9782748517439",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "le-grand-retour-du-taxi-brousse-de-papa-diop",
    title: "Le Grand Retour du taxi-brousse de Papa Diop",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["famille", "tradition", "spiritualite"],
    summary:
      "Dix ans ont passé. Le fameux minibus rouge est devenu la pièce maîtresse du musée de l'automobile de Dakar, où Sène travaille comme guide. Mais les admirateurs réclament son retour sur la route, et Papa Diop, très âgé, rêve d'un dernier voyage. Le taxi-brousse reprend donc du service, cette fois avec Sène au volant, pour parcourir des régions qu'il n'avait jamais traversées : pays bassari, parc du Niokolo-Koba, Tambacounda, jusqu'à la ville sainte de Touba.",
    whyRead: [
      "La suite tendre du Taxi-brousse de Papa Diop.",
      "Un tour du Sénégal en images, des villages aux parcs naturels.",
      "Un album à lire et à écouter, avec son CD.",
    ],
    year: 2016,
    publisher: "Syros",
    pages: null,
    isbn: "9782748521146",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "koumen-et-le-vieux-sage-de-la-montagne",
    title: "Koumen et le vieux sage de la montagne",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "enfance", "tradition"],
    summary:
      "La sécheresse a frappé le pays lobi et ruiné les récoltes. Au village, on accuse Koumen, une petite fille infirme que tout le monde a toujours tenue à l'écart. Blessée, elle décide de partir vers le sud, en pays baoulé, à la recherche du vieux sage de la montagne. Pour la guider, elle peut compter sur les animaux, dont elle comprend le langage. Un conte initiatique sur la différence et le courage.",
    whyRead: [
      "Une héroïne fragile en apparence, mais pleine de courage.",
      "Un conte sur le rejet de la différence, à lire dès le primaire.",
      "Des animaux complices et de grands paysages d'Afrique de l'Ouest.",
    ],
    year: 2006,
    publisher: "Monde global",
    pages: 34,
    isbn: "9782916435039",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "malin-comme-10-singes",
    title: "Malin comme 10 singes",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "ecole", "famille"],
    summary:
      "Les singes sont malins, agiles et farceurs. Pas Petit Bolo : il est timide, il a peur de l'eau et, à l'école, ses camarades se moquent de lui parce qu'il ne sait pas compter. Pour le consoler, sa maman l'emmène vendre des bananes au marché. Là, entre les clients et la monnaie à rendre, Petit Bolo va découvrir qu'il a plus de ressources qu'il ne le croit. Une petite fable sur la confiance en soi.",
    whyRead: [
      "Une fable douce pour les enfants qui doutent d'eux-mêmes.",
      "Une façon ludique d'aborder les chiffres.",
      "Les couleurs vives d'un marché africain.",
    ],
    year: 2006,
    publisher: "Seuil jeunesse",
    pages: null,
    isbn: "9782020880725",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "mes-images-du-senegal",
    title: "Mes images du Sénégal",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "ville", "famille"],
    summary:
      "Youssou vit à Dakar et nous fait visiter son pays. Il présente sa famille, son quartier, l'école, les repas, les transports, la musique et l'animation de la ville. Ce petit documentaire passe surtout par les images, aux couleurs chaudes, pour faire découvrir le Sénégal aux plus jeunes. Clair et bien construit, l'album respire le bonheur de vivre et se termine sur un chaleureux « Bienvenue au Sénégal ! ».",
    whyRead: [
      "Un premier documentaire sur le Sénégal pour les 5-10 ans.",
      "Des illustrations lumineuses qui racontent autant que le texte.",
      "Un guide plein d'entrain : le petit Youssou.",
    ],
    year: 2009,
    publisher: "Sorbier",
    pages: 32,
    isbn: "9782732039398",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "la-pipe-de-tita-nveng",
    title: "La Pipe de Tita Nveng",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "famille", "tradition"],
    summary:
      "Engoulou, une écolière de Yaoundé, adore passer les grandes vacances au village, chez ses grands-parents. Elle y retrouve surtout Tita Nveng, qui lui raconte de savoureuses histoires. Mais cette année, la fillette va toucher à l'interdit, et son geste risque de troubler la paix du village. Saura-t-elle réparer ce qu'elle a fait ? Un album sur la transmission entre générations et le respect des traditions.",
    whyRead: [
      "Les vacances au village, un souvenir partagé par beaucoup d'enfants camerounais.",
      "Un récit sur la désobéissance et la manière de réparer ses erreurs.",
      "Texte et images d'un même auteur-illustrateur.",
    ],
    year: 2009,
    publisher: "Orphie",
    pages: 32,
    isbn: "9782877635356",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "le-pagne-bleu",
    title: "Le Pagne bleu",
    contributors: [auteur("Jocelyne Sauvard", null), auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["exil", "identite", "famille"],
    summary:
      "Célia est métisse. Son père a disparu et elle a grandi en Afrique auprès d'une maman noire qui l'a élevée. Un jour, elle doit quitter son pays natal pour vivre en France avec sa mère blanche. Loin de tout ce qu'elle aime, elle n'oublie pas son autre mère et garde la tristesse au cœur. C'est la rencontre avec un cheval qui va l'aider à retrouver le goût de vivre.",
    whyRead: [
      "Un album sensible sur le déracinement et la double appartenance.",
      "Une histoire d'amitié entre une enfant et un cheval.",
      "Pour parler d'exil et de famille avec les plus jeunes.",
    ],
    year: 2012,
    publisher: "Orphie",
    pages: 28,
    isbn: "9782877636681",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "les-rois-de-la-sape",
    title: "Les Rois de la sape",
    contributors: [auteur("Christian Kingue Epanya", "christian-kingue-epanya")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["ville", "humour", "identite"],
    summary:
      "Élumbu, jeune étudiant arrivé de la province de l'Équateur, s'installe à Matonge, le quartier bouillonnant de Kinshasa. Les sapeurs, ces dandys qui se proclament princes de la mode, se moquent sans pitié de sa tenue. Conseillé par un coiffeur bienveillant, un habile fripier et son tonton, Élumbu décide de leur répondre sur leur propre terrain : l'élégance. Un festival de couleurs et de tenues extravagantes, qui se termine par le portrait d'un vrai sapeur.",
    whyRead: [
      "Une plongée joyeuse dans l'univers de la sape kinoise.",
      "Des illustrations somptueuses, fourmillant de détails de rue.",
      "Une histoire de confiance en soi et de solidarité.",
    ],
    year: 2014,
    publisher: "Océan éditions",
    pages: null,
    isbn: "9782362470837",
    format: "album",
    awards: [],
  }),

  // ------------------------------------------------------------------ Thembo Kash
  bd({
    slug: "jungle-urbaine-lola",
    title: "Jungle urbaine, t. 1",
    subtitle: "Lola",
    contributors: complet("Thembo Kash", "thembo-kash"),
    audience: "adulte",
    themes: ["ville", "amour"],
    summary:
      "À Kinshasa, Bwana est un petit mécanicien de quartier. Un jour, il rencontre Lola, la fille d'un riche homme d'affaires. Tout les oppose, et pourtant une idylle naît entre les deux jeunes gens. Mais un mystérieux 4x4 noir semble suivre chacun de leurs pas. Thembo Kash signe seul ce premier tome en noir et blanc, où la capitale congolaise est dessinée avec un réalisme rare.",
    whyRead: [
      "Kinshasa dessinée avec un grand souci du réel.",
      "Une histoire d'amour entre deux mondes, sur fond de suspense.",
      "Un album en solo d'un grand nom de la BD congolaise.",
    ],
    year: 2012,
    publisher: "L'Harmattan",
    pages: 56,
    isbn: "9782296966383",
    awards: [],
  }),
  bd({
    slug: "mbote-kinshasa-article-15",
    title: "Mbote Kinshasa !",
    subtitle: "Article 15",
    contributors: [scenario("Sébastien Maitre", null), dessin("Thembo Kash", "thembo-kash")],
    audience: "ado",
    themes: ["enfance", "ville", "famille", "humour"],
    summary:
      "À Kinshasa, « l'article 15 » est une maxime célèbre : débrouille-toi. Samuel, dix ans, va devoir l'appliquer quand on lui refuse l'entrée de l'école à cause de ses chaussures trouées. Ses parents n'ont pas un sou, toutes les économies ayant fondu dans la Scarlett, le taxi que son père a acheté pour devenir son propre patron. Samuel n'a donc qu'une solution : faire travailler son imagination pour s'offrir une nouvelle paire.",
    whyRead: [
      "Un petit héros débrouillard dans les rues de Kinshasa.",
      "L'esprit de la « débrouille » congolaise raconté avec humour et tendresse.",
      "Une BD idéale pour découvrir la vie d'un enfant kinois.",
    ],
    year: 2016,
    publisher: "La Boîte à bulles",
    pages: 52,
    isbn: "9782849532683",
    awards: [],
  }),

  // ------------------------------------------------------------------ Alain Kojélé
  bd({
    slug: "vies-volees",
    title: "Vies volées",
    contributors: [
      { role: "scenariste", name: "Alix Fuilu", authorSlug: null },
      dessin("Alix Fuilu", null),
      dessin("Didier Kassaï", "didier-kassai"),
      dessin("Alain Kojélé", "alain-kojele"),
    ],
    audience: "adulte",
    themes: ["guerre", "femmes", "enfance"],
    summary:
      "Dans l'est de la République démocratique du Congo, les guerres successives font des femmes et des jeunes filles les premières victimes des milices. Cet album réunit trois récits liés par ce thème grave, signés par trois auteurs africains. Dans l'un d'eux, Bathy, un garçon de douze ans, n'a que cinq jours pour rapporter du massif des Virunga une plante médicinale qui sauvera son grand-père, en traversant une savane pleine de dangers avec ses amies. Une BD engagée pour dénoncer les violences faites aux femmes.",
    whyRead: [
      "Trois auteurs africains réunis pour dénoncer une tragédie.",
      "Un album fort, à réserver aux grands adolescents et aux adultes.",
      "Le premier titre du collectif Afro Bulles.",
    ],
    year: 2008,
    publisher: "Afro Bulles",
    pages: 43,
    isbn: "9782916690018",
    awards: [],
  }),
  bd({
    slug: "sur-les-berges-du-fleuve-congo",
    title: "Sur les berges du fleuve Congo",
    contributors: [
      { role: "scenariste", name: "Alix Fuilu", authorSlug: null },
      dessin("Alix Fuilu", null),
      dessin("Willy Zekid", null),
      dessin("Alain Kojélé", "alain-kojele"),
    ],
    audience: "adulte",
    themes: ["femmes", "amour", "ville"],
    summary:
      "Trois histoires, trois dessinateurs congolais, un même sujet : le sida. Alix Fuilu prolonge le récit de Vies volées avec une femme qui attend les résultats de son test médical après un viol. Willy Zekid raconte la rencontre avec un musicien persuadé d'être malade. Alain Kojélé signe un récit sans paroles, la rencontre d'un jeune homme et d'une prostituée. Un album fort, porté par trois styles graphiques très différents.",
    whyRead: [
      "Trois regards d'artistes sur une maladie encore taboue.",
      "Un récit muet d'Alain Kojélé, tout en tension.",
      "La suite de Vies volées, par le collectif Afro Bulles.",
    ],
    year: 2011,
    publisher: "Afro Bulles",
    pages: 44,
    isbn: "9782916690025",
    awards: [],
  }),
  bd({
    slug: "bienvenue-a-saint-germain-les-corbeil",
    title: "Bienvenue à Saint-Germain-lès-Corbeil",
    contributors: [scenario("Guy Pascal Onga'ntsang", null), dessin("Alain Kojélé", "alain-kojele")],
    audience: "ado",
    themes: ["histoire", "exil", "famille"],
    summary:
      "En 2017, Saint-Germain-lès-Corbeil, commune de l'Essonne, manque de médecins. Grâce au jumelage, un médecin polonais vient diriger le nouveau centre médical et s'installe avec sa famille. En découvrant la ville, les nouveaux venus remontent le fil de son histoire, des origines jusqu'à aujourd'hui. Une BD de commande originale, qui raconte l'histoire d'une petite ville française à travers le regard de nouveaux arrivants.",
    whyRead: [
      "L'histoire d'une commune française racontée à hauteur de famille.",
      "Un dessinateur congolais au service du patrimoine local.",
      "Une idée simple : voir sa ville avec des yeux neufs.",
    ],
    year: 2017,
    publisher: "Éditions Kimia",
    pages: 40,
    isbn: "9782956052104",
    awards: [],
  }),
  livre({
    slug: "djoumaelle-et-yarhi",
    title: "Djoumaelle et Yarhi",
    contributors: [auteur("Mamou Traoré", null), auteur("Alain Kojélé", "alain-kojele")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "enfance", "histoire"],
    summary:
      "Au temps de l'empire du Ghana, deux jumeaux grandissent seuls, abandonnés dans la brousse. La fille, Djoumaelle, chante avec les oiseaux ; le garçon, Yarhi, court avec les léopards. Leur vie s'écoule paisiblement au rythme de la nature, jusqu'au jour où un étranger vient troubler leur tranquillité. Un récit illustré aux allures de conte, qui plonge les enfants dans l'Afrique des grands empires.",
    whyRead: [
      "Un conte de jumeaux sauvages au temps de l'empire du Ghana.",
      "De belles illustrations d'Alain Kojélé.",
      "Une porte d'entrée vers l'histoire ancienne de l'Afrique de l'Ouest.",
    ],
    year: 2018,
    publisher: "Publishroom",
    pages: 62,
    isbn: "9791023609264",
    format: "album",
    awards: [],
  }),
  bd({
    slug: "lucas-et-les-racoons",
    title: "Lucas et les racoons, vol. 1",
    contributors: [scenario("Catherine Douglas", null), dessin("Alain Kojélé", "alain-kojele")],
    audience: "jeunesse",
    themes: ["enfance", "contes"],
    summary:
      "Lucas a dix ans et vit sur une île couverte de plus d'une centaine de vieux moulins. La plupart semblent à l'arrêt, mais chacun cache en réalité un monde fantastique, mi-rêve, mi-cauchemar. Personne ne peut y entrer, sauf Lucas et ses amis les racoons. Leur mission : venir en aide à des enfants retenus prisonniers par une terrible sorcière, Carla. Une aventure fantastique pour les jeunes lecteurs.",
    whyRead: [
      "Une île aux moulins magiques, pleine de mystères.",
      "Une bande de ratons laveurs attachants.",
      "Une BD d'aventure pour les 8-12 ans.",
    ],
    year: 2019,
    publisher: "Teham éditions",
    pages: 66,
    isbn: "9791090147348",
    awards: [],
  }),

  // ------------------------------------------------------------------ KHP
  bd({
    slug: "chroniques-de-brazzaville",
    title: "Chroniques de Brazzaville",
    contributors: [dessin("Jussie Nsana", null), dessin("KHP", "khp"), dessin("Lionel Boussi", null)],
    audience: "adulte",
    themes: ["guerre", "ville", "enfance"],
    summary:
      "Trois jeunes artistes de Brazzaville réunis dans un même album. KHP et Lionel Boussi racontent leurs souvenirs de la guerre civile de 1997, qu'ils ont traversée enfants, enrôlés comme soldats. Jussie Nsana, elle, signe une histoire très urbaine, plus légère, qui montre une autre facette de la ville. Un livre qui révèle une nouvelle génération de dessinateurs congolais et fait entendre une mémoire encore à vif.",
    whyRead: [
      "Le témoignage rare d'anciens enfants-soldats devenus dessinateurs.",
      "Trois talents de la jeune BD congolaise.",
      "Brazzaville entre mémoire de guerre et vie de quartier.",
    ],
    year: 2012,
    publisher: "L'Harmattan",
    pages: 46,
    isbn: "9782296966260",
    awards: [],
  }),
  bd({
    slug: "les-dessous-de-pointe-noire",
    title: "Les Dessous de Pointe-Noire",
    contributors: complet("KHP", "khp"),
    audience: "adulte",
    themes: ["femmes", "ville", "exil"],
    summary:
      "À Pointe-Noire, capitale économique du Congo, la prostitution est devenue une activité comme une autre. Naomie et son amie Yevline espèrent s'en sortir en séduisant des Européens célibataires qui pourraient les emmener en France. Leur stratégie fonctionne parfois, mais elle a un prix dont les deux jeunes femmes ne mesurent pas toujours la portée. KHP aborde de front ce sujet dans un album entièrement dessiné au stylo-bille, d'un réalisme saisissant.",
    whyRead: [
      "Un sujet difficile, traité sans détour ni voyeurisme.",
      "Une prouesse graphique : tout est dessiné au stylo-bille.",
      "Le premier album en solo d'un dessinateur congolais.",
    ],
    year: 2018,
    publisher: "L'Harmattan",
    pages: 55,
    isbn: "9782343124377",
    awards: [],
  }),

  // ------------------------------------------------------------------ Koffi Roger N'Guessan
  bd({
    slug: "seductions-mille-mysteres-d-afrique",
    title: "Séductions ; Mille mystères d'Afrique",
    contributors: complet("Koffi Roger N'Guessan", "koffi-roger-nguessan"),
    audience: "adulte",
    themes: ["amour", "tradition", "ville", "spiritualite"],
    summary:
      "Un album double, à lire dans les deux sens. D'un côté, Séductions suit Anaïs, bien décidée à conquérir sérieusement un futur mari chirurgien en évitant tous les pièges de l'amour en ville. De l'autre, Mille mystères d'Afrique rassemble des histoires courtes autour de pratiques magiques et inquiétantes, dans une Afrique tiraillée entre modernité et traditions. Le premier album de Koffi Roger N'Guessan, en noir et blanc.",
    whyRead: [
      "Deux livres en un, avec deux couvertures tête-bêche.",
      "Une comédie sentimentale et des récits de mystère.",
      "Le premier album d'un dessinateur ivoirien au trait élégant.",
    ],
    year: 2013,
    publisher: "L'Harmattan",
    pages: null,
    isbn: "9782336301655",
    awards: [],
  }),
  bd({
    slug: "paris-vaille-que-vaille",
    title: "Paris vaille que vaille",
    contributors: complet("Koffi Roger N'Guessan", "koffi-roger-nguessan"),
    audience: "adulte",
    themes: ["exil", "femmes", "amour"],
    summary:
      "Marie-France rêve de quitter l'Afrique et de découvrir la France, par n'importe quel moyen. Sur Internet, elle fait la connaissance d'un Français qui la séduit et lui propose de la faire venir à Paris. Le conte de fées semble à portée de main, mais une fois sur place, la réalité se révèle bien différente. Koffi Roger N'Guessan décrit le désespoir d'une jeunesse qui voit dans l'émigration la seule issue.",
    whyRead: [
      "Le mirage de l'Europe vu à travers une rencontre en ligne.",
      "Une héroïne dont on suit les espoirs avec inquiétude.",
      "Un noir et blanc expressif, au service d'un sujet grave.",
    ],
    year: 2014,
    publisher: "L'Harmattan",
    pages: 82,
    isbn: "9782343046310",
    awards: [],
  }),
  bd({
    slug: "les-fins-limiers",
    title: "Les Fins Limiers",
    contributors: [scenario("Christophe Cassiau-Haurie", null), dessin("Koffi Roger N'Guessan", "koffi-roger-nguessan")],
    audience: "ado",
    themes: ["humour", "ville"],
    summary:
      "Le commissaire Koro et l'inspecteur Kouamé ne se ressemblent en rien, mais ils se complètent à merveille. Dans la Côte d'Ivoire de l'après-guerre civile, ils mènent six enquêtes qui plongent le lecteur dans la vie quotidienne ivoirienne et lui apprennent au passage le nouchi, l'argot d'Abidjan. La solution de chaque énigme n'est donnée qu'à la dernière page : au lecteur de jouer les détectives.",
    whyRead: [
      "Une BD à énigmes, où l'on mène l'enquête avec les héros.",
      "Une initiation savoureuse au nouchi, l'argot ivoirien.",
      "Un duo de policiers aussi drôle que dépareillé.",
    ],
    year: 2016,
    publisher: "L'Harmattan",
    pages: 58,
    isbn: "9782343077239",
    awards: [],
  }),
  bd({
    slug: "chaka-d-apres-l-oeuvre-de-thomas-mofolo",
    title: "Chaka",
    subtitle: "D'après l'œuvre de Thomas Mofolo",
    contributors: [scenario("Jean-François Chanson", null), dessin("Koffi Roger N'Guessan", "koffi-roger-nguessan")],
    audience: "ado",
    themes: ["histoire", "contes", "politique", "guerre"],
    summary:
      "Au XVIIIe siècle, en Afrique australe, le chef d'une petite tribu n'arrive pas à avoir de fils de ses quatre épouses. Il en a un hors mariage avec une jeune femme : c'est Chaka. Enfant du péché, rejeté par les siens, le garçon doit s'enfuir et commence une longue errance qui le conduira vers un destin hors du commun. Adapté du roman classique du Mosotho Thomas Mofolo, l'album raconte, entre histoire et légende, la naissance de l'épopée zouloue.",
    whyRead: [
      "Un grand classique de la littérature africaine, adapté en BD.",
      "Une épopée pleine de magie, de folie et de violence.",
      "Le dessin en couleurs de Koffi Roger N'Guessan, sur plus de cent pages.",
    ],
    year: 2018,
    publisher: "L'Harmattan",
    pages: 101,
    isbn: "9782343124322",
    awards: [],
  }),
  bd({
    slug: "legere-amertume-une-histoire-du-the",
    title: "Légère amertume",
    subtitle: "Une histoire du thé",
    contributors: [scenario("Elanni", null), scenario("Djaï", null), dessin("Koffi Roger N'Guessan", "koffi-roger-nguessan")],
    audience: "adulte",
    themes: ["histoire", "femmes", "tradition"],
    summary:
      "D'où vient le thé que l'on boit aujourd'hui jusque dans les rues d'Afrique de l'Ouest ? Cet album remonte son histoire, de sa découverte en Asie jusqu'à son expansion sur le continent africain. Le fil conducteur est la vie d'Adjoua, une femme indépendante née au milieu du XXe siècle en Côte d'Ivoire. À la fois roman graphique historique et chronique douce-amère, le livre voyage à travers plusieurs continents et plusieurs époques.",
    whyRead: [
      "L'histoire mondiale d'un breuvage, racontée à travers une vie de femme.",
      "Un voyage entre l'Asie, l'Europe et l'Afrique.",
      "Une chronique tendre et un peu amère, comme son titre.",
    ],
    year: 2018,
    publisher: "L'Harmattan",
    pages: 60,
    isbn: "9782343156859",
    awards: [],
  }),
  bd({
    slug: "moi-borg-enfant-de-korhogo",
    title: "Moi, Borg, enfant de Korhogo",
    contributors: [scenario("Sophie K. Boating", null), dessin("Koffi Roger N'Guessan", "koffi-roger-nguessan")],
    audience: "ado",
    themes: ["enfance", "famille", "tradition"],
    summary:
      "Borg est un margouillat, ce petit lézard qu'on voit partout sur les murs du nord de la Côte d'Ivoire. Adolescent taquin et curieux, respectueux et travailleur, il vit à Korhogo, capitale du pays sénoufo, et aime sa famille plus que tout. On le suit dans son quotidien et dans les questions qu'il se pose, celles qui décident de l'adulte qu'on va devenir. Une BD adaptée d'un récit de Sophie K. Boating.",
    whyRead: [
      "Un héros lézard plein de charme, symbole du nord ivoirien.",
      "La découverte de Korhogo et du pays sénoufo.",
      "Un récit d'adolescence tendre et réfléchi.",
    ],
    year: 2020,
    publisher: "L'Harmattan",
    pages: 64,
    isbn: "9782343174501",
    awards: [],
  }),

  // ------------------------------------------------------------------ Hector Sonon
  bd({
    slug: "koffi-aze",
    title: "Koffi Azé",
    contributors: complet("Hector Sonon", "hector-sonon"),
    audience: "adulte",
    themes: ["humour", "politique", "spiritualite"],
    summary:
      "La campagne présidentielle bat son plein au Bénin et Koffi Azé, ministre en exercice, est candidat. Pour mettre les ancêtres de son côté, il consulte un babalawo, un prêtre yorouba. Le sacrifice recommandé est pour le moins inattendu, et pour l'obtenir, le ministre va devoir compter sur son neveu, cuisinier chez des Blancs. Une courte bande dessinée mordante, au trait caricatural, sur la politique et les croyances.",
    whyRead: [
      "Une satire féroce de la politique béninoise.",
      "Le trait caricatural et vif d'un grand dessinateur de presse.",
      "Une histoire courte qui se lit d'une traite.",
    ],
    year: 2009,
    publisher: "Star Éditions",
    pages: 26,
    isbn: "9789991930329",
    awards: [],
  }),
  bd({
    slug: "toubab-or-not-toubab",
    title: "Toubab or not toubab",
    contributors: [
      scenario("Mathias Mercier", null),
      dessin("Hector Sonon", "hector-sonon"),
    ],
    audience: "adulte",
    themes: ["enfance", "exil"],
    summary:
      "Hondo a douze ans et vit en Mauritanie. À la mort de sa mère, il est confié à Houseïni, un chamelier avare et cruel qui fait de lui son souffre-douleur. Hondo est amoureux de Yasmine, la fille de son maître, et rêve de s'enfuir avec elle. Mais une tempête de sable disperse les chameaux dont il a la garde, et le garçon, pris de panique, s'élance seul dans le désert. Une adaptation du roman noir de Jean-Claude Derey.",
    whyRead: [
      "Un récit d'aventure et d'errance dans le désert mauritanien.",
      "L'adaptation d'un roman noir, dessinée par un maître béninois.",
      "Un grand album en couleurs, chez Casterman.",
    ],
    year: 2012,
    publisher: "Casterman",
    pages: 100,
    isbn: "9782203041653",
    awards: [],
  }),
  bd({
    slug: "les-aventures-de-zinsou-et-sagbo-le-temple-des-pythons",
    title: "Les Aventures de Zinsou et Sagbo",
    subtitle: "Le Temple des pythons",
    contributors: complet("Hector Sonon", "hector-sonon"),
    audience: "jeunesse",
    themes: ["enfance", "spiritualite", "ecole"],
    summary:
      "Les jumeaux Zinsou et Sagbo partent en sortie scolaire dans la région de Ouidah, au Bénin. Avec leur classe, ils découvrent la forêt sacrée de Kpassé, le culte vaudou rendu aux serpents et le célèbre temple des pythons. Au fil de la visite, les enfants sont sensibilisés au trafic d'animaux sauvages. Une petite BD vivante qui fait découvrir un patrimoine culturel majeur du Bénin.",
    whyRead: [
      "Une visite de Ouidah et de ses lieux sacrés, à hauteur d'enfant.",
      "Des jumeaux qui font écho à l'enfance de l'auteur.",
      "Un message sur la protection des animaux sauvages.",
    ],
    year: 2022,
    publisher: "Ruisseaux d'Afrique",
    pages: 28,
    isbn: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Dwa
  bd({
    slug: "megacomplots-a-tananarive",
    title: "Mégacomplots à Tananarive",
    contributors: [scenario("Dwa", "dwa"), scenario("Pov", null), dessin("Dwa", "dwa"), dessin("Pov", null)],
    audience: "adulte",
    themes: ["politique", "humour", "ville"],
    summary:
      "À Antananarivo, une association étudiante s'apprête à élire son président, et les ambitions s'aiguisent. Derrière cette élection en apparence modeste se dessine, comme en modèle réduit, la vie politique malgache. Premier album du duo Pov et Dwa, Mégacomplots à Tananarive ouvre une série qui promène ensuite le lecteur à travers toute la Grande Île. Une satire sociale pleine d'humour.",
    whyRead: [
      "La politique malgache vue à travers une élection étudiante.",
      "Le premier album d'un duo phare de la BD malgache.",
      "Une ville, Tana, dessinée avec gourmandise.",
    ],
    year: 2011,
    publisher: "Des bulles dans l'océan",
    pages: 94,
    isbn: "9782919069095",
    awards: [],
  }),
  bd({
    slug: "cout-d-etat-a-tamatave",
    title: "Coût d'État à Tamatave",
    contributors: [scenario("Dwa", "dwa"), scenario("Pov", null), dessin("Dwa", "dwa"), dessin("Pov", null)],
    audience: "adulte",
    themes: ["politique", "humour", "famille"],
    summary:
      "Rémy, asocial et égoïste, vient de perdre l'élection à la présidence de son association étudiante. Ce poste lui aurait permis de rejoindre son frère en France et d'échapper à sa belle-mère. Il se rapproche alors de Pross, le vice-président. Ensemble, ils comprennent que le nouveau président n'est qu'un opportuniste, et décident de le renverser. Le deuxième album de Pov et Dwa, cette fois dans la ville portuaire de Tamatave.",
    whyRead: [
      "Un coup d'État miniature, drôle et révélateur.",
      "Un antihéros mal aimable, qu'on suit avec plaisir.",
      "La découverte de Tamatave, grand port de Madagascar.",
    ],
    year: 2014,
    publisher: "Des bulles dans l'océan",
    pages: 94,
    isbn: "9782919069187",
    awards: [],
  }),
  bd({
    slug: "la-reunion-kely",
    title: "La Réunion Kely",
    subtitle: "L'Histoire de Fabrice",
    contributors: [scenario("Dwa", "dwa"), dessin("Liva", null)],
    audience: "adulte",
    themes: ["ville", "travail", "enfance"],
    summary:
      "La Réunion Kely est l'un des quartiers les plus pauvres de Tananarive. Dwa y suit Fabrice et raconte, sous forme de reportage, la vie quotidienne de ses habitants, leur débrouille et leur dignité. Le dessinateur Liva met en images ce récit avec une technique hors du commun : de minuscules croix tracées au stylo-bille, puis grattées à la lame de rasoir, qui donnent aux ombres et aux visages un réalisme saisissant.",
    whyRead: [
      "Un reportage dessiné au cœur d'un quartier oublié de Tana.",
      "Une technique graphique stupéfiante, au stylo-bille.",
      "Un regard respectueux sur la vie dans la pauvreté.",
    ],
    year: 2017,
    publisher: "Des bulles dans l'océan",
    pages: 64,
    isbn: "9782919069484",
    awards: [],
  }),
  bd({
    slug: "back-to-al-bak",
    title: "Back to Al Bak",
    contributors: complet("Dwa", "dwa"),
    audience: "adulte",
    themes: ["enfance", "identite", "tradition"],
    summary:
      "Dwa, de son vrai nom Éric Andriantsialonina, est né dans un village des hautes terres malgaches avant que sa famille ne s'installe à Tananarive. Dans ce carnet de voyage dessiné, il retourne sur la terre de son enfance. Au fil des pages, il confronte ses souvenirs à ce qu'il découvre sur place. Un très beau livre personnel, entre récit, croquis et réflexion sur les racines.",
    whyRead: [
      "Un carnet de voyage sensible au cœur de Madagascar.",
      "Un retour aux sources d'un auteur majeur de la BD malgache.",
      "Près de 150 pages pour prendre le temps du voyage.",
    ],
    year: 2018,
    publisher: "Des bulles dans l'océan",
    pages: 144,
    isbn: "9782919069538",
    awards: [],
  }),

  // ------------------------------------------------------------------ Gilbert G. Groud
  bd({
    slug: "magie-noire",
    title: "Magie noire, t. 1",
    contributors: complet("Gilbert G. Groud", "gilbert-g-groud"),
    audience: "adulte",
    themes: ["spiritualite", "tradition"],
    summary:
      "Gilbert G. Groud, peintre et graphiste ivoirien, consacre son premier album à la sorcellerie en Afrique. Entre fiction, reportage et étude de société, il explore l'univers trouble de la magie noire, aux frontières du surnaturel et de la folie. Il montre comment ces pratiques anciennes pèsent encore sur la vie quotidienne et sur les rapports de pouvoir. Un album sombre, au graphisme de peintre.",
    whyRead: [
      "Un sujet tabou, abordé de front par un artiste ivoirien.",
      "Un style pictural qui tranche avec la BD classique.",
      "Une enquête troublante entre fiction et documentaire.",
    ],
    year: 2002,
    publisher: "Albin Michel",
    pages: null,
    isbn: "9782226136428",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [
  {
    slug: "serge-diantantu",
    name: "Serge Diantantu",
    birthYear: 1960,
    deathYear: 2022,
    countryCode: "CD",
    origin: null,
    bio: "Né à Mbanza-Ngungu, dans le Bas-Congo, Serge Diantantu étudie la menuiserie puis les Beaux-Arts à Kinshasa. Installé en France en 1981, il travaille d'abord comme décorateur pour le cinéma et la télévision. Il se tourne vers la bande dessinée en 1994 avec Attention sida, un album de prévention, puis consacre trois tomes à la vie de Simon Kimbangu. Il se fait ensuite le spécialiste de l'histoire des Noirs, avec la série documentaire Mémoire de l'esclavage en cinq tomes et des galeries de portraits de femmes et d'hommes noirs. Souvent éditeur de ses propres livres, il a beaucoup œuvré pour les faire entrer dans les familles et les écoles. Il est mort en 2022 à Lucé, en Eure-et-Loir.",
    photo: null,
    photoCredit: null,
    startWith: "bulambemba",
    otherTitles: [
      "Attention sida (1994)",
      "Simon Kimbangu, t. 2 : Le Triomphe par la non-violence (2004)",
      "L'Amour sous les palmiers (2008)",
      "Homme noir d'Afrique, d'Amérique et des Antilles (2012-2013)",
      "Nkengue la capricieuse (2012)",
    ],
    facts: [
      "Le premier tome de Mémoire de l'esclavage s'est vendu à dix mille exemplaires.",
      "Il avait choisi la bande dessinée parce que le cinéma, disait-il, coûtait trop cher.",
      "Il appelait son style de dessin « mindélô ».",
    ],
    awards: [{ name: "Prix de la bande dessinée engagée (Lyon)", year: 2008 }],
  },
  {
    slug: "adjim-danngar",
    name: "Adjim Danngar",
    birthYear: 1982,
    deathYear: null,
    countryCode: "TD",
    origin: null,
    bio: "Né à Sarh, dans le sud du Tchad, Adjim Danngar rejoint à dix-sept ans l'Atelier Bulles du Chari, à N'Djamena, qui forme les jeunes dessinateurs tchadiens. Il publie ses premiers dessins dans Rafigui, un journal éducatif, puis dans l'hebdomadaire satirique Le Miroir. Installé à Paris depuis 2004, il devient dessinateur de presse et participe à de nombreux albums collectifs et festivals. Il dessine en 2017 Mamie Denis, sur un scénario d'Edimo, avant de signer seul Djarabane chez Delcourt, grand récit sur le Tchad des années 1980, la ville de Sarh où il est né. Il est engagé dans l'association United Sketches, qui défend la liberté des dessinateurs de presse.",
    photo: null,
    photoCredit: null,
    startWith: "djarabane-au-petit-marche-des-amours-perdues",
    otherTitles: ["Mémoire et voyages (2018)"],
    awards: [],
  },
  {
    slug: "didier-viode",
    name: "Didier Viodé",
    birthYear: 1979,
    deathYear: null,
    countryCode: "BJ",
    origin: "Né à Abidjan, d'origine béninoise",
    bio: "Didier Viodé naît à Abidjan et passe une partie de son enfance au Bénin, son pays d'origine, où il obtient son baccalauréat. Il étudie à l'Institut national supérieur des arts d'Abidjan, puis aux Beaux-Arts de Besançon, dont il sort diplômé en 2007. Plasticien, il travaille le dessin, la peinture et la vidéo, souvent autour des migrations et de l'identité. En bande dessinée, il publie Étranger sans rendez-vous, puis invente Yao, un jeune peintre naïf confronté à la corruption et aux refus de visa. Il vit et travaille en France.",
    photo: null,
    photoCredit: null,
    startWith: "yao-visa-refuse",
    otherTitles: [],
    awards: [],
  },
  {
    slug: "hallain-paluku",
    name: "Hallain Paluku",
    birthYear: 1977,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Né à Kinshasa d'un père originaire du Kivu, Hallain Paluku étudie à l'Académie des beaux-arts de la capitale et publie très tôt des dessins de presse. En 1999, il imagine Missy, une femme ronde dessinée sans visage, qui deviendra son premier album en 2006, après son installation à Bruxelles. Il dessine ensuite Rugbill, série humoristique sur le rugby de village, et Mes 18 ans, parlons-en !. En 2008, il crée Bana Boul, premier dessin animé en lingala, qui rencontre un immense succès en ligne. Revenu vivre à Kinshasa, il travaille aussi dans l'audiovisuel.",
    photo: null,
    photoCredit: null,
    startWith: "missy",
    otherTitles: ["Mes 18 ans, parlons-en ! (2009)"],
    facts: ["Sa série animée Bana Boul, en lingala, a été vue des millions de fois sur Internet."],
    awards: [],
  },
  {
    slug: "gaspard-njock",
    name: "Gaspard Njock",
    birthYear: null,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Gaspard Njock est un scénariste et dessinateur camerounais formé à la bande dessinée en Italie. Il y publie son premier album, une biographie de l'imprimeur vénitien Alde Manuce, avant de se faire connaître en France. Un voyage sans retour, paru en 2018, suit un adolescent de Douala jusqu'à Lampedusa et a été salué pour sa justesse sur l'exil des jeunes Africains. Il raconte ensuite l'enfance de Maria Callas dans La Callas : l'enfance d'une diva. Son œuvre mêle grands destins et récits intimes.",
    photo: null,
    photoCredit: null,
    startWith: "un-voyage-sans-retour",
    otherTitles: [],
    awards: [],
  },
  {
    slug: "annick-kamgang",
    name: "Annick Kamgang",
    birthYear: null,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Franco-camerounaise, Annick Kamgang, dite Kam, est la fille d'une mère antillaise et d'Hubert Kamgang, homme politique panafricain camerounais. Elle passe une grande partie de son enfance à Bangui, puis vit aux Antilles avant de venir étudier en France en 2000. Dessinatrice de presse, elle travaille pour Jeune Afrique, Le Monde Afrique ou L'Express. Son premier album, Lucha, raconte avec la journaliste Justine Brabant un mouvement citoyen non violent au Congo. En 2025, elle signe seule Les Enfants du pays, thriller familial sur la guerre d'indépendance du Cameroun.",
    photo: null,
    photoCredit: null,
    startWith: "les-enfants-du-pays",
    otherTitles: ["La Justice contre la force (2024)"],
    awards: [],
  },
  {
    slug: "massire-tounkara",
    name: "Massiré Tounkara",
    birthYear: null,
    deathYear: null,
    countryCode: "ML",
    origin: null,
    bio: "Massiré Tounkara est un dessinateur et illustrateur malien, qui a beaucoup travaillé pour l'édition jeunesse à Bamako, notamment chez Balani's. Il illustre des contes d'Ousmane Diarra et dessine la série écologique Issa et Wassa, sur des scénarios de Mahamadou Traoré. En 2010, il met en images Le Mali de Madi, une BD réalisée pour le cinquantenaire de l'indépendance du pays. Il collabore ensuite avec Christophe Cassiau-Haurie pour Les Dogues noirs de l'Empire, sur la Première Guerre mondiale en Afrique, publié par L'Harmattan BD.",
    photo: null,
    photoCredit: null,
    startWith: "les-dogues-noirs-de-l-empire-la-force-noire",
    otherTitles: [
      "Les Jumeaux à la recherche de leur mère (2003-2005)",
      "La Famille Doumbia (2012)",
    ],
    awards: [],
  },
  {
    slug: "mongo-sise",
    name: "Mongo Sisé",
    birthYear: 1948,
    deathYear: 2008,
    countryCode: "CD",
    origin: null,
    bio: "François-Xavier Mongo Awaï Sisé, dit Mongo Sisé, est né à Kinshasa. Formé à Bruxelles, où il est l'élève d'Hergé, il est considéré comme le précurseur de la bande dessinée en Afrique. Au début des années 1980, Le Boy, aventure de son duo Mata Mata et Pili Pili, fait de lui le premier auteur africain de BD publié en Europe. Il crée aussi Bingo, les aventures d'un enfant africain, une série publiée par la coopération belge. Mort à Kinshasa en 2008, il a laissé des archives d'où L'Harmattan a tiré un inédit, Mokanda illusion, puis une anthologie.",
    photo: null,
    photoCredit: null,
    startWith: "trois-aventures-de-mata-mata-et-pili-pili",
    otherTitles: [
      "Bingo en ville (1982)",
      "Bingo à Yama-Kara (1982)",
      "Bingo en Belgique ou L'Interdépendance (1983)",
      "Bingo au pays Mandio ou La Lutte contre la désertification (1984)",
    ],
    facts: ["Son album Le Boy est le premier d'un auteur africain publié en Europe."],
    awards: [],
  },
  {
    slug: "al-mata",
    name: "Al'Mata",
    birthYear: 1970,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Alain Mata Mamengi, dit Al'Mata, naît à Kinshasa et se forme aux arts graphiques à l'Académie des beaux-arts. Caricaturiste à partir de 1991, il devient directeur artistique du quotidien L'Observateur. Ses dessins, jugés subversifs, lui valent des ennuis sous Mobutu comme sous Laurent-Désiré Kabila, et même une arrestation. En 2002, il profite d'une invitation à un festival en France pour quitter le pays. Il y dessine, sur des scénarios d'Edimo, les aventures d'Alphonse Madiba dit Daudet, devenues l'une des séries phares de L'Harmattan BD.",
    photo: null,
    photoCredit: null,
    startWith: "le-retour-au-pays-d-alphonse-madiba-dit-daudet",
    otherTitles: ["Les Tribulations d'Alphonse Madiba dit Daudet (2016)"],
    awards: [],
  },
  {
    slug: "christian-kingue-epanya",
    name: "Christian Kingue Epanya",
    birthYear: 1956,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Auteur et illustrateur camerounais, Christian Kingue Epanya signe aussi Christian Epanya. Il illustre depuis les années 1990 de nombreux livres pour enfants, dont Le Petit Frère d'Amkoullel d'Amadou Hampâté Bâ, et des biographies de grandes figures africaines. Il écrit et dessine lui-même plusieurs albums, dont Le Taxi-brousse de Papa Diop, devenu un classique de la littérature jeunesse sur l'Afrique. Ses images lumineuses, aux couleurs chaudes, font vivre les villes, les marchés et les villages, du Sénégal au Congo en passant par le Cameroun.",
    photo: null,
    photoCredit: null,
    startWith: "le-taxi-brousse-de-papa-diop",
    otherTitles: [
      "Le Petit Camion de Garoua (2001)",
      "Le Petit Photographe de Bamba (2007)",
      "Comment le désert a disparu (2011)",
      "Papa Diop et son taxi-brousse (2024)",
    ],
    awards: [],
  },
  {
    slug: "thembo-kash",
    name: "Thembo Kash",
    birthYear: 1965,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Thembo Muhindo Kashauri, qui signe Kash, est né à Butembo, dans le Nord-Kivu. Figure de la bande dessinée congolaise, il dessine pour l'éditeur belge Joker la série policière Vanity, sur des scénarios d'André-Paul Duchâteau, le créateur de Ric Hochet. Il signe seul Jungle urbaine, chronique réaliste de Kinshasa, puis dessine Mbote Kinshasa !, où un petit garçon applique la célèbre « débrouille » kinoise. Son trait réaliste sait aussi bien rendre l'atmosphère d'un polar que celle des rues de la capitale.",
    photo: null,
    photoCredit: null,
    startWith: "mbote-kinshasa-article-15",
    otherTitles: [
      "Vanity, t. 1 : La Folie du diable (2007)",
      "Vanity, t. 2 : La Symphonie infernale (2010)",
    ],
    awards: [],
  },
  {
    slug: "alain-kojele",
    name: "Alain Kojélé",
    birthYear: 1975,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Alain Kojélé Makani est un dessinateur et illustrateur congolais. Il publie ses premières bandes dessinées à Kinshasa, comme Elikya, le petit orphelin, avant de participer aux albums du collectif Afro Bulles, fondé en France par Alix Fuilu, aux côtés de Didier Kassaï et Willy Zekid. Il dessine aussi des BD pour la jeunesse, comme Lucas et les racoons, et des albums de commande. Illustrateur très actif, il a mis en images de nombreux contes et recueils, d'Afrique, des Comores ou de l'Égypte ancienne.",
    photo: null,
    photoCredit: null,
    startWith: "sur-les-berges-du-fleuve-congo",
    otherTitles: [
      "Elikya, le petit orphelin (2005)",
      "Zamadrogo fils de Soroba (2006)",
    ],
    awards: [],
  },
  {
    slug: "khp",
    name: "KHP",
    birthYear: 1979,
    deathYear: null,
    countryCode: "CG",
    origin: null,
    bio: "KHP, de son vrai nom Koutawa Hamed Prislay, est né à Brazzaville. Il se forme à l'école de peinture de Poto-Poto, haut lieu de l'art congolais. Enfant pendant la guerre civile de 1997, il commence dès l'année suivante une chronique réaliste de ce conflit. Remarqué lors d'ateliers au Centre culturel français de Pointe-Noire, il publie en 2012 Chroniques de Brazzaville, avec deux autres jeunes artistes. Installé en France depuis 2015, il signe Les Dessous de Pointe-Noire, entièrement dessiné au stylo-bille.",
    photo: null,
    photoCredit: null,
    startWith: "les-dessous-de-pointe-noire",
    otherTitles: [],
    awards: [],
  },
  {
    slug: "koffi-roger-nguessan",
    name: "Koffi Roger N'Guessan",
    birthYear: 1975,
    deathYear: null,
    countryCode: "CI",
    origin: null,
    bio: "Koffi Roger N'Guessan est un dessinateur ivoirien, l'un des auteurs les plus réguliers de la collection L'Harmattan BD. Il débute avec Séductions ; Mille mystères d'Afrique, album double, puis Paris vaille que vaille, sur le mirage de l'émigration. Il dessine ensuite Les Fins Limiers, première BD africaine à énigmes, et adapte Chaka, le grand roman de Thomas Mofolo. Il illustre aussi une histoire du thé et les aventures d'un jeune lézard de Korhogo. En 2023, il a collaboré à un ouvrage de référence sur la bande dessinée en Côte d'Ivoire.",
    photo: null,
    photoCredit: null,
    startWith: "chaka-d-apres-l-oeuvre-de-thomas-mofolo",
    otherTitles: [],
    awards: [],
  },
  {
    slug: "hector-sonon",
    name: "Hector Sonon",
    birthYear: 1970,
    deathYear: null,
    countryCode: "BJ",
    origin: null,
    bio: "Né à Cotonou, Hector Sonon publie ses premiers dessins dans La Gazette du Golfe, premier journal indépendant du Bénin, puis dans le satirique Le Cafard enchaîné. Il se forme lors d'ateliers animés par de grands noms de la BD franco-belge. Caricaturiste, illustrateur de nombreux albums pour enfants et dessinateur de bande dessinée, il signe Koffi Azé, satire politique, et dessine Toubab or not toubab chez Casterman. En 2013, la Fondation Zinsou lui consacre une rétrospective, une première pour un auteur de BD en Afrique francophone.",
    photo: null,
    photoCredit: null,
    startWith: "toubab-or-not-toubab",
    otherTitles: ["Abalo a le palu (2004)"],
    facts: ["En 2013, la Fondation Zinsou de Cotonou lui a consacré une exposition rétrospective."],
    awards: [],
  },
  {
    slug: "dwa",
    name: "Dwa",
    birthYear: 1982,
    deathYear: null,
    countryCode: "MG",
    origin: null,
    bio: "Dwa, de son vrai nom Éric Andriantsialonina, est né dans un village des hautes terres de Madagascar avant que sa famille ne s'installe à Tananarive en 1993. Étudiant en économie, il dessine en parallèle et publie ses premières planches lors du festival Madabulles. Il participe au magazine satirique Saringotra, puis forme avec Pov un duo qui raconte la politique malgache à travers des élections étudiantes, de Mégacomplots à Tananarive à Dictature à Brickaville. Il signe aussi des reportages et carnets de voyage dessinés.",
    photo: null,
    photoCredit: null,
    startWith: "cout-d-etat-a-tamatave",
    otherTitles: [
      "Lundi noir sur l'île rouge (2017)",
      "Dictature à Brickaville (2020)",
      "Un gasy à Paris (2020)",
    ],
    awards: [],
  },
  {
    slug: "gilbert-g-groud",
    name: "Gilbert G. Groud",
    birthYear: null,
    deathYear: null,
    countryCode: "CI",
    origin: null,
    bio: "Gnangbei Gilbert, dit Groud G. Gilbert, est né vers 1956 dans l'ouest de la Côte d'Ivoire, fils d'un sculpteur et d'une chanteuse. Il étudie à l'Institut national des arts d'Abidjan, puis fait carrière comme maquettiste et directeur artistique dans des agences de publicité. Peintre reconnu, il se lance dans la bande dessinée avec Magie noire, publié par Albin Michel, une plongée dans l'univers de la sorcellerie en Afrique. Un second tome paraît en 2008.",
    photo: null,
    photoCredit: null,
    startWith: "magie-noire",
    otherTitles: ["Magie noire, t. 2 (2008)"],
    awards: [],
  },
];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {
  "serge-diantantu": { photo: "/authors/serge-diantantu.webp", credit: "Photo : G.Garitan · CC BY-SA 4.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Serge_Diantantu_00035.jpg" },
  "adjim-danngar": { photo: "/authors/adjim-danngar.webp", credit: "Photo : G.Garitan · CC BY-SA 4.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Adjim_Danngar_Falala_1542845.jpg" },
  "didier-viode": { photo: "/authors/didier-viode.webp", credit: "Photo : Didier Viodé · CC BY-SA 4.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Photo_portrait_de_l%27atriste_Didier-Viod%C3%A9.jpg" },
  "hallain-paluku": { photo: "/authors/hallain-paluku.webp", credit: "Photo : Ngilozi · CC BY-SA 3.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hallain_Paluku.jpg" },
  "annick-kamgang": { photo: "/authors/annick-kamgang.webp", credit: "Photo : Kam237971 · CC0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Autoportrait_AnnickKamgangKam_01.jpg" },
  "christian-kingue-epanya": { photo: "/authors/christian-kingue-epanya.webp", credit: "Photo : Vogler · CC BY-SA 3.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Christian_Epanya.jpg" },
  "hector-sonon": { photo: "/authors/hector-sonon.webp", credit: "Photo : Ekpene · CC BY-SA 3.0 · Wikimedia Commons", source: "https://commons.wikimedia.org/wiki/File:Hector_Sonon.JPG" },
};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "simon-kimbangu-la-voix-du-peuple-opprime", "simon-kimbangu-lipanda-dia-zole", "la-petite-djily-et-mere-mamou", "femme-noire-d-afrique-d-amerique-et-des-antilles", "bulambemba", "en-naviguant-vers-les-indes", "l-embarquement-de-bois-d-ebene", "ile-de-goree", "colonies-des-antilles-et-de-l-ocean-indien", "felix-eboue-heros-de-la-france-libre", "mamie-denis-evadee-de-la-maison-de-retraite", "djarabane-au-petit-marche-des-amours-perdues", "etranger-sans-rendez-vous", "vive-la-corruption", "yao-visa-refuse", "missy", "rugbill", "un-voyage-sans-retour", "la-callas-l-enfance-d-une-diva", "lucha-chronique-d-une-revolution-sans-armes-au-congo", "les-enfants-du-pays", "issa-et-wassa-woroni-du-bafing", "issa-et-wassa-le-forestier-du-baoule", "le-mali-de-madi", "les-dogues-noirs-de-l-empire-la-force-noire", "mokanda-illusion", "trois-aventures-de-mata-mata-et-pili-pili", "le-retour-au-pays-d-alphonse-madiba-dit-daudet", "le-retour-en-france-d-alphonse-madiba-dit-daudet", "revoir-paris", "le-taxi-brousse-de-papa-diop", "le-grand-retour-du-taxi-brousse-de-papa-diop", "koumen-et-le-vieux-sage-de-la-montagne", "malin-comme-10-singes", "mes-images-du-senegal", "la-pipe-de-tita-nveng", "le-pagne-bleu", "les-rois-de-la-sape", "jungle-urbaine-lola", "mbote-kinshasa-article-15", "vies-volees", "sur-les-berges-du-fleuve-congo", "bienvenue-a-saint-germain-les-corbeil", "djoumaelle-et-yarhi", "lucas-et-les-racoons", "chroniques-de-brazzaville", "les-dessous-de-pointe-noire", "seductions-mille-mysteres-d-afrique", "paris-vaille-que-vaille", "les-fins-limiers", "chaka-d-apres-l-oeuvre-de-thomas-mofolo", "legere-amertume-une-histoire-du-the", "moi-borg-enfant-de-korhogo", "koffi-aze", "toubab-or-not-toubab", "les-aventures-de-zinsou-et-sagbo-le-temple-des-pythons", "megacomplots-a-tananarive", "cout-d-etat-a-tamatave", "la-reunion-kely", "back-to-al-bak", "magie-noire",
];
