/**
 * Lot 07 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Auteurs traduits : Ngũgĩ, Coetzee, Mandela, Achebe, Adichie, Gyasi, Soyinka, Gurnah, Couto.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });
const trad = (name: string) => ({ role: "traducteur" as const, name, authorSlug: null });

const NGUGI = auteur("Ngũgĩ wa Thiong'o", "ngugi-wa-thiongo");
const COETZEE = auteur("J. M. Coetzee", "j-m-coetzee");
const MANDELA = auteur("Nelson Mandela", "nelson-mandela");
const ACHEBE = auteur("Chinua Achebe", "chinua-achebe");
const ADICHIE = auteur("Chimamanda Ngozi Adichie", "chimamanda-ngozi-adichie");
const GYASI = auteur("Yaa Gyasi", "yaa-gyasi");
const SOYINKA = auteur("Wole Soyinka", "wole-soyinka");
const GURNAH = auteur("Abdulrazak Gurnah", "abdulrazak-gurnah");
const COUTO = auteur("Mia Couto", "mia-couto");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Ngũgĩ wa Thiong'o
  livre({
    slug: "ne-pleure-pas-mon-enfant",
    title: "Ne pleure pas, mon enfant",
    contributors: [NGUGI, trad("Dominique Lanni")],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "ecole", "colonisation", "famille"],
    summary:
      "Dans le Kenya des années 1950, le petit Njoroge est le premier de sa famille à aller à l'école, et il y place tous ses espoirs. Son père, Ngotho, travaille sur une terre ancestrale devenue la propriété d'un colon blanc. Autour d'eux monte la révolte des Mau Mau, qui divise les familles et les villages. Njoroge s'accroche à ses livres et à son amitié avec Mwihaki, fille d'un notable rallié aux Anglais, tandis que la violence se rapproche.",
    whyRead: [
      "Le premier roman de Ngũgĩ, et l'un des premiers romans anglophones d'Afrique de l'Est.",
      "L'insurrection Mau Mau vue à hauteur d'enfant.",
      "Une belle histoire de foi dans l'école, face à l'histoire qui s'emballe.",
    ],
    year: 1964,
    originalLanguage: "anglais",
    publisher: "Passage(s)",
    pages: 243,
    isbn: "9791094898406",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-riviere-de-vie",
    title: "La Rivière de vie",
    contributors: [NGUGI, trad("Julie Senghor")],
    genre: "roman",
    audience: "adulte",
    themes: ["tradition", "colonisation", "spiritualite", "amour"],
    summary:
      "Deux collines kikuyu se font face de part et d'autre d'une rivière : Kameno reste fidèle aux coutumes, Makuyu s'est tournée vers la mission chrétienne. Le jeune Waiyaki, descendant d'une lignée de voyants, est envoyé à l'école des Blancs pour apprendre leur savoir et en faire une arme. Revenu chez les siens, il ouvre des écoles et rêve de réconcilier les deux camps. Mais la question de l'excision et son amour pour Nyambura, fille d'un pasteur intransigeant, rallument les querelles.",
    whyRead: [
      "Un roman fondateur sur le choc entre traditions et christianisme au Kenya.",
      "Un héros jeune et idéaliste, pris entre deux mondes.",
      "Un récit court, au rythme d'une tragédie.",
    ],
    year: 1965,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 281,
    isbn: "9782708709133",
    format: null,
    awards: [],
  }),
  livre({
    slug: "et-le-ble-jaillira",
    title: "Et le blé jaillira",
    contributors: [NGUGI, trad("Jacques Denève")],
    genre: "roman",
    audience: "adulte",
    themes: ["independances", "guerre", "histoire", "politique"],
    summary:
      "Décembre 1963 : le Kenya s'apprête à fêter son indépendance. Dans le village de Thabai, on prépare une cérémonie en l'honneur de Kihika, héros de la lutte pendu par les Anglais, et on cherche celui qui l'a trahi. On veut aussi que Mugo, un homme solitaire admiré pour avoir souffert dans les camps, prenne la parole. Par retours en arrière, Ngũgĩ suit plusieurs villageois que l'état d'urgence a marqués et qui portent chacun leurs blessures et leurs secrets.",
    whyRead: [
      "Le grand roman de l'indépendance kényane, par l'auteur de « Rêver en temps de guerre ».",
      "Une construction en puzzle où chaque personnage cache quelque chose.",
      "Une réflexion profonde sur la trahison, la culpabilité et la liberté.",
    ],
    year: 1967,
    originalLanguage: "anglais",
    publisher: "Julliard",
    pages: 411,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "petales-de-sang",
    title: "Pétales de sang",
    contributors: [NGUGI, trad("Josette Mane")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "independances", "travail", "tradition"],
    summary:
      "Trois dirigeants d'une brasserie meurent dans un incendie à Ilmorog, une petite ville née d'un ancien village. La police interroge quatre suspects : Munira, l'instituteur, Abdulla, l'ancien combattant devenu boutiquier, Wanja, la jeune femme indépendante, et Karega, le militant. En remontant le fil de leurs vies, depuis l'année de la grande sécheresse et la marche du village vers Nairobi, le roman raconte comment le Kenya indépendant a laissé les puissants confisquer ses promesses.",
    whyRead: [
      "Le roman le plus ample et le plus engagé de Ngũgĩ.",
      "Une enquête policière qui devient la fresque d'un pays.",
      "Le livre qui précéda l'emprisonnement de son auteur, en 1977.",
    ],
    year: 1977,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 476,
    isbn: "9782708704565",
    format: null,
    awards: [],
  }),
  livre({
    slug: "decoloniser-l-esprit",
    title: "Décoloniser l'esprit",
    contributors: [NGUGI, trad("Sylvain Prudhomme")],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "identite", "ecole", "politique"],
    summary:
      "Pourquoi un écrivain africain devrait-il écrire dans la langue de l'ancien colonisateur ? Dans cet essai devenu un classique, Ngũgĩ raconte son enfance, l'école où l'on punissait les élèves qui parlaient kikuyu, puis son théâtre populaire en langue kikuyu qui lui valut la prison. Il explique pourquoi il a choisi d'écrire désormais dans sa langue maternelle. Une réflexion claire sur la langue, la mémoire et la liberté.",
    whyRead: [
      "Un texte essentiel pour comprendre les débats sur les langues en Afrique.",
      "Un essai vivant, nourri de souvenirs personnels.",
      "Le livre où Ngũgĩ dit adieu à l'anglais comme langue d'écriture.",
    ],
    year: 1986,
    originalLanguage: "anglais",
    publisher: "La Fabrique",
    pages: 167,
    isbn: "9782358720199",
    format: null,
    awards: [],
  }),
  livre({
    slug: "pour-une-afrique-libre",
    title: "Pour une Afrique libre",
    contributors: [NGUGI, trad("Samuel Sfez")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "colonisation", "identite"],
    summary:
      "Dans ces textes courts, Ngũgĩ revient sur l'histoire du continent, de l'esclavage à la colonisation et aux indépendances. Il plaide pour une Afrique qui maîtrise ses ressources, ses langues et ses récits, et qui cesse de se penser à travers le regard des autres. Il y évoque aussi le Kenya, la mémoire des combattants Mau Mau et le rôle des intellectuels. Un livre engagé, accessible, qui prolonge le combat de toute une vie.",
    whyRead: [
      "Une porte d'entrée simple dans la pensée politique de Ngũgĩ.",
      "Des textes courts, faciles à lire et à discuter.",
      "Un appel à penser l'avenir de l'Afrique depuis l'Afrique.",
    ],
    year: 2016,
    originalLanguage: "anglais",
    publisher: "Philippe Rey",
    pages: 139,
    isbn: "9782848765815",
    format: null,
    awards: [],
  }),
  livre({
    slug: "combattants-et-martyrs",
    title: "Combattants et martyrs",
    contributors: [NGUGI, trad("Dominique Lanni")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["colonisation", "guerre", "independances"],
    summary:
      "Ces nouvelles, choisies dans le recueil « Secret Lives », dressent une galerie de portraits kényans. On y croise des anonymes, des combattants et des victimes, à l'époque coloniale, pendant la révolte des Mau Mau puis dans les années qui suivent l'indépendance. Ngũgĩ passe du tragique au comique pour dire les espoirs et les désillusions d'un peuple. Un bon moyen de découvrir son univers en peu de pages.",
    whyRead: [
      "Des nouvelles inédites en français jusqu'en 2019.",
      "Trois moments de l'histoire du Kenya en quelques portraits.",
      "Une porte d'entrée idéale dans l'œuvre de Ngũgĩ.",
    ],
    year: 2019,
    originalLanguage: "anglais",
    publisher: "Passage(s)",
    pages: 150,
    isbn: "9791094898383",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "les-neuf-parfaites",
    title: "Les Neuf Parfaites",
    subtitle: "L'épopée de Gĩkũyũ et Mũmbi",
    contributors: [NGUGI, trad("Laurent Vannini")],
    genre: "poesie",
    audience: "adulte",
    themes: ["contes", "femmes", "tradition", "famille"],
    summary:
      "Ngũgĩ reprend en vers le mythe des origines du peuple kikuyu. Gĩkũyũ et Mũmbi ont dix filles, que l'on appelle pourtant « les Neuf Parfaites ». Quand des prétendants venus de loin demandent leur main, les parents leur imposent une longue quête pleine d'épreuves et de monstres. Une épopée moderne qui fait la part belle aux femmes, écrite d'abord en kikuyu par l'auteur lui-même.",
    whyRead: [
      "Un grand mythe fondateur du Kenya, raconté comme une épopée.",
      "Des héroïnes au centre de l'histoire.",
      "L'un des derniers grands livres de Ngũgĩ, écrit dans sa langue.",
    ],
    year: 2018,
    originalLanguage: "kikuyu",
    publisher: "Présence africaine",
    pages: 141,
    isbn: "9782708710085",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ J. M. Coetzee
  livre({
    slug: "terres-de-crepuscule",
    title: "Terres de crépuscule",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "guerre", "histoire"],
    summary:
      "Le premier livre de Coetzee réunit deux récits que trois siècles séparent. Dans le premier, un spécialiste de la guerre psychologique travaille pour l'armée américaine au temps du Vietnam et s'enfonce peu à peu dans la folie. Dans le second, Jacobus Coetzee, un colon hollandais du XVIIIe siècle, raconte son expédition au-delà du fleuve Orange, chez les Namaquas. Deux voix glaçantes qui montrent la violence de l'esprit de conquête.",
    whyRead: [
      "Le premier livre de Coetzee, déjà audacieux et dérangeant.",
      "Deux récits en miroir sur la violence coloniale.",
      "Pour comprendre d'où vient l'un des grands écrivains du XXe siècle.",
    ],
    year: 1974,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 186,
    isbn: "9782020826051",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "au-coeur-de-ce-pays",
    title: "Au cœur de ce pays",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "femmes", "identite"],
    summary:
      "Magda vit seule avec son père dans une ferme isolée du Karoo, en Afrique du Sud. Vieille fille aigrie, elle tient le journal de sa vie en courts paragraphes numérotés. Quand son père prend pour maîtresse la jeune épouse d'un de leurs ouvriers noirs, l'équilibre de la ferme se brise. Dans ce monologue halluciné, on ne sait plus toujours ce qui est réel et ce que Magda imagine.",
    whyRead: [
      "Un monologue intérieur puissant, d'une grande liberté de forme.",
      "La solitude et la violence d'une ferme perdue dans le Karoo.",
      "Adapté au cinéma par Marion Hänsel sous le titre « Dust ».",
    ],
    year: 1977,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 221,
    isbn: "9782757807187",
    format: "poche",
    awards: [],
    adaptations: [{ kind: "film", title: "Dust", year: 1985, by: "Marion Hänsel" }],
  }),
  livre({
    slug: "en-attendant-les-barbares",
    title: "En attendant les barbares",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "colonisation", "guerre"],
    summary:
      "Dans une ville fortifiée aux confins d'un Empire sans nom, un vieux magistrat mène une vie tranquille. Un jour arrive le colonel Joll, venu de la capitale pour enquêter sur une attaque supposée des « barbares », les nomades qui vivent au-delà des murs. Les interrogatoires et la torture commencent. Le magistrat recueille une jeune nomade blessée et, peu à peu, ne peut plus fermer les yeux.",
    whyRead: [
      "Une fable intemporelle sur la peur de l'autre et la torture.",
      "Un roman bref et parfait, souvent cité comme le chef-d'œuvre de Coetzee.",
      "Adapté au cinéma et à l'opéra.",
    ],
    year: 1980,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 248,
    isbn: "9782020404563",
    format: "poche",
    awards: [{ name: "James Tait Black Memorial Prize", year: 1980 }],
    adaptations: [
      { kind: "opéra", title: "Waiting for the Barbarians", year: 2005, by: "Philip Glass" },
      { kind: "film", title: "Waiting for the Barbarians", year: 2019, by: "Ciro Guerra" },
    ],
  }),
  livre({
    slug: "michael-k-sa-vie-son-temps",
    title: "Michael K, sa vie, son temps",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "famille", "politique"],
    summary:
      "Une guerre civile ravage l'Afrique du Sud. Michael K, jardinier au Cap, homme simple au bec-de-lièvre, décide d'emmener sa mère malade vers la ferme de son enfance, à la campagne. Faute de permis, il la pousse dans une brouette sur les routes, entre barrages et camps. Commence alors l'errance d'un homme qui ne demande qu'à cultiver la terre en paix, loin des armes et des règlements.",
    whyRead: [
      "Le premier Booker Prize de Coetzee.",
      "Un héros inoubliable, fragile et obstiné.",
      "Un roman sur la liberté d'un homme qui refuse d'entrer dans la guerre.",
    ],
    year: 1983,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 229,
    isbn: "9791041411252",
    format: "poche",
    awards: [{ name: "Booker Prize", year: 1983 }],
  }),
  livre({
    slug: "foe",
    title: "Foe",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "femmes", "identite"],
    summary:
      "Au XVIIIe siècle, Susan Barton fait naufrage sur l'île de Robinson Cruso. Elle y découvre un homme bougon et Vendredi, son serviteur noir à qui l'on a coupé la langue. Revenue à Londres, elle demande à l'écrivain Daniel Foe de faire de son aventure un livre. Coetzee réécrit le célèbre roman de Defoe pour poser une question simple : qui a le droit de raconter l'histoire, et qui reste réduit au silence ?",
    whyRead: [
      "Une relecture brillante de « Robinson Crusoé ».",
      "Une femme et un esclave muet au centre d'un mythe européen.",
      "Un roman court qui fait réfléchir au pouvoir des récits.",
    ],
    year: 1986,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 169,
    isbn: "9782020476935",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-age-de-fer",
    title: "L'Âge de fer",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "famille", "ville"],
    summary:
      "Au Cap, à la fin des années 1980, Mrs Curren, une ancienne professeure de lettres classiques, apprend qu'elle a un cancer. Elle écrit une longue lettre à sa fille partie vivre en Amérique. Le jour même, un sans-abri s'installe devant chez elle. Tandis que les townships s'embrasent, cette femme blanche découvre de près la violence de l'apartheid, à travers le fils de sa domestique et ses camarades.",
    whyRead: [
      "Le portrait bouleversant d'une femme face à la mort et à l'injustice.",
      "L'Afrique du Sud des dernières années de l'apartheid.",
      "Une écriture limpide et grave.",
    ],
    year: 1990,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 223,
    isbn: "9782020476928",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-maitre-de-petersbourg",
    title: "Le Maître de Pétersbourg",
    contributors: [COETZEE, trad("Sophie Mayoux")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "politique", "histoire"],
    summary:
      "En 1869, l'écrivain Fiodor Dostoïevski revient en secret à Saint-Pétersbourg. Son beau-fils Pavel vient d'y mourir dans des circonstances troubles. Logé dans la chambre du jeune homme, il cherche à comprendre ce qui s'est passé et découvre que Pavel fréquentait des révolutionnaires. Coetzee imagine un Dostoïevski rongé par le deuil, au moment où naît en lui un nouveau roman.",
    whyRead: [
      "Un roman sur le deuil d'un père, porté par Dostoïevski lui-même.",
      "Une plongée dans la Russie des révolutionnaires du XIXe siècle.",
      "Coetzee dialogue avec l'un de ses grands maîtres.",
    ],
    year: 1994,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 267,
    isbn: "9782020638920",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "scenes-de-la-vie-d-un-jeune-garcon",
    title: "Scènes de la vie d'un jeune garçon",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "famille", "ecole", "identite"],
    summary:
      "Coetzee raconte son enfance à la troisième personne, dans les années 1950. Le garçon vit à Worcester, une petite ville de province près du Cap, avec un père qu'il méprise et une mère qu'il adore. À l'école, il cache qu'il n'est ni vraiment afrikaner, ni vraiment anglais, ni catholique comme il l'a prétendu. Il découvre peu à peu le monde des adultes et la société de l'apartheid.",
    whyRead: [
      "Le premier volet de l'autobiographie de Coetzee.",
      "Une enfance sud-africaine racontée avec une honnêteté sans pitié.",
      "Un récit court, précis, souvent drôle malgré lui.",
    ],
    year: 1997,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 189,
    isbn: "9782020525770",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "vers-l-age-d-homme",
    title: "Vers l'âge d'homme",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "recit",
    audience: "adulte",
    themes: ["exil", "identite", "travail", "ville"],
    summary:
      "Au début des années 1960, le jeune John quitte l'Afrique du Sud pour Londres. Il veut devenir poète et vivre une grande vie d'artiste. En attendant, il travaille comme programmeur chez IBM, s'ennuie dans des chambres meublées et accumule les liaisons ratées. Dans ce deuxième volet de son autobiographie, Coetzee regarde son jeune moi avec une ironie impitoyable.",
    whyRead: [
      "La suite de « Scènes de la vie d'un jeune garçon ».",
      "Le Londres des années 1960 vu par un jeune exilé solitaire.",
      "Un portrait de l'artiste en jeune homme, sans complaisance.",
    ],
    year: 2002,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 231,
    isbn: "9782020685344",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "elizabeth-costello",
    title: "Elizabeth Costello",
    subtitle: "Huit leçons",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "famille", "spiritualite"],
    summary:
      "Elizabeth Costello est une romancière australienne vieillissante et célèbre. On l'invite partout pour des conférences : sur le réalisme en littérature, sur le roman africain, sur la cruauté envers les animaux, sur le mal. Ses prises de position choquent, ses proches s'agacent, elle-même doute. En huit « leçons », Coetzee mêle récit et débat d'idées autour d'un personnage aussi attachant qu'irritant.",
    whyRead: [
      "Un roman d'idées original, construit comme une suite de conférences.",
      "Un personnage de vieille écrivaine qui revient dans plusieurs livres de Coetzee.",
      "Des pages fortes sur notre rapport aux animaux.",
    ],
    year: 2003,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 310,
    isbn: "9782020864770",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-homme-ralenti",
    title: "L'Homme ralenti",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "exil", "identite"],
    summary:
      "À Adélaïde, en Australie, Paul Rayment, photographe à la retraite, est renversé par une voiture alors qu'il roule à vélo. Amputé d'une jambe, il refuse la prothèse et s'enferme dans son appartement. Il tombe amoureux de Marijana, l'infirmière croate qui s'occupe de lui, mère de famille et mariée. Survient alors Elizabeth Costello, la romancière, qui semble tout savoir de lui.",
    whyRead: [
      "Un roman sur la vieillesse, la dépendance et le désir.",
      "Le retour étonnant du personnage d'Elizabeth Costello.",
      "Un jeu subtil entre l'écrivain et ses personnages.",
    ],
    year: 2005,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 310,
    isbn: "9782757806265",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "journal-d-une-annee-noire",
    title: "Journal d'une année noire",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "amour", "identite"],
    summary:
      "Un vieil écrivain sud-africain installé en Australie, nommé « JC », rédige pour un éditeur allemand des opinions tranchées sur la politique et le monde. Il engage pour les taper Anya, une jeune et jolie voisine, dont le compagnon, Alan, voit dans le vieil homme une proie. Chaque page est divisée en trois bandes : les essais de JC, ses pensées, et la voix d'Anya. Un roman inventif, à lire à plusieurs niveaux.",
    whyRead: [
      "Une forme unique : trois récits qui se lisent sur la même page.",
      "Un regard lucide sur la politique au début du XXIe siècle.",
      "Un trio de personnages à la fois drôle et inquiétant.",
    ],
    year: 2007,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 282,
    isbn: "9782757815151",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-ete-de-la-vie",
    title: "L'Été de la vie",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "recit",
    audience: "adulte",
    themes: ["identite", "famille", "amour"],
    summary:
      "Un jeune biographe anglais enquête sur l'écrivain John Coetzee, qu'il présente comme mort. Il interroge des personnes qui l'ont connu dans les années 1970, quand il vivait avec son père au Cap : une ancienne maîtresse, une cousine, une danseuse brésilienne, des collègues. De leurs souvenirs se dégage le portrait d'un homme maladroit, peu aimable et mal à l'aise avec les autres. Le troisième volet de l'autobiographie, en forme de jeu de miroirs.",
    whyRead: [
      "Une autobiographie où l'auteur se fait raconter par les autres.",
      "Un autoportrait cruel et souvent drôle.",
      "Le troisième volet après « Scènes de la vie d'un jeune garçon ».",
    ],
    year: 2009,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 306,
    isbn: "9782757824641",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "une-enfance-de-jesus",
    title: "Une enfance de Jésus",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "enfance", "famille"],
    summary:
      "Simón et le petit David arrivent par bateau à Novilla, une ville où les migrants reçoivent un nouveau nom, un nouvel âge et un travail, après avoir tout oublié de leur vie passée. L'enfant a perdu sa mère, et Simón, qui n'est pas son père, s'est promis de la retrouver. Dans cette ville où tout le monde est gentil et sans passion, il choisit une femme, Inés, pour l'élever. Mais David est un enfant à part.",
    whyRead: [
      "Une fable étrange et captivante sur l'exil et l'oubli.",
      "Un enfant mystérieux qui pose les grandes questions.",
      "Le premier volet de la trilogie de Jésus.",
    ],
    year: 2013,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 355,
    isbn: "9782757845271",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-education-de-jesus",
    title: "L'Éducation de Jésus",
    contributors: [COETZEE, trad("Georges Lory")],
    genre: "roman",
    audience: "adulte",
    themes: ["ecole", "enfance", "famille"],
    summary:
      "Simón, Inés et le jeune David ont quitté Novilla pour Estrella, une ville de province. David a maintenant six ans et refuse toujours l'école ordinaire. Ses parents l'inscrivent dans une académie de danse où l'on apprend à faire descendre les nombres du ciel. Mais un drame survient dans l'école et bouleverse leur petite famille.",
    whyRead: [
      "La suite d'« Une enfance de Jésus ».",
      "Une réflexion originale sur l'éducation et la liberté des enfants.",
      "Un roman philosophique qui se lit comme un conte.",
    ],
    year: 2016,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 306,
    isbn: "9782757871775",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-mort-de-jesus",
    title: "La Mort de Jésus",
    contributors: [COETZEE, trad("Georges Lory")],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "spiritualite"],
    summary:
      "David a dix ans et ne vit que pour le football. Quand le directeur d'un orphelinat lui propose de rejoindre son équipe, il décide de quitter Simón et Inés. Mais il tombe malade, d'un mal que les médecins ne comprennent pas. Autour de son lit, enfants et adultes écoutent ses paroles comme un message. Le dernier volet de la trilogie de Jésus.",
    whyRead: [
      "La fin de la trilogie commencée avec « Une enfance de Jésus ».",
      "Un livre bref, émouvant, sur le sens qu'on donne aux vies.",
      "Coetzee au sommet de son art du dépouillement.",
    ],
    year: 2019,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 234,
    isbn: "9791041410569",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-polonais",
    title: "Le Polonais",
    contributors: [COETZEE, trad("Sabine Porte")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "exil", "identite"],
    summary:
      "Witold Walczykiewicz, pianiste polonais de plus de soixante-dix ans, spécialiste de Chopin, vient donner un concert à Barcelone. Beatriz, la dame mariée et cultivée qui l'a invité, le trouve un peu ridicule. Mais le vieil homme tombe amoureux d'elle et refuse d'abandonner. Coetzee raconte avec finesse un amour tardif, fait de malentendus, de langues mal partagées et de poèmes.",
    whyRead: [
      "Un roman court et élégant sur un amour à contretemps.",
      "Chopin, Barcelone et Majorque en toile de fond.",
      "Le dernier roman de Coetzee, paru d'abord en espagnol.",
    ],
    year: 2023,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 160,
    isbn: "9791041420063",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "trois-histoires",
    title: "Trois histoires",
    contributors: [COETZEE, trad("Catherine Lauga du Plessis"), trad("Georges Lory")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["identite", "famille", "histoire"],
    summary:
      "Ce petit livre réunit trois textes brefs. Dans « Une maison en Espagne », un homme achète une vieille maison dans un village catalan et s'interroge sur ce que signifie posséder un lieu. « La ferme » suit un écrivain qui retourne régulièrement dans une ferme familiale du Karoo, devenue un relais touristique. « Lui et son homme », discours prononcé lors du prix Nobel, revient à Robinson Crusoé et à son créateur.",
    whyRead: [
      "Trois textes courts pour découvrir Coetzee en une soirée.",
      "On y trouve le discours de réception du prix Nobel.",
      "Une réflexion sobre sur les lieux qui nous attachent.",
    ],
    year: 2016,
    originalLanguage: "anglais",
    publisher: "Seuil",
    pages: 69,
    isbn: "9782021305616",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-abattoir-de-verre",
    title: "L'Abattoir de verre",
    contributors: [COETZEE, trad("Georges Lory")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["famille", "identite", "spiritualite"],
    summary:
      "On retrouve dans ces nouvelles Elizabeth Costello, la romancière vieillissante chère à Coetzee. Ses enfants, John et Helen, s'inquiètent : elle vit seule en Espagne, entourée de chats, et refuse de se laisser aider. Elle continue aussi de défendre la cause des animaux, jusqu'à imaginer un abattoir aux murs de verre. Des récits brefs sur la vieillesse, la mort et notre façon de traiter les bêtes.",
    whyRead: [
      "Le retour d'Elizabeth Costello, l'un des grands personnages de Coetzee.",
      "Des nouvelles courtes sur la vieillesse et la cause animale.",
      "Un livre qui bouscule nos habitudes.",
    ],
    year: 2018,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: null,
    isbn: "9782757876008",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "paysage-sud-africain",
    title: "Paysage sud-africain",
    contributors: [COETZEE, trad("Anne-Laure Jourdain")],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "identite", "histoire"],
    summary:
      "Comment les écrivains et les peintres blancs ont-ils regardé le paysage sud-africain ? Dans ce court essai, Coetzee montre que les modèles européens du pittoresque et du sublime collaient mal à ces terres sèches et immenses. Il montre aussi que ces paysages décrits comme vides effaçaient ceux qui y vivaient déjà. Une lecture brève pour comprendre le lien entre colonisation et regard porté sur la terre.",
    whyRead: [
      "Un essai très court, clair et stimulant.",
      "Pour comprendre comment les colons ont imaginé l'Afrique du Sud.",
      "Une clé de lecture pour les romans de Coetzee.",
    ],
    year: 1988,
    originalLanguage: "anglais",
    publisher: "Verdier",
    pages: 59,
    isbn: "9782864325178",
    format: null,
    awards: [],
  }),
  livre({
    slug: "doubler-le-cap",
    title: "Doubler le cap",
    subtitle: "Essais et entretiens",
    contributors: [COETZEE, trad("Jean-Louis Cornille")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "histoire"],
    summary:
      "Ce recueil rassemble des essais littéraires de Coetzee et de longs entretiens où il parle de son travail. Il y est question de la censure, de l'autobiographie, de la confession, et des écrivains qui l'ont marqué. Entre les textes, l'auteur, d'ordinaire si discret, se livre sur sa manière d'écrire et sur sa place d'écrivain blanc en Afrique du Sud. Pour les lecteurs qui veulent aller plus loin.",
    whyRead: [
      "Coetzee parle de son œuvre, ce qu'il fait rarement.",
      "Des réflexions précieuses sur la censure et la confession.",
      "Un compagnon idéal pour relire ses romans.",
    ],
    year: 1992,
    originalLanguage: "anglais",
    publisher: "Seuil",
    pages: 343,
    isbn: "9782020817271",
    format: null,
    awards: [],
  }),
  livre({
    slug: "de-la-lecture-a-l-ecriture",
    title: "De la lecture à l'écriture",
    subtitle: "Chroniques littéraires, 2000-2005",
    contributors: [COETZEE, trad("Jean-François Sené")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "histoire"],
    summary:
      "Entre 2000 et 2005, Coetzee a écrit des articles et des préfaces sur des écrivains qu'il admire ou qui l'intriguent. On y croise Walter Benjamin, Faulkner, Philip Roth, García Márquez, V. S. Naipaul ou Nadine Gordimer. Chaque texte présente une vie et une œuvre avec clarté et sans jargon. Une invitation à lire, par un grand lecteur.",
    whyRead: [
      "Des portraits d'écrivains clairs et passionnants.",
      "Une bibliothèque idéale commentée par un prix Nobel.",
      "Des textes courts qu'on peut lire dans le désordre.",
    ],
    year: 2007,
    originalLanguage: "anglais",
    publisher: "Seuil",
    pages: 313,
    isbn: "9782020985949",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ici-et-maintenant",
    title: "Ici & maintenant",
    subtitle: "Correspondance, 2008-2011",
    contributors: [COETZEE, { role: "auteur", name: "Paul Auster", authorSlug: null }, trad("Céline Curiol"), trad("Catherine Lauga du Plessis")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique"],
    summary:
      "En 2008, Coetzee propose à l'écrivain américain Paul Auster de s'écrire régulièrement. Pendant trois ans, les deux romanciers échangent des lettres sur tout : l'amitié, le sport, la crise financière, Israël et la Palestine, la vieillesse, le métier d'écrire. Le ton est amical, curieux, parfois en désaccord. Une conversation entre deux grands auteurs, à lire comme un journal à deux voix.",
    whyRead: [
      "Une rare correspondance entre deux grands romanciers vivants.",
      "Des sujets variés, du football à la politique.",
      "Coetzee comme on le connaît peu : chaleureux et curieux.",
    ],
    year: 2013,
    originalLanguage: "anglais",
    publisher: "Actes Sud",
    pages: 314,
    isbn: "9782330024673",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-verite-du-recit",
    title: "La Vérité du récit",
    subtitle: "Conversations sur le réel et la fiction",
    contributors: [COETZEE, { role: "auteur", name: "Arabella Kurtz", authorSlug: null }, trad("Aline Weill")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "histoire"],
    summary:
      "Un romancier et une psychothérapeute britannique, Arabella Kurtz, dialoguent par lettres. Ils se demandent ce qu'est une « bonne histoire », celle qu'on se raconte sur soi-même ou celle qu'une nation se raconte sur son passé. Ils parlent de vérité et de mensonge, de mémoire, de culpabilité, et de l'Afrique du Sud. Un échange exigeant mais clair entre littérature et psychologie.",
    whyRead: [
      "Un dialogue original entre un écrivain et une thérapeute.",
      "Des questions qui touchent chacun : que vaut l'histoire qu'on se raconte ?",
      "Un regard neuf sur la mémoire collective sud-africaine.",
    ],
    year: 2015,
    originalLanguage: "anglais",
    publisher: "Albin Michel",
    pages: 182,
    isbn: "9782226314925",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Nelson Mandela
  livre({
    slug: "conversations-avec-moi-meme",
    title: "Conversations avec moi-même",
    subtitle: "Lettres de prison, notes et carnets intimes",
    contributors: [MANDELA, trad("Maxime Berrée")],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "histoire", "famille"],
    summary:
      "Ce livre rassemble des archives personnelles de Nelson Mandela : lettres écrites en prison, notes griffonnées sur des calendriers, pages de carnets, transcriptions d'entretiens et un projet de suite à son autobiographie. On y découvre l'homme derrière le symbole, avec ses doutes, ses colères, son humour et son amour pour les siens. Les textes couvrent plus de soixante ans de vie, des années de lutte à la présidence.",
    whyRead: [
      "Mandela dans l'intimité, en ses propres mots.",
      "Des documents rares, des années de prison à la présidence.",
      "Le complément idéal d'« Un long chemin vers la liberté ».",
    ],
    year: 2010,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 505,
    isbn: "9791041410415",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "lettres-de-prison",
    title: "Lettres de prison",
    contributors: [MANDELA, trad("Jean Guiloineau")],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "famille", "histoire"],
    summary:
      "Pendant vingt-sept ans de détention, de Robben Island à Pollsmoor puis Victor Verster, Nelson Mandela a écrit des centaines de lettres. Plus de deux cents ont été réunies ici, adressées à sa femme Winnie, à ses enfants, à ses camarades ou aux autorités de la prison. Beaucoup ont été censurées ou n'ont jamais été envoyées. On y lit la dignité d'un homme qui défend ses droits et garde le lien avec sa famille malgré les murs.",
    whyRead: [
      "Vingt-sept ans de prison racontés lettre après lettre.",
      "Un père et un mari qui écrit à sa famille, au-delà du héros.",
      "Une leçon de courage et de patience.",
    ],
    year: 2018,
    originalLanguage: "anglais",
    publisher: "Pocket",
    pages: 803,
    isbn: "9782266287883",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Chinua Achebe
  livre({
    slug: "le-malaise",
    title: "Le Malaise",
    contributors: [ACHEBE, trad("Jocelyn Robert Duclos")],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "tradition", "amour", "independances"],
    summary:
      "Obi Okonkwo, petit-fils du héros du « Monde s'effondre », revient au Nigeria après des études en Angleterre payées par les gens de son village. Haut fonctionnaire à Lagos à la veille de l'indépendance, il est bien décidé à ne pas tomber dans la corruption. Mais ses dettes s'accumulent, sa famille attend beaucoup de lui, et il aime Clara, une femme que la tradition lui interdit d'épouser. Le roman s'ouvre sur son procès.",
    whyRead: [
      "La suite du « Monde s'effondre », deux générations plus tard.",
      "Le Lagos de la fin des années 1950, entre ambitions et tentations.",
      "Un roman toujours actuel sur la corruption et les attentes familiales.",
    ],
    year: 1960,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 202,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-fleche-de-dieu",
    title: "La Flèche de Dieu",
    contributors: [ACHEBE, trad("Irène Assiba d'Almeida"), trad("Olga Mahougbé Simpson")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "spiritualite", "tradition", "politique"],
    summary:
      "Dans les années 1920, en pays igbo, Ezeulu est le grand prêtre d'Ulu, le dieu qui protège les six villages d'Umuaro. Fier et réfléchi, il envoie l'un de ses fils à l'école des missionnaires pour connaître le savoir des Blancs. Mais ses rivaux l'accusent de trahison, et l'administrateur britannique veut faire de lui un chef à son service. Pris entre son peuple, son dieu et le pouvoir colonial, Ezeulu affronte une épreuve qui engage tout le village.",
    whyRead: [
      "Le troisième volet de la trilogie africaine d'Achebe.",
      "Un grand personnage tragique, prêtre orgueilleux et lucide.",
      "Un tableau magnifique de la société igbo face à la colonisation.",
    ],
    year: 1964,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 299,
    isbn: "9782708703599",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "le-demagogue",
    title: "Le Démagogue",
    contributors: [ACHEBE, trad("A. Diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "independances"],
    summary:
      "Odili, jeune instituteur idéaliste, retrouve son ancien professeur, le chef Nanga, devenu ministre et adoré du peuple. Invité dans la capitale, il découvre les luxes et les combines du pouvoir. Quand Nanga lui ravit la jeune femme qu'il fréquentait, Odili décide de se présenter contre lui aux élections. Une satire mordante et drôle de la vie politique dans un pays africain tout juste indépendant.",
    whyRead: [
      "Une satire politique féroce et très drôle.",
      "Un roman qui annonçait le premier coup d'État nigérian de 1966.",
      "Un regard toujours juste sur le clientélisme.",
    ],
    year: 1966,
    originalLanguage: "anglais",
    publisher: "Nouvelles éditions africaines",
    pages: 219,
    isbn: "9782723601757",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "femmes-en-guerre-et-autres-nouvelles",
    title: "Femmes en guerre et autres nouvelles",
    contributors: [ACHEBE, trad("Jean de Grandsaigne")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["guerre", "tradition", "femmes"],
    summary:
      "Ce recueil réunit des nouvelles écrites sur une vingtaine d'années. Certaines se passent dans les villages igbo, entre croyances anciennes et missions chrétiennes. D'autres se déroulent pendant la guerre du Biafra, comme celle qui donne son titre au livre, où un fonctionnaire croise une jeune femme que la faim et la guerre ont transformée. Achebe y montre des vies ordinaires bousculées par l'histoire.",
    whyRead: [
      "Achebe dans un format court, idéal pour le découvrir.",
      "La guerre du Biafra vue par des gens ordinaires.",
      "Des récits pleins d'ironie et d'humanité.",
    ],
    year: 1972,
    originalLanguage: "anglais",
    publisher: "Hatier",
    pages: 159,
    isbn: "9782218057359",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-termitieres-de-la-savane",
    title: "Les Termitières de la savane",
    contributors: [ACHEBE, trad("Étienne Galle")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "femmes", "independances"],
    summary:
      "Au Kangan, pays imaginaire d'Afrique de l'Ouest, un jeune militaire a pris le pouvoir. Deux de ses amis d'enfance l'entourent : Chris, ministre de l'Information, et Ikem, rédacteur en chef du grand journal du pays, poète et frondeur. Le « Grand Chef » rêve d'être président à vie, et les vieilles amitiés se fissurent. Beatrice, la compagne de Chris, observe avec lucidité les hommes qui jouent avec le pouvoir.",
    whyRead: [
      "Le dernier roman d'Achebe, vingt ans après les précédents.",
      "Une réflexion forte sur la dictature et l'amitié trahie.",
      "Un personnage féminin qui porte l'espoir du livre.",
    ],
    year: 1987,
    originalLanguage: "anglais",
    publisher: "Les Belles Lettres",
    pages: 285,
    isbn: "9782251455334",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Chimamanda Ngozi Adichie
  livre({
    slug: "l-hibiscus-pourpre",
    title: "L'Hibiscus pourpre",
    contributors: [ADICHIE, trad("Mona de Pracontal")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "enfance", "spiritualite", "politique"],
    summary:
      "Kambili, quinze ans, vit à Enugu, au Nigeria, dans une famille riche. Son père, catholique fervent et notable respecté, fait régner à la maison une discipline de fer. Quand elle part avec son frère Jaja chez leur tante Ifeoma, une universitaire, elle découvre une maison pleine de rires, de débats et de liberté. Pendant ce temps, un coup d'État secoue le pays.",
    whyRead: [
      "Le premier roman d'Adichie, déjà maîtrisé et bouleversant.",
      "Une adolescente qui apprend à parler et à rire.",
      "Un roman sur la violence familiale, sans jamais de lourdeur.",
    ],
    year: 2003,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 403,
    isbn: "9782073111043",
    format: "poche",
    awards: [{ name: "Commonwealth Writers' Prize du premier livre", year: 2005 }],
  }),
  livre({
    slug: "autour-de-ton-cou",
    title: "Autour de ton cou",
    contributors: [ADICHIE, trad("Mona de Pracontal")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["exil", "femmes", "identite", "famille"],
    summary:
      "Douze nouvelles qui vont du Nigeria aux États-Unis. Une jeune femme épouse un médecin nigérian installé en Amérique qui lui demande de changer de nom. Un jeune homme gâté découvre la dureté d'une cellule de police. Une mère attend un visa à l'ambassade américaine de Lagos. Adichie raconte avec finesse l'exil, le mariage, la violence politique et la solitude.",
    whyRead: [
      "Des nouvelles brèves qui touchent juste à chaque fois.",
      "Le Nigeria et l'Amérique vus par des femmes et des hommes ordinaires.",
      "Une bonne façon de découvrir Adichie.",
    ],
    year: 2009,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 312,
    isbn: "9782070462315",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "americanah",
    title: "Americanah",
    contributors: [ADICHIE, trad("Anne Damour")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "amour", "identite"],
    summary:
      "Ifemelu et Obinze s'aiment depuis le lycée, à Lagos. Les universités nigérianes étant sans cesse en grève, Ifemelu part étudier aux États-Unis, où elle découvre qu'elle est « noire », une étiquette qu'elle n'avait jamais portée. Elle tient un blog plein d'ironie sur la question raciale en Amérique. Obinze, lui, échoue à la rejoindre et tente sa chance à Londres. Quinze ans plus tard, Ifemelu décide de rentrer au pays.",
    whyRead: [
      "Un grand roman d'amour et d'exil, drôle et intelligent.",
      "Un regard vif sur la question raciale aux États-Unis.",
      "L'un des romans africains les plus lus de sa décennie.",
    ],
    year: 2013,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 684,
    isbn: "9782070468805",
    format: "poche",
    awards: [{ name: "National Book Critics Circle Award", year: 2014 }],
  }),
  livre({
    slug: "nous-sommes-tous-des-feministes",
    title: "Nous sommes tous des féministes",
    subtitle: "suivi de Le Danger de l'histoire unique",
    contributors: [ADICHIE, trad("Sylvie Schneiter"), trad("Mona de Pracontal")],
    genre: "essai",
    audience: "adulte",
    themes: ["femmes", "identite"],
    summary:
      "Tiré d'une conférence donnée en 2012, ce texte bref explique simplement pourquoi le féminisme concerne tout le monde, hommes compris. Adichie part de souvenirs personnels, de l'école à Lagos aux restaurants où l'on ne salue que l'homme. Cette édition y ajoute « Le Danger de l'histoire unique », où elle montre ce que l'on perd à ne connaître qu'une seule version de l'histoire d'un peuple. Deux textes courts devenus des classiques.",
    whyRead: [
      "Deux conférences célèbres, à lire en une heure.",
      "Un féminisme clair, chaleureux et plein d'humour.",
      "Idéal à offrir ou à faire lire aux adolescents.",
    ],
    year: 2014,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 73,
    isbn: "9782072886508",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chere-ijeawele",
    title: "Chère Ijeawele",
    subtitle: "ou un manifeste pour une éducation féministe",
    contributors: [ADICHIE, trad("Marguerite Capelle")],
    genre: "essai",
    audience: "adulte",
    themes: ["femmes", "famille", "enfance"],
    summary:
      "Une amie d'enfance, devenue mère d'une petite fille, demande à Adichie comment l'élever en féministe. Elle lui répond par une lettre en quinze suggestions. Partager les tâches avec le père, refuser les rôles tout faits, apprendre à l'enfant à aimer lire, à parler de son corps sans honte, à ne pas chercher à plaire à tout prix. Des conseils concrets, écrits avec tendresse et franchise.",
    whyRead: [
      "Quinze conseils simples pour élever les enfants autrement.",
      "Une lettre d'amitié, chaleureuse et directe.",
      "Un petit livre utile aux parents, d'où qu'ils viennent.",
    ],
    year: 2017,
    originalLanguage: "anglais",
    publisher: "Gallimard",
    pages: 77,
    isbn: "9782072721977",
    format: null,
    awards: [],
  }),
  livre({
    slug: "notes-sur-le-chagrin",
    title: "Notes sur le chagrin",
    contributors: [ADICHIE, trad("Mona de Pracontal")],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "identite"],
    summary:
      "En juin 2020, en pleine pandémie, Adichie apprend la mort soudaine de son père, au Nigeria, alors qu'elle est bloquée aux États-Unis. Dans ce court récit, elle raconte le choc, la colère, l'incrédulité, et les souvenirs d'un homme doux et drôle, professeur de statistiques. Elle dit aussi la douleur de ne pas pouvoir rentrer pour l'enterrer. Un hommage pudique et universel.",
    whyRead: [
      "Un texte bref et sincère sur le deuil d'un père.",
      "Un portrait tendre d'un père nigérian.",
      "Des mots justes pour ceux qui ont perdu un proche.",
    ],
    year: 2021,
    originalLanguage: "anglais",
    publisher: "Gallimard",
    pages: 98,
    isbn: "9782072943928",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-inventaire-des-reves",
    title: "L'Inventaire des rêves",
    contributors: [ADICHIE, trad("Blandine Longre")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "exil"],
    summary:
      "Pendant la pandémie de 2020, Chiamaka, écrivaine de voyage nigériane installée aux États-Unis, se retrouve seule et repense aux hommes qu'elle a aimés. Autour d'elle, trois autres femmes : son amie Zikora, avocate, sa cousine Omelogor, banquière à Abuja, et sa femme de ménage guinéenne, Kadiatou. Chacune a sa part de rêves, de désirs et de blessures. Un grand roman choral sur les femmes et la recherche de l'amour.",
    whyRead: [
      "Le grand retour d'Adichie au roman, douze ans après « Americanah ».",
      "Quatre portraits de femmes entre Afrique et Amérique.",
      "Un roman ample sur l'amour, l'amitié et la dignité.",
    ],
    year: 2025,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 649,
    isbn: "9782073137562",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Yaa Gyasi
  livre({
    slug: "sublime-royaume",
    title: "Sublime royaume",
    contributors: [GYASI, trad("Anne Damour")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "spiritualite"],
    summary:
      "Gifty, fille d'immigrés ghanéens élevée en Alabama, prépare un doctorat de neurosciences à Stanford. Elle étudie sur des souris les mécanismes de l'addiction. Son frère Nana, sportif prometteur, est mort d'une overdose, et sa mère, plongée dans la dépression, vient s'installer chez elle. Entre science et foi d'enfance, Gifty cherche à comprendre ce qui est arrivé aux siens.",
    whyRead: [
      "Le deuxième roman de l'autrice de « No Home ».",
      "Une famille ghanéenne en Amérique, entre exil et deuil.",
      "Une belle réflexion sur la science et la foi.",
    ],
    year: 2020,
    originalLanguage: "anglais",
    publisher: "Le Livre de poche",
    pages: 353,
    isbn: "9782253079880",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Wole Soyinka
  livre({
    slug: "les-gens-des-marais",
    title: "Les Gens des marais",
    subtitle: "suivi de Un sang fort et Les Tribulations de frère Jéro",
    contributors: [SOYINKA, trad("Élisabeth Janvier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["tradition", "spiritualite", "humour", "ville"],
    summary:
      "Ce volume réunit trois des premières pièces de Soyinka. Dans « Les Gens des marais », Igwezu revient de la ville dans son village du delta, ruiné par l'inondation, et se dresse contre le prêtre qui exploite les paysans. « Un sang fort » suit Eman, un étranger installé dans un village où l'on choisit chaque année un homme pour emporter les malheurs de tous. « Les Tribulations de frère Jéro », comédie, met en scène un faux prophète des plages de Lagos.",
    whyRead: [
      "Trois pièces courtes pour découvrir le théâtre de Soyinka.",
      "Du drame villageois à la satire la plus drôle.",
      "Le célèbre frère Jéro, escroc en robe de prophète.",
    ],
    year: 1958,
    originalLanguage: "anglais",
    publisher: "L'Harmattan",
    pages: 150,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-lion-et-la-perle",
    title: "Le Lion et la Perle",
    contributors: [SOYINKA, trad("Jacques Chuto"), trad("Philippe Laburthe-Tolra")],
    genre: "theatre",
    audience: "adulte",
    themes: ["tradition", "amour", "humour", "femmes"],
    summary:
      "Dans le village yoruba d'Ilujinle, Sidi est la plus belle fille du pays, et elle le sait. Lakunle, l'instituteur, veut l'épouser à l'européenne, sans payer de dot, au nom du progrès. Mais Baroka, le vieux chef rusé, entend bien ajouter Sidi à ses épouses. Une comédie pleine de chants et de danses sur le choc entre tradition et modernité.",
    whyRead: [
      "L'une des comédies les plus jouées du théâtre africain.",
      "Un trio savoureux : la belle, l'instituteur et le vieux chef.",
      "Une satire fine des prétentions de la modernité.",
    ],
    year: 1959,
    originalLanguage: "anglais",
    publisher: "CLÉ",
    pages: 93,
    isbn: "9782723500364",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "la-danse-de-la-foret",
    title: "La Danse de la forêt",
    contributors: [SOYINKA, trad("Élisabeth Janvier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["independances", "histoire", "spiritualite", "contes"],
    summary:
      "Pour une grande fête qui réunit les tribus, les vivants demandent aux dieux de leur envoyer d'illustres ancêtres. Mais les morts qui surgissent de la forêt sont un guerrier et sa femme, victimes d'une injustice passée, et non des héros glorieux. Esprits, dieux et humains se croisent dans une forêt où le passé et le présent se répondent. Une pièce écrite pour l'indépendance du Nigeria, en 1960.",
    whyRead: [
      "La pièce écrite par Soyinka pour l'indépendance du Nigeria.",
      "Un refus de célébrer un passé idéalisé.",
      "Un grand spectacle de masques, de danses et d'esprits.",
    ],
    year: 1960,
    originalLanguage: "anglais",
    publisher: "L'Harmattan",
    pages: 129,
    isbn: "9782858028689",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-recolte-de-kongi",
    title: "La Récolte de Kongi",
    contributors: [SOYINKA, trad("Éliane Saint-André Utudjian"), trad("Claire Pergnier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "tradition", "humour"],
    summary:
      "Dans la république d'Isma, le président Kongi a pris le pouvoir et emprisonné le vieux roi Danlola. Pour asseoir son autorité, il veut que le roi lui remette en personne l'igname nouvelle lors de la grande fête des récoltes. Le neveu du roi, Daodu, et sa compagne Segi préparent de leur côté un autre plan. Une satire des dictateurs, entre chants royaux et slogans de propagande.",
    whyRead: [
      "Une satire mordante des dictatures africaines.",
      "Adaptée au cinéma par Ossie Davis, avec Soyinka lui-même.",
      "Un affrontement savoureux entre un vieux roi et un jeune tyran.",
    ],
    year: 1965,
    originalLanguage: "anglais",
    publisher: "Silex",
    pages: 86,
    isbn: "9782876930131",
    format: null,
    awards: [],
    adaptations: [{ kind: "film", title: "Kongi's Harvest", year: 1970, by: "Ossie Davis" }],
  }),
  livre({
    slug: "la-route",
    title: "La Route",
    contributors: [SOYINKA, trad("Christiane Fioupou"), trad("Samuel Millogo")],
    genre: "theatre",
    audience: "adulte",
    themes: ["spiritualite", "ville", "tradition"],
    summary:
      "Au bord d'une route du Nigeria, dans une baraque transformée en « boutique des accidents », chauffeurs sans travail et voyous attendent. Leur maître est le Professeur, un ancien prédicateur qui fouille les épaves à la recherche du « Mot », le secret de la mort. Il veille sur Murano, un homme muet qu'il croit revenu de l'au-delà. Une pièce étrange et puissante, où la route devient un dieu dévoreur.",
    whyRead: [
      "L'une des pièces les plus ambitieuses de Soyinka.",
      "Le monde des chauffeurs routiers nigérians, entre rire et mystère.",
      "Une méditation sur la mort, nourrie de culture yoruba.",
    ],
    year: 1965,
    originalLanguage: "anglais",
    publisher: "Hatier",
    pages: 160,
    isbn: "9782218017841",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-interpretes",
    title: "Les Interprètes",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "independances", "identite"],
    summary:
      "À Lagos et Ibadan, au début des années 1960, cinq jeunes amis revenus d'études à l'étranger se retrouvent dans les bars. Egbo hésite entre un poste aux Affaires étrangères et la chefferie de sa famille, Sagoe est un journaliste désabusé, Sekoni un ingénieur rêveur, Kola un peintre, Bandele un universitaire. Ensemble, ils observent avec ironie la nouvelle élite nigériane. Le premier roman de Soyinka.",
    whyRead: [
      "Le premier roman de Soyinka, foisonnant et satirique.",
      "Une génération d'intellectuels face au Nigeria indépendant.",
      "Une nouvelle traduction d'Étienne Galle.",
    ],
    year: 1965,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 414,
    isbn: "9782708710290",
    format: null,
    awards: [],
  }),
  livre({
    slug: "cycles-sombres",
    title: "Cycles sombres",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "guerre", "politique"],
    summary:
      "Ce recueil réunit en français des poèmes de plusieurs livres de Soyinka. On y trouve « Idanre », long poème consacré à Ogun, dieu yoruba du fer, des routes et de la création, mais aussi des poèmes écrits en prison pendant la guerre du Biafra. La voix est tour à tour mythique, intime et politique. Une poésie exigeante, nourrie des dieux yoruba et de l'histoire du Nigeria.",
    whyRead: [
      "La poésie de Soyinka réunie en un volume.",
      "Des poèmes de prison d'une grande force.",
      "Une porte d'entrée vers la mythologie yoruba.",
    ],
    year: 1967,
    originalLanguage: "anglais",
    publisher: "Silex",
    pages: 194,
    isbn: "9782876930025",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "fous-et-specialistes",
    title: "Fous et Spécialistes",
    contributors: [SOYINKA, trad("Éliane Saint-André Utudjian"), trad("Claire Pergnier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["guerre", "politique", "famille"],
    summary:
      "Le docteur Bero revient de la guerre. Médecin devenu chef des services de renseignement, il a pris goût au pouvoir et à la torture. Il garde son propre père enfermé dans sa cave, tandis que quatre mendiants mutilés, anciens soldats, rôdent autour de la maison. Sa sœur Si Bero, restée au pays avec de vieilles herboristes, ne le reconnaît plus. Une pièce noire écrite au sortir de la guerre du Biafra.",
    whyRead: [
      "Une pièce sombre sur ce que la guerre fait aux hommes.",
      "Un humour grinçant au service d'une critique du pouvoir.",
      "Écrite après la détention de Soyinka pendant la guerre.",
    ],
    year: 1970,
    originalLanguage: "anglais",
    publisher: "Nouvelles du Sud",
    pages: 83,
    isbn: "9782879310220",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "cet-homme-est-mort",
    title: "Cet homme est mort",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "guerre", "histoire"],
    summary:
      "En 1967, au début de la guerre du Biafra, Wole Soyinka est arrêté pour avoir tenté une médiation de paix. Il passera plus de deux ans en prison sans jugement, en grande partie à l'isolement. Dans ces notes de prison, il raconte les interrogatoires, la faim, l'enfermement et les ruses pour garder l'esprit libre. Un témoignage puissant contre l'arbitraire et la violence d'État.",
    whyRead: [
      "Le récit de deux ans de détention à l'isolement.",
      "Un grand texte sur la résistance de l'esprit.",
      "Pour comprendre l'engagement de Soyinka pendant la guerre du Biafra.",
    ],
    year: 1972,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 367,
    isbn: "9782757899922",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "une-saison-d-anomie",
    title: "Une saison d'anomie",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "guerre", "amour", "tradition"],
    summary:
      "Ofeyi travaille pour le cartel du cacao, qui domine le pays. Il découvre Aiyéró, une communauté qui partage ses biens et vit selon ses propres règles, et rêve d'étendre ce modèle à tout le pays. Mais le cartel et les militaires ne tolèrent aucune contestation, et des massacres éclatent. Quand sa compagne Iriyise disparaît, Ofeyi part à sa recherche à travers un pays livré à la violence.",
    whyRead: [
      "Un roman écrit sous le choc des massacres de la fin des années 1960.",
      "Une quête amoureuse au cœur d'un pays en guerre.",
      "Un grand roman politique, sombre et lyrique.",
    ],
    year: 1973,
    originalLanguage: "anglais",
    publisher: "Le Livre de poche",
    pages: 381,
    isbn: "9782253062646",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-bacchantes-d-euripide",
    title: "Les Bacchantes d'Euripide",
    subtitle: "Rite de communion",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "theatre",
    audience: "adulte",
    themes: ["spiritualite", "politique", "contes"],
    summary:
      "Soyinka adapte la tragédie grecque d'Euripide. Le dieu Dionysos revient à Thèbes, où le roi Penthée refuse son culte. Soyinka ajoute un chœur d'esclaves et fait résonner le mythe avec les révoltes des opprimés et les rites africains. Une relecture puissante d'un classique, entre fête, sacrifice et révolte.",
    whyRead: [
      "Une tragédie grecque réinventée par un grand dramaturge africain.",
      "Un pont entre Dionysos et les dieux yoruba.",
      "Une pièce commandée et créée par le National Theatre de Londres.",
    ],
    year: 1973,
    originalLanguage: "anglais",
    publisher: "Silex",
    pages: 91,
    isbn: "9782876930094",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "du-rouge-de-cam-sur-les-feuilles",
    title: "Du rouge de cam sur les feuilles",
    contributors: [SOYINKA, trad("Éliane Saint-André Utudjian"), trad("Claire Pergnier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["famille", "spiritualite", "enfance"],
    summary:
      "Isola, fils d'un pasteur sévère, se révolte contre l'autorité de son père. Il a mis enceinte une jeune fille du village, Moniloja, et refuse de se soumettre. Entre la mère qui tente de protéger son fils et le père qui veut le briser, le conflit grandit. Une courte pièce, d'abord écrite pour la radio, sur la jeunesse et la tyrannie familiale.",
    whyRead: [
      "Une pièce brève et intense sur un conflit entre père et fils.",
      "Soyinka à ses débuts, pour la radio nigériane.",
      "Une critique de l'autorité religieuse et familiale.",
    ],
    year: 1973,
    originalLanguage: "anglais",
    publisher: "Nouvelles du Sud",
    pages: 61,
    isbn: "9782879310190",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-metamorphose-de-frere-jero",
    title: "La Métamorphose de frère Jéro",
    contributors: [SOYINKA, trad("Élisabeth Janvier")],
    genre: "theatre",
    audience: "adulte",
    themes: ["humour", "spiritualite", "politique"],
    summary:
      "Frère Jéro, le faux prophète des plages de Lagos, a appris que le gouvernement veut chasser les prédicateurs de la plage pour y construire un amphithéâtre destiné aux exécutions publiques. Plutôt que de céder, il réunit ses rivaux et rêve d'une Église officielle, au service de l'armée. Une comédie féroce sur l'alliance des charlatans et du pouvoir militaire.",
    whyRead: [
      "Le retour de frère Jéro, escroc irrésistible.",
      "Une satire grinçante du pouvoir militaire.",
      "Une comédie courte, facile à lire et à jouer.",
    ],
    year: 1973,
    originalLanguage: "anglais",
    publisher: "Présence africaine",
    pages: 75,
    isbn: "9782708704671",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-mort-et-l-ecuyer-du-roi",
    title: "La Mort et l'Écuyer du roi",
    contributors: [SOYINKA, trad("Thierry Dubost")],
    genre: "theatre",
    audience: "adulte",
    themes: ["tradition", "colonisation", "spiritualite"],
    summary:
      "À Oyo, en 1946, le roi est mort. Selon la tradition yoruba, son écuyer Elesin doit le suivre dans l'au-delà le soir des funérailles, pour guider son esprit. Elesin s'y prépare en dansant au marché, mais demande une dernière faveur : épouser une jeune fille. L'administrateur colonial, Pilkings, décide d'empêcher ce rite qu'il juge barbare. Une tragédie inspirée de faits réels.",
    whyRead: [
      "Le chef-d'œuvre théâtral de Soyinka, souvent comparé aux tragédies grecques.",
      "Un affrontement entre deux visions du monde, jamais caricatural.",
      "Une langue magnifique, pleine de chants et de proverbes.",
    ],
    year: 1975,
    originalLanguage: "anglais",
    publisher: "Hatier",
    pages: 111,
    isbn: "9782747302081",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "la-terre-de-mandela",
    title: "La Terre de Mandela",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "poesie",
    audience: "adulte",
    themes: ["politique", "colonisation", "histoire"],
    summary:
      "Ce recueil de poèmes a été écrit alors que Nelson Mandela était encore en prison. Soyinka s'adresse à lui, raille les défenseurs de l'apartheid et dénonce l'hypocrisie du monde. D'autres poèmes évoquent le Nigeria et les dictatures. Une poésie de combat, ironique et généreuse.",
    whyRead: [
      "Un hommage poétique à Mandela, écrit avant sa libération.",
      "Une poésie engagée contre l'apartheid.",
      "Paru deux ans après le prix Nobel de Soyinka.",
    ],
    year: 1988,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 94,
    isbn: "9782757898475",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ibadan-les-annees-pagaille",
    title: "Ibadan, les années pagaille",
    subtitle: "Mémoires, 1946-1965",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "independances", "histoire"],
    summary:
      "Après « Aké », Soyinka poursuit ses mémoires, de l'adolescence à l'âge adulte. Il raconte ses études à Ibadan puis en Angleterre, son retour au Nigeria, ses débuts au théâtre et ses premiers combats politiques. Dans les années qui suivent l'indépendance, il voit le pays basculer dans les fraudes électorales et la violence. Il se donne ici le nom de Maren et raconte avec verve une époque de « pagaille ».",
    whyRead: [
      "La suite des souvenirs d'enfance d'« Aké ».",
      "Le Nigeria des années 1950 et 1960 vu de l'intérieur.",
      "Un récit vif, plein d'humour et de colère.",
    ],
    year: 1994,
    originalLanguage: "anglais",
    publisher: "Actes Sud",
    pages: 499,
    isbn: "9782742710096",
    format: null,
    awards: [],
  }),
  livre({
    slug: "isara",
    title: "Isara",
    subtitle: "Périple autour de mon père",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "histoire", "tradition"],
    summary:
      "Après la mort de son père, Soyinka retrouve une boîte de lettres et de papiers. Il imagine à partir d'eux la jeunesse de cet homme, instituteur surnommé « Essay », et de ses amis originaires d'Isara, une petite ville yoruba. Entre les années 1930 et 1940, ces jeunes gens instruits débattent de l'avenir du pays, du commerce, de la politique et des traditions. Un récit tendre et drôle, entre biographie et roman.",
    whyRead: [
      "Le portrait d'un père, après celui de l'enfance dans « Aké ».",
      "Une petite ville yoruba à la fin de l'époque coloniale.",
      "Un livre plein de tendresse et d'humour.",
    ],
    year: 1989,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 404,
    isbn: "9782757899908",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "baabou-roi",
    title: "Baabou roi",
    contributors: [SOYINKA, trad("Christiane Fioupou")],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "humour"],
    summary:
      "Inspiré d'« Ubu roi » d'Alfred Jarry, ce texte suit le général Basha Bash qui, poussé par son épouse, renverse le pouvoir au pays de Guatu. Devenu Baabou, il se proclame roi et pille le pays sans retenue. Soyinka transpose la farce de Jarry dans l'Afrique des dictatures militaires. Une satire énorme, grotesque et irrésistible.",
    whyRead: [
      "« Ubu roi » à la sauce des dictatures africaines.",
      "Une farce féroce, écrite après les années Abacha.",
      "Un théâtre qui fait rire jaune.",
    ],
    year: 2001,
    originalLanguage: "anglais",
    publisher: "Actes Sud-Papiers",
    pages: 108,
    isbn: "9782742754526",
    format: null,
    awards: [],
  }),
  livre({
    slug: "il-te-faut-partir-a-l-aube",
    title: "Il te faut partir à l'aube",
    subtitle: "Mémoires",
    contributors: [SOYINKA, trad("Étienne Galle")],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "exil", "histoire"],
    summary:
      "Dans ce troisième volume de mémoires, Soyinka raconte sa vie d'adulte, des années 1960 aux années 2000. Il revient sur ses combats contre les régimes militaires, son prix Nobel, sa fuite du Nigeria à moto sous la dictature d'Abacha, et ses années d'exil. On y trouve aussi ses amitiés, ses colères et son amour du pays. Un récit foisonnant, à la mesure d'une vie d'écrivain engagé.",
    whyRead: [
      "La vie mouvementée d'un prix Nobel qui n'a jamais cessé de lutter.",
      "Le récit de sa fuite et de son exil sous Abacha.",
      "Un panorama de l'histoire du Nigeria indépendant.",
    ],
    year: 2006,
    originalLanguage: "anglais",
    publisher: "Actes Sud",
    pages: 649,
    isbn: "9782742770335",
    format: null,
    awards: [],
  }),
  livre({
    slug: "chroniques-du-pays-des-gens-les-plus-heureux-du-monde",
    title: "Chroniques du pays des gens les plus heureux du monde",
    contributors: [SOYINKA, trad("David Fauquemberg"), trad("Fabienne Kanor")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "spiritualite"],
    summary:
      "Le docteur Menka, chirurgien dans un hôpital du Nigeria, découvre un trafic de membres humains destinés à des rituels. Il en parle à son ami d'enfance Duyole, ingénieur sur le point de partir travailler à l'ONU. Autour d'eux s'agitent politiciens corrompus, prophètes milliardaires et intrigants de toutes sortes. Près de cinquante ans après son dernier roman, Soyinka signe une satire à la fois drôle et noire.",
    whyRead: [
      "Le premier roman de Soyinka depuis près d'un demi-siècle.",
      "Une satire féroce de la corruption et des faux prophètes.",
      "Une intrigue à suspense dans le Nigeria d'aujourd'hui.",
    ],
    year: 2021,
    originalLanguage: "anglais",
    publisher: "Seuil",
    pages: 529,
    isbn: "9782021497885",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Abdulrazak Gurnah
  livre({
    slug: "memoire-du-depart",
    title: "Mémoire du départ",
    contributors: [GURNAH, trad("Cécile Leclère")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "exil", "enfance"],
    summary:
      "Hassan Omar grandit dans une petite ville côtière d'Afrique de l'Est, au lendemain de l'indépendance, dans une famille pauvre dominée par un père violent. Brillant élève, il rêve de partir. Une occasion se présente : il est invité à Nairobi chez un oncle maternel fortuné. Là, il découvre une autre vie et tombe amoureux de sa cousine, tout en restant prisonnier des secrets de sa famille.",
    whyRead: [
      "Le premier roman de Gurnah, prix Nobel 2021.",
      "Une jeunesse étouffée qui rêve d'ailleurs.",
      "Les thèmes de toute son œuvre : la famille, le départ, la mémoire.",
    ],
    year: 1987,
    originalLanguage: "anglais",
    publisher: "Denoël",
    pages: 226,
    isbn: "9782207181133",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-voie-des-pelerins",
    title: "La Voie des pèlerins",
    contributors: [GURNAH, trad("Cécile Leclère")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "amour", "identite", "travail"],
    summary:
      "Daud, venu de Tanzanie, vit à Canterbury, en Angleterre, à la fin des années 1970. Aide-soignant dans un hôpital, il affronte chaque jour le mépris et le racisme, dans les pubs comme dans la rue. Il trouve refuge dans le cricket et dans ses souvenirs du pays natal. Sa rencontre avec Catherine, une infirmière, va peut-être lui permettre de reprendre pied.",
    whyRead: [
      "Un roman fort sur la solitude de l'immigré en Angleterre.",
      "Une histoire d'amour qui naît malgré les préjugés.",
      "Un regard précoce et juste sur le racisme ordinaire.",
    ],
    year: 1988,
    originalLanguage: "anglais",
    publisher: "Denoël",
    pages: 334,
    isbn: "9782207183809",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "adieu-zanzibar",
    title: "Adieu Zanzibar",
    contributors: [GURNAH, trad("Sylvette Gleize")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "colonisation", "exil", "famille"],
    summary:
      "En 1899, sur la côte de l'Afrique de l'Est, un Anglais épuisé est recueilli par Hassanali, un commerçant, et sa sœur Rehana. Une histoire d'amour interdite naît entre l'Anglais et Rehana. Un demi-siècle plus tard, à Zanzibar, à la veille de l'indépendance, le jeune Amin, frère du narrateur, vit à son tour un amour que sa famille refuse. Le narrateur, exilé en Angleterre, relie ces destins séparés par le temps.",
    whyRead: [
      "Deux histoires d'amour à cinquante ans d'écart.",
      "Zanzibar, de l'époque coloniale à l'indépendance.",
      "Un roman ample et délicat, parmi les plus beaux de Gurnah.",
    ],
    year: 2005,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 424,
    isbn: "9782073086372",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-vies-d-apres",
    title: "Les Vies d'après",
    contributors: [GURNAH, trad("Sylvette Gleize")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "guerre", "famille", "amour"],
    summary:
      "Au début du XXe siècle, en Afrique orientale allemande, le jeune Ilyas est enlevé par des soldats coloniaux puis éduqué par un fermier allemand. Revenu dans sa ville, il retrouve sa petite sœur Afiya avant de repartir à la guerre. Hamza, lui, s'engage dans les troupes africaines de l'armée allemande et traverse la Première Guerre mondiale. Gurnah suit ces vies ordinaires broyées par la colonisation et la guerre.",
    whyRead: [
      "Le premier roman de Gurnah publié après son prix Nobel.",
      "Une page méconnue : la Grande Guerre en Afrique de l'Est.",
      "Des personnages attachants qui tentent de se reconstruire.",
    ],
    year: 2020,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 431,
    isbn: "9782073151636",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Mia Couto
  livre({
    slug: "les-baleines-de-quissico",
    title: "Les Baleines de Quissico",
    contributors: [COUTO, trad("Maryvonne Lapouge-Pettorelli")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["guerre", "contes", "tradition"],
    summary:
      "Ces nouvelles ont été écrites pendant la guerre civile qui a ravagé le Mozambique après l'indépendance. On y croise des villageois, des vieillards, des enfants et des rêveurs, comme cet homme qui attend sur la plage une baleine censée apporter à manger aux affamés. Mia Couto mêle réalisme et merveilleux, et invente des mots pour dire la misère et l'espoir. Une première découverte de son monde.",
    whyRead: [
      "Les premières nouvelles de Mia Couto traduites en français.",
      "Le Mozambique en guerre, raconté avec poésie.",
      "Une langue inventive, pleine de mots nouveaux.",
    ],
    year: 1986,
    originalLanguage: "portugais",
    publisher: "10-18",
    pages: 242,
    isbn: "9782264033970",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "histoires-reverees",
    title: "Histoires rêvérées",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["guerre", "contes", "tradition"],
    summary:
      "Ces nouvelles ont été écrites juste après la fin de la guerre civile au Mozambique, en 1992. Ses personnages sortent des années de violence et réapprennent à vivre. Mia Couto y glisse des rêves, des esprits et des mots inventés qui disent mieux que les mots ordinaires ce que vivent ses personnages. Un livre sur la paix retrouvée et la force de l'imagination.",
    whyRead: [
      "Des nouvelles lumineuses sur le retour de la paix.",
      "Le merveilleux au cœur de la vie quotidienne.",
      "Une langue inventive, magnifiquement traduite.",
    ],
    year: 1994,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 167,
    isbn: "9782367321233",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-veranda-au-frangipanier",
    title: "La Véranda au frangipanier",
    contributors: [COUTO, trad("Maryvonne Lapouge-Pettorelli")],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "tradition", "contes"],
    summary:
      "Dans une ancienne forteresse coloniale transformée en maison de retraite, au bord de la mer, le directeur a été assassiné. Un inspecteur de police vient enquêter et interroge les vieillards, qui s'accusent tous du crime. Le narrateur est un mort, enterré sous le frangipanier, dont l'esprit s'est glissé dans le corps de l'inspecteur. À travers les récits des pensionnaires, c'est toute la mémoire du Mozambique qui ressurgit.",
    whyRead: [
      "Une enquête policière racontée par un fantôme.",
      "Des vieillards conteurs, gardiens de la mémoire.",
      "Un roman drôle, étrange et poétique.",
    ],
    year: 1996,
    originalLanguage: "portugais",
    publisher: "10-18",
    pages: 201,
    isbn: "9782264033574",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "tombe-tombe-au-fond-de-l-eau",
    title: "Tombe, tombe au fond de l'eau",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "tradition", "contes"],
    summary:
      "Dans un village de pêcheurs au bord de l'océan Indien, Zeca Perpétuo, vieux pêcheur à la retraite, fait la cour à sa voisine Luarmina. Elle le repousse mais l'écoute raconter ses histoires de mer et de souvenirs. Peu à peu, chacun livre ses secrets et son passé. Un petit roman tendre et drôle sur l'amour à l'âge où l'on croyait tout fini.",
    whyRead: [
      "Une histoire d'amour entre deux vieux voisins, pleine de charme.",
      "Un court roman de la mer et des souvenirs.",
      "Idéal pour découvrir la fantaisie de Mia Couto.",
    ],
    year: 1998,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 79,
    isbn: "9782367322865",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chronique-des-jours-de-cendre",
    title: "Chronique des jours de cendre",
    contributors: [COUTO, trad("Maryvonne Lapouge-Pettorelli")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "independances", "histoire"],
    summary:
      "Avril 1974 : au Portugal, la révolution des Œillets renverse la dictature. Dans une petite ville du Mozambique, Lourenço de Castro, agent de la police politique portugaise, continue de traquer les rebelles et de torturer des prisonniers. Autour de lui, sa mère, une jeune métisse et les habitants africains sentent que le monde colonial vacille. Un roman court sur la fin d'un empire.",
    whyRead: [
      "La fin de l'empire colonial portugais vue du Mozambique.",
      "Un roman bref, sombre et poétique.",
      "Une autre façon de raconter la révolution des Œillets.",
    ],
    year: 1999,
    originalLanguage: "portugais",
    publisher: "Albin Michel",
    pages: 148,
    isbn: "9782226138002",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-dernier-vol-du-flamant",
    title: "Le Dernier Vol du flamant",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "politique", "contes"],
    summary:
      "Après la guerre, des casques bleus de l'ONU sont chargés de surveiller la paix à Tizangara, une petite ville du Mozambique. Plusieurs d'entre eux explosent mystérieusement, sans qu'on retrouve rien d'autre que leur sexe. Un inspecteur italien est envoyé sur place, avec un traducteur du pays. Il va découvrir un monde où les vivants, les morts et les esprits se côtoient. Une enquête burlesque et une satire de l'après-guerre.",
    whyRead: [
      "Un point de départ aussi drôle qu'absurde.",
      "Une satire de l'aide internationale et des nouveaux puissants.",
      "Adapté au cinéma au Mozambique.",
    ],
    year: 2000,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 205,
    isbn: "9782367321189",
    format: "poche",
    awards: [],
    adaptations: [{ kind: "film", title: "O Último Voo do Flamingo", year: 2010, by: "João Ribeiro" }],
  }),
  livre({
    slug: "le-chat-et-le-noir",
    title: "Le Chat et le Noir",
    contributors: [COUTO, trad("Diogo Quintela"), trad("Bernard Tissier")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "famille", "contes"],
    summary:
      "Pintalgato est un petit chat jaune et curieux. Sa mère lui a interdit de dépasser la limite où commence l'obscurité. Mais un jour, il ne résiste pas et franchit la frontière. Dans le noir, il fait une rencontre qui va changer sa façon de voir les choses. Un conte illustré par Stanislas Bouvier sur la peur du noir et la peur de l'autre.",
    whyRead: [
      "Un conte pour enfants sur la peur du noir.",
      "Une jolie leçon sur le regard porté sur les autres.",
      "Une belle porte d'entrée dans l'univers de Mia Couto.",
    ],
    year: 2001,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 38,
    isbn: "9782367322483",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "un-fleuve-appele-temps-une-maison-appelee-terre",
    title: "Un fleuve appelé Temps, une maison appelée Terre",
    contributors: [COUTO, trad("Maryvonne Lapouge-Pettorelli")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "tradition", "contes"],
    summary:
      "Le jeune Mariano, étudiant en ville, revient sur l'île de son enfance pour l'enterrement de son grand-père, Dito Mariano. Mais le vieil homme n'est pas tout à fait mort : il refuse d'être enterré tant que certains secrets n'ont pas été révélés. Mariano reçoit de mystérieuses lettres qui lui apprennent l'histoire de sa famille. Un roman sur la mémoire, les ancêtres et la terre natale.",
    whyRead: [
      "Un grand-père qui refuse de mourir avant d'avoir tout dit.",
      "Les secrets d'une famille sur une île du Mozambique.",
      "Un roman plein de magie et de tendresse.",
    ],
    year: 2002,
    originalLanguage: "portugais",
    publisher: "Albin Michel",
    pages: 272,
    isbn: "9782226188588",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-fil-des-missangas",
    title: "Le Fil des missangas",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["femmes", "amour", "famille"],
    summary:
      "Les missangas sont de petites perles colorées enfilées en colliers. Mia Couto compose ici un collier de nouvelles très courtes, souvent consacrées à des femmes oubliées : épouses délaissées, veuves, filles qui attendent, mères qui rêvent. Chaque histoire tient en quelques pages et fait entendre une voix qu'on n'écoute jamais. Un livre délicat, plein d'humour et de mélancolie.",
    whyRead: [
      "Des nouvelles brèves, comme des perles enfilées.",
      "Des portraits de femmes invisibles, enfin écoutées.",
      "La poésie de Mia Couto à petites doses.",
    ],
    year: 2003,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 174,
    isbn: "9782915540765",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-pluie-ebahie",
    title: "La Pluie ébahie",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "tradition"],
    summary:
      "Dans un village au bord d'un fleuve, la pluie s'est arrêtée en l'air : elle ne tombe plus, elle flotte. Le fleuve s'assèche et chacun cherche une explication. Le père accuse l'usine voisine, la grand-mère invoque les ancêtres. Un enfant raconte cette étrange saison et les secrets que la pluie suspendue fait remonter dans sa famille. Un court roman, entre conte et fable écologique.",
    whyRead: [
      "Une fable poétique sur la nature et la pollution.",
      "Un regard d'enfant plein de fraîcheur.",
      "Un roman très court, à lire d'une traite.",
    ],
    year: 2004,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 97,
    isbn: "9782367322872",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "poisons-de-dieu-remedes-du-diable",
    title: "Poisons de Dieu, remèdes du diable",
    subtitle: "Les vies incurables de Vila Cacimba",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "exil", "famille"],
    summary:
      "Sidónio Rosa, jeune médecin portugais, débarque à Vila Cacimba, une petite ville du Mozambique, sous prétexte de lutter contre une épidémie. En réalité, il cherche Deolinda, une Mozambicaine dont il est tombé amoureux à Lisbonne. Il ne trouve que ses parents : Bartolomeu, vieux marin malade, et Munda, sa femme amère. Chacun lui raconte une version différente de l'histoire de Deolinda.",
    whyRead: [
      "Un jeune médecin perdu dans les secrets d'une famille.",
      "Un roman court, drôle et mélancolique.",
      "Les liens entre le Portugal et le Mozambique, vus avec malice.",
    ],
    year: 2008,
    originalLanguage: "portugais",
    publisher: "Métailié",
    pages: 168,
    isbn: "9782864248958",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-accordeur-de-silences",
    title: "L'Accordeur de silences",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "enfance", "guerre"],
    summary:
      "Après la mort de sa femme, Silvestre Vitalício emmène ses deux fils dans une réserve de chasse abandonnée, qu'il appelle Jésusalem. Il leur affirme que le monde a disparu et qu'ils sont les derniers humains. Mwanito, le plus jeune, grandit dans ce silence, avec son frère, un oncle et un vieux serviteur. Jusqu'au jour où une femme portugaise arrive dans ce refuge.",
    whyRead: [
      "Un père qui invente la fin du monde pour fuir son chagrin.",
      "Un roman sur le silence et les secrets de famille.",
      "Une écriture d'une grande beauté.",
    ],
    year: 2009,
    originalLanguage: "portugais",
    publisher: "Métailié",
    pages: 235,
    isbn: "9782864248996",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "et-si-obama-etait-africain",
    title: "Et si Obama était africain ?",
    subtitle: "suivi de Luso-aphonies, la lusophonie entre voyages et crimes",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite"],
    summary:
      "Au moment de l'élection de Barack Obama, Mia Couto se demande ce qui serait arrivé à un homme comme lui s'il avait voulu faire de la politique dans un pays africain. Il en profite pour dresser un portrait ironique des dirigeants du continent qui s'accrochent au pouvoir. Le second texte s'interroge sur ce que partagent vraiment les pays de langue portugaise. Deux textes brefs et percutants.",
    whyRead: [
      "Un regard ironique et lucide sur la politique africaine.",
      "Deux textes très courts, faciles à lire.",
      "Mia Couto essayiste, moins connu que le romancier.",
    ],
    year: 2009,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 37,
    isbn: "9782915540680",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "murer-la-peur",
    title: "Murer la peur",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite"],
    summary:
      "En 2011, invité à une conférence sur la sécurité au Portugal, Mia Couto prononce un discours sur la peur. Il rappelle qu'enfant, au Mozambique colonial, on lui a appris à craindre les autres, et montre comment les pouvoirs entretiennent la peur pour mieux gouverner. Il invite à abattre les murs plutôt qu'à en construire. Un texte de quelques pages, devenu célèbre.",
    whyRead: [
      "Un discours bref et lumineux contre la politique de la peur.",
      "Des souvenirs d'enfance au Mozambique colonial.",
      "Un texte à lire et à partager.",
    ],
    year: 2011,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 27,
    isbn: "9782367321301",
    format: null,
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "traducteur-de-pluies",
    title: "Traducteur de pluies",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "poesie",
    audience: "adulte",
    themes: ["famille", "identite", "amour"],
    summary:
      "Avant d'être romancier, Mia Couto a été poète, et il n'a jamais cessé de l'être. Dans ce recueil, ses poèmes parlent de la pluie, de la mémoire, de l'enfance, de l'amour et du temps. Les images y sont simples et inattendues, comme dans ses romans. C'est le premier livre de poèmes de Mia Couto traduit en français.",
    whyRead: [
      "Le premier recueil de poèmes de Mia Couto en français.",
      "Une poésie simple et pleine d'images.",
      "Pour entendre la voix intime du romancier.",
    ],
    year: 2011,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 147,
    isbn: "9782367322858",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-confession-de-la-lionne",
    title: "La Confession de la lionne",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "famille"],
    summary:
      "À Kulumani, un village du nord du Mozambique, des lions attaquent et tuent des femmes. Un chasseur venu de la capitale, Arcanjo Baleiro, est appelé pour les abattre. Mariamar, une jeune femme du village dont la sœur vient d'être tuée, attend son arrivée depuis des années. En alternant leurs deux voix, le roman révèle peu à peu une autre violence, celle que subissent les femmes. Inspiré de faits réels vécus par l'auteur.",
    whyRead: [
      "Un roman haletant, inspiré d'attaques de lions bien réelles.",
      "Une dénonciation forte de la violence faite aux femmes.",
      "Deux voix qui se répondent, d'une grande beauté.",
    ],
    year: 2012,
    originalLanguage: "portugais",
    publisher: "Métailié",
    pages: 233,
    isbn: "9791022601474",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-sables-de-l-empereur",
    title: "Les Sables de l'empereur",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "guerre", "histoire", "femmes"],
    summary:
      "À la fin du XIXe siècle, les Portugais font la guerre à Ngungunyane, le dernier empereur du Gaza, dans le sud du Mozambique. Imani, une jeune fille du peuple chope qui a appris le portugais à la mission, devient l'interprète d'un sergent portugais envoyé dans son village. Entre eux naît un lien que la guerre rend dangereux. Ce grand roman en trois parties raconte la chute d'un empire africain.",
    whyRead: [
      "Une grande fresque historique sur la conquête du Mozambique.",
      "Une héroïne forte, prise entre deux peuples et deux langues.",
      "La trilogie complète réunie en un seul volume.",
    ],
    year: 2015,
    originalLanguage: "portugais",
    publisher: "Métailié",
    pages: 665,
    isbn: "9791022609876",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-cartographe-des-absences",
    title: "Le Cartographe des absences",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "histoire", "independances"],
    summary:
      "En 2019, Diogo Santiago, poète et professeur, revient à Beira, la ville de son enfance, pour y recevoir un hommage, quelques jours avant le passage d'un cyclone dévastateur. Une femme, Liana, lui apporte des documents sur son père, poète lui aussi, et sur les derniers temps de la colonisation portugaise. En cherchant la vérité, Diogo remonte aux années 1970 et aux secrets de sa famille.",
    whyRead: [
      "Le roman le plus personnel de Mia Couto, nourri de son histoire familiale.",
      "Beira, entre la fin de la colonisation et le cyclone de 2019.",
      "Une enquête émouvante sur un père et une époque.",
    ],
    year: 2020,
    originalLanguage: "portugais",
    publisher: "Métailié",
    pages: 353,
    isbn: "9791022613927",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-chasseur-d-elephants-invisibles",
    title: "Le Chasseur d'éléphants invisibles",
    contributors: [COUTO, trad("Elisabeth Monteiro Rodrigues")],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["contes", "famille", "tradition"],
    summary:
      "Dans ces nouvelles, Mia Couto fait vivre des personnages ordinaires du Mozambique, comme ce chasseur qui donne son titre au recueil. Chaque histoire part du quotidien pour glisser vers le merveilleux. L'auteur y déploie son goût des mots inventés et des fables. Un recueil récent, plein d'humour et de poésie.",
    whyRead: [
      "Des nouvelles récentes d'un grand conteur.",
      "Le quotidien qui bascule doucement dans la fable.",
      "Des textes courts, parfaits pour découvrir l'auteur.",
    ],
    year: 2021,
    originalLanguage: "portugais",
    publisher: "Chandeigne",
    pages: 160,
    isbn: "9782367322438",
    format: null,
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "ne-pleure-pas-mon-enfant", "la-riviere-de-vie", "et-le-ble-jaillira", "petales-de-sang", "decoloniser-l-esprit",
  "pour-une-afrique-libre", "combattants-et-martyrs", "les-neuf-parfaites", "terres-de-crepuscule", "au-coeur-de-ce-pays",
  "en-attendant-les-barbares", "michael-k-sa-vie-son-temps", "foe", "l-age-de-fer", "le-maitre-de-petersbourg",
  "scenes-de-la-vie-d-un-jeune-garcon", "vers-l-age-d-homme", "elizabeth-costello", "l-homme-ralenti", "journal-d-une-annee-noire",
  "l-ete-de-la-vie", "une-enfance-de-jesus", "l-education-de-jesus", "la-mort-de-jesus", "le-polonais", "trois-histoires",
  "l-abattoir-de-verre", "paysage-sud-africain", "doubler-le-cap", "de-la-lecture-a-l-ecriture", "ici-et-maintenant", "la-verite-du-recit",
  "conversations-avec-moi-meme", "lettres-de-prison", "le-malaise", "la-fleche-de-dieu", "le-demagogue",
  "femmes-en-guerre-et-autres-nouvelles", "les-termitieres-de-la-savane", "l-hibiscus-pourpre", "autour-de-ton-cou", "americanah",
  "nous-sommes-tous-des-feministes", "chere-ijeawele", "notes-sur-le-chagrin", "l-inventaire-des-reves", "sublime-royaume",
  "les-gens-des-marais", "le-lion-et-la-perle", "la-danse-de-la-foret", "la-recolte-de-kongi", "la-route", "les-interpretes",
  "cycles-sombres", "fous-et-specialistes", "cet-homme-est-mort", "une-saison-d-anomie", "les-bacchantes-d-euripide",
  "du-rouge-de-cam-sur-les-feuilles", "la-metamorphose-de-frere-jero", "la-mort-et-l-ecuyer-du-roi", "la-terre-de-mandela",
  "ibadan-les-annees-pagaille", "isara", "baabou-roi", "il-te-faut-partir-a-l-aube",
  "chroniques-du-pays-des-gens-les-plus-heureux-du-monde", "memoire-du-depart", "la-voie-des-pelerins", "adieu-zanzibar",
  "les-vies-d-apres", "les-baleines-de-quissico", "histoires-reverees", "la-veranda-au-frangipanier", "tombe-tombe-au-fond-de-l-eau",
  "chronique-des-jours-de-cendre", "le-dernier-vol-du-flamant", "le-chat-et-le-noir", "un-fleuve-appele-temps-une-maison-appelee-terre",
  "le-fil-des-missangas", "la-pluie-ebahie", "poisons-de-dieu-remedes-du-diable", "l-accordeur-de-silences", "et-si-obama-etait-africain",
  "murer-la-peur", "traducteur-de-pluies", "la-confession-de-la-lionne", "les-sables-de-l-empereur", "le-cartographe-des-absences",
  "le-chasseur-d-elephants-invisibles",
];
