/**
 * Lot 05 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Congo et RDC (avec le Tchadien Nimrod) : Mabanckou, Sony Labou Tansi, Dongala, Lopes, Bofane, Mwanza Mujila, N'Sondé, Nimrod.
 * Éditions, pages et ISBN relevés au catalogue de la BnF ; disponibilité relevée sur leslibraires.fr.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });
const coauteur = (name: string) => ({ role: "auteur" as const, name, authorSlug: null });
const illustrateur = (name: string) => ({ role: "dessinateur" as const, name, authorSlug: null });

const MABANCKOU = auteur("Alain Mabanckou", "alain-mabanckou");
const SONY = auteur("Sony Labou Tansi", "sony-labou-tansi");
const DONGALA = auteur("Emmanuel Dongala", "emmanuel-dongala");
const LOPES = auteur("Henri Lopes", "henri-lopes");
const BOFANE = auteur("In Koli Jean Bofane", "in-koli-jean-bofane");
const MUJILA = auteur("Fiston Mwanza Mujila", "fiston-mwanza-mujila");
const NSONDE = auteur("Wilfried N'Sondé", "wilfried-nsonde");
const NIMROD = auteur("Nimrod", "nimrod");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Alain Mabanckou
  livre({
    slug: "la-legende-de-l-errance",
    title: "La Légende de l'errance",
    contributors: [MABANCKOU],
    genre: "poesie",
    audience: "adulte",
    themes: ["famille", "exil", "spiritualite"],
    summary:
      "Ce long poème est un adieu. Le fils, resté loin du Congo, n'a pas assisté aux funérailles de sa mère, une paysanne modeste morte seule. Il reconstitue en vers les signes qui ont annoncé ce deuil, puis le jour même de la mort, comme on raconte une légende. On y entend déjà la douleur de l'absence qui traversera toute l'œuvre de Mabanckou.",
    whyRead: [
      "Un hommage poignant du fils exilé à sa mère disparue.",
      "Les débuts poétiques de l'auteur de « Verre Cassé ».",
      "La source d'un thème qui reviendra dans « Lumières de Pointe-Noire ».",
    ],
    year: 1995,
    publisher: "L'Harmattan",
    pages: 91,
    isbn: "9782738435590",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "bleu-blanc-rouge",
    title: "Bleu-Blanc-Rouge",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "identite"],
    summary:
      "Au Congo, Massala-Massala a lâché ses études et ne pense qu'à Paris. Chaque saison sèche, il voit revenir au quartier Charles Moki, le « Parisien », habillé comme un prince et couvert de cadeaux. Il finit par partir à son tour. Mais la France qu'il découvre n'a rien de la carte postale : logements de fortune, petits trafics, papiers introuvables, et une spirale dont il est difficile de sortir.",
    whyRead: [
      "Le premier roman de Mabanckou, déjà drôle et grinçant.",
      "Le revers du rêve européen, vu par un jeune Congolais.",
      "Grand prix littéraire d'Afrique noire 1999.",
    ],
    year: 1998,
    publisher: "Présence africaine",
    pages: 222,
    isbn: "9782708708136",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1999 }],
  }),
  livre({
    slug: "quand-le-coq-annoncera-l-aube-d-un-autre-jour",
    title: "Quand le coq annoncera l'aube d'un autre jour",
    contributors: [MABANCKOU],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "identite", "spiritualite"],
    summary:
      "Dans ce recueil, le cinquième de ses livres de poésie, Mabanckou poursuit la quête d'un lieu à soi. Le poète, déraciné, cherche un « pays à venir » qui ne se confond plus tout à fait avec la terre natale. Les poèmes disent l'errance, le trouble intérieur de celui qui vit ailleurs, et l'attente d'un jour nouveau.",
    whyRead: [
      "Le Mabanckou poète, avant la célébrité des romans.",
      "Des vers sur l'exil et l'attente d'un ailleurs meilleur.",
    ],
    year: 1999,
    publisher: "L'Harmattan",
    pages: 85,
    isbn: "9782738482983",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "et-dieu-seul-sait-comment-je-dors",
    title: "Et Dieu seul sait comment je dors",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "spiritualite"],
    summary:
      "Le roman se passe en Guadeloupe, loin des images de carte postale. Auguste-Victor, un homme qui se sait laid, est hanté par l'image d'un bébé qui pleure dans un berceau. Mabakana, un vieil Africain arrivé sur l'île cinquante ans plus tôt, a perdu le sommeil depuis le jour où il a croisé cet homme tout de blanc vêtu. Construit comme une enquête, le livre suit des gens ordinaires aux prises avec un passé qui ne les lâche pas.",
    whyRead: [
      "Un Mabanckou méconnu, situé aux Antilles.",
      "Une intrigue à suspense sur la culpabilité et le pardon.",
    ],
    year: 2001,
    publisher: "Présence africaine",
    pages: 246,
    isbn: "9782708707191",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "les-petits-fils-negres-de-vercingetorix",
    title: "Les Petits-fils nègres de Vercingétorix",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "politique", "femmes", "famille"],
    summary:
      "Le Viétongo, ancienne colonie d'Afrique centrale, bascule dans la guerre civile après un coup d'État. Le chef rebelle qui se fait appeler Vercingétorix veut reprendre le pouvoir, et les violences entre gens du Nord et gens du Sud se déchaînent. Hortense, qui fuit avec sa fille, tient un journal : elle y raconte la guerre au jour le jour et y recolle les morceaux de sa vie, de son mariage et de son pays.",
    whyRead: [
      "La guerre civile du Congo-Brazzaville à peine transposée.",
      "Une voix de femme qui témoigne au milieu du chaos.",
      "Un roman grave, loin de la fantaisie habituelle de l'auteur.",
    ],
    year: 2002,
    publisher: "Points",
    pages: 248,
    isbn: "9782757800669",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "african-psycho",
    title: "African Psycho",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "ville", "identite"],
    summary:
      "Grégoire Nakobomayo, enfant trouvé d'un quartier pauvre d'une ville africaine, n'a commis jusqu'ici que des délits minables. Lui se rêve en grand criminel, sur le modèle d'Angoualima, tueur légendaire dont tout le pays a peur et qu'il vénère comme un maître. Il décide donc de tuer sa petite amie Germaine et prépare son crime avec un sérieux comique. Mabanckou fait de ce narrateur pathétique et inquiétant le héros d'une satire très noire.",
    whyRead: [
      "Un « American Psycho » africain, à l'humour très noir.",
      "Un narrateur à la fois effrayant et ridicule.",
      "Un roman court et dérangeant, qui se lit d'une traite.",
    ],
    year: 2003,
    publisher: "Points",
    pages: 219,
    isbn: "9782757865125",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "tant-que-les-arbres-s-enracineront-dans-la-terre",
    title: "Tant que les arbres s'enracineront dans la terre",
    contributors: [MABANCKOU],
    genre: "poesie",
    audience: "adulte",
    themes: ["enfance", "famille", "identite", "exil"],
    summary:
      "Ce volume réunit l'essentiel de la poésie de Mabanckou, des premiers recueils au long poème qui donne son titre au livre. Le poète y revient aux bruits et aux odeurs de son enfance congolaise, à la nature, aux arbres et au fleuve, et surtout à sa mère. L'édition de poche augmentée ajoute le recueil « Congo ». Une bonne manière de découvrir l'écrivain par ses vers.",
    whyRead: [
      "Toute la poésie de Mabanckou réunie en un seul poche.",
      "La mère, l'enfance et le Congo au cœur des poèmes.",
    ],
    year: 2004,
    publisher: "Points",
    pages: 398,
    isbn: "9782757866528",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "lettre-a-jimmy",
    title: "Lettre à Jimmy",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "exil", "politique"],
    summary:
      "Vingt ans après la mort de James Baldwin, Mabanckou écrit au grand écrivain américain une longue lettre, en le tutoyant. Il retrace sa vie, de Harlem à Paris puis au sud de la France, et dialogue avec ses livres. Ce qu'il admire chez Baldwin, c'est l'homme libre qui a combattu le racisme sans s'enfermer dans une appartenance. Un hommage complice entre deux écrivains noirs qui refusent les étiquettes.",
    whyRead: [
      "Une belle porte d'entrée dans l'œuvre de James Baldwin.",
      "Mabanckou parle autant de lui que de son modèle.",
    ],
    year: 2007,
    publisher: "Fayard",
    pages: 183,
    isbn: "9782213626765",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "black-bazar",
    title: "Black Bazar",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "humour", "amour"],
    summary:
      "Le narrateur, un Congolais de Paris amateur de beaux costumes, que ses amis surnomment « le Fessologue », vient d'être quitté par sa compagne, partie avec leur fille. Entre le bar où il a ses habitudes, le marché de Château-Rouge et son petit appartement, il ressasse son chagrin. Sa rencontre avec un écrivain haïtien lui donne l'idée de tout coucher par écrit. Une comédie mordante sur la diaspora africaine et ses préjugés.",
    whyRead: [
      "Le Paris africain de Château-Rouge, croqué avec humour.",
      "Un dandy congolais au cœur brisé, irrésistible.",
      "Adapté au théâtre en France et aux États-Unis.",
    ],
    year: 2009,
    publisher: "Points",
    pages: 264,
    isbn: "9782757816394",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "demain-j-aurai-vingt-ans",
    title: "Demain j'aurai vingt ans",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "politique", "humour"],
    summary:
      "Pointe-Noire, dans les années 1970. Michel, une dizaine d'années, grandit entre sa mère, maman Pauline, et son père adoptif, réceptionniste dans un grand hôtel. Il découvre l'amour, l'amitié et le monde par la radio, tandis que le Congo vit à l'heure du socialisme scientifique. Inspiré de l'enfance de l'auteur, ce roman raconte avec une naïveté feinte et beaucoup de tendresse une famille, un quartier et une époque.",
    whyRead: [
      "L'enfance de Mabanckou à Pointe-Noire, pleine de tendresse.",
      "Un narrateur enfant drôle et attachant.",
      "Prix Georges-Brassens 2010, préface de J.M.G. Le Clézio en poche.",
    ],
    year: 2010,
    publisher: "Folio",
    pages: 400,
    isbn: "9782070446230",
    format: "poche",
    awards: [{ name: "Prix Georges-Brassens", year: 2010 }],
  }),
  livre({
    slug: "ma-soeur-etoile",
    title: "Ma Sœur-Étoile",
    contributors: [MABANCKOU, illustrateur("Judith Gueyfier")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "famille"],
    summary:
      "Au Congo, dans les années 1970, un garçon de dix ans, fils unique, se sent souvent seul. Pendant la saison sèche, il sort la nuit dans la cour et attend qu'apparaisse une toute petite étoile, plus brillante que les autres. Il lui parle, lui confie ses secrets et finit par l'appeler sa sœur. Un album tiré des souvenirs d'enfance de l'auteur, illustré par Judith Gueyfier.",
    whyRead: [
      "Un album tendre sur la solitude d'un enfant unique.",
      "Les souvenirs d'enfance de Mabanckou, pour les plus jeunes.",
    ],
    year: 2010,
    publisher: "Seuil Jeunesse",
    pages: null,
    isbn: "9782021005882",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "ecrivain-et-oiseau-migrateur",
    title: "Écrivain et oiseau migrateur",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["exil", "identite", "enfance"],
    summary:
      "Enfant, à Pointe-Noire, Mabanckou regardait passer au-dessus de lui les oiseaux migrateurs. Dans cet essai, il fait de cette image celle de l'écrivain : quelqu'un qui part, qui ne tient pas en place et qui trouve dans le voyage la condition même de l'écriture. Il y raconte son propre parcours, du Congo à la France puis aux États-Unis, et explique pourquoi il se méfie d'une littérature réduite au combat ou à la propagande.",
    whyRead: [
      "Mabanckou explique ce que l'exil fait à l'écriture.",
      "Un essai personnel, nourri de souvenirs d'enfance.",
    ],
    year: 2011,
    publisher: "André Versaille",
    pages: 191,
    isbn: "9782874951558",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "tais-toi-et-meurs",
    title: "Tais-toi et meurs",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "humour"],
    summary:
      "Julien Makambo débarque à Paris sous un faux nom. Pedro, figure du milieu congolais et roi de la sape, le prend sous son aile et l'initie aux combines du quartier de Château-Rouge. La belle vie dure jusqu'au vendredi 13 où Julien se retrouve mêlé à la chute mortelle d'une jeune femme. Depuis sa cellule, il raconte comment il en est arrivé là. Le seul polar de Mabanckou, plein de personnages hauts en couleur.",
    whyRead: [
      "Le seul roman policier de Mabanckou.",
      "Une plongée dans le milieu congolais de Paris.",
    ],
    year: 2012,
    publisher: "Points",
    pages: 201,
    isbn: "9782757897799",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-sanglot-de-l-homme-noir",
    title: "Le Sanglot de l'homme noir",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "colonisation", "exil"],
    summary:
      "Le titre répond à un essai de Pascal Bruckner, « Le Sanglot de l'homme blanc ». Mabanckou, qui s'adresse à son fils né en France, invite les Noirs d'Afrique et d'Europe à ne pas s'enfermer dans la plainte et la rancœur héritées de la colonisation. Il parle de l'immigration, de la langue française, de l'école et de son propre parcours. Pour lui, l'identité se construit chaque jour, par ce que l'on fait plus que par ses origines.",
    whyRead: [
      "Un essai court et franc, qui a fait débat à sa sortie.",
      "Une réflexion personnelle sur l'identité et la mémoire.",
    ],
    year: 2012,
    publisher: "Points",
    pages: 178,
    isbn: "9782757865118",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "lumieres-de-pointe-noire",
    title: "Lumières de Pointe-Noire",
    contributors: [MABANCKOU],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "enfance", "exil", "ville"],
    summary:
      "Après vingt-trois ans d'absence, Mabanckou retourne dans la ville où il a grandi. Sa mère est morte entre-temps et il n'a pas pu assister à son enterrement. Pendant un mois, il revisite la cabane familiale, son ancien lycée, le cinéma de son enfance, retrouve des parents et des voisins. Ce récit autobiographique, accompagné de photographies, mêle souvenirs, rencontres et part de surnaturel.",
    whyRead: [
      "Le retour bouleversant d'un fils au pays natal.",
      "Pointe-Noire racontée de l'intérieur, loin des clichés.",
      "La clé des romans d'enfance de Mabanckou.",
    ],
    year: 2013,
    publisher: "Points",
    pages: 247,
    isbn: "9782757865071",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "petit-piment",
    title: "Petit Piment",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "politique", "ville", "humour"],
    summary:
      "Moïse grandit à l'orphelinat de Loango, près de Pointe-Noire. Quand arrive la révolution socialiste, l'abbé qui égayait la vie des enfants disparaît et le directeur fait régner la discipline du parti. Moïse s'enfuit avec deux redoutables jumeaux et rejoint les enfants des rues de Pointe-Noire, où on le surnomme Petit Piment. Commence alors une vie de débrouille, de rencontres et de dérives.",
    whyRead: [
      "Un héros orphelin qu'on n'oublie pas.",
      "Le Congo révolutionnaire vu par un enfant des rues.",
      "Un roman picaresque à la fois drôle et poignant.",
    ],
    year: 2015,
    publisher: "Points",
    pages: 226,
    isbn: "9782757861882",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "lettres-noires",
    title: "Lettres noires",
    subtitle: "Des ténèbres à la lumière",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "identite", "ecole"],
    summary:
      "En 2016, Alain Mabanckou devient le premier écrivain invité à la chaire de création artistique du Collège de France. Ce petit livre reprend sa leçon inaugurale. Il y montre comment l'Afrique a longtemps été racontée par les seuls Européens, comme un continent sauvage et obscur, avant que les écrivains africains ne prennent la parole. De la négritude à la « migritude », il trace l'histoire de cette littérature.",
    whyRead: [
      "Une leçon claire et vivante sur les littératures africaines.",
      "Un texte historique : la première leçon d'un écrivain africain au Collège de France.",
    ],
    year: 2016,
    publisher: "Pluriel",
    pages: 64,
    isbn: "9782818505526",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-monde-est-mon-langage",
    title: "Le monde est mon langage",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "exil", "ecole"],
    summary:
      "De Pointe-Noire à Cuba, de Montréal à Madagascar, Mabanckou va à la rencontre d'écrivains, d'artistes et d'inconnus qui ont un point commun : le français. Par de courts récits, portraits et entretiens, il raconte ce que chacun fait de cette langue et ce qu'elle lui a apporté. Le livre dessine une francophonie vivante, ouverte, qui ne tourne pas autour de Paris.",
    whyRead: [
      "Un tour du monde en langue française.",
      "Des portraits d'écrivains et d'artistes, grands et petits.",
    ],
    year: 2016,
    publisher: "Points",
    pages: 301,
    isbn: "9782757864135",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "congo",
    title: "Congo",
    contributors: [MABANCKOU],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "enfance", "spiritualite"],
    summary:
      "Dans ce recueil, Mabanckou célèbre l'alliance très ancienne entre l'arbre et l'homme. Les rides d'un tronc ressemblent à celles d'un front, et l'un comme l'autre attendent une forme de renaissance. La poésie y coule comme le fleuve Congo, là où se rejoignent les voix, et ramène vers le royaume de l'enfance.",
    whyRead: [
      "Une poésie méditative sur le fleuve, l'arbre et la mémoire.",
      "Repris en poche chez Points, à la suite de « Tant que les arbres… ».",
    ],
    year: 2016,
    publisher: "Mémoire d'encrier",
    pages: 83,
    isbn: "9782897123758",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-cigognes-sont-immortelles",
    title: "Les Cigognes sont immortelles",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "politique", "enfance", "famille"],
    summary:
      "Mars 1977, à Pointe-Noire. Michel, collégien, prépare son certificat d'études quand on annonce à la radio l'assassinat du président Marien Ngouabi. En trois jours, la ville se fige : couvre-feu, rumeurs, méfiance entre Nordistes et Sudistes. La famille de Michel est touchée de près. Le garçon découvre que la vérité officielle et la vérité tout court ne se ressemblent pas.",
    whyRead: [
      "Un épisode clé de l'histoire du Congo vu à hauteur d'enfant.",
      "On retrouve Michel et maman Pauline de « Demain j'aurai vingt ans ».",
    ],
    year: 2018,
    publisher: "Points",
    pages: 275,
    isbn: "9782757875605",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-coq-solitaire",
    title: "Le Coq solitaire",
    contributors: [MABANCKOU, illustrateur("Yuna Troël")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "famille", "tradition"],
    summary:
      "Grand-père Moulika, chef du village, raconte que chacun a un double animal et que les animaux sont des humains réincarnés. Son petit-fils Michel n'y croit qu'à moitié. Le jour où il veut chasser un vieux coq myope et malodorant, son grand-père l'en empêche vivement. Pourquoi ce coq compte-t-il tant ? Un conte initiatique sur les liens entre les vivants et leurs ancêtres.",
    whyRead: [
      "Un conte africain sur la transmission entre générations.",
      "Un grand album richement illustré par Yuna Troël.",
    ],
    year: 2019,
    publisher: "Seuil Jeunesse",
    pages: null,
    isbn: "9791023512816",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "huit-lecons-sur-l-afrique",
    title: "Huit leçons sur l'Afrique",
    contributors: [MABANCKOU],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "identite", "histoire", "ecole"],
    summary:
      "Ce livre rassemble les cours donnés par Mabanckou au Collège de France en 2016. Il y parle de littérature, mais aussi de cinéma, de peinture et de politique, en faisant revivre des créateurs longtemps laissés dans l'ombre, d'Aimé Césaire à Mongo Beti et de Mariama Bâ à Paulette Nardal. Il y défend une francophonie qui ne tourne plus autour de la seule France. Le volume contient aussi sa lettre ouverte au président de la République sur la francophonie.",
    whyRead: [
      "Un cours accessible sur un siècle de création africaine.",
      "Pour découvrir des écrivains et artistes souvent oubliés.",
    ],
    year: 2020,
    publisher: "Points",
    pages: 212,
    isbn: "9782757887004",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "rumeurs-d-amerique",
    title: "Rumeurs d'Amérique",
    contributors: [MABANCKOU],
    genre: "recit",
    audience: "adulte",
    themes: ["exil", "identite", "ville"],
    summary:
      "Installé depuis des années en Californie, où il enseigne, Mabanckou raconte son Amérique. De Los Angeles au Michigan, il observe ceux qui lui ressemblent et ceux qui ne lui ressemblent pas, fouille l'histoire de certains lieux et s'amuse de l'insolite du quotidien. Entre anecdotes, digressions et rêverie, il signe une sorte d'autobiographie américaine.",
    whyRead: [
      "Les États-Unis vus par un écrivain franco-congolais.",
      "Des chroniques vives, drôles et personnelles.",
    ],
    year: 2020,
    publisher: "Points",
    pages: 231,
    isbn: "9782757889176",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-commerce-des-allonges",
    title: "Le Commerce des Allongés",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "spiritualite", "politique", "humour"],
    summary:
      "Liwa, jeune cuisinier d'un grand hôtel de Pointe-Noire, élevé par sa grand-mère, ressort de sa tombe au cimetière des pauvres. Mort, il se souvient de sa dernière soirée, un 15 août, jour de fête nationale, où il était allé danser dans ses plus beaux habits et avait rencontré la belle Adeline. Pendant ce temps, il découvre le monde des morts, où les inégalités entre riches et pauvres continuent comme chez les vivants.",
    whyRead: [
      "Un narrateur mort, drôle et mélancolique.",
      "Une satire sociale qui se poursuit jusqu'au cimetière.",
    ],
    year: 2022,
    publisher: "Points",
    pages: 245,
    isbn: "9782757899687",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "cette-femme-qui-nous-regarde",
    title: "Cette femme qui nous regarde",
    subtitle: "Angela Davis, l'Amérique et moi",
    contributors: [MABANCKOU],
    genre: "recit",
    audience: "adulte",
    themes: ["identite", "politique", "exil"],
    summary:
      "Enfant, au Congo, Mabanckou voyait l'autobiographie d'Angela Davis dans la bibliothèque familiale, avec le visage de la militante en couverture. Des années plus tard, devenu professeur aux États-Unis, il finit par la rencontrer. Ce récit, entre réalité et fiction, raconte ce que cette rencontre a changé dans son regard sur l'Amérique, la France et le Congo, et dresse le portrait d'une grande figure de la lutte contre le racisme.",
    whyRead: [
      "Le portrait d'Angela Davis par un écrivain qui l'admire.",
      "Un récit court et personnel sur la fraternité.",
    ],
    year: 2024,
    publisher: "Robert Laffont",
    pages: 157,
    isbn: "9782221253878",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "ramses-de-paris",
    title: "Ramsès de Paris",
    contributors: [MABANCKOU],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "ville", "humour", "famille"],
    summary:
      "Un jeune apprenti écrivain, qui se fait appeler Berado, a rejoint à Paris son grand frère Benoît, séducteur fantasque du quartier de Château-Rouge. Quand Benoît épouse Lilwenn, au grand dam de la patronne du restaurant Manioc Pays, les ennuis s'annoncent. Pour donner sa version des faits, Berado va trouver Ramsès, barman d'un petit hôtel du XIe arrondissement. Son récit, sans cesse interrompu, glisse peu à peu entre rêve et réalité.",
    whyRead: [
      "Les « Mille et Une Nuits » de l'exil africain à Paris.",
      "Un roman drôle, peuplé de personnages truculents.",
    ],
    year: 2025,
    publisher: "Seuil",
    pages: 256,
    isbn: "9782021591859",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Sony Labou Tansi
  livre({
    slug: "l-etat-honteux",
    title: "L'État honteux",
    contributors: [SONY],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "independances"],
    summary:
      "Le colonel Martillimi Lopez, fils de « Maman Nationale », règne sur un pays imaginaire d'Afrique. Un jour, ses ministres, ses généraux et ses hauts fonctionnaires viennent un à un lui remettre leur démission, car ils refusent de laisser le pays « dans cet état honteux ». Le dictateur, obsédé par sa hernie dont il a fait un symbole national, ne se laisse pas émouvoir. Une farce politique féroce, dans la lignée d'« Ubu roi ».",
    whyRead: [
      "Une satire sans pitié des dictatures africaines.",
      "La langue inventive et débridée de Sony Labou Tansi.",
    ],
    year: 1981,
    publisher: "Seuil",
    pages: 156,
    isbn: "9782020058537",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "la-parenthese-de-sang",
    title: "La Parenthèse de sang",
    subtitle: "suivi de Je soussigné cardiaque",
    contributors: [SONY],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "guerre"],
    summary:
      "Deux pièces sur la violence du pouvoir. Dans la première, les soldats d'un régime totalitaire recherchent le rebelle Libertashio et refusent de croire qu'il est mort et enterré ; ils s'en prennent à sa famille avec une logique absurde. Dans la seconde, Mallot, modeste instituteur, a une idée trop personnelle de la liberté et de la dignité, et il va le payer cher. Un théâtre de l'absurde ancré dans l'Afrique des dictatures.",
    whyRead: [
      "Deux classiques du théâtre africain francophone.",
      "Une farce terrible sur l'absurdité de la répression.",
    ],
    year: 1981,
    publisher: "Hatier",
    pages: 142,
    isbn: "9782747302104",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "l-ante-peuple",
    title: "L'Anté-peuple",
    contributors: [SONY],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "amour", "exil"],
    summary:
      "Dadou, directeur d'une école de jeunes filles à Kinshasa, mène une vie rangée avec sa femme et leurs enfants. Une élève, Yavelde, s'éprend de lui et le poursuit de son amour ; il tente de résister, se met à boire, et le drame éclate. Accusé, emprisonné, il s'évade et traverse le fleuve. Commence alors une fuite à travers des pays aussi corrompus et violents que le sien, en quête d'un sens à sa vie.",
    whyRead: [
      "La descente aux enfers d'un homme ordinaire.",
      "Un roman fiévreux entre les deux Congo.",
      "Grand prix littéraire d'Afrique noire 1983.",
    ],
    year: 1983,
    publisher: "Points",
    pages: 210,
    isbn: "9782757816714",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1983 }],
  }),
  livre({
    slug: "les-sept-solitudes-de-lorsa-lopez",
    title: "Les Sept Solitudes de Lorsa Lopez",
    contributors: [SONY],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "politique", "contes"],
    summary:
      "Dans une ville côtière d'un pays imaginaire, Lorsa Lopez tue sa femme Estina Benta, et tout le monde le sait. La ville attend que la police vienne constater le crime, mais elle ne vient pas. Face à cette lâcheté collective, une femme prend la tête des autres et refuse que l'on continue à fermer les yeux. Un roman foisonnant, entre fable et réalisme magique, sur la condition des femmes et l'impunité.",
    whyRead: [
      "Un grand roman sur la révolte des femmes.",
      "Une ville imaginaire digne de García Márquez.",
    ],
    year: 1985,
    publisher: "Points",
    pages: 200,
    isbn: "9782757810590",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "les-yeux-du-volcan",
    title: "Les Yeux du volcan",
    contributors: [SONY],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "ville", "contes"],
    summary:
      "Dans une Brazzaville transfigurée, où les noms des lieux sont fragiles, la population attend une révolution qui ne vient pas. L'auteur fait de ce roman une sorte de réquisitoire poétique contre la misère, où l'amour des mots, l'amitié et l'humour servent d'armes. Un livre visionnaire, où l'Afrique entière gronde comme un volcan prêt à se réveiller.",
    whyRead: [
      "Un roman-poème sur la colère qui couve.",
      "L'imagination débordante de Sony Labou Tansi.",
    ],
    year: 1988,
    publisher: "Seuil",
    pages: 191,
    isbn: "9782020100823",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "qui-a-mange-madame-d-avoine-bergotha",
    title: "Qui a mangé Madame d'Avoine Bergotha ?",
    contributors: [SONY],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "amour", "humour"],
    summary:
      "Un amoureux transi se retrouve engagé malgré lui dans une lutte à mort contre une tyrannie postcoloniale. Pour mener ce combat, il prend l'apparence d'une femme. Le travestissement, ressort classique de la comédie, déclenche ici une mécanique vertigineuse qui mène le monde au bord de la destruction. Une pièce où le rire bascule dans l'inquiétude.",
    whyRead: [
      "Une comédie du travestissement qui tourne au cauchemar politique.",
      "L'édition Lansman ajoute un entretien avec l'auteur.",
    ],
    year: 1989,
    publisher: "Lansman",
    pages: 95,
    isbn: "9782807100114",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "le-commencement-des-douleurs",
    title: "Le Commencement des douleurs",
    contributors: [SONY],
    genre: "roman",
    audience: "adulte",
    themes: ["tradition", "humour", "amour"],
    summary:
      "À Hondo-Noote, ville de la Côte où chaque tempête passe pour un présage, le savant Hoscar Hana donne un baiser trop appuyé à la plus jeune fille du riche Arthur Banos Maya. Ce geste qui viole la coutume semble déclencher la colère des éléments. Le savant multiplie les ruses rationnelles pour échapper à son destin, sans grand succès. Le dernier roman de Sony Labou Tansi, paru l'année de sa mort, est une comédie cosmique traversée d'inquiétude.",
    whyRead: [
      "Le dernier roman de Sony Labou Tansi, paru en 1995.",
      "Un vaudeville où la nature se mêle des affaires humaines.",
    ],
    year: 1995,
    publisher: "Seuil",
    pages: 154,
    isbn: "9782020257985",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "encre-sueur-salive-et-sang",
    title: "Encre, sueur, salive et sang",
    contributors: [SONY],
    genre: "essai",
    audience: "adulte",
    themes: ["politique", "identite"],
    summary:
      "On connaît Sony Labou Tansi romancier, dramaturge et poète ; ce livre fait entendre le penseur. Il rassemble des textes critiques, déclarations et réflexions écrits entre 1973 et sa mort en 1995. L'écrivain y parle de son métier, de la langue, de la violence du monde et de ceux qu'on maintient à genoux, en Afrique et ailleurs. L'édition est établie et présentée par Greta Rodriguez-Antoniotti.",
    whyRead: [
      "La pensée d'un grand écrivain, longtemps restée dispersée.",
      "Des textes brûlants sur l'écriture et l'engagement.",
    ],
    year: 2015,
    publisher: "Seuil",
    pages: 195,
    isbn: "9782021285925",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "poemes-sony-labou-tansi",
    title: "Poèmes",
    subtitle: "Édition critique",
    contributors: [SONY],
    genre: "poesie",
    audience: "adulte",
    themes: ["politique", "identite", "spiritualite"],
    summary:
      "Sony Labou Tansi se disait d'abord poète, mais sa poésie est longtemps restée presque invisible, éparpillée dans des revues ou enfouie dans ses cahiers. Ce gros volume réunit pour la première fois l'ensemble de ses poèmes, des textes parus de son vivant aux nombreux inédits retrouvés après sa mort. L'édition, dirigée par Claire Riffard et Nicolas Martin-Granel, rend à cette œuvre torrentielle toute son ampleur.",
    whyRead: [
      "Toute la poésie de Sony Labou Tansi en un volume.",
      "Une édition de référence, pour lecteurs passionnés.",
    ],
    year: 2015,
    publisher: "CNRS Éditions",
    pages: 1252,
    isbn: "9782271087430",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),

  // ------------------------------------------------------------------ Emmanuel Dongala
  livre({
    slug: "un-fusil-dans-la-main-un-poeme-dans-la-poche",
    title: "Un fusil dans la main, un poème dans la poche",
    contributors: [DONGALA],
    genre: "roman",
    audience: "adulte",
    themes: ["independances", "politique", "guerre"],
    summary:
      "Mayéla dia Mayéla est un jeune intellectuel africain nourri des idées de Fanon, de Cabral et de Lumumba. Il passe du combat des idées à la lutte armée dans les maquis d'Afrique australe, puis accède au sommet du pouvoir dans son pays. Le roman suit l'itinéraire de toute une génération qui rêvait d'une Afrique libérée et qui a vu le colon remplacé par de nouveaux maîtres.",
    whyRead: [
      "Le premier roman de Dongala, publié en 1973.",
      "Le portrait d'une génération de révolutionnaires africains.",
    ],
    year: 1973,
    publisher: "Le Serpent à plumes",
    pages: 395,
    isbn: "9782842614614",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "jazz-et-vin-de-palme",
    title: "Jazz et vin de palme",
    contributors: [DONGALA],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["politique", "humour", "exil"],
    summary:
      "Ces nouvelles promènent le lecteur de la Brazzaville révolutionnaire aux clubs de jazz de New York. On y retrouve la Brazzaville de la « révolution rouge », des extraterrestres qu'apaise seulement le vin de palme, et un saxophoniste de génie en quête d'absolu, dans le sillage de John Coltrane. Sous l'humour et l'absurde, Dongala dit la désillusion des jeunes États africains après les indépendances.",
    whyRead: [
      "Des nouvelles drôles et désenchantées.",
      "Un bel hommage au jazz et à Coltrane.",
    ],
    year: 1982,
    publisher: "Le Serpent à plumes",
    pages: 205,
    isbn: "9782842610036",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-feu-des-origines",
    title: "Le Feu des origines",
    contributors: [DONGALA],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "tradition", "histoire", "contes"],
    summary:
      "Né à l'écart du village, l'enfant aux yeux verts Mandala Mankunku se révèle d'une curiosité sans limites. Forgeron, chasseur, sculpteur, guérisseur, il dépasse tous ses maîtres et finit par se rebeller contre un monde ancien qu'il croit connaître par cœur. Arrivent alors les Blancs, qui pillent et soumettent. Par la vie de ce héros, Dongala raconte la première moitié du XXe siècle au Congo, au temps de la conquête coloniale.",
    whyRead: [
      "Une épopée africaine au souffle de légende.",
      "La colonisation vue depuis un village congolais.",
      "Grand prix littéraire d'Afrique noire 1988.",
    ],
    year: 1987,
    publisher: "Actes Sud (Babel)",
    pages: 292,
    isbn: "9782330103217",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1988 }],
  }),
  livre({
    slug: "les-petits-garcons-naissent-aussi-des-etoiles",
    title: "Les petits garçons naissent aussi des étoiles",
    contributors: [DONGALA],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "politique", "humour", "famille"],
    summary:
      "Matapari, dernier né de triplés, est venu au monde deux jours après ses frères. De cette naissance tardive, il garde une curiosité insatiable. Avec ses yeux d'enfant faussement naïf, il observe les manigances de son oncle Boula Boula, coureur de jupons qui grimpe dans les hautes sphères du parti unique. Un roman grinçant sur une Afrique otage de ses dirigeants, à la manière d'un « Candide au Congo ».",
    whyRead: [
      "Un enfant narrateur malicieux et lucide.",
      "Une satire pleine d'humour du parti unique.",
    ],
    year: 1998,
    publisher: "Le Serpent à plumes",
    pages: 395,
    isbn: "9782268073057",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "photo-de-groupe-au-bord-du-fleuve",
    title: "Photo de groupe au bord du fleuve",
    contributors: [DONGALA],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "travail", "politique"],
    summary:
      "Elles sont une quinzaine à casser des pierres dans une carrière au bord d'un fleuve africain. Apprenant que la construction d'un aéroport a fait monter le prix du gravier, elles décident d'augmenter le prix de leurs sacs et choisissent Méréana pour négocier. Ce qui commence comme une simple discussion devient une véritable lutte. Chacune, marquée par la pauvreté, la guerre ou la violence des hommes, y découvre la force du collectif.",
    whyRead: [
      "Un grand roman social, porté par des femmes debout.",
      "De l'humour et de l'espoir malgré la dureté des vies.",
      "Prix Ahmadou-Kourouma 2011.",
    ],
    year: 2010,
    publisher: "Actes Sud (Babel)",
    pages: 439,
    isbn: "9782330012991",
    format: "poche",
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2011 }],
  }),
  livre({
    slug: "la-sonate-a-bridgetower",
    title: "La Sonate à Bridgetower",
    subtitle: "Sonata mulattica",
    contributors: [DONGALA],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "esclavage", "identite"],
    summary:
      "En 1789, George Bridgetower, violoniste prodige de neuf ans, arrive à Paris avec son père, un Noir de la Barbade qui se fait passer pour un prince d'Abyssinie. Élève de Haydn, l'enfant doit leur apporter gloire et fortune. De Paris à Londres puis à Vienne, le roman suit son apprentissage jusqu'à son amitié avec Beethoven, qui lui dédie à l'origine la sonate connue aujourd'hui sous le nom de « Sonate à Kreutzer ». Une fresque du siècle des Lumières, de ses idées et de ses contradictions.",
    whyRead: [
      "L'histoire vraie d'un musicien noir oublié.",
      "Un roman érudit et vivant sur l'Europe des Lumières.",
    ],
    year: 2017,
    publisher: "Actes Sud (Babel)",
    pages: 430,
    isbn: "9782330118587",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Henri Lopes
  livre({
    slug: "tribaliques",
    title: "Tribaliques",
    contributors: [LOPES],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["politique", "femmes", "independances", "tradition"],
    summary:
      "Premier livre d'Henri Lopes, ce recueil de huit nouvelles observe la société congolaise des années qui suivent l'indépendance. Le tribalisme, les petits arrangements des nouveaux puissants, le sort fait aux femmes y sont montrés à travers des histoires de gens ordinaires. Le ton est ironique, souvent amer, déjà lucide sur les promesses trahies.",
    whyRead: [
      "Le premier livre d'un grand romancier congolais.",
      "Grand prix littéraire d'Afrique noire 1972.",
    ],
    year: 1971,
    publisher: "Éditions CLÉ",
    pages: null,
    isbn: null,
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1972 }],
  }),
  livre({
    slug: "la-nouvelle-romance",
    title: "La Nouvelle Romance",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "independances"],
    summary:
      "N'Kamba, surnommé Delarumba, est une vedette du football local qui vit à sa guise. Sa femme, Wali, s'efface et se soumet. Mais elle va peu à peu prendre conscience de sa situation et se battre pour gagner son indépendance. Le premier roman d'Henri Lopes fait de l'émancipation des femmes l'un des grands enjeux de l'Afrique nouvelle.",
    whyRead: [
      "Le premier roman de Lopes, centré sur une femme qui s'émancipe.",
      "Un regard précoce sur l'égalité dans le couple africain.",
    ],
    year: 1976,
    publisher: "Éditions CLÉ",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "sans-tam-tam",
    title: "Sans tam-tam",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "ecole", "independances"],
    summary:
      "Gatsé, professeur, a été envoyé dans un collège de brousse à cause de ses opinions. Quand on lui propose un poste prestigieux à l'ambassade, en France, il préfère rester auprès de ses élèves. Dans des lettres, il explique son choix. Ce roman épistolaire dénonce la corruption des élites et défend une autre idée du service du pays.",
    whyRead: [
      "Un roman par lettres, court et engagé.",
      "Un héros qui choisit l'école plutôt que les honneurs.",
    ],
    year: 1977,
    publisher: "Éditions CLÉ",
    pages: 126,
    isbn: "9782723500135",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "le-chercheur-d-afriques",
    title: "Le Chercheur d'Afriques",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "exil", "famille"],
    summary:
      "André est né au Congo d'une mère noire et d'un père blanc qu'il n'a pas connu. Au pays, on le traite de « mal blanchi » ; en France, où il arrive jeune homme, il devient le « moricaud ». Il a promis à sa mère d'approcher le docteur Leclerc, un ancien colon à qui il ressemble étrangement. Entre souvenirs d'Afrique et découverte du jazz, il cherche sa place et son père.",
    whyRead: [
      "Un roman sensible sur le métissage et la quête du père.",
      "Prix Jules-Verne 1990.",
    ],
    year: 1990,
    publisher: "Points",
    pages: 312,
    isbn: "9782020849609",
    format: "poche",
    awards: [{ name: "Prix Jules-Verne", year: 1990 }],
  }),
  livre({
    slug: "sur-l-autre-rive",
    title: "Sur l'autre rive",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "amour", "femmes", "exil"],
    summary:
      "Marie-Ève, peintre installée dans une île des Caraïbes, semble avoir tout réussi. À la veille du vernissage qui doit la consacrer, elle croise un couple d'Africains qui paraît la reconnaître. Ce simple regard rouvre un passé qu'elle croyait effacé, au Gabon puis sur les rives du Congo, et une histoire d'amour qu'elle avait fuie. Un roman sur l'identité qu'on se choisit et celle qui vous rattrape.",
    whyRead: [
      "Une héroïne forte, entre Caraïbes et Afrique centrale.",
      "Un roman d'atmosphère sur la mémoire et le métissage.",
    ],
    year: 1992,
    publisher: "Seuil",
    pages: 235,
    isbn: "9782020168731",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "le-lys-et-le-flamboyant",
    title: "Le Lys et le Flamboyant",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "histoire", "femmes", "independances"],
    summary:
      "Victor-Augagneur Houang entreprend de raconter la vie de Kolélé, une femme métisse née au Congo au début du XXe siècle. Chanteuse, elle connaît en France un début de carrière de diva, puis s'engage aux côtés des partisans de Lumumba et se retrouve mêlée à la guérilla au Congo-Kinshasa. Le narrateur prétend corriger un certain Henri Lopes qui aurait déjà raconté son histoire. Une grande fresque musicale et malicieuse sur le métissage.",
    whyRead: [
      "Une grande fresque sur un demi-siècle d'histoire congolaise.",
      "Un jeu savoureux entre l'auteur et son narrateur.",
    ],
    year: 1997,
    publisher: "Seuil",
    pages: 430,
    isbn: "9782020200967",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "dossier-classe",
    title: "Dossier classé",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "famille", "exil", "histoire"],
    summary:
      "Lazare Mayélé, journaliste pour une revue américaine, a quitté son pays, le Mossika, à l'âge de six ans. La quarantaine venue, il y retourne pour un reportage, mais aussi pour comprendre l'assassinat de son père, tué peu après l'indépendance dans des circonstances jamais éclaircies. Dès l'arrivée, la peur s'installe. Mené comme une enquête, le roman raconte les retrouvailles difficiles d'un homme avec son histoire.",
    whyRead: [
      "Une enquête prenante sur un crime politique ancien.",
      "Le retour au pays d'un exilé, sans illusions.",
    ],
    year: 2002,
    publisher: "Seuil",
    pages: 251,
    isbn: "9782020326575",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "ma-grand-mere-bantoue-et-mes-ancetres-les-gaulois",
    title: "Ma grand-mère bantoue et mes ancêtres les Gaulois",
    subtitle: "Simples discours",
    contributors: [LOPES],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "tradition", "colonisation"],
    summary:
      "Que reste-t-il de la négritude pour un écrivain africain d'aujourd'hui ? Faut-il écrire en cultivant l'héritage oral de sa grand-mère, ou en s'ouvrant à la mondialisation ? Que signifie le métissage ? Dans ces courts discours, Henri Lopes répond en romancier plutôt qu'en philosophe ou en homme politique, et parle de la place des littératures africaines dans le monde.",
    whyRead: [
      "Un écrivain réfléchit au métissage et à la francophonie.",
      "Un essai bref, clair et personnel.",
    ],
    year: 2003,
    publisher: "Gallimard",
    pages: 112,
    isbn: "9782070715879",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "une-enfant-de-poto-poto",
    title: "Une enfant de Poto-Poto",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "independances", "ville"],
    summary:
      "Le soir du 15 août 1960, Pélagie et Kimia fêtent l'indépendance dans les rues de Brazzaville. Les deux amies, élèves au lycée, grandissent dans le quartier animé de Poto-Poto et tombent sous le charme du même homme, leur professeur de lettres, un métis né comme elles dans le quartier. Leurs vies vont se séparer, de l'Europe aux États-Unis, sans que leur amitié faite de rivalité et de solidarité ne se défasse.",
    whyRead: [
      "Une belle amitié de femmes au fil des décennies.",
      "Brazzaville au temps de l'indépendance, pleine de vie.",
      "Prix littéraire de la Porte Dorée 2012.",
    ],
    year: 2012,
    publisher: "Gallimard",
    pages: 264,
    isbn: "9782070136087",
    format: "grand-format",
    awards: [{ name: "Prix littéraire de la Porte Dorée", year: 2012 }],
  }),
  livre({
    slug: "le-meridional",
    title: "Le Méridional",
    contributors: [LOPES],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "politique", "histoire"],
    summary:
      "Sur l'île de Noirmoutier vit un homme discret qu'on appelle le Méridional. Le narrateur cherche à le rencontrer, mais l'homme se dérobe, et la poursuite le mène jusqu'à la maison d'arrêt de La Roche-sur-Yon. Peu à peu, derrière cette intrigue vendéenne, surgit le Congo des années 1960 et ses rêves idéologiques. Un roman sur le métissage et sur la difficulté d'effacer son passé.",
    whyRead: [
      "Une intrigue mystérieuse entre Vendée et Congo.",
      "Le neuvième roman d'Henri Lopes, sur ses thèmes de toujours.",
    ],
    year: 2015,
    publisher: "Gallimard",
    pages: 210,
    isbn: "9782070148271",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "il-est-deja-demain",
    title: "Il est déjà demain",
    contributors: [LOPES],
    genre: "recit",
    audience: "adulte",
    themes: ["identite", "histoire", "politique", "exil"],
    summary:
      "À trente ans, Henri Lopes doit prouver qu'il est bien congolais : le gouvernement exige de ses cadres qu'ils justifient leur filiation. La blessure ne l'a jamais quitté. Dans ces mémoires, il remonte l'histoire de ses parents, tous deux métis, raconte son enfance entre les deux rives du Congo, ses études en France, son engagement politique et sa vie de diplomate. Le récit d'une vie placée sous le signe de l'errance et du métissage.",
    whyRead: [
      "Les mémoires d'un écrivain devenu Premier ministre puis ambassadeur.",
      "Un témoignage rare sur l'histoire du Congo indépendant.",
    ],
    year: 2018,
    publisher: "JC Lattès",
    pages: 506,
    isbn: "9782709660624",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),

  // ------------------------------------------------------------------ In Koli Jean Bofane
  livre({
    slug: "pourquoi-le-lion-n-est-plus-le-roi-des-animaux",
    title: "Pourquoi le lion n'est plus le roi des animaux",
    contributors: [BOFANE, illustrateur("Lev")],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["contes", "politique", "humour"],
    summary:
      "Le lion règne en maître tout-puissant sur les animaux. Mais une petite mangouste n'entend pas obéir sans discuter : elle a décidé de se reposer un peu, et même de désobéir. Son audace va changer l'ordre des choses. Le premier livre d'In Koli Jean Bofane est un album malicieux sur le pouvoir et la désobéissance.",
    whyRead: [
      "Une fable drôle sur le pouvoir, à lire dès le plus jeune âge.",
      "Le tout premier livre de l'auteur de « Congo Inc. ».",
    ],
    year: 1996,
    publisher: "Gallimard Jeunesse",
    pages: null,
    isbn: "9782070596713",
    format: "album",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "mathematiques-congolaises",
    title: "Mathématiques congolaises",
    contributors: [BOFANE],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "ville", "humour"],
    summary:
      "À Kinshasa, Célio Matemona, orphelin débrouillard, ne quitte jamais un vieux manuel de mathématiques hérité de son père. Il applique ses formules à tout, et sa logique implacable finit par attirer l'attention d'un service de propagande du pouvoir. Le voilà lancé dans une ascension rapide, au milieu des manipulations, des barbouzes et des coups tordus. Une fable comique et grinçante sur la politique congolaise.",
    whyRead: [
      "Une satire hilarante et cruelle du pouvoir à Kinshasa.",
      "Un héros attachant qui met le monde en équations.",
      "Grand prix littéraire d'Afrique noire 2009.",
    ],
    year: 2008,
    publisher: "Actes Sud (Babel)",
    pages: 317,
    isbn: "9782742796830",
    format: "poche",
    awards: [
      { name: "Prix Jean-Muno", year: 2008 },
      { name: "Grand prix littéraire d'Afrique noire", year: 2009 },
      { name: "Prix littéraire de la SCAM", year: 2009 },
    ],
  }),
  livre({
    slug: "la-belle-de-casa",
    title: "La Belle de Casa",
    contributors: [BOFANE],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "ville"],
    summary:
      "Dans une ruelle d'un quartier populaire de Casablanca, on retrouve le corps d'Ichrak, une jeune femme d'une beauté qui attirait autant les convoitises que les rancœurs. Les suspects ne manquent pas. Sese, migrant clandestin arrivé de Kinshasa, était devenu son ami et son associé dans un commerce douteux. Sous le vent du désert, Bofane dénonce la spéculation immobilière, le sort des migrants et le désir masculin.",
    whyRead: [
      "Un polar plein d'humour au cœur de Casablanca.",
      "Le regard d'un Congolais sur les migrants au Maroc.",
    ],
    year: 2018,
    publisher: "Actes Sud (Babel)",
    pages: 205,
    isbn: "9782330139131",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "nation-cannibale",
    title: "Nation cannibale",
    contributors: [BOFANE],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "esclavage", "humour", "spiritualite"],
    summary:
      "Fuyant un scandale, Faust Losikiya, romancier congolais à court d'inspiration, part pour Haïti. Il veut comprendre comment des captifs déportés d'Afrique ont pu, au XIXe siècle, fonder une république indépendante. À Port-au-Prince, il retrouve des amis écrivains et artistes, croise un prêtre vaudou, une climatologue inquiète et la Mort elle-même, qui se fait appeler Miss Congo. Un roman féroce où dieux et humains sont de mauvaise foi.",
    whyRead: [
      "Un pont entre le Congo et Haïti, plein d'humour acide.",
      "Un personnage inattendu : la Mort en personne.",
    ],
    year: 2025,
    publisher: "Denoël",
    pages: 348,
    isbn: "9782207180242",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Fiston Mwanza Mujila
  livre({
    slug: "la-danse-du-vilain",
    title: "La Danse du Vilain",
    contributors: [MUJILA],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "guerre", "enfance"],
    summary:
      "À Lubumbashi, à l'époque où le Zaïre est au bord de l'explosion, le jeune Sanza quitte sa famille et rejoint les enfants des rues. Autour de lui gravitent un mystérieux Monsieur Guillaume et sa police secrète, des chercheurs de diamants partis dans l'Angola en guerre, et même un écrivain autrichien qui se promène avec une valise pleine de phrases. La nuit, tout le monde se retrouve dans une boîte où l'on danse la danse du Vilain.",
    whyRead: [
      "Le deuxième roman de l'auteur de « Tram 83 », aussi survolté.",
      "Une langue musicale, entre rumba et poésie.",
    ],
    year: 2020,
    publisher: "Métailié",
    pages: 263,
    isbn: "9791022610612",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Wilfried N'Sondé
  livre({
    slug: "le-coeur-des-enfants-leopards",
    title: "Le Cœur des enfants léopards",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "amour", "ville", "exil"],
    summary:
      "Un jeune homme reprend ses esprits dans une cellule de garde à vue, en banlieue parisienne. Mireille, son grand amour, l'a quitté, il a beaucoup bu, et il ne sait plus très bien ce qui s'est passé. Pendant que le policier l'interroge, une autre voix monte en lui, celle des ancêtres venue d'Afrique. Le premier roman de Wilfried N'Sondé, poétique et rythmé, parle d'amour, de violence et d'appartenance.",
    whyRead: [
      "Un premier roman intense, à la langue musicale.",
      "La banlieue, l'amour et l'Afrique des ancêtres.",
      "Prix des Cinq Continents de la Francophonie 2007.",
    ],
    year: 2007,
    publisher: "Actes Sud (Babel)",
    pages: 130,
    isbn: "9782742790050",
    format: "poche",
    awards: [{ name: "Prix des Cinq Continents de la Francophonie", year: 2007 }],
  }),
  livre({
    slug: "le-silence-des-esprits",
    title: "Le Silence des esprits",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "amour", "guerre"],
    summary:
      "Dans un train de banlieue, Clovis Nzila, sans papiers et sans abri, saute dans un wagon pour échapper à un contrôle. Il s'assoit face à Christelle, aide-soignante qui rentre fatiguée de son travail. Un regard suffit : elle lui propose de l'héberger pour la nuit. Dans le petit appartement, ils se racontent, de la guerre civile qu'il a fuie à la solitude qu'elle traverse, et tentent de s'offrir une seconde chance.",
    whyRead: [
      "Une rencontre tendre entre deux solitudes.",
      "Un roman court et sensible sur l'exil.",
    ],
    year: 2010,
    publisher: "Actes Sud (Babel)",
    pages: 170,
    isbn: "9782330097004",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "fleur-de-beton",
    title: "Fleur de béton",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "famille", "femmes"],
    summary:
      "Rosa Maria vit avec sa famille dans une grande cité de banlieue et rêve de soleil, d'amour et de calme. Elle pleure son frère aîné, retrouvé mort derrière le parking du supermarché, évite les coups de son père et soupire en secret pour Jason, qui ne la remarque pas. Un incident avec la police met le feu au quartier et précipite le destin de chacun. Un roman d'apprentissage vif, plein de dialogues et d'énergie.",
    whyRead: [
      "Une héroïne adolescente qui refuse la fatalité.",
      "La cité racontée de l'intérieur, sans clichés.",
    ],
    year: 2012,
    publisher: "Actes Sud",
    pages: 211,
    isbn: "9782330005894",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "orage-sur-le-tanganyika",
    title: "Orage sur le Tanganyika",
    contributors: [NSONDE],
    genre: "jeunesse",
    audience: "ado",
    themes: ["famille", "guerre"],
    summary:
      "Sur les hauteurs du lac Tanganyika, un orage se prépare. Joséphine va bientôt accoucher, et son mari Minerve est très inquiet : la dernière fois, l'enfant n'a pas survécu et Joséphine a été gravement blessée. Il est prêt à tout pour que cela ne recommence pas. Mais ils vivent loin de tout, sont pauvres, et des milices rôdent sur les routes. Un court roman écrit pour les lecteurs qui apprennent le français.",
    whyRead: [
      "Un récit court et fort, au cœur de l'Afrique des Grands Lacs.",
      "Écrit pour les lecteurs de français langue étrangère (niveau B1).",
    ],
    year: 2014,
    publisher: "Didier",
    pages: 75,
    isbn: "9782278078806",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "berlinoise",
    title: "Berlinoise",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "histoire", "politique"],
    summary:
      "Le 30 décembre 1989, Stan et Pascal arrivent à Berlin, où l'on est en train d'abattre le Mur. Ils y rencontrent Maya, jeune peintre aux yeux vairons, fille d'un exilé cubain et d'une Allemande de l'Est, et décident de rester. Dans la ville où tout semble possible, ils montent un groupe de rock, et Stan vit avec Maya une passion fiévreuse. Mais la montée de la menace néonazie vient assombrir l'utopie.",
    whyRead: [
      "Berlin en 1990, entre euphorie et désillusion.",
      "Une histoire d'amour sensuelle et mélancolique.",
    ],
    year: 2015,
    publisher: "Actes Sud (Babel)",
    pages: 171,
    isbn: "9782330117139",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "aigre-doux",
    title: "Aigre-doux",
    contributors: [NSONDE],
    genre: "jeunesse",
    audience: "ado",
    themes: ["identite", "ecole"],
    summary:
      "« D'où tu viens ? » La question revient sans cesse, comme pour ramener à une origine. Le narrateur, adolescent français à part entière, en a assez d'être jugé sur sa couleur de peau ou son apparence. Il réclame simplement le droit d'être un ado, ici et maintenant. Ce texte court dit la colère, puis la confiance qu'il faut trouver en soi pour passer de l'aigreur à la douceur.",
    whyRead: [
      "Un texte coup de poing contre les préjugés.",
      "Court et direct, idéal pour en parler en classe.",
    ],
    year: 2019,
    publisher: "Actes Sud Junior",
    pages: 55,
    isbn: "9782330124311",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "femme-du-ciel-et-des-tempetes",
    title: "Femme du ciel et des tempêtes",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "identite", "tradition"],
    summary:
      "Dans la péninsule de Yamal, en Sibérie, un chaman nenets découvre sous le permafrost la sépulture d'une reine à la peau noire, vieille de plus de dix mille ans. Il veut s'en servir pour protéger sa terre menacée par l'exploitation du gaz. Il appelle à l'aide un ami zoologue français, rejoint par une médecin légiste et un anthropologue d'origine congolaise. Sur place, un mafieux russe les attend.",
    whyRead: [
      "Un roman d'aventures de la Sibérie à l'Afrique.",
      "Un plaidoyer pour la nature et le lien entre les peuples.",
    ],
    year: 2021,
    publisher: "Actes Sud (Babel)",
    pages: 266,
    isbn: "9782330181895",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "heliosphera-fille-des-abysses",
    title: "Héliosphéra, fille des abysses",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "spiritualite"],
    summary:
      "Héliosphéra et Xanthelle, deux êtres microscopiques, se cherchent dans les profondeurs du Pacifique. Un morceau de plastique dérive sur tous les océans. Ollanta, jeune chercheuse, embarque pour une expédition au large du Chili. Ce roman tendre et étonnant est né du séjour de Wilfried N'Sondé à bord de la goélette scientifique Tara.",
    whyRead: [
      "Un roman poétique sur la vie cachée des océans.",
      "Une histoire d'amour… entre êtres microscopiques.",
    ],
    year: 2022,
    publisher: "Actes Sud",
    pages: 136,
    isbn: "9782330170639",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-reine-aux-yeux-de-lune",
    title: "La Reine aux yeux de lune",
    subtitle: "Kimpa Vita, la jumelle née de la guerre",
    contributors: [NSONDE],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "femmes", "spiritualite", "colonisation"],
    summary:
      "Royaume du Kongo, 1685. Dans un pays ravagé par les guerres et la présence portugaise, une fillette aux yeux de lune naît dans les eaux d'une rivière ; sa sœur jumelle ne survit pas. On l'appelle Kimpa Vita. En grandissant, elle traverse de dures épreuves et ses paroles de résistance commencent à rassembler les foules. Sainte pour les uns, sorcière pour les autres, elle incarne l'espoir d'un peuple déchiré.",
    whyRead: [
      "La vie romancée d'une héroïne réelle de l'histoire africaine.",
      "Le royaume du Kongo, à l'époque de la traite.",
    ],
    year: 2023,
    publisher: "Pocket",
    pages: 217,
    isbn: "9782266342681",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Nimrod (Tchad)
  livre({
    slug: "les-jambes-d-alice",
    title: "Les Jambes d'Alice",
    contributors: [NIMROD],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "amour", "ecole"],
    summary:
      "La guerre civile gronde à N'Djamena et les habitants fuient vers les campagnes. Dans la foule, un jeune professeur de français qui cherche à rejoindre sa femme et sa fille croise Alice, l'une de ses élèves, dont la démarche le hante depuis longtemps. Ensemble, ils vivent quelques jours hors du temps. Un premier roman sensuel et lucide sur le désir et ses limites.",
    whyRead: [
      "Le premier roman de Nimrod, à l'écriture très maîtrisée.",
      "Le Tchad en guerre, vu par un homme troublé.",
    ],
    year: 2001,
    publisher: "Actes Sud (Babel)",
    pages: 139,
    isbn: "9782742772582",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "tombeau-de-leopold-sedar-senghor",
    title: "Tombeau de Léopold Sédar Senghor",
    contributors: [NIMROD],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "spiritualite"],
    summary:
      "Un « tombeau », en littérature, est un texte écrit en hommage à un poète disparu. Peu après la mort de Senghor en 2001, Nimrod salue le poète sénégalais qui l'a profondément marqué. Le livre se poursuit par un essai qui présente Senghor en « chantre de l'Afrique heureuse ». Un hommage de poète à poète.",
    whyRead: [
      "Un poète tchadien rend hommage à son grand aîné.",
      "Une porte d'entrée sensible dans l'œuvre de Senghor.",
    ],
    year: 2003,
    publisher: "Le Temps qu'il fait",
    pages: 75,
    isbn: "9782868533753",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "le-depart",
    title: "Le Départ",
    contributors: [NIMROD],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "famille", "exil"],
    summary:
      "Un petit garçon suit son père à travers le Tchad, vers ce qu'il appelle « la borne bleue de l'infini ». Ce voyage en famille, raconté avec les yeux de l'enfant, prend des allures de prélude à l'exil. Nimrod y mêle souvenirs, paysages et rêverie dans une prose de poète.",
    whyRead: [
      "Un récit d'enfance court et lumineux.",
      "Les paysages du Tchad par un grand styliste.",
    ],
    year: 2005,
    publisher: "Actes Sud",
    pages: 101,
    isbn: "9782742753154",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "leopold-sedar-senghor-poetes-d-aujourd-hui",
    title: "Léopold Sédar Senghor",
    contributors: [coauteur("Armand Guibert"), NIMROD],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "histoire"],
    summary:
      "Pour le centenaire de la naissance de Senghor, les éditions Seghers ont remis à jour la monographie de la collection « Poètes d'aujourd'hui ». L'étude d'Armand Guibert, parue en 1969, est complétée par un essai de Nimrod. Ensemble, ils retracent la vie et l'œuvre du poète, de son enfance près de Dakar à l'Académie française, en passant par la négritude et la présidence du Sénégal,.",
    whyRead: [
      "Une présentation complète de Senghor, poète et homme d'État.",
      "Deux regards de deux générations sur le même poète.",
    ],
    year: 2006,
    publisher: "Seghers",
    pages: 364,
    isbn: "9782232122750",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-nouvelle-chose-francaise",
    title: "La Nouvelle Chose française",
    contributors: [NIMROD],
    genre: "essai",
    audience: "adulte",
    themes: ["exil", "identite", "colonisation"],
    summary:
      "Comment être écrivain quand on vient d'un pays sans éditeurs, sans critiques et presque sans lecteurs pour vos livres ? C'est la situation de l'écrivain africain de langue française, que Nimrod analyse à partir de son propre exil. Dans ces essais, il revient sur Senghor, sur l'invention de la francophonie et sur la langue française, plus vaste que l'Hexagone.",
    whyRead: [
      "Une réflexion profonde sur l'écrivain africain en exil.",
      "Un regard original sur la francophonie.",
    ],
    year: 2008,
    publisher: "Actes Sud",
    pages: 125,
    isbn: "9782742771868",
    format: "grand-format",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "rosa-parks-non-a-la-discrimination-raciale",
    title: "Rosa Parks, non à la discrimination raciale",
    contributors: [NIMROD],
    genre: "jeunesse",
    audience: "ado",
    themes: ["politique", "histoire", "femmes"],
    summary:
      "En 1955, à Montgomery, en Alabama, Rosa Parks refuse de céder sa place à un passager blanc dans un autobus. Ce geste simple fait d'elle le symbole de la lutte contre la ségrégation raciale aux États-Unis. Nimrod raconte aux jeunes lecteurs la vie de cette femme courageuse et le combat pour les droits civiques qu'elle a contribué à lancer.",
    whyRead: [
      "Une biographie claire pour comprendre la lutte pour les droits civiques.",
      "Une collection qui raconte ceux qui ont dit non.",
    ],
    year: 2008,
    publisher: "Actes Sud Junior",
    pages: 93,
    isbn: "9782330032432",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-or-des-rivieres",
    title: "L'Or des rivières",
    contributors: [NIMROD],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "enfance", "exil"],
    summary:
      "Comme chaque année, Nimrod revient au Tchad voir sa mère. À l'aube, il parcourt les ruelles ocre de son ancien quartier et comprend que c'est elle qui, pour lui, invente le pays. Dans une suite de tableaux, il ranime les bonheurs passés, les rares moments partagés avec un père souvent absent et les origines de son goût de la contemplation.",
    whyRead: [
      "Un hommage délicat à une mère et à un pays.",
      "Des récits brefs, d'une grande poésie.",
    ],
    year: 2010,
    publisher: "Actes Sud",
    pages: 125,
    isbn: "9782742789580",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "aime-cesaire-non-a-l-humiliation",
    title: "Aimé Césaire, non à l'humiliation",
    contributors: [NIMROD],
    genre: "jeunesse",
    audience: "ado",
    themes: ["colonisation", "identite", "politique"],
    summary:
      "Nimrod raconte aux jeunes lecteurs la vie d'Aimé Césaire, le poète martiniquais. Père de la négritude avec Senghor et Damas, combattant de l'anticolonialisme, maire de Fort-de-France pendant plus de cinquante ans, Césaire a lutté toute sa vie pour la dignité et l'égalité. Une biographie claire pour comprendre son œuvre et ses combats.",
    whyRead: [
      "Une biographie accessible d'un géant de la poésie.",
      "Pour comprendre la négritude et l'anticolonialisme.",
    ],
    year: 2012,
    publisher: "Actes Sud Junior",
    pages: 95,
    isbn: "9782330009137",
    format: "poche",
    awards: [],
    outOfPrint: true,
  }),
  livre({
    slug: "un-balcon-sur-l-algerois",
    title: "Un balcon sur l'Algérois",
    contributors: [NIMROD],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "exil", "ecole"],
    summary:
      "Dans le Paris des années 1970, entre la Sorbonne, Montparnasse et Saint-Germain, un étudiant tchadien devient l'amant de sa directrice de mémoire. Elle est une universitaire réputée, libre, issue de la grande bourgeoisie et habituée à choisir ses hommes. Ébloui, le jeune homme se laisse emporter, avant de devoir trouver la force de se libérer. Un roman d'amour subtil, plein d'humour et d'autodérision.",
    whyRead: [
      "Une passion inégale dans le Paris intellectuel des années 1970.",
      "Une langue ciselée, ironique et sensuelle.",
    ],
    year: 2013,
    publisher: "Actes Sud",
    pages: 173,
    isbn: "9782330018122",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "leon-gontran-damas-le-poete-jazzy",
    title: "Léon-Gontran Damas, le poète jazzy",
    contributors: [NIMROD],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["identite", "colonisation", "histoire"],
    summary:
      "Léon-Gontran Damas, poète de Guyane, est avec Senghor et Césaire l'un des trois fondateurs de la négritude. Dans ce petit livre destiné aux jeunes lecteurs, Nimrod raconte sa vie et fait entendre une poésie nourrie du rythme du jazz. Une première découverte d'un poète souvent moins connu que ses deux compagnons.",
    whyRead: [
      "Pour découvrir le troisième fondateur de la négritude.",
      "Un petit format pensé pour les jeunes lecteurs.",
    ],
    year: 2014,
    publisher: "À dos d'âne",
    pages: 45,
    isbn: "9782919372331",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "sur-les-berges-du-chari-district-nord-de-la-beaute",
    title: "Sur les berges du Chari, district nord de la beauté",
    contributors: [NIMROD],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "identite", "histoire"],
    summary:
      "Pour la première fois, Nimrod inscrit dans le titre d'un livre un nom qui le relie au Tchad : le Chari, fleuve qui se jette dans le lac Tchad. Ses poèmes en disent les paysages, les ciels, les oiseaux et les pêcheurs. Mais le poète exilé n'oublie ni la mémoire de l'esclavage ni la répression qui pèse sur son pays.",
    whyRead: [
      "Le Tchad du poète, entre beauté et blessures.",
      "Un recueil publié par Bruno Doucey, éditeur des poésies du monde.",
    ],
    year: 2016,
    publisher: "Bruno Doucey",
    pages: 118,
    isbn: "9782362291036",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "j-aurais-un-royaume-en-bois-flotte",
    title: "J'aurais un royaume en bois flotté",
    subtitle: "Anthologie personnelle, 1989-2016",
    contributors: [NIMROD],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "identite", "spiritualite"],
    summary:
      "Nimrod a choisi lui-même les poèmes de cette anthologie, qui couvre près de trente ans d'écriture, de son premier recueil en 1989 à 2016. On y suit le fil d'une œuvre marquée par le Tchad natal, l'exil, l'amour et la contemplation de la nature. Le livre est préfacé par l'éditeur et poète Bruno Doucey.",
    whyRead: [
      "Le meilleur moyen de découvrir la poésie de Nimrod.",
      "Une anthologie en poche, dans la collection Poésie/Gallimard.",
    ],
    year: 2017,
    publisher: "Gallimard (Poésie)",
    pages: 247,
    isbn: "9782072717178",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-enfant-n-est-pas-mort",
    title: "L'enfant n'est pas mort",
    contributors: [NIMROD],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "femmes", "histoire"],
    summary:
      "En 1960, dans un ghetto d'Afrique du Sud, la police tue un bébé noir. Ingrid Jonker, jeune poète, fille d'un dignitaire de l'apartheid, écrit alors un poème bouleversant. Plus de trente ans plus tard, Nelson Mandela le lit devant le premier Parlement démocratique du pays. Nimrod fait alterner la grande figure de Mandela et la fragile silhouette d'Ingrid, en lutte avec un père qui la renie.",
    whyRead: [
      "L'histoire vraie d'un poème devenu symbole.",
      "Un portrait sensible d'une poète sud-africaine méconnue.",
    ],
    year: 2017,
    publisher: "Bruno Doucey",
    pages: 146,
    isbn: "9782362291425",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "gens-de-brume",
    title: "Gens de brume",
    contributors: [NIMROD],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "identite"],
    summary:
      "Dans ce court texte, entre prose et poème, Nimrod revient au temps fragile de l'enfance africaine. Les souvenirs passent par les parfums et les odeurs : le sucre, la peau, le fleuve, la boue. Ses « gens de brume » marchent à la lisière de l'aube, comme ils traversent son œuvre depuis trente ans.",
    whyRead: [
      "Une prose poétique sur les odeurs de l'enfance.",
      "Un texte bref, à lire comme on respire.",
    ],
    year: 2017,
    publisher: "Actes Sud",
    pages: 56,
    isbn: "9782330082284",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "petit-eloge-de-la-lumiere-nature",
    title: "Petit éloge de la lumière nature",
    contributors: [NIMROD],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "identite"],
    summary:
      "Ce recueil est un hymne aux quatre éléments : la terre, le ciel, l'eau et le feu. Nimrod y décrit les saisons comme les briques de nos vies, qui nous colorent à la manière d'un peintre. La terre y devient une déesse lyrique qui remplit de lumière le cœur du poète.",
    whyRead: [
      "Une poésie lumineuse, tournée vers la nature.",
      "Un recueil apaisé, loin des fracas du monde.",
    ],
    year: 2020,
    publisher: "Obsidiane",
    pages: 95,
    isbn: "9782916447971",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "la-traversee-de-montparnasse",
    title: "La Traversée de Montparnasse",
    contributors: [NIMROD],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "amour"],
    summary:
      "Le narrateur, dandy ivoirien orphelin adopté par un puissant personnage de son pays, vit à Paris parmi une bande d'amis français trentenaires, raffinés, venus du monde de l'édition. Tout semble harmonieux, léger, sensuel. Pourtant, une remarque de l'un d'eux laisse deviner que l'amitié a ses limites et qu'une menace plane, en plein Quartier latin.",
    whyRead: [
      "Un roman élégant sur l'amitié et les préjugés cachés.",
      "Le Paris littéraire vu par un dandy africain.",
    ],
    year: 2020,
    publisher: "Gallimard",
    pages: 110,
    isbn: "9782072861475",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "le-temps-liquide",
    title: "Le Temps liquide",
    contributors: [NIMROD],
    genre: "recit",
    audience: "adulte",
    themes: ["identite", "exil", "famille"],
    summary:
      "Ces récits nous mènent de Venise aux horizons du Sahel, en passant par un train pour Clermont-Ferrand où se joue une rencontre bouleversante autour d'un fils disparu. La veine autobiographique y est forte, jusqu'au dernier texte où apparaît le nom même de Nimrod. Avec humour et gravité, l'auteur assemble une mosaïque où se mêlent la beauté, la laideur et le hasard des destins.",
    whyRead: [
      "Des récits courts, entre autobiographie et rêverie.",
      "Une prose de poète, pleine d'humour et d'émotion.",
    ],
    year: 2021,
    publisher: "Gallimard",
    pages: 115,
    isbn: "9782072920561",
    format: "grand-format",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "la-legende-de-l-errance", "bleu-blanc-rouge", "quand-le-coq-annoncera-l-aube-d-un-autre-jour", "et-dieu-seul-sait-comment-je-dors",
  "les-petits-fils-negres-de-vercingetorix", "african-psycho", "tant-que-les-arbres-s-enracineront-dans-la-terre", "lettre-a-jimmy",
  "black-bazar", "demain-j-aurai-vingt-ans", "ma-soeur-etoile", "ecrivain-et-oiseau-migrateur", "tais-toi-et-meurs",
  "le-sanglot-de-l-homme-noir", "lumieres-de-pointe-noire", "petit-piment", "lettres-noires", "le-monde-est-mon-langage", "congo",
  "les-cigognes-sont-immortelles", "le-coq-solitaire", "huit-lecons-sur-l-afrique", "rumeurs-d-amerique", "le-commerce-des-allonges",
  "cette-femme-qui-nous-regarde", "ramses-de-paris", "l-etat-honteux", "la-parenthese-de-sang", "l-ante-peuple",
  "les-sept-solitudes-de-lorsa-lopez", "les-yeux-du-volcan", "qui-a-mange-madame-d-avoine-bergotha", "le-commencement-des-douleurs",
  "encre-sueur-salive-et-sang", "poemes-sony-labou-tansi", "un-fusil-dans-la-main-un-poeme-dans-la-poche", "jazz-et-vin-de-palme",
  "le-feu-des-origines", "les-petits-garcons-naissent-aussi-des-etoiles", "photo-de-groupe-au-bord-du-fleuve", "la-sonate-a-bridgetower",
  "tribaliques", "la-nouvelle-romance", "sans-tam-tam", "le-chercheur-d-afriques", "sur-l-autre-rive", "le-lys-et-le-flamboyant",
  "dossier-classe", "ma-grand-mere-bantoue-et-mes-ancetres-les-gaulois", "une-enfant-de-poto-poto", "le-meridional", "il-est-deja-demain",
  "pourquoi-le-lion-n-est-plus-le-roi-des-animaux", "mathematiques-congolaises", "la-belle-de-casa", "nation-cannibale",
  "la-danse-du-vilain", "le-coeur-des-enfants-leopards", "le-silence-des-esprits", "fleur-de-beton", "orage-sur-le-tanganyika",
  "berlinoise", "aigre-doux", "femme-du-ciel-et-des-tempetes", "heliosphera-fille-des-abysses", "la-reine-aux-yeux-de-lune",
  "les-jambes-d-alice", "tombeau-de-leopold-sedar-senghor", "le-depart", "leopold-sedar-senghor-poetes-d-aujourd-hui",
  "la-nouvelle-chose-francaise", "rosa-parks-non-a-la-discrimination-raciale", "l-or-des-rivieres", "aime-cesaire-non-a-l-humiliation",
  "un-balcon-sur-l-algerois", "leon-gontran-damas-le-poete-jazzy", "sur-les-berges-du-chari-district-nord-de-la-beaute",
  "j-aurais-un-royaume-en-bois-flotte", "l-enfant-n-est-pas-mort", "gens-de-brume", "petit-eloge-de-la-lumiere-nature",
  "la-traversee-de-montparnasse", "le-temps-liquide",
];
