/**
 * Lot 06 : fiches ajoutées en octobre 2026 (voir docs/REDACTION.md).
 * Chaque lot est écrit séparément ; src/lib/demo/index.ts les rassemble.
 * Afrique de l'Est et océan Indien : Mukasonga, Faye, Waberi, Devi, Appanah, Rabearivelo, Raharimanana, Zamir,
 * Umubyeyi Mairesse. ISBN et pages relevés dans le catalogue de la BnF.
 */
import type { Author, Book } from "../../types";

type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured" | "quote"> &
  Partial<Pick<Book, "subtitle" | "originalLanguage" | "kind">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-10-02",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });
const mukasonga = auteur("Scholastique Mukasonga", "scholastique-mukasonga");
const faye = auteur("Gaël Faye", "gael-faye");
const waberi = auteur("Abdourahman A. Waberi", "abdourahman-a-waberi");
const devi = auteur("Ananda Devi", "ananda-devi");
const appanah = auteur("Nathacha Appanah", "nathacha-appanah");
const rabearivelo = auteur("Jean-Joseph Rabearivelo", "jean-joseph-rabearivelo");
const raharimanana = auteur("Raharimanana", "raharimanana");
const zamir = auteur("Ali Zamir", "ali-zamir");
const beata = auteur("Beata Umubyeyi Mairesse", "beata-umubyeyi-mairesse");
const mabanckou = auteur("Alain Mabanckou", "alain-mabanckou");

/** Livres et BD de ce lot. */
export const livres: Book[] = [
  // ------------------------------------------------------------------ Scholastique Mukasonga
  livre({
    slug: "inyenzi-ou-les-cafards",
    title: "Inyenzi ou les Cafards",
    contributors: [mukasonga],
    genre: "recit",
    audience: "adulte",
    themes: ["genocide", "famille", "enfance", "histoire"],
    summary:
      "En 1960, la famille de Scholastique Mukasonga, tutsi, est déportée avec des milliers d'autres à Nyamata, dans la brousse du Bugesera. L'autrice raconte son enfance dans ce village de relégation : les humiliations, les soldats, la peur, mais aussi les jours heureux, la bière de banane et l'énergie farouche de sa mère. Elle dit ensuite l'école où l'on traite les Tutsi d'« inyenzi », de cafards, puis l'exil qui la sauve. Écrit dix ans après le génocide de 1994, où presque tous les siens ont été tués, ce premier livre se veut un tombeau de papier pour ceux qui n'en ont pas eu.",
    whyRead: [
      "Le premier livre de l'autrice, un témoignage essentiel sur le Rwanda d'avant 1994.",
      "Un récit pudique qui garde la mémoire des noms et des visages.",
      "Pour comprendre comment la haine s'est installée pendant trente ans.",
    ],
    year: 2006,
    publisher: "Folio",
    pages: 190,
    isbn: "9782070457380",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-femme-aux-pieds-nus",
    title: "La Femme aux pieds nus",
    contributors: [mukasonga],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition", "genocide"],
    summary:
      "Scholastique Mukasonga rend hommage à sa mère, Stefania, qui marchait pieds nus et n'avait qu'une obsession : sauver ses enfants. À Nyamata, où la famille a été déportée, elle prépare des cachettes, guette les bruits de la nuit et transmet à ses filles tout ce qu'une femme rwandaise doit savoir. Le livre fait revivre les gestes du quotidien, la culture du sorgho, les recettes, les mariages et les remèdes. C'est à la fois le portrait d'une mère courageuse et un tableau de la vie des femmes rwandaises d'autrefois.",
    whyRead: [
      "Un portrait de mère bouleversant de tendresse.",
      "Une plongée dans les gestes et les savoirs des femmes rwandaises.",
      "Un livre lumineux malgré l'ombre du génocide.",
    ],
    year: 2008,
    publisher: "Folio",
    pages: 170,
    isbn: "9782070446667",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-iguifou",
    title: "L'Iguifou",
    subtitle: "Nouvelles rwandaises",
    contributors: [mukasonga],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["enfance", "famille", "tradition", "genocide"],
    summary:
      "Cinq nouvelles nourries des souvenirs d'enfance de l'autrice à Nyamata, où les Tutsi ont été relégués. Dans la première, la petite Colomba lutte contre l'iguifou, la faim qui lui ronge le ventre, et cherche partout de quoi l'apaiser. D'autres textes parlent du deuil, de la peur ou de la beauté des vaches que l'on vénère. Avec ce recueil, Scholastique Mukasonga passe du témoignage à la fiction, sans quitter les collines de son enfance.",
    whyRead: [
      "Le passage de l'autrice du récit de vie à la fiction.",
      "Des nouvelles courtes et fortes, où la faim est un personnage.",
      "Une enfance rwandaise racontée avec une grande délicatesse.",
    ],
    year: 2010,
    publisher: "Folio",
    pages: 154,
    isbn: "9782070466986",
    format: "poche",
    awards: [{ name: "Prix Renaissance de la nouvelle", year: 2011 }],
  }),
  livre({
    slug: "ce-que-murmurent-les-collines",
    title: "Ce que murmurent les collines",
    subtitle: "Nouvelles rwandaises",
    contributors: [mukasonga],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["tradition", "colonisation", "contes", "histoire"],
    summary:
      "Six nouvelles qui puisent dans les contes anciens et la vie quotidienne du Rwanda. L'une raconte la rivière Rukarara, près de laquelle l'autrice est née et que des explorateurs européens ont prise pour une source du Nil. D'autres évoquent l'arrivée des missionnaires, l'école, les croyances et les histoires que se transmettent les femmes. C'est le premier livre de Scholastique Mukasonga qui ne parle pas directement du génocide, même si son ombre reste présente.",
    whyRead: [
      "Le Rwanda des contes et des traditions, avant la tragédie.",
      "Des nouvelles où les mères transmettent la mémoire.",
      "Un regard malicieux sur la rencontre avec les colons et les missionnaires.",
    ],
    year: 2014,
    publisher: "Folio",
    pages: 173,
    isbn: "9782070463084",
    format: "poche",
    awards: [{ name: "Prix de la nouvelle de la Société des gens de lettres", year: 2015 }],
  }),
  livre({
    slug: "coeur-tambour",
    title: "Cœur tambour",
    contributors: [mukasonga],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "identite", "exil", "femmes"],
    summary:
      "Kitami, chanteuse célèbre que l'on surnomme « l'Amazone noire », est morte dans des circonstances mystérieuses, écrasée sous un tambour sacré. Le roman remonte le fil de sa vie : la formation de son groupe avec un rasta jamaïcain et un Guadeloupéen, puis l'enfance de Prisca, jeune Rwandaise brillante, habitée par l'esprit de Nyabinghi, reine légendaire dont le nom a traversé les océans jusqu'aux rastas. Un journaliste tente enfin d'élucider sa mort. Du Rwanda à la Jamaïque et à New York, un roman sur la musique, les esprits et les racines africaines.",
    whyRead: [
      "Un voyage du Rwanda aux Caraïbes, au rythme des tambours.",
      "Une diva inoubliable et une énigme à résoudre.",
      "Mukasonga élargit son univers à toute la diaspora africaine.",
    ],
    year: 2016,
    publisher: "Folio",
    pages: 194,
    isbn: "9782072762536",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "un-si-beau-diplome",
    title: "Un si beau diplôme !",
    contributors: [mukasonga],
    genre: "recit",
    audience: "adulte",
    themes: ["ecole", "exil", "femmes", "identite"],
    summary:
      "Pour sauver sa fille d'une mort annoncée, le père de Scholastique Mukasonga n'a qu'une idée : qu'elle obtienne un « beau diplôme », qui ferait d'elle une « évoluée », ni hutu ni tutsi. C'est pourtant pour décrocher ce diplôme d'assistante sociale qu'elle doit partir en exil, au Burundi, puis à Djibouti et en France. De pays en pays, le précieux papier tantôt ouvre des portes, tantôt ne vaut plus rien. L'autrice raconte ce parcours avec humour, en faisant du diplôme le talisman qui l'a aidée à tenir.",
    whyRead: [
      "Un récit d'exil plein d'humour et de fantaisie.",
      "La foi d'un père dans l'école, plus forte que tout.",
      "Du Burundi à Djibouti et à la France, un parcours de femme obstinée.",
    ],
    year: 2018,
    publisher: "Folio",
    pages: 205,
    isbn: "9782072881763",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "kibogo-est-monte-au-ciel",
    title: "Kibogo est monté au ciel",
    contributors: [mukasonga],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "colonisation", "contes", "humour"],
    summary:
      "Dans le Rwanda des années 1930, la sécheresse et la famine frappent les collines. Les missionnaires prêchent Yézu, qui est monté au ciel ; les anciens racontent Kibogo, le fils du roi qui y est monté lui aussi pour faire revenir la pluie. Lequel des deux a sauvé le peuple ? Entre les pères blancs qui baptisent à la chaîne et les mères qui racontent les vieilles histoires à la veillée, Scholastique Mukasonga montre comment les Rwandais ont résisté en mêlant les croyances. Un roman satirique, drôle et merveilleux.",
    whyRead: [
      "Une satire savoureuse de l'évangélisation coloniale.",
      "Des histoires miraculeuses où se mêlent mythes et prières.",
      "Un roman court, drôle et plein de malice.",
    ],
    year: 2020,
    publisher: "Folio",
    pages: 171,
    isbn: "9782072964176",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "sister-deborah",
    title: "Sister Deborah",
    contributors: [mukasonga],
    genre: "roman",
    audience: "adulte",
    themes: ["spiritualite", "femmes", "colonisation", "histoire"],
    summary:
      "Dans les années 1930, une Afro-Américaine arrive au Rwanda avec des missionnaires. Sister Deborah guérit les malades et annonce la venue d'un Messie noir et féminin, ce qui inquiète bientôt les autorités coloniales. Des décennies plus tard, Ikirezi, qu'elle a guérie quand elle était enfant et qui est devenue universitaire aux États-Unis, part sur ses traces jusqu'à Nairobi. Un roman sur les prophétesses, les femmes guérisseuses et les rêves de libération.",
    whyRead: [
      "Une figure de prophétesse fascinante, entre l'Amérique et l'Afrique.",
      "Une enquête qui traverse le siècle, du Rwanda au Kenya.",
      "Un roman qui imagine un royaume des femmes.",
    ],
    year: 2022,
    publisher: "Folio",
    pages: 156,
    isbn: "9782073045782",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "julienne",
    title: "Julienne",
    contributors: [mukasonga],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "famille", "amour", "femmes"],
    summary:
      "Julienne grandit dans le Rwanda des années 1970, protégée par sa grande sœur Lidia. Tutsi, elle est une exilée dans son propre pays, et quand Lidia part au Burundi, elle n'a plus qu'un rêve : la rejoindre à Bujumbura. Le prix à payer pour obtenir le droit de partir est terrible. Son chemin la mène ensuite jusqu'à Bruxelles, portée par un amour fou. Scholastique Mukasonga s'inspire de la vie de sa propre sœur pour raconter un destin d'exil.",
    whyRead: [
      "Un hommage poignant de l'autrice à sa petite sœur.",
      "Une histoire d'amour et d'exil, du Rwanda à Bruxelles.",
      "Le destin d'une femme qui ne renonce jamais à espérer.",
    ],
    year: 2024,
    publisher: "Folio",
    pages: 240,
    isbn: "9782073133359",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Gaël Faye
  livre({
    slug: "l-ennui-des-apres-midi-sans-fin",
    title: "L'Ennui des après-midi sans fin",
    contributors: [faye, { role: "dessinateur", name: "Hippolyte", authorSlug: null }],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["enfance", "famille"],
    summary:
      "Gaël Faye transforme en album illustré un texte slamé de son premier disque, Pili Pili sur un croissant au beurre. Il y raconte les longs après-midi de son enfance à Bujumbura, quand l'ennui pousse à inventer des jeux. Le jardin familial, où son père gardait des serpents dans des cages, devient un monde à explorer et une source d'imagination sans fin. Les grandes illustrations d'Hippolyte accompagnent le texte, que l'on peut aussi écouter en musique.",
    whyRead: [
      "Un éloge de l'ennui, qui fait naître l'imagination.",
      "L'enfance burundaise de l'auteur de Petit pays, pour les plus jeunes.",
      "Un album à lire et à écouter, porté par la voix de Gaël Faye.",
    ],
    year: 2020,
    publisher: "Les Arènes",
    pages: null,
    isbn: "9791037514998",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "petit-pays-bd",
    kind: "bd",
    title: "Petit pays",
    contributors: [
      faye,
      { role: "scenariste", name: "Marzena Sowa", authorSlug: null },
      { role: "dessinateur", name: "Sylvain Savoia", authorSlug: null },
    ],
    genre: "bd",
    audience: "ado",
    themes: ["enfance", "guerre", "genocide", "famille"],
    summary:
      "Adaptation en bande dessinée du roman de Gaël Faye. Au début des années 1990, Gabriel, une dizaine d'années, vit à Bujumbura entre son père français, sa mère rwandaise et sa petite sœur Ana. Avec sa bande de copains de l'impasse, il passe ses journées à chaparder des mangues et à faire les quatre cents coups. Mais la séparation de ses parents, la guerre civile au Burundi puis le génocide au Rwanda viennent briser ce paradis d'enfance. Marzena Sowa et Sylvain Savoia mettent en images ce récit devenu un classique.",
    whyRead: [
      "Le roman culte de Gaël Faye, mis en images avec sensibilité.",
      "Une bonne porte d'entrée pour les adolescents.",
      "Par les auteurs de la série Marzi, eux aussi conteurs d'enfance.",
    ],
    year: 2024,
    publisher: "Dupuis",
    pages: 126,
    isbn: "9791034737369",
    format: "album",
    awards: [],
  }),

  // ------------------------------------------------------------------ Abdourahman A. Waberi
  livre({
    slug: "le-pays-sans-ombre",
    title: "Le Pays sans ombre",
    contributors: [waberi],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["colonisation", "independances", "ville", "humour"],
    summary:
      "Le premier livre de Waberi rassemble de courtes nouvelles qui font le portrait de Djibouti, son pays natal. On y croise des fous et des poètes, des colons, des nomades aux prises avec un climat impitoyable, des mâcheurs de khat, des réfugiés affamés et les habitants de Balbala, le bidonville qui s'étend au sud de la capitale. Les récits passent du passé précolonial à la colonisation puis aux années d'après l'indépendance. Ironique et tendre, le recueil ouvre une trilogie consacrée à Djibouti.",
    whyRead: [
      "La première entrée en littérature d'un pays rarement raconté.",
      "Un kaléidoscope de personnages, entre ironie et tendresse.",
      "Le premier volet de la trilogie djiboutienne de Waberi.",
    ],
    year: 1994,
    publisher: "Le Serpent à plumes",
    pages: 174,
    isbn: "2842612353",
    format: "poche",
    awards: [
      { name: "Grand prix de la nouvelle francophone (Fondation Henri Cornélus)", year: 1994 },
      { name: "Prix Albert-Bernard de l'Académie des sciences d'outre-mer", year: 1994 },
    ],
  }),
  livre({
    slug: "cahier-nomade",
    title: "Cahier nomade",
    contributors: [waberi],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["exil", "identite", "histoire", "ville"],
    summary:
      "Treize nouvelles, réparties en deux parties, où Waberi, installé en France depuis dix ans, part à la recherche de son pays absent. Il se souvient du Djibouti de son enfance, de l'époque où sept cinémas faisaient rêver la ville et où son père chantait pour chasser la nuit. Les fantômes du passé côtoient les images d'un présent figé. Ce deuxième volet de sa trilogie djiboutienne est un carnet de mémoire, écrit dans une langue poétique.",
    whyRead: [
      "Le Djibouti d'hier, entre souvenirs d'enfance et fantômes.",
      "Grand prix littéraire d'Afrique noire 1996.",
      "Une écriture de l'exil, nomade comme son titre.",
    ],
    year: 1996,
    publisher: "Le Serpent à plumes",
    pages: 153,
    isbn: "2842611276",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1996 }],
  }),
  livre({
    slug: "balbala",
    title: "Balbala",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "ville", "femmes", "colonisation"],
    summary:
      "Balbala est le bidonville qui s'étend aux portes de Djibouti. Quatre amis y vivent : Waïs, champion de course à pied, Yonis, médecin, leur ami Dilleyta et Anab, la sœur de Waïs. Sous un régime autoritaire et corrompu, ils sont déclarés ennemis de l'ordre public et deviennent la cible du pouvoir. Chacune des quatre parties du roman donne la parole à l'un d'eux. Ce premier roman clôt la trilogie de Waberi sur Djibouti et interroge l'histoire coloniale comme la dictature d'après l'indépendance.",
    whyRead: [
      "Quatre amis face à la dictature, dans un bidonville de Djibouti.",
      "Le premier roman de Waberi, à la prose riche et poétique.",
      "Un regard sans complaisance sur l'après-indépendance.",
    ],
    year: 1997,
    publisher: "Folio",
    pages: 187,
    isbn: "207042121X",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "moisson-de-cranes",
    title: "Moisson de crânes",
    subtitle: "Textes pour le Rwanda",
    contributors: [waberi],
    genre: "recit",
    audience: "adulte",
    themes: ["genocide", "histoire", "politique"],
    summary:
      "En 1998, Waberi fait partie des écrivains africains invités au Rwanda pour écrire après le génocide des Tutsi de 1994. De ce séjour sont nés ces textes brefs, entre récit, méditation et poème. Il y décrit les mémoriaux, les ossuaires, les survivants qu'il rencontre, et s'interroge sur ce qu'un écrivain peut dire face à l'horreur. Un livre court, grave, qui refuse l'oubli.",
    whyRead: [
      "Un écrivain africain face aux traces du génocide.",
      "Des textes brefs, entre récit et poème.",
      "Une réflexion sur le devoir de mémoire et les mots qui manquent.",
    ],
    year: 2000,
    publisher: "Mille et une nuits",
    pages: 97,
    isbn: "9782755508659",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "les-nomades-mes-freres-vont-boire-a-la-grande-ourse",
    title: "Les Nomades, mes frères, vont boire à la Grande Ourse",
    contributors: [waberi],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "identite", "colonisation"],
    summary:
      "Le premier recueil de poèmes de Waberi, écrit entre 1991 et 1998. Il y chante la vie nomade de ses ancêtres, les déserts de Djibouti et la dureté de son climat. Les poèmes évoquent aussi les blessures de la colonisation et de l'après-indépendance, l'exil, la langue arabe et les écrivains qu'il admire. Un appel à la tolérance, en vers ciselés.",
    whyRead: [
      "La voix poétique d'un grand romancier djiboutien.",
      "Le désert et les nomades, chantés en images fortes.",
      "Des poèmes courts, faciles à lire à voix haute.",
    ],
    year: 2000,
    publisher: "Mémoire d'encrier",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "rift-routes-rails",
    title: "Rift, routes, rails",
    subtitle: "Variations romanesques",
    contributors: [waberi],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["exil", "histoire", "identite"],
    summary:
      "Treize variations romanesques sur l'Afrique, son passé et son présent. Waberi y fait passer des personnages historiques, des hommes et des femmes portés par les mots, qui empruntent les routes et les rails. Le livre voyage de la vallée du Rift aux poissons du Nil, des grandes figures du jazz à la tour Eiffel. Des textes tour à tour rêveurs et violents, sur un continent qui se cherche.",
    whyRead: [
      "Treize textes courts pour découvrir la palette de Waberi.",
      "Un voyage entre l'Afrique, le jazz et Paris.",
      "Une écriture libre, entre nouvelle et poème.",
    ],
    year: 2001,
    publisher: "Gallimard",
    pages: 85,
    isbn: "2070760235",
    format: null,
    awards: [],
  }),
  livre({
    slug: "transit",
    title: "Transit",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "guerre", "politique", "identite"],
    summary:
      "À l'aéroport de Roissy, deux Djiboutiens attendent qu'on statue sur leur sort. Bachir, enfant-soldat démobilisé et blessé, a été pris par un agent de l'ambassade pour le fils de Harbi, ancien opposant arrêté par la police, qui n'a pas démenti. Leurs voix, et celles de leurs proches, racontent la guerre civile, les trafics d'armes, la faim et la difficile conquête de la dignité après la colonisation. Un roman choral sur l'exil, qui n'épargne pas non plus le rôle de la France.",
    whyRead: [
      "Deux exilés, un faux père et un faux fils, réunis par le hasard.",
      "Un roman à plusieurs voix, vif et souvent drôle.",
      "La guerre civile djiboutienne vue de l'intérieur.",
    ],
    year: 2003,
    publisher: "Gallimard",
    pages: 154,
    isbn: "2070768740",
    format: null,
    awards: [],
  }),
  livre({
    slug: "passage-des-larmes",
    title: "Passage des larmes",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "spiritualite", "politique", "famille"],
    summary:
      "Djibril, né à Djibouti juste avant l'indépendance et installé au Canada, revient dans son pays pour le compte d'une société de renseignement économique. Le port est devenu un enjeu stratégique depuis le 11 septembre 2001, et le retour réveille en lui les souvenirs et la rupture avec son frère jumeau, Djamal, devenu islamiste. Le récit alterne ses notes avec le journal que Djamal tient en prison, sous lequel affleure la pensée de Walter Benjamin. Le titre évoque le détroit de Bab el-Mandeb, la « porte des larmes ».",
    whyRead: [
      "Deux frères jumeaux que tout oppose, entre exil et fanatisme.",
      "La Corne de l'Afrique au cœur des enjeux mondiaux.",
      "Un roman habité par la pensée de Walter Benjamin.",
    ],
    year: 2009,
    publisher: "JC Lattès",
    pages: 249,
    isbn: "9782709631075",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-divine-chanson",
    title: "La Divine Chanson",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "esclavage", "politique"],
    summary:
      "Waberi imagine la vie de Sammy, chanteur, poète et musicien afro-américain né à Chicago en 1949, librement inspiré de Gil Scott-Heron. C'est un chat nommé Paris qui raconte son histoire : l'enfance dans le Tennessee auprès de sa grand-mère, les combats pour les droits civiques, la gloire sur les scènes de New York, Paris ou Berlin, mais aussi la drogue et la prison. À travers lui, c'est toute l'expérience afro-américaine qui se déploie, sous le regard du dieu Papa Legba.",
    whyRead: [
      "Une biographie rêvée de Gil Scott-Heron, pionnier du rap.",
      "Un narrateur inattendu : un chat parisien.",
      "Prix Louis-Guilloux 2015.",
    ],
    year: 2015,
    publisher: "Zulma",
    pages: 237,
    isbn: "9782843047329",
    format: null,
    awards: [{ name: "Prix Louis-Guilloux", year: 2015 }],
  }),
  livre({
    slug: "mon-nom-est-aube",
    title: "Mon nom est aube",
    contributors: [waberi],
    genre: "poesie",
    audience: "adulte",
    themes: ["spiritualite", "famille", "identite"],
    summary:
      "Dans ce recueil, Waberi se tourne vers l'islam de son enfance, ses textes sacrés, ses grands poètes et les paysages où ils ont marché. Les poèmes disent aussi les êtres chers : la mère, l'épouse, l'enfant à naître. Le poète y cherche un apaisement, une manière de rassembler en lui toutes ses histoires. Une poésie de méditation, qui plaide pour la tolérance et l'ouverture.",
    whyRead: [
      "Une poésie spirituelle, à rebours des fanatismes.",
      "Des poèmes intimes, adressés aux siens.",
      "Traduit en anglais sous le titre Naming the Dawn.",
    ],
    year: 2016,
    publisher: "Vents d'ailleurs",
    pages: 105,
    isbn: "9782364130708",
    format: null,
    awards: [],
  }),
  livre({
    slug: "pourquoi-tu-danses-quand-tu-marches",
    title: "Pourquoi tu danses quand tu marches ?",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "ecole", "exil"],
    summary:
      "Un matin, à Paris, sur le chemin de l'école, une petite fille demande à son père pourquoi il « danse » quand il marche. Pour lui répondre, il doit raconter sa jambe malade et revenir à Djibouti, dans le quartier du Château d'eau. Il y était le « gringalet », mais aussi le meilleur élève de l'école, un lecteur insatiable. Entre la grand-mère surnommée Cochise, la mère silencieuse et l'institutrice venue de France, Waberi signe un roman d'enfance très personnel.",
    whyRead: [
      "Un père qui raconte son enfance à sa fille.",
      "Djibouti, la poussière et la lumière, vus à hauteur d'enfant.",
      "Un roman tendre sur le handicap et le goût des livres.",
    ],
    year: 2019,
    publisher: "Folio",
    pages: 218,
    isbn: "9782072894695",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "dictionnaire-enjoue-des-cultures-africaines",
    title: "Dictionnaire enjoué des cultures africaines",
    contributors: [mabanckou, waberi],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "histoire", "humour"],
    summary:
      "Alain Mabanckou et Abdourahman Waberi composent ensemble un dictionnaire libre et joyeux des cultures africaines. D'une entrée à l'autre, ils évoquent des écrivains, des musiciens, des villes, des mots, des plats, des mythes et des figures politiques du continent et de sa diaspora. Les définitions sont tour à tour savantes, drôles ou personnelles. Un livre à picorer pour découvrir l'Afrique loin des clichés.",
    whyRead: [
      "Deux grands écrivains réunis pour un abécédaire vivant.",
      "Un livre à ouvrir au hasard, plein de découvertes.",
      "Une Afrique plurielle, loin des idées reçues.",
    ],
    year: 2019,
    publisher: "Pluriel",
    pages: 335,
    isbn: "9782818506318",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "dis-moi-pour-qui-j-existe",
    title: "Dis-moi pour qui j'existe ?",
    contributors: [waberi],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "enfance", "exil"],
    summary:
      "Aden est un professeur heureux et un père comblé, jusqu'au jour où sa fille tombe gravement malade. L'épreuve réveille en lui ses propres souvenirs d'enfant malade à Djibouti : le garçon solitaire qu'il était, la douceur de sa grand-mère, le réconfort des livres. Chaque jour, il écrit et téléphone à sa fille, lui raconte les paysages de sa jeunesse et ses ancêtres faiseurs de pluie. Un dialogue lumineux entre un père et sa fille.",
    whyRead: [
      "Un échange bouleversant entre un père et sa fille.",
      "La mémoire et la poésie comme remèdes.",
      "Le prolongement de Pourquoi tu danses quand tu marches ?",
    ],
    year: 2022,
    publisher: "JC Lattès",
    pages: 266,
    isbn: "9782709669443",
    format: null,
    awards: [],
  }),
  livre({
    slug: "quand-on-n-a-que-la-terre",
    title: "Quand on n'a que la terre",
    contributors: [waberi],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "exil", "spiritualite"],
    summary:
      "Ce volume de poche réunit un recueil inédit et des poèmes déjà parus de Waberi. Le texte qui donne son titre au livre est une ode à la terre et à tous les êtres vivants, et un cri d'alarme sur une planète en danger. On y retrouve aussi ses thèmes de toujours : le désert, les nomades, l'exil et la foi. Une bonne porte d'entrée dans son œuvre poétique, avec une langue musicale et pleine de jeux de mots.",
    whyRead: [
      "Toute la poésie de Waberi réunie en un volume de poche.",
      "Une ode à la terre et une alerte écologique.",
      "Une langue musicale, qui se lit à voix haute.",
    ],
    year: 2022,
    publisher: "Points",
    pages: 253,
    isbn: "9782757893425",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "notre-france-noire",
    title: "Notre France noire",
    subtitle: "De A à Z",
    contributors: [mabanckou, { role: "auteur", name: "Pascal Blanchard", authorSlug: null }, waberi],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "identite", "colonisation"],
    summary:
      "Après leur dictionnaire des cultures africaines, Alain Mabanckou et Abdourahman Waberi s'associent à l'historien Pascal Blanchard. Ensemble, ils racontent en un abécédaire la présence noire dans l'histoire et la culture françaises. Les entrées vont de Joséphine Baker à Yannick Noah, d'Arthur Rimbaud à la publicité Banania, des humoristes aux combats contre le racisme. Un livre à la fois facétieux et sérieux, historique et politique.",
    whyRead: [
      "L'histoire noire de la France, racontée en abécédaire.",
      "Deux écrivains et un historien réunis.",
      "Un livre à picorer, riche en découvertes.",
    ],
    year: 2023,
    publisher: "Fayard",
    pages: 602,
    isbn: "9782213717043",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Ananda Devi
  livre({
    slug: "rue-la-poudriere",
    title: "Rue la Poudrière",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "ville", "famille"],
    summary:
      "Paule grandit dans un quartier pauvre de Port-Louis, la capitale de l'île Maurice, où vivent les rejetés de la société. Fille dont ses parents n'ont pas voulu, elle se retrouve prise dans le monde de la prostitution, à la fin des années 1970. Elle cherche pourtant de toutes ses forces un moyen d'échapper à ce destin. Premier roman d'Ananda Devi, réédité en 2024, il annonce déjà les grands thèmes de son œuvre : le corps des femmes, la violence et l'envers de l'île.",
    whyRead: [
      "Le premier roman d'Ananda Devi, enfin réédité.",
      "L'envers de l'île Maurice, loin des cartes postales.",
      "Une héroïne qui se bat pour échapper à son destin.",
    ],
    year: 1988,
    publisher: "Project'îles",
    pages: 207,
    isbn: "9782493036254",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-voile-de-draupadi",
    title: "Le Voile de Draupadi",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "famille", "tradition"],
    summary:
      "Anjali, jeune femme hindoue de l'île Maurice, voit son fils tomber gravement malade. Son mari lui demande d'accomplir la marche sur le feu, un rituel par lequel elle espère obtenir des dieux la guérison de l'enfant. Avant l'épreuve, elle revient sur sa vie et sur le souvenir de Vasanti, morte pendant ce même rituel. Guidée par le mythe de Draupadi, Anjali apprend à se libérer des règles de sa famille et de sa communauté.",
    whyRead: [
      "Une mère prête à marcher sur le feu pour son fils.",
      "Les mythes hindous au cœur de la vie mauricienne.",
      "Un roman sur la liberté des femmes face aux traditions.",
    ],
    year: 1993,
    publisher: "L'Harmattan",
    pages: 175,
    isbn: "2738416411",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-arbre-fouet",
    title: "L'Arbre-fouet",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "spiritualite"],
    summary:
      "Le roman s'ouvre sur la tentative de suicide d'Aeena. La mort n'a pas voulu d'elle, et elle voit dans ce sursaut de vie un signe qui l'oblige à comprendre les causes de son malheur. Elle remonte alors le fil de sa vie, des violences subies et d'une faute ancienne qui la hante. Dans une atmosphère proche du rêve, Ananda Devi explore la souffrance, la culpabilité et le silence imposé aux femmes.",
    whyRead: [
      "Un roman intense, entre rêve et confession.",
      "Une héroïne qui cherche la vérité sur elle-même.",
      "Une étape clé dans l'œuvre d'Ananda Devi.",
    ],
    year: 1997,
    publisher: "L'Harmattan",
    pages: 172,
    isbn: "2738450571",
    format: null,
    awards: [],
  }),
  livre({
    slug: "moi-l-interdite",
    title: "Moi, l'interdite",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "identite"],
    summary:
      "Mouna est née avec un bec-de-lièvre, et sa famille voit en elle un monstre. Rejetée, cachée, privée d'affection, elle trouve refuge auprès d'un chien, le seul être qui l'accepte telle qu'elle est. Sa quête de tendresse l'entraîne dans une lente descente, qu'elle raconte elle-même. Un court roman bouleversant sur l'exclusion et le regard des autres.",
    whyRead: [
      "Une voix d'enfant rejetée, inoubliable.",
      "Un texte court et poétique sur la différence.",
      "Prix Radio France du livre de l'océan Indien 2001.",
    ],
    year: 2000,
    publisher: "Dapper",
    pages: 125,
    isbn: "2906067601",
    format: "poche",
    awards: [{ name: "Prix Radio France du livre de l'océan Indien", year: 2001 }],
  }),
  livre({
    slug: "pagli",
    title: "Pagli",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "tradition"],
    summary:
      "Dans un village de l'île Maurice, Daya a été mariée sans amour et se refuse à son époux. Elle aime Zil, un pêcheur créole, et ce choix fait d'elle une « pagli », une folle, aux yeux de sa communauté hindoue. Rejetée par les siens, elle raconte sa révolte et son désir. Ananda Devi fait de cette femme insoumise le symbole de toutes celles que l'on réduit au silence.",
    whyRead: [
      "Une héroïne insoumise, qui choisit l'amour contre la loi du groupe.",
      "Une langue poétique et brûlante.",
      "L'un des romans les plus forts d'Ananda Devi.",
    ],
    year: 2001,
    publisher: "Gallimard",
    pages: 157,
    isbn: "2070760219",
    format: null,
    awards: [],
  }),
  livre({
    slug: "soupir",
    title: "Soupir",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "travail", "spiritualite"],
    summary:
      "À Rodrigues, petite île aride de l'archipel mauricien, un groupe d'hommes et de femmes abîmés par la vie part s'installer sur un plateau désolé appelé Soupir. Ils espèrent y échapper à la misère, en cultivant la ganja. Prostitution, handicap, abandon : chacun porte ses blessures, et les esprits des morts hantent les vivants. Un roman poétique et tendre sur les déshérités d'une île oubliée.",
    whyRead: [
      "Rodrigues, l'île la plus méconnue de l'archipel mauricien.",
      "Des personnages en marge, racontés avec tendresse.",
      "Une atmosphère de rêve où les morts parlent aux vivants.",
    ],
    year: 2002,
    publisher: "Gallimard",
    pages: 225,
    isbn: "207076401X",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-long-desir",
    title: "Le Long Désir",
    contributors: [devi],
    genre: "poesie",
    audience: "adulte",
    themes: ["amour", "identite", "histoire"],
    summary:
      "Recueil de poèmes où Ananda Devi mêle l'histoire de l'île Maurice et celle d'un corps. Le désir y est sensuel, obsédant et parfois cruel, comme le passé de l'île, marqué par l'esclavage et l'engagisme. Les vers alternent l'intime et le collectif, la mer et la chair. Une porte d'entrée dans la poésie d'une romancière qui écrit toujours en poète.",
    whyRead: [
      "La poésie charnelle d'Ananda Devi.",
      "L'île Maurice et son histoire, vues à travers le désir.",
      "Des poèmes courts et intenses.",
    ],
    year: 2003,
    publisher: "Gallimard",
    pages: 128,
    isbn: "2070768732",
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-vie-de-josephin-le-fou",
    title: "La Vie de Joséphin le fou",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "famille", "identite"],
    summary:
      "Joséphin vit au bord de la mer, à l'île Maurice, et tout le monde le prend pour un fou. Enfant maltraité et rejeté, il a trouvé refuge dans la mer, qui est devenue sa seule famille. Il raconte lui-même sa vie, dans une langue mêlée de créole, chaotique et poétique. Un court roman sur la solitude, la cruauté des hommes et la consolation des éléments.",
    whyRead: [
      "Un monologue saisissant, dans une langue inventive.",
      "La mer comme refuge contre la violence des hommes.",
      "Un roman bref et inoubliable.",
    ],
    year: 2003,
    publisher: "Gallimard",
    pages: 87,
    isbn: "2070703347",
    format: null,
    awards: [],
  }),
  livre({
    slug: "indian-tango",
    title: "Indian Tango",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "politique", "ville"],
    summary:
      "New Delhi, 2004, pendant les élections qui pourraient porter Sonia Gandhi au pouvoir. Subhadra, femme mûre et respectable, mère et grand-mère, voit sa vie bouleversée par la rencontre d'une romancière venue d'ailleurs. Le désir qu'elle croyait éteint renaît, contre toutes les conventions. Ananda Devi entremêle l'histoire de cette passion et celle d'une Inde en pleine transformation.",
    whyRead: [
      "Un désir de femme mûre, raconté sans tabou.",
      "L'Inde contemporaine, entre tradition et changement.",
      "Sélectionné pour le prix Femina 2007.",
    ],
    year: 2007,
    publisher: "Folio",
    pages: 253,
    isbn: "9782070361724",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-sari-vert",
    title: "Le Sari vert",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition"],
    summary:
      "À l'île Maurice, un vieux médecin respecté, surnommé Dokter-Sa, est en train de mourir. Sa fille et sa petite-fille veillent sur lui, et cette agonie fait remonter les souvenirs d'une vie de tyrannie domestique. Face au mourant, qui ne regrette rien, les femmes osent enfin parler. Un roman puissant sur la violence conjugale et le silence des familles.",
    whyRead: [
      "Un huis clos tendu autour d'un tyran domestique.",
      "Trois générations de femmes qui reprennent la parole.",
      "Prix Louis-Guilloux 2010.",
    ],
    year: 2009,
    publisher: "Folio",
    pages: 255,
    isbn: "9782070440344",
    format: "poche",
    awards: [{ name: "Prix Louis-Guilloux", year: 2010 }],
  }),
  livre({
    slug: "les-hommes-qui-me-parlent",
    title: "Les Hommes qui me parlent",
    contributors: [devi],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "famille", "identite"],
    summary:
      "Dans ce récit autobiographique, Ananda Devi s'interroge sur les hommes qui ont compté dans sa vie, dans sa famille comme parmi ses amis écrivains. Elle raconte comment ils ont considéré sa place dans la famille, son travail et sa vocation d'écrivain. Elle revient sur son enfance, ses débuts en écriture, l'amour, la maternité et la solitude. Une méditation sincère sur la liberté d'une femme qui écrit.",
    whyRead: [
      "Ananda Devi se livre comme rarement.",
      "Une réflexion sur l'écriture et la liberté des femmes.",
      "Pour mieux comprendre son œuvre de romancière.",
    ],
    year: 2011,
    publisher: "Gallimard",
    pages: 215,
    isbn: "9782070134403",
    format: null,
    awards: [],
  }),
  livre({
    slug: "quand-la-nuit-consent-a-me-parler",
    title: "Quand la nuit consent à me parler",
    contributors: [devi],
    genre: "poesie",
    audience: "adulte",
    themes: ["femmes", "identite"],
    summary:
      "Court recueil de poèmes publié par Bruno Doucey. Ananda Devi y parle du silence, de la souffrance et de la transformation, dans des vers brefs et tranchants. La nuit y devient le moment où la parole se libère enfin. Le recueil a été traduit en anglais, preuve de son écho bien au-delà de l'île Maurice.",
    whyRead: [
      "Des poèmes brefs, d'une grande intensité.",
      "Une bonne entrée dans la poésie d'Ananda Devi.",
      "Un petit livre à garder près de soi.",
    ],
    year: 2011,
    publisher: "Bruno Doucey",
    pages: 58,
    isbn: "9782362290183",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-jours-vivants",
    title: "Les Jours vivants",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "amour", "colonisation", "identite"],
    summary:
      "Mary Grimes, vieille Anglaise solitaire, vit dans un appartement de Portobello Road, à Londres. Sa vie semble s'être arrêtée à quinze ans, quand elle a aimé un jeune soldat parti à la guerre. Le hasard lui fait rencontrer Cub, un jeune Jamaïcain de Brixton, et entre eux naît une relation trouble et magnétique. Ananda Devi confronte la vieillesse et la jeunesse, la misère et le désir, dans un Londres marqué par l'héritage colonial.",
    whyRead: [
      "Un roman troublant, qui dérange autant qu'il fascine.",
      "Londres vu par ses marges, de Portobello à Brixton.",
      "Traduit en anglais sous le titre The Living Days.",
    ],
    year: 2013,
    publisher: "Gallimard",
    pages: 182,
    isbn: "9782070140411",
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-ambassadeur-triste",
    title: "L'Ambassadeur triste",
    contributors: [devi],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["humour", "identite", "politique"],
    summary:
      "Recueil de nouvelles où Ananda Devi montre une facette inattendue : un humour satirique et mordant. Ses personnages vivent entre plusieurs mondes et plusieurs langues, du français à l'anglais, du hindi au créole mauricien. Une écriture plus vive et plus ample que dans ses romans, qui ouvre ses récits au monde entier.",
    whyRead: [
      "Ananda Devi en satiriste, une belle surprise.",
      "Des nouvelles courtes, qui voyagent entre les langues.",
      "Une bonne porte d'entrée dans son œuvre.",
    ],
    year: 2015,
    publisher: "Gallimard",
    pages: 192,
    isbn: "9782070147960",
    format: null,
    awards: [],
  }),
  livre({
    slug: "ceux-du-large",
    title: "Ceux du large",
    contributors: [devi],
    genre: "poesie",
    audience: "adulte",
    themes: ["exil", "guerre", "identite"],
    summary:
      "Un long poème dédié aux réfugiés et aux naufragés de la Méditerranée, tous ceux qui fuient leur terre pour tenter d'atteindre une autre rive. Ananda Devi l'a écrit en trois langues : le français, l'anglais et le créole mauricien. Elle dit l'avoir fait pour ne pas rester passive face à la catastrophe qui se déroule sous nos yeux. Un chant de fraternité, bref et poignant.",
    whyRead: [
      "Un poème fraternel pour les exilés d'aujourd'hui.",
      "Une édition trilingue, en français, anglais et créole.",
      "Un texte court, à lire et à partager.",
    ],
    year: 2017,
    publisher: "Bruno Doucey",
    pages: 82,
    isbn: "9782362291487",
    format: null,
    awards: [],
  }),
  livre({
    slug: "manger-l-autre",
    title: "Manger l'autre",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "identite"],
    summary:
      "La narratrice est née obèse. Sa mère est partie, son père cuisine sans fin pour elle, persuadé qu'elle a dévoré sa jumelle dans le ventre maternel. Au lycée, ses camarades la photographient et livrent son corps aux moqueries d'Internet. Entre conte et récit d'horreur, Ananda Devi interroge la dictature de la minceur et la solitude dans nos sociétés de consommation.",
    whyRead: [
      "Un roman audacieux sur le corps et le regard des autres.",
      "Une narratrice qui passe de l'humour à l'effroi.",
      "Prix Ouest-France Étonnants Voyageurs 2018.",
    ],
    year: 2018,
    publisher: "Zulma",
    pages: 182,
    isbn: "9782843049576",
    format: "poche",
    awards: [{ name: "Prix Ouest-France Étonnants Voyageurs", year: 2018 }],
  }),
  livre({
    slug: "danser-sur-tes-braises",
    title: "Danser sur tes braises",
    subtitle: "suivi de Six décennies",
    contributors: [devi],
    genre: "poesie",
    audience: "adulte",
    themes: ["femmes", "famille", "exil"],
    summary:
      "Deux ensembles de poèmes sur la condition des femmes. Le premier est dédié à la mère de l'autrice et évoque le premier exil de tout être humain, celui du ventre maternel. Dans le second, Ananda Devi s'adresse à son propre corps, sans fard, et dessine la géographie changeante de six décennies de vie. Une exploration de la perte et de la séparation.",
    whyRead: [
      "Un hommage poétique d'une fille à sa mère.",
      "Un regard sans fard sur le corps qui vieillit.",
      "Des poèmes intimes et universels.",
    ],
    year: 2020,
    publisher: "Bruno Doucey",
    pages: 89,
    isbn: "9782362292750",
    format: null,
    awards: [],
  }),
  livre({
    slug: "fardo",
    title: "Fardo",
    contributors: [devi],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["femmes", "histoire", "identite"],
    summary:
      "Le musée des Confluences, à Lyon, invite des écrivains à choisir un objet de ses collections pour en tirer une fiction. Ananda Devi s'est arrêtée devant une momie précolombienne et des restes d'une sépulture du Caucase. Elle tisse le destin de ces deux femmes du passé avec son propre parcours de femme et d'artiste. Un texte bref, entre fiction et méditation sur ce qui reste de nous.",
    whyRead: [
      "Un texte né d'une rencontre avec deux femmes du passé.",
      "Une méditation sur le corps, la mort et la mémoire.",
      "Un petit livre, vite lu, longtemps gardé en tête.",
    ],
    year: 2020,
    publisher: "Cambourakis",
    pages: 64,
    isbn: "9782366245035",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-rire-des-deesses",
    title: "Le Rire des déesses",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "spiritualite", "enfance"],
    summary:
      "Dans une ruelle d'une ville du nord de l'Inde vivent des prostituées et la petite Chinti, dix ans, que sa mère Veena n'arrive pas à aimer. Les femmes du quartier veillent sur elle, à commencer par Sadhana, une hijra devenue guide de sa communauté. Quand Shivnath, un swami adulé, enlève Chinti en pèlerinage vers Bénarès, persuadé qu'elle est une déesse capable de le rendre divin, Veena et Sadhana se lancent à sa poursuite. Un roman sur la sororité des femmes rejetées face aux abus du religieux.",
    whyRead: [
      "Deux femmes en marge unies pour sauver une enfant.",
      "L'Inde des ruelles et des temples, sans fard.",
      "Prix Femina des lycéens 2021.",
    ],
    year: 2021,
    publisher: "Le Livre de Poche",
    pages: 255,
    isbn: "9782253938705",
    format: "poche",
    awards: [{ name: "Prix Femina des lycéens", year: 2021 }],
  }),
  livre({
    slug: "sylvia-p",
    title: "Sylvia P.",
    contributors: [devi],
    genre: "recit",
    audience: "adulte",
    themes: ["femmes", "amour", "identite"],
    summary:
      "Ananda Devi se penche sur la vie de Sylvia Plath, la poétesse américaine qui s'est donné la mort à Londres en 1963. Elle retrace sa relation avec le poète Ted Hughes, ses combats contre la dépression et les contraintes qui pesaient sur les femmes de son époque. Surtout, elle montre comment l'écriture donnait forme et beauté au chaos de sa vie. En miroir, l'autrice interroge sa propre place de femme écrivain.",
    whyRead: [
      "Un portrait sensible de Sylvia Plath.",
      "Une réflexion sur l'écriture comme survie.",
      "Le dialogue entre deux femmes poètes.",
    ],
    year: 2022,
    publisher: "Bruno Doucey",
    pages: 201,
    isbn: "9782362294297",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-jour-des-cameleons",
    title: "Le Jour des caméléons",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "politique", "femmes", "colonisation"],
    summary:
      "C'est l'île Maurice elle-même qui raconte cette journée où tout bascule. Le roman s'ouvre sur un centre commercial en ruines, où Zigzig, chef de bande, tient dans ses bras une fillette ensanglantée. Puis le récit remonte les heures, en suivant un oncle fatigué de vivre, sa nièce, une femme qui vient de quitter son mari et Zigzig lui-même. Pendant ce temps, des caméléons attendent patiemment que les hommes aient fini de tout détruire.",
    whyRead: [
      "Une journée d'explosion racontée comme un compte à rebours.",
      "L'île Maurice comme narratrice, une idée saisissante.",
      "Les inégalités et l'urgence climatique au cœur du roman.",
    ],
    year: 2023,
    publisher: "Le Livre de Poche",
    pages: 253,
    isbn: "9782253907671",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-nuit-s-ajoute-a-la-nuit",
    title: "La nuit s'ajoute à la nuit",
    contributors: [devi],
    genre: "recit",
    audience: "adulte",
    themes: ["histoire", "guerre", "identite"],
    summary:
      "Pour la collection « Ma nuit au musée », Ananda Devi passe une nuit seule dans l'ancienne prison de Montluc, à Lyon, devenue mémorial. Jean Moulin, des résistants, les enfants d'Izieu, puis des condamnés algériens y ont été enfermés. Au fil des heures, l'autrice remonte un siècle d'histoire et interroge le bien, le mal et sa propre présence entre ces murs. Un récit intime et grave, hanté par les fantômes du lieu.",
    whyRead: [
      "Une nuit dans une prison chargée d'histoire.",
      "Une méditation intime sur le bien et le mal.",
      "Un récit court, intense et habité.",
    ],
    year: 2024,
    publisher: "Le Livre de Poche",
    pages: 231,
    isbn: "9782253252078",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "chronique-d-un-royaume-perdu",
    title: "Chronique d'un royaume perdu",
    contributors: [devi],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "histoire", "famille", "contes"],
    summary:
      "À la fin du XIXe siècle, cinq enfants bannis d'une plantation de canne de l'île Maurice fondent un village isolé, le Bouchon. Trois sont nés dans la famille blanche des Dumontais, deux d'une esclave, et tous ont le même père. Un enfant chroniqueur consigne, sur quatre générations, le destin des habitants de ce petit royaume où la frontière entre les vivants et les morts s'efface. Une vaste fresque où se mêlent mythes, légendes et mémoire de l'esclavage.",
    whyRead: [
      "Une saga familiale sur quatre générations, aux accents de réalisme magique.",
      "La mémoire de l'esclavage à Maurice, racontée comme une épopée.",
      "En première sélection du prix Goncourt 2026.",
    ],
    year: 2026,
    publisher: "Grasset",
    pages: 464,
    isbn: "9782246846949",
    format: "grand-format",
    awards: [],
  }),

  // ------------------------------------------------------------------ Nathacha Appanah
  livre({
    slug: "les-rochers-de-poudre-d-or",
    title: "Les Rochers de Poudre d'Or",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "travail", "colonisation", "histoire"],
    summary:
      "À la fin du XIXe siècle, des Indiens quittent leur pays pour l'île Maurice, engagés pour travailler dans les champs de canne à sucre à la place des esclaves affranchis. Le roman suit plusieurs d'entre eux, chacun avec ses raisons de partir, pendant la longue traversée puis à l'arrivée sur l'île. Ils découvrent vite que les promesses ne seront pas tenues. Nathacha Appanah, elle-même descendante d'engagés, signe un premier roman sur cette histoire méconnue.",
    whyRead: [
      "L'histoire méconnue des engagés indiens.",
      "Un premier roman sobre et émouvant.",
      "Prix RFO du livre 2003.",
    ],
    year: 2003,
    publisher: "Folio",
    pages: 231,
    isbn: "2070321118",
    format: "poche",
    awards: [{ name: "Prix RFO du livre", year: 2003 }],
  }),
  livre({
    slug: "blue-bay-palace",
    title: "Blue Bay Palace",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "tradition", "femmes", "travail"],
    summary:
      "Maya, jeune Mauricienne d'origine indienne, travaille dans un hôtel de luxe pour touristes, le Blue Bay Palace. Elle tombe passionnément amoureuse de Dev, le fils du patron, qui n'est pas de sa caste. Leur histoire se heurte aux règles de la société et aux attentes des familles. Un court roman sur une passion absolue, dans une île où les différences de classe et de caste restent fortes.",
    whyRead: [
      "Une passion amoureuse brûlante et impossible.",
      "L'île Maurice derrière le décor des hôtels de luxe.",
      "Un roman bref, d'une grande intensité.",
    ],
    year: 2004,
    publisher: "Folio",
    pages: 126,
    isbn: "9782070462322",
    format: "poche",
    awards: [{ name: "Grand prix littéraire des océans Indien et Pacifique", year: 2004 }],
  }),
  livre({
    slug: "la-noce-d-anna",
    title: "La Noce d'Anna",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "femmes", "amour"],
    summary:
      "Sophie, romancière, vit le jour du mariage de sa fille unique, Anna. Tout au long de cette journée de fête, elle repense à sa propre jeunesse, à la naissance d'Anna, qu'elle a élevée seule, et à ce qu'elle lui a transmis ou non. Mère et fille se ressemblent si peu. Un roman délicat sur la transmission et les liens entre une mère et sa fille.",
    whyRead: [
      "Une seule journée, celle d'un mariage, pour toute une vie.",
      "Un beau portrait de mère, entre fierté et inquiétude.",
      "Un roman intime, plein de finesse.",
    ],
    year: 2005,
    publisher: "Folio",
    pages: 178,
    isbn: "9782070379941",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "le-dernier-frere",
    title: "Le Dernier Frère",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["enfance", "guerre", "exil", "histoire"],
    summary:
      "En 1944, à l'île Maurice, Raj est un garçon de neuf ans maltraité par son père, gardien de la prison de Beau-Bassin. Derrière les barbelés, il découvre des prisonniers venus d'Europe : des Juifs refoulés de Palestine. Il se lie d'amitié avec l'un d'eux, David, un enfant blond de son âge. Soixante ans plus tard, Raj raconte cette amitié née d'un épisode oublié de la Seconde Guerre mondiale.",
    whyRead: [
      "Une amitié d'enfance au cœur d'un épisode oublié de l'Histoire.",
      "Un roman émouvant, traduit dans plus de quinze langues.",
      "Prix du roman Fnac 2007.",
    ],
    year: 2007,
    publisher: "Points",
    pages: 210,
    isbn: "9782757810040",
    format: "poche",
    awards: [{ name: "Prix du roman Fnac", year: 2007 }],
  }),
  livre({
    slug: "en-attendant-demain",
    title: "En attendant demain",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "famille", "exil", "femmes"],
    summary:
      "Adam et Anita se rencontrent à Paris à vingt ans. Lui voulait peindre, elle voulait écrire ; ils deviennent architecte et journaliste et s'installent dans le Sud-Ouest avec leur fille. Un jour, Anita rencontre Adèle, une Mauricienne sans papiers qui a tout perdu, et l'engage pour s'occuper de la maison et de l'enfant. La présence d'Adèle va réveiller les rêves enfouis du couple et bouleverser leur vie.",
    whyRead: [
      "Le portrait d'un couple, de la passion à l'usure.",
      "Une tension psychologique qui monte page après page.",
      "Une réflexion sur la création et ce qu'elle coûte aux autres.",
    ],
    year: 2015,
    publisher: "Folio",
    pages: 215,
    isbn: "9782070792771",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "petit-eloge-des-fantomes",
    title: "Petit éloge des fantômes",
    contributors: [appanah],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "famille", "identite"],
    summary:
      "Dans ce petit livre de la collection Folio à 2 euros, Nathacha Appanah réunit des textes courts autour de la figure du fantôme. Le souvenir d'un être cher, un cyclone, une photographie, un plat ou un paysage peuvent devenir des fantômes. Elle y revient sur son enfance d'île en île et sur tout ce qui continue de nous habiter. Un livre à lire d'une traite, entre mémoire et méditation.",
    whyRead: [
      "Un court recueil, idéal pour découvrir l'autrice.",
      "Des fantômes doux, faits de souvenirs.",
      "Une écriture pudique et lumineuse.",
    ],
    year: 2016,
    publisher: "Folio",
    pages: 98,
    isbn: "9782070465910",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "une-annee-lumiere",
    title: "Une année lumière",
    contributors: [appanah],
    genre: "essai",
    audience: "adulte",
    themes: ["exil", "identite", "histoire"],
    summary:
      "Ce livre rassemble les chroniques que Nathacha Appanah a tenues chaque semaine dans le journal La Croix en 2017. Elle y parle de son enfance à l'île Maurice, de Mayotte, de la langue indienne transmise par sa grand-mère, mais aussi des migrants, de la mondialisation et du regard porté sur la couleur de peau. Elle évoque aussi son métier d'écrivain et de traductrice, et des pages d'histoire oubliées. Une année de lucidité, qui cherche malgré tout la lumière.",
    whyRead: [
      "Des chroniques courtes, à lire au fil des jours.",
      "Un regard lucide et apaisé sur le monde.",
      "Pour mieux connaître l'autrice de Tropique de la violence.",
    ],
    year: 2018,
    publisher: "Gallimard",
    pages: 142,
    isbn: "9782072819896",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-ciel-par-dessus-le-toit",
    title: "Le Ciel par-dessus le toit",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "enfance", "politique"],
    summary:
      "Loup, dix-sept ans, se retrouve en maison d'arrêt après une folle équipée au volant d'une voiture. Sa mère, Phénix, et sa sœur Paloma, dont il était séparé depuis longtemps, tentent d'imaginer ce qu'il vit derrière les murs. Le roman remonte l'histoire de cette famille cabossée, où chacun a cherché à se réinventer. Le titre fait écho au poème de Verlaine écrit en prison.",
    whyRead: [
      "Une famille abîmée qui tente de se retrouver.",
      "Un roman court et poétique, nourri de Verlaine et de Rimbaud.",
      "En première sélection du prix Goncourt 2019.",
    ],
    year: 2019,
    publisher: "Folio",
    pages: 139,
    isbn: "9782072935848",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "rien-ne-t-appartient",
    title: "Rien ne t'appartient",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "guerre", "identite", "enfance"],
    summary:
      "Tara vient de perdre son mari. Ce deuil fait resurgir en elle une autre identité, longtemps enfouie : celle d'une fille qui portait un autre prénom et dont l'enfance a été saccagée, dans un pays d'Asie jamais nommé où les filles ne comptent pour rien. Le roman alterne son présent, fait de dérive et de chagrin, et le passé de celle qu'elle a été. Un récit intense sur la mémoire du corps et la violence faite aux femmes.",
    whyRead: [
      "Une héroïne hantée par la fille qu'elle a été.",
      "Une écriture précise, qui dit la brutalité sans la montrer complaisamment.",
      "Prix des libraires de Nancy - Le Point 2021.",
    ],
    year: 2021,
    publisher: "Folio",
    pages: 172,
    isbn: "9782073003010",
    format: "poche",
    awards: [{ name: "Prix des libraires de Nancy - Le Point", year: 2021 }],
  }),
  livre({
    slug: "la-memoire-delavee",
    title: "La Mémoire délavée",
    contributors: [appanah],
    genre: "recit",
    audience: "adulte",
    themes: ["famille", "exil", "travail", "histoire"],
    summary:
      "En 1872, les ancêtres de Nathacha Appanah quittent leur village d'Inde pour l'île Maurice, où ils viennent travailler dans les champs de canne comme engagés. À leur arrivée à Port-Louis, ils reçoivent un numéro. L'autrice reconstitue, génération après génération, cette histoire familiale qui s'efface, jusqu'à sa propre enfance dans la maison de ses grands-parents. Illustré de photographies, ce récit est le fruit de vingt ans de recherche.",
    whyRead: [
      "L'histoire intime des engagés indiens de Maurice.",
      "Un portrait tendre du grand-père de l'autrice.",
      "Un récit pudique, illustré de photographies de famille.",
    ],
    year: 2023,
    publisher: "Folio",
    pages: 148,
    isbn: "9782073097996",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-nuit-au-coeur",
    title: "La Nuit au cœur",
    contributors: [appanah],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "amour", "famille"],
    summary:
      "Nathacha Appanah entrelace trois histoires de femmes prises dans l'emprise d'un compagnon violent. Il y a celle d'Emma, sa cousine, celle de Chahinez Daoud, tuée par son ex-mari en 2021, et la sienne, car l'autrice a elle-même connu la violence dans sa jeunesse. Elle cherche les mots pour dire la peur, l'emprise et la nuit qui gagne. Un livre nécessaire, salué par trois grands prix en 2025.",
    whyRead: [
      "Un texte courageux sur les violences conjugales.",
      "Trois destins de femmes, dont celui de l'autrice.",
      "Prix Femina et Goncourt des lycéens 2025.",
    ],
    year: 2025,
    publisher: "Gallimard",
    pages: 282,
    isbn: "9782073080028",
    format: "grand-format",
    awards: [
      { name: "Prix Femina", year: 2025 },
      { name: "Prix Goncourt des lycéens", year: 2025 },
      { name: "Prix Renaudot des lycéens", year: 2025 },
    ],
  }),

  // ------------------------------------------------------------------ Jean-Joseph Rabearivelo
  livre({
    slug: "la-coupe-de-cendres",
    title: "La Coupe de cendres",
    contributors: [rabearivelo],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "colonisation"],
    summary:
      "Premier recueil de Rabearivelo, publié à Tananarive en 1924, quand il a vingt-trois ans. Autodidacte passionné de littérature française, le jeune poète y montre déjà une grande maîtrise des mètres et des rythmes. Il reste encore fidèle aux modèles du XIXe siècle qu'il a lus et admirés. Un premier pas qui annonce le grand poète malgache qu'il deviendra.",
    whyRead: [
      "Les débuts du premier grand poète moderne de Madagascar.",
      "Une poésie classique, déjà très maîtrisée.",
      "Pour suivre l'évolution de Rabearivelo depuis l'origine.",
    ],
    year: 1924,
    publisher: "G. Pitot de la Beaujardière",
    pages: 39,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "sylves",
    title: "Sylves",
    contributors: [rabearivelo],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "colonisation"],
    summary:
      "Deuxième recueil de Rabearivelo, Sylves appartient à sa période d'inspiration néo-romantique. Il y privilégie les pièces brèves, sonnets et dizains, et tend vers une poésie pure, très travaillée. Le poète, nourri de littérature française, y cherche encore sa propre voix. Réédité en 2017, ce recueil permet de découvrir la première manière d'un auteur essentiel.",
    whyRead: [
      "La première manière de Rabearivelo, enfin rééditée.",
      "Des poèmes brefs, ciselés comme des bijoux.",
      "Un jalon de la poésie malgache de langue française.",
    ],
    year: 1927,
    publisher: "Abordo",
    pages: 72,
    isbn: "9791092965087",
    format: null,
    awards: [],
  }),
  livre({
    slug: "volumes",
    title: "Volumes",
    contributors: [rabearivelo],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "colonisation"],
    summary:
      "Publié à Tananarive en 1928, Volumes prolonge l'inspiration de Sylves. Rabearivelo, qui se dit alors poète post-symboliste, y réunit plusieurs ensembles de poèmes courts, aux rythmes très maîtrisés. On y sent l'admiration pour les poètes français et la recherche d'une poésie pure. Quelques années plus tard, il trouvera une voie plus personnelle avec Presque-songes et Traduit de la nuit.",
    whyRead: [
      "Un recueil de jeunesse d'un poète majeur.",
      "La virtuosité d'un autodidacte passionné.",
      "Pour mesurer le chemin parcouru jusqu'à Presque-songes.",
    ],
    year: 1928,
    publisher: "Imprimerie de l'Imerina",
    pages: 108,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "traduit-de-la-nuit",
    title: "Traduit de la nuit",
    contributors: [rabearivelo],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "tradition", "contes"],
    summary:
      "Recueil jumeau de Presque-songes, Traduit de la nuit réunit trente poèmes que Rabearivelo a écrits en même temps en malgache et en français. Le poète y renouvelle complètement sa manière : images rurales et quotidiennes, visions de rêve, paroles anciennes chantées sur un mode neuf. Seule la version française a paru de son vivant, en 1935. C'est l'un des sommets de la poésie malgache.",
    whyRead: [
      "L'un des chefs-d'œuvre de Rabearivelo.",
      "Une poésie née entre deux langues, le malgache et le français.",
      "Des images d'une étrangeté magnifique.",
    ],
    year: 1935,
    publisher: "Sépia",
    pages: 75,
    isbn: "9782842801250",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "vieilles-chansons-des-pays-d-imerina",
    title: "Vieilles chansons des pays d'Imerina",
    contributors: [rabearivelo],
    genre: "poesie",
    audience: "adulte",
    themes: ["tradition", "contes", "amour"],
    summary:
      "À la fin de sa vie, Rabearivelo se tourne vers la poésie traditionnelle de sa région, les hain-teny, ces joutes poétiques où l'on parle d'amour et de sagesse par images. Il les adapte en français, en gardant leur saveur et leurs détours. Le recueil paraît après sa mort, en 1939. Une belle manière de découvrir la poésie orale des hautes terres de Madagascar.",
    whyRead: [
      "La poésie traditionnelle malgache transmise par un grand poète.",
      "Des poèmes d'amour malicieux et imagés.",
      "Un recueil posthume, devenu classique.",
    ],
    year: 1939,
    publisher: "La Différence",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "l-interference",
    title: "L'Interférence",
    contributors: [rabearivelo],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "famille", "histoire"],
    summary:
      "Écrit en 1928 et publié bien après la mort de l'auteur, ce roman historique suit une famille de l'aristocratie merina sur trois générations. De la fin du XIXe siècle à la conquête française, il montre comment la colonisation bouleverse ses privilèges, son prestige et sa manière de vivre. Rabearivelo, lui-même issu de cette noblesse déchue, y met beaucoup de son histoire. Un témoignage précieux sur Madagascar au moment de la conquête.",
    whyRead: [
      "Un roman longtemps inédit du grand poète malgache.",
      "La fin d'un monde aristocratique sous la colonisation.",
      "Une page d'histoire de Madagascar vue de l'intérieur.",
    ],
    year: 1988,
    publisher: "No comment éditions",
    pages: 204,
    isbn: "9791090721173",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-aube-rouge",
    title: "L'Aube rouge",
    contributors: [rabearivelo],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "guerre"],
    summary:
      "Premier roman de Rabearivelo, écrit en 1925 et publié seulement en 1998. Il raconte les dernières années du royaume de l'Imerina et le début des guerres franco-malgaches. Le livre rend hommage à Rainandriamampandry, gouverneur de Tamatave, figure de la résistance à la conquête française. Un roman historique qui exalte la mémoire d'un royaume perdu.",
    whyRead: [
      "La fin du royaume de Madagascar racontée par un poète.",
      "Un hommage à un héros de la résistance malgache.",
      "Un inédit longtemps oublié, enfin réédité.",
    ],
    year: 1998,
    publisher: "No comment éditions",
    pages: 158,
    isbn: "9791090721180",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Raharimanana
  livre({
    slug: "lucarne",
    title: "Lucarne",
    contributors: [raharimanana],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["ville", "enfance", "politique"],
    summary:
      "Premier recueil de nouvelles de Raharimanana, Lucarne plonge au cœur d'Antananarivo, la capitale de Madagascar. On y découvre ses zones d'ombre, la misère quotidienne et la survie d'un jeune garçon prêt à tout pour s'en sortir. L'écriture, très poétique, passe de la douceur à une violence saisissante. Le regard d'un jeune auteur sur une ville qu'il a quittée pour la France.",
    whyRead: [
      "Antananarivo comme on ne la voit jamais.",
      "Une écriture lyrique qui ne détourne pas les yeux.",
      "Les débuts d'une grande voix malgache.",
    ],
    year: 1996,
    publisher: "Le Serpent à plumes",
    pages: 136,
    isbn: "2842611667",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "reves-sous-le-linceul",
    title: "Rêves sous le linceul",
    contributors: [raharimanana],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["politique", "ville", "contes"],
    summary:
      "Dans ce deuxième recueil de nouvelles, Raharimanana mêle les légendes et les vieilles croyances de Madagascar à la violence du présent. Les bidonvilles, la misère et la mort y côtoient la beauté de la nature et la force des rêves. Sa langue, sensuelle et nourrie de tradition orale, donne une dimension de poème à ces récits souvent durs. Le livre a reçu le grand prix littéraire de Madagascar.",
    whyRead: [
      "Madagascar entre légendes et misère contemporaine.",
      "Une prose poétique, puissante et sensuelle.",
      "Grand prix littéraire de Madagascar 1998.",
    ],
    year: 1998,
    publisher: "Le Serpent à plumes",
    pages: 131,
    isbn: "2753800081",
    format: "poche",
    awards: [{ name: "Grand prix littéraire de Madagascar (ADELF)", year: 1998 }],
  }),
  livre({
    slug: "l-arbre-anthropophage",
    title: "L'Arbre anthropophage",
    contributors: [raharimanana],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "histoire", "famille", "contes"],
    summary:
      "En 2002, le père de Raharimanana, professeur d'histoire à l'université d'Antananarivo, est arrêté et torturé pour une émission de radio consacrée à l'histoire de Madagascar. Dans ce récit, l'écrivain mêle les légendes et superstitions de son île aux événements politiques récents, jusqu'à la crise qui a suivi l'élection présidentielle contestée de 2001. Il y dénonce la dictature, la corruption et toutes les formes d'oppression. Un texte en colère, qui cherche à sauver la mémoire d'un peuple.",
    whyRead: [
      "Un fils qui écrit pour défendre son père.",
      "L'histoire de Madagascar entre mythes et actualité.",
      "Un récit engagé, d'une grande force.",
    ],
    year: 2004,
    publisher: "Joëlle Losfeld",
    pages: 255,
    isbn: "2070789497",
    format: null,
    awards: [],
  }),
  livre({
    slug: "madagascar-1947",
    title: "Madagascar, 1947",
    contributors: [raharimanana],
    genre: "essai",
    audience: "adulte",
    themes: ["colonisation", "histoire", "guerre", "politique"],
    summary:
      "En 1947, une insurrection éclate à Madagascar contre la colonisation française, et sa répression fait des dizaines de milliers de morts. Raharimanana retrace ces événements et s'interroge sur les rapports entre colonisateurs et colonisés, mais aussi entre le pouvoir d'aujourd'hui et ce passé. Le texte est accompagné de photographies du fonds de Charles Ravoajanahary, grande figure de l'indépendance malgache. Une édition bilingue, en français et en malgache.",
    whyRead: [
      "Un épisode colonial longtemps passé sous silence.",
      "Un texte bref, accompagné de photographies d'archives.",
      "Pour prolonger la lecture de Nour, 1947.",
    ],
    year: 2007,
    publisher: "Vents d'ailleurs",
    pages: 93,
    isbn: "9782364130531",
    format: null,
    awards: [],
  }),
  livre({
    slug: "za",
    title: "Za",
    contributors: [raharimanana],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "famille", "contes"],
    summary:
      "Quelque part sur l'océan, sur une île dominée par les puissants et leur chef Dollaromane, Za, ancien prisonnier brisé par la torture, cherche le corps de son fils mort. Suivi de sa femme devenue folle, il parle sans arrêt, dans une langue cabossée qui zézaie. Entre le monde des vivants et celui des morts, son long monologue dit la barbarie qui ronge son pays. Une fable politique incantatoire et grinçante.",
    whyRead: [
      "Un monologue fou et bouleversant.",
      "Une langue inventée, qui fait entendre les sans-voix.",
      "Une fable sur Madagascar et toutes les dictatures.",
    ],
    year: 2008,
    publisher: "Philippe Rey",
    pages: 300,
    isbn: "9782848761053",
    format: null,
    awards: [],
  }),
  livre({
    slug: "les-cauchemars-du-gecko",
    title: "Les Cauchemars du gecko",
    contributors: [raharimanana],
    genre: "theatre",
    audience: "adulte",
    themes: ["politique", "humour", "colonisation"],
    summary:
      "Comment voit-on le monde quand on vit dans un pays très pauvre comme Madagascar, et qu'on regarde de là-bas l'Occident riche, même en crise ? Ce texte, tiré d'un spectacle créé en 2008, répond avec une ironie mordante. Raharimanana y manie les mots comme une arme, entre théâtre et poésie. Le livre a reçu le prix de la poésie du Salon du livre insulaire d'Ouessant.",
    whyRead: [
      "Un regard ironique du Sud sur le Nord.",
      "Un texte de scène, entre théâtre et poème.",
      "Prix de poésie du Salon du livre insulaire d'Ouessant 2011.",
    ],
    year: 2011,
    publisher: "Vents d'ailleurs",
    pages: 109,
    isbn: "9782911412790",
    format: null,
    awards: [{ name: "Prix de poésie du Salon du livre insulaire d'Ouessant", year: 2011 }],
  }),
  livre({
    slug: "portraits-d-insurges",
    title: "Portraits d'insurgés",
    subtitle: "Madagascar 1947",
    contributors: [raharimanana, { role: "auteur", name: "Pierrot Men", authorSlug: null }],
    genre: "recit",
    audience: "adulte",
    themes: ["colonisation", "histoire", "guerre"],
    summary:
      "Raharimanana et le photographe malgache Pierrot Men sont allés à la rencontre des derniers témoins de l'insurrection de 1947. Le livre réunit leurs portraits en noir et blanc et leurs témoignages. Ces vieillards racontent la révolte contre la colonisation et sa terrible répression, longtemps tue. Né d'une exposition présentée au festival d'Avignon en 2009, c'est un livre pour briser le silence.",
    whyRead: [
      "Les visages et les voix des derniers témoins de 1947.",
      "Un livre de photographies d'une grande force.",
      "Une mémoire coloniale enfin entendue.",
    ],
    year: 2011,
    publisher: "Vents d'ailleurs",
    pages: null,
    isbn: "9782911412882",
    format: null,
    awards: [],
  }),
  livre({
    slug: "revenir",
    title: "Revenir",
    contributors: [raharimanana],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "famille", "politique", "enfance"],
    summary:
      "Invité en Corse pour lire ses textes, l'écrivain Hira manque de se noyer devant la plage d'Algajola. Ce frôlement de la mort le décide à écrire son histoire et à affronter les images de sa vie d'avant, à Madagascar. Il se souvient de son enfance dans les collines, puis de son père, intellectuel devenu opposant, arrêté et torturé. Un grand roman de mémoire, en partie inspiré de la vie de l'auteur.",
    whyRead: [
      "Un roman ample sur l'enfance, l'exil et la mémoire.",
      "Madagascar de l'indépendance à aujourd'hui.",
      "Le livre le plus personnel de Raharimanana.",
    ],
    year: 2018,
    publisher: "Rivages",
    pages: 454,
    isbn: "9782743671174",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "tisser",
    title: "Tisser",
    contributors: [raharimanana],
    genre: "recit",
    audience: "adulte",
    themes: ["contes", "politique", "histoire"],
    summary:
      "Un enfant mort-né raconte la naissance du monde et convoque les mythes de Madagascar pour dire les dérives totalitaires et la quête de liberté. Dans cette fable contemporaine, Raharimanana relie les temps, les ancêtres et les vivants, l'esprit et la réalité, comme les fils d'un tissage. Le texte mêle récit et poésie, et l'auteur le lit souvent en public au son du marovany, la harpe malgache. Une méditation sur l'histoire collective et le pouvoir de l'utopie.",
    whyRead: [
      "Une fable poétique racontée par un narrateur inattendu.",
      "Les mythes malgaches au service d'une réflexion politique.",
      "Un texte à écouter autant qu'à lire.",
    ],
    year: 2021,
    publisher: "Mémoire d'encrier",
    pages: 92,
    isbn: "9782897127374",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Ali Zamir
  livre({
    slug: "mon-etincelle",
    title: "Mon étincelle",
    contributors: [zamir],
    genre: "roman",
    audience: "adulte",
    themes: ["amour", "famille", "humour"],
    summary:
      "Étincelle est une jeune fille à bord d'un avion qui relie deux îles des Comores. Prise dans les turbulences du vol et tiraillée entre deux amours, elle se souvient des histoires que lui racontait sa mère, à commencer par celle de ses parents, deux étudiants rencontrés à Mahajanga, à Madagascar. Au fil des récits défilent des personnages aux noms improbables : Douceur, Douleur, Efferalgan, Vitamine… Un roman foisonnant, entre conte et satire de la société comorienne.",
    whyRead: [
      "Des histoires d'amour en cascade, au rythme des turbulences.",
      "Des personnages aux noms aussi drôles qu'inoubliables.",
      "La langue inventive d'Ali Zamir, l'auteur d'Anguille sous roche.",
    ],
    year: 2017,
    publisher: "Le Tripode",
    pages: 271,
    isbn: "9782370551368",
    format: null,
    awards: [],
  }),
  livre({
    slug: "derange-que-je-suis",
    title: "Dérangé que je suis",
    contributors: [zamir],
    genre: "roman",
    audience: "adulte",
    themes: ["travail", "humour", "amour"],
    summary:
      "Sur le port de Mutsamudu, à Anjouan, Dérangé est un pauvre docker aux habits rapiécés qui pousse son chariot rafistolé pour gagner de quoi manger. Sa vie bascule quand il croise une femme éblouissante, qui l'entraîne dans un défi insensé contre un trio de dockers hostiles. Construit en cinq actes, le roman passe sans cesse de la farce au drame. Ali Zamir y raconte la misère et l'exploitation avec une gaieté et une invention verbale irrésistibles.",
    whyRead: [
      "Un héros naïf et attachant, entre rire et larmes.",
      "Une langue qui bouscule joyeusement le français.",
      "Prix du roman France Télévisions 2019.",
    ],
    year: 2019,
    publisher: "Le Tripode",
    pages: 190,
    isbn: "9782370551696",
    format: null,
    awards: [{ name: "Prix du roman France Télévisions", year: 2019 }],
  }),
  livre({
    slug: "jouissance",
    title: "Jouissance",
    contributors: [zamir],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "identite"],
    summary:
      "Le narrateur de ce roman est un livre, qui raconte lui-même sa vie malchanceuse. Passant de main en main et de poubelle en poubelle, il assiste à des scènes hilarantes ou cruelles, à une arnaque, à un fait divers digne des journaux à sensation. À travers ses lecteurs successifs, il observe la malice, le désir et la folie des humains. Un hommage débridé au Grand-Guignol et à l'objet livre.",
    whyRead: [
      "Un narrateur original : un roman qui parle de ses lecteurs.",
      "Une comédie humaine grinçante et réjouissante.",
      "Un hommage plein de verve à la lecture.",
    ],
    year: 2022,
    publisher: "Le Tripode",
    pages: 234,
    isbn: "9782370553249",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Beata Umubyeyi Mairesse
  livre({
    slug: "ejo",
    title: "Ejo",
    subtitle: "suivi de Lézardes et autres nouvelles",
    contributors: [beata],
    genre: "nouvelles",
    audience: "adulte",
    themes: ["genocide", "femmes", "famille", "enfance"],
    summary:
      "Ce volume réunit les deux premiers recueils de Beata Umubyeyi Mairesse. Ejo, mot kinyarwanda qui signifie à la fois « hier » et « demain », raconte l'avant et l'après du génocide des Tutsi à travers des voix de femmes. Lézardes dresse le portrait de la génération de l'autrice, entre conte et nouvelle, et montre comment 1994 a marqué des enfants et de futurs parents. Des histoires brèves, pudiques et fortes.",
    whyRead: [
      "Les deux recueils qui ont révélé l'autrice, réunis en un volume.",
      "Des voix de femmes avant et après le génocide.",
      "Des nouvelles courtes, à lire une à une.",
    ],
    year: 2015,
    publisher: "Autrement",
    pages: 399,
    isbn: "9782746755932",
    format: null,
    awards: [{ name: "Prix François Augiéras", year: 2016 }],
  }),
  livre({
    slug: "consolee",
    title: "Consolée",
    contributors: [beata],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "identite", "femmes", "exil"],
    summary:
      "En 1954, au Rwanda sous tutelle belge, Consolée, fille d'un Blanc et d'une Rwandaise, est arrachée à sa famille pour être placée dans une institution pour « enfants mulâtres ». Soixante-cinq ans plus tard, Ramata, d'origine sénégalaise, fait un stage d'art-thérapie dans une maison de retraite du Sud-Ouest de la France. Elle y rencontre madame Astrida, une vieille femme métisse atteinte d'Alzheimer qui ne parle plus qu'une langue inconnue. En reconstituant sa vie, Ramata se confronte à sa propre histoire.",
    whyRead: [
      "Un épisode colonial méconnu : les enfants métis arrachés à leurs mères.",
      "Deux femmes, deux époques, qui se répondent.",
      "Prix Ahmadou-Kourouma 2023.",
    ],
    year: 2022,
    publisher: "J'ai lu",
    pages: 345,
    isbn: "9782290385005",
    format: "poche",
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2023 }],
  }),
  livre({
    slug: "peau-d-epice",
    title: "Peau d'épice",
    contributors: [beata, { role: "dessinateur", name: "Véronique Joffre", authorSlug: null }],
    genre: "jeunesse",
    audience: "jeunesse",
    themes: ["identite", "famille", "enfance"],
    summary:
      "Premier album jeunesse de Beata Umubyeyi Mairesse, illustré par Véronique Joffre. Une petite fille métisse s'interroge sur sa couleur de peau et sur ses origines. Elle les explore à travers les arbres fruitiers du pays de son père, qui est noir. Un album tendre et coloré pour parler du métissage avec les plus jeunes.",
    whyRead: [
      "Un album pour parler du métissage avec les enfants.",
      "Des illustrations chaleureuses et colorées.",
      "La première incursion de l'autrice en jeunesse.",
    ],
    year: 2023,
    publisher: "Gallimard Jeunesse",
    pages: null,
    isbn: "9782075189866",
    format: "album",
    awards: [],
  }),
  livre({
    slug: "culbuter-le-malheur",
    title: "Culbuter le malheur",
    subtitle: "suivi de Après le progrès",
    contributors: [beata],
    genre: "poesie",
    audience: "adulte",
    themes: ["genocide", "femmes", "identite"],
    summary:
      "Ce recueil réunit un ensemble de poèmes inédits et la réédition d'Après le progrès, paru en 2019. Ce premier recueil se composait de quarante-cinq poèmes en prose, ordonnés en trois parties : perdu, volé, racheté. Beata Umubyeyi Mairesse y dit la survie, la mémoire et la volonté de renverser le malheur. Le livre a été très bien accueilli en France comme au Québec.",
    whyRead: [
      "Toute la poésie de l'autrice réunie en un volume.",
      "Des poèmes de survie et de résistance.",
      "Pour découvrir une autre facette de la romancière.",
    ],
    year: 2024,
    publisher: "Mémoire d'encrier",
    pages: 114,
    isbn: "9782897129545",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-convoi",
    title: "Le Convoi",
    contributors: [beata],
    genre: "recit",
    audience: "adulte",
    themes: ["genocide", "enfance", "histoire"],
    summary:
      "En 1994, pendant le génocide des Tutsi, Beata Umubyeyi Mairesse, adolescente, survit à Butare puis parvient à fuir le Rwanda grâce à un convoi d'enfants organisé par l'ONG Terre des hommes. Pendant quinze ans, elle a enquêté pour retrouver les autres enfants du convoi, l'équipe de la BBC qui a filmé leur évacuation et les humanitaires qui l'ont sauvée. Entre archives et écriture de soi, elle réfléchit à ce que signifie témoigner. Un récit majeur, comparé à Si c'est un homme de Primo Levi.",
    whyRead: [
      "Un témoignage bouleversant et une enquête minutieuse.",
      "Une réflexion profonde sur les traces et la mémoire.",
      "Prix Essai France Télévisions.",
    ],
    year: 2024,
    publisher: "J'ai lu",
    pages: 317,
    isbn: "9782290406373",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-solidarite-des-ebranles",
    title: "La Solidarité des ébranlés",
    contributors: [beata],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "histoire", "identite"],
    summary:
      "Tout part d'une photographie de Nelson Mandela aux côtés de l'activiste sud-africain Zackie Achmat, tous deux vêtus d'un tee-shirt « HIV Positive ». Cette image renvoie l'autrice à une scène de son enfance au Rwanda, qui n'a jamais été photographiée. Elle raconte son entrée dans la lutte contre le sida au début des années 2000, avec Act Up-Paris, et enquête sur les combats pour l'accès aux trithérapies en Afrique du Sud, en France et dans le monde. Un récit sur la honte retournée en colère, puis en solidarité.",
    whyRead: [
      "Un pan d'histoire oublié : la bataille pour les trithérapies.",
      "Un récit intime et militant à la fois.",
      "Par l'autrice du Convoi.",
    ],
    year: 2026,
    publisher: "Julliard",
    pages: null,
    isbn: null,
    format: "grand-format",
    awards: [],
  }),
];

/** Nouveaux auteurs de ce lot (vide si le lot ne complète que des auteurs déjà présents). */
export const auteurs: Author[] = [];

/** Photos libres de droits des nouveaux auteurs (fichiers : public/authors/). */
export const photos: Record<string, { photo: string; credit: string; source: string }> = {};

/** Livres de ce lot qui ont leur illustration Keurbook (public/illustrations/<slug>.webp). */
export const illustres: string[] = [
  "inyenzi-ou-les-cafards", "la-femme-aux-pieds-nus", "l-iguifou", "ce-que-murmurent-les-collines", "coeur-tambour",
  "un-si-beau-diplome", "kibogo-est-monte-au-ciel", "sister-deborah", "julienne", "l-ennui-des-apres-midi-sans-fin",
  "petit-pays-bd", "le-pays-sans-ombre", "cahier-nomade", "balbala", "moisson-de-cranes",
  "les-nomades-mes-freres-vont-boire-a-la-grande-ourse", "rift-routes-rails", "transit", "passage-des-larmes",
  "la-divine-chanson", "mon-nom-est-aube", "pourquoi-tu-danses-quand-tu-marches",
  "dictionnaire-enjoue-des-cultures-africaines", "dis-moi-pour-qui-j-existe", "quand-on-n-a-que-la-terre",
  "notre-france-noire", "rue-la-poudriere", "le-voile-de-draupadi", "l-arbre-fouet", "moi-l-interdite", "pagli",
  "soupir", "le-long-desir", "la-vie-de-josephin-le-fou", "indian-tango", "le-sari-vert",
  "les-hommes-qui-me-parlent", "quand-la-nuit-consent-a-me-parler", "les-jours-vivants", "l-ambassadeur-triste",
  "ceux-du-large", "manger-l-autre", "danser-sur-tes-braises", "fardo", "le-rire-des-deesses", "sylvia-p",
  "le-jour-des-cameleons", "la-nuit-s-ajoute-a-la-nuit", "chronique-d-un-royaume-perdu",
  "les-rochers-de-poudre-d-or", "blue-bay-palace", "la-noce-d-anna", "le-dernier-frere", "en-attendant-demain",
  "petit-eloge-des-fantomes", "une-annee-lumiere", "le-ciel-par-dessus-le-toit", "rien-ne-t-appartient",
  "la-memoire-delavee", "la-nuit-au-coeur", "la-coupe-de-cendres", "sylves", "volumes", "traduit-de-la-nuit",
  "vieilles-chansons-des-pays-d-imerina", "l-interference", "l-aube-rouge", "lucarne", "reves-sous-le-linceul",
  "l-arbre-anthropophage", "madagascar-1947", "za", "les-cauchemars-du-gecko", "portraits-d-insurges", "revenir",
  "tisser", "mon-etincelle", "derange-que-je-suis", "jouissance", "ejo", "consolee", "peau-d-epice",
  "culbuter-le-malheur", "le-convoi", "la-solidarite-des-ebranles",
];
