import type { Author } from "../types";

export const auteursBd: Author[] = [
  {
    slug: "marguerite-abouet",
    name: "Marguerite Abouet",
    birthYear: 1971,
    deathYear: null,
    countryCode: "CI",
    origin: null,
    bio: "Née à Abidjan, Marguerite Abouet grandit dans le quartier de Yopougon avant de partir pour la France à douze ans. Elle écrit d'abord pour elle-même, puis découvre la bande dessinée comme moyen de raconter la Côte d'Ivoire autrement que par les images de crise. Aya de Yopougon, dessinée par Clément Oubrerie, paraît en 2005 et devient un grand succès populaire, couronné à Angoulême. Elle crée ensuite Akissi pour les plus jeunes, inspirée de ses propres bêtises d'enfant, puis d'autres séries comme Bienvenue et Commissaire Kouamé. Elle a aussi coréalisé l'adaptation d'Aya en film d'animation, sortie en 2013.",
    photo: null,
    photoCredit: null,
    startWith: "aya-de-yopougon",
    otherTitles: [
      "Bienvenue (2010)",
      "Délices d'Afrique (2012)",
      "Commissaire Kouamé : Un si joli jardin (2017)",
      "Terre gâtée : Ange, le migrant (2018)",
    ],
    awards: [
      { name: "Prix du premier album, Festival d'Angoulême", year: 2006 },
      { name: "Prix de la BD du Point", year: 2007 },
    ],
  },
  {
    slug: "pahe",
    name: "Pahé",
    birthYear: 1971,
    deathYear: null,
    countryCode: "GA",
    origin: null,
    bio: "Pahé, de son vrai nom Patrick Essono Nkouna, est né à Bitam, dans le nord du Gabon. Après des études d'art à Paris, il devient dans les années 1990 un caricaturiste très lu de la presse gabonaise, puis une figure de la télévision avec une émission satirique. Sa rencontre avec l'éditeur Pierre Paquet le lance dans la bande dessinée autobiographique avec La Vie de Pahé, adaptée ensuite en dessin animé. Il donne aussi un album à Dipoula, le petit albinos qu'il a inventé dès le lycée. Son humour mordant en fait l'un des dessinateurs les plus populaires d'Afrique centrale.",
    photo: null,
    photoCredit: null,
    startWith: "la-vie-de-pahe",
    otherTitles: [
      "Gabonaises... Gabonais... (2006)",
      "Les Choses du pays (2008)",
      "La Vie de Pahé, t. 2 : Paname (2008)",
    ],
    awards: [],
  },
  {
    slug: "joelle-esso",
    name: "Joëlle Esso",
    birthYear: 1968,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Née à Douala, Joëlle Esso grandit au Cameroun, passe son adolescence en Côte d'Ivoire puis s'installe à Paris, où elle étudie les arts graphiques et l'histoire de l'art. Artiste aux multiples talents, elle est à la fois illustratrice, peintre, chanteuse et comédienne. Après avoir illustré des livres pour enfants, elle signe en 2010 sa première bande dessinée, Petit Joss, inspirée de son enfance à Douala. Elle a ensuite raconté en BD la jeunesse du footballeur Samuel Eto'o. Elle dirige aussi un centre culturel panafricain à Porto-Novo, au Bénin.",
    photo: null,
    photoCredit: null,
    startWith: "petit-joss",
    otherTitles: [
      "Hanibal@Pushkin (2011)",
      "Eto'o Fils, t. 1 : Naissance d'un champion (2012)",
      "Eto'o Fils, t. 2 : L'Envol (2014)",
      "Une maison dans le désert (2023)",
    ],
    awards: [],
  },
  {
    slug: "didier-kassai",
    name: "Didier Kassaï",
    birthYear: 1974,
    deathYear: null,
    countryCode: "CF",
    origin: null,
    bio: "Né à Sibut, en Centrafrique, Didier Kassaï apprend le dessin en autodidacte et publie ses premiers dessins dans la presse de Bangui à la fin des années 1990. Un prix remporté à l'Alliance française lui ouvre les portes des festivals de BD, en Afrique puis en Europe. Il travaille aussi comme illustrateur pour des ONG, dont Médecins sans frontières. Témoin de la guerre civile qui déchire son pays à partir de 2012, il en tire Tempête sur Bangui, récit autobiographique en plusieurs tomes. Il est aujourd'hui l'auteur de BD centrafricain le plus connu.",
    photo: null,
    photoCredit: null,
    startWith: "tempete-sur-bangui",
    otherTitles: [
      "Vies volées (2008)",
      "L'Odyssée de Mongou (2008)",
      "Tempête sur Bangui, t. 2 (2018)",
      "Maison sans fenêtres (2018)",
    ],
    awards: [],
  },
  {
    slug: "barly-baruti",
    name: "Barly Baruti",
    birthYear: 1959,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Né à Kisangani, Barly Baruti remporte enfant un concours de dessin du journal Spirou et devient l'un des pionniers de la bande dessinée au Congo. Dans les années 1980, il anime des ateliers dans toute l'Afrique, lance une revue de BD à Kinshasa et se forme auprès de Bob de Moor, collaborateur d'Hergé. Installé en Belgique au début des années 1990, il dessine avec Frank Giroud les séries Eva K. et Mandrill. Avec Christophe Cassiau-Haurie, il signe ensuite des romans graphiques sur l'histoire du Congo, dont Madame Livingstone. Musicien, il est aussi auteur-compositeur-interprète.",
    photo: null,
    photoCredit: null,
    startWith: "madame-livingstone",
    otherTitles: [
      "Eva K. (1995)",
      "Mandrill (1998)",
      "Chaos debout à Kinshasa (2016)",
      "Le Singe jaune (2018)",
    ],
    awards: [],
  },
  {
    slug: "christophe-ngalle-edimo",
    name: "Christophe Ngalle Edimo",
    birthYear: 1963,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Christophe Ngalle Edimo a grandi au Cameroun, où il a fait des études de lettres à l'université de Yaoundé, avant de s'installer en France à vingt-quatre ans. Parallèlement à un métier auprès de jeunes en difficulté, il écrit des scénarios de bande dessinée. Il a fondé Afrique dessinée, association qui rassemble des auteurs de BD africains vivant en Europe. Ses histoires parlent d'immigration, de retour au pays et des liens compliqués entre la France et l'Afrique. Malamine, dessiné par Simon-Pierre Mbumbo, reste son album le plus connu.",
    photo: null,
    photoCredit: null,
    startWith: "malamine",
    otherTitles: [
      "Une journée dans la vie d'un Africain d'Afrique (2007)",
      "À l'ombre de Paris (2020)",
      "Djo'o bar (2021)",
    ],
    awards: [],
  },
  {
    slug: "simon-pierre-mbumbo",
    name: "Simon-Pierre Mbumbo",
    birthYear: null,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Dessinateur camerounais, Simon-Pierre Mbumbo se passionne très tôt pour la bande dessinée, au point de quitter l'école pour s'y consacrer. Au Cameroun, il fonde le journal New Kids et participe à la création du magazine de BD Mac BD. Installé en France depuis 1999, il rejoint Christophe Ngalle Edimo au sein de l'association Afrique dessinée. Il a créé la série Les K-libres pour le magazine Planète Jeunes. Avec Ngalle Edimo, il signe Malamine, roman graphique sur un jeune Africain à Paris.",
    photo: null,
    photoCredit: null,
    startWith: "malamine",
    otherTitles: ["Le Jugement des animaux (2019)"],
    awards: [],
  },
  {
    slug: "pat-masioni",
    name: "Pat Masioni",
    birthYear: 1961,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Né dans la province du Bandundu, Pat Masioni étudie à l'Académie des beaux-arts de Kinshasa. Dès les années 1980, il dessine de nombreux albums pour les éditions Saint-Paul, illustre des livres et publie des caricatures dans la presse congolaise. Installé à Paris en 2002, il dessine Rwanda 1994, bande dessinée en deux tomes sur le génocide des Tutsi. Il devient ensuite le premier auteur de BD d'Afrique noire publié aux États-Unis par DC Comics, avec un épisode de la série Unknown Soldier. Il réalise aussi des BD éducatives, notamment pour des agences de l'ONU.",
    photo: null,
    photoCredit: null,
    startWith: "rwanda-1994",
    otherTitles: [
      "Israel Vibration (2009)",
      "Soldat inconnu, t. 3 : Saison sèche (2013)",
      "Njinga Mbandi, reine du Ndongo et du Matamba (2014)",
      "UN3 : Urgence niveau 3 (2018)",
    ],
    awards: [{ name: "Prix Glyph Comics", year: 2010 }],
  },
  {
    slug: "eyoum-ngangue",
    name: "Eyoum Ngangué",
    birthYear: 1967,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Eyoum Ngangué est un journaliste camerounais, figure de la presse d'investigation dans les années 1990. Il lance en 1993 Le Messager Popoli, journal satirique associé au Messager. Condamné et emprisonné en 1997 pour un article jugé offensant envers le chef de l'État, il obtient l'asile en France l'année suivante. Installé à Paris, il poursuit sa carrière de journaliste et écrit des scénarios de bande dessinée. Une éternité à Tanger, dessiné par Faustin Titi, a été traduit dans plusieurs langues.",
    photo: null,
    photoCredit: null,
    startWith: "une-eternite-a-tanger",
    otherTitles: [],
    awards: [],
  },
  {
    slug: "faustin-titi",
    name: "Faustin Titi",
    birthYear: 1971,
    deathYear: null,
    countryCode: "CI",
    origin: null,
    bio: "Dessinateur ivoirien, Faustin Titi étudie la peinture au centre artistique d'Abengourou à la fin des années 1980. Il travaille ensuite pour des agences et des journaux d'Abidjan, où il publie dessins de presse et bandes dessinées. Il réalise aussi de nombreuses BD éducatives et publicitaires. Remarqué dans plusieurs concours en Côte d'Ivoire et en Europe, il dessine Une éternité à Tanger sur un scénario d'Eyoum Ngangué, album qui a beaucoup circulé en Afrique comme en Europe.",
    photo: null,
    photoCredit: null,
    startWith: "une-eternite-a-tanger",
    otherTitles: ["Le Secret du manguier ou La Jeunesse volée (2008)"],
    awards: [],
  },
];
