import type { Author } from "../types";

/** Champs communs : photos ajoutées plus tard à la main (libres de droits uniquement). */
type Saisie = Omit<Author, "photo" | "photoCredit" | "origin"> & Partial<Pick<Author, "origin">>;

const auteur = (a: Saisie): Author => ({ origin: null, photo: null, photoCredit: null, ...a });

export const auteursOuest: Author[] = [
  // ------------------------------------------------------------------ Sénégal
  auteur({
    slug: "mariama-ba",
    name: "Mariama Bâ",
    birthYear: 1929,
    deathYear: 1981,
    countryCode: "SN",
    bio: "Née à Dakar, Mariama Bâ est élevée par ses grands-parents maternels dans un milieu musulman traditionnel. Institutrice, puis inspectrice de l'enseignement, elle s'engage très tôt pour l'éducation et les droits des femmes. Son premier roman, « Une si longue lettre », paraît en 1979 et connaît un succès immédiat, traduit dans de nombreuses langues. Elle meurt en 1981, avant la parution de son second roman. Son œuvre, brève, reste l'une des plus lues de la littérature africaine.",
    startWith: "une-si-longue-lettre",
    otherTitles: ["Un chant écarlate (1981)"],
    awards: [{ name: "Prix Noma", year: 1980 }],
  }),
  auteur({
    slug: "cheikh-hamidou-kane",
    name: "Cheikh Hamidou Kane",
    birthYear: 1928,
    deathYear: null,
    countryCode: "SN",
    bio: "Né à Matam, dans le nord du Sénégal, Cheikh Hamidou Kane fréquente l'école coranique avant l'école française, puis étudie la philosophie et le droit à Paris. Il fait ensuite carrière dans la haute administration sénégalaise et dans des organisations internationales, et devient ministre. Son premier roman, « L'Aventure ambiguë », largement inspiré de son parcours, devient un classique dès sa parution en 1961. Il attend plus de trente ans avant de publier un second roman. Son œuvre est au cœur des réflexions sur la rencontre entre l'Afrique et l'Occident.",
    startWith: "l-aventure-ambigue",
    otherTitles: ["Les Gardiens du temple (1995)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1962 }],
  }),
  auteur({
    slug: "ousmane-sembene",
    name: "Ousmane Sembène",
    birthYear: 1923,
    deathYear: 2007,
    countryCode: "SN",
    bio: "Né à Ziguinchor, en Casamance, Ousmane Sembène quitte l'école tôt, devient pêcheur, maçon, puis tirailleur pendant la Seconde Guerre mondiale. Docker à Marseille, syndicaliste, il apprend seul à écrire et publie son premier roman en 1956. Ses livres donnent la parole aux ouvriers, aux femmes et aux petites gens. Il se tourne ensuite vers le cinéma pour toucher un public plus large, et devient l'un des pères du cinéma africain. Écrivain engagé, il n'a jamais cessé de dénoncer les injustices, coloniales comme postcoloniales.",
    startWith: "les-bouts-de-bois-de-dieu",
    otherTitles: ["Le Docker noir (1956)", "Ô pays, mon beau peuple ! (1957)", "Le Mandat (1966)", "Xala (1973)"],
    awards: [],
  }),
  auteur({
    slug: "leopold-sedar-senghor",
    name: "Léopold Sédar Senghor",
    birthYear: 1906,
    deathYear: 2001,
    countryCode: "SN",
    bio: "Né à Joal, sur la Petite-Côte sénégalaise, Léopold Sédar Senghor fait ses études à Paris, où il devient le premier Africain agrégé de grammaire. Avec Aimé Césaire et Léon-Gontran Damas, il fonde le mouvement de la négritude, qui revendique la valeur des cultures noires. Poète, il publie de nombreux recueils à partir de 1945. Homme politique, il devient en 1960 le premier président du Sénégal indépendant, et le reste vingt ans. Il est en 1983 le premier Africain élu à l'Académie française.",
    startWith: "ethiopiques",
    otherTitles: ["Chants d'ombre (1945)", "Hosties noires (1948)", "Nocturnes (1961)", "Lettres d'hivernage (1973)"],
    awards: [],
  }),
  auteur({
    slug: "mohamed-mbougar-sarr",
    name: "Mohamed Mbougar Sarr",
    birthYear: 1990,
    deathYear: null,
    countryCode: "SN",
    bio: "Né à Dakar et élevé à Diourbel, Mohamed Mbougar Sarr part en France après le prestigieux Prytanée militaire de Saint-Louis, pour étudier à Compiègne puis à l'EHESS. Son premier roman, « Terre ceinte », sur la vie d'une ville sous le joug djihadiste, est remarqué dès 2015. Il explore ensuite l'accueil des migrants en Italie, puis l'homophobie au Sénégal. En 2021, « La plus secrète mémoire des hommes » fait de lui, à 31 ans, le premier écrivain né en Afrique subsaharienne à recevoir le prix Goncourt. Il est aujourd'hui l'une des voix majeures de la littérature de langue française.",
    startWith: "la-plus-secrete-memoire-des-hommes",
    otherTitles: ["Terre ceinte (2015)", "Silence du chœur (2017)", "De purs hommes (2018)"],
    awards: [
      { name: "Prix Ahmadou-Kourouma", year: 2015 },
      { name: "Prix Goncourt", year: 2021 },
    ],
  }),
  auteur({
    slug: "fatou-diome",
    name: "Fatou Diome",
    birthYear: 1968,
    deathYear: null,
    countryCode: "SN",
    bio: "Fatou Diome est née sur l'île de Niodior, dans le delta du Saloum, où elle est élevée par sa grand-mère. Elle part étudier en France et s'installe à Strasbourg, où elle poursuit des études de lettres tout en enchaînant les petits emplois. Son premier livre, un recueil de nouvelles, paraît en 2001, et « Le Ventre de l'Atlantique » la fait connaître du grand public en 2003. Ses romans parlent d'exil, de solitude, de liens familiaux et du regard porté sur les immigrés. Elle est aussi une voix engagée, très présente dans le débat public.",
    startWith: "le-ventre-de-l-atlantique",
    otherTitles: ["La Préférence nationale (2001)", "Kétala (2006)", "Celles qui attendent (2010)", "Impossible de grandir (2013)"],
    awards: [],
  }),
  auteur({
    slug: "boubacar-boris-diop",
    name: "Boubacar Boris Diop",
    birthYear: 1946,
    deathYear: null,
    countryCode: "SN",
    bio: "Né à Dakar, Boubacar Boris Diop est professeur de philosophie, journaliste et scénariste avant de se consacrer à l'écriture. Ses premiers romans interrogent la mémoire et le pouvoir en Afrique. En 1998, il participe au Rwanda à une résidence d'écrivains africains, d'où naît « Murambi, le livre des ossements ». Il écrit aussi en wolof et a fondé une maison d'édition consacrée à cette langue. En 2022, il reçoit le prix international de littérature Neustadt pour l'ensemble de son œuvre.",
    startWith: "murambi-le-livre-des-ossements",
    otherTitles: ["Les Tambours de la mémoire (1990)", "Le Cavalier et son ombre (1997)", "Doomi Golo (2003)", "Kaveena (2006)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2000 },
      { name: "Prix international de littérature Neustadt", year: 2022 },
    ],
  }),
  auteur({
    slug: "aminata-sow-fall",
    name: "Aminata Sow Fall",
    birthYear: 1941,
    deathYear: null,
    countryCode: "SN",
    bio: "Née à Saint-Louis du Sénégal, Aminata Sow Fall fait ses études de lettres en France avant de rentrer enseigner au Sénégal. Elle publie son premier roman en 1976 et devient l'une des premières romancières africaines reconnues. Ses livres observent avec humour et lucidité la société sénégalaise, ses contradictions et ses rapports de pouvoir. Elle a aussi œuvré pour le livre en Afrique, en créant notamment un centre culturel et une maison d'édition. Elle est considérée comme une grande dame des lettres africaines.",
    startWith: "la-greve-des-battu",
    otherTitles: ["Le Revenant (1976)", "L'Appel des arènes (1982)", "Douceurs du bercail (1998)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1980 }],
  }),
  auteur({
    slug: "david-diop",
    name: "David Diop",
    birthYear: 1966,
    deathYear: null,
    countryCode: "SN",
    origin: null,
    bio: "David Diop passe son enfance et sa jeunesse au Sénégal avant de poursuivre ses études en France. Il devient universitaire, spécialiste de la littérature française du XVIIIe siècle et des représentations de l'Afrique à cette époque. Son premier roman paraît en 2012. « Frère d'âme », en 2018, le révèle au grand public et remporte le Goncourt des lycéens, puis l'International Booker Prize pour sa traduction anglaise. Ses romans explorent la violence de l'histoire coloniale et ce qu'elle fait aux êtres.",
    startWith: "frere-d-ame",
    otherTitles: ["1889, l'Attraction universelle (2012)", "La Porte du voyage sans retour (2021)"],
    awards: [
      { name: "Prix Goncourt des lycéens", year: 2018 },
      { name: "Prix Ahmadou-Kourouma", year: 2019 },
      { name: "International Booker Prize", year: 2021 },
    ],
  }),
  auteur({
    slug: "birago-diop",
    name: "Birago Diop",
    birthYear: 1906,
    deathYear: 1989,
    countryCode: "SN",
    bio: "Né à Ouakam, près de Dakar, Birago Diop étudie la médecine vétérinaire à Toulouse, où il côtoie les étudiants de la négritude. Vétérinaire dans plusieurs colonies d'Afrique de l'Ouest, il parcourt la brousse et recueille les contes qu'il entend, en particulier ceux du griot Amadou Koumba. Ses recueils de contes, à partir de 1947, font entrer la tradition orale wolof dans la littérature de langue française. Il est aussi poète et fut ambassadeur du Sénégal. Son poème « Souffles » compte parmi les plus connus de la poésie africaine.",
    startWith: "les-contes-d-amadou-koumba",
    otherTitles: ["Les Nouveaux Contes d'Amadou Koumba (1958)", "Leurres et lueurs (1960)", "Contes et lavanes (1963)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1964 }],
  }),
  auteur({
    slug: "ken-bugul",
    name: "Ken Bugul",
    birthYear: 1947,
    deathYear: null,
    countryCode: "SN",
    bio: "Ken Bugul, de son vrai nom Mariètou Mbaye Biléoma, est née dans le Ndoucoumane, au centre du Sénégal. Après des études au lycée à Thiès, elle part étudier en Belgique, expérience qui nourrit son premier livre, « Le Baobab fou ». Son pseudonyme, qui signifie en wolof « personne n'en veut », lui a été imposé par son éditeur pour protéger son anonymat. Elle poursuit ensuite une œuvre très personnelle, où elle parle sans détour de la condition des femmes, du désir et de la polygamie. Son roman « Riwan ou le chemin de sable » reçoit le Grand prix littéraire d'Afrique noire.",
    startWith: "le-baobab-fou",
    otherTitles: ["Cendres et braises (1994)", "Riwan ou le chemin de sable (1999)", "La Folie et la Mort (2000)", "Mes hommes à moi (2008)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1999 }],
  }),
  auteur({
    slug: "marie-ndiaye",
    name: "Marie NDiaye",
    birthYear: 1967,
    deathYear: null,
    countryCode: "SN",
    origin: "Née à Pithiviers, d'un père sénégalais et d'une mère française",
    bio: "Marie NDiaye grandit en banlieue parisienne avec sa mère et publie son premier roman à dix-sept ans. Elle construit ensuite une œuvre singulière, faite de romans, de pièces de théâtre et de livres pour la jeunesse, souvent traversée par l'étrangeté et le malaise familial. Elle reçoit le prix Femina en 2001 pour « Rosie Carpe ». En 2009, « Trois femmes puissantes » obtient le prix Goncourt. Elle est aussi l'une des rares autrices vivantes dont une pièce est entrée au répertoire de la Comédie-Française.",
    startWith: "trois-femmes-puissantes",
    otherTitles: ["En famille (1990)", "Rosie Carpe (2001)", "Papa doit manger (2003)", "Ladivine (2013)", "La Cheffe, roman d'une cuisinière (2016)"],
    awards: [
      { name: "Prix Femina", year: 2001 },
      { name: "Prix Goncourt", year: 2009 },
    ],
  }),
  auteur({
    slug: "felwine-sarr",
    name: "Felwine Sarr",
    birthYear: 1972,
    deathYear: null,
    countryCode: "SN",
    bio: "Né sur l'île de Niodior, Felwine Sarr est économiste, universitaire, écrivain et musicien. Après des études en France, il enseigne à l'université Gaston-Berger de Saint-Louis, puis aux États-Unis. Il publie des récits, des méditations et des essais, dont « Afrotopia », qui l'impose comme un penseur majeur de l'avenir africain. En 2018, il cosigne avec l'historienne Bénédicte Savoy un rapport remarqué sur la restitution du patrimoine culturel africain. Il a aussi cofondé les Ateliers de la pensée de Dakar.",
    startWith: "afrotopia",
    otherTitles: ["Dahij (2009)", "Méditations africaines (2012)", "Habiter le monde (2017)"],
    awards: [],
  }),
  auteur({
    slug: "cheikh-anta-diop",
    name: "Cheikh Anta Diop",
    birthYear: 1923,
    deathYear: 1986,
    countryCode: "SN",
    bio: "Né à Thieytou, dans la région de Diourbel, Cheikh Anta Diop part étudier à Paris la physique, la chimie, la philosophie et l'histoire. En 1954, « Nations nègres et culture » défend l'idée que l'Égypte ancienne appartient à l'histoire africaine, ce qui suscite de vifs débats. De retour au Sénégal, il crée un laboratoire de datation au radiocarbone à l'Institut fondamental d'Afrique noire, et s'engage en politique contre le parti de Senghor. Son œuvre a nourri la pensée panafricaine. L'université de Dakar porte aujourd'hui son nom.",
    startWith: "nations-negres-et-culture",
    otherTitles: ["L'Unité culturelle de l'Afrique noire (1959)", "Antériorité des civilisations nègres (1967)", "Civilisation ou barbarie (1981)"],
    awards: [],
  }),

  // ------------------------------------------------------------------ Mali
  auteur({
    slug: "amadou-hampate-ba",
    name: "Amadou Hampâté Bâ",
    birthYear: 1901,
    deathYear: 1991,
    countryCode: "ML",
    bio: "Né à Bandiagara, dans une famille peule, Amadou Hampâté Bâ reçoit l'enseignement des maîtres de la tradition avant d'être envoyé à l'école française. Fonctionnaire de l'administration coloniale, puis chercheur à l'Institut français d'Afrique noire, il consacre sa vie à recueillir les traditions orales d'Afrique de l'Ouest. Membre du conseil exécutif de l'Unesco, il y plaide pour la sauvegarde de cette mémoire. Il est l'auteur de contes, d'études sur l'islam et les Peuls, et de mémoires. On lui attribue la célèbre formule selon laquelle, en Afrique, un vieillard qui meurt est une bibliothèque qui brûle.",
    startWith: "amkoullel-l-enfant-peul",
    otherTitles: ["Kaïdara (1969)", "Petit Bodiel (1977)", "Oui mon commandant ! (1994)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1974 },
      { name: "Grand prix littéraire d'Afrique noire", year: 1991 },
    ],
  }),
  auteur({
    slug: "yambo-ouologuem",
    name: "Yambo Ouologuem",
    birthYear: 1940,
    deathYear: 2017,
    countryCode: "ML",
    bio: "Né à Bandiagara, au pays dogon, Yambo Ouologuem fait des études de lettres, de philosophie et de sociologie à Paris. En 1968, son premier roman, « Le Devoir de violence », reçoit le prix Renaudot, une première pour un écrivain africain. Le livre est ensuite accusé d'emprunts à d'autres auteurs, et la polémique ternit sa réputation. Ouologuem publie encore deux livres, puis rentre au Mali où il vit retiré jusqu'à sa mort. Son roman est aujourd'hui relu comme une œuvre audacieuse et visionnaire.",
    startWith: "le-devoir-de-violence",
    otherTitles: ["Lettre à la France nègre (1969)", "Les Mille et Une Bibles du sexe (1969)"],
    awards: [{ name: "Prix Renaudot", year: 1968 }],
  }),

  // ------------------------------------------------------------------ Guinée
  auteur({
    slug: "camara-laye",
    name: "Camara Laye",
    birthYear: 1928,
    deathYear: 1980,
    countryCode: "GN",
    bio: "Né à Kouroussa, en Haute-Guinée, dans une famille de forgerons malinkés, Camara Laye étudie à Conakry puis part en France pour une formation de mécanicien. Ouvrier chez Simca, isolé à Paris, il écrit le récit de son enfance : « L'Enfant noir » paraît en 1953 et rencontre un grand succès. Rentré en Guinée après l'indépendance, il entre en conflit avec le régime de Sékou Touré et doit s'exiler au Sénégal. Il y consacre ses dernières années à recueillir la tradition des griots. Son premier livre reste l'un des plus lus de la littérature africaine.",
    startWith: "l-enfant-noir",
    otherTitles: ["Le Regard du roi (1954)", "Dramouss (1966)", "Le Maître de la parole (1978)"],
    awards: [{ name: "Prix Charles-Veillon", year: 1954 }],
  }),
  auteur({
    slug: "tierno-monenembo",
    name: "Tierno Monénembo",
    birthYear: 1947,
    deathYear: null,
    countryCode: "GN",
    bio: "Tierno Monénembo, de son vrai nom Thierno Saïdou Diallo, est né à Porédaka, dans le Fouta-Djalon. Il fuit la dictature de Sékou Touré en 1969, passe par le Sénégal et la Côte d'Ivoire, puis étudie la biochimie en France. Son premier roman paraît en 1979. Son œuvre, souvent ironique, raconte l'exil, les dictatures et l'histoire des Peuls. Il reçoit le prix Renaudot en 2008 pour « Le Roi de Kahel ».",
    startWith: "le-roi-de-kahel",
    otherTitles: ["Les Crapauds-brousse (1979)", "L'Aîné des orphelins (2000)", "Peuls (2004)", "Le Terroriste noir (2012)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1986 },
      { name: "Prix Renaudot", year: 2008 },
      { name: "Prix Ahmadou-Kourouma", year: 2013 },
    ],
  }),
  auteur({
    slug: "djibril-tamsir-niane",
    name: "Djibril Tamsir Niane",
    birthYear: 1932,
    deathYear: 2021,
    countryCode: "GN",
    bio: "Djibril Tamsir Niane est né à Conakry. Historien formé à Dakar et à Bordeaux, il se consacre à l'histoire de l'empire du Mali et aux traditions orales mandingues. En 1960, il publie « Soundjata ou l'Épopée mandingue », transcription en français du récit d'un griot, qui fait connaître cette épopée dans le monde entier. Il est aussi auteur de pièces de théâtre et d'ouvrages d'histoire. Il a enseigné en Guinée et au Sénégal et participé à l'« Histoire générale de l'Afrique » de l'Unesco.",
    startWith: "soundjata-ou-l-epopee-mandingue",
    otherTitles: ["Sikasso ou la dernière citadelle (1971)", "Méry (1975)", "Contes d'hier et d'aujourd'hui (1985)"],
    awards: [],
  }),

  // ------------------------------------------------------------------ Côte d'Ivoire
  auteur({
    slug: "ahmadou-kourouma",
    name: "Ahmadou Kourouma",
    birthYear: 1927,
    deathYear: 2003,
    countryCode: "CI",
    bio: "Né en Côte d'Ivoire dans une famille malinké, Ahmadou Kourouma est enrôlé comme tirailleur en Indochine, puis fait des études de mathématiques et d'actuariat en France. Son premier roman, « Les Soleils des indépendances », refusé en France, paraît d'abord au Canada en 1968 et bouleverse la manière d'écrire le français en Afrique. Opposant au régime, il vit longtemps en exil et publie peu, mais chacun de ses livres fait date. « Allah n'est pas obligé » reçoit le prix Renaudot en 2000. Il meurt en 2003 en laissant un roman inachevé.",
    startWith: "allah-n-est-pas-oblige",
    otherTitles: ["Monnè, outrages et défis (1990)", "En attendant le vote des bêtes sauvages (1998)", "Quand on refuse on dit non (2004)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1990 },
      { name: "Prix du Livre Inter", year: 1999 },
      { name: "Prix Renaudot", year: 2000 },
      { name: "Prix Goncourt des lycéens", year: 2000 },
    ],
  }),
  auteur({
    slug: "veronique-tadjo",
    name: "Véronique Tadjo",
    birthYear: 1955,
    deathYear: null,
    countryCode: "CI",
    bio: "Née à Paris d'un père ivoirien et d'une mère française, Véronique Tadjo grandit à Abidjan. Après des études d'anglais et de civilisation africaine-américaine, elle enseigne à l'université d'Abidjan, puis vit au Kenya, en Afrique du Sud et à Londres. Poétesse, romancière et autrice de livres pour la jeunesse qu'elle illustre elle-même, elle mêle volontiers les genres. Elle a notamment écrit sur le génocide des Tutsi au Rwanda et sur l'épidémie d'Ebola. « Reine Pokou » reçoit le Grand prix littéraire d'Afrique noire en 2005.",
    startWith: "reine-pokou",
    otherTitles: ["À vol d'oiseau (1986)", "L'Ombre d'Imana (2000)", "Loin de mon père (2010)", "En compagnie des hommes (2017)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2005 },
      { name: "Prix Ahmadou-Kourouma", year: 2025 },
    ],
  }),
  auteur({
    slug: "bernard-dadie",
    name: "Bernard Dadié",
    birthYear: 1916,
    deathYear: 2019,
    countryCode: "CI",
    bio: "Né à Assinie, Bernard Dadié étudie à l'école William-Ponty au Sénégal, puis travaille à l'Institut français d'Afrique noire à Dakar. Militant anticolonialiste, il est emprisonné plus d'un an à la fin des années 1940. Poète, conteur, romancier, auteur de théâtre et de chroniques de voyage, il signe une œuvre abondante et variée. Après l'indépendance, il devient ministre de la Culture de Côte d'Ivoire. Mort à 103 ans, il est considéré comme le père de la littérature ivoirienne.",
    startWith: "climbie",
    otherTitles: ["Un Nègre à Paris (1959)", "Patron de New York (1964)", "Béatrice du Congo (1970)", "Monsieur Thôgô-gnini (1970)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1965 }],
  }),
  auteur({
    slug: "gauz",
    name: "Gauz",
    birthYear: 1971,
    deathYear: null,
    countryCode: "CI",
    bio: "Gauz, de son vrai nom Armand Patrick Gbaka-Brédé, est né à Abidjan. Diplômé en biochimie, il arrive en France dans les années 1990 et vit un temps sans papiers, enchaînant les petits boulots, dont celui de vigile. Il est aussi photographe, documentariste et journaliste. Son premier roman, « Debout-payé », publié en 2014, est un succès inattendu. Ses livres suivants revisitent avec le même humour l'histoire coloniale et la vie à Abidjan.",
    startWith: "debout-paye",
    otherTitles: ["Camarade Papa (2018)", "Black Manoo (2020)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 2018 }],
  }),

  // ------------------------------------------------------------------ Mauritanie
  auteur({
    slug: "mbarek-ould-beyrouk",
    name: "Mbarek Ould Beyrouk",
    birthYear: 1957,
    deathYear: null,
    countryCode: "MR",
    bio: "Né à Atar, dans le nord de la Mauritanie, Mbarek Ould Beyrouk étudie le droit au Maroc, puis devient journaliste. Il fonde l'un des premiers journaux indépendants du pays et dirige plus tard la presse publique. Il publie son premier roman en 2006 et devient la grande voix francophone de la littérature mauritanienne. Ses livres racontent le désert, la société nomade et la confrontation avec la ville moderne. « Le Tambour des larmes » reçoit le prix Ahmadou-Kourouma en 2016.",
    startWith: "le-tambour-des-larmes",
    otherTitles: ["Et le ciel a oublié de pleuvoir (2006)", "Le Griot de l'émir (2013)", "Je suis seul (2018)"],
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2016 }],
  }),

  // ------------------------------------------------------------------ Burkina Faso
  auteur({
    slug: "nazi-boni",
    name: "Nazi Boni",
    birthYear: 1912,
    deathYear: 1969,
    countryCode: "BF",
    bio: "Né à Bwan, dans le pays bwa, à l'ouest de l'actuel Burkina Faso, Nazi Boni est formé à l'école William-Ponty et devient instituteur. Il entre en politique après la Seconde Guerre mondiale et siège comme député de la Haute-Volta à l'Assemblée nationale française. Opposant au premier président voltaïque, il s'exile après l'indépendance. En 1962 paraît « Crépuscule des temps anciens », premier roman de l'histoire du pays. Il meurt dans un accident de la route en 1969.",
    startWith: "crepuscule-des-temps-anciens",
    otherTitles: ["Histoire synthétique de l'Afrique résistante (1971)"],
    awards: [],
  }),

  // ------------------------------------------------------------------ Bénin
  auteur({
    slug: "olympe-bhely-quenum",
    name: "Olympe Bhêly-Quenum",
    birthYear: 1926,
    deathYear: null,
    countryCode: "BJ",
    bio: "Né à Ouidah, au Dahomey, l'actuel Bénin, Olympe Bhêly-Quenum part en France après la guerre pour faire des études de lettres et de sociologie. Il enseigne, puis devient journaliste et dirige la revue « L'Afrique actuelle ». Il travaille ensuite longtemps à l'Unesco. Son premier roman, « Un piège sans fin », paraît en 1960 et devient un classique de la littérature béninoise. Son œuvre mêle souvent réalisme et fantastique.",
    startWith: "un-piege-sans-fin",
    otherTitles: ["Le Chant du lac (1965)", "L'Initié (1979)"],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1966 }],
  }),

  // ------------------------------------------------------------------ Togo
  auteur({
    slug: "sami-tchak",
    name: "Sami Tchak",
    birthYear: 1960,
    deathYear: null,
    countryCode: "TG",
    bio: "Sami Tchak, de son vrai nom Sadamba Tcha-Koura, est né au Togo. Professeur de philosophie à Lomé, il s'installe en France dans les années 1980 et y soutient une thèse de sociologie. Il mène des recherches à Cuba et en Amérique latine, qui nourrissent plusieurs de ses romans. Son œuvre, souvent provocante, aborde sans tabou la sexualité, l'argent et le pouvoir. Il reçoit le Grand prix littéraire d'Afrique noire en 2004.",
    startWith: "place-des-fetes",
    otherTitles: ["Hermina (2003)", "La Fête des masques (2004)", "Le Paradis des chiots (2006)", "Al Capone le Malien (2011)"],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2004 },
      { name: "Prix Ahmadou-Kourouma", year: 2007 },
    ],
  }),
  auteur({
    slug: "kossi-efoui",
    name: "Kossi Efoui",
    birthYear: 1962,
    deathYear: null,
    countryCode: "TG",
    bio: "Né au Togo, Kossi Efoui étudie la philosophie à l'université de Lomé et s'engage dans le mouvement étudiant contre le régime d'Eyadéma, ce qui le pousse à l'exil. Installé en France, il se fait d'abord connaître comme dramaturge : sa pièce Le Carrefour reçoit le grand prix du concours théâtral de RFI en 1989. Il publie ensuite des romans au Seuil, à la langue très travaillée, qui tournent autour de la mémoire, de la violence et du théâtre. Solo d'un revenant reçoit en 2009 le prix Ahmadou-Kourouma et le prix des Cinq Continents de la Francophonie. Il est l'une des voix les plus singulières de la littérature africaine d'aujourd'hui.",
    startWith: "solo-d-un-revenant",
    otherTitles: [
      "La Polka (1998)",
      "La Fabrique de cérémonies (2001)",
      "L'Ombre des choses à venir (2011)",
      "Cantique de l'acacia (2017)",
      "Une magie ordinaire (2023)",
    ],
    awards: [
      { name: "Prix Ahmadou-Kourouma", year: 2009 },
      { name: "Prix des Cinq Continents de la Francophonie", year: 2009 },
    ],
  }),
];
