import type { Author } from "../types";

const base = { photo: null, photoCredit: null };

export const auteursCentreEstSud: Author[] = [
  // ------------------------------------------------------------------ Cameroun
  {
    ...base,
    slug: "mongo-beti",
    name: "Mongo Beti",
    birthYear: 1932,
    deathYear: 2001,
    countryCode: "CM",
    origin: null,
    bio: "De son vrai nom Alexandre Biyidi Awala, Mongo Beti est né dans le sud du Cameroun. Parti étudier en France, il y devient professeur de lettres et publie dans les années 1950 des romans qui dénoncent avec ironie la colonisation et les missions. Son essai Main basse sur le Cameroun, qui s'en prend au régime d'Ahidjo et à la politique française, est saisi dès sa sortie. Exilé pendant plus de trente ans, il fonde la revue Peuples noirs, Peuples africains. Rentré au Cameroun dans les années 1990, il y ouvre une librairie à Yaoundé et reste jusqu'au bout une voix libre et combative.",
    startWith: "le-pauvre-christ-de-bomba",
    otherTitles: [
      "Ville cruelle (1954)",
      "Mission terminée (1957)",
      "Le Roi miraculé (1958)",
      "Main basse sur le Cameroun (1972)",
      "Remember Ruben (1974)",
    ],
    awards: [],
  },
  {
    ...base,
    slug: "ferdinand-oyono",
    name: "Ferdinand Oyono",
    birthYear: 1929,
    deathYear: 2010,
    countryCode: "CM",
    origin: null,
    bio: "Né dans le sud du Cameroun, Ferdinand Oyono fait ses études au Cameroun puis en France. En 1956, il publie coup sur coup deux romans qui font date, Une vie de boy et Le Vieux Nègre et la médaille, deux satires féroces de la société coloniale. Après un troisième roman, il se consacre à la diplomatie puis à la politique. Il est ambassadeur dans plusieurs pays et occupe ensuite de nombreux postes de ministre au Cameroun. Ses romans, courts et mordants, restent parmi les plus lus de la littérature africaine.",
    startWith: "une-vie-de-boy",
    otherTitles: ["Le Vieux Nègre et la médaille (1956)", "Chemin d'Europe (1960)"],
    awards: [],
  },
  {
    ...base,
    slug: "calixthe-beyala",
    name: "Calixthe Beyala",
    birthYear: 1961,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Née à Douala, Calixthe Beyala grandit dans un quartier pauvre de la ville avant de partir pour la France. Elle publie son premier roman, C'est le soleil qui m'a brûlée, en 1987. Ses livres donnent la parole à des femmes africaines, à Douala comme dans le quartier parisien de Belleville, avec une langue crue, drôle et colorée. Le Petit Prince de Belleville et Maman a un amant lui valent un large public. En 1996, Les Honneurs perdus reçoit le Grand prix du roman de l'Académie française.",
    startWith: "les-honneurs-perdus",
    otherTitles: [
      "C'est le soleil qui m'a brûlée (1987)",
      "Tu t'appelleras Tanga (1988)",
      "Le Petit Prince de Belleville (1992)",
      "Maman a un amant (1993)",
    ],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1994 },
      { name: "Grand prix du roman de l'Académie française", year: 1996 },
    ],
  },
  {
    ...base,
    slug: "leonora-miano",
    name: "Léonora Miano",
    birthYear: 1973,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Née à Douala, Léonora Miano s'installe en France à la fin de son adolescence pour y étudier les lettres. Son premier roman, L'Intérieur de la nuit, paraît en 2005 et la révèle aussitôt. Son œuvre explore les mémoires africaines et afro-descendantes, en particulier la traite atlantique et ses blessures. Elle a reçu le prix Goncourt des lycéens pour Contours du jour qui vient, puis le prix Femina pour La Saison de l'ombre. Romancière, dramaturge et essayiste, elle est l'une des voix majeures de la littérature francophone d'aujourd'hui.",
    startWith: "la-saison-de-l-ombre",
    otherTitles: [
      "L'Intérieur de la nuit (2005)",
      "Contours du jour qui vient (2006)",
      "Crépuscule du tourment (2016)",
      "Rouge impératrice (2019)",
    ],
    awards: [
      { name: "Prix Goncourt des lycéens", year: 2006 },
      { name: "Grand prix littéraire d'Afrique noire", year: 2011 },
      { name: "Prix Femina", year: 2013 },
    ],
  },
  {
    ...base,
    slug: "djaili-amadou-amal",
    name: "Djaïli Amadou Amal",
    birthYear: 1975,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Djaïli Amadou Amal est née dans l'Extrême-Nord du Cameroun, dans une famille peule. Mariée très jeune, elle a elle-même connu la polygamie et puise dans cette expérience la matière de ses romans. Dès Walaande, en 2010, elle raconte la condition des femmes du Sahel, les mariages forcés et les violences conjugales. Avec Les Impatientes, elle remporte le prix Goncourt des lycéens 2020 et touche un très large public. Elle mène aussi un combat militant pour l'éducation des filles à travers son association.",
    startWith: "les-impatientes",
    otherTitles: [
      "Walaande, l'art de partager un mari (2010)",
      "Mistiriijo, la mangeuse d'âmes (2013)",
      "Cœur du Sahel (2022)",
    ],
    awards: [{ name: "Prix Goncourt des lycéens", year: 2020 }],
  },
  {
    ...base,
    slug: "patrice-nganang",
    name: "Patrice Nganang",
    birthYear: 1970,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Né à Yaoundé, Patrice Nganang fait des études au Cameroun puis en Allemagne, avant de devenir professeur de littérature aux États-Unis. Il se fait connaître avec Temps de chien, où un chien observe la vie d'un quartier populaire de Yaoundé. Il consacre ensuite une grande fresque romanesque à l'histoire du Cameroun, de la colonisation allemande à la guerre d'indépendance. Poète et essayiste, il prend souvent position contre le pouvoir camerounais. En 2017, il est arrêté au Cameroun puis expulsé du pays.",
    startWith: "temps-de-chien",
    otherTitles: [
      "La Promesse des fleurs (1997)",
      "Mont Plaisant (2010)",
      "La Saison des prunes (2013)",
      "Empreintes de crabe (2018)",
    ],
    awards: [
      { name: "Prix Marguerite-Yourcenar", year: 2001 },
      { name: "Grand prix littéraire d'Afrique noire", year: 2002 },
    ],
  },
  {
    ...base,
    slug: "hemley-boum",
    name: "Hemley Boum",
    birthYear: 1973,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Née à Douala, Hemley Boum étudie l'anthropologie à Yaoundé avant de poursuivre ses études en France. Elle publie son premier roman, Le Clan des femmes, en 2010. Avec Les Maquisards, elle ressuscite la guerre d'indépendance menée en pays bassa, un épisode longtemps occulté de l'histoire camerounaise. Ses romans mêlent grande histoire et destins intimes, en donnant une place centrale aux femmes. Le Rêve du pêcheur, paru en 2024, a confirmé sa place parmi les grandes romancières africaines d'aujourd'hui.",
    startWith: "les-maquisards",
    otherTitles: [
      "Le Clan des femmes (2010)",
      "Si d'aimer (2012)",
      "Les jours viennent et passent (2019)",
      "Le Rêve du pêcheur (2024)",
    ],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2015 },
      { name: "Prix Ahmadou-Kourouma", year: 2020 },
      { name: "Grand prix littéraire d'Afrique noire", year: 2024 },
      { name: "Prix des Cinq Continents de la Francophonie", year: 2025 },
    ],
  },
  {
    ...base,
    slug: "achille-mbembe",
    name: "Achille Mbembe",
    birthYear: 1957,
    deathYear: null,
    countryCode: "CM",
    origin: null,
    bio: "Né au Cameroun, Achille Mbembe est historien et philosophe. Après des études au Cameroun puis en France, il enseigne dans plusieurs universités américaines avant de s'installer en Afrique du Sud, à Johannesburg. Son livre De la postcolonie l'impose comme l'un des grands penseurs des sociétés africaines après les indépendances. Il a depuis publié de nombreux essais sur la race, la violence politique et l'avenir de l'Afrique. Ses idées, discutées dans le monde entier, ont renouvelé la réflexion sur le passé colonial.",
    startWith: "critique-de-la-raison-negre",
    otherTitles: [
      "De la postcolonie (2000)",
      "Sortir de la grande nuit (2010)",
      "Politiques de l'inimitié (2016)",
      "Brutalisme (2020)",
    ],
    awards: [],
  },

  // ------------------------------------------------------------------ Congo
  {
    ...base,
    slug: "alain-mabanckou",
    name: "Alain Mabanckou",
    birthYear: 1966,
    deathYear: null,
    countryCode: "CG",
    origin: null,
    bio: "Né à Pointe-Noire, Alain Mabanckou part en France pour étudier le droit et travaille d'abord dans une entreprise. Il commence par la poésie avant de se tourner vers le roman avec Bleu-Blanc-Rouge. Verre Cassé, en 2005, le fait connaître d'un large public, et Mémoires de porc-épic reçoit le prix Renaudot l'année suivante. Professeur de littérature en Californie, il a aussi enseigné au Collège de France. Drôle, inventif et nourri de la vie populaire congolaise, il est aujourd'hui l'un des écrivains africains les plus lus au monde.",
    startWith: "verre-casse",
    otherTitles: [
      "Bleu-Blanc-Rouge (1998)",
      "African psycho (2003)",
      "Black Bazar (2009)",
      "Demain j'aurai vingt ans (2010)",
      "Petit Piment (2015)",
    ],
    awards: [
      { name: "Prix des Cinq Continents de la Francophonie", year: 2005 },
      { name: "Prix Renaudot", year: 2006 },
    ],
  },
  {
    ...base,
    slug: "sony-labou-tansi",
    name: "Sony Labou Tansi",
    birthYear: 1947,
    deathYear: 1995,
    countryCode: "CG",
    origin: null,
    bio: "Sony Labou Tansi naît au Congo belge, près de Kinshasa, et grandit ensuite au Congo-Brazzaville, où il devient professeur. Son premier roman, La Vie et demie, fait l'effet d'un coup de tonnerre en 1979. Il y invente une langue baroque et explosive pour dire la folie des dictatures africaines. Homme de théâtre, il fonde le Rocado Zulu Théâtre, une troupe qui joue en Afrique et en Europe. Mort jeune, il reste l'une des figures les plus audacieuses de la littérature africaine.",
    startWith: "la-vie-et-demie",
    otherTitles: [
      "L'État honteux (1981)",
      "L'Anté-peuple (1983)",
      "Les Sept Solitudes de Lorsa Lopez (1985)",
    ],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1983 }],
  },
  {
    ...base,
    slug: "emmanuel-dongala",
    name: "Emmanuel Dongala",
    birthYear: 1941,
    deathYear: null,
    countryCode: "CG",
    origin: null,
    bio: "Né en Centrafrique d'un père congolais et d'une mère centrafricaine, Emmanuel Dongala grandit au Congo-Brazzaville. Chimiste de formation, il étudie aux États-Unis et en France, puis enseigne la chimie à l'université de Brazzaville. Son premier roman, Un fusil dans la main, un poème dans la poche, paraît en 1973. La guerre civile de 1997 le pousse à l'exil aux États-Unis, où il enseigne la chimie et la littérature. Ses romans racontent le Congo avec humanité, de l'histoire coloniale aux violences contemporaines.",
    startWith: "johnny-chien-mechant",
    otherTitles: [
      "Un fusil dans la main, un poème dans la poche (1973)",
      "Le Feu des origines (1987)",
      "Les Petits Garçons naissent aussi des étoiles (1998)",
      "Photo de groupe au bord du fleuve (2010)",
    ],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1988 },
      { name: "Prix Ahmadou-Kourouma", year: 2011 },
    ],
  },
  {
    ...base,
    slug: "henri-lopes",
    name: "Henri Lopes",
    birthYear: 1937,
    deathYear: 2023,
    countryCode: "CG",
    origin: null,
    bio: "Né à Léopoldville, l'actuelle Kinshasa, Henri Lopes grandit entre les deux rives du fleuve Congo avant de faire ses études en France. Rentré au Congo-Brazzaville, il y mène une carrière politique qui le conduit jusqu'au poste de Premier ministre. Il travaille ensuite à l'Unesco puis devient pendant de longues années ambassadeur du Congo en France. En parallèle, il construit une œuvre littéraire importante, de Tribaliques au Pleurer-rire. Ses romans explorent le pouvoir, le métissage et la quête des origines.",
    startWith: "le-pleurer-rire",
    otherTitles: [
      "Tribaliques (1971)",
      "Le Chercheur d'Afriques (1990)",
      "Le Lys et le Flamboyant (1997)",
      "Une enfant de Poto-Poto (2012)",
    ],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 1972 },
      { name: "Grand prix de la francophonie de l'Académie française", year: 1993 },
    ],
  },

  // ------------------------------------------------------------------ RD Congo
  {
    ...base,
    slug: "in-koli-jean-bofane",
    name: "In Koli Jean Bofane",
    birthYear: 1954,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Né à Mbandaka, dans le nord-ouest de la RD Congo, In Koli Jean Bofane s'installe en Belgique en 1993, fuyant les violences politiques. Il commence par des livres pour la jeunesse avant de publier Mathématiques congolaises, un premier roman remarqué sur la manipulation politique à Kinshasa. Congo Inc. le consacre comme l'une des voix majeures de la littérature congolaise. Ses romans, féroces et pleins d'humour, parlent de mondialisation, de pillage des ressources et de survie. Il vit à Bruxelles.",
    startWith: "congo-inc",
    otherTitles: [
      "Mathématiques congolaises (2008)",
      "La Belle de Casa (2018)",
      "Nation cannibale (2025)",
    ],
    awards: [
      { name: "Grand prix littéraire d'Afrique noire", year: 2009 },
      { name: "Grand prix du roman métis", year: 2014 },
      { name: "Prix des Cinq Continents de la Francophonie", year: 2015 },
    ],
  },
  {
    ...base,
    slug: "fiston-mwanza-mujila",
    name: "Fiston Mwanza Mujila",
    birthYear: 1981,
    deathYear: null,
    countryCode: "CD",
    origin: null,
    bio: "Né à Lubumbashi, dans le Katanga, Fiston Mwanza Mujila vit en Autriche, où il enseigne la littérature. Poète avant tout, il écrit aussi pour le théâtre et se produit souvent avec des musiciens de jazz. Son premier roman, Tram 83, est traduit dans de nombreuses langues et salué dans le monde entier. Il poursuit avec La Danse du vilain, qui se déroule entre le Zaïre de Mobutu et l'Angola. Sa prose rythmée et musicale en fait une voix à part.",
    startWith: "tram-83",
    otherTitles: ["Soleil privé de mazout (2016)", "La Danse du vilain (2020)"],
    awards: [
      { name: "Grand prix des associations littéraires", year: 2015 },
      { name: "Prix Les Afriques", year: 2021 },
    ],
  },

  // ------------------------------------------------------------------ Rwanda
  {
    ...base,
    slug: "scholastique-mukasonga",
    name: "Scholastique Mukasonga",
    birthYear: 1956,
    deathYear: null,
    countryCode: "RW",
    origin: null,
    bio: "Née au Rwanda dans une famille tutsi, Scholastique Mukasonga connaît très jeune les persécutions et la déportation dans une région reculée du pays. Elle s'exile au Burundi, puis s'installe en France dans les années 1990. Pendant le génocide de 1994, elle perd une grande partie de sa famille. Dix ans plus tard, elle commence à écrire pour garder leur mémoire, avec Inyenzi ou les Cafards. Son roman Notre-Dame du Nil reçoit le prix Renaudot en 2012.",
    startWith: "notre-dame-du-nil",
    otherTitles: [
      "Inyenzi ou les Cafards (2006)",
      "La Femme aux pieds nus (2008)",
      "Cœur tambour (2016)",
      "Kibogo est monté au ciel (2020)",
      "Sister Deborah (2022)",
    ],
    awards: [
      { name: "Prix Renaudot", year: 2012 },
      { name: "Prix Ahmadou-Kourouma", year: 2012 },
    ],
  },

  // ------------------------------------------------------------------ Burundi
  {
    ...base,
    slug: "gael-faye",
    name: "Gaël Faye",
    birthYear: 1982,
    deathYear: null,
    countryCode: "BI",
    origin: null,
    bio: "Né à Bujumbura d'un père français et d'une mère rwandaise, Gaël Faye quitte le Burundi pour la France en 1995, au moment où la guerre civile ravage le pays. Il devient d'abord rappeur et auteur-compositeur, avant de publier son premier roman, Petit pays, en 2016. Ce livre, qui raconte une enfance heurtée par la guerre, devient un immense succès et reçoit le prix Goncourt des lycéens. Installé à Kigali pendant plusieurs années, il écrit ensuite Jacaranda, prix Renaudot 2024. Son œuvre, entre musique et littérature, interroge la mémoire du génocide des Tutsi.",
    startWith: "petit-pays",
    otherTitles: [],
    awards: [
      { name: "Prix Goncourt des lycéens", year: 2016 },
      { name: "Prix Renaudot", year: 2024 },
    ],
  },

  // ------------------------------------------------------------------ Djibouti
  {
    ...base,
    slug: "abdourahman-a-waberi",
    name: "Abdourahman A. Waberi",
    birthYear: 1965,
    deathYear: null,
    countryCode: "DJ",
    origin: null,
    bio: "Né à Djibouti, Abdourahman A. Waberi part en France à la fin des années 1980 pour étudier la littérature anglaise. Il publie d'abord des nouvelles, dont Le Pays sans ombre, qui racontent son pays natal. Romancier, poète et essayiste, il manie volontiers l'ironie et la satire, comme dans Aux États-Unis d'Afrique. Il enseigne la littérature aux États-Unis, à Washington. Son œuvre fait de Djibouti, petit pays souvent ignoré, un lieu de littérature.",
    startWith: "aux-etats-unis-d-afrique",
    otherTitles: [
      "Le Pays sans ombre (1994)",
      "Cahier nomade (1996)",
      "Transit (2003)",
      "Passage des larmes (2009)",
      "La Divine Chanson (2015)",
    ],
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1996 }],
  },

  // ------------------------------------------------------------------ Maurice
  {
    ...base,
    slug: "ananda-devi",
    name: "Ananda Devi",
    birthYear: 1957,
    deathYear: null,
    countryCode: "MU",
    origin: null,
    bio: "Née à l'île Maurice dans une famille d'origine indienne, Ananda Devi publie ses premières nouvelles très jeune. Elle fait des études d'anthropologie en Angleterre, puis travaille comme traductrice. Son œuvre, abondante, explore la condition des femmes, le corps et la violence d'une société mauricienne loin des images de carte postale. Ève de ses décombres, en 2006, lui vaut une large reconnaissance. Elle vit en Suisse et est aussi poète.",
    startWith: "eve-de-ses-decombres",
    otherTitles: [
      "Le Voile de Draupadi (1993)",
      "Pagli (2001)",
      "Le Sari vert (2009)",
      "Manger l'autre (2018)",
      "Le Rire des déesses (2021)",
    ],
    awards: [{ name: "Prix des Cinq Continents de la Francophonie", year: 2006 }],
  },
  {
    ...base,
    slug: "nathacha-appanah",
    name: "Nathacha Appanah",
    birthYear: 1973,
    deathYear: null,
    countryCode: "MU",
    origin: null,
    bio: "Née à Mahébourg, sur l'île Maurice, Nathacha Appanah est d'abord journaliste avant de s'installer en France en 1998. Son premier roman, Les Rochers de Poudre d'Or, raconte l'arrivée des travailleurs indiens à Maurice au XIXᵉ siècle. Elle a ensuite vécu à Mayotte, expérience qui lui inspire Tropique de la violence. Ses romans, courts et tendus, parlent d'exil, d'enfance blessée et de violence. Elle est aujourd'hui l'une des romancières mauriciennes les plus lues.",
    startWith: "tropique-de-la-violence",
    otherTitles: [
      "Les Rochers de Poudre d'Or (2003)",
      "Le Dernier Frère (2007)",
      "En attendant demain (2015)",
      "Le Ciel par-dessus le toit (2019)",
      "Rien ne t'appartient (2021)",
    ],
    awards: [{ name: "Prix Femina des lycéens", year: 2016 }],
  },

  // ------------------------------------------------------------------ Madagascar
  {
    ...base,
    slug: "jean-joseph-rabearivelo",
    name: "Jean-Joseph Rabearivelo",
    birthYear: 1901,
    deathYear: 1937,
    countryCode: "MG",
    origin: null,
    bio: "Né à Antananarivo, Jean-Joseph Rabearivelo quitte l'école très tôt et apprend seul le français et la littérature. Correcteur dans une imprimerie, il fréquente les milieux littéraires de la capitale et écrit en français comme en malgache. Ses recueils, de Sylves à Presque-songes et Traduit de la nuit, mêlent poésie française moderne et tradition malgache. Il correspond avec de nombreux écrivains étrangers, mais rêve en vain de voyager en France. Il meurt jeune, en 1937, et est considéré comme le premier grand poète moderne de Madagascar.",
    startWith: "presque-songes",
    otherTitles: [
      "La Coupe de cendres (1924)",
      "Sylves (1927)",
      "Volumes (1928)",
      "Traduit de la nuit (1935)",
      "Chants pour Abéone (1936)",
    ],
    awards: [],
  },
  {
    ...base,
    slug: "raharimanana",
    name: "Raharimanana",
    birthYear: 1967,
    deathYear: null,
    countryCode: "MG",
    origin: null,
    bio: "Jean-Luc Raharimanana, qui signe simplement Raharimanana, est né à Antananarivo. Il se fait remarquer très jeune avec une nouvelle primée par un prix international, puis s'installe en France au début des années 1990. Romancier, poète, nouvelliste et homme de théâtre, il écrit en français et en malgache. Son œuvre revient souvent sur l'histoire coloniale de Madagascar, en particulier l'insurrection de 1947. Il a aussi fondé une compagnie de théâtre et participé à la création d'une maison d'édition.",
    startWith: "nour-1947",
    otherTitles: ["Rêves sous le linceul (1998)", "Za (2008)", "Revenir (2018)"],
    awards: [{ name: "Prix Jacques-Lacarrière", year: 2018 }],
  },

  // ------------------------------------------------------------------ Comores
  {
    ...base,
    slug: "ali-zamir",
    name: "Ali Zamir",
    birthYear: 1987,
    deathYear: null,
    countryCode: "KM",
    origin: null,
    bio: "Né à Mutsamudu, sur l'île d'Anjouan, Ali Zamir fait des études de lettres modernes au Caire. De retour aux Comores, il occupe divers emplois tout en écrivant. Son premier roman, Anguille sous roche, paru en 2016, est écrit en une seule phrase et reçoit le prix Senghor. Il publie ensuite plusieurs romans à la langue très travaillée, où la parole coule sans s'arrêter. Il vit aujourd'hui en France, à Montpellier.",
    startWith: "anguille-sous-roche",
    otherTitles: ["Mon étincelle (2017)", "Dérangé que je suis (2019)", "Jouissance (2022)"],
    awards: [
      { name: "Prix Senghor du premier roman francophone", year: 2016 },
      { name: "Prix Mandela de littérature", year: 2017 },
    ],
  },

  // ------------------------------------------------------------------ Kenya
  {
    ...base,
    slug: "ngugi-wa-thiongo",
    name: "Ngũgĩ wa Thiong'o",
    birthYear: 1938,
    deathYear: 2025,
    countryCode: "KE",
    origin: null,
    bio: "Né près de Limuru, au Kenya, Ngũgĩ wa Thiong'o grandit pendant la révolte des Mau Mau contre la colonisation britannique. Ses premiers romans, écrits en anglais, font de lui l'un des pères de la littérature d'Afrique de l'Est. Emprisonné sans procès en 1978 pour une pièce de théâtre en kikuyu, il décide ensuite d'écrire dans sa langue maternelle. Contraint à l'exil, il enseigne pendant des décennies aux États-Unis. Son essai Décoloniser l'esprit a profondément marqué la réflexion sur les langues africaines.",
    startWith: "rever-en-temps-de-guerre",
    otherTitles: [
      "Enfant, ne pleure pas (1964)",
      "Et le blé jaillira (1967)",
      "Pétales de sang (1977)",
      "Décoloniser l'esprit (1986)",
    ],
    awards: [],
  },

  // ------------------------------------------------------------------ Afrique du Sud
  {
    ...base,
    slug: "j-m-coetzee",
    name: "J. M. Coetzee",
    birthYear: 1940,
    deathYear: null,
    countryCode: "ZA",
    origin: null,
    bio: "Né au Cap dans une famille afrikaner, John Maxwell Coetzee étudie les mathématiques et la littérature, puis travaille comme programmeur en Angleterre. Il enseigne ensuite la littérature au Cap tout en construisant une œuvre sobre et exigeante. Ses romans interrogent la violence, la domination et la culpabilité dans l'Afrique du Sud de l'apartheid et d'après. Il est le premier écrivain à recevoir deux fois le Booker Prize, avant le prix Nobel de littérature en 2003. Il vit en Australie depuis le début des années 2000.",
    startWith: "disgrace",
    otherTitles: [
      "En attendant les barbares (1980)",
      "Michael K, sa vie, son temps (1983)",
      "Foe (1986)",
      "Elizabeth Costello (2003)",
    ],
    awards: [
      { name: "Booker Prize", year: 1983 },
      { name: "Booker Prize", year: 1999 },
      { name: "Prix Nobel de littérature", year: 2003 },
    ],
  },
  {
    ...base,
    slug: "nelson-mandela",
    name: "Nelson Mandela",
    birthYear: 1918,
    deathYear: 2013,
    countryCode: "ZA",
    origin: null,
    bio: "Né dans un village du Transkei, Nelson Mandela devient avocat à Johannesburg et s'engage dans le Congrès national africain (ANC) contre la ségrégation raciale. Condamné à la prison à vie en 1964, il passe vingt-sept ans en détention, en grande partie à Robben Island. Libéré en 1990, il négocie la fin de l'apartheid et reçoit le prix Nobel de la paix en 1993. L'année suivante, il devient le premier président noir de l'Afrique du Sud. Son autobiographie, commencée en prison, est l'un des grands témoignages du XXᵉ siècle.",
    startWith: "un-long-chemin-vers-la-liberte",
    otherTitles: ["Conversations avec moi-même (2010)"],
    awards: [{ name: "Prix Nobel de la paix", year: 1993 }],
  },

  // ------------------------------------------------------------------ Nigeria
  {
    ...base,
    slug: "chinua-achebe",
    name: "Chinua Achebe",
    birthYear: 1930,
    deathYear: 2013,
    countryCode: "NG",
    origin: null,
    bio: "Né à Ogidi, dans le sud-est du Nigeria, Chinua Achebe grandit dans une famille igbo convertie au christianisme. Il travaille d'abord à la radio nigériane et publie en 1958 Things Fall Apart, traduit en français sous le titre Le monde s'effondre. Ce roman, qui raconte la colonisation du point de vue africain, est devenu le livre le plus lu de la littérature africaine. Pendant la guerre du Biafra, il s'engage aux côtés de la sécession. Il a ensuite enseigné aux États-Unis et reçu le Man Booker International Prize en 2007.",
    startWith: "le-monde-s-effondre",
    otherTitles: [
      "Le Malaise (1960)",
      "La Flèche de Dieu (1964)",
      "Le Démagogue (1966)",
      "Les Termitières de la savane (1987)",
    ],
    awards: [{ name: "Man Booker International Prize", year: 2007 }],
  },
  {
    ...base,
    slug: "chimamanda-ngozi-adichie",
    name: "Chimamanda Ngozi Adichie",
    birthYear: 1977,
    deathYear: null,
    countryCode: "NG",
    origin: null,
    bio: "Née à Enugu, Chimamanda Ngozi Adichie grandit à Nsukka, sur le campus universitaire où travaillent ses parents. Elle part étudier aux États-Unis à dix-neuf ans. Son premier roman, L'Hibiscus pourpre, est remarqué, puis L'Autre Moitié du soleil, sur la guerre du Biafra, reçoit l'Orange Prize. Americanah, sur l'exil et la question raciale, en fait une star internationale. Ses conférences, dont Nous sommes tous des féministes, ont été lues et partagées dans le monde entier.",
    startWith: "l-autre-moitie-du-soleil",
    otherTitles: [
      "L'Hibiscus pourpre (2003)",
      "Autour de ton cou (2009)",
      "Americanah (2013)",
      "Nous sommes tous des féministes (2014)",
    ],
    awards: [{ name: "Orange Prize for Fiction", year: 2007 }],
  },

  // ------------------------------------------------------------------ Ghana
  {
    ...base,
    slug: "yaa-gyasi",
    name: "Yaa Gyasi",
    birthYear: 1989,
    deathYear: null,
    countryCode: "GH",
    origin: "Née à Mampong (Ghana), a grandi aux États-Unis",
    bio: "Née au Ghana, Yaa Gyasi part enfant pour les États-Unis avec sa famille et grandit en Alabama. Elle étudie la littérature à l'université Stanford, puis l'écriture à l'université de l'Iowa. Un voyage au Ghana, et la visite du fort de Cape Coast, lui inspire son premier roman, Homegoing, traduit en français sous le titre No Home. Le livre connaît un succès mondial et reçoit plusieurs prix. Elle a publié ensuite Sublime royaume, sur une famille ghanéenne installée en Alabama.",
    startWith: "no-home",
    otherTitles: ["Sublime royaume (2020)"],
    awards: [{ name: "PEN/Hemingway Award", year: 2017 }],
  },
];
