import type { Book } from "../types";

export const bandesDessinees: Book[] = [
  {
    slug: "aya-de-yopougon",
    kind: "bd",
    title: "Aya de Yopougon",
    subtitle: "Tome 1",
    contributors: [
      { role: "scenariste", name: "Marguerite Abouet", authorSlug: "marguerite-abouet" },
      { role: "dessinateur", name: "Clément Oubrerie", authorSlug: null },
    ],
    genre: "bd",
    audience: "ado",
    themes: ["ville", "famille", "femmes", "amour"],
    summary:
      "Abidjan, fin des années 1970 : la Côte d'Ivoire vit ses années de prospérité et Yopougon, quartier populaire animé, bruisse de fêtes et de ragots. Aya, dix-neuf ans, sérieuse et têtue, rêve de devenir médecin pendant que ses amies Adjoua et Bintou ne pensent qu'aux sorties du soir et aux garçons. Autour d'elles gravitent des pères volages, des mères qui veillent au grain et des prétendants plus ou moins recommandables. Ce premier tome installe une chronique de quartier pleine de vie, où les petites affaires de cœur finissent toujours par devenir l'affaire de tout le monde.",
    whyRead: [
      "Une Afrique joyeuse et quotidienne, loin des clichés de guerre et de misère.",
      "Des dialogues savoureux, truffés d'expressions ivoiriennes expliquées en fin d'album.",
      "Le point de départ d'une série culte, adaptée en film d'animation.",
    ],
    quote: null,
    year: 2005,
    originalLanguage: null,
    publisher: "Gallimard",
    pages: 112,
    isbn: "9782070669349",
    format: "album",
    awards: [{ name: "Prix du premier album, Festival d'Angoulême", year: 2006 }],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: true,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "akissi",
    kind: "bd",
    title: "Akissi",
    subtitle: "Attaque de chats",
    contributors: [
      { role: "scenariste", name: "Marguerite Abouet", authorSlug: "marguerite-abouet" },
      { role: "dessinateur", name: "Mathieu Sapin", authorSlug: null },
    ],
    genre: "bd",
    audience: "jeunesse",
    themes: ["enfance", "humour", "famille"],
    summary:
      "Akissi est une petite fille de Yopougon, à Abidjan, qui ne tient pas en place. Entre les chats du quartier, son grand frère qu'elle adore taquiner et les voisins qui n'en peuvent plus de ses idées, chaque journée tourne à l'aventure. L'album enchaîne de courtes histoires indépendantes, faciles à lire seul dès 6 ans. Marguerite Abouet y puise dans ses propres souvenirs d'enfance pour raconter les bêtises d'une héroïne aussi espiègle qu'attachante.",
    whyRead: [
      "Des histoires courtes et drôles, parfaites pour les premiers lecteurs de BD.",
      "Une héroïne ivoirienne pleine d'énergie, rare dans la BD jeunesse.",
      "Par la scénariste d'Aya de Yopougon, pour les plus jeunes.",
    ],
    quote: null,
    year: 2010,
    originalLanguage: null,
    publisher: "Gallimard Jeunesse",
    pages: null,
    isbn: "9782070628025",
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "la-vie-de-pahe",
    kind: "bd",
    title: "La Vie de Pahé",
    subtitle: "Bitam",
    contributors: [
      { role: "scenariste", name: "Pahé", authorSlug: "pahe" },
      { role: "dessinateur", name: "Pahé", authorSlug: "pahe" },
    ],
    genre: "bd",
    audience: "ado",
    themes: ["enfance", "humour", "famille", "ecole"],
    summary:
      "Le dessinateur gabonais Pahé se met lui-même en scène et remonte le fil de son enfance à Bitam, petite ville du nord du Gabon. Il y raconte avec humour la vie de famille, l'école, les copains et les mille combines d'un gamin gabonais. Derrière l'humour, c'est tout un monde qui se dessine : les rapports entre générations, la débrouille et la vie de quartier. Premier tome d'une série autobiographique, l'album a ensuite été adapté en dessin animé.",
    whyRead: [
      "Un récit d'enfance africaine drôle et tendre, raconté par celui qui l'a vécue.",
      "Un trait de caricaturiste vif, qui fait mouche à chaque page.",
      "À lire en famille : les ados comme les adultes y trouvent leur compte.",
    ],
    quote: null,
    year: 2006,
    originalLanguage: null,
    publisher: "Paquet",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "dipoula",
    kind: "bd",
    title: "Dipoula",
    subtitle: "Mbolo",
    contributors: [
      { role: "scenariste", name: "Sti", authorSlug: null },
      { role: "dessinateur", name: "Pahé", authorSlug: "pahe" },
    ],
    genre: "bd",
    audience: "jeunesse",
    themes: ["enfance", "humour", "identite"],
    summary:
      "Dipoula est un petit garçon gabonais albinos, confié dès sa naissance à un orphelinat tenu par des religieuses. Avec sa bande de copains, il enchaîne les bêtises dans de courtes scènes d'une ou deux pages. Au détour des gags, il se pose de grandes questions sur la richesse et la pauvreté, l'amitié et surtout la différence. Pahé, qui a imaginé ce personnage dès le lycée, lui donne ici son premier album.",
    whyRead: [
      "Un héros albinos qui aborde la différence avec humour et sans lourdeur.",
      "Des gags courts, idéaux pour les jeunes lecteurs.",
      "Un personnage culte de la BD gabonaise.",
    ],
    quote: null,
    year: 2008,
    originalLanguage: null,
    publisher: "Paquet",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "petit-joss",
    kind: "bd",
    title: "Petit Joss",
    subtitle: "École urbaine mixte",
    contributors: [
      { role: "scenariste", name: "Joëlle Esso", authorSlug: "joelle-esso" },
      { role: "dessinateur", name: "Joëlle Esso", authorSlug: "joelle-esso" },
    ],
    genre: "bd",
    audience: "jeunesse",
    themes: ["enfance", "ecole", "ville"],
    summary:
      "Douala, dans les années 1970, peu après l'indépendance du Cameroun. À l'école primaire Petit Joss, les élèves vivent mille petites aventures : deux bonnes élèves tentent l'école buissonnière, une bande lorgne sur le potager du directeur, une éclipse sème la panique en classe. En six histoires, Joëlle Esso mêle souvenirs et fiction pour raconter une enfance africaine heureuse et insouciante. Un album lumineux, au dessin clair et coloré, accessible dès 7 ans.",
    whyRead: [
      "Une enfance africaine joyeuse, loin des images habituelles.",
      "Six histoires courtes, faciles à lire seul ou à partager.",
      "Un regard plein de tendresse sur l'école d'autrefois à Douala.",
    ],
    quote: null,
    year: 2010,
    originalLanguage: null,
    publisher: "Dagan",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "tempete-sur-bangui",
    kind: "bd",
    title: "Tempête sur Bangui",
    subtitle: "Tome 1",
    contributors: [
      { role: "scenariste", name: "Didier Kassaï", authorSlug: "didier-kassai" },
      { role: "dessinateur", name: "Didier Kassaï", authorSlug: "didier-kassai" },
    ],
    genre: "bd",
    audience: "adulte",
    themes: ["guerre", "politique", "histoire"],
    summary:
      "Fin 2012, la rébellion de la Séléka marche sur Bangui et la capitale centrafricaine bascule dans la violence. Didier Kassaï, dessinateur installé en ville avec sa famille, raconte ce qu'il a vécu jour après jour : les rumeurs, la peur, les pillages et la difficulté de simplement survivre. Continuer à dessiner devient pour lui une manière de tenir et de témoigner. Ce premier tome, publié avec le concours d'Amnesty International, couvre la prise de pouvoir de la Séléka et les mois de chaos qui suivent.",
    whyRead: [
      "Un témoignage de l'intérieur sur une guerre dont on parle peu.",
      "Un dessin saisissant, qui rend la peur palpable.",
      "Pour comprendre la crise centrafricaine à hauteur d'homme.",
    ],
    quote: null,
    year: 2015,
    originalLanguage: null,
    publisher: "La Boîte à bulles",
    pages: 128,
    isbn: "9782849532256",
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "madame-livingstone",
    kind: "bd",
    title: "Madame Livingstone",
    subtitle: "Congo, la Grande Guerre",
    contributors: [
      { role: "scenariste", name: "Christophe Cassiau-Haurie", authorSlug: null },
      { role: "dessinateur", name: "Barly Baruti", authorSlug: "barly-baruti" },
    ],
    genre: "bd",
    audience: "adulte",
    themes: ["colonisation", "guerre", "histoire", "identite"],
    summary:
      "1915, au Congo belge, sur les rives du lac Tanganyika. Gaston Mercier, jeune aviateur belge, arrive à Albertville avec une mission : localiser et couler un navire de guerre allemand qui domine le lac. On lui adjoint un guide énigmatique, un métis qui se dit fils de l'explorateur David Livingstone et que l'on surnomme « Madame Livingstone » à cause du kilt écossais qu'il porte. Entre ces deux hommes que tout sépare naît peu à peu une amitié faite de respect. Une aventure qui éclaire un front oublié de la Première Guerre mondiale.",
    whyRead: [
      "Un pan méconnu de la Grande Guerre, vécu depuis l'Afrique.",
      "Les aquarelles de Barly Baruti, figure majeure de la BD congolaise.",
      "Un duo de personnages inattendu et attachant.",
    ],
    quote: null,
    year: 2014,
    originalLanguage: null,
    publisher: "Glénat",
    pages: 128,
    isbn: "9782723497190",
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "malamine",
    kind: "bd",
    title: "Malamine",
    subtitle: "Un Africain à Paris",
    contributors: [
      { role: "scenariste", name: "Christophe Ngalle Edimo", authorSlug: "christophe-ngalle-edimo" },
      { role: "dessinateur", name: "Simon-Pierre Mbumbo", authorSlug: "simon-pierre-mbumbo" },
    ],
    genre: "bd",
    audience: "adulte",
    themes: ["exil", "identite", "ville", "travail"],
    summary:
      "Malamine est diplômé, cultivé, et il vit à Paris. Pourtant, dans le regard des autres, il reste d'abord un Africain, assigné aux petits boulots et aux clichés. L'album suit son quotidien d'immigré, entre démarches, rencontres et humiliations ordinaires. Il dit avec justesse la colère, la frustration et le sentiment d'être étranger partout qui naissent de cette situation.",
    whyRead: [
      "Un regard lucide sur la vie des Africains diplômés en France.",
      "Un duo d'auteurs camerounais qui parle d'une expérience vécue.",
      "Une BD qui fait réfléchir sur les préjugés, sans jamais faire la leçon.",
    ],
    quote: null,
    year: 2009,
    originalLanguage: null,
    publisher: "Les Enfants Rouges",
    pages: 118,
    isbn: "9782354190224",
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "rwanda-1994",
    kind: "bd",
    title: "Rwanda 1994",
    subtitle: "Descente en enfer",
    contributors: [
      { role: "scenariste", name: "Cécile Grenier", authorSlug: null },
      { role: "scenariste", name: "Ralph", authorSlug: null },
      { role: "dessinateur", name: "Pat Masioni", authorSlug: "pat-masioni" },
    ],
    genre: "bd",
    audience: "adulte",
    themes: ["genocide", "histoire", "famille"],
    summary:
      "Avril 1994 : au Rwanda, le génocide des Tutsi commence. L'album suit Mathilde et ses enfants, pris dans l'engrenage de la violence et contraints de chercher à survivre. Les scénaristes ont passé de longs mois sur place à recueillir des témoignages, et la fiction s'appuie sur des faits réels. Le dessin de Pat Masioni, sobre et puissant, raconte beaucoup avec peu de mots.",
    whyRead: [
      "Un récit rigoureux, nourri de témoignages recueillis au Rwanda.",
      "Le dessin de Pat Masioni, grand auteur congolais publié jusqu'aux États-Unis.",
      "Pour transmettre la mémoire du génocide aux lecteurs d'aujourd'hui.",
    ],
    quote: null,
    year: 2005,
    originalLanguage: null,
    publisher: "Albin Michel",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
  {
    slug: "une-eternite-a-tanger",
    kind: "bd",
    title: "Une éternité à Tanger",
    subtitle: null,
    contributors: [
      { role: "scenariste", name: "Eyoum Ngangué", authorSlug: "eyoum-ngangue" },
      { role: "dessinateur", name: "Faustin Titi", authorSlug: "faustin-titi" },
    ],
    genre: "bd",
    audience: "adulte",
    themes: ["exil", "politique", "identite"],
    summary:
      "Gawa a quitté Gnasville, une ville imaginaire d'Afrique de l'Ouest, pour tenter sa chance en Europe. Après des milliers de kilomètres de désert, le voici à Tanger, face aux quatorze kilomètres du détroit de Gibraltar. Cette dernière étape se révèle la plus rude : passeurs sans scrupules, frontières fermées, attente et pauvreté. L'album raconte, sans misérabilisme, le parcours d'un migrant suspendu entre deux rives.",
    whyRead: [
      "Un récit de migration écrit et dessiné par deux auteurs africains.",
      "Une histoire forte, qui donne un visage aux candidats à l'exil.",
      "Un classique de la BD africaine, traduit dans plusieurs langues.",
    ],
    quote: null,
    year: 2005,
    originalLanguage: null,
    publisher: "Lai-momo",
    pages: null,
    isbn: null,
    format: "album",
    awards: [],
    amazonAsin: null,
    priceCents: null,
    cover: null,
    featured: false,
    addedAt: "2026-09-28",
    isPublished: true,
  },
];
