import type { Book } from "../types";

const base = {
  kind: "livre" as const,
  subtitle: null,
  quote: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  addedAt: "2026-09-28",
  isPublished: true,
};

export const livresCentreEstSud: Book[] = [
  // ------------------------------------------------------------------ Cameroun
  {
    ...base,
    slug: "le-pauvre-christ-de-bomba",
    title: "Le Pauvre Christ de Bomba",
    contributors: [{ role: "auteur", name: "Mongo Beti", authorSlug: "mongo-beti" }],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "spiritualite", "humour"],
    summary:
      "Dans le sud du Cameroun des années 1930, le révérend père Drumont part en tournée dans une région qui a tourné le dos à sa mission. Denis, son jeune boy, tient le journal du voyage avec une naïveté totale. Village après village, le missionnaire découvre que les Africains ne se laissent pas convertir aussi facilement qu'il l'espérait. À travers les yeux candides du narrateur, le lecteur voit ce que le prêtre refuse de voir : les liens entre la mission et l'administration coloniale.",
    whyRead: [
      "Un classique de la littérature camerounaise, jugé scandaleux à sa sortie.",
      "Un narrateur naïf qui rend la satire à la fois drôle et cruelle.",
      "Pour comprendre le rôle ambigu des missions dans la colonisation.",
    ],
    year: 1956,
    originalLanguage: null,
    publisher: "Présence Africaine",
    pages: 349,
    isbn: "9782708705685",
    format: null,
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "une-vie-de-boy",
    title: "Une vie de boy",
    contributors: [{ role: "auteur", name: "Ferdinand Oyono", authorSlug: "ferdinand-oyono" }],
    genre: "roman",
    audience: "ado",
    themes: ["colonisation", "enfance", "humour"],
    summary:
      "Toundi, un garçon de village, quitte sa famille pour vivre auprès d'un missionnaire blanc, puis devient le boy du commandant de Dangan. Il note tout dans un cahier : les repas, les réceptions, les petites manies de ses maîtres. Peu à peu, ce témoin discret en apprend beaucoup trop sur la vie privée des colons. Le journal d'un domestique devient ainsi un portrait sans pitié de la société coloniale.",
    whyRead: [
      "Un roman court et souvent étudié en classe, idéal pour commencer.",
      "L'ironie de Toundi rend visible l'absurdité du monde colonial.",
      "Un regard de l'intérieur, celui de ceux qu'on ne voyait pas.",
    ],
    year: 1956,
    originalLanguage: null,
    publisher: "Pocket",
    pages: null,
    isbn: "9782266169288",
    format: "poche",
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "les-honneurs-perdus",
    title: "Les Honneurs perdus",
    contributors: [{ role: "auteur", name: "Calixthe Beyala", authorSlug: "calixthe-beyala" }],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "ville", "humour"],
    summary:
      "Saïda Bénérafa a grandi à Couscous, un quartier pauvre de Douala, où elle vit sous l'œil de parents qui veillent sur sa virginité comme sur un trésor. À cinquante ans passés, toujours célibataire, elle décide de partir pour Paris. Elle atterrit à Belleville, chez une Africaine au franc-parler redoutable, et découvre une autre façon d'être femme. Un roman plein de verve sur l'émancipation tardive et le choc de l'exil.",
    whyRead: [
      "Une héroïne inattendue, qui choisit sa vie après cinquante ans.",
      "Une langue colorée et pleine d'humour, entre Douala et Belleville.",
      "Un livre couronné par l'Académie française.",
    ],
    year: 1996,
    originalLanguage: null,
    publisher: "J'ai lu",
    pages: null,
    isbn: "9782290049747",
    format: "poche",
    awards: [{ name: "Grand prix du roman de l'Académie française", year: 1996 }],
    featured: false,
  },
  {
    ...base,
    slug: "la-saison-de-l-ombre",
    title: "La Saison de l'ombre",
    contributors: [{ role: "auteur", name: "Léonora Miano", authorSlug: "leonora-miano" }],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "histoire", "femmes", "tradition"],
    summary:
      "Dans un village mulongo d'Afrique centrale, un incendie a éclaté une nuit et douze jeunes hommes ont disparu. Leurs mères sont mises à l'écart dans une case, comme si leur malheur pouvait contaminer les autres. L'une d'elles, Eyabe, refuse d'attendre et part à la recherche de la vérité. Le roman raconte, du point de vue de ceux qui l'ont subie, le début de la traite atlantique.",
    whyRead: [
      "La traite négrière racontée depuis l'Afrique, par les familles des disparus.",
      "Une écriture ample, presque incantatoire.",
      "Prix Femina 2013.",
    ],
    year: 2013,
    originalLanguage: null,
    publisher: "Pocket",
    pages: 246,
    isbn: "9782266248778",
    format: "poche",
    awards: [{ name: "Prix Femina", year: 2013 }],
    featured: false,
  },
  {
    ...base,
    slug: "les-impatientes",
    title: "Les Impatientes",
    contributors: [{ role: "auteur", name: "Djaïli Amadou Amal", authorSlug: "djaili-amadou-amal" }],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition", "spiritualite"],
    summary:
      "Dans le nord du Cameroun, Ramla, Hindou et Safira vivent sous la même loi : celle des familles et des maris. À chacune, on répète le même conseil, « munyal », patience. Ramla est promise à un homme déjà marié, Hindou est donnée à un cousin violent, Safira voit arriver une jeune coépouse. Le roman fait entendre tour à tour leurs trois voix, prises entre soumission et désir de liberté.",
    whyRead: [
      "Trois voix de femmes qui disent la polygamie et le mariage forcé de l'intérieur.",
      "Un roman court, direct et très fort.",
      "Prix Goncourt des lycéens 2020.",
    ],
    year: 2020,
    originalLanguage: null,
    publisher: "J'ai lu",
    pages: 288,
    isbn: "9782290252949",
    format: "poche",
    awards: [{ name: "Prix Goncourt des lycéens", year: 2020 }],
    featured: true,
  },
  {
    ...base,
    slug: "temps-de-chien",
    title: "Temps de chien",
    contributors: [{ role: "auteur", name: "Patrice Nganang", authorSlug: "patrice-nganang" }],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "humour", "politique"],
    summary:
      "Mboudjak est un chien qui vit dans un bar de Madagascar, un quartier populaire de Yaoundé. Couché au pied du comptoir de son maître Massa Yo, il écoute les clients, les disputes, les rumeurs et les colères de la rue. Il observe les hommes avec l'ambition de les comprendre, et parfois de devenir plus humain qu'eux. À travers lui, c'est tout le Cameroun des années de crise qui parle.",
    whyRead: [
      "Un narrateur à quatre pattes, drôle et lucide.",
      "Le Yaoundé populaire, sa langue et ses bars, comme si on y était.",
      "Une satire politique qui ne se prend jamais au sérieux.",
    ],
    year: 2001,
    originalLanguage: null,
    publisher: "Le Serpent à plumes (Motifs)",
    pages: 376,
    isbn: "9782842614195",
    format: "poche",
    awards: [
      { name: "Prix Marguerite-Yourcenar", year: 2001 },
      { name: "Grand prix littéraire d'Afrique noire", year: 2002 },
    ],
    featured: false,
  },
  {
    ...base,
    slug: "les-maquisards",
    title: "Les Maquisards",
    contributors: [{ role: "auteur", name: "Hemley Boum", authorSlug: "hemley-boum" }],
    genre: "roman",
    audience: "adulte",
    themes: ["independances", "histoire", "famille", "femmes"],
    summary:
      "En pays bassa, dans le sud du Cameroun, plusieurs familles sont prises dans la lutte pour l'indépendance menée par l'UPC et son chef Ruben Um Nyobè. Le roman suit leurs membres sur plusieurs générations, des maquis de la forêt aux villes coloniales. Les femmes y tiennent une place centrale : elles nourrissent, cachent, transmettent et combattent. Une grande fresque sur une guerre longtemps passée sous silence.",
    whyRead: [
      "Pour découvrir une page méconnue de l'histoire du Cameroun.",
      "Une saga familiale riche, portée par des personnages féminins forts.",
      "Grand prix littéraire d'Afrique noire.",
    ],
    year: 2015,
    originalLanguage: null,
    publisher: "Folio",
    pages: 400,
    isbn: "9782073133915",
    format: "grand-format",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 2015 }],
    featured: false,
  },
  {
    ...base,
    slug: "critique-de-la-raison-negre",
    title: "Critique de la raison nègre",
    contributors: [{ role: "auteur", name: "Achille Mbembe", authorSlug: "achille-mbembe" }],
    genre: "essai",
    audience: "adulte",
    themes: ["esclavage", "colonisation", "identite", "histoire"],
    summary:
      "Comment le mot « nègre » a-t-il été inventé, et à quoi a-t-il servi ? Achille Mbembe retrace l'histoire de cette catégorie, de la traite atlantique à la colonisation, puis à nos sociétés mondialisées. Il montre comment elle a permis d'exploiter des êtres humains, mais aussi comment les Noirs s'en sont emparés pour se défendre et s'affirmer. L'essai se demande enfin ce que ce passé dit du monde qui vient.",
    whyRead: [
      "Un essai majeur d'un des grands penseurs africains d'aujourd'hui.",
      "Pour relier l'histoire de l'esclavage aux débats actuels.",
      "Exigeant mais éclairant, à lire par chapitres.",
    ],
    year: 2013,
    originalLanguage: null,
    publisher: "La Découverte",
    pages: null,
    isbn: "9782707187932",
    format: "poche",
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ Congo
  {
    ...base,
    slug: "verre-casse",
    title: "Verre Cassé",
    contributors: [{ role: "auteur", name: "Alain Mabanckou", authorSlug: "alain-mabanckou" }],
    genre: "roman",
    audience: "adulte",
    themes: ["humour", "ville", "politique"],
    summary:
      "Au Crédit a voyagé, un bar de Pointe-Noire, le patron confie un cahier à un vieil habitué surnommé Verre Cassé. Il lui demande d'y consigner la mémoire des lieux. Ancien instituteur porté sur le vin rouge, Verre Cassé raconte alors les clients, leurs vies ratées et leurs histoires extravagantes. Le tout en une longue phrase presque sans point, truffée de clins d'œil aux grands livres du monde entier.",
    whyRead: [
      "Un roman drôle et virtuose, sans aucun point final avant la fin.",
      "Des dizaines de titres de livres cachés dans le texte, à retrouver.",
      "Le livre qui a fait connaître Mabanckou au grand public.",
    ],
    year: 2005,
    originalLanguage: null,
    publisher: "Points",
    pages: 264,
    isbn: "9782757864500",
    format: "poche",
    awards: [{ name: "Prix des Cinq Continents de la Francophonie", year: 2005 }],
    featured: true,
  },
  {
    ...base,
    slug: "memoires-de-porc-epic",
    title: "Mémoires de porc-épic",
    contributors: [{ role: "auteur", name: "Alain Mabanckou", authorSlug: "alain-mabanckou" }],
    genre: "roman",
    audience: "adulte",
    themes: ["contes", "humour", "tradition"],
    summary:
      "Selon une croyance du Congo, chaque humain aurait un double animal. Le narrateur est l'un de ces doubles : un porc-épic lié depuis l'enfance à un homme nommé Kibandi. Réfugié au pied d'un baobab, il se confie à l'arbre et raconte les missions nocturnes que son maître lui a confiées. Un conte noir et drôle, dans la même veine que Verre Cassé.",
    whyRead: [
      "Un narrateur animal, entre fable et roman noir.",
      "Les croyances du Congo racontées avec humour.",
      "Prix Renaudot 2006.",
    ],
    year: 2006,
    originalLanguage: null,
    publisher: "Points",
    pages: 228,
    isbn: "9782757805190",
    format: "poche",
    awards: [{ name: "Prix Renaudot", year: 2006 }],
    featured: false,
  },
  {
    ...base,
    slug: "la-vie-et-demie",
    title: "La Vie et demie",
    contributors: [{ role: "auteur", name: "Sony Labou Tansi", authorSlug: "sony-labou-tansi" }],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "guerre", "humour"],
    summary:
      "Dans la Katamalanasie, un pays imaginaire d'Afrique, le Guide Providentiel fait exécuter Martial, un opposant. Mais Martial refuse de mourir tout à fait et revient hanter le dictateur et sa descendance. Sa fille Chaïdana entre alors dans une vengeance qui traversera plusieurs générations de tyrans. Un roman baroque, violent et parfois burlesque sur la folie du pouvoir absolu.",
    whyRead: [
      "Un chef-d'œuvre de la littérature africaine sur les dictatures.",
      "Une langue inventive et explosive, qui ne ressemble à aucune autre.",
      "Un livre qui fait rire et frémir à la fois.",
    ],
    year: 1979,
    originalLanguage: null,
    publisher: "Points",
    pages: 176,
    isbn: "9782757894477",
    format: "poche",
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "johnny-chien-mechant",
    title: "Johnny chien méchant",
    contributors: [{ role: "auteur", name: "Emmanuel Dongala", authorSlug: "emmanuel-dongala" }],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "enfance", "ville"],
    summary:
      "Une guerre civile éclate dans une capitale d'Afrique. Deux adolescents racontent tour à tour ce qu'ils vivent. Johnny, seize ans, s'est engagé dans une milice et se fait appeler « Chien Méchant » ; il pille et tue, persuadé d'être un intellectuel. Laokolé, du même âge, tente de fuir la ville avec sa mère infirme et son petit frère. Leurs deux récits dessinent le visage des enfants pris dans la guerre.",
    whyRead: [
      "Deux voix d'adolescents, deux façons de traverser la guerre.",
      "Un roman fort sur les enfants soldats, adapté au cinéma (Johnny Mad Dog).",
      "Une héroïne courageuse qu'on n'oublie pas.",
    ],
    year: 2002,
    originalLanguage: null,
    publisher: "Actes Sud (Babel)",
    pages: 376,
    isbn: "9782330079192",
    format: null,
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "le-pleurer-rire",
    title: "Le Pleurer-rire",
    contributors: [{ role: "auteur", name: "Henri Lopes", authorSlug: "henri-lopes" }],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "independances"],
    summary:
      "Dans un pays africain sans nom, un coup d'État porte au pouvoir Bwakamabé Na Sakkadé, dit « Tonton ». Le narrateur devient son maître d'hôtel et assiste, de très près, aux caprices, aux fêtes et aux colères du nouveau chef. Son récit est entrecoupé des remarques d'un autre personnage, qui commente et conteste ce qu'il écrit. Une satire des dictatures post-indépendance, où l'on rit pour ne pas pleurer.",
    whyRead: [
      "Un classique du roman africain sur le pouvoir, drôle et grinçant.",
      "Une construction originale, avec un récit qui se discute lui-même.",
      "Un auteur qui a connu le pouvoir de l'intérieur.",
    ],
    year: 1982,
    originalLanguage: null,
    publisher: "Présence Africaine",
    pages: null,
    isbn: "9782708706293",
    format: null,
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ RD Congo
  {
    ...base,
    slug: "congo-inc",
    title: "Congo Inc.",
    subtitle: "Le testament de Bismarck",
    contributors: [{ role: "auteur", name: "In Koli Jean Bofane", authorSlug: "in-koli-jean-bofane" }],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "politique", "humour", "guerre"],
    summary:
      "Isookanga, un jeune Pygmée ekonda, rêve de mondialisation et passe ses journées sur un jeu en ligne. Il quitte son village de la forêt pour Kinshasa, bien décidé à faire fortune. Dans la capitale, il croise des enfants des rues, un Chinois en situation irrégulière, des militaires et des profiteurs de toutes sortes. Un roman à la fois hilarant et terrible sur le pillage des richesses du Congo.",
    whyRead: [
      "Kinshasa dans toute sa démesure, racontée avec un humour ravageur.",
      "Pour comprendre comment la mondialisation se joue au Congo.",
      "Grand prix du roman métis et prix des Cinq Continents.",
    ],
    year: 2014,
    originalLanguage: null,
    publisher: "Actes Sud (Babel)",
    pages: null,
    isbn: "9782330058876",
    format: "poche",
    awards: [
      { name: "Grand prix du roman métis", year: 2014 },
      { name: "Prix des Cinq Continents de la Francophonie", year: 2015 },
    ],
    featured: false,
  },
  {
    ...base,
    slug: "tram-83",
    title: "Tram 83",
    contributors: [{ role: "auteur", name: "Fiston Mwanza Mujila", authorSlug: "fiston-mwanza-mujila" }],
    genre: "roman",
    audience: "adulte",
    themes: ["ville", "travail", "politique"],
    summary:
      "Dans une ville minière qui a fait sécession, tout le monde finit au Tram 83, une boîte de nuit ouverte jour et nuit. Lucien, écrivain qui a fui la censure, y retrouve Requiem, un ami d'enfance devenu trafiquant. Autour d'eux gravitent creuseurs, touristes, étudiants et chercheurs de fortune venus du monde entier. Un roman écrit comme un morceau de jazz, au rythme effréné.",
    whyRead: [
      "Une écriture musicale, pensée comme une improvisation de jazz.",
      "Le monde des mines et de l'argent facile, vu de l'intérieur d'un bar.",
      "Un premier roman remarqué dans le monde entier.",
    ],
    year: 2014,
    originalLanguage: null,
    publisher: "Métailié",
    pages: null,
    isbn: "9782864249597",
    format: "grand-format",
    awards: [{ name: "Grand prix des associations littéraires", year: 2015 }],
    featured: false,
  },

  // ------------------------------------------------------------------ Rwanda
  {
    ...base,
    slug: "notre-dame-du-nil",
    title: "Notre-Dame du Nil",
    contributors: [{ role: "auteur", name: "Scholastique Mukasonga", authorSlug: "scholastique-mukasonga" }],
    genre: "roman",
    audience: "adulte",
    themes: ["genocide", "ecole", "femmes", "histoire"],
    summary:
      "Au début des années 1970, le lycée Notre-Dame du Nil accueille, sur une crête proche des sources du fleuve, les filles de l'élite rwandaise. Les élèves y apprennent les bonnes manières et la foi catholique, loin du monde. Mais un quota limite le nombre de lycéennes tutsi, et les tensions du pays s'invitent dans les dortoirs. Un huis clos qui montre comment la haine se prépare, bien avant le génocide.",
    whyRead: [
      "Pour comprendre les racines du génocide des Tutsi au Rwanda.",
      "Un huis clos entre adolescentes, tendu et captivant.",
      "Prix Renaudot 2012.",
    ],
    year: 2012,
    originalLanguage: null,
    publisher: "Folio",
    pages: null,
    isbn: "9782070456314",
    format: "poche",
    awards: [
      { name: "Prix Renaudot", year: 2012 },
      { name: "Prix Ahmadou-Kourouma", year: 2012 },
    ],
    featured: false,
  },

  // ------------------------------------------------------------------ Burundi
  {
    ...base,
    slug: "petit-pays",
    title: "Petit pays",
    contributors: [{ role: "auteur", name: "Gaël Faye", authorSlug: "gael-faye" }],
    genre: "roman",
    audience: "ado",
    themes: ["enfance", "guerre", "genocide", "famille"],
    summary:
      "Gabriel, dix ans, vit à Bujumbura avec son père français, sa mère rwandaise et sa petite sœur. Avec ses copains de l'impasse, il passe ses journées à voler des mangues et à faire les quatre cents coups. Mais en 1993, le Burundi bascule dans la violence, et le génocide des Tutsi se prépare au Rwanda voisin. Le paradis de l'enfance commence à se fissurer.",
    whyRead: [
      "Un premier roman bouleversant, lu par des millions de lecteurs.",
      "L'enfance et la guerre racontées à hauteur d'enfant.",
      "Prix Goncourt des lycéens 2016.",
    ],
    year: 2016,
    originalLanguage: null,
    publisher: "Le Livre de Poche",
    pages: null,
    isbn: "9782253070443",
    format: "poche",
    awards: [
      { name: "Prix Goncourt des lycéens", year: 2016 },
      { name: "Prix du roman Fnac", year: 2016 },
    ],
    featured: true,
  },
  {
    ...base,
    slug: "jacaranda",
    title: "Jacaranda",
    contributors: [{ role: "auteur", name: "Gaël Faye", authorSlug: "gael-faye" }],
    genre: "roman",
    audience: "adulte",
    themes: ["genocide", "famille", "identite", "histoire"],
    summary:
      "Milan grandit à Versailles, fils d'une mère rwandaise qui ne dit rien de son pays. En 1994, un jeune garçon blessé arrive du Rwanda dans leur maison, et le silence familial se lézarde. Devenu adulte, Milan multiplie les séjours à Kigali, où il découvre une famille, une ville et un pays qui se reconstruisent. Le roman suit plusieurs générations, entre mémoire du génocide et désir de vivre.",
    whyRead: [
      "Un grand roman sur le Rwanda d'après, et sur ce qu'on transmet.",
      "Des personnages attachants sur trente ans d'histoire.",
      "Prix Renaudot 2024.",
    ],
    year: 2024,
    originalLanguage: null,
    publisher: "Le Livre de Poche",
    pages: 288,
    isbn: "9782253252030",
    format: "poche",
    awards: [{ name: "Prix Renaudot", year: 2024 }],
    featured: false,
  },

  // ------------------------------------------------------------------ Djibouti
  {
    ...base,
    slug: "aux-etats-unis-d-afrique",
    title: "Aux États-Unis d'Afrique",
    contributors: [{ role: "auteur", name: "Abdourahman A. Waberi", authorSlug: "abdourahman-a-waberi" }],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "humour", "identite", "politique"],
    summary:
      "Et si le monde était à l'envers ? Dans ce roman, l'Afrique est riche et unie, tandis que l'Europe et l'Amérique sont ravagées par la misère et les guerres. Des migrants suisses ou français tentent de rejoindre les États-Unis d'Afrique au péril de leur vie. Maya, une jeune femme adoptée, part en quête de ses origines dans une France dévastée. Une fable satirique qui renverse tous nos clichés.",
    whyRead: [
      "Une idée géniale : inverser les rôles entre Nord et Sud.",
      "Une satire drôle qui fait réfléchir sur les migrations.",
      "Un roman court, à lire d'une traite.",
    ],
    year: 2006,
    originalLanguage: null,
    publisher: "Actes Sud (Babel)",
    pages: 192,
    isbn: "9782742775170",
    format: "poche",
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ Maurice
  {
    ...base,
    slug: "eve-de-ses-decombres",
    title: "Ève de ses décombres",
    contributors: [{ role: "auteur", name: "Ananda Devi", authorSlug: "ananda-devi" }],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "ville", "enfance"],
    summary:
      "À Troumaron, un quartier pauvre de Port-Louis, loin des plages des cartes postales, quatre adolescents cherchent à s'en sortir. Ève, dix-sept ans, n'a que son corps pour monnaie d'échange. Savita, son amie, veille sur elle ; Sad, amoureux d'Ève, écrit des poèmes ; Clélio fulmine contre tout. Leurs quatre voix se relaient pour dire la violence du quotidien et l'envie de s'en échapper.",
    whyRead: [
      "L'île Maurice loin des clichés touristiques.",
      "Quatre voix d'adolescents, rageuses et poétiques.",
      "Prix des Cinq Continents de la Francophonie 2006.",
    ],
    year: 2006,
    originalLanguage: null,
    publisher: "Gallimard",
    pages: 160,
    isbn: "9782070776184",
    format: "grand-format",
    awards: [{ name: "Prix des Cinq Continents de la Francophonie", year: 2006 }],
    featured: false,
  },
  {
    ...base,
    slug: "tropique-de-la-violence",
    title: "Tropique de la violence",
    contributors: [{ role: "auteur", name: "Nathacha Appanah", authorSlug: "nathacha-appanah" }],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "enfance", "ville"],
    summary:
      "À Mayotte, Marie, une infirmière venue de métropole, adopte le bébé qu'une jeune migrante comorienne lui a laissé. Elle l'appelle Moïse. À l'adolescence, le garçon se retrouve seul et bascule dans Gaza, un bidonville où règnent des bandes d'enfants livrés à eux-mêmes. Plusieurs voix racontent tour à tour cette île française dont on parle si peu.",
    whyRead: [
      "Un roman court et intense sur Mayotte et ses enfants des rues.",
      "Une construction à plusieurs voix, qui éclaire chaque point de vue.",
      "Prix Femina des lycéens 2016.",
    ],
    year: 2016,
    originalLanguage: null,
    publisher: "Folio",
    pages: 192,
    isbn: "9782072764578",
    format: "poche",
    awards: [{ name: "Prix Femina des lycéens", year: 2016 }],
    featured: false,
  },

  // ------------------------------------------------------------------ Madagascar
  {
    ...base,
    slug: "presque-songes",
    title: "Presque-songes",
    contributors: [
      { role: "auteur", name: "Jean-Joseph Rabearivelo", authorSlug: "jean-joseph-rabearivelo" },
    ],
    genre: "poesie",
    audience: "adulte",
    themes: ["contes", "tradition", "identite"],
    summary:
      "Publié à Tananarive en 1934, ce recueil réunit des poèmes en prose que Rabearivelo a écrits en malgache et en français. Les paysages des hautes terres, la nuit, les ancêtres et les mythes de l'île y deviennent des visions presque rêvées. Le poète y cherche une langue neuve, nourrie à la fois de la tradition malgache et de la poésie française moderne. C'est l'un des premiers grands livres de la poésie africaine d'expression française.",
    whyRead: [
      "Un pionnier de la poésie africaine francophone, à redécouvrir.",
      "Des images d'une grande beauté, entre rêve et mythe.",
      "Un recueil bref, qu'on peut lire poème par poème.",
    ],
    year: 1934,
    originalLanguage: null,
    publisher: "Project'Îles",
    pages: 80,
    isbn: "9782493036308",
    format: null,
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "nour-1947",
    title: "Nour, 1947",
    contributors: [{ role: "auteur", name: "Raharimanana", authorSlug: "raharimanana" }],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "guerre", "amour"],
    summary:
      "En 1947, Madagascar se soulève contre la puissance coloniale française, et la répression est terrible. Un homme, réfugié dans la forêt avec d'autres insurgés, veille le corps de Nour, la femme qu'il aimait. Sa voix mêle souvenirs de l'insurrection, mythes fondateurs de l'île et questions sur ce qui a mené au désastre. Un roman-poème sur un épisode longtemps effacé de l'histoire de France.",
    whyRead: [
      "Pour découvrir l'insurrection malgache de 1947.",
      "Une langue poétique et puissante.",
      "Un grand roman de mémoire.",
    ],
    year: 2001,
    originalLanguage: null,
    publisher: "Le Serpent à plumes (Motifs)",
    pages: 264,
    isbn: "9782842614034",
    format: null,
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ Comores
  {
    ...base,
    slug: "anguille-sous-roche",
    title: "Anguille sous roche",
    contributors: [{ role: "auteur", name: "Ali Zamir", authorSlug: "ali-zamir" }],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "exil"],
    summary:
      "En pleine mer, entre les îles des Comores, une jeune femme surnommée Anguille lutte pour ne pas se noyer. Pendant qu'elle se débat, elle raconte sa vie à Anjouan : son père, sa sœur jumelle, son amour pour un garçon, les interdits d'une société qui juge les filles. Le récit tient en une seule phrase, qui coule comme les vagues. Un premier roman d'une énergie folle.",
    whyRead: [
      "Un roman entier en une seule phrase, porté par une voix unique.",
      "Les Comores racontées par une héroïne insolente et libre.",
      "Prix Senghor du premier roman francophone 2016.",
    ],
    year: 2016,
    originalLanguage: null,
    publisher: "Le Tripode",
    pages: null,
    isbn: "9782370550941",
    format: "grand-format",
    awards: [{ name: "Prix Senghor du premier roman francophone", year: 2016 }],
    featured: false,
  },

  // ------------------------------------------------------------------ Kenya
  {
    ...base,
    slug: "rever-en-temps-de-guerre",
    title: "Rêver en temps de guerre",
    subtitle: "Mémoires d'enfance",
    contributors: [
      { role: "auteur", name: "Ngũgĩ wa Thiong'o", authorSlug: "ngugi-wa-thiongo" },
      { role: "traducteur", name: "Jean-Pierre Orban", authorSlug: null },
      { role: "traducteur", name: "Annaëlle Rochard", authorSlug: null },
    ],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "colonisation", "ecole", "famille"],
    summary:
      "Ngũgĩ wa Thiong'o raconte son enfance à Limuru, dans le Kenya colonial des années 1940 et 1950. Il grandit dans une grande famille, entre un père aux nombreuses épouses et une mère qui fait tout pour qu'il aille à l'école. Autour de lui, la Seconde Guerre mondiale puis la révolte des Mau Mau bouleversent la vie des villages. Le récit montre comment un enfant découvre le pouvoir des livres au milieu de la violence.",
    whyRead: [
      "Le premier tome des mémoires d'un géant de la littérature africaine.",
      "Pour comprendre le Kenya colonial et la révolte des Mau Mau.",
      "Un bel hommage à l'école et aux mères.",
    ],
    year: 2010,
    originalLanguage: "anglais",
    publisher: "Project'Îles",
    pages: 300,
    isbn: "9782493036780",
    format: null,
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ Afrique du Sud
  {
    ...base,
    slug: "disgrace",
    title: "Disgrâce",
    contributors: [
      { role: "auteur", name: "J. M. Coetzee", authorSlug: "j-m-coetzee" },
      { role: "traducteur", name: "Catherine Lauga du Plessis", authorSlug: null },
    ],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "famille", "identite"],
    summary:
      "David Lurie, professeur de littérature au Cap, cinquante-deux ans, a une liaison avec une de ses étudiantes. Le scandale éclate et il refuse de s'excuser publiquement. Chassé de l'université, il se réfugie chez sa fille Lucy, qui vit seule dans une ferme de la province du Cap-Oriental. Là, dans l'Afrique du Sud d'après l'apartheid, les rapports entre Blancs et Noirs, hommes et femmes, sont en train de changer.",
    whyRead: [
      "Un roman sec et puissant sur l'Afrique du Sud après l'apartheid.",
      "Deuxième Booker Prize pour son auteur, prix Nobel en 2003.",
      "Un livre qui dérange et fait longtemps réfléchir.",
    ],
    year: 1999,
    originalLanguage: "anglais",
    publisher: "Points",
    pages: 272,
    isbn: "9782020562331",
    format: "poche",
    awards: [{ name: "Booker Prize", year: 1999 }],
    featured: false,
  },
  {
    ...base,
    slug: "un-long-chemin-vers-la-liberte",
    title: "Un long chemin vers la liberté",
    contributors: [
      { role: "auteur", name: "Nelson Mandela", authorSlug: "nelson-mandela" },
      { role: "traducteur", name: "Jean Guiloineau", authorSlug: null },
    ],
    genre: "recit",
    audience: "adulte",
    themes: ["politique", "histoire", "travail"],
    summary:
      "Nelson Mandela raconte sa vie, de son enfance dans un village du Transkei à ses années d'avocat à Johannesburg. Il décrit son engagement dans l'ANC, la lutte contre l'apartheid, puis le passage à la lutte armée. Il consacre une grande partie du livre à ses vingt-sept années de prison, en particulier sur l'île de Robben Island. Un témoignage essentiel sur l'histoire de l'Afrique du Sud au XXᵉ siècle.",
    whyRead: [
      "L'autobiographie d'une des grandes figures du XXᵉ siècle.",
      "Pour comprendre l'apartheid et la lutte pour l'abolir.",
      "Un récit simple, humain, souvent émouvant.",
    ],
    year: 1994,
    originalLanguage: "anglais",
    publisher: "Le Livre de Poche",
    pages: 767,
    isbn: "9782253140634",
    format: "poche",
    awards: [],
    featured: false,
  },

  // ------------------------------------------------------------------ Nigeria
  {
    ...base,
    slug: "le-monde-s-effondre",
    title: "Le monde s'effondre",
    contributors: [
      { role: "auteur", name: "Chinua Achebe", authorSlug: "chinua-achebe" },
      { role: "traducteur", name: "Michel Ligny", authorSlug: null },
    ],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "tradition", "spiritualite", "famille"],
    summary:
      "Okonkwo est un homme respecté d'Umuofia, un groupe de villages igbo du Nigeria. Lutteur réputé et cultivateur acharné, il a bâti sa vie contre le souvenir d'un père jugé faible. Mais une faute grave l'oblige à quitter son village pour plusieurs années. Pendant ce temps, les missionnaires et l'administration britannique arrivent, et l'ordre ancien commence à vaciller.",
    whyRead: [
      "Le roman africain le plus lu au monde, fondateur.",
      "Une société igbo décrite de l'intérieur, avant la colonisation.",
      "Un héros tragique, complexe et inoubliable.",
    ],
    year: 1958,
    originalLanguage: "anglais",
    publisher: "Présence Africaine",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
    featured: false,
  },
  {
    ...base,
    slug: "l-autre-moitie-du-soleil",
    title: "L'Autre Moitié du soleil",
    contributors: [
      { role: "auteur", name: "Chimamanda Ngozi Adichie", authorSlug: "chimamanda-ngozi-adichie" },
      { role: "traducteur", name: "Mona de Pracontal", authorSlug: null },
    ],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "amour", "histoire", "famille"],
    summary:
      "Au début des années 1960, à Nsukka, dans le sud-est du Nigeria, Ugwu, treize ans, devient le domestique d'un professeur passionné de politique. Il découvre le monde de son maître et de sa compagne Olanna, belle et cultivée, dont la sœur jumelle Kainene fréquente un Anglais timide. Quand le Biafra fait sécession en 1967, la guerre civile bouleverse la vie de ces personnages. Un grand roman sur l'amour et la guerre.",
    whyRead: [
      "Pour découvrir la guerre du Biafra, souvent oubliée.",
      "Des personnages attachants dont on suit le destin pendant des années.",
      "Orange Prize 2007, le roman qui a révélé Adichie.",
    ],
    year: 2006,
    originalLanguage: "anglais",
    publisher: "Folio",
    pages: 663,
    isbn: "9782072722479",
    format: "poche",
    awards: [{ name: "Orange Prize for Fiction", year: 2007 }],
    featured: false,
  },

  // ------------------------------------------------------------------ Ghana
  {
    ...base,
    slug: "no-home",
    title: "No Home",
    contributors: [
      { role: "auteur", name: "Yaa Gyasi", authorSlug: "yaa-gyasi" },
      { role: "traducteur", name: "Anne Damour", authorSlug: null },
    ],
    genre: "roman",
    audience: "adulte",
    themes: ["esclavage", "famille", "exil", "histoire"],
    summary:
      "Au XVIIIᵉ siècle, sur la Côte-de-l'Or, deux demi-sœurs qui ne se connaissent pas connaissent des destins opposés. Effia épouse le gouverneur anglais du fort de Cape Coast ; Esi est enfermée dans les cachots du même fort, avant d'être déportée en Amérique. Chaque chapitre suit un de leurs descendants, génération après génération, d'un côté et de l'autre de l'Atlantique. Trois siècles d'histoire se dessinent ainsi, du Ghana à Harlem.",
    whyRead: [
      "Une construction brillante : deux lignées, un chapitre par génération.",
      "L'esclavage et ses suites, des deux côtés de l'Atlantique.",
      "Un premier roman salué dans le monde entier.",
    ],
    year: 2016,
    originalLanguage: "anglais",
    publisher: "Calmann-Lévy",
    pages: null,
    isbn: "9782702159637",
    format: "grand-format",
    awards: [{ name: "PEN/Hemingway Award", year: 2017 }],
    featured: false,
  },
];
