import type { Book } from "../types";

/** Champs communs aux fiches de ce fichier (remplis plus tard à la main : ASIN, prix, couverture). */
type Saisie = Omit<Book, "kind" | "subtitle" | "originalLanguage" | "amazonAsin" | "priceCents" | "cover" | "addedAt" | "isPublished" | "featured"> &
  Partial<Pick<Book, "subtitle" | "featured">>;

const livre = (b: Saisie): Book => ({
  kind: "livre",
  subtitle: null,
  originalLanguage: null,
  amazonAsin: null,
  priceCents: null,
  cover: null,
  featured: false,
  addedAt: "2026-09-28",
  isPublished: true,
  ...b,
});

const auteur = (name: string, authorSlug: string) => ({ role: "auteur" as const, name, authorSlug });

export const livresOuest: Book[] = [
  // ------------------------------------------------------------------ Sénégal
  livre({
    slug: "une-si-longue-lettre",
    title: "Une si longue lettre",
    contributors: [auteur("Mariama Bâ", "mariama-ba")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "famille", "tradition", "amour"],
    summary:
      "À Dakar, Ramatoulaye vient de perdre son mari, Modou, qui l'avait délaissée quelques années plus tôt pour épouser une très jeune femme. Pendant les jours de deuil imposés par la tradition, elle écrit à son amie d'enfance Aïssatou, installée aux États-Unis. Au fil de cette longue lettre, elle revient sur leurs mariages, leurs espoirs de jeunes femmes instruites et la blessure de la polygamie. C'est le portrait intime d'une femme qui fait le bilan de sa vie et se demande comment rester debout.",
    whyRead: [
      "Un classique court et bouleversant, lu dans les lycées de toute l'Afrique francophone.",
      "Une voix de femme qui parle franchement du mariage, de la polygamie et de la liberté.",
      "Une porte d'entrée idéale dans la littérature sénégalaise.",
    ],
    quote: null,
    year: 1979,
    publisher: "Le Serpent à plumes",
    pages: 164,
    isbn: "9782842612894",
    format: "poche",
    awards: [{ name: "Prix Noma", year: 1980 }],
    featured: true,
  }),
  livre({
    slug: "l-aventure-ambigue",
    title: "L'Aventure ambiguë",
    contributors: [auteur("Cheikh Hamidou Kane", "cheikh-hamidou-kane")],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "tradition", "spiritualite", "ecole"],
    summary:
      "Samba Diallo grandit au pays des Diallobé, dans une école coranique où son maître exige de lui une ferveur absolue. Mais la famille noble à laquelle il appartient doit trancher une question brûlante : faut-il envoyer les enfants à l'école des Blancs, au risque de les voir oublier qui ils sont ? Samba part, jusqu'à Paris, pour apprendre « l'art de vaincre sans avoir raison ». Le roman suit ce jeune homme partagé entre deux mondes, la foi de son enfance et la pensée occidentale.",
    whyRead: [
      "Un grand roman philosophique sur le choc entre tradition et modernité.",
      "Une langue d'une grande beauté, presque méditative.",
      "Une question toujours actuelle : que perd-on en gagnant un autre savoir ?",
    ],
    quote: null,
    year: 1961,
    publisher: "10/18",
    pages: 191,
    isbn: "9782264036933",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1962 }],
  }),
  livre({
    slug: "les-bouts-de-bois-de-dieu",
    title: "Les Bouts de bois de Dieu",
    contributors: [auteur("Ousmane Sembène", "ousmane-sembene")],
    genre: "roman",
    audience: "adulte",
    themes: ["travail", "colonisation", "femmes", "histoire"],
    summary:
      "En 1947, les cheminots africains de la ligne Dakar-Niger se mettent en grève pour obtenir les mêmes droits que leurs collègues européens. Le roman passe de Bamako à Thiès et à Dakar, et suit les ouvriers, leurs familles et la compagnie qui refuse de céder. À mesure que la grève dure et que la faim s'installe, ce sont souvent les femmes qui tiennent les foyers et prennent la parole. Une fresque collective inspirée d'une grève bien réelle.",
    whyRead: [
      "Un grand roman social, inspiré de la grève des cheminots de 1947-1948.",
      "Des personnages de femmes inoubliables, au cœur de la lutte.",
      "Par l'un des pères du cinéma africain, qui écrit comme il filme.",
    ],
    quote: null,
    year: 1960,
    publisher: "Pocket",
    pages: 416,
    isbn: "9782266245814",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "ethiopiques",
    title: "Éthiopiques",
    contributors: [auteur("Léopold Sédar Senghor", "leopold-sedar-senghor")],
    genre: "poesie",
    audience: "adulte",
    themes: ["identite", "amour", "tradition"],
    summary:
      "Ce recueil réunit des poèmes où Senghor chante l'Afrique, ses paysages, ses rois et ses femmes, souvent pour être dits avec l'accompagnement d'instruments (kôras, balafong, tam-tams). On y trouve notamment « Chaka », poème dramatique consacré au roi zoulou, et « À New York », où le poète confronte la ville moderne au rythme de l'Afrique. Le livre se termine par une postface où Senghor explique sa conception d'une poésie faite pour être chantée. C'est l'un des recueils essentiels de la négritude.",
    whyRead: [
      "Des poèmes à lire à voix haute, pleins de rythme et d'images.",
      "Pour comprendre la négritude à travers son plus célèbre poète.",
      "« À New York », un poème qui n'a pas pris une ride.",
    ],
    quote: null,
    year: 1956,
    publisher: "Seuil",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "la-plus-secrete-memoire-des-hommes",
    title: "La plus secrète mémoire des hommes",
    contributors: [auteur("Mohamed Mbougar Sarr", "mohamed-mbougar-sarr")],
    genre: "roman",
    audience: "adulte",
    themes: ["identite", "histoire", "exil", "colonisation"],
    summary:
      "À Paris, Diégane Latyr Faye, jeune écrivain sénégalais, découvre un livre culte et introuvable paru en 1938, « Le Labyrinthe de l'inhumain », signé T. C. Elimane. Son auteur, surnommé en son temps « le Rimbaud nègre », a disparu après un scandale. Fasciné, Diégane se lance sur ses traces, du Sénégal à la France et jusqu'en Argentine. L'enquête traverse un siècle d'histoire et pose une question vertigineuse : qu'est-ce qu'écrire, et à quel prix ?",
    whyRead: [
      "Le premier Goncourt attribué à un écrivain d'Afrique subsaharienne.",
      "Une enquête littéraire haletante, entre roman policier et roman d'idées.",
      "Un hommage à la littérature et à ceux qu'elle a oubliés.",
    ],
    quote: null,
    year: 2021,
    publisher: "Le Livre de Poche",
    pages: 576,
    isbn: "9782253937715",
    format: "poche",
    awards: [{ name: "Prix Goncourt", year: 2021 }],
    featured: true,
  }),
  livre({
    slug: "le-ventre-de-l-atlantique",
    title: "Le Ventre de l'Atlantique",
    contributors: [auteur("Fatou Diome", "fatou-diome")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "famille", "identite"],
    summary:
      "Salie a quitté l'île de Niodior, au Sénégal, pour vivre à Strasbourg. Au téléphone, son petit frère Madické ne rêve que d'une chose : devenir footballeur en France, comme les idoles qu'il regarde à la télévision. Pour les gens du village, l'Europe est un paradis où l'argent se ramasse à la pelle. Salie, qui connaît la solitude et les petits boulots de l'exil, tente de lui faire entendre une autre réalité, sans briser son rêve.",
    whyRead: [
      "Un roman drôle et amer sur le mirage de l'Europe.",
      "Le regard d'une femme partagée entre deux rives.",
      "Une écriture vive, pleine d'humour et de tendresse.",
    ],
    quote: null,
    year: 2003,
    publisher: "Le Livre de Poche",
    pages: null,
    isbn: "9782253109075",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "murambi-le-livre-des-ossements",
    title: "Murambi, le livre des ossements",
    contributors: [auteur("Boubacar Boris Diop", "boubacar-boris-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["genocide", "histoire", "guerre"],
    summary:
      "Quatre ans après le génocide des Tutsi au Rwanda, Cornelius revient dans son pays après un long exil à Djibouti. Il se rend à Murambi, une école où des milliers de personnes ont été massacrées et où les corps sont désormais exposés. Le roman alterne ses pas avec les voix de ceux qui ont vécu 1994 : victimes, témoins, bourreaux. Peu à peu, Cornelius découvre la part que sa propre famille a prise dans les tueries.",
    whyRead: [
      "Un roman essentiel pour comprendre le génocide des Tutsi au Rwanda.",
      "Né d'une résidence d'écrivains africains au Rwanda en 1998.",
      "Une écriture sobre, à plusieurs voix, qui ne détourne pas le regard.",
    ],
    quote: null,
    year: 2000,
    publisher: "Zulma",
    pages: 224,
    isbn: "9782843049668",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "la-greve-des-battu",
    title: "La Grève des bàttu",
    subtitle: "ou les déchets humains",
    contributors: [auteur("Aminata Sow Fall", "aminata-sow-fall")],
    genre: "roman",
    audience: "adulte",
    themes: ["politique", "humour", "ville", "spiritualite"],
    summary:
      "À Dakar, Mour Ndiaye, haut fonctionnaire ambitieux, veut débarrasser la ville de ses mendiants, jugés mauvais pour le tourisme. Les rafles se multiplient et les mendiants sont chassés loin du centre. Mais ceux-ci s'organisent et décident à leur tour de faire grève. Or Mour a justement besoin d'eux : un marabout lui a prescrit de faire l'aumône pour obtenir le poste de vice-président qu'il convoite.",
    whyRead: [
      "Une satire savoureuse du pouvoir et de l'hypocrisie sociale.",
      "Un renversement de situation plein d'humour.",
      "Par une grande dame des lettres sénégalaises.",
    ],
    quote: null,
    year: 1979,
    publisher: "Le Serpent à plumes",
    pages: 167,
    isbn: "9782842612504",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1980 }],
  }),
  livre({
    slug: "frere-d-ame",
    title: "Frère d'âme",
    contributors: [auteur("David Diop", "david-diop")],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "colonisation", "identite"],
    summary:
      "Pendant la Première Guerre mondiale, Alfa Ndiaye, tirailleur sénégalais, voit mourir dans ses bras son ami d'enfance Mademba Diop, son « plus que frère ». Rongé par la culpabilité, Alfa ne se bat plus seulement pour la France : dans les tranchées, il devient un combattant redouté, même par ses camarades. De cette voix intérieure surgissent aussi les souvenirs du village, de l'amitié et de l'amour. Un court roman d'une intensité rare sur la guerre et la folie.",
    whyRead: [
      "Un roman bref et saisissant sur les tirailleurs sénégalais de 14-18.",
      "Une voix hypnotique, qui répète et envoûte comme un chant.",
      "Couronné en France comme à l'étranger, notamment par l'International Booker Prize.",
    ],
    quote: null,
    year: 2018,
    publisher: "Points",
    pages: null,
    isbn: "9782757875964",
    format: "poche",
    awards: [
      { name: "Prix Goncourt des lycéens", year: 2018 },
      { name: "Prix Ahmadou-Kourouma", year: 2019 },
      { name: "International Booker Prize", year: 2021 },
    ],
  }),
  livre({
    slug: "les-contes-d-amadou-koumba",
    title: "Les Contes d'Amadou Koumba",
    contributors: [auteur("Birago Diop", "birago-diop")],
    genre: "contes",
    audience: "adulte",
    themes: ["contes", "tradition"],
    summary:
      "Birago Diop met par écrit des contes qu'il a entendus enfant, notamment de la bouche d'Amadou Koumba, le griot de sa famille. On y croise Leuk-le-Lièvre, malin entre tous, Bouki-l'Hyène, gourmande et bête, mais aussi des génies, des rois et des hommes ordinaires. Chaque histoire, drôle ou cruelle, porte une leçon de sagesse. Le recueil fait passer dans la langue française la saveur de la parole des veillées wolof.",
    whyRead: [
      "Des contes courts, à lire seul ou à raconter.",
      "Un classique qui a fait entrer la tradition orale africaine en littérature.",
      "Humour, animaux rusés et sagesse populaire.",
    ],
    quote: null,
    year: 1947,
    publisher: "Présence Africaine",
    pages: 187,
    isbn: "9782708701670",
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-baobab-fou",
    title: "Le Baobab fou",
    contributors: [auteur("Ken Bugul", "ken-bugul")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "identite", "enfance"],
    summary:
      "Une petite fille grandit dans un village du Ndoucoumane, au Sénégal, marquée par le départ de sa mère. Élève brillante à l'école française, elle part étudier en Belgique, persuadée de retrouver en Europe une famille et une identité. À Bruxelles, dans les années 1970, elle découvre au contraire la solitude, les faux-semblants et une dérive de plus en plus violente. Un récit très autobiographique, qui a marqué par sa franchise.",
    whyRead: [
      "Un premier livre d'une sincérité rare, sur l'exil d'une jeune femme.",
      "Une des premières autrices africaines à parler si librement du corps et du désir.",
      "Une écriture fiévreuse, qui ne ressemble à aucune autre.",
    ],
    quote: null,
    year: 1982,
    publisher: "Présence Africaine",
    pages: 226,
    isbn: "9782708708037",
    format: null,
    awards: [],
  }),
  livre({
    slug: "trois-femmes-puissantes",
    title: "Trois femmes puissantes",
    contributors: [auteur("Marie NDiaye", "marie-ndiaye")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "exil", "famille"],
    summary:
      "Trois récits, trois femmes, entre la France et l'Afrique. Norah, avocate parisienne, est appelée au Sénégal par un père qui l'a toujours tenue à distance. Fanta a quitté Dakar pour suivre son mari en France, et c'est de son point de vue à lui que l'on découvre leur vie. Khady, jeune veuve sans enfant, est poussée sur les routes de l'exil. Chacune, face à l'humiliation, trouve une manière de rester digne.",
    whyRead: [
      "Prix Goncourt 2009 : un roman majeur de la littérature française contemporaine.",
      "Trois portraits de femmes qui refusent de plier.",
      "Une écriture ample, précise, d'une grande force.",
    ],
    quote: null,
    year: 2009,
    publisher: "Folio",
    pages: null,
    isbn: "9782070440498",
    format: "poche",
    awards: [{ name: "Prix Goncourt", year: 2009 }],
  }),
  livre({
    slug: "afrotopia",
    title: "Afrotopia",
    contributors: [auteur("Felwine Sarr", "felwine-sarr")],
    genre: "essai",
    audience: "adulte",
    themes: ["identite", "politique", "tradition"],
    summary:
      "Et si l'Afrique cessait de se mesurer à l'Occident et au seul critère de la croissance économique ? L'économiste et écrivain Felwine Sarr invite le continent à penser son avenir à partir de ses propres ressources : ses langues, ses cultures, ses manières de vivre ensemble. Il propose de sortir du discours du « retard » pour imaginer une utopie concrète, une « Afrotopia ». Un essai court et stimulant, qui a eu un large écho.",
    whyRead: [
      "Un essai clair et optimiste sur l'avenir de l'Afrique.",
      "Pour sortir des clichés sur le « développement ».",
      "Une lecture qui nourrit le débat, bien au-delà du continent.",
    ],
    quote: null,
    year: 2016,
    publisher: "Philippe Rey",
    pages: 192,
    isbn: "9782848765020",
    format: "grand-format",
    awards: [],
  }),
  livre({
    slug: "nations-negres-et-culture",
    title: "Nations nègres et culture",
    contributors: [auteur("Cheikh Anta Diop", "cheikh-anta-diop")],
    genre: "essai",
    audience: "adulte",
    themes: ["histoire", "identite", "colonisation"],
    summary:
      "Dans ce livre fondateur, Cheikh Anta Diop soutient que l'Égypte ancienne était une civilisation africaine noire et que l'histoire de l'Afrique a été effacée par le regard colonial. Il s'appuie sur l'histoire, la linguistique et l'anthropologie pour retracer les liens entre l'Égypte et le reste du continent. Il y défend aussi l'idée que les langues africaines peuvent exprimer la science et la philosophie. L'ouvrage a profondément marqué la pensée africaine du XXe siècle.",
    whyRead: [
      "Un livre qui a changé le regard de toute une génération sur l'histoire africaine.",
      "Pour comprendre les débats qui entourent encore aujourd'hui Cheikh Anta Diop.",
      "Un classique de la pensée panafricaine.",
    ],
    quote: null,
    year: 1954,
    publisher: "Présence Africaine",
    pages: null,
    isbn: "9782708706880",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Mali
  livre({
    slug: "amkoullel-l-enfant-peul",
    title: "Amkoullel, l'enfant peul",
    contributors: [auteur("Amadou Hampâté Bâ", "amadou-hampate-ba")],
    genre: "recit",
    audience: "adulte",
    themes: ["enfance", "tradition", "colonisation", "ecole"],
    summary:
      "Amadou Hampâté Bâ raconte son enfance et sa jeunesse au Mali, au début du XXe siècle, alors que le pays passe sous domination française. Surnommé Amkoullel, il grandit entre sa famille peule, les récits des anciens, l'école coranique puis l'école des Blancs, où il est envoyé de force. Son monde est peuplé de griots, de chefs, de marabouts et de bandes d'enfants espiègles. Le premier tome de ses mémoires est aussi un portrait vivant de toute une société.",
    whyRead: [
      "Des mémoires passionnants, racontés avec l'art d'un conteur.",
      "Un témoignage unique sur l'Afrique de l'Ouest au début de la colonisation.",
      "Plein d'humour, d'anecdotes et de sagesse.",
    ],
    quote: null,
    year: 1991,
    publisher: "Babel",
    pages: null,
    isbn: "9782868699060",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "l-etrange-destin-de-wangrin",
    title: "L'Étrange Destin de Wangrin",
    subtitle: "ou les roueries d'un interprète africain",
    contributors: [auteur("Amadou Hampâté Bâ", "amadou-hampate-ba")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "humour", "politique"],
    summary:
      "Au temps de l'Afrique-Occidentale française, Wangrin devient interprète auprès des administrateurs coloniaux. Placé entre les Blancs, qui ne comprennent pas la langue, et les Africains, qui ne connaissent pas les règles des colons, il tire parti de cette position pour s'enrichir. Ruses, intrigues et coups de génie s'enchaînent, au détriment des puissants de tous bords. Hampâté Bâ assure avoir recueilli cette histoire de la bouche même de son héros.",
    whyRead: [
      "Un roman picaresque, drôle et malicieux.",
      "Une satire fine de l'administration coloniale.",
      "Un héros inoubliable, aussi génial que sans scrupules.",
    ],
    quote: null,
    year: 1973,
    publisher: "10/18",
    pages: null,
    isbn: "9782264017581",
    format: "poche",
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 1974 }],
  }),
  livre({
    slug: "le-devoir-de-violence",
    title: "Le Devoir de violence",
    contributors: [auteur("Yambo Ouologuem", "yambo-ouologuem")],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "politique", "colonisation", "esclavage"],
    summary:
      "Dans le royaume imaginaire du Nakem, la dynastie des Saïfs règne depuis des siècles par la terreur, l'esclavage et la ruse. Quand les colons français arrivent, les Saïfs s'arrangent avec eux pour garder leur pouvoir. Le roman suit cette longue histoire jusqu'au XXe siècle, où le jeune Raymond Spartacus Kassoumi part étudier en France. Ouologuem y bouscule l'image d'une Afrique précoloniale idéalisée.",
    whyRead: [
      "Un roman provocant, qui a fait scandale à sa sortie.",
      "Une vision de l'histoire africaine sans complaisance.",
      "Premier roman africain couronné par le prix Renaudot.",
    ],
    quote: null,
    year: 1968,
    publisher: "Seuil",
    pages: 304,
    isbn: "9782021341775",
    format: null,
    awards: [{ name: "Prix Renaudot", year: 1968 }],
  }),

  // ------------------------------------------------------------------ Guinée
  livre({
    slug: "l-enfant-noir",
    title: "L'Enfant noir",
    contributors: [auteur("Camara Laye", "camara-laye")],
    genre: "roman",
    audience: "ado",
    themes: ["enfance", "famille", "tradition", "ecole"],
    summary:
      "Depuis Paris, Camara Laye se souvient de son enfance à Kouroussa, en Haute-Guinée. Il y a son père, forgeron et orfèvre, dont le travail de l'or tient presque de la magie, sa mère aux pouvoirs mystérieux, les séjours chez ses oncles à la campagne, les rites de passage et l'école. À mesure qu'il grandit, les études l'éloignent de plus en plus de sa famille et de son village. Un récit tendre et lumineux sur l'enfance et le départ.",
    whyRead: [
      "Un classique étudié au collège, simple et émouvant.",
      "Un portrait magnifique d'un père et d'une mère.",
      "Pour découvrir la vie d'un village malinké dans les années 1930.",
    ],
    quote: null,
    year: 1953,
    publisher: "Pocket",
    pages: 221,
    isbn: "9782266178945",
    format: "poche",
    awards: [{ name: "Prix Charles-Veillon", year: 1954 }],
    featured: true,
  }),
  livre({
    slug: "le-roi-de-kahel",
    title: "Le Roi de Kahel",
    contributors: [auteur("Tierno Monénembo", "tierno-monenembo")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "histoire", "humour"],
    summary:
      "À la fin du XIXe siècle, Aimé Olivier de Sanderval, aventurier lyonnais, se met en tête de conquérir le Fouta-Djalon, en Guinée, pour s'y tailler un royaume. Il y part à ses frais, sans armée, et doit négocier pied à pied avec les princes peuls, aussi rusés que lui. Monénembo s'inspire de ce personnage réel pour raconter, avec ironie, l'aube de la colonisation. Le roman montre la rencontre de deux mondes, vue autant du côté peul que du côté français.",
    whyRead: [
      "Un roman d'aventures inspiré d'une histoire vraie.",
      "Un regard ironique et nuancé sur les débuts de la colonisation.",
      "Prix Renaudot 2008.",
    ],
    quote: null,
    year: 2008,
    publisher: "Points",
    pages: null,
    isbn: "9782757814611",
    format: "poche",
    awards: [{ name: "Prix Renaudot", year: 2008 }],
  }),
  livre({
    slug: "soundjata-ou-l-epopee-mandingue",
    title: "Soundjata ou l'Épopée mandingue",
    contributors: [auteur("Djibril Tamsir Niane", "djibril-tamsir-niane")],
    genre: "recit",
    audience: "ado",
    themes: ["contes", "histoire", "tradition"],
    summary:
      "Au XIIIe siècle, Soundjata Keïta naît infirme et moqué, fils d'un roi mandingue et d'une femme laide mais promise à un grand destin. Contraint à l'exil par la rivalité de la première épouse du roi, il revient un jour affronter Soumaoro Kanté, le terrible roi-sorcier du Sosso. Djibril Tamsir Niane transcrit en français le récit du griot Mamadou Kouyaté, gardien de cette mémoire. C'est l'histoire de la fondation de l'empire du Mali.",
    whyRead: [
      "La grande épopée de l'Afrique de l'Ouest, transmise par les griots.",
      "Un récit captivant, entre histoire, magie et héroïsme.",
      "Idéal pour découvrir la tradition orale mandingue.",
    ],
    quote: null,
    year: 1960,
    publisher: "Présence Africaine",
    pages: null,
    isbn: "9782708700789",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Côte d'Ivoire
  livre({
    slug: "les-soleils-des-independances",
    title: "Les Soleils des indépendances",
    contributors: [auteur("Ahmadou Kourouma", "ahmadou-kourouma")],
    genre: "roman",
    audience: "adulte",
    themes: ["independances", "politique", "tradition", "humour"],
    summary:
      "Fama Doumbouya, dernier prince d'une lignée malinké, a tout perdu avec les indépendances : ni pouvoir, ni richesse, ni même d'héritier. Réduit à courir les funérailles de la capitale pour vivre des aumônes, il rumine sa colère contre le parti unique et contre son épouse Salimata, qui ne lui donne pas d'enfant. Le retour au village natal et les intrigues politiques vont bousculer sa vie. Kourouma y invente un français nourri des tournures du malinké.",
    whyRead: [
      "Le roman qui a révolutionné la langue française en Afrique.",
      "Une satire mordante des lendemains des indépendances.",
      "Un héros pathétique et attachant.",
    ],
    quote: null,
    year: 1968,
    publisher: "Points",
    pages: null,
    isbn: "9782020259217",
    format: "poche",
    awards: [],
  }),
  livre({
    slug: "allah-n-est-pas-oblige",
    title: "Allah n'est pas obligé",
    contributors: [auteur("Ahmadou Kourouma", "ahmadou-kourouma")],
    genre: "roman",
    audience: "adulte",
    themes: ["guerre", "enfance", "humour", "politique"],
    summary:
      "Birahima, une dizaine d'années, a quitté l'école tôt et parle un français bien à lui, qu'il vérifie dans quatre dictionnaires. Orphelin, il part avec le féticheur Yacouba chercher sa tante au Liberia. En chemin, il devient enfant-soldat et traverse les guerres civiles du Liberia et de la Sierra Leone. Il raconte ce qu'il voit avec un mélange d'insolence et de naïveté qui rend l'horreur encore plus frappante.",
    whyRead: [
      "Une voix d'enfant inoubliable, drôle et terrible à la fois.",
      "Un roman fort sur les enfants-soldats.",
      "Prix Renaudot et Goncourt des lycéens 2000.",
    ],
    quote: null,
    year: 2000,
    publisher: "Points",
    pages: null,
    isbn: "9782020525718",
    format: "poche",
    awards: [
      { name: "Prix Renaudot", year: 2000 },
      { name: "Prix Goncourt des lycéens", year: 2000 },
    ],
    featured: true,
  }),
  livre({
    slug: "reine-pokou",
    title: "Reine Pokou",
    subtitle: "Concerto pour un sacrifice",
    contributors: [auteur("Véronique Tadjo", "veronique-tadjo")],
    genre: "roman",
    audience: "adulte",
    themes: ["contes", "femmes", "histoire", "politique"],
    summary:
      "Selon la légende, la reine Abraha Pokou, fuyant avec son peuple, sacrifia son enfant pour franchir un fleuve : ainsi serait né le peuple baoulé de Côte d'Ivoire. Véronique Tadjo reprend ce mythe fondateur et en propose plusieurs versions, en variant les points de vue. Elle interroge le sens de ce sacrifice et fait écho à la Côte d'Ivoire déchirée du début des années 2000. Un livre bref, poétique et grave.",
    whyRead: [
      "Un mythe ivoirien célèbre, raconté de plusieurs façons.",
      "Un texte court, entre poésie et conte.",
      "Une réflexion sur le pouvoir et la violence faite au nom du peuple.",
    ],
    quote: null,
    year: 2005,
    publisher: "Actes Sud",
    pages: 90,
    isbn: "9782742753970",
    format: null,
    awards: [{ name: "Grand prix littéraire d'Afrique noire", year: 2005 }],
  }),
  livre({
    slug: "climbie",
    title: "Climbié",
    contributors: [auteur("Bernard Dadié", "bernard-dadie")],
    genre: "roman",
    audience: "adulte",
    themes: ["colonisation", "ecole", "enfance", "politique"],
    summary:
      "Climbié grandit en Côte d'Ivoire sous la colonisation française. À l'école, on punit ceux qui parlent leur langue maternelle en leur faisant porter un « symbole ». Devenu adulte et fonctionnaire, il découvre les injustices de l'administration coloniale et s'engage peu à peu dans la lutte politique. Dadié s'inspire largement de sa propre vie dans ce roman d'apprentissage.",
    whyRead: [
      "Un roman autobiographique sur l'école et la vie sous la colonisation.",
      "Par une grande figure de la littérature et de la politique ivoiriennes.",
      "Un témoignage sobre et sans haine.",
    ],
    quote: null,
    year: 1956,
    publisher: "Seghers",
    pages: null,
    isbn: null,
    format: null,
    awards: [],
  }),
  livre({
    slug: "le-pagne-noir",
    title: "Le Pagne noir",
    subtitle: "Contes africains",
    contributors: [auteur("Bernard Dadié", "bernard-dadie")],
    genre: "contes",
    audience: "jeunesse",
    themes: ["contes", "tradition"],
    summary:
      "Ce recueil rassemble des contes de Côte d'Ivoire, où Kacou Ananzè, l'araignée rusée et gourmande, joue des tours à tous les animaux, souvent à ses dépens. On y trouve aussi le conte qui donne son titre au livre : une orpheline maltraitée par sa marâtre doit laver un pagne noir jusqu'à ce qu'il devienne blanc. Chaque histoire se lit en quelques minutes et porte une morale. Un classique des bibliothèques d'école.",
    whyRead: [
      "Des contes courts, parfaits pour la lecture du soir.",
      "Ananzè l'araignée, un héros aussi drôle que malin.",
      "Un classique lu par des générations d'écoliers.",
    ],
    quote: null,
    year: 1955,
    publisher: "Présence Africaine",
    pages: 158,
    isbn: "9782708700253",
    format: null,
    awards: [],
  }),
  livre({
    slug: "debout-paye",
    title: "Debout-payé",
    contributors: [auteur("Gauz", "gauz")],
    genre: "roman",
    audience: "adulte",
    themes: ["travail", "exil", "humour", "ville"],
    summary:
      "Ossiri, étudiant ivoirien arrivé sans papiers à Paris, devient vigile de magasin : un « debout-payé », payé pour rester debout. Entre deux chapitres sur son parcours et celui des générations d'Ivoiriens venus avant lui, il note ses observations sur les clients de Sephora ou de Camaïeu. Ces petites scènes, drôles et cruelles, dessinent un portrait décapant de la société de consommation. Le roman raconte aussi l'histoire de l'immigration africaine en France, des années 1960 à nos jours.",
    whyRead: [
      "Un roman très drôle, à l'œil aiguisé.",
      "Un regard neuf sur Paris, vu par un vigile.",
      "Une histoire de l'immigration ivoirienne racontée avec légèreté.",
    ],
    quote: null,
    year: 2014,
    publisher: "Le Livre de Poche",
    pages: 216,
    isbn: "9782253185550",
    format: "poche",
    awards: [],
  }),

  // ------------------------------------------------------------------ Mauritanie
  livre({
    slug: "le-tambour-des-larmes",
    title: "Le Tambour des larmes",
    contributors: [auteur("Mbarek Ould Beyrouk", "mbarek-ould-beyrouk")],
    genre: "roman",
    audience: "adulte",
    themes: ["femmes", "tradition", "ville"],
    summary:
      "Rayhana, jeune femme d'une tribu nomade du désert mauritanien, a aimé un jeune homme venu de la ville, puis a été forcée par les siens de se séparer de l'enfant né de cette liaison. Promise à un mariage arrangé, elle s'enfuit, emportant le tambour sacré de la tribu, symbole de son honneur. Poursuivie, elle gagne la ville, cherche son fils et se confronte à un monde qui lui est inconnu. Un roman sur la liberté des femmes face au poids du clan.",
    whyRead: [
      "Une héroïne courageuse, en lutte contre les traditions de sa tribu.",
      "Une porte d'entrée dans la littérature mauritanienne.",
      "Prix Ahmadou-Kourouma 2016.",
    ],
    quote: null,
    year: 2015,
    publisher: "Elyzad",
    pages: 248,
    isbn: "9789973581150",
    format: null,
    awards: [{ name: "Prix Ahmadou-Kourouma", year: 2016 }],
  }),

  // ------------------------------------------------------------------ Burkina Faso
  livre({
    slug: "crepuscule-des-temps-anciens",
    title: "Crépuscule des temps anciens",
    contributors: [auteur("Nazi Boni", "nazi-boni")],
    genre: "roman",
    audience: "adulte",
    themes: ["histoire", "tradition", "spiritualite"],
    summary:
      "Le roman fait revivre le Bwamu, pays des Bwa, à l'ouest de l'actuel Burkina Faso, avant l'arrivée des Européens. Autour du héros Térhé et de sa communauté, on découvre les rites, les fêtes, les guerres et les amours d'une société villageoise. L'auteur mêle récit romanesque et description presque ethnographique de coutumes qu'il voit disparaître. C'est le premier roman de l'histoire du Burkina Faso.",
    whyRead: [
      "Le premier roman burkinabè.",
      "Un voyage dans une société ouest-africaine d'avant la colonisation.",
      "Un témoignage précieux sur la culture bwa.",
    ],
    quote: null,
    year: 1962,
    publisher: "Présence Africaine",
    pages: null,
    isbn: "9782708705760",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Bénin
  livre({
    slug: "un-piege-sans-fin",
    title: "Un piège sans fin",
    contributors: [auteur("Olympe Bhêly-Quenum", "olympe-bhely-quenum")],
    genre: "roman",
    audience: "adulte",
    themes: ["famille", "amour", "tradition"],
    summary:
      "Ahouna, fils d'un éleveur respecté du nord du Dahomey, connaît une jeunesse heureuse avant que la colonisation et les malheurs ne frappent sa famille. Plus tard, marié et père, il voit son bonheur rongé par la jalousie de son épouse. Une succession d'événements l'entraîne alors dans une spirale dont il ne parvient pas à sortir. Un roman sombre sur le destin et l'injustice.",
    whyRead: [
      "Un grand classique de la littérature béninoise.",
      "Un roman tragique, à la manière d'une fatalité antique.",
      "Une peinture sensible de la vie rurale au Dahomey.",
    ],
    quote: null,
    year: 1960,
    publisher: "Présence Africaine",
    pages: 284,
    isbn: "9782708704558",
    format: null,
    awards: [],
  }),

  // ------------------------------------------------------------------ Togo
  livre({
    slug: "place-des-fetes",
    title: "Place des fêtes",
    contributors: [auteur("Sami Tchak", "sami-tchak")],
    genre: "roman",
    audience: "adulte",
    themes: ["exil", "identite", "famille", "humour"],
    summary:
      "Le narrateur, né en banlieue parisienne de parents africains, se lance dans un long monologue sans filtre. Il y déballe l'histoire de sa famille, du « pays » qu'il ne connaît qu'à travers eux, et sa propre vie de jeune homme entre la France et l'Afrique. Rien n'est épargné : sexe, argent, hypocrisies des uns et des autres. Un roman cru et provocateur, qui démonte les clichés sur l'Afrique et l'immigration.",
    whyRead: [
      "Un roman iconoclaste, qui ose tout dire.",
      "Une voix de la deuxième génération, entre colère et humour noir.",
      "Pour lecteurs avertis qui aiment être bousculés.",
    ],
    quote: null,
    year: 2001,
    publisher: "Gallimard",
    pages: null,
    isbn: "9782070760114",
    format: "grand-format",
    awards: [],
  }),
];
